:PROPERTIES:
:ID:       662a4e02-1771-46bf-8664-baab8d09171a
:END:
#+TITLE: Using Caffeine to Optimize Mental & Physical Performance (Andrew Huberman)
#+filetags: :podcast:health:
#+CREATED: [2023-06-01 Thu]

* Using Caffeine to Optimize Mental & Physical Performance (Andrew Huberman)
:PROPERTIES:
:URL: https://hubermanlab.com/using-caffeine-to-optimize-mental-and-physical-performance/
:END:

* Summary by podcastnotes.org
Added some notes here andd there..

**  Key Takeaways
- Caffeine is not just a stimulant, it’s a strong reinforcer that subconsciously
  drives behavior - caffeine (tasteless) added to anything will give you a
  preference for that thing, this applies to behavior, food, company
- Caffeine increases dopamine and acetylcholine in the forebrain which improves
  the ability to think, adjust to mental and physical demands
- Caffeine increases the number of dopamine receptors in the reward pathway of
  the brain
- Caffeine acts as an antagonist to adenosine which offsets sleepiness in the
  first half of the day
- Delay caffeine intake 90-120 minutes after waking (unless doing intense
  exercise) to fight off afternoon sleepiness

 - Tip #1: If this sounds impossible at first, delay in 15-minute increments
   until you hit 90 minutes+
 - Tip #2: If you can’t wait, drink half of the caffeine when you wake up and
   the other half a couple of hours later

- Does caffeine make you jittery? Consume at least an equal volume of water
  (with a pinch of salt) or electrolyte drink with caffeine to offset
- To extract more benefits from caffeine (assuming you already delay intake):
  (1) Consume on an empty stomach if you can tolerate it; (2) Abstain from
  caffeine for 2-5 days then resume; (3) Half your amount of caffeine intake for
  a period of time then resume

**  Introduction

Dr. Andrew Huberman, Ph.D. is a Professor of Neurobiology and Ophthalmology at
Stanford University School of Medicine. His lab focuses on neural regeneration,
neuroplasticity, and brain states such as stress, focus, fear, and optimal
performance.

In this episode of the Huberman Lab Podcast, Andrew Huberman explains how to
optimize caffeine intake for maximal mental and physical health and performance.
He explains optimal dosage, timing, mechanism, effects on health and longevity,
and more!

Host: Andrew Huberman (@hubermanlab)

**  GLP-1: Hot Off The Press

- Yerba mate tea (avoid smoked variety) stimulates the release of GLP-1 which
  reduces hunger, increases satiety in the gut and brain
- GLP-1 stimulates thermogenesis (use of more metabolic energy) and converts
  white fat cells (stored energy) into beige or brown fat cells (increases basal
  metabolic rate)
- GLP-1 can be stimulated with exercise such as fast cardio
- Prescription GLP-1 analogs are available through physician

**  Caffeine Is A Strong Reinforcer

- The effects of caffeine are largely subconscious
- The nervous system recalls previous experiences of good or not-good feelings
  and adjusts behavior accordingly - you are drawn to a certain mug, certain
  location, and certain caffeine ritual
- Caffeine makes us feel better in the immediate minutes before and after
  ingestion
- Caffeine stimulates dopamine, acetylcholine, and adenosine
  - Caffeine stimulates dopamine release in the region of the brain associated
    with clarity of thought
  - Caffeine also increases dopamine receptors in the reward pathway
  - Caffeine is a strong adenosine antagonist, reducing feelings of lethargy and
    sleepiness

**  Adenosine

- Caffeine is a plant alkaloid (bitter)
- Adenosine makes us feel tired - caffeine blocks adenosine and biases our
  system toward a more energetic pathway
- Adenosine levels are as low as they will be in the morning - avoid caffeine
  first 90-120 minutes after waking
- Caffeine does not increase energy - it’s borrowing energy, altering the time
  at which adenosine is released
- Adenosine is an inherent part of biology, it’s not going anywhere and will
  release every 24 hours
- How to clear adenosine: (1) sleep; (2) non-sleep deep rest; (3) view morning
  sunlight (spikes cortisol which clears residual adenosine); (4) some exercise
  can reduce adenosine

**  Optimizing Caffeine Intake

- Bodyweight is a good measure of proper caffeine dose for your body: 1-3mg/kg
  body weight per setting
  - This dose will likely provide you with all the benefits without the jitters

- Caffeine tolerance depends on one’s preexisting disposition (are you anxious,
  calm, stressed, etc.), caffeine tolerance
- Some people will feel anxious with caffeine use, some will feel nothing -
  start low and increase if you’re just starting
- Timing of intake: delay caffeine intake 90-120 minutes after waking most
  days - this will help you avoid afternoon crash and the need for that second
  cup of coffee in the afternoon which can disrupt the depth and quality of
  sleep
  - Adenosine builds up the longer we are awake, it’s lowest in the morning
  - Sets into motion cascade which will set you up for better sleep that night
    and more alertness the next day

- If you wake up and do intense exercise within the first 90 minutes of waking,
  drink the caffeine before but the combination of caffeine and exercise may
  increase afternoon fatigue
- you want to increase cortisol levels (by doing exercises)
  - this will "clean up" remaining adenosine in the body
- If you really can’t delay caffeine, you can extend the arc of caffeine if you
  drink half when you wake up and half later
- Caffeine has a more potent stimulant effect on an empty stomach (this may
  induce jitteriness which can be offset with 200-400mg of thionine)
  - Thionine has positive effects on sleep depth and duration, has antidepressant
    and antianxiety effects, and has endothelial benefits
  - You don’t have to take thionine every time you drink coffee throughout the
    day, just the first
- Tip: if you regularly ingest caffeine, performance-enhancing effects will
  increase if you abstain for a few days and then start again

**  Caffeine Myths & When To Avoid

- Caffeine does not create or exacerbate osteoporosis
- Caffeine does not appear to have a direct or indirect impact on estrogen or
  testosterone (i.e., caffeine does not appear to increase or decrease estrogen
  or testosterone)
  - But excessive caffeine intake does increase sex hormone binding globulin,
    though not to concerning levels

- *Avoid caffeine intake 12 hours prior to sleep* - the quarter-life of caffeine
  is 12 hours
- If you are not used to caffeine, avoid intake on days of tough physical or
  mental demands as the negative side effects may outweigh the benefits if you
  are not accustomed
- Don’t try the “napaccino” - ingesting caffeine in the late afternoon then
  taking a short nap, with the assumption that the caffeine will kick in when
  you wake up and you’ll feel stimulated

**  Benefits Of Caffeine Intake

- Caffeine has neuroprotective effects, provided intake is not excessive
- The properties of caffeine may be protective against depression but unknown
  whether the correlation is direct or indirect
- Caffeine consumption while fasting increases focus and alertness within 5
  minutes that peaks at 30 minutes and lasts up to 60 minutes
- Shortens reaction time if consumed about 30 minutes prior to the task
- Lowers activation threshold of learning and memory (you can recall things
  easier)
- Caffeine can increase physical performance enhancement, improve peak
  performance, increase aerobic endurance
- Brief or extended breaks from caffeine can enhance the effects once you resume
- Caffeine increases aerobic power throughout the entire menstrual cycle

**  Caffeine For Enhancing Mental Performance

- Spiking adrenaline after learning can enhance memory and recall
- Tip: abstain from caffeine when trying to learn something, then drink caffeine
  immediately after for improved memory
- Ingesting caffeine prior to exercise further increases dopamine release - this
  has a few benefits, most importantly creating a positive feeling about the
  exercise and maybe changing your association with exercise if you don’t
  otherwise like it

 - This does not hold if you drink caffeine every time you exercise

- Ingesting caffeine every other day can help you maximize the positive effects
  of caffeine without extended abstinence
- Pro-health effects of caffeine (assuming you are getting good sleep): (1)
  neuroprotective effects - may offset some neurodegenerative diseases; (2) can
  diminish headache, particularly in combination with aspirin; (3) may provide
  brief but substantial relief from asthma; (4) improves focus and alertness in
  people with ADHD

* Raw Notes
Welcome to the Huberman lab podcast where we discuss science and science space
tools for everyday life.
- I'm Andrew Huberman and I'm a professor of neurobiology
and ophthalmology at Stanford School of Medicine.
- Today we are discussing
caffeine.
- Caffeine is one of the most widely used substances on the planet,
estimates are that more than 90% of adults and as many as 50% of kids that is
adolescents and teenagers use caffeine on a daily basis, caffeine is an amazing
molecule.
- Most people are familiar with caffeine's ability to increase alertness
and to reduce our feelings of sleepiness and fatigue and indeed it does that.
But what most people are not aware of is that caffeine acts as a strong
reinforce er what I mean by reinforce er is that when caffeine is present in a
drink or food and yes, indeed caffeine is present in many foods.
- Even
unbeknownst to us when it's present in drinks and foods, we actively come to
like those foods and drinks more than if caffeine were not contained in those
foods and drinks.
- So it reinforces our liking of particular foods and drinks and
indeed it even reinforces our liking of the containers they are consumed from
and the company we keep when we consume foods and drinks that contain caffeine
That is caffeine is not just a stimulant, caffeine is a reinforceer and it's a
reinforce er that plays an active role in almost everybody's daily life.
- We can
say that with confidence because as I mentioned a moment ago, more than 90% of
people are consuming caffeine and most people think that they consume caffeine
because it makes them feel more alert.
- But there are many reasons why you're
consuming caffeine and I'm not going to tell you that consuming caffeine is
necessarily bad.
- In fact today I'm going to tell you about many of the positive
health benefits of caffeine including neuro protective effects, anti depressive
effects and certainly performance enhancing effects both for mental performance
and for physical performance.
- Now that said there are certain situations in
which you want to avoid caffeine and there are certain people who might opt to
avoid caffeine.

That's especially the case when one thinks about [[id:994d97cb-9da7-4e02-b2f0-5939701b25bd][caffeine]], not just as a
stimulant but as a reinforce er in fact caffeine is such a strong reinforce er
that if even tiny amounts of caffeine are present in certain foods and drinks
you will very quickly come to prefer those foods and drinks over other choices
which can be a good thing or a bad thing depending on what sorts of food and
drink choices you're trying to make.
- So today I'm going to inform you about how
caffeine works at a mechanistic level, I promise to do that with a minimum of
nomenclature and such that even if you don't have a background in biology you
will be able to digest that information easily and then I'll tell you how to use
caffeine to your advantage or conversely how to avoid caffeine at certain times
to your advantage.
- So today's episode will focus both on mechanisms and tools
that is the use and leverage of caffeine to improve mental health, physical
health and performance.
- Before we go any further into today's discussion, I want
to tell you about some recent results about a molecule that's found in certain
caffeinated beverages and that has been proven to be very useful for both weight
loss, mental performance and controlling blood sugar levels.
- And that's GLP one
or glue Kogan like peptide one.
- Glueck agan like peptide one is found in the
brain and body.
- It acts both on the brain and body.
- It does many different
things but one of its primary effects it's been discovered is to reduce hunger
and it does that two ways it does that by activating certain neurons in your
*hypothalamus.
- So that's a brain region that controls hunger and satiety*.
- It
makes us feel full at the level of the brain so it makes us feel sated.
- That is
and it actually makes us feel full, turns out that GLP one acts on certain
receptors in the gut to make us feel as if we've ingested enough food doesn't
necessarily make us feel as if our gut is distended but it makes us feel full.
That's really interesting because if you think about it when we eat our stomach
fills up obviously and that information has to be communicated to the brain such
that the brain can then send satiety signals that actually shut off our hunger
and believe it or not, the brain actually activates signals to reduce the desire
to chew when our stomach is full.

And GLP one as I mentioned, works on the brain to create these feelings of
satiety as if we've had enough.
- And to reduce our desire to eat more.
- And GLP
one acts directly on the gut to give us a slight sense of fullness in the gut
which then is communicated to the brain.
- So really there are two parallel
signals being sent when we have GLP one present in our system.
- A little bit of
relevant history on GLP one, it was actually discovered in [[https://en.
- ikipedia.
- rg/wiki/Gila_monster][gila monsters]].
- These
are these um reptiles that can go long periods of time without eating.
- And a
very clever scientist decided to study why it is that certain animals like Hila
monsters can go a long period of time without ingesting anything.
- It's because
they produce very large amounts of GLP one, They isolate the peptide from GLP
one.
- Then they looked for the analogous peptide in humans and it turns out that
does exist and as I mentioned, it's released in both brain and body to make you
feel full and sated.
- Why am I telling you all this? Well today we're going to
talk about caffeine and there's one particular caffeine source which is your
grandma And there's some other forms of teas similar to your moment that
stimulate the release of GLP one significantly.
- There are also nowadays drugs
which are called analogs of GLP one.

So these are drugs that mimic or are identical to the kind of GLP one that you
would make.
- And those drugs are proving to be very effective for the treatment
of certain forms of diabetes and for the treatment of obesity.
- But they trigger
enormous amounts of GLP one pathway activation.
- So those are extreme cases for
people that are really struggling for weight loss.
- But the clinical trials and
the data that are out there in the general population now are very, very
promising for GLP one analogs you're Beaumont T provided.
- It's not the smoked
variety.
- And I mentioned that because a number of people have cued me to the
fact that you're Beaumont eighties coming smoked varieties and non smoked
varieties and the smoked varieties are thought to perhaps be carcinogenic that
is pro cancer causing.
- So I advise people to avoid smoked varieties of your
Beaumont T.
- But your Beaumont T.
- S are known to stimulate significant amounts of
GLP one release and so they can be effective as a weight loss tool mainly by
blunting appetite and again they do that both at the level of the brain and at
the level of the gut.
- Now all of what I just told you has been known for some
period of time.
- But there are a new set of findings that were just published in
cell reports.

Medicine Cell Press journal, Excellent Journal, which indicate exactly how it is
that GLP one stimulates both satiety and can trigger additional weight loss
through other mechanisms.
- And I find the mechanism to be really interesting and
actually really important given some other topics we've covered on this podcast
before.
- So the basic finding is that GLP one whether or not it's stimulated
through the release of analog drug that one is prescribed or by drinking your
Bramante T for instance and stimulate the release of your own so called
endogenous GLP one.
- Yes it makes you feel more full at the level of brain and
body but it turns out it also stimulates thermogenesis.
- Now thermo genesis is
the active utilization of more metabolic energy and fat cells in particular, so
called beige and brown fat cells are a potent source of thermo genic activity in
your body.
- Basic background is that you have white adipose cells.
- So white fat
cells, you have beige fat cells and you have brown fat cells and the beige and
brown ones.
- Our fat cells that you actually want more of.
- They are not abundant
under your skin.
- They're abundant really around your clavicles and your upper
neck.
- They are the ones that generate heat and the beige and brown nous of them
is actually the consequence of having a lot of mitochondria in those cells.
- When
GLP one is elevated in your system, it turns out that it communicates to those
white fat cells and helps convert them into beige and brown fat cells.

That is.
- it takes fat cells that are not doing anything useful for you except
being stored energy.
- And I think most people out there would like to have fewer
of those white adipose cells.
- There are few of you out there that actually need
more of them that are too thin to lean.
- But most people are suffering from
having too many of these white adipose cells.
- Well when you ingest your tea or
you were to take a GLP one analog or stimulate GLP one in any number of
different ways.
- Yes, you stimulate increased satiety but you're also stimulating
the conversion of these white fat cells into beige and brown fat cells which
makes you more thermo genic and over time raises your basal metabolic rate so
you're burning more calories even at rest.
- It also makes you feel as if you're
more comfortable in colder environments at rest.
- This is very much the same as
the mechanism that induced when you were to say take a cold shower or do regular
ice baths or get into cold water regularly.
- That two stimulates the conversion
of white fat cells to beige and brown fat cells.
- So I like these findings very
much because they provide a mechanistic coherence they provide.
- That is a really
nice story as to how something like GLP one could be so effective for weight
loss.

metabolic rate and we now know how that's accomplished.
- It's likely accomplished
at least through this one mechanism by the stimulation of conversion of these
white fat cells, which don't do much for us except at as energy storage units to
these metabolically mitochondrial rich beige and brown fat cells which you can
think of a sort of the oil in the candle that allows your furnace, your
metabolism to burn at a higher temperature and a higher rate.
- So that's the
mechanism and the basic tool takeaway is that if you're somebody who's
interested in losing weight and you want to leverage the GLP one pathway
drinking a cup or two of yerba mate tea early in the day would be a great way to
stimulate GLP one release.
- There are other ways to stimulate GLP one release.
You can get it through certain forms of exercise in particular fasted exercise.
This is actually a vote in favor of fasted exercise.
- There's a debate as to
whether or not fasted cardio burns more fat than non fasted cardio.
- In the the
data basically say no, it doesn't really matter.
- But that doesn't really take
into account the longer arc of things like GLP one release.
- So that needs to be
taken into consideration.
- So you could do fasted cardio, you could drink yerba
mate tea, keeping in mind that tea does contain caffeine.

We'll talk more about the specific forms of stimulants, including caffeine that
man has, but monty would be a great way to stimulate GLP one release.
- And then
of course, for those of you that are interested in more robust activation of GLP
one, then perhaps you might want to consider some of the new prescription GLP
one analogs that are out there, but that's a more severe stimulus for GLP one of
course.
- And for everybody, regardless of whether or not you're trying to lose
weight, gain weight or maintain weight.
- I think we're going to be hearing a lot
more about GLP one analog and drinks and supplements and things of that sort
that stimulate GLP one in the very near future because it does appear to be a
very important biological mechanism.
- Before we begin, I'd like to emphasize that
this podcast is separate from my teaching and research roles at stanford.
- It is
however, part of my desire and effort to bring zero cost to consumer information
about science and science related tools to the general public.
- In keeping with
that theme, I'd like to thank the sponsors of today's podcast.
- Our first sponsor
is levels levels is a program that lets you see how different foods affect your
health By giving you real time feedback on your diet using a continuous glucose
monitor.
- Blood glucose or blood sugar is a critical aspect of your media and
long term health and indeed your feelings of vigor and mental clarity and well
being at any moment.
- One of the key things is to know how different foods and
food combinations and timing of food intake is impacting blood glucose and with
levels you're able to assess all of that in real time.
- I tried levels and what
it taught me for instance, was that I can eat certain foods at certain times of
day, but if I eat them at other times a day I get a blood sugar crash.
- It also
taught me, for instance how to space my exercise and my food intake turns out
for me, exercising fast, it is far more beneficial.

That's something I learned using levels and it's completely transformed not just
the spacing and timing of my diet and exercise, but also use of things like the
sauna and other activities.
- It's been a, this learning for me that's really
shaped an enormous number of factors in my life that have led to me feeling far
more vigorous with far more mental focus and physical strength and endurance.
- So
if you're interested in learning more about levels and trying a continuous
glucose monitor yourself, go to levels dot link slash Huberman.
- Again, that's
levels.
- Dot link L I N K slash Huberman.
- Today's episode is also brought to us
by Eight sleep.
- Eight sleep makes smart mattress covers with cooling, heating
and sleep tracking capacity.
- I've talked many times on this podcast about the
critical relationship between sleep and body temperature that is in order to
fall asleep and stay deeply asleep throughout the night.
- Our body temperature
needs to drop by about 1 to 3 degrees.
- And conversely when we wake up in the
morning, that is in large part because of our body heating up by 123 degrees.
People have different core body temperatures and they tend to run colder or
hotter throughout the night.
- Eight sleep allows you to adjust the temperature of
your sleeping environment so that you have the optimal temperature that gets you
the best night's sleep.

I started sleeping on an eight sleep mattress cover about eight months ago and
it is completely transformed by sleep.
- I sleep so much deeper.
- I wake up far
less during the middle of the night if at all and I wake up feeling far better
than I ever have even after the same amount of sleep.
- If you want to try eight
sleeping, go to eight sleep dot com slash Huberman to save up to $400 off their
sleep holiday bundle which includes their new pod three cover eight sleep
currently ships in the Usa Canada United Kingdom select countries in the EU and
Australia.
- Again, that's eight sleep dot com slash Huberman.
- Today's episode is
also brought to us by Roca.
- Roca makes eyeglasses and sunglasses that are the
absolute highest quality.
- The company was founded by two all american swimmers
from stanford and everything about Rocca eyeglasses and sunglasses were designed
with performance in mind.
- I've spent a lifetime working on the biology, the
visual system and I can tell you that your visual system has to contend with an
enormous number of challenges in order for you to see clearly.
- For instance when
you move from a sunny area to a shady area and back again.
- Whether or not you're
looking at something up close or off into the distance.
- Rocca understands the
biology of the visual system and has designed their eyeglasses and sunglasses so
you always see with perfect clarity.

Rocca eyeglasses and sunglasses were initially designed for activities such as
running and cycling and indeed they are very lightweight most of the time, I
can't even remember that they're on my face, They're so lightweight.
- But the
important thing to know about Rocca eyeglasses and sunglasses is that while they
can be used during sports activities, they also have a terrific aesthetic and
they can be used just as well for wearing to work or out to dinner etcetera.
- If
you'd like to try Rocca eyeglasses and sunglasses, you can go to Rocca, that's
our okay A dot com and enter the code Huberman to save 20% off on your first
order again, that's Roca are okay dot com and enter the code Huberman check out
the Huberman Lab podcast is now partnered with momentous supplements to find the
supplements we discuss on the Huberman lab podcast.
- You can go to live momentous
spelled O.
- U.
- S.
- Live momentous dot com slash Huberman and I should just mention
that the library of those supplements is constantly expanding again.
- That's live
momentous dot com slash Huberman.
- Let's talk about caffeine.
- So as I mentioned
earlier, caffeine is consumed by basically most all adults every single day and
consumed at very regular times each day.
- In fact, if you were to take a look at
your caffeine intake or the caffeine intake of somebody close to you, what you
would realize is that they don't do so well if their caffeine intake arrives
even 10, 20 or 30 minutes past their expected or usual intake of caffeine.
That's pretty remarkable and it brings to mind ideas that we are all quote
unquote addicted to caffeine or that caffeine is somehow bad.


I'm certainly not going to make the argument that caffeine is bad.
- First of all,
I'm a regular caffeine user, I wouldn't call myself a caffeine abuser, but I am
a regular caffeine user and caffeine is known to have certain health benefits.
- I
listed off a few of them earlier, but I'll mention those again now before going
forward, caffeine is known to have certain neuro protective effects and that is
because of its ability to increase neural modulators such as dopamine but also
other so called cata cola means like Norepinephrine if you don't know what those
names mean, These are molecules that increased levels of alertness, motivation
and drive and so then therefore, not surprisingly, the large scale analyses of
the relationship between depression and caffeine shows that provided people are
not drinking so much caffeine that it makes them overly anxious.
- That regular
intake of caffeine is inversely related to levels of depression.
- So it may have
some antidepressant effects and those could be direct or indirect.
- What do I
mean by that? Well, you can imagine that people are ingesting caffeine and they
are more motivated to do work and pursue quality social interactions.
- Then the
probably that they will have depression could be lower.
- It could also be that
there are direct effects on the chemical systems of the brain that relate to
mood and well being that could offset depression.
- It is not clear whether or not
the effects of caffeine encountering depression are direct or indirect.
Nonetheless, there's a relationship there and it's an interesting and positive
one or I should say negative correlation, positive uh effect overall on mood and
well being to be exact.
- Now, it's also the case that caffeine can improve mental
performance and physical performance.


This has been demonstrated in tens of thousands of studies.
- I will review a few
studies on this in particular today, but to just give you a sense of how
caffeine works at the level of its timing and impact on mental performance and
physical performance when we ingest caffeine, provided that we don't have a lot
of food In our stomach and that our blood sugar isn't particularly high.
Generally we experience an increase in alertness within about five minutes and
that increase in focus and alertness peaks around 30 minutes after ingestion of
caffeine and persist for as long as 60 minutes.
- Now this is assuming that one
takes caffeine in pill form or drinks the entire caffeine drink within a short
period of time.
- But a little bit later, I'll talk about how you can consume
caffeine at regular intervals while doing mental work or physical work in a way
that can further increase mental performance and physical performance.
- But let's
just touch on what caffeine intake really does for mental performance and
physical performance.
- Perhaps the most robust finding across all of the studies
that I've examined is that caffeine reduces a reaction time.
- That is, it
improves our reaction time.
- It doesn't make it longer, it makes it shorter.
- So
for instance, in a laboratory study where people were asked to hit a lever every
time they hear a tone, you can greatly reduce the time between the tone and the
pressing of the lever.
- If people ingest caffeine about 30 minutes before they do
that task.
- Now, that seems like a trivial task.


But this is also seen in the domain of sports performance and even in cognitive
performance, where people have to arrive at a particular answer to a question
and the answer to that question has to be pulled from their memory banks within
their brain, their hippocampus, for instance, a brain structure involved in
memory and if you are asking people for instance to remember the capitals of
different states or cities or to remember certain historical facts, they will do
that at a particular rate.
- But if they've ingested caffeine within the hour
prior their ability to recall that information is much much better.
- They are
faster and it does not appear that accuracy is reduced.
- In fact in many cases
accuracy is enhanced.
- And that's because caffeine both works on the reaction
time systems of the brain and body.
- I'll talk about the mechanisms for that in a
little bit but it also stimulates certain neurotransmitters and so called neuro
modulators within the brain and body that give the neural circuits in the brain
that are associated with learning and memory a lower threshold to activation.
What does that mean? That means that we are better able to access the brain
circuitry involved in learning and memory when we have a certain amount of
caffeine circulating in our system.
- So this makes caffeine an incredible
performance enhancing compound.
- And I could give you tens thousands of examples
of this in humans.
- But before I do that I want to just touch on what we know
about the existence of caffeine and nature and what the existence of caffeine
and nature and its effects on other animals tells us about what caffeine does in
humans because as I alluded to earlier.
- What caffeine is doing for us is not
just making us more alert, improving our memory, improving our reaction time and
so on.


It's actually acting as a powerful reinforce er of experience and it's acting is
not just a powerful reinforce er of the caffeine containing drinks that we drink
but also the mug that it's contained in plus the person that we might be sitting
across from when we consume that caffeine and so on and so forth.
- If it's a
little bit hard for you to conceptualize what a reinforce er is and why I'm
calling it a reinforce er Let me spell it out in three specific ways.
- We often
hear about the word reward and we think okay if we do certain things and we like
the outcome then those certain things are rewarded right? If we're doing
something we receive praise the praises the reward and therefore we are more
likely to do that thing in the future that a lot of parenting is like that and a
lot of life is like that.
- However when we hear the word reward we often think
about something that feels good to us and certainly if we've worked hard and we
get some praise that's natural for the praise to feel good to us or for instance
if we we work very hard and we get a certain outcome a trophy, a financial
outcome, a degree outcome recognition etcetera all of those can act as rewards
but those are all conscious rewards.
- We are aware that they are happening
reinforces our a little bit different because the word reinforcement can apply
to conscious rewards of the sort that I just described.
- But there are also many
ways in which caffeine stimulates the release of chemicals in our body that act
as reinforce ear's but those reinforce ear's our subconscious that is we are not
aware that they cause this preference for the activities that cause their
release.
- So the study I'm about to describe beautifully I believe encapsulates
how is it that humans came to consume caffeine and why caffeine exists in nature
and the powerful effects of caffeine as a reinforcing agent both in animals,
insects and in you and me.
- And the title of the paper is caffeine and floral
nectar enhances the pollinators memory of reward? Keep in mind that caffeine is
made from plants, Usa Duh, but I think some of us don't realize that the reason
why there is caffeine and coffee is because coffee comes from a plant, it's a
coffee bean certainties which of course are plants that people brew caffeine is
contained in those teas such as well.
- Why would this bitter substance? Because
in fact caffeine is quite bitter in high concentrations.


Why would this bitter substance be something that insects or animals would want
to consume at all? It turns out that in most plants caffeine is present in small
enough quantities that insects and other animals and in fact we can't actually
taste the caffeine if I were to give you a little bit of pure caffeine.
- Yes, it
would be a stimulant for you but you would say that it tasted awful.
- It's in the
category of compounds that would strongly stimulate the bitter receptors on your
tongue and would make you cringe and pucker and essentially walk away from
whatever it is that contained that caffeine and from the experience that
contained that caffeine well in nature, caffeine is present in very low
concentrations or is masked by other flavors within flowers, beans and plants.
And what this paper really points to is that caffeine in nature is acting as a
reinforce er for bees that are consuming different nectar.
- So the way that it
works is that bees of course go from flower to flower and they are consuming the
nectar.
- They are bringing nectar and pollen back to the hive and that provides
critical nourishment for the bee colony.
- The bees are foraging in a way that
includes information about color in particular ultraviolet color, things that we
can't see.
- But they can see because they have different photo receptors than we
do.
- And what this study shows is that plants and nectars that contain very small
amounts of caffeine are the preferred sources of food for bees.
- And the study is
beautiful because they were able to confirm that they could mask the caffeine
taste.
- So if they know that the bees are not preferring the taste of caffeine
but what they do is they pair caffeine with different food sources for the bees,
then they remove the caffeine and what they find is that the bees very strongly
prefer flavors that contain caffeine, not because they could taste the caffeine,
but rather for the way that those caffeine containing flavors made the bees
feel.


So how do those caffeine containing flavors make the bees feel the same way that
they make you and I feel a little bit more alert and thereby able to do more
work for the B.
- The more work is the consumption of more food which then has a
further reinforcing effect.
- So what we're really talking about here is the fact
that a caffeine exists in nature in plants.
- It exists in concentrations that are
very low, so low in fact that they are not detectable to the taste receptors of
insects and in many cases to the taste receptors of humans.
- And of course there
can be high levels of caffeine in a plant.
- But if the plant also contains
compounds that mask the flavor of caffeine, well then those plants are going to
essentially be even stronger reinforces for the flavor of the plant.
- Okay, so
now we're talking about strong flavors plus strong neuro stimulant effects of
caffeine and the most important point here is that all of these effects of
caffeine.
- Our subconscious it is not because the B or you like the taste of
caffeine.
- In fact most people when they take their first sip of coffee, they
find it taste bitter and kind of noxious.
- They don't like it.
- You may not even
remember that because it happened so long ago and because caffeine is such a
strong reinforces that very quickly you come to like the taste of coffee, you
might even come to like the feeling of your mug in your hand, you might even
come to like the smell of coffee and so on and so forth.
- And that's because
caffeine stimulates the release of certain neurochemicals in the brain.


In particular dopamine and acetylcholine to neuro modulators that increase our
focus and alertness and our feelings of well being a little bit later.
- I'll tell
you that caffeine stimulates the release of dopamine in a way that's very much
distinct from the classical dopamine pathway associated with addiction and
reward.
- In fact we can think of caffeine as having a somewhat privileged access
to the reward systems.
- I'll give you a bit of a hint of where this is going.
Caffeine stimulates the release of dopamine and acetylcholine, not within the
classic so called meso limbic reward pathway that's just fancy nerd speak for
the reward pathways of the brain.
- They're associated with things like sex and
food and drugs of abuse like cocaine and methamphetamine but rather caffeine
seems to stimulate the release of dopamine in the parts of the brain that are
associated with alertness and cognition meaning the forebrain.
- This is very
important.
- We have multiple dopamine systems in the brain and body and caffeine
seems to stimulate dopamine directly within this components of the brain that
are associated with clarity of thought and well being but more so clarity of
thought.
- Now I'm also talking about caffeine as a strong reinforce er in that it
makes you feel good overall and it does and that suggests that it also taps into
the more classic reward pathway but it does that in a very interesting and
frankly almost diabolical way.
- When we regularly ingest caffeine it stimulates
the increase in dopamine receptors at multiple sites throughout the brain but in
particular within the reward pathways of the brain.
- So not the areas of the
brain that associated with focus and clarity of thought and cognition.
- It does
that but it is also increasing the level of dopamine receptors in the reward
pathway.


And what that means is that for any dopamine that's released in response to a
positive experience, social experience or any number of the other things that
can stimulate dopamine release there are more receptors more parking spots if
you will for that dopamine to arrive at and to exert its increases in mood
increases in motivation and overall feelings of drive and excitement.
- So there
are four ways that caffeine works that we need to understand.
- First of all
caffeine acts as a reinforcing agent.
- It increases the probability that you will
return to and engage in a certain activity or consume a certain beverage or
food.
- Second of all caffeine increases dopamine and acetylcholine, which are
both neuro modulators in the forebrain, which helps us improve our ability to
think to modify our rule sets.
- That is to adjust our strategies for different
social situations and mental demands and physical demands.
- And third, it
increases the number and efficacy of dopamine receptors in the reward pathways
of the brain.
- That is, it makes things that would feel pretty good, feel even
better.
- And fourth, caffeine acts as an antagonist to a dentist scene which
offsets the sleepiness that we would otherwise feel from the accumulation of a
dentist scene that occurs as we are awake for more and more hours throughout the
day.
- So let's talk first about caffeine as a reinforcing agent again.
- So it's
first most beautifully demonstrated in this study on honeybees, where the bees
prefer nectars that contain caffeine and that all makes perfect sense in terms
of the ecology of bees and flowers that contain nectar.
- Uh there's an advantage
at least in terms of adaptation that the flower benefits because of distribution
of things from the flower, which is good for the flowers and the bees benefit
because they're getting food.


And so there's a kind of a symbiosis there.
- But with humans we were consuming
caffeine containing beverages for our sake.
- I don't think we have it in mind,
nor do the bees have it in mind, frankly that we're trying to preserve the
plants that provide the caffeine.
- I think we would all suffer actually, say 90%
of adults would suffer greatly if all the caffeine containing uh coffee and tea
plants were gone certainly.
- But most of us are not consuming coffees and teas
and caffeine containing foods because we're thinking about the plants they come
from and we want to help those plants were thinking about how we want to help
ourselves.
- And yet the point of the reinforcing effects of caffeine are that
they are largely subconscious.
- We are not aware of them.
- Now you might say no,
that's not true.
- When I drink caffeine, it makes me feel really good.
- So I'm
aware that it makes me feel good in order to illustrate how reinforcement really
works.
- Let me give you the counter example, which would be an aversive agent.
- So
we have reinforcing agents and we have aversive agents.


Let's say that there were compounds in nature that exist in plants that are
aversive and indeed they are.
- And let's say that these compounds were present at
such low concentrations that you couldn't taste them.
- Let's say you wake up in
the morning and you go to your refrigerator and you open it up and you are
thirsty and so you reach for a nice um you know, rich red containing beverage in
a glass jar.
- It looks like cranberry juice or something of that sort or even a
nice clear glass of water.
- It looks like a jug of water, a glass of water and
you drink that case, find you maybe even taste great to you And then let's say
about 30 minutes later, you feel a little queasy, you feel a little off, you
feel like going back to sleep, you just don't feel very good, you don't know
why, but your nervous system is a predictive machine and it has a process in
which it back integrates or I should say integrates backwards into your
immediate experience that preceded that.
- Not so good feeling, we can reliably
say that there is a much lower probability that the next day when you wake up
that you would reach for that same beverage or for that same container even, and
maybe if you're in a novel environment, maybe you're staying in an Airbnb or a
hotel or something of that sort.
- You might even find that you don't really like
the kitchen in which you consume that beverage in the first place and you don't
know why.
- And unless you got very, very sick that the day before, it's unlikely
that you would have such a strong response that you would entirely avoid.
- For
instance, water or glass jars containing liquids etcetera, let's say you went
back to the refrigerator and you consumed beverage again and you just didn't
feel so well, you felt less good than you normally would.
- Well, even without any
ability to taste what's in that beverage and even without any understanding of
what was happening to you at a conscious level, there is a very, very high
probability that you will avoid drinking that particular beverage and certainly
at that location and in the same volume in the subsequent days, that's just the
way that aversive agents work and they work by way of activating neurons in the
gut that communicate with areas in the brain that give us this feeling of
queasiness and for some of you hearing this that pathway and that association
with times in which you felt queasy and as if you wanted to vomit is so powerful
that you might even be feeling some of that symptomology now for certain people
that's going to be increased salivation which precedes vomiting.
- We know that
there's a class of neurons in the brain relate to an area called area post rima
that actually stimulates vomiting and if I keep talking about this I'll probably
feel like I want to vomit.
- So I'm gonna move on from this in a moment.


So when we ingest caffeine containing beverages and foods, it's the exact
opposite scenarios to what I just described caffeine as a reinforce er makes us
feel slightly better or a lot better in the immediate minutes and hours after we
ingest it, so it's acting as a reinforcing agent, not just while you're under
the effects of caffeine, but for the things that preceded the ingestion of
caffeine, which is why you return again and again to caffeine containing
beverages such as coffee and tea.
- Or maybe even foods that contain caffeine,
even if the taste of those foods is not something that you would otherwise
consider especially delicious.
- In fact, most people, when they take their first
sip of coffee or tea or other caffeine containing beverage, they find to be very
bitter and that's not because of the taste of caffeine, it's because of the
taste of the beverage itself, independent of caffeine.
- However, when caffeine is
present in there, they come to prefer that taste over most all taste.
- In fact,
they will, as I mentioned earlier, will invest a lot of financial resources and
time and energy to make sure that they get that beverage.
- What they're trying to
make sure is not that they get that taste, but that they get the caffeine.
- It is
that positively reinforcing and the taste therefore takes on new significance
new meaning and we come to associate it as positive and in fact most of us
including myself, love the taste of espresso, love the taste of coffee, love the
taste of your, even if the initial taste, the very first time that we consume
that beverage was either neutral or negative and that is all because of the
reinforcing properties of caffeine and then of course there are the more direct
actions of caffeine, that is the faster actions of caffeine.
- And just to list
those off again very briefly, so that you have them in mind going forward.
Caffeine also increases the release of dopamine and acetylcholine, both of which
are neuro modulators in the forebrain which increases clarity of thought and
your ability to rule, switch your ability to move from one context to another
and change and understand the rules of engagement, social engagement, physical
engagement, mental engagement and so forth.
- And as I mentioned before, caffeine
also increases the number of dopamine receptors in the reward pathway.
- Such that
any good thing that happens to you, any positive experience that you have will
have a more potent effect on your feelings of well being and last but certainly
not least caffeine access and a denizen antagonist.
- It reduces your feelings of
lethargy and fatigue and your desire to sleep by parking in the receptors for a
dentist scene and not allowing a adenosine to have its pro sleepy if you will
effects on your brain and body.

I'd like to take a quick break and acknowledge one of our sponsors, athletic
greens athletic greens, now called a G.
- One is a vitamin mineral probiotic drink
that covers all of your foundational nutritional needs.
- I've been taking
athletic greens since 2012 so I'm delighted that they're sponsoring the podcast.
The reason I started taking athletic greens and the reason I still take athletic
greens once or usually twice a day is that it gets to be the probiotics that I
need for gut health.
- Our gut is very important.
- It's populated by gut microbiota
that communicate with the brain, the immune system and basically all the
biological systems of our body to strongly impact our immediate and long term
health.
- And those probiotics and athletic greens are optimal and vital for micro
biotic health.
- In addition, athletic greens contains a number of adapt asians,
vitamins and minerals that make sure that all of my foundational nutritional
needs are met and it tastes great.
- If you'd like to try athletic greens, you can
go to athletic greens dot com slash Huberman and they'll give you five free
travel packs that make it really easy to mix up athletic greens while you're on
the road in the car, on the plane etcetera.
- And they'll give you a year's supply
of vitamin D.
- Three K.
- Two.

Again, that's athletic greens dot com slash Huberman to get the five free travel
packs and the year's supply of vitamin D.
- Three K.
- Two.
- I'd like to just briefly
talk about it, Dennis Scene and some of its molecular features.
- And again, if
you don't have a background in biology, don't worry, I promise to make this very
clear to everyone.
- First of all caffeine is what's called a metal Xanthan.
- It's
an it's a plant alkaloid, that's why caffeine itself is very bitter.
- Again, if I
were to give you just the tiniest little bit of pure caffeine, you would find it
to be extremely aversive and so these plants that have snuck small enough
amounts of caffeine into them or that have masked the flavor of caffeine with
other flavors such that bees and humans want to consume them.
- Uh Well we don't
know what plants think.
- Um It does seem very diabolical and very clever in that
we are seeking out these caffeine containing uh plants, beverages and foods.
Even though caffeine itself is this alkaloid is very very bitter metals and seen
that is caffeine binds to adenosine receptors and there's really two types of
identity in receptors.
- There are these so called A.

One receptors and the A.
- Two receptors and their president different parts of
the brain and body at different levels.
- We don't have to get too far into
receptor subtypes.
- More importantly to understand is that a dentist scene makes
us feel tired because of the way that it taps into the
A.
- T.
- P.
- Pathway.
- The A.
- T.
- P.
- Pathway is central to energy production and
   feelings of overall energy in our brain and body in all cells and organ
systems when caffeine binds to adenosine receptors, it prevents a Dennis scene
from breaking down certain components of the energy production pathway.
- And the
net consequence of that is increased cyclic A.


M.
- P.
- So basically when we ingest caffeine we are biasing our system towards the
   pro energetic aspects of the cellar pathways.
- Now it's really
important to understand that in biology even if you block a receptor or you
prevent the activity of an enzyme and at least in this case you end up with more
cyclic GMP more energy.
- You're not really getting more energy.
- You're actually
borrowing energy against an overall system that is frankly non negotiable.
- What
do I mean by that? Well, let's say that you were to wake up after six or eight
hours of sleep and to drink a lot of caffeine and keep drinking caffeine
throughout the day, throughout the day, blocking those identity and receptors.
Yes, you'll offset fatigue.
- You'll offset sleepiness because that identity in
simply can't function.
- But at the point where the caffeine becomes dislodged
from the identity and receptors you will have a massive glut, a backlog of a
dentist scene and you will feel extra extra sleepy.
- So really there's no way to
create more energy in your system.


Really, what you're doing is you're changing the timing in which the sleepy
signals and the more energetic signals are arriving.
- And this is really
important to understand as as the backdrop to the various tools that we're going
to get into next, in which you can use caffeine for enhancing mental performance
and physical performance and other aspects of health.
- But it's very important to
understand this concept that When you wake up in the morning, provided that you
slept well and enough the night before your levels of a dentist scene will be
about as low as they will ever be.
- Actually in order to get your identity levels
really bottomed out.
- You want to avoid caffeine in the 1st 90 220 minutes after
waking.
- We'll talk about why that is because it turns out there's a way to
completely clear a dentist scene out of your system in the hour or so after
awaken.
- But for most people, identity levels are going to be close to their
lowest after a good night's sleep.
- But there's really no negotiating the
accumulation of a dentist, seen that it's going to occur and going to bias you
towards feeling more sleepy than you would otherwise, that's gonna occur
throughout the day.
- There's really no way to eliminate a denizen.
- All you can
really do is block its function.
- So it sort of like borrowing energy against the
fatigue that you will inevitably feel.
- Now this actually has very important
socio economical relevance.


Before caffeine was regularly consumed by human beings.
- We were really slaves to
the light dark cycle.
- And this was especially true before the presence of
artificial lighting.
- But even before the advent of artificial lighting, humans
were largely constrained to the outside light dark cycle.
- We need to be active
during the day and working during the day and we need to be asleep at night,
caffeine allows us to divorce ourselves from that circadian cycle, circadian
just means about 24 hours Caffeine allows us to do that at least somewhat by way
of increasing our alertness.
- That is spiking our alertness at various times
throughout the day and even at night.
- This is how we can have shift workers for
instance, that can sleep during the day and then drink a strong cup of coffee at
eight p.
- .
- and then work into the night.
- That ability completely transformed our
society.
- Now, of course the healthiest schedule, We know this with certainty the
healthiest schedule for brain and body is going to be to be alert during the
daytime and asleep at night.
- There's no question about that.
- Shift workers run
into all sorts of health problems and thank you shift workers for doing the
important work that you do.


We need you.
- Air traffic controllers, paramedics, firefighters, police officers,
etcetera.
- But we know that there are serious health consequences, negative
health consequences.
- That is for shift workers.
- But for most people out there,
about 95% of people follow a typical schedule.
- They're awake during the day and
sleep at night.
- And yet it used to be before the advent of caffeine containing
beverages that if you were sleepy in the afternoon, you either had to take a nap
or battle that sleepiness, that your activity rhythms and your sleep rhythms
were governed by these circadian changes in Availability of sunlight and when
you slept and you just didn't have the ability to ingest a beverage.
- That would
increase your levels of alertness because you block a adenosine.
- So this is
important to understand that nowadays we certainly live in a time in which we
use in fact 90% or more of adults and half or more of adolescents and teenagers
use caffeine as a way to negotiate with to borrow against this natural pattern
of a adenosine making a sleepy.
- But again you're just offsetting the effects
of sleepiness that denizen causes.
- You can't eliminate the identities in
entirely.
- The important point is that a adenosine as a pro sleepy molecule is
a non negotiable aspect of your biology.


In fact it's so non negotiable that every 24 hours you are going to release a
dentist scene and you're going to release the tennessean in direct proportion to
how long you've been awake.
- So the longer you've been awake the more adenosine
circulating your system.
- There are really only a handful of ways to completely
clear out a adenosine.
- The major one being to get sleep.
- The other is to take
a short nap which of course is sleep but it's shallow sleep or non sleep
depressed.
- So called N.
- S.
- D.
- R.
- Has been shown to reduce levels of adenosine.
And there are certain things such as viewing morning sunlight which, because of
its effects on cortisol can quote unquote, clear out a dentist and we'll talk
about this in more detail in a few minutes.
- And there's also evidence that
certain forms of exercise provided that it's brief and intense can also reduce a
adenosine.


Not just block its effects.
- Now that we've talked about some of the incredible
mechanisms by which caffeine changes our experience of life, increases alertness
and mood etcetera.
- I want to talk about the use of caffeine as a tool.
- Now,
caffeine is a very potent and useful tool for enhancing mental health, physical
health and performance, But there are certain considerations one has to keep in
mind in particular dose.
- Now first off, not everybody will respond to the same
dose of caffeine the same way.
- But we can reliably say that your body weight is
a good measure by which you can estimate what a healthy useful dose of caffeine
would be.
- So for most people ingesting 123 mg of caffeine per kilogram of body
weight is going to be the range in which caffeine can have positive effects
without making us feel overly anxious.
- And give us that feeling that you were
jumping out of our skin and turn the otherwise positive experience of caffeine
into an aversive one.
- For those of you that aren't familiar with thinking in
terms of kilograms and normally thinking pounds, I'll just quickly give you some
general estimations that for instance, 100 kg equals £220.
- So for me I weigh 100
kg, that means that 123 mg.
- Again, milligrams, thousands of a gram.
- 123 mg of
caffeine per kilogram of body weight would mean for me, I could safely ingest
100 to 300 mg of caffeine in a single dose in a single drink if that's the way
I'm consuming it or pill form, if that's the way that I'm consuming it and it's
very likely that that would be a tolerable dose.


However, if you are not somebody that's accustomed to drinking caffeine on a
regular basis, I suggest you start on the lower end of that 123 mg per kilogram
of body weight range.
- So for instance, if you're somebody who weighs 50 kg,
that's approximately 100 and £10 And you would be pretty comfortable ingesting
somewhere between 50 and 150 mg of caffeine.
- So what I recommend is that people
who are considering using caffeine as a tool or who are already ingesting
caffeine, start to think about the dosage of caffeine that you are ingesting or
plan to ingest.
- And the timing in which you ingest that caffeine relative to
certain tasks throughout your day.
- You're waking in your sleep and we'll talk
about that in just a moment.
- But the first step for you is to figure out how
much you weigh in kilograms and then to go to that number of 1 to 3 mg of
caffeine per kilogram of body weight and that's a good range in which you might
want to explore the use of caffeine in a single application, meaning a single
dose.
- Now I do realize that some people out there are drinking coffee all day
long or having coffee in the morning and then again in the afternoon, What I'm
referring to here is the ingestion of caffeine in a single, about right one Cup
of coffee or two cups of coffee for instance, to achieve that 100-300 mg range,
if that's what's appropriate for your body weight.
- But to avoid any confusion,
when I talk about dosage of caffeine, what I'm really talking about is not the
total amount of caffeine ingested per day.
- I'm talking about the total amount of
caffeine ingested in one sitting or setting.
- That is, and if you're somebody
who's drinking caffeine multiple times throughout the day, you can imagine for
instance, let's say the appropriate dose for you in order to get an enhancement
and mental performance or physical performance is 200 mg.
- And you are somebody
who's doing some work in the morning and you want to have that lift in the
morning to be able to focus better and you're doing some physical exercise in
the afternoon or vice versa, that you would ingest 200 mg of caffeine at two
separate times per day, separated by about four hours.
- Now you don't have to
separate them.


You could uh you could put them two hours apart for instance, but We'll talk
about half life of caffeine and so forth.
- Just keep in mind that if you're
ingesting 200 mg of caffeine and that's the appropriate dose for you based on
your body weight and then you are ingesting another 200 mg of caffeine an hour
later you're effectively ingesting Prock Accidentally 400 mg of caffeine which
is going to start exceeding the dose in which you can normally tolerate without
feeling anxious and jittery.
- With all of that said, there is a range of
tolerance for caffeine that's based on two things.
- One is a pre existing
disposition that is whether or not your genetics and nervous system in the
backdrop of your life, how much stress you're experiencing tends to make you
feel more anxious and alert and jittery before you ingest any caffeine.
- And the
other is how so called caffeine adapted.
- You are we often hear about tolerance.
Tolerance means something very specific.
- It's the ability to ingest more and
more of something with a plateau that is a non no increase or an actual
reduction in the effectiveness of that thing.
- But here we're not really talking
about tolerance to caffeine, What we're talking about is being caffeine adapted.
A simple way to understand whether or not your caffeine adapted or not is that
if you drink caffeine and it tends to increase your heart rate and make you feel
more alert and a bit more anxious.
- The chances are you're not caffeine adapted
provided the amount of caffeine is within the healthy range for you that is the
ranges we talked about a moment ago.
- However, here's somebody who drinks
caffeine and you actually feel alert and relaxed, chances are you are caffeine
adapted and so at various times during today's episode, I'll talk about people
are caffeine adapted and people who are not caffeine adapted.


We'll talk about the use of caffeine every other day.
- I know a few habitual
caffeine drinkers, including myself.
- Just the simple mention of that probably
sounds aversive.
- Um but there is actually great utility to using caffeine every
other day as opposed to every day.
- But just keep in mind that some people will
drink caffeine and not get much of a lift from it at all.
- Other people will
drink caffeine and they will feel extremely anxious even at dosages far lower
than that.
- 123 mg per kilogram of body weight range that I described a moment
ago.
- So you have to take into account individual differences.
- That said 123 mg
of caffeine per kilogram of body weight for a given sitting, you know, for your
morning coffee or your your morning, your tea is a good range from which to
start and I do encourage you to go online and look up the various beverages and
foods that you might be eating that contain caffeine.
- For instance, some people
are surprised to discover that the coffee that they get from some of the more
standard popular vendors out there.
- The small coffee or the medium coffee for
instance, can contain as much as 400 to 600 mg of caffeine and that the large
coffee that is often sold at those commercial vendors can contain as much as one
g 1000 mg of caffeine.
- Now you may be adapted to that such that it doesn't make
you feel anxious, but if you wonder why you feel irritable and you get a
headache when you don't get that caffeine or that amount of caffeine at
precisely the time that you're used to getting it each day.


That's because you are consuming quite large quantities of caffeine on a regular
basis.
- So I do recommend whether or not you drink soda or coffee or tea that you
figure out the source of that.
- Okay, so figure out what vendor you purchase it
from what kind of coffee and go online and spend a little bit of time because
the information is out there to discover what levels of caffeine you're actually
ingesting.
- Now, if you happen to be ingesting more than 123 mg per kilogram of
body weight of caffeine, that's not necessarily bad.
- However, you do want to be
careful about ingesting very high levels of caffeine over long periods of time
in your life because there can be issues that start to arise in particular a
bias towards higher levels of anxiety and depletion of certain electrolytes
because caffeine is a diuretic can cause you lose sodium and other and other
things of that sort and also just from simply a dependent standpoint, it does
appear that if you ingest high levels of caffeine that is exceeding the dosages
that normally you could get away with and get just as much mental enhancing and
physical enhancing benefits that you can cause some disruption to the micro
vasculature.
- You can bias yourself towards headaches, anxiety attacks and you
can become actually quite irritable when you're not getting those higher levels
of caffeine.
- So I do encourage you to figure out not just what an appropriate
caffeine dosage would be for you, but also how much caffeine you might already
be ingesting.
- The first tool I'd like to talk about is one that I've mentioned
before on this podcast several times And it's something that if you haven't
heard of will be very useful to you.
- And if you have heard this tool before, I'm
going to add some additional features to the description of this tool that
should make this worthwhile for you as well.
- And that is to delay your caffeine
intake 90-120 minutes after waking up on most days.
- And I'll be very clear as
two days in which you might want to ingest caffeine more closely to when you
wake up.
- Why would you want to delay your caffeine intake?


2 90, 220 minutes after waking.
- The answer to.
- That is very simple.
- Many people
wake up in the morning They drink caffeine within 10, sometimes within two
minutes of waking and they feel more alert naturally.
- That makes sense because
of the effects of caffeine in blocking the effects of a dentist that I talked
about earlier and its effects on other neurotransmitter systems.
- But then what
they find is that in the early afternoon, in particular after lunch they
experience a dramatic dip in their overall levels of energy, the so called
afternoon crash and in most cases the way they respond to that is to ingest more
caffeine, which indeed can increase their levels of mood and alertness.
- However,
as we'll soon talk about, there is a problem with ingesting caffeine in the
afternoon if it falls within eight or 10 or dare I even say, 12 hours of going
to sleep and that is the caffeine ingested in the afternoon.
- For most, everybody
would say for 95 plus percent of people disrupts the architecture and quality of
their nighttime sleep and I should say that it doesn't necessarily impact their
ability to fall asleep and maybe even sleep through the night, but that the
depth and quality of that sleep is disrupted by consuming caffeine in the
afternoon.
- A little bit later, I'll talk about how you can offset some of those
negative effects if you absolutely require caffeine in the afternoon, But
there's a huge advantage to restricting your caffeine intake to the early part
of your day, but not consuming caffeine within the 1st 90-120 minutes after
waking.
- In fact, many people find that if they delay their caffeine intake to 90
to 120 minutes after waking up, that they feel more alert in the morning and
they completely avoid that afternoon crash.
- Now that said, many people,
including myself, do need a short nap or non sleep depressed or other form of
relaxation for 10 to 30 minutes in the afternoon.
- That is natural and healthy.


I'm not referring to the need for that.
- When I refer to the so called afternoon
crash, what I'm talking about the afternoon crashes, a inability to recover
energy and focus and a need to consume more caffeine just to make it through the
afternoon By delaying caffeine intake from 2 90 220 minutes after waking.
- There
are a couple of things that are accomplished.
- First of all, you offset that
afternoon crash and this is an effect that many people experienced the very
first time they start delaying their caffeine intake to 90 220 minutes after
waking.
- And the reason this works so well is the following.
- As I mentioned
earlier, a denizen is a molecule that builds up the longer that we are awake, it
is a molecule that is reduced or cleared from our system by sleep.
- So when we
emerge from sleep, regardless of how long we've slept, our identity levels are
lower than they were when we went to sleep the previous night.
- If you slept well
enough and long enough, those identity in levels can be very, very low, but they
are never completely zero when you wake up in the morning, even if you're one of
these people that springs out of bed and is ready to attack the day and here I
am certainly not explain describing myself.
- I'm not not one of those people tend
to wake fairly slowly, but if you're one of those spring up and attack the day
or you're one of the people who moves more slowly into your day regardless,
there's still some residual identity in in your system.
- And this is particularly
the case if you did not get enough sleep or enough depth of sleep the night
before, the the correct ratios of slow wave sleep and rapid eye movement, sleep.
And for those of you interested in optimizing sleep, I'll just refer you to our
master your sleep episode of the Huberman lab podcast, to perfect your sleep
episode, Huberman Lab podcast and we have a toolkit for sleep, all of which are
available zero cost time stamped, etcetera at Huberman lab dot com, you wake up
in the morning and your identity in levels are low, but they're not zero.
- And if
you didn't sleep that well or deeply enough the night before you're going to
have more identity in in your system, you might think the logical thing to do is
therefore to drink caffeine and to block the identity that's there.


But what happens if you do that is, there's an accumulation sort of glut of a
dentist scene that hangs around and then in the afternoon, when the effects of
that caffeine start to wear off, you will experience the so called afternoon
crash.
- As I mentioned earlier, there is a way to clear out the identity that's
present when you wake up in the morning and to clear it out essentially
completely without just blocking its receptors and letting it accumulate or hang
around and the way to do that is to deliberately spike your cortisol.
- Now, many
of you have heard of cortisol, the so called stress hormone as a bad thing and
indeed chronically elevated cortisol is a bad thing.
- It depletes your immune
system, It's bad for psychosocial effects.
- It tends to make us feel anxious and
on and on.
- But cortisol itself is not bad.
- Cortisol is wonderful.
- Cortisol
enhances the efficiency the immune system.
- It makes us alert and focus, it
stimulates our metabolism.
- It does a huge number of positive things provided
that it is released in a circadian fashion, that is at the appropriate times
every 24 hours and that it tends to peak very close to waking.
- In fact, one of
the reasons you wake up in the morning, assuming that you weren't woken up by
some noise or or sleeping in an environment that's too warm, etcetera is that
your cortisol levels start to rise and shortly after waking, your cortisol
levels will start to reach their peak.
- And when I refer to a cortisol pulse,
that's just biology nerd speak for a rise and peak in cortisol.


You want that cortisol pulse to occur early in the day, close to waking and you
want that for a couple of reasons.
- First of all, if you don't restrict that
cortisol pulse too early in the day, it will tend to bleed into the later parts
of the day.
- And actually a late shifted cortisol peak is one of the hallmarks
signatures of depression, low level depression and serious depression and it can
start to disrupt sleep and certainly can disrupt mood metabolism and your immune
system.
- So you want that cortisol peak early in the day, how do you ensure that
that happens? Well, you wake up in the morning and whether or not you're a
bounce out of bed type or you're more groggy, you know, kind of weighed slowly
into the day type like I am, you wake up and you don't ingest caffeine find and
in fact beneficial to hydrate with water and electrolytes terrific.
- In fact, I
would say, necessary to get bright light in your eyes ideally from sunlight.
I've talked about this many many times before on the podcast.
- If you wake up
before the sun comes out, then turn on bright artificial lights, but then
certainly once the sun is out and even on cloudy days.
- In fact, especially on
cloudy days, get outside for anywhere from 5 to 20 maybe even 30 minutes, do
some work outside, take your breakfast outside.
- If you're a breakfast eater, get
something done outside even if it's just to get outside and get bright light in
your eyes.
- Why? Well, because it's been shown in studies on humans that getting
bright light in your eyes in the first hour after waking or as soon as possible
after waking increases the peak of that cortisol pulse by 50% 50.


And that cortisol pulse yes, increases mood, yes, increases alertness.
- But it
does one other very important thing which is that, that through an indirect
pathway it can clear out any residual identity scene that might be present in
your system when you wake up in the morning.
- Again, this is going to be
especially important for those of you that are not getting as much sleep or as
much quality sleep as you would like.
- It's going to be very important for you to
get that morning bright light, ideally from sunlight, get that cortisol peak
going.
- Other ways to increase that cortisol peak would be to do some physical
activity if you don't have time to do a full workout.
- Well then getting some
movement, you know, 10 minutes of skipping rope or even five minutes of skipping
rope or jumping jacks or walking if that's all you have time for ideally while
getting the sunlight in your eyes, but that's going to zero out the identity in
present in your system.
- If however you were to wake up and immediately drink
caffeine caffeine itself can stimulate the release of cortisol a little bit more
than it would otherwise be present in your system.
- But by blocking those
identities in receptors and because of the indirect effects of caffeine on the
cortisol system, you actually are reducing the clearance of a dentist scene that
would otherwise occur.
- So I realize that's a mouthful just to be very clear.
- If
you wake up and you ingest caffeine right away, you're blocking the Tennessean
receptor but you're not clearing it out, you're also preventing cortisol from
having its normal increase in rise such that it can directly clear out a dentist
because cortisol can clear out a dentist scene and that's what you want.
- You
want to be at maximum alertness and focus in your morning and throughout your
day and by delaying your caffeine to 9200 and 20 minutes after waking you set up
your system so that you get that morning cortisol peak ideally a peak.
- That's
even greater because you're getting your bright light viewing and then when you
ingest your caffeine, 9200 and 20 minutes after waking.


Not only will you be craving it just a little bit, but you will be drinking that
caffeine on an already existing backdrop of increased alertness for two reasons
one is a denizen is zeroed out and your cortisol peak is higher and so now when
you ingest caffeine, you can actually ingest levels of caffeine that are a
little more reasonable.
- That almost with certainty are going to fall in this 123
mg per kilogram dosage and will allow you to feel really alert and we'll carry
that alertness well into the afternoon hours without the need to drink more
caffeine and thereby will prevent you from drinking caffeine and disrupting your
nighttime sleep.
- And of course by getting better nighttime sleep, you're going
to zero out your dentist scene even more.
- So what I'm describing here are
essentially two tools, I'm telling you to get morning sunlight and maybe some
exercise in conjunction with that even if it's brief exercise.
- But the main tool
of delaying caffeine, 90-120 minutes After waking has immediate effects, but it
also sets in motion.
- A cascade or Domino falls that lead to better sleep and
more wakefulness the next night and the next day and so on and so forth.
- Now I
realize there are some people who just simply cannot or will not delay their
caffeine, 90 220 minutes after waking for whatever reason.
- First off, let me say
that if you are somebody who likes to wake up and do very intense exercise
within the 1st 90 minutes after waking.
- Well in that case it would be
appropriate to ingest your caffeine just prior to doing that exercise.
- Not a
problem, not a problem, but you should expect that the combination of drinking
caffeine very shortly after waking plus exercising very intensely shortly after
waking will increase the intensity of that early afternoon and afternoon fatigue
that you feel.
- Now for some people that's a great thing.
- They can afford to take
a nap or do non sleep depressed, step away from work and so forth.


In that case, I strongly encourage you to do whatever it is that allows you to
get regular exercise because regular exercise is going to be very beneficial.
- In
fact, we did an entire episode called toolkit for Fitness that describes a
couple of different but really one main structure that allows you to get the
appropriate amount of resistance training and cardiovascular training and
flexibility training throughout the week.
- I happen to follow that program and It
works very well and it does involve some of those workouts to come very early in
the morning, shortly after waking.
- And in those cases I do ingest caffeine just
prior to those.
- So within, you know, 10, 20 minutes of waking.
- However, on other
days I personally delay my caffeine intake 90 220 minutes and I've done that too
great benefit.
- And most people, if not all people that try that have reported
the same, I should mention that some people will find getting out to that 90
minutes to be excruciatingly difficult because they're so accustomed to
ingesting caffeine close to waking up.
- In that case, maybe just push out your
caffeine intake by about 15 minutes each day until you hit that 9200 and 20
minute mark.
- And that will make it much easier.
- Might take you a week or so to
get there.
- But once you get there you'll find it to be quite easy to maintain.
The other thing is that if you are somebody who insists on drinking caffeine
very shortly after waking, I would encourage you to drink half of your caffeine
then and then the other half of your caffeine about an hour later.


That also will help offset some of the afternoon crash.
- For reasons related to
the so called kinetics of caffeine, caffeine has a quarter life of about 12
hours.
- That means that if you were to ingest a cup of coffee at let's say eight
a.
- .
- And let's say 100 mg coffee, just for sake of simplicity, that about 25% of
that caffeine action, we wouldn't really say 25 mg, but about 25% of that
caffeine action will still be present at eight p.
- .
- That night, which is pretty
remarkable.
- So there's a long arc of caffeine effects.
- And this is why it can
impede sleep if it's uh if we take caffeine in the afternoon.
- But again, if
you're somebody who wakes up and you really need caffeine right away and you
refuse to do this 9200 and 20 minute delay thing that I'm talking about.
- Well
then in that case I would drink half of your caffeine upon waking and then a
little bit more or the other half um about an hour later.
- And that will extend
the arc of that caffeine effects such that you don't need it again in the
afternoon because you won't experience the afternoon crash because of the way
caffeine works.
- I should mention that if you ingest caffeine on an empty
stomach, it will have a more potent stimulant effect.
- That will also tend to
increase the level of jitteriness that caffeine can produce later.


I'll talk about ways to offset that jitteriness, but I'll just tell you one tool
now, many people opt to take 100 mg of theon in th E A N I N E nine as a way to
offset some of that jitteriness.
- Theoden will reduce the jitteriness of
caffeine, which is why many energy drink manufacturers and even some coffee
manufacturers are now putting these in in in energy drinks and in ground coffee
because no surprise it allows people to consume more of that beverage and
thereby purchase more of that beverage, which is what these vendors want without
feeling overly anxious and jittery so you can take pill form theon in if you
want with your caffeine.
- I don't tend to do that.
- Rather I control the total
dosage of my caffeine.
- I do tend to consume caffeine on an empty stomach because
I do restrict my caffeine intake to the early part of the day and I generally
eat my first meal somewhere around 11 AM and then I generally eat my last meal
sometime around eight p.
- .
- Or so.
- Those are those are averages I would say plus
or minus an hour.
- And that's not because I'm religiously following any kind of
um time restricted feeding, it's just those that's tends to work best with my
schedule and my appetite.
- But again, that's a general theme.
- There are days in
which I wake up and I'm very hungry and I might ingest something um small snack
or something.
- Or if I'm meeting somebody for breakfast, sometimes I'll have
breakfast, sometimes I won't and so on and so forth.
- The point is that you can
get away with drinking less caffeine to get the stimulant effect if you do it on
an empty stomach and if you're somebody who likes to exercise on an empty
stomach and I'm one of those people, well then ingesting caffeine just prior to
exercise can be a fantastic tool.


A little bit later, we'll talk about some of the physical performance enhancing
effects of caffeine.
- But I'll just briefly jump to a point about that as we
relate to morning exercise.
- If you are somebody who regularly ingest caffeine
and we can define regularly by if you've ingested caffeine every day for the
last two weeks, you're a regular consumer of caffeine whereas if you're somebody
who only ingest caffeine somewhere between two and four times per week, well
then you're not a regular consumer of caffeine, you're an intermittent user of
caffeine.
- If you're somebody who's a regular user of caffeine, the performance
enhancing effects of caffeine are going to be most dramatic if you take two or
three days off from drinking caffeine, which to my mind as I don't want to call
myself, a caffeine addict but a regular caffeine user.
- That's a horrible notion
to me and this subversive notion um because I do like the effects of caffeine so
much.
- But if you really want to see the maximum performance enhancing effects of
caffeine, you will do either one of two things.
- You will either abstain from
caffeine for a few days or three days prior to ingesting caffeine or you will
use caffeine on an empty stomach.
- It's very clear that caffeine on an empty
stomach enhances both the mental and physical enhancing effects of caffeine.
- And
of course all of that has to be stated on the backdrop of consideration that if
you uh you know, you're very very hungry, it can be make it hard to concentrate
and so on and so forth.
- So I'm not encouraging people to starve themselves by
any means uh certainly don't do that.
- But if you want to maximize the
performance enhancing effects of caffeine, you will consume it on an empty
stomach.
- And then as a final point to that caffeine is a diuretic.


It cause us to lose fluid and along with that fluid to excrete sodium because of
the effects of caffeine on various processes within the kidney.
- So one thing
that works very well to maintain mood and alertness longer, given a certain
amount of caffeine intake and to avoid the jitteriness and what can sometimes
feel like a crash or low blood sugar feeling or even blurry vision is to make
sure that you consume at least an equal volume of water with your caffeine.
- And
ideally that water would contain maybe a small pinch of salt or some sort of
electrolyte drink or powder.
- Rather for me I use element full disclosure.
- They
are a podcast affiliate and sponsor but you don't need to do that.
- You could
simply just have a glass of water alongside your your coffee or espresso or your
your Beaumont and just put a small pinch of sea salt in that or even just plain
table salt and that will help offset some of the jitteriness of caffeine.
- A lot
of people think that when they ingest caffeine they get the jitteriness and
crash because their blood sugar is low and while that can be the case.
Oftentimes it's simply because of the excretion of sodium that's occurred when
they've ingested caffeine.
- So I encourage you to hydrate well and to hydrate
with something that contains a little bit of sodium.
- Obviously not so much that
increases hypertension or something of that sort of a small amount of sodium or
an electrolyte drink like element.
- And there's other electrolyte drinks out
there that can accomplish the same of course.
- Just a couple of quick notes about
because there are a growing number of products out there that contains tannin
and there's certainly a growing number of people out there who are using
feminine for the effect that I described before, which is to offset some of the
jitteriness associated with caffeine containing beverages or foods.


And of course I should mention that I've talked about the effects of feminine on
sleep at that sleep toolkit that you can find as a free download.
- You don't even
have to sign up for anything.
- You just download it from Huberman lab dot com.
- Go
to the menu, go to newsletter.
- You'll see the toolkit for sleep.
- You'll see that
the so called sleep stack that I use and recommend includes magnesium three and
eight, something called a pigeon in.
- And Although that sleep stack is designed
to be taken 30-60 minutes prior to sleep and I make the point there and I'll
make it again here that ingesting theon in prior to sleep is not a good idea if
you're somebody who tends to have very vivid dreams, night terrors or night walk
sleepwalking.
- Excuse me, etc.
- In that case eliminate from from the sleep stack.
However, a number of people are using CNN and products are using to offset
jitteriness from caffeine containing products during the daytime daytime
consumption.
- That is a couple of notes about is something that is present in
green tea.
- Right.


It's now been created as a supplement.
- It's what's called a non protein amino
acids.
- So while there are amino acids and proteins are of course amino acids in
non proteins and the indian is one such non protein amino acid theme intends to
stimulate the so called glutamate and glutamine pathway.
- It's actually very
similar to glutamate and glutamine and it has a lot of effects on a lot of
different aspects of the nervous system.
- But the general effect of thiamine is
to compete for the receptors for certain neurotransmitters and the
neurotransmitters I'm referring to are all excitatory neurotransmitters, things
like glutamate and they govern a tremendous amount of our daily thinking and
action and feeling etcetera because their president, so many connections between
neurons in the brain meaning competes for the receptors for glutamate and tends
to reduce our overall levels of alertness.
- So really when people take fenian
along with caffeine, what they're doing is they're really uh taking a slight, I
don't want to call it depressant to the point where it misleads people and makes
people think that it will make you depressed.
- The word is a little bit
misleading but tends to reduce or blunt some of the more excitatory pro
alertness actions of neurons in the brain.
- So when you take it alongside
caffeine tends to quote unquote even things out a bit, I should mention that the
dosages of the Indian that are effective for offsetting the jitteriness of
caffeine is 200-400 mg and the studies that I was able to find showed that
essentially up to 900 mg per day can be safe, but that's a very high dosage of
in fact so much so that it might increase sleepiness to the point where it
wouldn't feel good.
- There are also some positive effects of daytime consumption
of that are independent of reducing the jitteriness of caffeine.
- For instance,
there's a study demonstrating that 17 days of ingesting these at this 204 100 mg
dosage of 1 to 3 times per day can reduce depression and anxiety.
- There are also
some good data out there showing that can have positive effects on endothelial
cells.
- So blood vessels, capillaries and so on and increase some of the function
of blood vessels, allowing them to pass more blood through them, give them a
little bit more elasticity if you will.


So thinning has certain pro sleep effects.
- If it's taken prior to sleep, it can
enhance the quality, depth and duration of sleep again if you're a sleepwalker
or somebody who has extremely vivid dreams from which you wake up in the middle
of the night, Probably best to leave out the a nine or maybe reduce the dosage
down to 100 mg.
- And if that's still too much, then eliminate it completely but
can be terrific for enhancing quality, depth and duration of sleep.
- It can also
reduce the jitteriness associated with caffeine containing beverages and foods
and it has certain antidepressant and pro and epithelial effects.
- That is, it
can offset depression, it can offset anxiety although those are minor effects.
Okay subtle effects and it has been shown to improve endothelial cell that is
vessel and capillary function and structure in ways that can be beneficial for
both brain and body.
- Now, one final point about Canaan that's worth paying
attention to is that the kinetics of the indian are such that you don't need to
take these every time you ingest a caffeinated beverage.
- When we ingest
caffeine, the peak effects of caffeine occur about 30 minutes after we drink it
and there, I'm assuming one takes it all at once and this is a key point that
we'll come back to later right rather than sipping your coffee slowly over a
couple of hours or an hour, if you drink all 200 or 300 mg of caffeine in your
coffee, 600 mg of your coffee.
- If you're getting one of those commercial coffees
and you take these along with it will block some of the jitteriness and anxiety
inducing effects of caffeine that can occur for much longer than the effects
that caffeine last.
- So the peak Anthony occurs about an hour after ingestion, I
suppose if you want to get really fancy and really dial in the kinetics you can
ingest the in in about half hour before you ingest your caffeine.
- But I think
that's getting a little bit excessive in terms of controlling your micro
environment.
- If you will I think it would be perfectly fine too.


Take 100 to 200 mg capsule of thinning along with your coffee or tea and so
forth and just realize that if you drink more caffeine or you extend your
caffeine intake over several hours that you don't necessarily have to take these
repeated times throughout the day.
- I'd like to take a brief break and thank our
sponsor.
- Inside Tracker.
- Inside Tracker is a personalized nutrition platform
that analyzes data from your blood and D.
- N.
- A.
- To help you better understand
your body and help you reach your health goals.
- I've long been a believer in
getting regular blood work done for the simple reason that many of the factors
that impact your immediate and long term health can only be analyzed from
equality.
- Blood test the problem with a lot of blood and D.
- N.
- A.
- Tests out
there however is that you get data back about metabolic factors, lipids and
hormones and so forth.


But you don't know what to do with those data Inside Tracker solves that problem
and makes it very easy for you to understand what sorts of nutritional
behavioral, maybe even supplementation based interventions you might want to
take on in order to adjust the numbers of those metabolic factors, hormones,
lipids and other things that impact your immediate long term health to bring
those numbers into the ranges that are appropriate and indeed optimal for you.
If you'd like to try inside tracker, you can visit inside tracker dot com slash
Huberman and get 20% off any of inside trackers plans.
- That's inside Tracker dot
com slash Huberman to get 20% off.
- Let's talk for a moment about when to avoid
caffeine and in the same stroke, let's also talk about some of the myths around
caffeine.
- For instance, one of the major myths around caffeine is that it can
increase osteoporosis turns out that while there is a relationship of course
between calcium and osteoporosis that is reductions in bone density and it is
the case that caffeine can extract calcium from certain tissues.
- The large scale
studies that are out there essentially prove that if people are ingesting enough
calcium through their diet, which most everybody is, although certainly there
are some people that need to supplement calcium or make it a point to consume
more calcium containing foods.
- But assuming that you are getting adequate levels
of calcium, there is no direct relationship between caffeine intake and
osteoporosis, at least not that I'm aware of.
- I know this was debated for a
number of years in the literature, but the literature seems to have arrived at a
general consensus now that caffeine itself is not going to create or exacerbate
osteoporosis provided people are getting enough calcium through their diet that
is through foods through supplementation.
- Or both.
- Some of the other myths
around caffeine are that, for instance, caffeine will reduce testosterone levels
or will reduce estrogen levels.
- Other myths out there are an exact opposite to
that, that caffeine will increase testosterone levels in particular free
testosterone levels.
- There's been some large scale studies addressing the
hormone effects of caffeine.


They are a little bit difficult to do.
- I should just mention that caveat and the
reason they are difficult to do is because 90% of adults are consuming caffeine
and therefore, you can imagine it's very hard to find a control group to compare
the caffeine consumers to in particular a control group that's well controlled
for other things like lifestyle, diet, exercise, etcetera.
- However, when one
controls as well as one can for all the various factors that could impact
hormones.
- What one discovers is that caffeine intake at least at the dosages we
talked about earlier, 123 mg per kilogram of body weight or even up to double
that, that there are no consistent increases or reductions in testosterone or
estrogen in men or women that can be directly attributed to the caffeine intake.
And I say directly attributed because in these association studies, one always
has to wonder for instance, if because people are ingesting more caffeine, they
have more energy and therefore exercising more and exercise is known to have
effects on testosterone estrogen and other hormones.
- Whether or not the effects
of caffeine on those hormones is indirect and so on and so forth.
- And this all
just underscores the challenges of doing studies on humans in the wild in their
natural habitat of living as opposed to an acute study as it's called to bring
someone into the laboratory and studying them just for those hours or moments.
With all that said, there does appear to be a relationship between caffeine
intake and so called sex hormone binding globulin, which is a protein present in
the body of both men and women that binds to the sex story hormones,
testosterone and estrogen and prevents them from being in their free or active
form.
- It has been shown that ingestion of caffeine even in the sorts of dosage
ranges that are considered safe and that we've been discussing can increase sex
hormone binding globulin such that it can slightly reduce overall levels of free
testosterone and free estradiol in women.
- Now, those effects are relatively
minor, but they do exist If any of you are interested in reading further into
the effects of caffeine on hormones, just refer you to a couple of studies, we
will link to this in the show notes caption, the title of the study is
consumption of caffeinated beverages and serum concentrations of sex steroid
hormones in us men and within this study there's a reference to a equally sized
empowered study done on women, both of which converged on the same conclusion by
examining More than 1000.
- So in this case 1410 men or more than 1000 women that
there are increases in sex hormone binding globulin associated with increased
intake of coffee in particular.
- Um but they were able to narrow that down
specifically to ingestion of caffeine.


So it's not coffee per se that's causing the increase in sex hormone binding
globulin.
- It's actually caffeine itself.
- Now again, the increases in sex hormone
binding globulin were not so significant that at least to my mind, they seem
like a concern, although I think that it is worth noting that if you're going to
consume caffeine that you probably want to consume caffeine in a way that is in
dosages and with the sort of timing that will allow you to get away with
ingesting caffeine but not to access.
- So to derive the benefits of caffeine
without, for instance, driving up sex hormone binding globulin too far now, why
would that be a good idea? Why would you want to make sure that you have enough
free testosterone and free estrogen? Well, some of that is related to the acute
effects of those hormones in terms of well being and libido and strength and
mood etcetera.
- But some of this also relates to the longer term effects of sex
hormones.
- Many people don't realize this, but the sex steroid hormones operate
on the receptors at the surface of cells to have immediate effects.
- But they
also can enter cells and actually go into the nucleus of cells where
the D.
- N.
- A.
- Of those cells are contained and control gene expression in those
cells.


So the sec storied hormones, testosterone and estrogen are controlling a lot of
different cellular functions over long periods of time.
- So blunting their action
over long periods of time is probably not a great idea.
- But again at the dosages
of caffeine that we're talking about today.
- 123 mg per kilogram of body weight
unlikely that the increases in sex hormone binding globulin that one experiences
from that are going to be detrimental and certainly the positive effects of
caffeine that one experiences in terms of mental performance and physical
performance and the fact that it increases energy to do the sorts of things like
exercise that we know can profoundly improve hormone profiles you Twofold or
threefold improvement in hormone profiles.
- In that case it seems that ingesting
caffeine is overall a good thing, provided it's not in excess that also makes
this the appropriate time to mention one of the more impressive effects of
caffeine which is on overall levels of mood and mental health.
- There are several
studies on this but the one that I'm particularly fond of was published in 2019
in psychiatry research and the title of the paper is inverse association between
caffeine intake and depressive symptoms in US adults and these are data from the
national Health and nutrition examination survey.
- And the basic takeaway is that
while of course there are a ton of different factors that are going to relate to
whether or not people are depressed or not life circumstances, genetics and so
on that.
- And here I'm quoting from the study, caffeine psycho stimulant
properties that just means the ability to make us feel more alert and positive
appear to protect against depressive symptoms.
- And of course they acknowledge
that additional studies are needed.
- But this is just one of several studies
pointing the fact that people who regularly ingest caffeine and the appropriate
dosages do seem to enjoy an anti depressive effect.
- Overall, I wouldn't want
anyone to consider caffeine a treatment for severe depression or at least not
alone, a treatment for severe depression but provided the anxiety inducing
effects of caffeine can be kept in check through use of thinning or making sure
that the dosage and the timing of caffeine ingestion is correct.
- Then caffeine
overall seems to be good for our mood and prevent depression or at least keep
depression at bay when depression might otherwise surface or be more severe.


And of course there are the donuts surrounding caffeine intake as it relates to
sleep and to put it very simply sleep that is getting enough quality sleep each
night is the foundation.
- It is the bedrock of mental health, physical health and
performance, sleep and the power of sleep far exceeds any new tropic you could
ever take any prescription drug, you could ever take Any health promoting tool
for your immune system, your metabolism, your mental function, your physical
function, you could ever take sleep is the bedrock.
- I know a lot of people
experience challenge with sleep.
- Nobody is perfect about sleep.
- That's important
to keep in mind.
- I think a good goal is to get enough quality sleep of
sufficient duration, 80% of the nights of your life and then As much as possible
to make sure that the remaining 20% of nights you're not getting enough sleep
for good reasons.
- As opposed to hard reasons.
- Good reasons would include raising
Children.
- That's important after all, every species um desires to make more of
itself and to preserve and extend the well being of its young.
- So child rearing
is a perfectly legitimate reason to get a lack of sleep.
- But you really want to
strive to get quality sleep most nights of your life, which means that even if
you're somebody who can quote unquote, drink an espresso and then fall right
asleep that you avoid caffeine intake in the 12 hours prior to sleep.
- I realize
not everyone will be able to do that.


In fact, I sometimes violate that.
- So I tend to go to sleep around 10 p.
- .
- Every
night, Sometimes 11, occasionally 12 midnight, but usually around 10 p.
- .
- every
night.
- I confess that my last ingestion of caffeine is not always 10 am or prior
to that.
- So sometimes I will have caffeine up until 11 a.
- .
- Or maybe noon.
- And
very very rarely I'll have an afternoon coffee or espresso or non calorie
containing soda or tea or something that's of that sort.
- But I really try to
restrict my caffeine intake to the early part of my day that is before noon.
Given that I go to sleep around 10 p.
- .
- Each night and I strongly encourage
everyone out there to try and limit their afternoon caffeine intake.
- This is
something that dr matt walker who's an expert sleep researcher out of University
of California, Berkeley Psychology and neuroscience department there, author of
the incredible book why we sleep.


He's been on this podcast many other podcasts talking about the importance of
sleep.
- He will remind us and I'll remind you now that the quarter life of
caffeine is 12 hours.
- I mentioned this earlier but I'm going to repeat it again
and that means that if you ingest caffeine at noon 25% of its effects more or
less.
- Okay I'm using broad stroke here to talk about quarter life, 25% of that
is still going to be bio active at midnight that night which will disrupt the
early phase of your night.
- The amount of slow wave sleep which then in turn will
disrupt the amount of rapid eye movement sleep which will disrupt your emotional
processing during the following day and so on and so forth.
- Okay, none of this
is to say if you have the occasional cup of coffee in the afternoon, that's
going to completely demolish your sleep wake cycle forever.
- But I really
encourage people to avoid drinking caffeine in the 12 hours prior to sleep.
- And
if you can't do that within the 10 hours prior to sleep and if you can't do that
within the eight hours prior to sleep, so really try and limit your caffeine
intake in the 8 to 12 hours prior to going to sleep at night.
- And of course,
slow wave sleep take a deep sleep is the sleep that's associated with somewhat
mundane dreams, which makes it sound like it might not be that important, but
it's also the sleep that's associated with growth hormone release, which is
important for protein synthesis, repair of all bodily tissues and metabolism.
And slow wave sleep is also critically attached to your immune system's ability
to clear out bacteria and viruses that might otherwise infect your tissues.
- Now,
I'd like to talk about caffeine and performance and that includes both mental
performance and physical performance.
- Now I'd like to talk about caffeine and
its positive effects on performance when used correctly.


And here we are referring to both mental performance and physical performance.
The exploration of caffeine as a pro performance tool has been explored since
the 1930s, at least that some of the earliest documented literature on this,
although I have to imagine, given that people have been using caffeine for much
longer than that that long ago, somebody realized that by ingesting a certain
plant that they felt much more alertness and were able to hunt and gather or do
any number of different things better and as a consequence decided to consume
more of that plant.
- Now these days we consume a lot of caffeine in the form of
coffee and tea mainly, and some people consume it in the form of caffeine,
tablets or energy drinks etcetera.
- Across the board, one finds that caffeine
intake at a level of 1-3 mg per kilogram of body weight improves reaction time.
That is, it reduces the amount of time to take a physical action or to answer a
question correctly with a verbal response.
- It can also improve coordination.
- It
can also improve memory, although I do want to mention that whereas most studies
of the effects of caffeine on improving mental and physical performance involved
taking caffeine At 12, 3 mg per kilogram of body weight before the mental task
or physical task.
- There is also a pro performance effect of caffeine on memory.
If one takes caffeine after learning certain material or I should say being
exposed to certain material, we'll come back to that in a few minutes.
- If one
examines reaction time, mood, alertness, focus and memory, or the ability to
call up information from memory or physical dexterity, power output, endurance
and overall feelings of well being during exercise and exertion, caffeine has
been shown in numerous studies in both men and women to improve all of those
metrics significantly.
- So this is all just to say that caffeine is an incredible
performance enhancing tool.
- Now, what's not obvious from the statement that
caffeine is a performance enhancing tool across the board and in men and women
and in different context, is that the way in which caffeine is taken is very
important Because 90% or more of adults consume caffeine.


Finding controls for studies of caffeine is really challenging.
- That is finding
people who don't ingest caffeine regularly is a very challenging task for the
researcher and as a consequence, many of the studies of caffeine on human beings
involved depriving regular caffeine users of caffeine and then examining the
effects of caffeine given after a period of say 5-15 days of abstinence in a
person that is essentially experiencing mild withdrawal symptoms because they
haven't had the caffeine that they were used to getting.
- So this is an important
point and it's a point that likely exacerbates the observed pro performance
effects of caffeine.
- Now, all of that isn't necessarily a problem, provided you
keep it in mind.
- And it actually points to a way in which even if you're a
regular caffeine, user, you can extract more of the benefits of caffeine.
- The
simplest way to do this for instance, is to look back to what we talked about
earlier in terms of the need to have most of your cortisol increase restricted
to the hour or hours just after waking in terms of mood and alertness and
performance.
- One of the ways to increase the peak of that cortisol early in the
day is to consume caffeine shortly after that peak occurs.
- And this was really
nicely demonstrated in a study entitled caffeine stimulation of cortisol
secretion across the waking hours in relation to caffeine intake levels.
- We will
provide a link to this study.
- It's a somewhat complicated study because they
looked at a bunch of different times of day for caffeine intake And I should
mention in this study, they use this 300 mg per day or 600 mg per day, so that's
quite high, although for people of sufficient body weight um and who are
accustomed to taking caffeine, it's um certainly not going to be in excess of
what a lot of people out there are taking.
- But basically what they observed was
the following Cortisol responses to caffeine are reduced but not eliminated in
people who consume caffeine on a daily basis.
- What this means is that if you
wake up and as I recommended earlier you avoid drinking caffeine for the 1st
90-120 minutes after waking, but you do get some sunlight or other bright light
in your eyes in that time.


Maybe even get some exercise in that time which would be even better.
- And then
you ingest caffeine, you will get a further increase in Cortisol which Provided
it's restricted to the early part of the day, is a good thing overall for mood
and alertness.
- So this is a simple performance enhancing tool which is to stack
caffeine on the tail of that early Cortisol peak.
- I should also mention however
that in this study they had people do a five day caffeine abstinence prior to
being tested with 300 mg or 600 mg of caffeine.
- So the simple tool to extract
from this and other studies like it is that if you want to experience the
maximum alertness promoting effects of caffeine when you ingest it early in the
day, you would abstain from caffeine for five days and then ingest caffeine 90
to 120 minutes after waking.
- I would still hope that you were doing all the
other things that I described morning sunlight exercise etcetera correctly.
- But
regardless it's very clear that a five day abstinence from caffeine, however
painful that might be will increase the performance enhancing effects of
caffeine when you take caffeine on that sixth day.
- Now, I'm sure many of you out
there are saying, why would I ever want to abstain from caffeine for five days
in order to just get this six day performance enhancing effect.
- Well there's a
couple reasons for doing that perhaps um you're planning to travel to a new time
zone And you want to use caffeine as a stimulant to stay up during the day in
the new time zone.
- That's a somewhat unusual case.
- Others of you might be
interested in the pro physical performance effects of caffeine.
- We'll talk more
about these in a little bit, but you want to get the maximum strength increases
the maximum endurance increase from ingesting.


In this case, 300-600 mg of caffeine.
- Well in that case, abstaining from
caffeine for five days will greatly exacerbate the pro performance effects of
caffeine when you take it on that sixth day.
- Although admittedly, those five
days are likely to be pretty painful if you're a regular caffeine user.
- Another
variation on this however, might be to have the amount of caffeine that you
ingest on a daily basis and then go back to your regular level of caffeine
intake on that day in which you need the caffeine to really boost your mood
energy and performance.
- Another reason why you might want to abstain from
caffeine or reduce your caffeine intake for a period of time and then go back to
your regular caffeine intake is simply to identify how much of an effect
caffeine is really having on your overall level of daily functioning and mood.
This was something that was actually covered in beautiful detail in a book by
Michael pollen all about caffeine.
- It's available on audible.
- I really enjoyed
that book.
- It describes his experience with the decision to completely abstain
from caffeine for a period of months.
- Although I confess that after hearing that
book, what it basically made me want to do is never quit drinking caffeine
because it sounded as if at least my interpretation was that even after several
weeks or months of abstaining from caffeine, that he still fantasized about the
effects of caffeine.
- But he did mention that when returning to ingesting
caffeine after a period of long abstinence, that it had almost a uh let's not
call it a psychedelic property.
- But it had such obvious effects on mood and
alertness and feelings of well being.


That it really highlighted for him the extent to which caffeine normally was
allowing him to just function what he thought was normally.
- So in other words,
many of us don't even really know what our normal basal level of cognitive and
physical functioning is, because we're ingesting caffeine on such a regular
basis.
- I confessed that as much as I enjoyed that book and as intriguing as his
description of caffeine abstinence and then the return to caffeine was I don't
intend to ever find out personally.
- Now, a very good reason why you might want
to abstain from caffeine for a deliberate period of time and then return to
caffeine intake is for its physical performance enhancing effects.
- And here we
can look to a really interesting study title of which is time course of
tolerance to the performance effects of caffeine.
- And what I like about this
study is that while, yes, it does say that abstaining from caffeine and then
returning to caffeine intake can enhance physical performance in a very specific
way.
- It also says that if you take caffeine regularly, you can still see the
physical performance enhancing effects of caffeine, although they are not quite
as robust as they would be had.
- You abstain from caffeine, the Design of the
study is pretty straightforward.
- They had people either ingest three mg per
kilogram of caffeine for 20 consecutive days.
- Many people are already doing
that.
- I realized that they had people do that or ensure that they were doing
that or others ingested a placebo for 20 days.
- So they abstained from caffeine
without realizing it.


Then After that 20 days of either ingesting caffeine or a placebo, their peak
performance was measured in terms of aerobic output.
- But prior to that
measurement they had caffeine, Okay, so it's 20 days of caffeine and then a 21st
day of caffeine and then the physical task on that 21st day or it's 20 days of
abstinence from caffeine and then on day 21 you get caffeine and you get the
same physical test and what they discovered was that the ingestion of caffeine
increased peak performance in this aerobic output dramatically if people had
abstained from caffeine But for people that had consumed caffeine all the way
through up until that day it still was effective to ingest caffeine on day 21
but not as effective as it would have been had they abstained and in fact the
magnitude of the what they call ergo genic effect, which is the pro performance
enhancing effect of caffeine was higher on the first day than in subsequent days
when they allowed people to continue caffeine intake.
- So the takeaway from this
study is really straightforward if you want to get the maximum physical
performance enhancing effects of caffeine, you abstained from caffeine for 20
days.
- Then on day 21 when you're going to do the physical thing the task, you
ingest caffeine about 30 minutes to an hour before you do that physical
challenge.
- 20 days of abstinence is gonna be rough for a lot of people.
- I
certainly don't want to sign up for this study In which case you might want to
do five days of abstinence as we talked about before and then on day six is the
day that you ingest caffeine and do the physical task.
- There are even some
studies showing that you can abstain from caffeine for just two days for just 48
hours.
- And in particular if you are a regular user of caffeine.
- This allows you
to, on day three, ingest caffeine at the dose that's appropriate for you and do
the physical or I should mention mental performance task and perform
significantly better than those that have been taking caffeine throughout the
entire period leading up to the challenge.
- So you don't necessarily need to
abstain for 20 days In order to get the pro performance effects of caffeine on
day 21 you could do five days of abstinence prior or even two days of abstinence
prior or if that's intolerable to you as it is in my mind, to me to just reduce
your caffeine intake slightly or even perhaps have it if you can tolerate that
in the week or two weeks or maybe even three weeks preceding some physical or
mental challenge.
- Again, this sort of implies that you're going up against a
marathon or you're going up against a series of long test, maybe standardized
tests in one day there, I just really want to point out that there is an
abundant literature showing that people perform best on mental tests if they are
in the state that they were when they studied for that material.
- Uh in college,
I knew a number of people who took this to the extreme thinking that if they
were to study under the effects of alcohol that they would be best off um
consuming alcohol prior to taking exams.


And it turns out to not be the case here, We're talking in particular about
psycho stimulant effect of caffeine and other compounds.
- So don't think that you
can drink or be under the influence of THC and then take when you study and then
take an exam under the same influence and do just as well as you would had you
not ingested anything.
- Please don't let that be the takeaway.
- However, do let it
be the takeaway that caffeine's effects are made more potent by a brief to not
so brief period of abstinence, prior to taking a dosage of caffeine.
- And then
the final point to make is that if you are somebody who is not accustomed to
drinking caffeine meaning you're hypersensitive to caffeine or you don't
regularly ingest caffeine, please do not ingest caffeine on the day of any
important mental or physical challenge or performance.
- Because what you will
find is that because you are not caffeine adapted, you will experience changes
in your thermal regulation in your levels of anxiety and jitteriness and your
levels of focus that could be very detrimental to mental or physical
performance.
- So you don't wanna throw yourself in the deep end um by ingesting
caffeine if you're not used to it.
- And I should mention that for people that are
not accustomed to Ingesting caffeine are very sensitive to caffeine, even 25-50
mg of caffeine in the amount that's found in for instance a piece of certain
types of chocolate can actually cause anxiety.
- So be careful they're here.
- I'm
referring only to people that are custom with caffeine intake.
- So what I
recommend is to explore the eugenic effects of caffeine during your training.
And then to make a decision about what you can reasonably and reliably do in
terms of abstinence and then pulse with caffeine on the day of the challenge.


I get a lot of questions as to whether or not caffeine has different effects on
the nervous system and on performance in particular depending on phases of the
menstrual cycle.
- So I explored that in my research for this episode and I found
two studies, both of which we will reference in the show notes, captions.
- The
first one is entitled caffeine consumption and menstrual function.
- So it's
actually the relationship between caffeine and menstrual function.
- We will do an
entire episode about the menstrual cycle.
- Menstrual function.
- But the other one
as it relates to performance was published in 2020 in the european journal
nutrition, which is ergo genic effects of caffeine on peak aerobic cycling power
during the menstrual cycle and the basic takeaway of this study frankly, a very
nice study showed that quote caffeine increased peak aerobic cycling power in
the early follicular prio dilatory and mid Lucille phases of the menstrual
cycle.
- Thus the ingestion and again here they use three mg of caffeine per
kilogram of body mass might be considered an ergot genic aid for women who are
in the menstrual cycle during all three phases of their cycle.
- So keep that in
mind.
- Women for those of you that are regular users of caffeine or you're using
caffeine to enhance physical performance.
- There does not seem to be any
menstrual cycle.
- Phase dependent effects of caffeine on performance.


That is caffeine seems to always increase physical performance regardless of the
phase of the menstrual cycle you might happen to be in.
- I'd like to touch on a
little bit more of the use of caffeine for enhancing mental performance.
- Yes it
is the case That ingesting 123 mg of caffeine per kilogram of body weight in the
30 minutes or so prior to doing a memory task or um sitting down to doing some
studying or learning of any kind, physical or mental performance of any kind is
beneficial for all the reasons we talked about before, related to dopamine and
acetylcholine etc.
- But it turns out that it is also the case that spiking one's
adrenaline and other so called cata cola means.
- So this would be dopamine
norepinephrine and epinephrine after about of learning can greatly enhance
memory for the information that one was trying to learn.
- That's right.
- Spiking
your adrenaline after learning can greatly increase memory for the material
you're trying to learn.
- In fact this is a practice that dates back centuries and
was written about in a beautiful annual review of neuroscience on the biology of
memory by James McGaugh where he talks about medieval practices of Children
being taught information and then being thrown literally into cold water to
stimulate the release of adrenaline and that increases in adrenaline.
- While the
mechanism wasn't completely understood, it was understood that that sort of
shock to the system from the cold water lead to better memory and retention of
the information that these Children had been exposed to.
- And it turns out the
exact same thing is true for adults in the laboratory or kids in the laboratory.
And here I'm not suggesting throwing anyone into cold water if you want to get
into cold water and there's a reason we call it deliberate cold exposure on the
podcast is that it should be deliberate and controlled by you, not by somebody
else.
- If it's controlled by somebody else that might be, you know, military
screening or something.


But here we're talking about deliberately increasing your levels of adrenaline
and other cattle cola means dopamine norepinephrine et cetera.
- You can do that
certainly by deliberate cold exposure with a cold shower or getting in up to
your neck in cold water of any kind.
- But the other way to do that is to spike
your adrenaline by ingesting 123 mg per kilogram of caffeine.
- After sitting down
to try and learn some material.
- I confess that more often than not, I use
caffeine the same way that most people use it.
- Which is okay.
- I'm gonna sit
down, I'm gonna research information for a podcast or assemble um some
information for a paper or Grant and I want to focus.
- So I will drink a cup of
coffee at the beginning of that and maybe even throughout that or a couple of
years ago mate at the beginning or throughout that or I'll sip on one or both
throughout trying to learn and that works quite well in terms of maintaining
focus and alertness and retention of information.
- But it is indeed the case that
is the research supports the fact and I've experienced the fact that if I
abstained from caffeine while I'm trying to learn something, but then I drink
caffeine immediately after, somewhat surprisingly to me.
- But certainly in a way
that's consistent with the research literature, memory for the information that
I was focused on prior to ingesting that caffeine is much greater.
- And here I'm
talking about as a personal anecdote.
- But this is actually what the data point
to both in animals and in humans.


And if you think about it makes perfect sense because the way that the memory
systems of the brain are organized is that we go through life experiencing
things, we encounter surprises, both good and bad.
- We go through the motions of
things, both typical mundane, exciting and and novel and not novel and then
every once in a while something will happen that will spike our cat.
- A cola
means dopamine.
- Typically if it's a positive surprise adrenaline which can be
associated with both positive surprise or positive events and negative events or
surprises and without fail increases in the catacomb amines tend to lock in
memories for things that preceded the increase in those catacombs means again
the cata cola means being dopamine epinephrine and norepinephrine.
- Sometimes all
three in combination.
- Sometimes just two of those.
- Sometimes just one of those
depending on the experience.
- So it makes perfect sense that using caffeine at
the end of a learning about would enhance our memory for the information that
we're trying to learn.
- So if you decide that you want to try and um extract this
performance enhancing effect of caffeine, what I recommend would be to try and
abstain from caffeine for a day or two prior.
- But if you can't to just continue
with your normal caffeine intake.
- But then when you sit down to study or learn
something to not ingest any caffeine as you do that.
- But then afterward to
ingest caffeine.


Now in theory you could probably further enhance the memory encoding effects of
adrenalin and the other cata cola means by drinking caffeine and then taking a
cold shower, doing deliberate cold exposure if you really wanted to or had the
ability to or doing some sort of intense form of exercise.
- And we'll talk in a
moment about how caffeine exercise and the adrenaline system interact.
- But as a
brief but relevant aside brief bouts of intense exercise ranging from 10 to 15
minutes or so.
- Have been shown to improve memory for information that one was
trying to learn prior to the intense exercise.
- This is work from dr Wendy
Suzuki's lab at N.
- Y.
- U.
- As well as other laboratories.
- Some of the work that's
being done at stanford in the mind body laboratories and our laboratory points
in the direction of these kinds of effects as well.
- They all come back to the
same general neurochemical theme which is that when we experience an increase in
these catacombs means that include adrenaline, dopamine and norepinephrine.
- The
memory systems of the brain flip on in a way that tried to capture the
information and the perceptions and the experiences that we were exposed to just
prior to the increase in cata cola means and caffeine but also exercise and also
cold water and of course any of those alone or in combination all increased
levels of cata cola means.
- So it makes perfect logical mechanistic sense as to
why this would work.


And in fact it does work.
- If you want to remember specific information, you
might consider using caffeine as you move through and absorb and are exposed to
that information.
- But you might also consider using caffeine after being exposed
to that information because studies and animals and humans show that that is a
potent way to increase memory for what you were just exposed to.
- I should
mention that what I just described also pushes back on something that I know a
number of people perhaps have heard about and maybe even use which is this
notion of the napa chino.
- I remember hearing about this a few years back.
- It was
uh sort of trend if you will, the trend involved drinking a cup of coffee or
double espresso and then going down for a nap typically in the afternoon and
then waking up.
- And the idea was that the caffeine would hit your system right
at the time that you awake from the nap and that you would be better able to
focus and exercise.
- There are a couple of things about that practice that I
don't like.
- First of all.
- Uh it implies in most cases that you're napping and
ingesting caffeine in the afternoon, which I realize for many students and for
people that are comfortable staying up until the wee hours of the night and then
waking up late the next day might be compatible with their schedule.
- But again,
because of the sleep diminishing effects of caffeine.
- And we talked about
earlier, I'm not crazy about the idea of people ingesting caffeine in the late
afternoon in order to perform better in the late afternoon.


Far better would be to restrict caffeine intake to the early part of the day as
we talked about earlier.
- The other reason is that the data on things like non
sleep depressed and naps in the afternoon.
- And again, the the rule here is that
you don't have to nap, but if you want to nap, it's been shown that naps of 90
minutes or less or non sleep depressed protocols and you can find those for
instance, there's one with me speaking, you just put N str Huberman into
youtube, you can hear that it's completely zero cost.
- There are
other N.
- S.
- D.
- R.
- Scripts out there.
- Now of course if you prefer those that
those can all lead to increases in one of the catacombs means at least.
- Which is
dopamine.
- That's been shown in a really nice uh neurotransmitter labeling study
not from my laboratory but from another laboratory but also can improve mood,
focus and alertness on its own without the need to ingest caffeine prior to
going into those states.
- And in fact ingesting caffeine prior to a nap or
ingesting caffeine prior to N.


S.
- D.
- R.
- Is most certainly going to to reduce the effectiveness of that nap in
   str in restoring natural levels of alertness and focus.
- That would
lead to the performance enhancing effect.
- So I'm not such a fan of the so called
nah pacino, although if any of you out there have derived great benefit from it,
definitely let me know your protocol um and what you've experienced.
- Put it in
the comment section, if you would, I'd appreciate that there's another very
important and potent use of caffeine for enhancing performance.
- And this relates
not just to the dopamine and epinephrine and the arousal inducing effects of
caffeine and it doesn't even just relate to the effect of caffeine on enhancing
frontal lobe function.
- It does include all that but it also includes those
reinforcing effects of caffeine that we talked about at the beginning of the
episode.
- And the best way to illustrate these performance enhancing effects of
caffeine that stem directly from its association with reinforcement is to
highlight a study.
- And the title of the study is blood dopamine level enhanced
by caffeine in men after treadmill running.
- And as the title suggests, this was
carried out in men, but there's no reason to think that the same results
wouldn't also be present in women.

There are some sex dependent effects of caffeine I'll touch on just briefly at
the end, but those are largely present in kids that is adolescents and teens as
opposed to adults.
- So this study is really interesting.
- What they had people do
was run on a treadmill and either ingest caffeine again, three mg per kilogram
of body weight or to not ingest caffeine.
- And then they looked at levels of
dopamine and other neurotransmitters and hormones such as prolactin and
cortisol.
- And the basic takeaway is as the title suggests, that exercise while
on its own can increase cortisol in healthy ways, provided it's not too intense
and too long.
- Little note here if you have trouble recovering from exercise or
you want to continue to derive the benefits from exercise in general.
- Best not
to do high intensity exercise for longer than 75 minutes or 90 minutes probably
being the outer threshold.
- I realize that there are some genetic freaks out.
There are people that are chemically assisted that can recover from very intense
long bouts of exercise.
- But most people don't do well long bouts of intense
exercise on a regular basis and limiting their intense exercise to 60 minutes or
less, that doesn't include the warm up is going to be beneficial.
- See the
episode on toolkit for fitness, if you like, details on that exercise is known
to increase levels of dopamine, cortisol and other cata cola means and
neurotransmitters very potently and things like testosterone and estrogen in
ways that we know are beneficial to us and of course have all these positive
effects on the musculoskeletal system and cardiovascular effects.
- But
unbeknownst to most people ingesting three mg per kilogram of caffeine prior to
exercise further increases the dopamine release associated with exercise
specifically.

- Speaker And this has two important effects.
- First of all, that increase in
dopamine is great because it provides a long lasting increase in focus,
alertness and motivation, not just during the exercise, but also after the
exercise.
- And second it that is caffeine and dopamine and combination act as a
reinforcing her to make the experience of exercise and the period immediately
after exercise more pleasant and in fact reinforcing so in other words, one way
to enjoy exercise more and to enjoy the activities that follow exercise more and
to experience a genuine increase in dopamine that's beneficial for mood and
alertness is to ingest caffeine prior to exercise.
- Now this is important because
a number of people out there are exercising love exercise.
- I love eating great,
love doing all the things that are beneficial for their health.
- But a number of
people out there really don't like to exercise and that serves as a serious
block for their willingness and their consistency to exercise, ingesting
caffeine gives us energy to exercise.
- It increases the release of neurochemicals
and hormones that are good for us during exercise.
- But as I'm highlighting here,
it also increases the reinforcement pathways associated with exercise.
- That is,
it creates a positive feeling about the general theme of engaging in exercise
and it creates a general positive experience of the things that follow exercise.
So I think this if nothing else is a call for or support for the idea that
ingesting caffeine as a performance enhancing tool makes perfect sense.
- But for
those out there that don't enjoy exercise in particular, certain forms of
exercise, ingesting caffeine can change your relationship to that exercise.
- In
other words, make it more positive, much in the same way that ingesting caffeine
alongside a certain taste that would otherwise be neutral or maybe even
negative, can actually make the taste of that particular drink or food positive.

– Speaker So, again, this brings us back to the reinforcing properties of
caffeine that our subconscious, it's not just about the enhanced performance in
the test or the enhanced performance on the treadmill or with the weights in the
gym.
- It's enhanced feelings of mood and well being that are genuine because of
the effect of caffeine on certain neurotransmitter and hormone systems but it
also is creating an overall milieu of reinforcing all of the things that lead
into occur during and occur after exercise.
- I do want to point out something
that's very important as it relates to combining things like caffeine and
exercise in order to increase dopamine.
- This is something that came up in the
episode that I did on Dopamine motivation and Drive which turns out to be one of
our most popular episodes.
- Again you can find that Huberman lab dot com and
links to all formats with timestamps etcetera.
- This also came up in the episode
on A.
- D.
- H.
- D.
- Because of the relationship between A.
- D.
H.

– Speaker
D.
- And dopamine.
- And that's this notion of dopamine stacking in the episode on
   dopamine motivation and drive.
- I pointed out that while there
are a near infinite number of things that can increase dopamine release most
notably positive surprise um or positive anticipation or experiencing a win.
- Um
Certainly their compounds both drugs of abuse food, sex um and certain
supplements that can increase dopamine to varying levels and to varying degrees
both healthy and unhealthy that's all contained in that episode on dopamine
motivation and drive.
- But what I pointed out is that if you're somebody who
tends to experience difficulty with motivation that so called dopamine stacking
as I called.
- It might be something that you want to avoid, What is dopamine
stacking dopamine stacking would be combining, you know, a highly caffeinated
energy drink that also includes the amino acid tyrosine, which is a precursor to
dopamine plus loud music plus getting yourself really ramped up in an intense
workout.
- All of that can be great if you do it every once in a while.
- But what
you will quickly find is that the extent to which your dopamine peaks also
dictates the extent to which your dopamine will drop after that peak.
- And when I
say drop, I mean drop below baseline.
- So a lot of people find that they stack a
lot of things to pique their dopamine that then they experience a low and it
does take some time for them to return to baseline.
- And I highly recommend not
engaging in activities or consuming compounds that are an attempt to accelerate
that return to baseline because all it will do is drive that baseline lower and
lower.

– Speaker So this requires being able to tolerate a drop in dopamine baseline
for a period of time etcetera.
- Now, the reason I'm bringing this up now in the
context of this caffeine episode is I just described a study in which using
caffeine prior to exercise, increases dopamine after exercise.
- And so you might
be saying, especially if you heard that earlier episode, Wait, isn't that
dopamine stacking aren't you encouraging me to stack my dopamine well, in some
sense? Yes, but keep in mind, I'm not suggesting that you do this every time you
exercise.
- So just as in that earlier episode, I emphasized the fact that while
stacking multiple stimuli, right caffeine or energy drinks and music and
etcetera for exercise or for mental work or for any experience for that matter,
is okay to do every once in a while for most people you don't want to get in the
habit of doing it consistently every time you exercise or every time you go out
for instance, and so you really wanna be cautious.
- That is you want to protect
your both baseline levels of dopamine and your peak levels of dopamine that said
for people that want to experience an increase in mood alertness and performance
or who want to condition themselves because that's really what it is.
- It's
conditioning yourself by the reinforcing effects of dopamine too increase your
liking or maybe even your loving of exercise.
- Occasionally using caffeine or
frequently using caffeine prior to exercise is fine, but be very careful and by
being very careful what I mean is pay attention to how you feel in the hours and
days after that dopamine increase wears off.
- So for instance, if you ingest
caffeine and then exercise very intensely and you're feeling great afterwards.
But then eight hours later the next day you're feeling a little bit low, I
suggest you don't go back and do the exact same thing right away.
- I would give
you yourself a little bit of time to let that baseline of dopamine return to
normal.
- So again stacking different things chemical and behavioral in order to
increase dopamine can be done in a safe way that's beneficial to you depending
on your goals.

– Speaker But be careful about not stacking too many stimuli for dopamine too
often.
- That's the key.
- Early In the episode, I mentioned one possible caffeine
consuming schedule that works very well.
- That doesn't fortunately subject you to
long 20 day bouts or five day or even two day bouts of abstinence.
- And that's
the every other day schedule of caffeine.
- If you look at the half life of
caffeine and you look at its effects on the dopamine system and its performance
enhancing effects and how a period of abstinence can in fact increase the
performance enhancing effects of caffeine, but also take into consideration that
caffeine can be habit forming and we can develop a sort of tolerance to
caffeine.
- Well then what emerges from all of that is that Being a person who
consumes caffeine every other day can actually help you maximize most of the
positive effects of caffeine without subjecting you to the kind of misery that
occurs if you're accustomed to consuming caffeine every single day and then
suddenly go into a two or five or 20 day abstinence.
- So I myself have never
tried and every other day caffeine approach, although I'm considering doing it
based on the literature that I've read.
- And I'm considering doing it in a very
specific way, which will be to only consume caffeine on the days in which I
resistance train.
- And since I tend to do that, about three or four days per week
organized in a way that every other day again, if you want to see the exercise
schedule that I follow, including cardiovascular exercise and weight training
and all the reasons and rationale for what I do and how it maps onto the
scientific literature related to health span and lifespan, vitality, etcetera.
You can find that Huberman lab dot com and we had a toolkit for fitness that
ought to be posted um to our website before long, every other day schedule of
caffeine intake To me seems like the most rational one if one wants to maximize
on the performance enhancing effects of caffeine without suffering the effects
of caffeine withdrawal that are associated with being a regular consumer of
caffeine and then stopping caffeine intake such as headache and irritability and
so forth.
- Not I nor anyone in my life wants me to experience those effects and
I'm sure you don't want to experience those effects for you either.

– Speaker So if you're somebody that decides to try the every other day protocol
or you are somebody who's already doing that protocol.
- Please let me know what
your experiences with that are at least by my read of the literature on caffeine
and its performance enhancing effects, but also the effects of caffeine on
neurotransmitter and hormone systems every other day, caffeine's schedule does
seem to be the most rational and scientifically grounded one in order to
maximize on all those effects.
- In addition to so called performance enhancing
effects of caffeine.
- There are also the well studied and now fairly well
mechanistic lee understood pro health effects of caffeine.
- Now here, when I talk
about pro health effects of caffeine, I want to be very clear that if your
schedule of caffeine intake that is your timing of caffeine intake or anything
else for that matter offsets getting regular high quality sleep of sufficient
duration.
- Well then you are undermining the pro health effects of that thing.
This is true for exercise, this is true for caffeine, this is true for
supplementation.
- This is true for prescription drugs.
- Again, you don't wanna be
neurotically attached to the idea that you have to get perfect sleep every night
because that's simply not true.
- But it is absolutely the case that anything
whether or not it's good for you or bad for you in the short term that disrupts
your sleep because of the timing in which you're doing that thing is going to
undermine your immediate and long term health before long.
- So with that said,
there are several well described health promoting effects of caffeine ingestion
And once again when I say caffeine ingestion.
- I'm referring to that 1-3 mg per
kilogram of body weight dosage.

– Speaker There are really nice studies showing that being a regular consumer of
caffeine can help offset some of the probability some of the probability of
developing Parkinson's and maybe alzheimer's related dementia as well.
- These are
not terribly controversial data because of the fact that caffeine is known to
increase the release of those cattle cola means dopamine, epinephrine and
norepinephrine as well as a cto calling all those neurotransmitter and
neuromodulation systems are the ones that are known to be defective in
Parkinson's and alzheimer's although there are other transmitter and hormone
systems that are defective as well.
- There are beautiful reviews on the neuro
protective effects of caffeine and neurodegenerative diseases.
- They're quite
extensive and I'll just refer you to one and the references they're in and we'll
provide a link to this in the show notes captions.
- The title as the topic at
hand suggests, is the neuro protective effects of caffeine and neurodegenerative
diseases.
- This was published in 2016.
- I'm sure there have been other reviews
since then but includes many, many quality references and studies, both in
animals and in humans, pointing to the fact that specific enzymes that are
associated with the health of in particular dopamine neurons are made more
robust by regular ingestion of caffeine.
- It also points to the fact that the
increase in dopamine receptors that is induced by regular ingestion of caffeine
that I referred to earlier is another way in which dopamine.
- However many
dopamine neurons remain around in people with Parkinson's or people who are
aging that lose dopamine neurons naturally.
- That dopamine can have its maximal
effect because of the increase in receptors for dopamine that caffeine induces.
And there are other biological mechanisms that further support why caffeine
ought to be neuro protective, including its effects on the acetylcholine system,
which is one of the major systems disrupted in alzheimer's dementia.
- So in other
words it makes perfect sense as to why caffeine would be neuro protective.

– Speaker Caffeine has also been shown to diminish headache particularly when
taken in combination with aspirin and that's because of the effects of caffeine
and aspirin on blood flow.
- There's also evidence that caffeine can provide brief
but substantial relief from asthma.
- So I wouldn't want people to rely on
caffeine as a life uh Saving approach to an asthmatic attack that said for
people that suffer from minor asthma, that caffeine intake again of the dosages
that we talked about before has been shown to alleviate some of the major
symptoms of asthma for anywhere from 1-4 hours.
- And I know this is of relevance
to a lot of people out there because caffeine increases the cata cola means and
in particular because caffeine increases dopamine transmission in the prefrontal
cortex this area of the brain associated with focus and rule setting and context
and task switching.
- Caffeine is known to improve focus and alertness in
particular in people who have symptoms of a.
- D.
- H.
- D.
- Or other attention and
focus issues.
- Now caffeine alone does not appear to be as potent for the
treatment of A.
- D.
- H.

– Speaker
D.
- As are things like Ritalin, Adderall, modafinil and our modafinil and vivants
   if you would like a sort of head by head comparison of
prescription drugs, supplements and things like caffeine as well as coverage of
behavioral tools and nutritional tools etcetera.
- That can positively offset some
of the symptoms of A.
- D.
- H.
- D.
- Please see the episode that I did on A.
- D.
- H.
- D.
Again that's available at Huberman lab dot com in all formats.
- But that said
caffeine does increase focus and it does it through a number of different
mechanisms not the least of which is to increase dopamine transmission in the
forebrain.

– Speaker Just as a drug like Ritalin or Adderall would although not to the same
extent as a drug like Ritalin or Adderall does.
- Before we close today, I do want
to just briefly return to the reinforcing effects of caffeine that we talked
about earlier.
- This study on the honeybees that showed that bees prefer certain
sectors because they contain caffeine even though they are not aware that those
nectars contain caffeine.
- They just come to like the feeling that those nectars
provide them so much that they associate that in a subconscious way with the
flowers themselves and they come to like those flowers or human beings.
- For
instance Children that ingest caffeinated beverages come to adore the taste of
those beverages and beautiful studies have been done that describe how Children
and adults truly cannot distinguish between the taste of a caffeinated and non
caffeinated beverage and caffeine can be placed into essentially any beverage in
order to give us a preference for that beverage or food.
- In fact, the studies
have been done with yogurt.
- If you put caffeine into yogurt of different
flavors, even plain yogurt, which most kids don't like.
- They will come to prefer
whatever flavor contain the caffeine even if then you remove the caffeine from
that flavor.
- Now eventually their preference for that flavor will be
extinguished.
- But all of this is just to say that so many of the things that we
like whether or not it's coffee or tea or given flavor of food or given
experience or even exercise occur because we ingest caffeine in conjunction with
those activities.
- Now these are not tricks that your nervous system plays on
you.
- These are real neurochemical reinforcing effects.

– Speaker And I think that we would all do well to think about and to leverage
these reinforcing effects much in the same way we would do well to think about
and hopefully not leverage aversive effects of certain compounds.
- Right? The
simple way to put this is I or anyone could get you to dislike something.
Someone or some place by making you feel slightly less good, lower mood.
- I don't
even have to make you feel nauseous but less good after ingesting something or
having a certain kind of interaction or being in a certain environment very
straightforward to do that because of the way that your nervous system is wired
for conditioning.
- However, there's the positive side of all this which is that
it's very straightforward to reinforce the experience of a given food including
its taste, but all the context around the container, the texture, the people you
consume it with where you consume it etcetera for instance, I wonder why we are
not pairing caffeine with broccoli and here I'm not suggesting that people
actually do that experiment or play that trick on people.
- But you have to sort
of imagine that if caffeine is this incredible reinforce er of all sorts of
things in particular things that we ingest and would want to ingest more of if
it's paired with caffeine.
- Well then you actually can use caffeine as a tool to
increase reinforcement of different things and you can avoid caffeine as a way
to further reinforce things that you would like to stop And here I'd like to
just give the example of sugar cravings.
- A lot of people ask me, how do I avoid
sugar cravings? I've talked about the use of l glutamine for that.
- I've talked
about making sure you're getting enough essential fatty acids and essential
amino acids as a way to reduce sugar cravings, please note however that if you
are somebody who likes to have your sugar whether or not it's a piece of
chocolate or your dessert etcetera.
- I'm not saying that's bad.

– Speaker But if you're trying to reduce your sugar cravings, ask yourself are
you ingesting sugar along with caffeine? Could be the caffeine contained in that
sugar containing foods like chocolate or it could be that you're having a cup of
coffee along with your pastry and then you're struggling with sugar cravings.
Well, think about it.
- You're not just being reinforced by the sugar and the
effects of sugar on dopamine, which are real and both conscious and subconscious
through the gut to the brain, dopamine system and direct on the brain dopamine
system.
- But by co ingesting caffeine, you are also further enhancing the
reinforcing effects of sugar.
- The flip side to all of this is that you could use
caffeine as a way to increase your appetite for certain things.
- Actually know
somebody I won't reveal who this person is, but they are quite prominent
podcaster who ingests 125, mg of caffeine in tablet form in tablet form along
with herbal tea and use this as a way to develop a preference for herbal tea
because they found that coffee was giving them other effects that weren't good
for them.
- So it works quite well in animals and it works quite well in insects
and it works quite well in humans, I suppose animals, insects and humans are all
animals at the end of the day.
- So no surprise there.
- But it all underscores the
sense to which caffeine is an absolutely fascinating molecule.
- I mean it's an
ability to offset the sleepiness system if you will.
- This a dentist in system
and to control our schedules in that way to essentially take a withdrawal
against the bank.

– Speaker That is a dentist in and then pay that back later in the form of
getting sleepy later as opposed to when we want to be alert.
- Its ability to
enhance focus, alertness and mood and if taken after trying to learn something
and remember it to enhance memory especially and its ability to increase vo two
max increased strength.
- We didn't even talk today about it but I'll just briefly
mention that caffeine ingested the sorts of doses we talked about earlier
because its effects on the neuro muscular system and the calcium system
associated with neuro muscular exertion and fatigue can increase peak power
output and muscle contract ability enhancing performance there as well.
- And of
course caffeine does a number of other things just generally related to our
overall and basal level of mood and alertness, not the least of which are.
- These
increases in dopamine.
- So caffeine is really an incredible molecule.
- It's
affecting all these various neurotransmitter systems but not haphazardly.
- It's
increasing dopamine and acetylcholine in the forebrain to increase attention.
It's reducing fatigue it's improving mental and physical performance for some
obvious and some not so obvious reasons and what I think is among the more
miraculous and powerful effects of caffeine.
- It is a potent, potent, potent
reinforce er of things foods people and experiences and it's one that you can
leverage in any direction that you like.
- Once you understand the way that
caffeine exerts those reinforcing properties.
- So today I've really tried to
cover as much as I could about the mechanisms of caffeine action in the brain
and body, as well as tools and schedules and dosages in which you can leverage
caffeine in order to meet your physical performance, mental performance and
frankly mental health and overall health goals.

– Speaker If you're learning from and or enjoying this podcast, please subscribe
to our Youtube channel, that's a terrific.
- Zero cost way to support us.
- In
addition, please subscribe to the podcast on both Spotify and Apple and on both
Spotify and Apple.
- You can leave us up to a five star review if you have
questions for us or comments about the podcast or guess that you'd like me to
interview on the Huberman Lab podcast, please put those in the comments section
on Youtube.
- We do read all the comments in addition, please check out the
sponsors mentioned at the beginning and throughout today's episode.
- That's the
best way to support this podcast if you're not already following Huberman lab on
social media.
- We are Huberman lab on all platforms so that's instagram twitter
linkedin and facebook and all of those places.
- I describe science and science
related tools, some of which overlap with the contents of the Huberman lab
podcast, but much of which which is distinct from content on the Huberman lab
podcast.
- So again it's Huberman Lab on all social media platforms during today's
episode and on many previous episodes of the Huberman lab podcast, we discuss
supplements while supplements aren't necessary for everybody, many people derive
tremendous benefit from them for things like sleep hormone augmentation and
focus.
- If you'd like to see the supplements discussed on various episodes of the
hubert podcast, please go to live momentous dot com slash Huberman.
- We partnered
with Momentous because they are extremely high quality they ship internationally
and they formulated supplements in the precise ways that are discussed as
optimal to take for various outcomes here on the Huberman Lab podcast.
- If you
haven't already subscribe to the Huberman Lab podcast newsletter, it is a
monthly newsletter that includes summary of podcast episodes as well as tool
kits, all of which are completely zero cost.

All you have to do is provide your email to sign up, we do not share your email
with anybody.
- You do this by going to Huberman Lab dot com.
- Go to the menu and
tap down to newsletter, provide your email, you'll get a confirmation link,
click on that link and you'll receive our monthly newsletters and you can also
access any of the previous newsletters that we've released, including the
toolkit for sleep, for fitness, deliberate cold exposure and so on by going to
Huberman lab dot com, going to the menu, going to newsletter and there you'll
see those as immediately downloadable PDFs.
- Thank you for joining me for today's
discussion about caffeine, both its mechanisms and its many powerful uses.
- And
last but certainly not least.
- Thank you for your interest in science.
* Resources
** 2023-06-05 ◦ [[https://www.hubermanlab.readablepods.com/p/effects-of-caffeine][Effects of Caffeine: Improved Mental and Physical Performance]]
*** Caffeine Benefits for Mental & Physical Performance

Caffeine is a staple in the daily routine of most adults, consumed at regular
intervals throughout the day.

In fact, many people feel the effects of caffeine withdrawal if their intake is
delayed even by a few minutes.

This has led some to believe that caffeine is addictive or harmful. However,
research suggests that caffeine has numerous benefits for both mental and
physical performance.

One of the main benefits of caffeine is its neuroprotective effects. Caffeine
increases the levels of neuromodulators such as dopamine and norepinephrine,
which are responsible for increasing alertness, motivation, and drive.

Studies show that regular caffeine intake is inversely related to levels of
depression, suggesting that it may have antidepressant effects, either directly
or indirectly.

Caffeine also improves mental and physical performance.

Thousands of studies have shown that caffeine reduces reaction time, making us
quicker to respond to stimuli. In laboratory studies, participants who ingested
caffeine 30 minutes before a task showed significant improvements in reaction
time. Additionally, caffeine can improve physical performance by increasing
endurance and reducing muscle pain.

It's important to note that the effects of caffeine on mental and physical
performance can be further enhanced by consuming it at regular intervals while
working.

Ingesting caffeine in pill form or drinking it quickly will result in an
increase in alertness within 5 minutes, peaking at 30 minutes and lasting for up
to 60 minutes.

*** Caffeine Effects on Brain; Reward Pathways

Caffeine is a naturally occurring substance that can be found in certain plants
and flowers.

It is known for its ability to improve alertness, memory, and reaction time in
humans. However, recent research has shown that caffeine also acts as a powerful
reinforcer of experience.

This means that not only does caffeine make the drink or food that contains it
more appealing, but it also enhances the experience of the person or object
associated with it.

In a recent study titled "Caffeine in Floral Nectar Enhances a Pollinator's
Memory of Reward," scientists have discovered that caffeine in nature acts as a
reinforcer for bees that are consuming nectar from different flowers.

The researchers found that bees are more likely to remember the location of a
flower that contains caffeine in its nectar, which in turn, helps them to
efficiently gather nectar and pollen for their hive.

It is important to note that caffeine is a bitter substance, and in high
concentrations, it would be unappealing to most insects and animals.

However, in nature, caffeine is present in low concentrations or is masked by
other flavors in flowers and plants, making it more palatable.

*** Caffeine, Adenosine & Reduced Sleepiness 

Caffeine is a methylxanthine, which is a plant alkaloid that is bitter in taste.

It is found in many plants and is consumed by bees and humans in small amounts,
despite its bitter taste.

Caffeine binds to adenosine receptors, which are found in different parts of the
brain and body.

Adenosine makes us feel tired because it taps into the ATP pathway, which is
responsible for energy production in the brain and body.

When caffeine binds to adenosine receptors, it prevents adenosine from breaking
down certain components of the energy production pathway.

This results in increased cyclic AMP, which leads to increased energy levels.
However, it is important to understand that caffeine does not actually create
more energy in the body. Instead, it changes the timing of when sleepy and
energetic signals are received.

It is also important to note that when we wake up after a good night's sleep,
our adenosine levels are at their lowest.

To get the most benefit from caffeine, it is best to avoid consuming it for the
first 90 to 120 minutes after waking, as this allows for the complete clearing
of adenosine from the body.

However, for most people, adenosine levels will accumulate throughout the day,
making them feel more sleepy.

The only way to offset this is by blocking the function of adenosine through the
consumption of caffeine.

*** Morning Exercise & Residual Caffeine Effects


Dr. Huberman understands that some people cannot or will not delay their
caffeine intake for 90 to 120 minutes after waking.

For those who like to wake up and do intense exercise within the first 90
minutes after waking, it is appropriate to ingest caffeine just before the
exercise.

However, it is important to note that this combination of drinking caffeine
shortly after waking and exercising intensely will increase the intensity of the
afternoon fatigue.

For some people, this is not a problem as they can afford to take a nap or do
non-sleep deep rest, step away from work, etc.

In that case, Dr. Huberman strongly encourages regular exercise as it is
beneficial for overall health.

He follows a workout program that involves some early morning workouts shortly
after waking and in those cases, he ingests caffeine just before the workout.

On other days, Dr. Huberman delays his caffeine intake for 90 to 120 minutes and
has found it to be beneficial. Most people who try this have also reported the
same.

For those who find it difficult to delay their caffeine intake, Dr. Huberman
suggests pushing out the caffeine intake by 15 minutes each day until they reach
the 90 to 120 minutes mark. This might take a week or so, but once they get
there, it will be easy to maintain.

For those who insist on drinking caffeine shortly after waking, Dr. Huberman
suggests drinking half of the caffeine upon waking and the other half an hour
later. This will help offset some of the afternoon crash.

Caffeine has a quarter-life of about 12 hours, which means that if you were to
ingest a cup of coffee at 8 a.m., about 25% of that caffeine action will still
be present at 8 p.m. that night.

This is why it can impede sleep if we take caffeine in the afternoon. By
drinking half of the caffeine upon waking and the other half an hour later, it
will extend the effects of caffeine, preventing the need for more caffeine in
the afternoon and avoiding the afternoon crash.

*** Theanine: Effects & Dosage


Dr. Huberman has previously discussed the effects of theanine on sleep in his
"Toolkit for Sleep" which can be downloaded for free from his website,
hubermanlab.com.

The "sleep stack" he recommends includes magnesium threonate, apogenin, and
theanine and should be taken 30 to 60 minutes before sleep.

However, Dr. Huberman advises against taking theanine before sleep if you tend
to have vivid dreams, night terrors or sleepwalking.

Theanine has a calming effect and can be used to offset jitteriness from
caffeine-containing products during the day.

It stimulates the glutamate and glutamine pathway and competes for the receptors
of excitatory neurotransmitters like glutamate, reducing overall levels of
alertness.

The effective dosage for offsetting jitteriness from caffeine is 200 to 400
milligrams and studies have shown that up to 900 milligrams per day can be safe,
although this may cause sleepiness.

Theanine has other positive effects as well.

A 17-day study showed that consuming 200 to 400 milligrams of theanine one to
three times per day can reduce depression and anxiety.

There is also evidence that theanine can have positive effects on endothelial
cells and increase the function of blood vessels, allowing them to pass more
blood through them and increase elasticity.

*** Other Effects: Osteoporosis, Hormone Levels, Depression


When it comes to caffeine, there are several myths circulating about its effects
on our bodies.

One of the most common is the idea that caffeine can increase the risk of
osteoporosis.

While it is true that caffeine can extract calcium from certain tissues,
large-scale studies have shown that if individuals are getting enough calcium
through their diet, there is no direct relationship between caffeine intake and
osteoporosis.

Another myth surrounding caffeine is that it can reduce hormone levels, such as
testosterone or estrogen.

However, large-scale studies have found that at moderate levels of caffeine
intake, there are no consistent increases or reductions in hormone levels in men
or women that can be directly attributed to caffeine consumption.

It's important to note that these studies are difficult to conduct because of
the high percentage of adults who consume caffeine, making it difficult to find
a control group.

Additionally, caffeine intake has been found to have a slight impact on sex
hormone-binding globulin, a protein present in both men and women that binds to
sex steroid hormones, preventing them from being in their free or active form.

Studies have shown that caffeine intake can increase sex hormone-binding
globulin, which can slightly reduce overall levels of free testosterone and free
estradiol in women. However, these effects are relatively minor.

Overall, while caffeine can have some minor effects on hormone levels and bone
density, it is important to keep in mind that these effects are relatively small
and can be mitigated by ensuring that you are getting enough calcium through
your diet.

*** Afternoon Caffeine & Sleep


Sleep is the foundation of mental and physical health, and it is essential to
getting enough quality sleep each night.

While it is understandable that some people may have difficulty getting enough
sleep, the goal should be to get enough quality sleep for 80% of the nights of
your life, and to make sure that the remaining 20% of nights without enough
sleep are for good reasons, such as child rearing.

To ensure that you get the best quality sleep, it is important to avoid caffeine
intake in the 12 hours prior to sleep.

This means that even if you are someone who can drink an espresso and fall right
asleep, you should still avoid caffeine in the 12 hours leading up to your
bedtime.

The ideal time to have your last caffeine intake is before noon, if you go to
sleep around 10 p.m. every night.

It is important to note that the quarter-life of caffeine is 12 hours, meaning
that 25% of its effects will still be active at midnight after you ingest it.

This can disrupt the early phase of your night, the amount of slow-wave sleep,
and the amount of rapid eye movement sleep. This can also disrupt your emotional
processing during the following day.

To avoid disrupting your sleep-wake cycle, it is best to avoid drinking caffeine
in the 12 hours prior to sleep, and if you can't do that, try to limit your
caffeine intake in the 8-12 hours prior to going to sleep at night.

Slow-wave sleep, also known as deep sleep, is the sleep associated with growth
hormone release, which is important for protein synthesis, repair of all bodily
tissues, and metabolism. It is also critically important for your immune
system's ability to clear out pathogens.

In summary, it is important to avoid caffeine intake in the 12 hours prior to
sleep, and to strive to get quality sleep most nights of your life.

This will ensure that you are able to get the benefits of deep sleep and the
release of growth hormones, which are essential for maintaining good physical
and mental health.

*** Caffeine, Performance & Menstrual Cycle


Caffeine is a widely used stimulant that can improve mental and physical
performance.

Some people may wonder if caffeine has different effects on the nervous system
and performance, depending on the phase of the menstrual cycle.

Recent research has explored this question and found that caffeine can enhance
physical performance during all three phases of the menstrual cycle.

One study, entitled "Caffeine Consumption and Menstrual Function," looked at the
relationship between caffeine and menstrual function.

Another study, published in the European Journal of Nutrition in 2020, titled
"Ergogenic Effects of Caffeine on Peak Aerobic Cycling Power During the
Menstrual Cycle," found that caffeine increased peak aerobic cycling power
during the early follicular, pre-ovulatory, and mid-luteal phases of the
menstrual cycle. The study used a dosage of 3 milligrams of caffeine per
kilogram of body mass.

The findings of these studies suggest that for women who are regular users of
caffeine or use caffeine to enhance physical performance, there does not seem to
be any menstrual cycle phase-dependent effects of caffeine on performance.

In other words, caffeine seems to always increase physical performance,
regardless of the phase of the menstrual cycle.

*** Caffeine & Naps


There is a trend known as the *nappuccino*, which involves drinking a cup of
coffee or double espresso and then taking a nap, typically in the afternoon,
with the idea that the caffeine will hit your system right when you wake up from
the nap and you will be better able to focus and exercise. However, there are a
few things that are not ideal about this practice.

First, it implies that in most cases, people are napping and ingesting caffeine
in the afternoon.

This is not ideal because caffeine can have sleep-diminishing effects and it is
better to restrict caffeine intake to the early part of the day.

The other reason is that the data on things like non-sleep deep rest and naps in
the afternoon shows that naps of 90 minutes or less, or non-sleep deep rest
protocols, can lead to increases in one of the catecholamines, dopamine, and can
improve mood, focus, and alertness on its own without the need to ingest
caffeine prior to going into those states.

In fact, ingesting caffeine prior to a nap or non-sleep deep rest will most
certainly reduce the effectiveness of the nap and non-sleep deep rest in
restoring natural levels of alertness and focus that would lead to the
performance-enhancing effect.

*** Dopamine Stacking

Dopamine stacking is a technique that involves combining various stimuli, such
as caffeine and exercise, to increase dopamine release in the brain.

This technique was discussed in an episode of the Huberman Lab podcast, which is
one of the most popular episodes on the show. The episode highlighted the fact
that while there are many things that can increase dopamine release, there are
also certain compounds and activities that can increase dopamine to varying
levels and to varying degrees, both healthy and unhealthy.

However, for those who tend to experience difficulty with motivation, dopamine
stacking may not be the best approach.

Dopamine stacking can lead to a peak in dopamine levels, but it also leads to a
subsequent drop in dopamine levels below baseline.

This requires being able to tolerate a drop in dopamine baseline for a period of
time.

In the context of caffeine and exercise, a recent study has shown that using
caffeine prior to exercise increases dopamine after exercise.

While this may seem like dopamine stacking, it is important to keep in mind that
this should not be done consistently every time you exercise.

Instead, it should be done occasionally to increase mood, alertness, and
performance, or to condition yourself to increase your liking or even your love
of exercise.

However, it is important to be cautious when using caffeine before exercise and
to pay attention to how you feel in the hours and days after the dopamine
increase wears off.

If you experience a low after eight hours or the next day, it is best to avoid
doing the same thing again in the future.

*** Scheduling Caffeine to Maximize Its Effects

The schedule Huberman suggests is an every other day schedule, where you consume
caffeine on alternate days.

This is based on the half-life of caffeine, its effects on the dopamine system,
and its performance-enhancing effects.

He also suggests that a period of abstinence can increase the
performance-enhancing effects of caffeine.

Andrew Huberman himself has never tried an every other day caffeine approach,
but he is considering doing it based on the literature he has read.

He is also considering consuming caffeine only on the days when he resistance
trains, which he does about three or four days per week.

He believes that this schedule seems like the most rational one if one wants to
maximize the performance-enhancing effects of caffeine without suffering the
effects of caffeine withdrawal, such as headaches and irritability.

He encourages readers to try the every other day protocol and to let him know
their experiences with it.

*** Pro-Health Effects of Caffeine


One of the most well-established pro-health effects of caffeine is its ability
to lower the probability of developing Parkinson's and Alzheimer's related
dementia.

This is likely due to caffeine's ability to increase the release of
neurotransmitters and neuromodulators that are known to be defective in these
diseases.

A 2016 review titled "The Neuroprotective Effects of Caffeine and
Neurodegenerative Diseases" provides an extensive overview of the studies in
animals and humans that support this claim.

Additionally, caffeine has been found to be effective in reducing headaches when
taken in combination with aspirin, and providing brief but substantial relief
from asthma.

However, it is important to note that caffeine should not be relied upon as a
life-saving approach for asthma attacks.

The recommended dosage for these pro-health effects is one to three milligrams
per kilogram of body weight.

*** Wrapping Up
Caffeine is a widely consumed substance that has numerous benefits for both
mental and physical performance. 

Studies have shown that caffeine increases neuromodulators such as dopamine and
norepinephrine, which are responsible for increasing alertness, motivation, and
drive. 

Additionally, caffeine has been shown to reduce reaction time, improve
endurance, and reduce muscle pain. 

Caffeine also acts as a powerful reinforcing agent, making the drink or food
that contains it more appealing and enhancing the experience of the person or
object associated with it. 

However, it is important to note that excessive caffeine intake can lead to
negative effects and it's important to consume it in moderation.
