:PROPERTIES:
:ID:       67080028-4f04-4174-a2ae-60022d293cc3
:END:
#+authors: [[Nicola Schmidt]]
#+created: 20191124120807668
#+finished_month: 02
#+finished_year: 2020
#+genres: Education Parenting
#+goodreads: https://www.goodreads.com/book/show/27410360-artgerecht---das-andere-baby-buch
#+isbn: 9783466346059
#+lang: de
#+date: 2021-05-18
#+publication_title: Artgerecht - Das andere Baby-Buch
#+publication_type: book
#+revision: 0
#+slider: hide
#+status: todo
#+filetags: :book:
#+title: Artgerecht
#+tmap.id: 5c8aac50-40ee-482d-83b6-444d8411759b
#+type: text/vnd.tiddlywiki

#+begin_quote
Seit der Steinzeit haben unsere Babys dieselben Bedürfnisse: Nähe, Schutz, Getragensein, essen dürfen, wenn sie hungrig sind, und schlafen dürfen, wenn sie müde sind. Unsere moderne Welt jedoch passt nicht immer zu diesen Bedürfnissen. Wie Eltern dennoch dem biologischen Urprogramm ihrer Kinder gerecht werden können, zeigt dieses Buch: konkret, ermutigend, undogmatisch und nachhaltig.

(Quelle: [[https://www.randomhouse.de/Buch/artgerecht-Das-andere-Baby-Buch/Nicola-Schmidt/Koesel/e473926.rhd]])

#+end_quote
* Notes
** Artgerecht - Note 1                                                         :quote:done:
#+begin_quote
Wir lassen unser Baby an 7 Tagen pro Woche 24 Stunden in Windeln, füttern mit der Flaschem nutzen den Schnuller auch noch nach dem 8. Monat als Beruhigung, legen es im Kinderwagen ab und lassen es allein schlafen. Es scheint auf den ersten Block alles leichter, aber wir handeln uns je nach Veranlagung unseres Kindes später eine Menge Arbeit ein: Wir müssen ihm die Windeln und den Schnuller - oft mit viel Mühe - wieder abgewöhnen, es ist öfter krank, es bekommt womöglich einen platten Hinterkopf und braucht unter Umständen einen Helm, es kommt auch als Schulkind noch nachs ins Elternbett, kurz: Es entwickelt sich nicht optimal, wir müssen ständig nachbessern.
#+end_quote

** Artgerecht - Note 2                                                         :quote:done:
#+begin_quote
Das perfekte Baby wäre doch eigentlich dieses: Es will etwa 4 am Tag stillen, 8 Stunden pro Nacht tief schlafen, immer friedlich im Kinderwagen liegen, es kann Bescheid sagen, wenn es mal muss, sieht ansonsten süß aus und entwickelt sich prächtigt.
#+end_quote

** Artgerecht - Note 3                                                         :quote:done:
#+begin_quote
Im Stamm der Lakota war jeder gern bereit, Kinder zu betreuen. Ein Kind gehörte nicht nur einer bestimmten Familie an, sondern der großen Gemeinschaft der Sippe. Sobald es gehen kontte, war es im ganzen Lager daheim, denn jeder fühlte sich als sein Verwandter. Meine Mutter erzählte mir, dass ich als Kind oft von Zelt zu Zelt getragen wurde und sie mich an manchen Tagen nur hier und da zu Gesicht bekam. (Quelle: Häuptling Luther Standing Bear)
#+end_quote

** Artgerecht - Note 4                                                         :quote:done:
#+begin_quote
Geboren wird nicht nur das Kind durch die Mutter, sonder auch die Mutter durch das Kind. (Quelle: Gertrud von Le Fort)
#+end_quote

** Artgerecht - Note 5                                                         :quote:done:
#+begin_quote
Stellen SIe sich vor, es gibt keine Zeit, keiner Vergangenheit und keine Zukunft. Sie machen eine lebensbedrohliche und anstregende Reise in die Welt und kommen völlig erschöpft auf diesem neuen Planeten an. Sie kennen sich hier nicht aus, und plötzlich ist es kälter, eventuell heller und lauter. Wie würde es sich anfühlen, jetzt unter Fremden zu sein, ohne zu wissen, wann diese Einsamkeit endet? Wie würde es sich anfühlen, die Wärme und Geborgenheit der vertrauetn Mutter zu spüren und den Herzschlag und den Körperkontakt zu genießen? (Quelle: Bastian Barucker)
#+end_quote

** Artgerecht - Note 6                                                         :quote:done:
#+begin_quote
Während amerikanische Eltern Schlaflieder, Geschichten, spezielle Kleidung, Baden und Spielzeug nutzten, um Schlaf zu ritualisieren, ließen Maya-Eltern ihre Babys einfach einschlafen, wenn sie eben einschliefen, ohne weiteren Zinnober. (Meredith Small)
#+end_quote

** Artgerecht - Note 7                                                         :quote:done:
#+begin_quote
Babys schlafen anders als Erwachsene. Wir gehen ins Bett, fallen in Tiefschlaf und haben dann einige Schlafzyklen mit sehr tiefem Schlaf und Traumphasen. [...] Babys schlafen anders - denn sie brauchen nachts Nahrung für ihr schnelles Wachstum und in zu tiefem Schlaf können sie auf potentiell gefährliche Situationen nicht reagieren (nasse Windel, Kälte, Hitze oder Atemaussetzer).
[...]
es dauert unter Umständen bis zum 9. oder 10. Monat, bis das Baby einen eigenen zirkadianen Rhythmus etabliert hat. Babys brauchen etwa 20 Minuten bis sie in ihrer ersten Tiefschlafphase angekommen sind, sie verbringen dort nur vgl. kurze Zeiten, haben daher mehr und kürzere Schlafzyklen und lernen erst von uns, diese einzelnen zu einer andauernden Episode zu verbinden.
#+end_quote

** Artgerecht - Note 8                                                         :quote:done:
#+begin_quote
Es gibt nicht den Menschenschlaf. Das Konzept, 8 Stunden durchzuschlafen und den Rest des Tages zu arbeiten, ist weder natürlich noch normal. Diese Klare Trennung zwischen Tag und Nacht ist etwas, was wir uns ausgedachr haben,weil es gut in unsere Industriegesellschaft passt.
#+end_quote

** Artgerecht - Note 9                                                         :quote:done:
#+begin_quote
Aufgeweckt werden und gut gut schlafen sind Konstrukte. Kulturübergreifende Beobachtungen zeigen: In westlichen Kulturen ist die Idee vom Durchschlafen weiter verbreitet als in allen anderen. Hier wird auch das Wecken durch das Kind am dramatischsten empfunden. In anderen Kulturen ist das schon deshalb nicht so schlimm, weil man Schlaf ja jederzeit nachholen kann.
#+end_quote

** Artgerecht - Note 10                                                        :quote:done:
#+begin_quote
Die Gründe liegen auf der Hand: Es ist eine wunderbare Möglichkeit, der Mutter Entlastung zu verschaffen und eine enge Bindung zum Kind aufzubauen. Vater und Kind sind in unmittelbarem Kontakt, in ständiger, kuscheliger Kommunikation, und Papa hat ein enormes Selbstwirksamkeits- und Kompetenzgefühl, wenn er es schafft, das quengelige, überreizte kleine Wesen in einen seligen Schlaf zu tragen.
#+end_quote

** Artgerecht - Note 11                                                        :quote:done:
#+begin_quote
Obwohl das Nervensystem bei der Geburt noch nicht ausgereift ist, haben menschliche Babys das Bedürfnis, trocken und sauber zu sein. Sie weinen nicht nur bei vollen Windeln, sie merken und signalisieren schon vor ihrem Geschäft, dass sich im Bauch etwas tut, und Eltern können darauf reagieren. Das ist keine ominöse Veranlagung asiatischer oder afrikanischer Babys, alle Neugeborenen verhalten sich so.
#+end_quote

** Artgerecht - Note 12                                                        :quote:done:
#+begin_quote
Jean McKellar erzählte mir von ihren Jahren in Uganda, wo ihr Mann als Arzt praktizierte. Die Mütter aus der Gegend brachten ihre Kinder zur Untersuchung und warteten oft stundenlang geduldig in der Schlange. Sie trugen die Babys nackt im Sling, dennoch waren sowohl Mutter als auch Baby stets sauber. Als Jean fragte, wie sie das machten, sagten sie, dass sie einfach mit den Babys in den Busch gehen, wenn diese mal müssten. Als sie fragte: Aber woher wisst ihr wann sie mal müssen?, fragten sie nur verständnislos zurück: Woher weisst du denn, wann du mal musst?
#+end_quote

** Artgerecht - Note 13                                                        :quote:done:
#+begin_quote
Hätten Sie es gewusst:

- Die erste Einmalwindel aus Papier stammt aus den 50ern
- Die erste Pampers kamm 1961 auf den amerikanischen Markt (auf dem deutschen erst 1973)
- EIn Baby braucht im Durchschnitt 50k Wegwerfwindeln
- Die Anzahl Wegwerfwindeln, die in DE täglich in den Müll wandern, beträgt 8.5 Millionen
- Der jährliche Umsatz beträgt in DE 500 Millionen EURO
- In US 3 Milliarden US-Dollaer
- Ein Baby produziert beim Vollzeitwickeln bis zum Sauberwerden etwa 1,5 Tonnen Windelmüll
- Eine Wegwerfwindel braucht 500 Jahre, um zu verroteten
#+end_quote

** Artgerecht - Note 14                                                        :quote:done:
#+begin_quote
Die Frau, die arbeitet, und die Frau, die bei ihrem Kind ist, war immer ein und dieselbe Person. (Quelle: Herbert Renz-Polster)
#+end_quote

** Artgerecht - Note 15                                                        :quote:done:
#+begin_quote
All unsere Sinne wurden und werden immer noch bereits in der ganz frühen Kindheit im Freien geschärft: durch Wind und Wetter, durch Geräusche in der Natur, durch gefärbte Hände von Beerensammeln, druch Berühren von Wasser, Erde, Stöcken oder durch den Geruch von Regen, Schnee und Feuer.
#+end_quote

** Artgerecht - Note 16                                                        :quote:done:
#+begin_quote
Familien brauchen auf jeden Fall einen Clan, der sie unterstützt und in dessen Kreis sie sich sicher fühlen. Sie brauchen gesellschaftliche Wertschätzung, Zeit und die Freiheit, sich um ihre sozialen Belange ausreichend kümmern zu können. Was sie nicht brauchen, sind Zeitdruck, Geldsorgen und Leistungsdruck.
#+end_quote

** Artgerecht - Note 17                                                        :quote:done:
#+begin_quote
Wenn ich nach meinen Vorträgen und Seminaren Eltern frage, was sie davon abhält, mit ihrer Familie artgerecht zu leben, dann lauten die Gründe: [...]
Wir weichen dem aus, indem wir weniger schlafen, hektischer essen, mehr arbeiten, eine traditionelle Aufgabenverteilung wählen (einer arbeitet, einer hütet die Kinder) oder ähnliche Modelle leben. Ich nenne es das Heidi-Klum-Printip: Du musst dich nur genug anstrengen!
#+end_quote

** Artgerecht - Note 18                                                        :quote:done:
#+begin_quote
Was dich zu einem Mann macht, ist nicht deine Fähigkeit, ein Kind zu haben, sondern die Courage, es großzuziehen (Barack Obama)
#+end_quote

** Artgerecht - Note 19                                                        :quote:done:
#+begin_quote
De Vries schlussfolgerte aus diesem tragischen Geschehen, dass ein schwieriges Temperament ein evolutionärer Vorteil sein könnte. Laute, intensive und anhaltend schreiende Babys werden auch in Hungerzeiten gefüttert und getragen. In unserer Überflussgesellschaft gilt solches Verhalten als schwierig, in einer Mangelgesellschaft wäre das Attribut eher stark oder überlebenswillig.
#+end_quote

** Artgerecht - Note 20                                                        :quote:done:
#+begin_quote
Es braucht ein Dorf, um ein Kind zu erziehen(Afrikanisches Sprichwort)
#+end_quote

** Artgerecht : 226 - 226                                                      :quote:done:
#+begin_quote
Dass eine Mutter ihr Baby allein betreut, ist bei einer kooperativ aufziehenden Art wie der unsrigen nicht sinnvoll. Mütter, die den ganzen Tag mit ihren Babys allein sind - ohne andere Verwandte oder Freunde -, befinden sich in einer Ausnahmesituation, auch wenn dies bei uns die Regel ist. Wir merken das daran, dass den meisten Müttern sehr bald die Decke auf den Kopf fällt. Das gilt auch, wenn Papa und Mama zusammen sind. Die Kleinfamilie ist ebenfalls kein artgerechtes Setting, sie schafft eine Belastungssituation, je nach Temperament des Babys auch einer Überlastungssituation.
#+end_quote
