:PROPERTIES:
:ID:       8d4b1325-b284-45d6-a99d-bed176a67a6e
:END:
#+title: Atomic Habits
#+filetags: :productivity:book:
#+date: 2020-11-01

* Atomic Habits
- in general *you get what you repeat*
  - the more you repeat a behaviour, the more your brain will change to become efficient at that activity (see [[#Hebb's%20Law][Hebb's Law]])
- don't focus on goals, *focus on systems* instead
  - goals are for setting the direction
  - systems are best for making progress
  - sometimes you spend to much time thinking about the goals
  - thus there is not enough time for designing your systems
- there are no good or bad habits
  - there are only *effective* habits
  - habits solve problems (even the bad ones)
  - "good habits" lead to good habits (similar to [[id:ba41119d-e928-40e8-b5dd-b077e2b0ac7d][Diderots Effect]]))
- challenges with changing habits
  - you try to change the wrong thing
  - you try to change your habits in the wrong way
  - most people have *outcome-based* habits
    - the focus is on /what you want to achieve/
  - true behaviour change is an *identity change*
    - you focus on what you wish /to become/
    - if you believe in a certain aspect of your identity, you're more likely to *act* in alignment with that belief
      - examples
        #+begin_quote
        The goal is not to read a book, the goal is to become a reader. The goal is not to run a marathon, the goal is to become a runner. he goal is not to learn an instrument, the goal is to become a musician.
        #+end_quote
* Notes
*** 4 Laws of Behaviour Change                                                  :note:
:PROPERTIES:
:CREATED:  Tue Jun 08 2021 10:36:22 GMT+0200 (Central European Summer Time)
:TAGS:     Definition
:END:
- 4 Laws of Behaviour Change
  - Cardinal Rule
    - what is rewarded is repeated
    - what is punished is avoided
  - Cue
    - Make it obvious
    - The /inversion/: Make it invisible
      - reduce exposure to the cue that causes the bad habit
    - also see [[id:7e028eb7-acd6-473d-9aad-8d74c63b7dac][The Premacks Principle]] for temptation bundling
    - [[https://jamesclear.com/implementation-intentions][Implementation intention]] still works quite well
    - also make sure you [[https://jamesclear.com/choice-architecture][architecture your environment]] wisely in order to form new habits
  - Craving
    - Make it attractive
    - use /reframing/ to make habits more attractive
      - you don't /have/ to; you /get/ to
      - change burdens/difficulties into opportunities
    - timing is also crucial
      - coz habits are attractive when you actually have the energy to do them
      - and your energy levels depend on the time of the day
      - it's better to perform a habit early in the day
  - Response
    - Make it easy
    - reduce /friction/ associated with a habit
  - Reward
    - Make it satisfying
    - habits are dopamine-driven feedback loops
    - same reward system is activated when you /anticipate/ the reward
    - don 't focus on the result
      - focus on how it makes you feel

*** 4 step model of habits                                                      :note:
:PROPERTIES:
:CREATED:  Tue Jun 08 2021 10:39:20 GMT+0200 (Central European Summer Time)
:TAGS:     Definition
:END:
- 4 step model of habits
  - Cue
    - triggers your brain to initiate a behaviour
    - it predicts a reward
  - Craving
    - the motivational force behind every habit
      - motivation, desire etc.
    - you don't *crave* the habit itself but the sensation/emotion in delivers
  - Response
    - the actual habit
    - it can be a /thought/ or an /action/
  - Reward
    - the goal of every habit
    - we chase rewards because
      - they /satisfy/
      - they /teach/

*** Habit Tracking                                                              :note:
:PROPERTIES:
:CREATED:  Tue Jun 08 2021 10:38:34 GMT+0200 (Central European Summer Time)
:TAGS:     Definition
:END:
- Habit Tracking
  - creates a visual cue that reminds you to act
  - you see the progress and that motivates you
  - it feels satisfying whenever you add a new successful record
  - but it's only useful when it /guides/ you and not consuming you
  - also read about [[https://jamesclear.com/paper-clips][paper clip strategy]]

*** The Big Five                                                                :note:
:PROPERTIES:
:CREATED:  Wed Dec 16 2020 19:22:16 GMT+0100 (Central European Standard Time)
:TAGS:
:END:
- personality is a set of characteristics that doesn't change regarding the situation
- "Big Five" is the most proven scientific analysis of personality traits which break down into 5 /spectrums/
  - openness to experience
    - from curious and inventive on one end to cautious and consistent on the other.
  - conscientiousness
    - organized and efficient to easygoing and spontaneous.
  - extroversion
    - outgoing and energetic to solitary and reserved
  - agreeableness
    - friendly and compassionate to challenging and detached.
  - neuroticism
    - anxious and sensitive to confident, calm, and stable

* Quotes
** Atomic Habits - Note 1                                                      :quote:done:
#+begin_quote
Here’s how the math works out: if you can get 1 percent better each day for one
year, you’ll end up thirty-seven times better by the time you’re done.12
Conversely, if you get 1 percent worse each day for one year, you’ll decline
nearly down to zero. What starts as a small win or a minor setback accumulates
into something much more.
#+end_quote


** Atomic Habits - Note 2                                                      :quote:done:
#+begin_quote
In 1936, psychologist Kurt Lewin wrote a simple equation that makes a powerful
statement: Behavior is a function of the Person in their Environment, or B = f
(P,E)
#+end_quote

** Atomic Habits - Note 3                                                      :quote:done:
#+begin_quote
Your brain did not evolve with a desire to smoke cigarettes or to check
Instagram or to play video games. At a deep level, you simply want to reduce
uncertainty and relieve anxiety, to win social acceptance and approval, or to
achieve status.
#+end_quote

** Atomic Habits - Note 4                                                      :quote:done:
#+begin_quote
- Find love and reproduce = using Tinder
- Connect and bond with others = browsing Facebook
- Win social acceptance and approval = posting on Instagram
- Reduce uncertainty = searching on Google
- Achieve status and prestige = playing video games
#+end_quote
** Atomic Habits - Note 5                                                      :quote:done:
#+begin_quote
The most effective form of learning is practice, not planning. Focus on taking
action, not being in motion
#+end_quote

** Atomic Habits - Note 6                                                      :quote:done:
#+begin_quote
Standardize before you optimize. You can’t improve a habit that doesn’t exist.
#+end_quote

** Atomic Habits - Note 7                                                      :quote:done:
#+begin_quote
In our Data Driven world, we tend to overvalue numbers and undervalue anything
ephemeral, soft, and difficult to quantify. We mistakenly think the factors we
can measure are the only factors that exist. But just because you can measure
something doesn’t mean it’s the most important thing. And just because you can’t
measure something doesn’t mean it’s not important at all.
#+end_quote

** Atomic Habits - Note 8                                                      :quote:done:
#+begin_quote
The greatest threat to success is not failure but boredom. We get bored with
habits because they stop delighting us. The outcome becomes expected. And as our
habits become ordinary, we start derailing our progress to seek novelty. Perhaps
this is why we get caught up in a never-ending cycle, jumping from one workout
to the next, one diet to the next, one business idea to the next. As soon as we
experience the slightest dip in motivation, we begin seeking a new strategy—even
if the old one was still working.
#+end_quote

** Atomic Habits - Note 9                                                      :quote:done:
#+begin_quote
The only way to become excellent is to be endlessly fascinated by doing the same
thing over and over. You have to fall in love with boredom.
#+end_quote

** Atomic Habits - Note 10                                                     :quote:done:
#+begin_quote
Satisfaction = Liking – Wanting

This is the wisdom behind Seneca’s famous quote, “Being poor is not having too little, it is wanting more. If your wants outpace your likes, you’ll always be unsatisfied. You’re perpetually putting more weight on the problem than the solution.
#+end_quote
