:PROPERTIES:
:ID:       0C99DE6D-1001-4E6E-8991-14FC2238C53D
:END:
#+title: Brave New World
#+filetags: :scifi:book:
#+date: 2025-03-11

👉 https://www.goodreads.com/book/show/5129.Brave_New_World

* Notizen
** S.5
#+begin_quote
Ein allgemeines Bild mussten sie schließlich schon haben, wenn sie qualifizierte Arbeit
leisten sollten – allerdings, da aus ihnen ja gute, glückliche Mitglieder der Gesellschaft
werden sollten, eben so allgemein wie nur möglich. Denn der Schlüssel zu Tugend und Glück
liegt, wie wir wissen, im Besonderen; das Allgemeine ist ein intellektuell notwendiges
Übel. Nicht Philosophen, sondern Laubsäger und Briefmarkensammler bilden das Rückgrat der
Gesellschaft.
#+end_quote
** S.8
#+begin_quote
Einer der Studenten aber war so unvorsichtig zu fragen, worin denn dabei der Vorteil
liege. »Mein lieber Junge!« Der Direktor schoss sich sofort auf ihn ein. »Verstehen Sie
denn nicht? Verstehen Sie nicht?« Er hob mit feierlich ernster Miene die Hand.
»Bokanowskis Verfahren ist ein Hauptinstrument gesellschaftlicher Stabilität!«
Hauptinstrument gesellschaftlicher Stabilität. Genormte Männer und Frauen in konstanten
Mengen. Aus einer einzigen bokanowskifizierten Eizelle die Belegschaft eines mittelgroßen
Werks. »Sechsundneunzig identische Zwillinge bemannen sechsundneunzig identische
Maschinen!« Die Stimme bebte förmlich vor Begeisterung. »Da weiß man doch wirklich, was
man hat. Zum ersten Mal in der Geschichte.« Er zitierte den planetarischen Wahlspruch:
»Kollektivität, Identität, Stabilität.« Große Worte. »Könnten wir endlos
bokanowskifizieren, alle unsere Probleme wären gelöst.«
#+end_quote
** S.184
#+begin_quote
»Ja, wieso nicht?«, wiederholte Helmholtz die Frage. Auch er vergaß die unerfreuliche
Realität der Situation. Grün vor Sorge und unguter Ahnung, behielt nur Bernard sie im
Blick, doch ihn beachtete niemand. »Wieso nicht?« »Weil unsere Welt nicht die Welt
Othellos ist. Für Flivver benötigt man Stahl, für Tragödien gesellschaftliche
Instabilität. Heute aber ist die Welt stabil. Die Menschen sind glücklich, sie haben
alles, was sie wollen, und nie wollen sie, was sie nicht haben können. Es geht ihnen gut,
sie leben in Sicherheit, sie sind niemals krank, sie fürchten den Tod nicht, sie wissen
nichts von Leidenschaft, nichts vom Altern, sie werden nicht von Müttern und Vätern
geplagt, sie haben keine Ehefrauen, keine Kinder, keine Lieben, denen ihre Gefühle gelten,
sie sind so konditioniert, dass sie praktisch nicht anders können, als sich zu verhalten,
wie sie es sollen. Und wenn irgendetwas schiefgeht, gibt es Soma. Das Sie im Namen der
Freiheit zum Fenster hinauswerfen, Mr Savage. Freiheit!« Er lachte. »Von Deltas zu
erwarten, dass sie wüssten, was Freiheit ist! Und überdies von ihnen zu verlangen, dass
sie Othello verstehen. Mein Bester, also wirklich!
#+end_quote
** S.223
#+begin_quote
»Ja, wieso nicht?«, wiederholte Helmholtz die Frage. Auch er vergaß die unerfreuliche
Realität der Situation. Grün vor Sorge und unguter Ahnung, behielt nur Bernard sie im
Blick, doch ihn beachtete niemand. »Wieso nicht?« »Weil unsere Welt nicht die Welt
Othellos ist. Für Flivver benötigt man Stahl, für Tragödien gesellschaftliche
Instabilität. Heute aber ist die Welt stabil. Die Menschen sind glücklich, sie haben
alles, was sie wollen, und nie wollen sie, was sie nicht haben können. Es geht ihnen gut,
sie leben in Sicherheit, sie sind niemals krank, sie fürchten den Tod nicht, sie wissen
nichts von Leidenschaft, nichts vom Altern, sie werden nicht von Müttern und Vätern
geplagt, sie haben keine Ehefrauen, keine Kinder, keine Lieben, denen ihre Gefühle gelten,
sie sind so konditioniert, dass sie praktisch nicht anders können, als sich zu verhalten,
wie sie es sollen. Und wenn irgendetwas schiefgeht, gibt es Soma. Das Sie im Namen der
Freiheit zum Fenster hinauswerfen, Mr Savage. Freiheit!« Er lachte. »Von Deltas zu
erwarten, dass sie wüssten, was Freiheit ist! Und überdies von ihnen zu verlangen, dass
sie Othello verstehen. Mein Bester, also wirklich!
#+end_quote
