:PROPERTIES:
:ID:       742d5cb7-cf9b-4fae-981f-1ea6efada208
:END:
#+title: Buddha und die Wissenschaft vom Glück
#+filetags: book
#+date: 2017-09-01

* Buddha und die Wissenschaft vom Glück
:PROPERTIES:
:FINISHED: 2017-09
:END:
** Description
#+begin_quote
Der vom Dalai Lama erwählte jüngste tibetisch-buddhistische Meister berichtet: Eine spannende Mischung aus Autobiographie, Meditationstechniken und neuesten wissenschaftlichen Erkenntnissen.

Mingyur Rinpoche lebte als Exiltibeter zunächst in Indien. Bereits mit 17 Jahren jüngster tibetischer Meditationsmeister, galt er als „Wunderkind“. Als der Dalai Lama vor Jahren gebeten wurde, für umfangreiche neurologische Untersuchungen über die Wirkung von Meditation einen Kandidaten zu benennen, fiel seine Wahl auf Mingyur Rinpoche. Die Genialität des vorliegenden Buches liegt vor allem in seiner Fähigkeit, wissenschaftliche Genauigkeit mit verständlichen, teils humorvollen Erklärungen der buddhistischen Perspektive und praktischen Unterweisungen zu verbinden. Neben seiner philosophischen Perspektive finden wir erprobte Meditationsanleitungen, die neugierig machen auf die „Früchte“ am Ende des Weges.

(Quelle: https://www.lovelybooks.de/autor/Yongey-Mingyur-Rinpoche/Buddha-und-die-Wissenschaft-vom-Gl%C3%BCck-144605890-w/)
#+end_quote
* Quotes
** Buddha und die Wissenschaft vom Glück - Note 1                              :quote:done:
#+begin_quote
Hat man erst einmal gelernt, über sich selbst zu lachen, gewinnt jeder Aspekt von Erfahrung eine gewisse Heiterkeit.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 2                              :quote:done:
#+begin_quote
Er war der Buddha, ein Wort aus dem Sanskrit, das »der Erwachte« bedeutet.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 3                              :quote:done:
#+begin_quote
Die direkte Erfahrung der Natur des Geistes auch nur versuchsweise in Worte zu fassen, ist praktisch unmöglich. Bestenfalls lässt sich sagen, dass sie unermesslich friedvoll und praktisch unerschütterlich ist, wenn sie erst einmal durch Wiederholung stabilisiert worden ist. Es ist eine Erfahrung des absoluten Wohlseins, das alle physischen, emotionalen und mentalen Zuständen durchdringt und durchstrahlt – auch jene, die man normalerweise als unangenehm bezeichnen würde.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 4                              :quote:done:
#+begin_quote
Das Maß, in dem wir uns dem Wohlergehen anderer widmen, wird uns tausendfach mit Gelegenheiten entgolten, zu lernen und uns weiterzuentwickeln. Jedes freundliche Wort, jedes Lächeln, das wir jemandem schenken, der vielleicht einen schlechten Tag hatte, kommt auf völlig unerwarteten Wegen zu uns zurück.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 5                              :quote:done:
#+begin_quote
Dass wir ein Phänomen nicht genau lokalisieren oder definieren können, bedeutet nicht, dass es nicht existiert. Es bedeutet nur, dass wir noch nicht ausreichende Informationen gesammelt haben, um ein arbeitsfähiges Modell erstellen zu können.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 6                              :quote:done:
#+begin_quote
Je genauer die Wissenschaftler die geistige Aktivität erforschen, desto stärker nähern sie sich dem buddhistischen Verständnis an, wonach der Geist ein sich ständig entwickelndes und entfaltendes Ereignis ist und keine eindeutige, eigenständige Entität.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 7                              :quote:done:
#+begin_quote
Buddhisten und moderne Wissenschaftler sind sich einig, dass der Geist das Merkmal ist, wodurch sich alle fühlenden – oder bewussten – Wesen von anderen Organismen wie etwa Gräsern oder Bäumen unterscheiden, und schon gar von Dingen, die wir nicht unbedingt als etwas Lebendiges ansehen würden wie zum Beispiel Steine, Bonbonpapier oder Zementblöcke.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 9                              :quote:done:
#+begin_quote
Ohne dass wir auch nur einmal bewusst über sie nachdenken, blockiert die Vorstellung, nichts an unserem Geist oder Bewusstsein ändern zu können, jeden Versuch, es auch nur mal zu probieren.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 11                             :quote:done:
#+begin_quote
In neurowissenschaftlichen Begriffen bezeichnet man die Fähigkeit, alte neuronale Verbindungen durch neue zu ersetzen, als neuronale Plastizität.

[...]

Auf der rein zellularen Ebene bedeutet das unterm Strich, dass wiederholte Erfahrung die Arbeitsweise des Gehirns verändern kann. Und das ist das Warum, das hinter dem Wie der buddhistischen Belehrungen steht, die sich mit dem Ausräumen von mentalen, dem Unglücklichsein förderlichen Gewohnheiten befassen.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 13                             :quote:done:
#+begin_quote
Die erste und älteste dieser Schichten, die man den Hirnstamm nennt, besteht aus einer knollenförmigen Gruppe von Zellen, die direkt oben aus dem Rückenmark hervorgeht. Diese Schicht wird auch als Reptiliengehirn bezeichnet, weil sie insgesamt dem Gehirn vieler Reptilienarten ähnelt. Der Hauptzweck des Reptiliengehirns besteht in der Regulierung so elementarer automatisierter Funktionen wie der Atmung, des Stoffwechsels, Herzschlags und Kreislaufs.

[...]

Diese als limbisches System (oder limbischer Lappen) bezeichnete Schicht umgibt den Hirnstamm wie eine Art Helm und beinhaltet eine Reihe einprogrammierter neuraler Verbindungen, die den Impuls zur Fürsorge stimulieren – das heißt, Nahrung für die Jungen herbeizuschaffen, sie zu beschützen und über das Spiel und andere Übungen die wesentlichen Überlebensfähigkeiten zu lehren.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 15                             :quote:done:
#+begin_quote
Der tibetisch-buddhistische Begriff für Geist ist sem, ein Wort, das man mit »das, was weiß« übersetzen könnte. Dieser einfache Begriff kann uns die buddhistische Sicht auf den Geist besser verstehen lassen. Ihr zufolge ist der Geist nicht so sehr ein spezifisches Objekt, sondern vielmehr eine Fähigkeit, die es uns ermöglicht, unsere Erfahrungen und Wahrnehmungen zu erkennen und über sie nachzudenken.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 16                             :quote:done:
#+begin_quote
Wenn ich jeden Gedanken, jedes Gefühl, jede Empfindung, die mir durchs Bewusstsein strichen, beobachtete, löste sich die Illusion von einem begrenzten Ich oder Selbst auf und wurde durch ein Gewahrsein ersetzt, das sehr viel ruhiger, weiträumiger und gelassener ist.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 17                             :quote:done:
#+begin_quote
Das Grundanliegen, das alle Wesen miteinander teilen – Menschen, Tiere und Insekten gleichermaßen – ist der Wunsch, glücklich zu sein und Leiden zu vermeiden.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 18                             :quote:done:
#+begin_quote
Weil die wahre Natur aller Lebewesen bereits völlig frei von Leiden und mit vollkommenem Glück ausgestattet ist: Indem wir nach Glück streben und Leiden zu vermeiden suchen, bringen wir – ganz gleich, wie wir die Sache angehen – nur die Essenz dessen, der wir sind, zum Ausdruck.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 19                             :quote:done:
#+begin_quote
Das sehnliche Verlangen nach dauerhaftem Glück, das die meisten von uns empfinden, ist die »leise innere Stimme« des natürlichen Geistes, die uns an das erinnert, was wir in Wirklichkeit zu erfahren und zu erleben vermögen.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 20                             :quote:done:
#+begin_quote
In der Nichtmeditation beobachten wir einfach nur, was passiert, ohne uns einzumischen. Wir sind lediglich interessierte Beobachter bei einer Art introspektivem Experiment, ohne aber daran interessiert zu sein, wie das Experiment ausgeht.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 21                             :quote:done:
#+begin_quote
Wenn Sie in einem beliebigen Moment Ihre Aufmerksamkeit einfach auf dem Geschehen in Ihrem Geist ruhen lassen, dann ist das Meditation, was auch immer Sie dabei erfahren oder erleben. Einfach in dieser Weise ruhig zu verweilen ist die Erfahrung des natürlichen Geistes.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 22                             :quote:done:
#+begin_quote
Wenn ich nur Leerheit bin, dann bin ich im Grunde nichts, und es gibt auch nichts, was mich davon abhalten könnte, mich einfach ins Nichts aufzulösen.«
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 23                             :quote:done:
#+begin_quote
»Ich glaube, ich fange an, die Leerheit zu verstehen.« Ich bat ihn um eine Erklärung. »Ich folgte Ihren Anweisungen, und nachdem ich lange über das Thema meditiert hatte, erkannte ich, dass die Leerheit nicht das Nichts ist, weil irgendetwas da sein muss, bevor nichts da sein kann. Die Leerheit ist alles und jedes – alle vorstellbaren Möglichkeiten von Existenz und Nichtexistenz, die sich gleichzeitig ereignen. Wenn also unsere wahre Natur Leerheit ist, dann kann man von niemandem sagen, dass er, sie oder es wirklich stirbt, und kann man von niemandem sagen, dass er, sie oder es wirklich geboren wird, weil die Möglichkeit des Seins und des Nichtseins in jedem Moment in uns gegenwärtig ist.«
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 24                             :quote:done:
#+begin_quote
Form ist Leere, Leere ist Form; Leere ist nichts anderes als Form. Form ist nichts anderes als Leere. In modernen Begriffen ausgedrückt könnte man sagen: Ein Traum-Auto ist ein nicht aus sich selbst heraus wirkliches Auto. Ein nicht aus sich selbst heraus wirkliches Auto ist ein Traum-Auto. Ein Traum-Auto ist nichts anderes als ein nicht aus sich selbst heraus wirkliches Auto, und ein nicht aus sich selbst heraus wirkliches Auto ist auch nichts anderes als ein Traum-Auto.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 25                             :quote:done:
#+begin_quote
weil viele Leute irrtümlicherweise glauben, Meditation beinhalte, dass man der natürlichen Bewegung der Gedanken und Gefühle bewusst Einhalt gebietet.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 26                             :quote:done:
#+begin_quote
Ein Zustand ganz ohne Gedanken oder Emotionen ist ein Zustand ohne Unterscheidung oder Klarheit.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 27                             :quote:done:
#+begin_quote
Eine subtilere Bedeutung, die frühen Übersetzern entgangen sein mag, impliziert, dass alles, was aus diesem unendlichen Potenzial hervorgeht – ob es nun ein Gedanke, ein Wort, ein Planet oder ein Tisch ist –, für sich genommen gar nicht als ein »Ding« existiert, sondern vielmehr das Resultat zahlreicher Ursachen und Bedingungen ist.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 28                             :quote:done:
#+begin_quote
Die buddhistische Schulung bietet eine andere Herangehensweise an unsere Erfahrung vom Leben an. Diese beinhaltet, dass wir eine im Wesentlichen auf Angst gegründete, auf das Überleben ausgerichtete Sichtweise aufgeben zugunsten einer Erfahrung vom Leben als einer Folge von seltsamen und wundervollen Ereignissen.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 29                             :quote:done:
#+begin_quote
Die Vergangenheit ist wie ein Samenkorn, das im Feuer verbrannt wurde. Ist es erst einmal zu Asche verbrannt, gibt es kein Samenkorn mehr. Da ist nur noch eine Erinnerung, ein Gedanke, der Ihnen durch den Kopf geht. Mit anderen Worten, die Vergangenheit ist nichts anderes als eine Vorstellung.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 30                             :quote:done:
#+begin_quote
Indem sie unsere Empfindung von einem »Ich« verstärken, das gegen die »anderen« antritt, bestätigen sie unser Selbstgefühl, das, wie wir im vorhergehenden Kapitel sahen, selbst nur eine Erscheinung ohne inhärente Wirklichkeit ist.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 31                             :quote:done:
#+begin_quote
Es bedeutet, von unseren Vorstellungen über die Wirklichkeit Abschied zu nehmen und stattdessen den Fluss der Wirklichkeit so zu erfahren, wie er ist.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 32                             :quote:done:
#+begin_quote
Als ich erst einmal meine Vorstellungen davon, wie die Dinge sein sollten, abgestreift hatte, war ich frei, auf meine Erfahrungen als genau das, was sie im Hier und Jetzt sind und was ich im Hier und Jetzt bin, zu reagieren.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 33                             :quote:done:
#+begin_quote
Der Geist ist die Quelle aller Erfahrung, und indem wir die Ausrichtung des Geistes ändern, können wir die Qualität all dessen, was wir erfahren und wahrnehmen, verändern.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 34                             :quote:done:
#+begin_quote
Indem man einer Erfahrung mit Intention begegnet und ihr Aufmerksamkeit widmet, kann man den schmerzvollen oder unerträglichen Kontext der Bedeutung einer Erfahrung in einen erträglichen oder angenehmen Kontext umwandeln. Mit der Zeit stellt diese kognitive Umstrukturierung neue neuronale Verbindungen im Gehirn her, vor allem im limbischen System, wo die meisten Empfindungen von Schmerz und Lust erkannt und verarbeitet werden.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 35                             :quote:done:
#+begin_quote
Erwachen des Mitgefühls, der uns angeborenen Fähigkeit, uns mit den Erfahrungen von anderen zu identifizieren und sie zu verstehen.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 36                             :quote:done:
#+begin_quote
Je klarer wir die Dinge so sehen, wie sie sind, desto mehr sind wir willens und fähig, unser Herz für andere Wesen zu öffnen. Wenn wir erkennen, dass andere Schmerz und Unglück erleiden, weil sie ihre wahre Natur nicht erkennen, sind wir spontan vom tiefen Wunsch bewegt, dass sie das gleiche Gefühl von Frieden und Klarheit erfahren mögen, das wir schon kennen lernen durften.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 37                             :quote:done:
#+begin_quote
Meiner Kenntnis nach entstehen die meisten Konflikte zwischen Leuten aus einem Verkennen der Motive des anderen. Wir haben alle unsere Gründe, zu tun, was wir tun, und zu sagen, was wir sagen. Je mehr wir uns vom Mitgefühl leiten lassen – einen Moment innehalten und versuchen zu erkennen, wovon die andere Person ausgeht –, desto weniger wahrscheinlich werden wir in einen Konflikt geraten.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 38                             :quote:done:
#+begin_quote
Ein Übermaß an materiellen Dingen und Möglichkeiten liefert eine solche Vielfalt an äußerlichen Ablenkungen, dass die Menschen den Kontakt mit ihrem Innenleben verlieren.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 39                             :quote:done:
#+begin_quote
Emotionale Zustände sind relativ rasche Ausbrüche neuronalen Geschwätzes. Wesenszüge hingegen sind eher das neuronale Äquivalent für eine feste Beziehung.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 40                             :quote:done:
#+begin_quote
Wenn uns zum Beispiel jemand anschreit, nehmen wir uns kaum die Zeit, zwischen der bloßen Erkenntnis, »Oh, diese Person erhebt ihre Stimme und sagt diese und jene Worte«, und der emotionalen Reaktion, »Der Typ ist ein Blödmann«, zu unterscheiden. Stattdessen neigen wir dazu, die bloße Wahrnehmung und unsere emotionale Reaktion zu einem Paket zu vereinen: »Dieser Mensch schreit mich an, weil er ein Blödmann ist.«
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 41                             :quote:done:
#+begin_quote
Diese bilden die Grundlage für alle anderen Faktoren, die uns in unserer Fähigkeit behindern, die Dinge so zu sehen, wie sie wirklich sind. Diese drei sind: Unwissenheit, Anhaftung und Ablehnung.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 42                             :quote:done:
#+begin_quote
Unwissenheit ist die grundsätzliche Unfähigkeit, das grenzenlose Potenzial, die Klarheit und die Kraft unseres eigenen Geistes zu erkennen.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 43                             :quote:done:
#+begin_quote
Und während wir uns angewöhnen, zwischen dem »Ich« und dem »anderen« zu unterscheiden, sperren wir uns in eine dualistische Wahrnehmungsweise ein, ziehen konzeptuelle Grenzen zwischen unserem »Ich« und dem Rest der Welt »da draußen«, einer Welt, die so ungeheuer groß und weit zu sein scheint, dass wir fast nicht anders können, als uns selbst für sehr klein, beschränkt und verletzlich zu halten. Wir fangen an, andere Menschen, materielle Gegenstände und so weiter als potenzielle Quellen unseres Glücks und Unglücks zu betrachten, und das Leben wird zum Kampf darum, zu erlangen, was wir zum Glücklichsein brauchen, bevor es sich jemand anders holt.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 44                             :quote:done:
#+begin_quote
Samsara bezieht sich insbesondere auf das Rad oder den Kreislauf des Elends und der Unzufriedenheit, die Gewohnheit, im Kreis herumzurennen, immer wieder den gleichen Erfahrungen nachzujagen und dabei jedes Mal auf ein anderes Resultat zu hoffen.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 45                             :quote:done:
#+begin_quote
Das Sanskritwort Nirvana lässt sich grob mit »auslöschen« oder »ausblasen« (wie: eine Kerzenflamme ausblasen) übersetzen, und so wird Nirvana oft als ein Zustand absoluter Glückseligkeit interpretiert, der aus dem Auslöschen oder »Ausblasen« des Egos oder der Vorstellung von einem »Ich« oder »Selbst« entsteht.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 46                             :quote:done:
#+begin_quote
Nirvana ist ein grundlegend objektiver Geisteszustand: ein nicht bewertendes Annehmen von Erfahrungen, das uns das Potenzial zur Einsicht in Lösungen erschließt, die vielleicht nicht direkt mit unserem Überleben als Individuen, aber mit dem Überleben aller fühlenden Wesen verbunden sind.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 47                             :quote:done:
#+begin_quote
Wir brauchen die Berührung; wir brauchen es, dass man mit uns spricht; wir brauchen es, dass die einfache Tatsache unserer Existenz bestätigt und anerkannt wird.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 48                             :quote:done:
#+begin_quote
Anhaftung lässt sich in vielerlei Hinsicht mit Sucht vergleichen, einer zwanghaften Abhängigkeit von äußeren Objekten oder von Erfahrungen, die in uns eine Illusion von Ganzheit produzieren.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 49                             :quote:done:
#+begin_quote
Der Buddha verglich das Anhaften mit dem Trinken von Salzwasser aus dem Ozean. Je mehr wir trinken, desto durstiger werden wir.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 50                             :quote:done:
#+begin_quote
Ablehnung bezeichnet: Ein Widerstand gegenüber den unausweichlichen Veränderungen, die sich als Folge der Vergänglichkeit alles relativ Wirklichen ereignen.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 51                             :quote:done:
#+begin_quote
Die Vorstellung von einem dauerhaften, unabhängig existierenden Ich drängt uns dazu, uns mit enormer Anstrengung der Unvermeidlichkeit der Veränderung und des Wandels zu widersetzen und sicherzustellen, dass dieses »Ich« in Sicherheit und ungefährdet bleibt. Haben wir einen Zustand erreicht, der uns einigermaßen das Gefühl gibt, heil und ganz zu sein, wollen wir, dass alles genau so bleibt, wie es ist. Und je tiefer und stärker diese Anhaftung an das ist, was uns dieses Gefühl von Ganzheit vermittelt, desto größer ist unsere Angst, es zu verlieren, und desto brutaler ist unser Schmerz, wenn wir es verlieren.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 52                             :quote:done:
#+begin_quote
Ablehnung verstärkt neuronale Muster, die ein mentales Konstrukt erzeugen, das uns die Vorstellung übermittelt, beschränkt, schwach und unvollständig zu sein. Weil alles, was die Unabhängigkeit dieses mentalen »Ich«-Konstrukts untergraben könnte, als Bedrohung wahrgenommen wird, verwenden wir unbewusst ein enormes Maß an Energie auf das Ausschauhalten nach potenziellen Gefahren.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 53                             :quote:done:
#+begin_quote
Wenn Sie einfach nur einmal innehalten und sich die riesige Vielfalt und Anzahl der Geschöpfe vor Augen führen, die den Planeten mit uns teilen, und sie dann mit dem relativ kleinen Prozentsatz an Menschenwesen vergleichen, müssen Sie daraus schließen, dass die Chancen, als Mensch zur Welt zu kommen, extrem gering sind.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 55                             :quote:done:
#+begin_quote
Wir benutzen den Geist, um den Geist zu erkennen. Das ist übrigens eine gut funktionierende Definition von Meditation. Bei ihr geht es nicht um ein »In-der-Glückseligkeit-Versunkensein«, »Abheben« oder »Zur-Klarheit-Kommen« – um nur einiges davon zu nennen, was ich bei meinen Reisen rund um die Welt von Leuten zu hören bekam. Im Grunde ist die Meditation eine sehr einfache Übung, bei der Sie im natürlichen Zustand Ihres Bewusstseins im Hier und Jetzt ruhen und sich erlauben, für alle Gedanken, Empfindungen oder Emotionen, die auftreten mögen, einfach und klar präsent zu sein.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 56                             :quote:done:
#+begin_quote
Wenn wir den Geist in seinem natürlichen Zustand ruhen lassen, unterscheidet sich das sehr vom Bemühen, unseren Gedankenfluss ganz und gar zum Stillstand zu bringen. Die buddhistische Meditation beinhaltet in keiner Weise den Versuch, den Geist zur totalen Mattscheibe werden zu lassen. Eine gedankenleere Meditation lässt sich unmöglich erreichen. Selbst wenn es Ihnen gelänge, Ihre Gedanken vollkommen zum Stillstand zu bringen, würden Sie doch nicht meditieren; Sie würden einfach nur in einen zombieähnlichen Zustand abdriften.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 57                             :quote:done:
#+begin_quote
Sieben-Punkte-Haltung des Vairochana bekannt, ein Aspekt des Buddha, der den Zustand der Erleuchtung und Weisheit bezeichnet.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 58                             :quote:done:
#+begin_quote
Feststellung, dass geschlossene Augen leichter zum Anhaften an einem künstlichen Gefühl von Ruhe und Gelassenheit verführen.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 59                             :quote:done:
#+begin_quote
das »mentale Sediment« der Gedanken, Emotionen, Empfindungen und Wahrnehmungen ganz natürlich, und die dem Geist innewohnende Klarheit offenbart sich.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 60                             :quote:done:
#+begin_quote
MEDITATION OHNE OBJEKT
#+end_quote

auch als Shine-Praxis bekannt

In gewisser Weise gleicht die objektlose Shiné-Praxis einem Schauen in die unermessliche Weite des Alls, statt dass wir den Blick auf die sich durchs Universum bewegenden Galaxien, Sterne und Planeten fokussieren. So wie Galaxien, Sterne und Planeten durch den Raum des Alls ziehen, findet ein Kommen und Gehen von Gedanken, Emotionen und Empfindungen im Gewahrsein statt.

** Buddha und die Wissenschaft vom Glück - Note 63                             :quote:done:
#+begin_quote
Wenn ich meine Aufmerksamkeit, statt auf den speziellen schmerzenden Bereich, auf den Geist richte, der den Schmerz registriert, bedeutet das nicht unbedingt, dass der Schmerz verschwindet. Doch er wird jetzt zum Ausgangspunkt einer aktiven Beschäftigung mit dem, was ich im Hier und Jetzt erlebe, statt zu etwas, das ich zu vermeiden suche.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 66                             :quote:done:
#+begin_quote
Das Denken ist die natürliche Aktivität des Geistes. Bei der Meditation geht es nicht darum, dass du deine Gedanken abstellst. Meditation ist einfach ein Prozess, bei dem du den Geist in seinem natürlichen Zustand ruhen lässt; ein Zustand, in dem der Geist für die Gedanken, Emotionen und Empfindungen, so wie sie in Erscheinung treten, offen und ihrer ganz natürlich gewahr ist. Der Geist ist wie ein Fluss; und wie bei einem Fluss macht es keinen Sinn, seinem Fließen Einhalt zu gebieten. Da könnten Sie ebenso gut auch versuchen, Ihren Herzschlag zum Stillstand zu bringen oder Ihre Lungen vom Atmen abzuhalten. Was für einen Sinn sollte das haben?
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 67                             :quote:done:
#+begin_quote
Im Gegensatz dazu wird die Aufmerksamkeit, die Sie auf ein mit negativen Emotionen besetztes Objekt gerichtet halten, eher zur Verstärkung der Vorstellung führen, dass die betreffende Person, Situation oder Sache an und für sich schlecht oder von Übel ist.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 68                             :quote:done:
#+begin_quote
In solchen Fällen besteht die konstruktivere Methode darin, dass Sie, ähnlich wie beim Arbeiten mit negativen Gedanken, Ihre Aufmerksamkeit einfach auf der Emotion selbst und nicht auf deren Objekt ruhen lassen.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 69                             :quote:done:
#+begin_quote
»Der Pfau frisst Gift, und das von ihm verspeiste Gift verwandelt sich in wunderschöne Federn.«
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 70                             :quote:done:
#+begin_quote
Nehmen Sie ein Blatt Papier und einen Stift zur Hand und notieren Sie zehn Probleme, die Sie gerne gelöst sähen. Es spielt keine Rolle, ob es um globale oder mehr oder weniger häusliche Probleme geht.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 71                             :quote:done:
#+begin_quote
Wenn wir eine Liste von Menschen er- stellen sollten, die wir nicht mögen, würden wir eine Menge über die As- pekte von uns selbst herausfinden, denen wir uns nicht stellen können.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 72                             :quote:done:
#+begin_quote
Aus buddhistischer Sicht bedeutet »Güte« das Bestreben, dass alle anderen fühlenden Wesen – auch die, die wir nicht mögen – die gleiche Freude und Freiheit erfahren mögen, die auch wir anstreben; die Erkenntnis, dass wir alle die gleiche Art Wünsche und Bedürfnisse haben: das Verlangen, unser Leben in Frieden führen zu können und keine Angst vor Schmerz oder Verletzung haben zu müssen.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 73                             :quote:done:
#+begin_quote
Indras Netz
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 74                             :quote:done:
#+begin_quote
Der allmähliche Pfad, den ich in Bezug auf die Entwicklung von Mitgefühl für andere lernte, beinhaltet drei »Ebenen«.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 75                             :quote:done:
#+begin_quote
Auf der Ebene eins lernt man, wie man eine freundlich gütige oder mitfühlende Einstellung zu sich selbst und anderen nahestehenden Wesen entwickelt.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 76                             :quote:done:
#+begin_quote
Auf der Ebene zwei konzentriert man sich auf die Entwicklung von unermesslicher Güte und unermesslichem Mitgefühl, die sich auf alle Wesen erstrecken.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 77                             :quote:done:
#+begin_quote
Ebene drei ist als Bodhicitta (Erleuchtungsgeist) bekannt und wird noch einmal in zwei Arten oder Ebenen unterteilt: das absolute und das relative Bodhicitta. Unter absolutem Bodhicitta versteht man die spontane Erkenntnis, dass alle fühlenden Wesen bereits vollständig erleuchtet sind, ganz gleich wie sie handeln oder in Erscheinung treten.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 78                             :quote:done:
#+begin_quote
Als ich jedoch die Mitgefühlsmeditation zu praktizieren begann, stellte ich fest, dass mein Gefühl, allein und isoliert zu sein, allmählich abnahm und mein ganz persönliches Empfinden von Befähigung nach und nach zunahm. Wo ich ehedem nur Probleme sah, begann ich nun Lösungen zu erkennen. Und da, wo ich einst mein Glück für wichtiger gehalten hatte als das Glück anderer, konnte ich nun das Wohlergehen anderer als Grundlage für meinen eigenen Geistesfrieden
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 81                             :quote:done:
#+begin_quote
Aber ein gebrochenes Herz ist ein offenes Herz. Und jeder Anlass, der Ihnen das Herz bricht, bietet die Gelegenheit, dass Sie von Liebe und Mitgefühl durchströmt werden.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 82                             :quote:done:
#+begin_quote
Nicht das Objekt Ihrer Gefühle ist die Ursache für Ihren Schmerz, sondern Ihre eigene, mental erzeugte Reaktion auf das Subjekt oder den Gegenstand Ihrer Gefühle.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 86                             :quote:done:
#+begin_quote
Lassen Sie sich von Ihrer eigenen Erfahrung führen und inspirieren. Genießen Sie die Sicht während Ihres Reisens auf dem Pfad. Die Sicht ist Ihr eigener Geist, und weil Ihr Geist schon erleuchtet ist, werden Sie schließlich auch erkennen, dass der Ort, den Sie erreichen wollen, der Ort ist, an dem Sie bereits sind.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 87                             :quote:done:
#+begin_quote
Wenn Essen, Trinken, Sex und so weiter dauerhafte Empfindungen von Glück erzeugen könnten, würden wir alle diese Dinge nur ein Mal tun und uns dann zufrieden zurücklehnen, während sich andere den Aufgaben widmen, die mit dem Fortdauern der Spezies einhergehen. Strikt biologisch gesprochen, drängt uns der Überlebenstrieb stärker zum Unglücklichsein als zum Glücklichsein.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 88                             :quote:done:
#+begin_quote
Alles, was du denkst, alles, was du sagst, und alles, was du tust, wird dir als deine eigene Erfahrung zurückgespiegelt.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 90                             :quote:done:
#+begin_quote
Doch der Punkt ist der, dass Sie auch im Wachzustand erstaunliche Dinge vollbringen können, wenn Sie sich im Erkennen der Leerheit aller Phänomene schulen. Die meisten Menschen sind im Wachzustand den gleichen Täuschungen von Begrenztheit und Eingeschlossenheit unterworfen wie im Traumzustand.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 92                             :quote:done:
#+begin_quote
persönlichen Begrenzungen, die er fast sein ganzes Leben lang als Realität akzeptiert hat, tatsächlich nur Projektionen seines Geistes sind.
#+end_quote

** Buddha und die Wissenschaft vom Glück - Note 94                             :quote:done:
#+begin_quote
Je achtsamer Sie werden, desto leichter wird es Ihnen fallen, mitfühlend zu sein. Und je mehr Sie Ihr Herz für andere öffnen, desto achtsamer werden Sie bei all Ihren Aktivitäten werden.
#+end_quote
