:PROPERTIES:
:ID:       bcf4b1f6-efe6-4d50-b406-502b1f5e19a5
:END:
#+title: Company of One
#+filetags: :entrepreneurship:leadership:book:
#+date: 2024-02-17

👉 https://www.goodreads.com/en/book/show/37570605


* Prologue
** Higher profit vs efficiency

#+begin_quote
As a means to generating higher profits, what if you acquired more customers simply by
creating more efficiency, so you didn’t have to hire more people? What if you generated
more revenue by finding a way to spend less (again, for higher profits)? What if you
responded to the growth in support requests by finding a better way to teach your
customers how to use what you sell, so they didn’t have to ask questions as often? What if
you didn’t have to work more hours to finish a project but just more efficiently, so you
could then enjoy more of your life away from work?
#+end_quote

- *Generate higher profits without hiring more people*
- *Spend less to increase revenue*
- *Improve customer education to reduce support requests*
- *Increase efficiency to enjoy more work-life balance*

* Company of One
** Company of One vs Freelancing
#+begin_quote
A company of one questions growth and stays small on purpose. A company of one isn’t
simply a practicing freelancer either. While freelancing is a perfect first step to
becoming a company of one, freelancers are different because they exchange time for money.
Whether they’re getting paid by the hour or by deliverables, if they’re not working,
they’re not getting paid. All of a freelancer’s relationships are one-to-one, meaning that
each time paid work occurs, a freelancer has to do something and use his or her time.
#+end_quote

- *Company of one questions growth and stays small intentionally*
- *Freelancers exchange time for money*
- Freelancers get paid per hour or per deliverable*
- *Freelancers work one-to-one with clients*

** Entrepreneurship

#+begin_quote
In contrast, a company of one is more in line with the traditional definition of an
entrepreneur. If you’re utilizing systems, automations, and processes to build a long-term
business, you’re not trading time for money, but instead operating and profiting outside
of the time you spend working and beyond your one-to-one relationships. For example,
whether you’re creating physical products, selling software, or teaching online courses,
customers and users can purchase and consume these products and services without your
company of one putting in time for each transaction.
#+end_quote

- Company of one aligns with traditional entrepreneur definition
- Utilizes systems, automations, and processes for *long-term* business
- Operates and profits outside of time spent working
- Sells products/services without time for each transaction

#+begin_quote
Just as Michael Pollan’s food ideology is summarized in three simple rules—“eat food, not
too much, mostly plants”—the “company of one” model can be laid out in a similar fashion:
“*start small, define growth, and keep learning*.”
#+end_quote

** Intrapreneuer

#+begin_quote
The word “intrapreneur” points to one example of a *company of one within a larger
organization*. It describes corporate leaders who come up with their own goals and then
execute them. They don’t need much direction, micromanaging, or oversight, as they’ve been
given full work autonomy. They know what needs doing and they just do it. They’re aware of
the needs of the company and how their talents fit, and they just get to work.
#+end_quote

** Typical traits

#+begin_quote
Next, let’s look at the four typical traits of all companies of one: resilience, autonomy, speed, and simplicity.
#+end_quote

*** Resilience
 - It denotes toughness and the ability to recover quickly from difficulties. This trait is key as it helps the business adapt to changes and progress forward.

#+begin_quote
Resilience Miles Kington, a British journalist, reportedly said that “knowledge is knowing that a tomato is a fruit. Wisdom is not putting it in a fruit salad.” We should never assume that having an abundance of knowledge is the same as having an abundance of wisdom. Even if you have access to a plethora of data or experience, there are still so many factors beyond your control. The truth is, much of business is a guess. That’s why it’s important to be able to bounce back and reenergize a team when failure strikes.
#+end_quote
*** Autonomy
 - This trait signifies the capacity to make independent decisions, sans unwanted bureaucracy. It is beneficial for a single-person company as it allows quick decision-making and smooth business operations.

*** Speed
 - It involves the ability to act promptly and move quickly. It includes recognizing opportunities and seizing them before competitors do. Also, it connotes the capacity to change directions swiftly when required.

#+begin_quote
For Peldi and his team at Balsamiq, focusing on better, not bigger, removes any pressure to take shortcuts in software development. He gets to spend his time talking to customers instead of in board meetings or at investor pitches. Moreover, Peldi says, “*I’m Italian. Italians measure things in generations, not quarters*.
#+end_quote

*** Simplicity
 - It involves keeping everything straightforward and avoiding unnecessary complications, right from the business model to product offerings and operations. A clear and simple approach leads to fewer issues and better overall efficacy.


**** Focus on relationships
#+begin_quote
When you feel like you have to start out competing with the largest player in the market,
you end up chasing your competitor’s growth instead of bettering your own offering.
Sometimes finding and working with a single customer, then adding another, and then
another, is a very useful and solid way to begin. And sometimes that can even be the end
goal—one where your focus is on the relationship and the paid work at hand. Sometimes the
best plan is focused on your current customers’ success, not on chasing leads and growth.
#+end_quote

- Don't chase competitor's growth, focus on improving your own offering
- Starting with one customer and gradually adding more can be effective
- Focus on customer relationship and current customers' success
- Not always necessary to chase leads and growth
** Minimum Viable Profit (MVPr)
#+begin_quote
As a company of one, you need to reach profitability as quickly as possible. Since you’re not relying on massive influxes of cash from investors, every minute you spend getting set up and started is a minute when you aren’t making money. So getting your product or service released as soon as possible, even if it’s small, is both financially wise and educational, since a quick release can also serve as a perfect learning experience. The first version of a product doesn’t need to be huge—it simply needs to solve one problem well and leave your customers feeling better than before they purchased it. In determining your minimum viable profit—the point at which your business is operating in the black (we’ll call it MVPr from here on in)—keep in mind that the lower the number, the quicker you can reach it. So it’s important to scale up your timelines and focus on core features only, reduce expenses and overhead, and ensure that your business model works at a small scale first. The assumption at work here is that your MVPr—not the number of your customers, not your measured growth, not even your gross revenue—is the most important determinant of the sustainability of your company of one. If you make a profit right from the beginning, then you can figure out everything else. If your expenses are low, profit happens sooner. Decisions should be made with a focus on realized profit, not based on the expectation that profit may happen. This is such a key and main difference in how growth-focused businesses and companies of one operate. Even when a company of one needs to grow, that can happen only if metrics are based on actual profit, not on hopeful profit projections.
#+end_quote

- Reach profitability quickly
  - Every minute spent in setup/start is a minute not making money.
  - Release products/services quickly, even small ones, for financial wisdom and learning.

- Launch a product that solves one problem well
  - Leaves customers feeling better
  - It doesn't have to be a huge product - keep it simple

    #+begin_quote
    According to entrepreneur and author Dan Norris, you don’t learn anything until you launch. It might sound obvious, but a product is built to solve a specific problem. But as Dan points out, you won’t know how well your product solves that problem until people are actually paying for it and using it. Whether you’re selling cars, accounting software, or falafels from a falafel stand, these products exist to fix or address an existing and pressing problem.
    #+end_quote

- Determine your *minimum viable profit* (MVPr)
  - The lower this number (the point at which your business is operating in the black), the quicker you can reach it.
  - Scale up timelines, focus on core features, reduce expenses, and ensure your business model works at a smaller scale first.

- Focus on realized profit
  - MVPr is the *primary determinant* of your company's sustainability.
  - Aim to profit from the beginning, and keep expenses low.
  - *Decisions should be based on actual profit, not just projected profit*.

- Growth should be based on actual profits
  - Even if growth is necessary, it should be based on actual profit, not on hopeful profit projections.
** Focus on relationships
#+begin_quote
Measuring profit or customer retention can lead to more sustainability because, as the adage goes, “What gets measured gets done.” So if you’re focusing on growth, growth is what will happen. But if you focus instead on relationships that turn into long-term customers and sales, that’s what will happen instead.
#+end_quote

* ROWE (Results-Only Work Environments)

#+begin_quote
Other companies set up ROWEs (Results-Only Work Environments), in which employees don’t
have set schedules, all meetings are optional, and it’s entirely up to employees how they
spend their time working. They can choose to work from home, they can work from 2:00 AM to
6:00 AM if it suits them, and they can sculpt their job however they want, as long as the
results benefit the company as a whole. Cali Ressler and Jody Thompson have defined and
then studied ROWE implementations for over a decade, and they find that in these kinds of
autonomous environments, productivity goes up, employee satisfaction goes up, and turnover
goes down.
#+end_quote



#+begin_quote
In a typical company, regardless of how quickly you work, you’re still required to be
there for a set number of hours a day; in other words, *there’s no reward for productivity
or efficiency*.
#+end_quote

*** Speed
#+begin_quote
Speed is not merely about frantically working faster. It’s about figuring out the *best way to accomplish a task with new and efficient methods*. This is the concept at work in the ROWE method: employees *no longer have to work a set amount of time, but are rewarded when they finish their tasks faster*. By being smarter at getting more work done faster when you work for yourself, you can create a more flexible schedule that fits work into your life in better ways.
#+end_quote

* Leadership
** Introverted Leaders
#+begin_quote
A study done by professors at Harvard Business School found that introverted leaders,
especially when they are managing skilled and proactive teams, can be highly successful.
That’s because a quieter, calmer leader is more likely to listen carefully, stay very
focused, and not be afraid to work for long stretches of time without interruption. And
they are able to lead a team of people who can do the same. Just as autonomy can only be
of benefit once a skill set is mastered (as we discussed in Chapter 1), a company of one
that operates as a small team requires real expertise from each member if they are to
function both separately and as a whole without very much managing required.
#+end_quote
** Autonomy vs Alignment
#+begin_quote
Autonomy can also be badly abused. The problem is not so much employees taking advantage
of perks like flex hours or remote work, but leaders assuming that they need to give less
direction. A leader’s job is to provide clear direction and then get out of the way. Even
companies of one require direction and set processes—it’s this common constraint that
allows creativity to thrive and goals to be met. This alignment has to be carefully
orchestrated, not as binary autonomous/non-autonomous decisions, but as a balance between
guidance and trust. Provide too much guidance and a team will start to rely on it and
leadership will become a bottleneck for decision-making. Provide too little and things
devolve into anarchy. The middle ground is where high-performing teams excel, providing
the most benefit to a company and delivering the most innovative and amazing results.
#+end_quote

- Autonomy can be misused
- Leaders should provide clear direction
- Companies, including those of one, need direction and processes for creativity and goal achievement
- Balance between guidance and trust is crucial
- Middle ground between too much guidance and too little fosters high performance and innovation
* Customers related
** Customer education
#+begin_quote
Companies in the past have not always been eager to invest in customer education, as they haven’t seen clear or direct economic benefits from it. Conventional (but uninformed) wisdom has been that if you teach customers everything you know or share inside tricks of the trade, your customers will use that knowledge to not buy from you—or even worse, they’ll buy from the competition instead, armed with the knowledge they gained from you. But these fears are just myths. In fact, the opposite tends to happen, according to a study done by Andreas Eisingerich and Simon Bell at the MIT Sloan School of Business. Eisingerich and Bell surveyed 1,200 clients of an investment firm and found that the more those clients were educated on the pros and cons of the financial products the investment firm offered, the more they trusted that firm, the more loyalty to the firm they developed, and the more appreciative they became of the firm’s customer service for taking the time to educate them.
#+end_quote
** On teaching
#+begin_quote
Teaching builds trust and expertise like nothing else for a company of one. When someone’s receptive to what you’re teaching, they inherently trust the information you’re sharing. If you can consistently give your audience useful, relevant, and timely knowledge (through your mailing list, speaking events, website, and so on), they’ll begin to lean on you for more information (which you can then charge for). Teaching also doesn’t require lots of time, resources, or even money—it can be as simple as sharing what you know with the people who are listening.
#+end_quote
** Build a fan base
#+begin_quote
Having 100 passionate fans of your business who are eager to buy anything you release is exponentially more effective than having 100,000 followers who simply follow your business to win something like a free iPad.
#+end_quote

#+begin_quote
Alex Beauchamp, former head of content at Airbnb, said that she never wants any content she works on to “go viral.” She doesn’t want to ever be on the hook for making that happen. Moreover, going viral is often what happens with a business that, not understanding who its intended audience is, tries to appeal to pretty much everyone. If you want a piece of content for your business to generate a billion views, you probably don’t understand the purpose of that content or whom it was really created for. Engagement and connection with your niche are more important and far less costly to generate.
#+end_quote

** Earn trust not money
#+begin_quote
Making money is often easier than earning trust, because money can be lost and won back without judgment, whereas trust is hard to regain once it’s lost. Your word and your company’s word have to be a contract with your customers. This is how many companies of one stand out in competitive industries: by simply doing the work they say they’ll do and then honoring social contracts with their customers.
#+end_quote
** Types of capital
#+begin_quote
Even a company of one whose true north isn’t growth requires three types of capital. The first is financial capital, which we learned in Chapter 11 should be as small as possible to start so that profit—achieving your MVPr—happens quickly. The second is human capital, which is the value that you (or your small team) bring to the business or group: this value takes the form of the skills you’ll need—or your willingness to learn them—to build something and be autonomous in running it. The third type of capital required is social capital. While financial and human capital are important, social capital tends to be what makes or breaks a business, as it’s the piece that relates to how a market or audience sees the value in what you’re offering.
#+end_quote
*** Financial Capital
 - The monetary resources a business can use to fund its operations and investments.

*** Human Capital
 - Refers to the skills, knowledge, and experience of the company's employees, which can be leveraged to create value.

*** Social Capital
 - The networks and relationships that businesses can access to benefit their processes and gain advantage, such as partnerships, alliances, customer relationships, etc.

    #+begin_quote
    There are several schools of thought about building social capital, but a popular theory put forth by Sam Milbrath of HootSuite is that you can begin by dividing your mass interactions with an audience into thirds. Sam suggests that one-third of your updates should be about your business or your content, one-third should be sharing content from others, and one-third should be personal interactions that build relationships with your audience.
    #+end_quote

*** Physical Capital
 - The tangible assets a company owns, such as buildings, machines, equipment, and inventory.

*** Intellectual Capital
 - Intangible assets like patents, brands, business systems, and proprietary technology.

*** Natural Capital
 - The stock of natural resources, like water, land, air, and minerals, that a business can utilize for its processes.

* Examples
** Nomad List
#+begin_quote
Pieter Levels is a digital nomad and Dutch programmer who is challenging the status quo of
business tradition. Working from any location around the globe with an internet connection
(currently in a village in Thailand), he builds software that competes with VC-funded
Silicon Valley companies with teams of twenty or more people. Pieter runs his online
service, Nomad List—a community list of cities around the world ranked by how easy and fun
it is to work from them—and earns $400,000 a year without employees or even an office.
#+end_quote

** Story of Pinboard
#+begin_quote
While Delicious was rapidly changing hands, Pinboard was started by web developer Maciej
Ceglowski. He offered his simple service to users at $3 per year, a fee that increased
over time to $11 per year. Since the beginning, Pinboard has been a one-person company
with a limited feature-set and with no investors. Ceglowski operated it as a side business
for the first few months, until it was generating enough income for him to move to working
on Pinboard full-time. Then, on June 1, 2017, Pinboard acquired Delicious for just $35,000
and quickly shut it down to new users, offering existing users the option to migrate their
accounts to Pinboard instead. After rapid growth and increased complexity in its offerings
and internal structure, Delicious, in which millions of dollars had been invested, was
ultimately consumed by a company of one for a tiny price. Pinboard had kept things simple,
played the long game, and ended up winning.
#+end_quote
** WD-40
#+begin_quote
WD-40, the well-known everyday lubricant, is literally named after its thirty-nine failures and one success. Originally it was created for the aerospace industry, but it became so popular with employees using it for other tasks that it was brought to retail, where it thrived.
#+end_quote

* Quotes
** Follow your passion
Also check [[id:9a5fc738-0ba0-42ce-8271-99eccc5c2abb][So good they can't ignore you]]

#+begin_quote
The second missing ingredient in their account of successfully “following their passion” is that they were able to test their leap with a smaller jump before they climbed to the top of the highest platform. Most of these speakers neglect to mention that they didn’t just willy-nilly jump; rather, they did a small jump first to make sure they could land it (that is, they made sure there was enough demand for their offerings) and not drown once they hit the water.
#+end_quote
** Eight hour shift
👉 [[id:25164e94-c574-43f2-9a89-461f27827df2][The 4Hour Work Week]]

#+begin_quote
Prior to the industrial revolution, work took up all waking hours. Everyone was either sleeping, eating, or working. The automaker Henry Ford instituted *eight-hour shifts in his factory in 1914*. An early advocate for breaking the day into thirds (work, sleep, family), he did so not so much out of unbridled generosity, but because he realized (so the story goes) that *his workers needed free time to go out and buy more consumer goods*. After many companies followed suit, we ended up with the traditional idea that work should take forty hours a week. The funny thing, though, is that any task will take up the time we give it. So if we give ourselves eight hours to work each day, our work will take eight hours, and if our tasks take less time than that, we usually fill much of the “extra” time with busywork. If we reframe the question of how we spend our time, however, we can start to figure out how long each of our tasks actually takes. Perhaps we need only four hours a day to get our work done.
#+end_quote

* Ideas
** Weekend Check-in
#+begin_quote
On the company intranet, Basecamp has a “weekend check-in” where employees can post photos of what they did on their three days off from work. This helps this remote-based company build connections between its employees, who are spread all over the globe.
#+end_quote
