:PROPERTIES:
:ID:       3749ac25-5a66-4d81-a4ad-456d146e273b
:END:
#+title: Conscious Breathing
#+filetags: :book:
#+date: 2018-10-01

* Conscious Breathing
  :PROPERTIES:
  :FINISHED: 2018-10
  :END:
** Description
#+begin_quote
Conscious Breathing draws on more than twenty years of research and practice to present a simple yet comprehensive program that can be used every day to improve energy, mental clarity, and physical health. As the essential life-force of the body, the breath influences how we feel on every level.  But many traditional breathing programs are limited by esoteric or cultlike elements.  Pioneering therapist Gay Hendricks has refined the most important practices into a mainstream healing tool that can provide dramatic benefits–ranging from lowered blood pressure and pain reduction to elimination of depression and anxiety–in as little as ten minutes a day. At the core of the book are eight key breathing exercises, fully illustrated, with step-by-step instructions, plus the "short form" ten-minute breathing program.  Additional chapters provide breathing techniques for special concerns, including: Breathing to aid in trauma release and recovery from addictions. Treatment of asthma and other respiratory problems. Enhancement of sex and communication between couples. Improved concentration and stamina in sports.

(Source: https://www.goodreads.com/en/book/show/1255236.Conscious_Breathing)
#+end_quote
* Quotes
** Conscious Breathing - Note 1                                                :quote:done:
#+begin_quote
The Lating word for breath in spiritus. Allow your breath to flow through you as a sense of spirit flows through your body. —JERRY BRAZA, PH.D.
#+end_quote

** Conscious Breathing - Note 2                                                :quote:done:
#+begin_quote
The average person can go without food for several weeks, without liquid for several days. But oxygen is a different matter entirely. If you close off the oxygen supply to your brain by pressing the pulse points on the sides of your neck, reality as you know it starts to melt down rapidly.
#+end_quote

** Conscious Breathing - Note 3                                                :quote:done:
#+begin_quote
There is a tiny amount of Carbon Dioxide in it, less than one percent, and the rest is nitrogen. But each in-breath also brings with it a swarm of irritants, pollutants, and dust.
#+end_quote

** Conscious Breathing - Note 4                                                :quote:done:
#+begin_quote
As air enters the nose, it first encounters a tiny but important set of filters that we can observe as we look in the mirror and tilt our heads back: nose hairs. These hairs offer the first line of resistance to the pollutants and dust particles that float in on a wave of fresh air.
#+end_quote

** Conscious Breathing - Note 5                                                :quote:done:
#+begin_quote
For every in-breath there is an out-breath, and as these two currents meet in the nose, a fine microclimate is set up. Moisture is deposited by the out-breath on the mucus blanket, only to be picked up by the entering in-breath. The in-rushing currents of air grow warmer and more moist as they travel through the hair and past the mucus wall. In a miracle of heat-efficiency, the air reaches body temperature within a little more than an inch of the outside world, even on a cold day.
#+end_quote

** Conscious Breathing - Note 7                                                :quote:done:
#+begin_quote
Viruses an microbes live best in low oxygen environments. They are anaerobic. That means, raise the oxygen environment around them and they die. —EDWARD MCCABE
#+end_quote

** Conscious Breathing - Note 8                                                :quote:done:
#+begin_quote
And what are they doing, these tiny dancers of the deep? They are engaged in a heroic and thankless task, but one that is absolutely essential for health. They are passing the mucus blanket upward from the lungs, against gravity. Not only is the mucus blanket able to trap particles of dust and debris, but it is also a microbe hunter. It kills unfriendly bugs and drops them overboard toward the stomach, which gives them an acid bath and sends them south. To top it all off, the mucus blanket is richly supplied with white blood cells, providing a long gauntlet of immune-system barriers through which an invading microbe must pass.
#+end_quote

** Conscious Breathing - Note 9                                                :quote:done:
#+begin_quote
A gust of exhaled air is made of only 14 percent oxygen and 69 percent nitrogen, along with some water vapor and traces of other gases. But the important passenger on this wave of exiting air is Carbon Dioxide, about 5 percent of the volume. This is the exhaust, the smoggy emission that will quickly poison your system if not completely exhaled.
#+end_quote


** Conscious Breathing - Note 10                                               :quote:done:
#+begin_quote
When the human body is under stress, it responds with restricted breathing. The breath becomes shorter, shallower, and more in the chest than in the belly. When the body is relaxed, breathing slows down and drops farther into the belly, becoming deeper and more nurturing.
#+end_quote

** Conscious Breathing - Note 11                                               :quote:done:
#+begin_quote
If you observe carefully, you will feel your breathing shift when an emotion is present in your body. A first step to mastery of feelings is simply to notice when you are having one.
#+end_quote

** Conscious Breathing - Note 12                                               :quote:done:
#+begin_quote
The unpleasant qualities of emotions come from not letting them through, from holding on to them by not participating with them. By directly participating with feelings, largely through breathing with them, you can rid yourself of much unnecessary negativity.
#+end_quote

** Conscious Breathing - Note 13                                               :quote:done:
#+begin_quote
Today, people are taking charge of their own health. Many have found that simple things—eating healthy foods, exercising, breathing, getting a massage—can have profound health benefits. Western medicine is extremely good at dealing with certain problems such as infections and emergencies. Most people in the grip of a staph infection still choose treatment by antibiotics rather than acupuncture. But with the degenerative diseases Western medicine has a very poor track record.
#+end_quote

** Conscious Breathing - Note 14                                               :quote:done:
#+begin_quote
The skin is the body’s largest organ, and when you breathe effectively, you send more health-giving oxygen to it. Few people realize that the skin is an organ that helps in the elimination of toxins from the body. If the breathing mechanism is not doing its job, the skin must take over some of the responsibility. When you learn to breathe well, you use the full potential of your lungs, which frees the skin from overwork. It will celebrate its new-found freedom by looking better.
#+end_quote

** Conscious Breathing - Note 15                                               :quote:done:
As I have said, people hold their breath when they are hurt; this is a normal human reaction. But if this pattern is repeated, it becomes programmed into the body. Later as you breathe consciously, you can free yourself from these limits.

** Conscious Breathing - Note 16                                               :quote:done:
physiology. At the top of your lungs, up near your collarbones, the rate of blood flow is less than a tenth of a liter per minute. In other words, only a half-teacup or so of blood moves through the upper part of your lungs every minute. By contrast, the blood flow at the bottom of your lungs, down toward the bottom of your rib cage, is well over a liter per minute. Most of the blood circulation is in the bottom third of the lungs. If your belly muscles are tense, preventing you from breathing deeply into your abdomen, you are not getting the oxygen down to where all the blood is.

** Conscious Breathing - Note 17                                               :quote:done:
Your lungs are relatively small at the top and very large at the bottom. That is why in our lessons we will focus a great deal on learning to breathe deeply into the belly, so that we take advantage of how nature has designed us.

** Conscious Breathing - Note 18                                               :quote:done:
When I ask new clients to take a deep breath, nine times out of ten they will take a big, exaggerated breath up into their chests, sucking in their bellies by tightening their abdominal muscles. This is upside-down breathing at work.

** Conscious Breathing - Note 19                                               :quote:done:
The left side of the nose is connected to the right side of the brain, and vice versa. Breathing alternately through each nostril causes a shift from one hemisphere of the brain to the other. In this lesson we will draw on this phenomenon of physiology. My sense is that shifting hemispheres is what gives the practice its power. Switching from one brain hemisphere to another a number of times, while breathing slowly and deeply, seems to bring about a balance. My personal experience has shown me that it improves mood, refreshes the body, and sharpens the mind.

** Conscious Breathing - Note 20                                               :quote:done:
IN MANY ANCIENT CULTURES BREATH WAS SYNONYMOUS WITH SPIRIT. To the Greeks, spirit was pneuma, the feeling of the breath moving in the body. To the Romans it was spiritus and to the Hindus atman, the very feeling of God in the body. The enlivening feeling of the moving breath occupies a special place in the human experience.

** Conscious Breathing - Note 21                                               :quote:done:
Prana is the breath of life of all beings in the universe. They are born through it and live by it, and when they die their individual breath dissolves into the cosmic breath. —B.K.S. JYENGAR

** Conscious Breathing - Note 22                                               :quote:done:
Many of these lessons are informed and inspired by Wilhelm Reich and Moshe Feldenkrais, two geniuses of our century. It was through Feldenkrais in particular that I learned the power of using creative, conscious movements—done very slowly—to open the breath.

** Conscious Breathing - Note 23                                               :quote:done:
Beginning Position

** Conscious Breathing - Note 24                                               :quote:done:
On the In-Breath, Roll Your Arms Up the Floor, Opening Your Chest as You Fill Your Belly

** Conscious Breathing - Note 25                                               :quote:done:
#+begin_quote
As you have already seen, if there is a secret to conscious breathing, it is to relocate the center of breathing from the chest down into the lower abdomen. When you take a deep breath, you must learn to take it down deep in your center rather than up high in your chest. Later you can learn to center your breathing in your abdomen all day long. Surprisingly, the deeper you breathe in the center of your body, the more completely the rest of your body participates in each breath.
#+end_quote

** Conscious Breathing - Note 26                                               :quote:done:
#+begin_quote
craniosacral rhythm
#+end_quote

** Conscious Breathing - Note 27                                               :quote:done:
#+begin_quote
Take a big breath and hold it for ten or fifteen seconds. While your breath is held, see if you can feel a slow and gentle widening and narrowing of the head. With your breath rhythm out of the way, because your breath is held, you are more likely to be able to feel the rhythm. Each cycle of the craniosacral rhythm takes three or four seconds to swell and three or four seconds to recede. This is the average, although individuals may vary in the speed of their rhythm. Don’t hold your breath to the point of discomfort. Rest for a little while between breath-holdings.
#+end_quote

** Conscious Breathing - Note 28                                               :quote:done:
#+begin_quote
Any trauma you can breathe through loses its grip on you.
#+end_quote

** Conscious Breathing - Note 29                                               :quote:done:
#+begin_quote
My general observation is that people in cities do not breathe as deeply as people in the country. Noise, pollution, and other factors contribute to the collectively held breath of civilization.
#+end_quote

** Conscious Breathing - Note 30                                               :quote:done:
#+begin_quote
Predictably I have trouble sleeping the first night, due to sirens, horns, and such, but by the second or third night my body has made some adjustment that allows me to rest. If I am gone for a few days, I notice a definite unwinding effect when I return to the quiet and clean air of home. My body even lets go of fluids when I return, as if the stresses of urban life had encouraged it to hold on to moisture at the cellular level.
#+end_quote

** Conscious Breathing - Note 31                                               :quote:done:
#+begin_quote
ATHLETES’ TECHNIQUE ONE Increasing Stamina
#+end_quote

** Conscious Breathing - Note 32                                               :quote:done:
#+begin_quote
The basic technique involves lengthening the breath through a specific type of breath-counting, meanwhile coordinating it with the rhythm of your arms or legs. Since I mainly use it biking and hiking, my experience is in coordinating my breath with leg movement.
#+end_quote

** Conscious Breathing - Note 33                                               :quote:done:
#+begin_quote
ATHLETES’ TECHNIQUE TWO Honing Concentration
#+end_quote

** Conscious Breathing - Note 34                                               :quote:done:
#+begin_quote
Just take a relaxed, full breath, then say something true.
#+end_quote

** Conscious Breathing - Note 35                                               :quote:done:
#+begin_quote
ATHLETES’ TECHNIQUE THREE Quickly Coming into the Present
#+end_quote

** Conscious Breathing - Note 36                                               :quote:done:
#+begin_quote
you take three big, deep breaths and change your body position.
#+end_quote

** Conscious Breathing - Note 37                                               :quote:done:
#+begin_quote
If you would like to get to know the breadth of their knowledge, I can recommend Light on Pranayama (New York: Crossroad, 1985) by B.K.S. Iyengar and The Science of Breathing (Honesdale, PA: Himalayan Publishers, 1979) by Swami Rama and two Western colleagues, Rudolph Ballentine and Alan Hymes.
#+end_quote
