:PROPERTIES:
:ID:       dfdf5744-7a98-44f8-9dc8-acb56e114527
:END:
#+title: Das Zettelkasten-Prinzip
#+created: 20200907200141685
#+finished_month: 09
#+finished_year: 2020
#+genres: Productivity
#+goodreads: https://www.goodreads.com/book/show/34386139-das-zettelkasten-prinzip?from_search=true&from_srp=true&qid=U7vfq2Vqia&rank=1
#+lang: de
#+modified: 20210622091928954
#+revision: 0
#+filetags: :philosophy:personal-growth:productivity:basb:book:
#+type: text/vnd.tiddlywiki
#+date: 2020-09-01

* Einleitung
:PROPERTIES:
:CUSTOM_ID: einleitung
:END:
- Es geht drum dem Schreiben mehr Fokus zu widmen
  - Nicht nur formale Regeln
  - Schreiben um Wissensdatenbank aufzubauen
- Gegebenheiten unserer Umwelt beeinflussen unser Verhalten
  - Das Schreiben von Notizen in den Alltag integrieren
  - Routinen entlasten das Gehirn und setzen Kapazitäten frei
- Das Hirn ist sehr schlecht im objektiven Erinnern von Informationen
  - das Gleiche wird auch im [[#Getting%20Things%20Done%20-%20The%20Art%20of%20Stress-Free%20Productivity][Getting Things Done - The Art of Stress-Free Productivity]] gesagt
  - Durch die Entlastung werden Kapazitäten frei fürs Denken, Verstehen und neue Ideen entwickeln
- Siehe Dunniger-Kruger-Effekt
- Grundidee des Zettelkasten Zettelkastens
  - [[#Getting%20Things%20Done%20-%20The%20Art%20of%20Stress-Free%20Productivity][David Allen]] meets [[#LukasLuhmann][Lukas Luhmann]]
  - hat sich im akademischen Umfeld nicht durchgesetzt, da das Schreiben von Texten nicht Projekten (in Unternehmen) ähnelt
  - Es reicht nicht zu verstehen wie ein Zettelkasten funktioniert, man muss das System in die eigene Abläufe integrieren
  - Unabhängig davon ob man den <<. zk "Zettelkasten "ZK">> digital oder analog verwendet, ist zu beachten, dass Notizen auf Dauer angelegt werden und diese den Lebenszyklus von Programmen oder Unternehmen überdauern sollten.
- Zum Schreiben
  - Es geht darum mit dem Ende anzufangen
  - Man stellt sich vor man hat eine Rohfassung des Textes, den man verfassen möchte

* Notizen
:PROPERTIES:
:CUSTOM_ID: notizen
:END:
- [[#Die%204%20Grundprinzipien%20effektiven%20Schreibens][Die 4 Grundprinzipien effektiven Schreibens]]
- [[#Die%206%20Arbeitsschritte%20zum%20intelligenten%20Text][Die 6 Arbeitsschritte zum intelligenten Text]]
* Quotes
** Das Zettelkasten-Prinzip - Note 1                                           :quote:
#+begin_quote
Wenn man bereits eine Sammlung an entwickelten Gedankengängen zur Hand und problemlos auf passende Zitate und Quellenangaben zugreifen kann, dann kann man sich auch mit einer klaren Perspektive aufs Formulieren konzentrieren und muss nicht mit Schreibhemmungen, Prokrastination und Deadlines kämpfen (p. 10)
#+end_quote

** Das Zettelkasten-Prinzip - Note 2                                           :quote:
#+begin_quote
Wenn man von etwas keine Ahnung hat, hat man auch meine Ahnung davon, was für einen Unterschied es machen würde, wenn man Ahnung hätte. Ergo man sieht seine eigene Inkompetenz nicht (p. 16)
#+end_quote

** Das Zettelkasten-Prinzip - Note 3                                           :quote:
#+begin_quote
Ohne externe Hilfsmittel oder ein externes Gedächtnis kann man gar nicht richtig denken, jedenfalls nicht in systematischer Weise und schon gar nicht mit der Absicht, wissenschaftliche Erkenntnisse zu gewinnen. (p. 27)
#+end_quote

** Das Zettelkasten-Prinzip - Note 4                                           :quote:
#+begin_quote
Wer sich neues Wissen mit dem Prinzip des Zettelkastens aneignet, bringt zwei sich gegenseitig und jeweils selbst verstärkende Dynamiken zusammen: man verknüpft aktiv neues Wissen mit altem Wissen ,expliziert dieses und verbessert dadurch sein internes als auch sein externes Gedächtnis - und die Verbindung zwischen ihnen. (p.53)
#+end_quote

** Das Zettelkasten-Prinzip - Note 5                                           :quote:
#+begin_quote
Die Arbeit mit dem Zettelkasten gleicht hingegen eher der eines Investors, der sein Geld nicht nur zurück-, sondern auch anlegt, so dass das zurückgelegte Geld selbst zu seiner Vermehrung beitragen kann. (p. 85)
#+end_quote

** Das Zettelkasten-Prinzip - Note 6                                           :quote:
#+begin_quote
Ich habe immer einen Zettel zur Hand, auf dem ich mir die Ideen bestimmter Seiten notiere. Auf der Rückseite halte ich die biographischen Angaben fest. Wenn ich das Buch durchgelesen habe, dann gehe ich diese Notizen durch und überlege, was für welche bereits geschriebenen Zettel wie auswertbar ist. Ich lese also immer mit einem Blick auf die Verzettelungsfähigkeit von Büchern - (Luhmann, 1987, p.150)
#+end_quote

** Das Zettelkasten-Prinzip - Note 7                                           :quote:
#+begin_quote
Ohne zu schreiben, kann man nicht denken, jedenfalls nicht in anspruchsvoller, anschlussfähiger Weise (Luhmann, 1992, S. 53)
#+end_quote

** Das Zettelkasten-Prinzip - Note 8                                           :quote:
#+begin_quote
Ich habe immer einen Zettel zur Hand, auf dem ich mir die Ideen bestimmter Seiten notiere. Auf der Rückseite halte ich die biographischen Angaben fest. Wenn ich das Buch durchgelesen habe, dann gehe ich diese Notizen durch und überlege, was für welche bereits geschriebenen Zettel wie auswertbar ist. Ich lese also immer mit einem Blick auf die Verzettelungsfähigkeit von Büchern - (Luhmann, 1987, p.150)
#+end_quote

** Das Zettelkasten-Prinzip - Note 9                                           :quote:
#+begin_quote
#+begin_quote
Der Trick besteht darin, gezielt neue Gewohnheiten einzuüben, statt zu versuchen mit alten Gewohnheiten zu brechen. Das Ziel ist hier, automatisch einen Stift in die Hand zu nehmen, wann immer man etwas liest, um sich die wichtigsten Stellen herauszuschreiben; die eigenen Notizen genauso gewohnheitsgemäss zu verzetteln wie man seine Einkäufe in den Schrank räumt; beim Schreiben immer nach möglichen Anknüpfungspunkten im Zettelkasten zu schauen und immer, wenn man eine Idee hat, sie jedes Mal zu setzen. Wer sich so, ganz aus Gewohnheit, einen Fundus an verschriftlichen Ideen aufbaut, für den ist das eigentliche Schreiben keine unüberwindbar scheinende Aufgabe mehr, sondern die logische Konsequenz des vorherigen Tuns, das nun nur noch zum Abschluss gebracht wird. (S. 138)
#+end_quote
#+end_quote
