:PROPERTIES:
:ID:       abd6a1c6-fad0-4396-94f8-edc87fe19a0d
:END:
#+title: Deep Work: Rules for Focused Success in a Distracted World
#+filetags: :book:todo:
#+date: 2022-07-01

* On the Importance of Deep Work
** Constantly learn new things                                                 :quote:
#+begin_quote
To remain valuable in our economy, therefore, you must master the art of quickly
learning complicated things. This task requires deepwork. If you don't cultivate
this ability, you're likely to fall behind as technology advances.
#+end_quote
** Lifelong learning                                                           :quote:
#+begin_quote
The ability to perform [[id:32bf2a39-ed76-4f18-bac4-75dc54a417a9][deep work]] is becoming increasingly rare at exactly the same time it
is becomingincreasingly valuable in our economy. As a consequence, the few whocultivate
this skill, and then make it the core of their working life,will thrive
#+end_quote

* Attention residue
:PROPERTIES:
:ID:       89ad758a-c3f2-40b7-a18a-367718d36c0b
:END:
#+begin_quote
The problem this research identifies with this work strategy is that when you
switch from some Task A to another Task B,your attention doesn't immediately
follow---a residue of your attention remains stuck thinking about the original
task. This residue gets especially thick if your work on Task A was unbounded and
of lowintensity before you switched, but even if you finish Task A beforemoving
on, your attention remains divided for a while.
- [[https://www.sciencedirect.com/science/article/abs/pii/S0749597809000399][Why is it so hard to do my work]]
#+end_quote
* Part 1
** Chapter 1: Deep Work is Valuable
- Two Core Abilities for Thriving in the New Economy 
  - 1. The ability to quickly master hard things. 
  - 2. The ability to produce at an elite level, in terms of both quality and speed
*** The Intelectual Life                                                      :quote:
#+begin_quote
"Let your mind become a lens, thanks to the converging rays of attention; let your soul be
 all intent on whatever it is that is established in your mind as a dominant, wholly
 absorbing idea."
#+end_quote
*** Law of productivity
- High-Quality Work Produced = (Time Spent) x (Intensity of Focus)
** Chapter 2: Deep Work is rare
*** The Principle of Least Resistance
:PROPERTIES:
:ID:       c0efa937-0efe-4109-9307-a7b4cc09aa36
:ROAM_ALIASES: "Principle of Least Resistance"
:END:
#+begin_quote
In a business setting, without clear feedback on the impact of various behaviors to the
bottom line, we will tend toward behaviors that are easiest in the moment.
#+end_quote
*** Busyness as Proxy for Productivity
:PROPERTIES:
:ID:       5d94d44f-bb14-450e-b398-46a7a1f0db2d
:END:
#+begin_quote
In the absence of clear indicators of what it means to be productive and valuable in their jobs, many knowledge workers turn back toward an industrial indicator of productivity: doing lots of stuff in a visible manner
#+end_quote
** Chapter 3: Deep Work is Meaningful
*** Rapt
#+begin_quote
As Gallagher recalls in her 2009 book [[https://www.goodreads.com/book/show/6262510-rapt][Rapt]], as she walked away from the hospital after the
diagnosis she formed a sudden and strongintuition: "This disease wanted to monopolize my
attention, but as much as possible, I would focus on my life instead."
#+end_quote
#+begin_quote
Her curiosity piqued, Gallagher set out to better understand the role that
attention---that is, what we choose to focus on and what wechoose to ignore---plays in
defining the quality of our life. After fiveyears of science reporting, she came away
convinced that she was witness to a "*grand unified theory*" of the mind:
#+end_quote
**** Attention management                                                    :quote:
#+begin_quote
Like fingers pointing to the moon, other diverse disciplines from anthropology to
education, behavioral economics tofamily counseling, similarly suggest that the skillful
management of attention is the sine qua non of the good life and the key to improving
virtually every aspect of your experience
#+end_quote
*** Flow
#+begin_quote
"The best moments usually occur when a person's body or mind is stretched to its limits in a voluntary effort to accomplish something difficult and worthwhile." Csikszentmihalyi calls this mental state flow (a term he popularized with a 1990 book of the same title).
#+end_quote

#+begin_quote
Ironically, jobs are actually easier to enjoy than free time, because like flow activities
they have built-in goals, feedbackrules, and challenges, all of which encourage one to
become involved inone's work, to concentrate and lose oneself in it. Free time, on
theother hand, is unstructured, and requires much greater effort to be shaped into
something that can be enjoyed.
#+end_quote

- The connection between [[id:3c7f407e-38f4-4a55-bfca-89e2e09f65a9][deep work]] and flow should be clear
  - deep work generates a flow state
    - stretches your mind to its limits
    - helps you to concentrate and loose yourself in an activity
* Part 2
Taking action.

** The Rules
*** Rule #1: Work deeply
**** By Roy Baumeister
#+begin_quote
You have a finite amount of willpower that becomes depleted as you use it. Your will, in
other words, is not a manifestation of yourcharacter that you can deploy without limit;
it's instead like a muscle that tires
#+end_quote
#+begin_quote
The key to developing a [[id:3c7f407e-38f4-4a55-bfca-89e2e09f65a9][deep work]] habit is to move beyond good intentions and add routines
and rituals to your working life designed to minimize the amount of your limited willpower
necessary to transition into and maintain a state of unbroken concentration
#+end_quote
**** Different philosophies
***** Monastic
#+begin_quote
Knuth deploys what I call the monastic philosophy of [[id:3c7f407e-38f4-4a55-bfca-89e2e09f65a9][deep work]] scheduling. This philosophy
attempts to maximize deep efforts by eliminating or radically minimizing [[id:7315aeb7-8e69-4c52-a996-3e8b9545938e][shallow]]
obligations. Practitioners of the monastic philosophy tend to have a well-defined and
highly valued professional goal that they're pursuing, and the bulk of their professional
success comes from doing this one thing exceptionally well
#+end_quote
***** Bimodal
#+begin_quote
Jung's approach is what I call the bimodal philosophy of [[id:3c7f407e-38f4-4a55-bfca-89e2e09f65a9][deep work]]. This philosophy asks
that you divide your time, dedicating some clearly defined stretches to deep pursuits and
leaving the rest open to everything else. During the deep time, the bimodal worker will
act monastically---seeking intense and uninterrupted concentration. During the shallow
time, such focus is not prioritized. This division of time between deep and open can
happen on multiple scales. For example, on the scale of a week, you might dedicate a
four-day weekend to depth and the rest to open time. Similarly, on the scale of a year,
you might dedicate one season to contain most of your deep stretches (as many academics do
over the summer or while on sabbatical).
#+end_quote
***** Rhythmic
#+begin_quote
This chain method (as some now call it) soon became a hit among writers and fitness
enthusiasts---communities that thrive on the ability to do hard things consistently. For
our purposes, it provides a specific example of a general approach to integrating depth
into your life: the rhythmic philosophy. This philosophy argues that the easiest way to
consistently start deep work sessions is to transform them into a simple regular habit.
*The goal, in other words, is to generate a rhythm for this work that removes the need for
you to invest energy in deciding if and when you're going to go deep*. The chain method is
a good example of the rhythmic philosophy of deep work scheduling because it combines a
simple scheduling heuristic (do the work every day), with an easy way to remind yourself
to do the work: the big red Xs on the calendar.
#+end_quote
***** Journalistic
#+begin_quote
I call this approach, in which you fit deep work wherever you can into your schedule, the
journalist philosophy. This name is a nod to the fact that journalists, like Walter
Isaacson, are trained to shift into a writing mode on a moment's notice, as is required by
the deadline-driven nature of their profession
#+end_quote
**** 4DX Framework
***** The 4 Discipline of Execution
****** #1 Focus on the wildly importante
- Aim to for a small number of wildly importantly goals
- Let ambitious goals drove focus driven behaviour
  - The Art of Focus (David Brooks)
    #+begin_quote
    "If you want to win the war for attention, don't try to say 'no' to the trivial
    distractions you find on the information smorgasbord; try to say 'yes' to the
    subject that arouses a terrifying longing, and let the terrifying longing crowd
    out everything else."
    #+end_quote
****** #2 Act on the lead measures
- 2 types of metrics to measure the your goal
******** Lag measures
- Lag measures describe the thing you're ultimately trying to improve
- the problem with lag measures is that they come too late to change your behavior: "When you receive them, the
  performance that drove them is already in the past."
******** Lead measures
- Lead measures, on the other hand, “measure the new behaviors that will drive success on the lag measures.
- For an individual focused on [[id:3c7f407e-38f4-4a55-bfca-89e2e09f65a9][deep work]], it's easy to identify the relevant lead measure: time spent in a state of [[id:3c7f407e-38f4-4a55-bfca-89e2e09f65a9][deep work]] dedicated toward your wildly important goal
  - Don't track how many books, articles you've read
  - Measure instead how many hours of [[id:32bf2a39-ed76-4f18-bac4-75dc54a417a9][deep work]] you've mastered
****** #3 Keep the a compelling scoreboard
#+begin_quote
"People play differently when they're keeping score," the 4DX authors explain. They then elaborate that when attempting
to drive your team's engagement toward your organization's wildly important goal, it's important that they have a public
place to record and track their lead measures. This scoreboard creates a sense of competition that drives them to focus
on these measures, even when other demands vie for their attention. It also provides a reinforcing source of motivation.
Once the team notices their success with a lead measure, they become invested in perpetuating this performance.
#+end_quote
****** #4 Create a Cadence of Accountability
- The 4DX authors elaborate that the final step to help maintain a focus on lead measures is to put in place "a rhythm of regular and
frequent meetings of any team that owns a wildly important goal."
- multiple places throughout this book I discuss and recommend the habit of a weekly review in which you make a plan for the workweek ahead (see Rule #4). During my experiments with 4DX, I used a weekly review to look over my scoreboard to celebrate good weeks, help understand what led to bad weeks, and most important, figure out how to ensure a good score for the days ahead. This led me to adjust my schedule to meet the needs of my lead measure---enabling significantly more [[id:32bf2a39-ed76-4f18-bac4-75dc54a417a9][deep work]] than if I had avoided such reviews altogether.
*** Rule #2: Embrace boredom
- Much in the same way that athletes must take care of their bodies outside of their training sessions, you'll struggle to achieve the deepest levels of concentration if you spend the rest of your time fleeing the slightest hint of boredom
#+begin_quote
Don't Take Breaks from Distraction. Instead Take Breaks from Focus
#+end_quote
- *Productively Meditation*
  #+begin_quote
  The goal of productive meditation is to take a period in which you're occupied
  physically but not mentally---walking, jogging, driving, showering---and focus your
  attention on a single well-defined professional problem. Depending on your profession,
  this problem might be outlining an article, writing a talk, making progress on a proof,
  or attempting to sharpen a business strategy. As in mindfulness meditation, you must
  continue to bring your attention back to the problem at hand when it wanders or stalls
  #+end_quote
  - Tipps
    - Be Wary of Distractions and Looping
    - Structure Your Deep Thinking
**** Attention control
***** Memorize deck of cards
- Daniel Kilov
#+begin_quote
"We found that one of the biggest differences between memory athletes and the rest of us
is in a cognitive ability that's not a direct measure of memory at all but of attention,"
explained Roediger in a New York Times blog post (emphasis mine). The ability in question
is called "attentional control," and it measures the subjects' ability to maintain their
focus on essential information.
#+end_quote
#+begin_quote
The technique for card memorization I'll teach you comes from someone who knows quite a
bit about this particular challenge: Ron White, a former USA Memory Champion and world
record holder in card memorization.* The first thing White emphasizes is that professional
memory athletes never attempt rote memorization, that is, where you simply look at
information again and again, repeating it in your head. This approach to retention, though
popular among burned-out students, misunderstands how our brains work. We're not wired to
quickly internalize abstract information. We are, however, really good at remembering
scenes
#+end_quote
*** Rule #3: Quit social media
- Chose your tools
  - The Craftsman Approach to Tool Selection: Identify the core factors that determine success and happiness in your professional and personal life. Adopt a tool only if its positive impacts on these factors substantially outweigh its negative impacts
- Social media as source of distraction
  - They're just products, developed by private companies, fundedlavishly, marketed carefully, and designed ultimately to capture thensell your personal information and attention to advertisers. They can befun, but in the scheme of your life and what you want to accomplish,they're a lightweight whimsy, one unimportant distraction among many threatening to derail you from something deeper
*** Rule #4: Drain the Shallows
**** 37signals/Basecamp 4-day week
#+begin_quote
Very few people work even 8 hours a day. You're lucky if you geta few good hours in
between all the meetings, interruptions, websurfing, office politics, and personal
business that permeate thetypical workday. Fewer official working hours helps squeeze the
fat outof the typical workweek. Once everyone has less time to get their stuffdone, they
respect that time even more. People become stingy with theirtime and that's a good thing.
They don't waste it on things that just don't matter. When you have fewer hours you
usually spend them more wisely.
#+end_quote
#+begin_quote
37signals' experiments highlight an important reality: The shallow work that increasingly
dominates the time and attention ofknowledge workers is less vital than it often seems in
the moment. Formost businesses, if you eliminated significant amounts of thisshallowness,
their bottom line would likely remain unaffected. And asJason Fried discovered, if you not
only eliminate shallow work, but also replace this recovered time with more of the deep
alternative, not only will the business continue to function; it can become more
successful
#+end_quote
**** Cognitive capacity and deep work
#+begin_quote
Then there's the issue of cognitive capacity. [[id:32bf2a39-ed76-4f18-bac4-75dc54a417a9][Deep work]] is exhausting because it pushes
you toward the limit of your abilities.Performance psychologists have extensively studied
how much such effortscan be sustained by an individual in a given day.* In their
seminalpaper on deliberate practice, Anders Ericsson and his collaboratorssurvey these
studies. They note that for someone new to such practice(citing, in particular, a child in
the early stages of developing anexpert-level skill), an hour a day is a reasonable limit.
For those familiar with the rigors of such activities, the limit expands to something like
four hours, but rarely more
#+end_quote
* Conclusion
- A commitment to [[id:32bf2a39-ed76-4f18-bac4-75dc54a417a9][deep work]] is not a moral stance and it's not aphilosophical statement
  - it is instead a pragmatic recognition that the ability to concentrate is a skill that [[id:3ee54643-65c2-482a-8c60-fa099449a62d][gets valuable things done]]
