:PROPERTIES:
:ID:       7a0a99bf-b194-4540-a5ea-7fda082f48f2
:END:
#+title: Dein kompetentes Kind
#+filetags: :parenting:book:
#+date: 2020-11-01

* Dein kompetentes Kind
:PROPERTIES:
:FINISHED: 2020-11
:END:
** Description
* Quotes
** Dein kompetentes Kind - Note 1                                              :quote:done:
#+begin_quote
Wenn Kinder aufhören zu kooperieren, dann wurde entweder ihre Kooperationsbereitschaft überstrapaziert oder ihre Integrität verletzt. Es geschieht niemals, weil sie nicht kooperieren wollen.
#+end_quote

** Dein kompetentes Kind - Note 2                                              :quote:done:
#+begin_quote
Er ist nicht wütend auf seine Eltern und sieht sie nicht kritischer als vorher. Er hat ein wenig an  verloren, ist etwas weniger er selbst und etwas mehr so, wie seine Eltern ihn haben wollen. Doch wie alle anderen Kinder liebt er seine Eltern bedingungslos und ist bereit, ihnen den Sohn zu geben, den sie sich vorstellen. Er ist so tief davon überzeugt, dass sie im Recht sind und er nicht, dass er mit großer Wahrscheinlichkeit den Schmerz und die Demütigung verdrängt und in 20 Jahren seinen eigenen Sohn genau so behandeln wird, wie er behandelt wurde.
#+end_quote

** Dein kompetentes Kind - Note 3                                              :quote:done:
#+begin_quote
Wenn Kinder sich destruktiv und/oder asozial verhalten, liegt das stets daran, dass einer oder mehrere Erwachsene in ihrer Nähe dies ebenfalls tun. Oft auf andere Weise als das Kind und nicht selten in einer Fprm, die zur Gruppe der akzeptierten Kränkungen gehört.

Es sind immer die Erwachsenen, die den Anfang machen. Manchmal in der bewussten Absicht, dem Kind eine Lehre zu erteilen oder einen Denkzettel zu verpassen, doch am häufigsten als Resultat ihres eigenen destruktiven Verhaltens.
#+end_quote

** Dein kompetentes Kind - Note 4                                              :quote:done:
#+begin_quote
Aus dem Blickwinkel eines Familientherapeuten ist die in Südeuropa vorherrschende patriarchalische Familienstruktur oft nur eine soziale und ökonomische Realität. Psychologisch und existenziell erweisen sich die scheinbar so männerdominierten Familien oft als getarnte Matriarchate.
#+end_quote
** Note 5
#+begin_quote
Ich habe jedoch während meiner Arbeit mit Familien und anderen Gruppen die
Erfahrung gemacht, dass dies nicht mehr zutrifft. Vieles deutet sogar auf das
Gegenteil hin: *Die Integrität des Einzelnen ist die Bedingung dafür, dass sich die Gemeinschaft gut entwickelt*. Es gibt kein kollektives Wohl- befinden ohne das Wohlbefinden des Einzelnen.

Unsere heutigen Erkenntnisse über die psychische Entwicklung von Kindern (und
Menschen im Allgemeinen) versetzen uns in die Lage, neue Werte für die
Interaktion zwischen Kindern und Erwachsenen zu definieren. Das gilt vor allem für das Zusammenspiel in der Familie, aber auch in anderen Organisationen, in denen Kinder und Erwachsene zielgerichtet zusammenarbeiten, wie Schulen, Kindergarten, Pflegefamilien, therapeutischen Einrichtungen etc.
#+end_quote
** Note 6
#+begin_quote
Wir können unsere ökonomische, physische und soziale Macht benutzen, um Kindern gewisse Dinge und Umstände entweder zu gewähren oder zu versagen, doch wenn wir sie benutzen, um ihre Reaktionen und Gefühle zu diskreditieren, dann missbrauchen wir unsere Macht. *Unsere Elternschaft gibt uns nicht das Recht, das Leben selbst zu kränken*. *Dieselbe Ethik ist ebenfalls nötig, um eine gleichwürdige Beziehung unter Erwachsenen zu etablieren*.
#+end_quote
