:PROPERTIES:
:ID:       9b735d66-ae5c-48eb-b535-49cd38e53262
:END:
#+title: Die Kunst der Schlagfertigkeit im Alltag
#+filetags: :book:
#+date: 2017-04-01

* Die Kunst der Schlagfertigkeit im Alltag
  :PROPERTIES:
  :FINISHED: 2017-04
  :END:
** Description
#+begin_quote
Geraten Sie im Job als auch im Privatleben schnell in peinliche und sehr unangenehme Situationen? Kennen Sie das Gefühl der Hilflosigkeit wenn der Chef, Kollegen, der Partner oder Freunde Sie bloßstellen und erst Stunden später fällt Ihnen dann eine passende Antwort ein?

Das muss nicht so bleiben! Kontern Sie. Jetzt! Schlagfertigkeit kann man erlernen.

Schlagfertigkeit ist die Kunst spontan und souverän zu kontern. Damit stoppen Sie etliche Verbalattacken und nehmen dem Angreifer den Wind aus den Segeln.

Verändern Sie ihr Leben mit dem Buch: „Schlagfertigkeit - Vom Anfänger zum Profi“.
Nie wieder wortlos. Bewahren Sie mit der Schlagfertigkeit Ihre eigene Souveränität und nutzen Sie unser Wissen um Sie zu unterstützen!

(Quelle: https://www.amazon.de/Schlagfertigkeit-Smalltalk-Schlagf%C3%A4higkeit-trainieren-wortgewandt-ebook/dp/B01GBX84ES)
#+end_quote
* Quotes
** Die Kunst der Schlagfertigkeit im Alltag - Note 1                           :quote:done:
#+begin_quote
Besser berufsunerfahren als lernunwillig. Und lernen will ich.
#+end_quote

** Die Kunst der Schlagfertigkeit im Alltag - Note 2                           :quote:done:
#+begin_quote
Das bedeutet, dass Sie mich nicht grundsätzlich ablehnen. Und damit haben Sie Recht, denn ...
#+end_quote

** Die Kunst der Schlagfertigkeit im Alltag - Note 3                           :quote:done:
#+begin_quote
Dann finden Sie also, dass ich alle für diese Stelle verlangten Qualifikationen mitbringe - und sogar noch ein paar mehr.
#+end_quote

** Die Kunst der Schlagfertigkeit im Alltag - Note 4                           :quote:done:
#+begin_quote
Vielleicht banaler als Ihre Antwort. Und die wäre?
#+end_quote

** Die Kunst der Schlagfertigkeit im Alltag - Note 5                           :quote:done:
#+begin_quote
Ich bin ein dynamischer, leistungsbereiter Mensch  und wenn ich mein Potenzial in einem Unternehmen nicht richtig einsetzen kann, werde ich leider unglücklich. Sie dürfen nur nicht schlecht über Ihren Noch-Arbeitgeber reden.
#+end_quote

** Die Kunst der Schlagfertigkeit im Alltag - Note 6                           :quote:done:
#+begin_quote
Betonen Sie seinen Nutzen: Ja, gerade weil die Zeiten schlecht sind, erscheint es mir sinnvoll, in gute Mitarbeiter zu investieren, die harten Umsatz machen.
#+end_quote

** Die Kunst der Schlagfertigkeit im Alltag - Note 7                           :quote:done:
#+begin_quote
Wenn ich Sie richtig verstehe, erhalte ich zwar das Geld, wie im Arbeitsvertrag vereinbart, bringe aber nicht die entsprechende Leistung, das heißt, ich verletze arbeitsvertragliche Pflichten. Jetzt kann Ihr Chef fast nicht anders als zurückrudern.
#+end_quote

** Die Kunst der Schlagfertigkeit im Alltag - Note 8                           :quote:done:
#+begin_quote
Entschuldigung, ich muss eingeschlafen sein, was genau meinen Sie? Wiederholt sich Ihr Chef, wird er selbst merken, wie hohl seine Worte sind.
#+end_quote

** Die Kunst der Schlagfertigkeit im Alltag - Note 9                           :quote:done:
#+begin_quote
In Ihrer Position ist leider nicht mehr Gehalt drin. Überraschen Sie Ihren Chef, indem Sie ihm Recht geben: 'Das sehe ich genauso. Also sollten wir vielleicht über eine Beförderung sprechen.'
#+end_quote

** Die Kunst der Schlagfertigkeit im Alltag - Note 10                          :quote:done:
#+begin_quote
Gut, das heißt, wir sind uns schon mal einig. Dann sollte ich jetzt wohl mein Anliegen in der Geschäftsführung vortragen.
#+end_quote

** Die Kunst der Schlagfertigkeit im Alltag - Note 11                          :quote:done:
#+begin_quote
Heute Sie, und morgen verlangt die halbe Abteilung auch eine Gehaltserhöhung. Sie können den versteckten Vorwurf, Sie würden Ihre Gehaltserhöhung hinausposaunen, offenlegen: 'Daraus entnehme ich, Sie befürchten, ich könnte im Kollegenkreis über vertrauliche Dinge wie Gehalt reden?' Oder Sie antworten ganz sachlich: 'Das glaube ich nicht. Erstens erzähle ich den Kollegen nicht von diesem Gespräch und zweitens dürfte kaum einer von ihnen so gute Argumente wie ich
#+end_quote

** Die Kunst der Schlagfertigkeit im Alltag - Note 12                          :quote:done:
#+begin_quote
Sie behaupten, dass ich nicht zu dem stehe, was ich tue.
#+end_quote

** Die Kunst der Schlagfertigkeit im Alltag - Note 13                          :quote:done:
#+begin_quote
Ja, früher habe ich mich richtig in eine Sache verbissen. Aber heute weiß ich, dass ich mit ruhiger Überlegung mehr erreiche.
#+end_quote

** Die Kunst der Schlagfertigkeit im Alltag - Note 14                          :quote:done:
#+begin_quote
Gerade weil ich noch viel lernen muss und will, können Sie von mir hervorragende Leistungen erwarten.
#+end_quote

** Die Kunst der Schlagfertigkeit im Alltag - Note 15                          :quote:done:
#+begin_quote
Wenn etwas mit meinem Zeitmanagement nicht stimmen würde, könnte ich hier überhaupt nicht arbeiten.
#+end_quote

** Die Kunst der Schlagfertigkeit im Alltag - Note 16                          :quote:done:
#+begin_quote
Und ich bin dafür, wir beide betrachten uns als diese Arbeitsgruppe und entscheiden jetzt.
#+end_quote

** Die Kunst der Schlagfertigkeit im Alltag - Note 17                          :quote:done:
#+begin_quote
Oder als Kompliment. Immerhin widmet Ihnen jemand so viel Aufmerksamkeit, dass er Sie als Zielscheibe ausgewählt hat. Und wer steckt sich schon so kleine Ziele?
#+end_quote

** Die Kunst der Schlagfertigkeit im Alltag - Note 18                          :quote:done:
#+begin_quote
Wenn Sie etwas -ganz ehrlich- sagen müssen, suggerieren Sie, dass der Rest Ihrer Worte eigentlich unehrlich ist. Finden Sie nicht?
#+end_quote

** Die Kunst der Schlagfertigkeit im Alltag - Note 20                          :quote:done:
#+begin_quote
Stimmt, ich wollte mich gerade aufhängen.
#+end_quote

** Die Kunst der Schlagfertigkeit im Alltag - Note 22                          :quote:done:
#+begin_quote
Ablenkungsmanöver aus:
#+end_quote

** Die Kunst der Schlagfertigkeit im Alltag - Note 23                          :quote:done:
#+begin_quote
Wie sagte schon Gandhi: 'Es gibt viel Wichtigeres im Leben, als beständig dessen Geschwindigkeit zu erhöhen.'
#+end_quote

** Die Kunst der Schlagfertigkeit im Alltag - Note 25                          :quote:done:
#+begin_quote
Ähnlich wie die rhetorischen Fragen dienen auch diese dazu, dem Gesprächspartner eine Gemeinsamkeit bewusst zu machen.
#+end_quote

** Die Kunst der Schlagfertigkeit im Alltag - Note 26                          :quote:done:
#+begin_quote
Ideengeber für Sprachspiele sind viele Schriftsteller. Zu den Meistern des Sprachwitzes zählen unter anderem Oscar Wilde, Karl Kraus und Robert Gernhardt.
#+end_quote

** Die Kunst der Schlagfertigkeit im Alltag - Note 27                          :quote:done:
#+begin_quote
Spielbälle- Nehmen Sie's wörtlich:
#+end_quote

** Die Kunst der Schlagfertigkeit im Alltag - Note 29                          :quote:done:
#+begin_quote
Sie es nicht zu bunt? Antwort: Sehen Sie denn lieber schwarz? Zwischenruf: Das klingt aber ziemlich eingebildet! Antwort: Ich bin halt gut ausgebildet.
#+end_quote

** Die Kunst der Schlagfertigkeit im Alltag - Note 30                          :quote:done:
#+begin_quote
Am Ende ist es leicht, den Sack zuzumachen. Noch gemeiner ist: Dem Gegner zum Schein zustimmen. Anschließend seine Thesen und Argumente überhöhen, derart zu übertreiben, dabei seine Zustimmung suggestiv provozieren und anschließend die Übertreibung genüsslich widerlegen:
#+end_quote

** Die Kunst der Schlagfertigkeit im Alltag - Note 31                          :quote:done:
#+begin_quote
Die antiken Sophisten empfahlen sogar, anstelle zu antworten, plötzlich loszulachen, um den Gegner zu verunsichern. Langes, süffisantes Schweigen funktioniert genauso gut. Hauptsache danach kommt ein Knaller.
#+end_quote

** Die Kunst der Schlagfertigkeit im Alltag - Note 32                          :quote:done:
#+begin_quote
Die Kunst der Eristik ist die ganz böse Stiefschwester der Rhetorik, bei der es nicht mehr nur darum geht, einen Angriff zu parieren oder um das allerbeste Argument in den Vordergrund zu stellen, sondern es geht darum,  einen groben Streit mit allen fiesen Mitteln zu gewinnen.
#+end_quote

** Die Kunst der Schlagfertigkeit im Alltag - Note 33                          :quote:done:
#+begin_quote
Spruch: Kennen wir uns nicht? Die Antwort: Kann sein. Bist du die neue Putzkraft hier im Haus?
#+end_quote

** Die Kunst der Schlagfertigkeit im Alltag - Note 34                          :quote:done:
#+begin_quote
Der Spruch: -Hat es wehgetan, als du vom Himmel gefallen bist?- Die Antwort: -Als du mit dem Kopf voran vom Wickeltisch gefallen bist, hat es sicher mehr wehgetan.-
#+end_quote

** Die Kunst der Schlagfertigkeit im Alltag - Note 35                          :quote:done:
#+begin_quote
Der Spruch: -Bist du öfter hier?- Die Antwort: -Wenn du öfter hier bist, dann ist es heute das letzte Mal.-
#+end_quote

** Die Kunst der Schlagfertigkeit im Alltag - Note 36                          :quote:done:
#+begin_quote
du am Samstag schon was vor?- Die Antwort: -Sorry, dieses Wochenende hab ich Kopfschmerzen.-
#+end_quote

** Die Kunst der Schlagfertigkeit im Alltag - Note 37                          :quote:done:
#+begin_quote
Der Spruch: -Wenn ich dich nur einmal nackt sehen könnte, würde ich glücklich sterben.- Die Antwort: -Wenn ich dich nur einmal nackt sehen könnte, würde ich vor Lachen sterben!-
#+end_quote

** Die Kunst der Schlagfertigkeit im Alltag - Note 38                          :quote:done:
#+begin_quote
du trinken?- Die Antwort: -Ein Brechmittel, bitte!-
#+end_quote

** Die Kunst der Schlagfertigkeit im Alltag - Note 39                          :quote:done:
#+begin_quote
Der Spruch: „Du bist aber klein geraten“ Die Antwort: „Blumen wachsen nun mal langsamer als Unkraut-
#+end_quote

** Die Kunst der Schlagfertigkeit im Alltag - Note 40                          :quote:done:
#+begin_quote
Die Antwort: „Sag mal, hab ich die Null gewählt?
#+end_quote

** Die Kunst der Schlagfertigkeit im Alltag - Note 41                          :quote:done:
#+begin_quote
Der Spruch: „Gibt es Dich auch in schön?“ Die Antwort: „Gibt es Dich auch in
#+end_quote

** Die Kunst der Schlagfertigkeit im Alltag - Note 42                          :quote:done:
#+begin_quote
Der Spruch: Du bist ganz schön behindert! Die Antwort: Da krieg ich später wenigstens immer einen Parkplatz.
#+end_quote

** Die Kunst der Schlagfertigkeit im Alltag - Note 43                          :quote:done:
#+begin_quote
-Der Spruch: „Was verdienen Sie eigentlich?“ Die Antwort: „Ich verdiene es in den Himmel zu kommen.“ oder„ Ich verdiene: Glück, Gesundheit und ein langes Leben!“
#+end_quote

** Die Kunst der Schlagfertigkeit im Alltag - Note 44                          :quote:done:
#+begin_quote
Antwort: „Ich baue Nudeln in Italien an.“ oder  „Wer Glashaus sitzt, sollte nicht mit Steinen werfen.
#+end_quote
