:PROPERTIES:
:ID:       0c4ceb51-171c-4a8f-9175-b75ce6901862
:END:
#+title: Die Mutter der Erfindung
#+filetags: book
#+date: 2023-10-17

👉 [[https://www.goodreads.com/en/book/show/56969567][Mother of Invention: How Good Ideas Get Ignored in an Economy Built for Men by Katrine Marçal]]

* Notes
** Teil 1: Erfindungen
*** Note 1
#+begin_quote
Die Geschichtsschreibung war sich lange einig, dass das Rad in Mesopotamien erfunden wurde. Es diente dort als
Töpferscheibe, wurde also nicht für den Transport verwendet. Inzwischen glauben manche Historiker, dass Bergleute in den
Karpaten schon mit Karren Kupfererz aus ihren Minen rollten, lange bevor sich in Mesopotamien die Töpferscheiben
drehten. Das älteste noch erhaltene Rad ist fünftausend Jahre alt. Es wurde in Slowenien, rund zwanzig Kilometer südlich
von Ljubljana, gefunden. Mit anderen Worten: Die Technologie, die Bernard Sadow schließlich nutzte, um sein
Kofferproblem zu lösen, existiert seit mindestens fünf Jahrtausenden.
#+end_quote
*** Note 2
#+begin_quote
Robert Shiller war offenbar fasziniert von diesem Thema, es taucht in seinen Veröffentlichungen immer wieder auf. In
seinem Buch «Narrative Wirtschaft» erwägt der weltbekannte Ökonom die These, unser Widerstand gegen Koffer auf Rädern
lasse sich durch eine Form von Gruppendruck erklären, die häufig eine Rolle spielt, wenn neumodische Ideen zunächst auf
Skepsis stoßen. Wenn niemand sonst die Neuerung nutzt – insbesondere niemand, den wir als erfolgreich einstufen –,
vermuten wir einen rationalen Grund dahinter. Was, wenn diese Neuerung schädlich ist oder sogar gefährlich? Da wählen
wir lieber das bekannte Übel. Wenn niemand sonst seinen Koffer hinter sich herzieht, kann es zu nichts gut sein.
#+end_quote
*** Note 3
#+begin_quote
Ein weiterer weltbekannter Denker, den das Rollkoffer-Rätsel in seinen Bann geschlagen hat, ist [[id:f1d276d1-1549-416f-84dc-4d8dd0942fd5][Nassim Taleb]]. Er hatte
selbst jahrelang schwere Gepäckstücke durch Flughäfen und Bahnhöfe geschleppt und wunderte sich rückblickend, dass er
den Status quo so fraglos akzeptierte. In seinem Buch «Antifragilität» setzt er sich mit dem Phänomen auseinander. Taleb
begreift unsere Unfähigkeit, Koffer mit Rollen zu versehen, als Paradebeispiel für die allgemeine Neigung, gerade die
einfachsten Lösungen zu übersehen. Wir Menschen haben es gern schwierig, verschwenderisch und kompliziert. Nur weil
Erfindungen wie Koffer auf Rollen im Nachhinein naheliegend erscheinen, muss das also nicht heißen, dass sie es wirklich
waren.
#+end_quote
*** Note 4
Männer lehnen Einkaufswagen ab:

#+begin_quote
Niemand wollte die Vehikel benutzen. Man lehnte sie komplett ab. Goldman musste eigens Statisten anheuern, die seine
Einkaufswagen durch die Gänge schoben, um die Kundschaft an das Konzept zu gewöhnen. Männer empfanden die Neuerung als
persönlichen Affront: «Sehe ich aus, als könnte ich mit meinen starken Armen diesen lächerlichen kleinen Korb nicht
tragen?», riefen sie. Bevor Sylvan Goldman mit seiner Idee Millionen verdienen konnte, musste er erst einmal die
Vorstellung überwinden, es sei unmännlich, einen Einkaufswagen zu benutzen. Diese Vorstellung hatte durchaus Gewicht.
#+end_quote
*** Note 5
Vom Erfinder des Rollkoffers:

#+begin_quote
Das stürzte Lancelot in ein unlösbares Dilemma und verlieh dem Angebot des Zwergs einen diabolischen Dreh. Die
entscheidende Pointe der Verserzählung besteht darin zu zeigen, wie tief der edle Lancelot für seine Königin und ihre
Liebe zu sinken bereit ist. Sehr tief, wie sich herausstellt. Er steigt auf den Karren und bringt damit seine tragische
Geschichte ins Rollen. Aber kommen wir zu Bernard Sadow zurück und zu seiner revolutionären Erfindung. In einem der
wenigen Interviews, die er gegeben hat, sprach er darüber, wie schwierig es war, den amerikanischen Warenhäusern sein
Produkt schmackhaft zu machen: «Es gab damals diese machohafte Einstellung. Männer trugen ihren Frauen das Gepäck. Das
wurde als der natürliche Lauf der Dinge angesehen.»
#+end_quote
*** Note 6
Über *echte* Männer:

#+begin_quote
Solche Fragen bilden den Kern des vorliegenden Buches. Wie sich noch zeigen wird, ist die Welt voll von Menschen, die
lieber sterben würden, als bestimmte Männlichkeitsideale aufzugeben. Glaubenssätze wie «Echte Männer essen kein Gemüse»,
«Echte Männer gehen nicht mit jeder Kleinigkeit zum Arzt» und «Echte Männer benutzen keine Kondome» kosten buchstäblich
echte Männer aus Fleisch und Blut das Leben. Unsere Vorstellungen davon, was einen Mann ausmacht, gehören zu den am
wenigsten wandelbaren kulturellen Konstanten, und sie zu erhalten ist uns wichtiger als das Leben selbst. So gesehen ist
es schon weniger überraschend, dass sie technische Neuerungen ein paar Jahrtausende lang ausbremsen können. Wir sind es
nur nicht gewohnt, Genderrollen und Innovation zueinander in Beziehung zu setzen.
#+end_quote
*** Note 7

Über Bertha Benz (Frau von Carl Benz)

#+begin_quote
Dazu sollte man wissen, dass Bertha Benz fast ihr gesamtes Vermögen in diese Erfindung gesteckt hatte. Erst hatte sie
ihre Mitgift in die Firma investiert, dann ihre Eltern überredet, ihr eine vorzeitige Erbschaft zu überschreiben. Von
den 4244 Gulden, mit denen sie den Betrieb ihres Mannes finanzierte, hätte sie in Mannheim eine stattliche Villa kaufen
können. Stattdessen gab sie alles für seinen Traum – einen Viertaktmotor, der einen Wagen ohne Pferde antreiben sollte.
Nach jahrelangen Versuchen war das erste Automobil fertiggestellt. Der Benz Patent-Motorwagen erreichte eine
Höchstgeschwindigkeit von sechzehn Stundenkilometern und besaß einen Einzylinder-Viertaktmotor mit 0,75 Pferdestärken.
Das Entscheidende aber war, dass er funktionierte.
#+end_quote
** Teil 2: Technik
*** Note 8
#+begin_quote
1961 beschlossen die USA, einen Mann auf den Mond zu schicken. Dass es ein Mann sein würde, ergab sich im selben Jahr
aus der Regelung, dass nur amerikanische Kampfpiloten Astronauten werden durften. Da Frauen nicht als Kampfpiloten
zugelassen waren, kamen nur Männer für den Job infrage. *Die UdSSR schickte bereits 1963 mit Walentina Tereschkowa eine
erste Kosmonautin ins Weltall*. Im Unterschied zu allem anderen, was die UdSSR im Weltall anstellte, schien dieses Detail
auf die USA jedoch wenig Eindruck zu machen.
#+end_quote
*** Note 9
#+begin_quote
Die Notwendigkeit ist die Mutter der Erfindung, heißt es, aber es kann nicht schaden, sie mit Elterngeld auszustatten.
Der Krieg – oder auch nur die Angst davor – bewegt Staaten dazu, all ihre Ressourcen in die militärische Forschung zu
stecken. *Wo würden wir heute stehen, wenn wir die Summen, die in die Abschreckungspolitik des Kalten Krieges geflossen
sind, in das Abwenden der Klimakrise investiert hätten? Womöglich wären wir der Lösung des Problems ein wenig näher.
Dennoch klammern wir uns an die Vorstellung, man müsse dem Erfindergeist mit einem Mindestmaß an Blut und Tod auf die
Sprünge helfen*.
#+end_quote
*** Note 10
#+begin_quote
Der technische Fortschritt, glauben wir, müsse mit einer Waffe begonnen haben. Und der erste Erfinder müsse ein Mann
gewesen sein. *Dabei kann es ebenso gut sein, dass spitze Stöcke ursprünglich von Frauen genutzt wurden, um Nahrung zu
sammeln, bevor man sie für die Jagd umfunktioniert hat*.
#+end_quote
*** Note 11
Rolle der Frauen:

#+begin_quote
Es lässt sich nicht genau rekonstruieren, wie es dazu kam, aber irgendwann wurde es unter Menschen üblich, dass Frauen
ihre Zeit überwiegend mit der Betreuung von Kleinkindern, der Nahrungszubereitung und der Herstellung von Kleidung
verbrachten. Deshalb gehen Wissenschaftler heute davon aus, dass zum Beispiel Mörser und Mahlsteine von Frauen erfunden
wurden und dass Frauen Fortschritte beim Sammeln, Transportieren und Zubereiten von Nahrung anstießen. Ebenso lässt es
sich aufgrund ihrer Spezialisierung annehmen, dass Frauen die Techniken entwickelten, Nahrung zu räuchern oder sie in
Honig oder Salz zu konservieren. Auch Kochen ist Technik. Viele physikalische und chemische Innovationen waren dafür
nötig, und das Kochen hat umgekehrt zu anderen technologischen Bereichen wie der Metallgewinnung, dem Töpfern oder dem
Färberhandwerk beigetragen oder sie hervorgebracht. Zum Kochen gehören Prozesse und Techniken, die man nicht einfach so
entdecken kann – man muss experimentieren, um sie in effiziente, wiederholbare Vorgänge zu überführen. Zur Erfindung des
Kochens brauchte es weit mehr als nur jemanden, der ein Schwein ins Lagerfeuer schubste und feststellte, wie gut
geröstete Schwarte riecht.
#+end_quote
*** Note 12

Frauen in der Geschichte:

#+begin_quote
oder eines Tages gebären könnten. Als wäre der Weg durch den Muttermund ins Licht der Welt nicht die universellste
menschliche Erfahrung von allen. Ganz ähnlich verhält es sich mit der Geschichte der Technik: *Von Männern erfundene
Geräte gehen in die Menschheitsgeschichte ein (im Englischen heißt es passenderweise «history»)*, während man Erfindungen
von Frauen im Nischenfach Frauengeschichte abhandelt. Daraus ergibt sich ein kleines Folgeproblem, nämlich dass wir
alles, aber auch wirklich alles fehlinterpretieren.
#+end_quote
*** Note 13

Technische Berufe vs "angelernte" Fähigkeiten:

#+begin_quote
Ist es überhaupt folgerichtig, Berufe, die mithilfe von Gerätschaften ausgeführt werden, mit höheren Honoraren und einem
höheren Status auszustatten? Die bloße Tatsache, dass eine Aufgabe den Einsatz von Werkzeug erfordert, macht sie nicht
notwendigerweise anspruchsvoller. Eine Hebamme ist in der Lage, mit der Hand in den Geburtskanal zu greifen und die
Haltung eines Kindes zu verändern, dessen Schulter im Becken der Mutter feststeckt. Das ist alles andere als
kinderleicht, es braucht dazu jahrelange Übung. Doch es gehört nun mal zu unseren Vorannahmen, dass von Hand ausgeführte
Arbeiten weniger Können erfordern als die mithilfe von Gerätschaften ausgeführten. «Frauenberufe» werden schon deshalb
schlechter bezahlt, weil wir sie nicht als technische Berufe auffassen.
#+end_quote
*** Note 14

Über Teflon:

#+begin_quote
Einige Jahrzehnte nach der ersten Mondlandung begann sich der Mythos zu verbreiten, wir verdankten die Teflonpfannen in
unseren Küchen dem Umstand, dass die NASA das Material für seine Raumfahrzeuge verwendet hatte. Tatsächlich gab es sie
schon, lange bevor die NASA Raketen ins Weltall schoss. Eine Französin namens Colette Grégoire kam 1954 auf die Idee,
die Beschichtung auf der Angelausrüstung ihres Mannes könnte sich in ihren Bratpfannen als nützlich erweisen. Dieser
Einfall machte ihren Mann sehr reich. Das von ihm gegründete Unternehmen Tefal gibt es bis heute.
#+end_quote
*** Note 15

PS vs "Mädchenjahre":

#+begin_quote
Das verdanken wir einem Schotten namens James Watt. Ende des 18. Jahrhunderts entwickelte Watt eine verbesserte Version
der Dampfmaschine. Als Geschäftsmann wollte er sein neues Produkt natürlich gewinnbringend verkaufen. Aber wie sollte er
dessen Vorzüge einem potenziellen Kunden vermitteln, der sich mit Dampfmaschinen gar nicht auskannte? Watt verfiel auf
die Idee, seine Innovation in einem Vokabular anzupreisen, das der Käuferschaft vertraut war – daher die Pferde. Sie
zogen nämlich üblicherweise die Lasten, die Watts neuartige Dampfmaschine übernehmen sollte. Als Argument für den Erwerb
seines Produkts konnte Watt den Interessierten einfach angeben, wie viele Pferde es ersetzen würde.

Watt stellte eine über den Daumen gepeilte Schätzung zur Leistung eines durchschnittlichen Pferdes an und errechnete,
wie viele dieser Pferde seine Dampfmaschine ersetzte. Diese neue Messgröße war anschaulich, den Pferden gegenüber
allerdings eine Beleidigung: Eine Pferdestärke entspricht nämlich keineswegs der Leistung eines Pferdes. Arial, ein
schwedischer Hengst, der in den 1950er-Jahren Berühmtheit erlangte, brachte es auf stolze 12,5 PS. Nun war Arial ein
außergewöhnliches Tier, aber auch durchschnittliche Arbeitspferde können durchaus 10 PS erreichen. Davon einmal
abgesehen, erschuf Watt eine Maßeinheit, die die Leistung seiner Maschine mit der Leistung derjenigen verglich, die
bestimmte Aufgaben bisher übernommen hatten – in diesem Fall die Pferde. Und nach derselben Logik sprach George Stibitz
Jahrzehnte später von den «Mädchenjahren».
#+end_quote
*** Note 16                                               :computer:

#+begin_quote
Das Wort computer bezeichnete im Englischen zunächst kein Gerät, sondern einen Beruf. Wer eine Anstellung als computer
fand, löste beruflich von morgens bis abends Rechenaufgaben.
#+end_quote
*** Note 17                                               :computer:

#+begin_quote
Die Arbeit der computer galt nicht als intellektuell anspruchsvoll. Genau deshalb begann man die Datenverarbeitung mehr
und mehr als Frauenberuf zu betrachten. In den USA wurden die entsprechenden Stellen aufgrund ihres geringen Status auch
häufig an Afroamerikaner, Juden und Menschen mit Behinderungen vergeben. Arbeitnehmer, die anderswo ausgeschlossen
blieben,
#+end_quote
*** Note 18

#+begin_quote
Bis dahin waren computer überwiegend Männer. Doch im neuen Jahrhundert entdeckten immer mehr Unternehmen, dass man durch
die Beschäftigung von Frauen Geld einsparen konnte. Schließlich konnte man die mit der Hälfte eines Männergehalts
abspeisen, ohne dass sie sich darüber beschwerten. Als im Harvard College Observatory Daten aus der Himmelsbeobachtung
verarbeitet werden sollten, wurden dafür ausschließlich Frauen engagiert. Der Leiter des Observatoriums klopfte sich für
diese kluge Sparmaßnahme kräftig selbst auf die Schulter. Bald arbeiteten im Datenverarbeitungssektor nicht etwa die
Vorväter der heutigen Kapuzenpulli-Nerds (mit ihren legendär miserablen Sozialkompetenzen), sondern adrette junge Damen
in Korsetts, die von wissenschaftlichen Karrieren träumten.
#+end_quote
*** Note 19                                               :computer:

#+begin_quote
Wie sich herausstellte, waren sie gut darin, und weil sie so gut darin waren, begannen ihre Arbeitgeber, diese Fähigkeit
als «natürliche weibliche Eigenschaft» anzusehen. Eine solche natürliche Eigenschaft musste man natürlich nicht wie eine
eigens erworbene Qualifikation entlohnen. Diese Denkweise versetzte Frauen in eine ausweglose Lage. Wenn eine Arbeiterin
eine Aufgabe nicht beherrschte, galt das als Beweis, dass Frauen insgesamt ein geringerer Lohn zustand: Da seht ihr’s –
Frauen können eben nicht arbeiten wie ein Mann! Aber es galt, wie eben beschrieben, auch das genaue Gegenteil: Wenn eine
Arbeiterin in etwas besonders gut war, musste auch das als Grund herhalten, Frauen schlecht zu entlohnen. Egal, wie es
um ihre Fähigkeiten bestellt war – es ließ sich immer ein Grund für geringere Vergütung finden. Dazu musste man bloß
alles, worin Frauen sich hervortaten, als ihre natürliche weibliche Eigenschaft definieren. Dann konnte die Frau
schließlich nichts dafür, dass eine biologische Veranlagung ihr half, Strumpfspitzen besonders sauber zu vernähen,
Computer zu programmieren oder alte Menschen zu pflegen.
#+end_quote
*** Note 20                                               :computer:

#+begin_quote
und Haushalt kombinieren konnte. In vielerlei Hinsicht, so hieß es, konnte man den Umgang mit Computern als Erweiterung
der weiblichen Natur betrachten. Dieses Klischee erweist sich immer wieder als praktisch, wenn es darum geht, niedrige
Löhne zu begründen. Wenn die für eine Tätigkeit benötigten Fähigkeiten geradezu der Biologie der Frauen eingeschrieben
waren, warum sollte man ihnen dann viel dafür bezahlen?
#+end_quote
*** Note 21

#+begin_quote
Dieser Denkweise begegnen wir noch heute. Die Gesellschaft greift auf diese Argumentation zurück, wenn es etwa um
Altenpflege oder Kinderbetreuung geht. *Wir erleben, dass Frauen die entsprechenden Berufe ergreifen und ohne lange
institutionelle Ausbildung gut darin werden, und daraus folgern wir, die Stellen seien «gering qualifiziert» und müssten
entsprechend nicht allzu hoch dotiert sein*. *Wenn dagegen Männer ein «natürliches Talent» für irgendetwas mitbringen,
gilt das als Argument für das genaue Gegenteil, nämlich dafür, sie reichlich zu vergüten*.
#+end_quote
** Teil 3: Weiblichkeit
*** Note 22

#+begin_quote
Dazu passend wurde das erste E-Mail-Protokoll von dem Amerikaner Vint Cerf entwickelt, der schwerhörig war. Cerf
verstand den großen Nutzen von E-Mails sofort, denn er konnte damit vom Arbeitsplatz aus mit seiner Familie
kommunizieren, ohne dass sie aus vollem Hals in den Telefonhörer schreien mussten. Dass wir unsere Smartphones mit
Wischgesten bedienen können, verdanken wir ebenfalls einem Amerikaner: Wayne Westerman litt an Nervenschädigungen an der
rechten Hand und konnte daher keine Computermaus bedienen. Also entwickelte er eine Technologie, die es ihm erlaubte,
den Cursor mit einem Bedienfeld zu steuern. Diese Erfindung verkaufte er 2005 an Apple. Zwei Jahre darauf präsentierte
Steve Jobs der Welt das erste iPhone.
#+end_quote
*** Note 23

ber *Prosumer*:

#+begin_quote
In den 2010ern verschwammen die Grenzen zwischen Produktion und Konsum, und seither ist öfter von «Prosumern» oder
«Prosumenten» die Rede. In diesem Grenzgebiet siedelten etliche Frauen ihre Unternehmen an. Auch Influencer sind
Prosumer. *So konsumiert eine Vloggerin zum Beispiel Vitaminpräparate und produziert Werbung dafür, indem sie
dokumentiert, wie sie das Mittel einnimmt. Ihre Hauptaufgabe besteht darin, das Publikum davon zu überzeugen, dass sie
die Vitamine auch nehmen würde, wenn sie kein Geld dafür bekäme*. Der Trick ist, den Followern zu vermitteln, dass man
eine normale Konsumentin ist. Und das ist man ja auch. Und doch wiederum nicht.
#+end_quote
*** Note 24

Über die neuen "Social Media Berufe":

#+begin_quote
Auch in Europa sind Frauen oft unzufrieden mit ihren Arbeitsverhältnissen: Eine Anwältin zum Beispiel hat es vielleicht
satt, dass sie schlechter bezahlt wird als männliche Kollegen, oder sieht es nicht ein, dass in ihrer Kanzlei zwölf
Stunden Büroarbeitszeit erwartet werden. Die technische Entwicklung hat mehr Unternehmerinnen hervorgebracht, weil es
leichter geworden ist, ein Unternehmen zu gründen und es von zu Hause aus zu führen. In den 2010ern wurde Unternehmertum
sogar als neue Form des Feminismus begrüßt. Am meisten Aufmerksamkeit erfuhren natürlich jene Unternehmerinnen, die wie
beschrieben ihren Lebensunterhalt damit verdienten, ihre Konsumentscheidungen öffentlich zu machen und dabei Ausschnitte
aus dem Alltagsleben ihrer Familie zu präsentieren. Das war zugleich die Geschäftsidee, die sich am leichtesten mit den
weiblichen Rollenerwartungen in Einklang bringen ließ, wenn sie nicht sogar wie eine Fortschreibung dieser Erwartungen
wirkte
#+end_quote
*** Note 25

Auch Männer schlagen aus ihren Hobbys Kapital:

#+begin_quote
Gleichzeitig bieten diese Plattformen auch Möglichkeiten, mit traditionell weiblichen Kompetenzen Geld zu verdienen. Und
was ist falsch daran, ein Geschäft auf den eigenen Interessen aufzubauen – auf Schönheitstipps und dem eigenen Haus, auf
Kindererziehung, Backrezepten und dem Wunsch, für die Kinder da zu sein, wenn sie aus der Schule kommen? Männliche
Promis verurteilen wir ja auch nicht dafür, wenn sie aus ihren Hobbys Kapital schlagen. Man denke nur an George Clooney,
der eine halbe Milliarde an seinem Tequila verdient hat.
#+end_quote
*** Note 26

#+begin_quote
Barry Lord zeigt in «[[https://www.goodreads.com/en/book/show/18767114][Art & Energy]]», dass unser Selbstbild eng mit unserem Energieverbrauch verknüpft ist. Die heutige
Fixierung auf die Konsumentenrolle verdankt sich dem Zeitalter des Erdöls. Wir werden uns nicht von den fossilen
Brennstoffen lösen können, wenn wir nicht zugleich eine neue gesellschaftliche Rolle für uns erfinden. Solange wir uns
selbst primär als Konsumenten begreifen, werden wir mögliche Wege aus der Klimakrise gar nicht erst erkennen. Statt die
Welt zu konsumieren, müssen wir lernen, sie zu erhalten. Und dabei hilft uns Kylie Jenner eher wenig weiter.
#+end_quote
*** Note 27

Wie wir angefangen haben uns als *Konsumenten* zu definieren:

#+begin_quote
Der Autor Barry Lord beschreibt diesen Wandel in seinem Buch «Art & Energy». *Beginnend in den Siebzigerjahren und zur
selben Zeit, als die Wirtschaft immer stärker vom Erdöl abhängig wurde, gewann unsere Rolle als Konsumenten kulturell an
Bedeutung*. *Das Erdöl befeuerte eine wahre Explosion kostengünstiger Konsumgüter, deren Kauf und Verkauf zum
bedeutenden Wirtschaftsfaktor wurde. Und das beeinflusste wiederum das kulturelle Selbstbild: Wir definierten uns nicht
mehr in erster Linie über unser Verhältnis zur Produktion von Waren, sondern als Konsumenten*. Das war fortan unser
wichtigster Beitrag zum Wirtschaftsgeschehen, und somit war es auch in Krisenzeiten unsere Aufgabe zu konsumieren. Darin
lag die Macht des einzelnen Bürgers, und in dem Sinne wurden alle ein Stück weit zu Frauen. Das Kaufhaus hatte uns
aufgekauft, könnte man sagen.
#+end_quote
** Teil 4: Körper
*** Note 28
Wirtschaftskrise von 2008:

#+begin_quote
Wirtschaftlich betrachtet, war diese Krise sehr untypisch. Üblicherweise verläuft die Dramaturgie einer Wirtschaftskrise
nämlich vom Abstrakten hin zum Konkreten. Die Wirtschaftskrise von 2008 zum Beispiel begann mit Finanzprodukten, die
derart komplex waren, dass selbst deren Verkäufer nicht hätten sagen können, woraus sie bestanden. Als den Investoren
irgendwann auffiel, dass ihr Goldschatz in Wahrheit aus Krediten bestand, die niemand würde zurückzahlen können,
gerieten sie in Panik. Im Tumult kollabierten mehrere amerikanische Banken rasch hintereinander, und dann griff die
Krise auf weitere Bereiche der Wirtschaft über. Das hatte katastrophale, ganz konkrete Folgen für die Menschen, die ihre
Arbeitsplätze, ihre Ersparnisse, ihre Häuser und in Einzelfällen ihr Leben verloren. So stellen wir uns
Wirtschaftskrisen im Allgemeinen vor: Der menschliche Körper kommt sozusagen als Letztes.
#+end_quote
*** Note 29

#+begin_quote
Das rief uns eindrucksvoll eine schlichte Tatsache ins Gedächtnis: *Die Wirtschaft basiert auf dem menschlichen Körper*.
Jetzt ist es uns allen bewusst, aber erinnern wir uns an den März 2020, als bei dieser revolutionären Entdeckung der
Aktienmarkt einbrach. An die Zeit, als ein Wirtschaftsexperte nach dem anderen den Umstand, dass Menschen sich mit Viren
anstecken können, als einen schwarzen Schwan bezeichnete. Mit anderen Worten: als ein bedeutsames, unwahrscheinliches,
nicht vorhersagbares Ereignis. Dabei gehört es zu den Grundtatsachen des menschlichen Daseins, dass Körper einander mit
einem Virus infizieren können, dass Menschen verletzlich sind und aufeinander angewiesen. Wie zum Teufel konnten wir das
vergessen?
#+end_quote
*** Note 30                                               :quote:

#+begin_quote
*Es geht ganz einfach darum, dass wahrer Fortschritt von der Realität ausgehen sollte. Und unsere Realität, das sind
menschliche Körper. Unsere Wirtschaft besteht aus menschlichen Körpern. Körpern, die arbeiten, Körpern, die Pflege
brauchen, Körpern, die andere Körper hervorbringen. Körpern, die geboren werden, altern und sterben*. Die in vielen
Stadien ihres Lebens auf Hilfe angewiesen sind und darauf, dass ihre Gesellschaft diese Hilfe ermöglicht.
#+end_quote
*** Note 31                                               :quote:

#+begin_quote
Du wurdest nicht von den Wikingergöttern aus einem Stück Holz geschnitzt. Du bist keine hydraulische Statue, keine
Telefonzentrale, kein Computer. Du wurdest strampelnd und schreiend aus einem pulsierenden, blutroten Mutterschoß
geboren. Komm damit klar. Und dann schaffe eine Wirtschaft, die auf dem basiert, was wir wirklich wissen.
#+end_quote
*** Note 32

Über vermeintlich "sichere" Jobs:

#+begin_quote
Wenn Maschinen Menschen in der Fabrik ersetzen können, aber nicht bei der Raumpflege zu Hause, mag es passieren, dass
Putzjobs eines Tages sicherer sind als die Arbeit in Fabriken. Und wenn in den Fabriken mehr Männer arbeiten, in den
Haushalten aber mehr Frauen, ahnen wir schon, worauf es hinausläuft
#+end_quote

Sie auch [[id:0cf14cd2-8c41-49e8-b1e6-394d41410401][Polanyi's Paradox]]
** Teil 5: Zukunft
*** Note 33

Über *körperliche* Intelligenz:

#+begin_quote
«Elefanten spielen kein Schach», sagt Rodney Brooks. Und trotzdem sind Elefanten verdammt schlau. Sie sind in vielerlei
Hinsicht schlauer als der rechenstärkste Computer, wenn auch in anderen Hinsichten dümmer. Kurz gesagt, es ist
kompliziert. Hunde scheinen es zu merken, wenn ihr Besitzer traurig ist, während Computer damit Schwierigkeiten haben.
Wer von beiden ist also intelligenter? *Bloß weil eine Maschine Garri Kasparow im Schach besiegt, heißt das nicht, dass
sie im Tennis gegen Serena Williams antreten könnte. An ihr zeigt sich eine andere Form der Intelligenz. Eine
körperliche Intelligenz*. *Und auch darin offenbart sich wieder vieles, das uns als Menschen ausmacht. Aber irgendwie
fällt es uns schwer, das zuzugeben*.
#+end_quote

*** Note 34

Wird KI wirklich unser Jobs wegnehmen?

#+begin_quote
Was sollen die nutzlos gewordenen Menschen den ganzen Tag machen? Können wir uns darauf verlassen, dass sie friedlich zu Hause sitzen und Computerspiele spielen? Oder würden sie – Schockschwerenot! – etwa den Aufstand proben? Mit der Heugabel in der Hand ins Silicon Valley ziehen? Politiker wählen, die schlecht fürs Geschäft sind oder die meinen, Tech-Konzerne sollten wie alle anderen Steuern zahlen? Wird die «nutzlose Klasse» auf die Straße gehen und fliegende Autos demolieren? Muss dann die Elite in selbstversorgenden, CO2-neutralen Bunkern mit Solardächern und Wachrobotern leben? Bezahlbar wäre es, aber langfristig darin zu wohnen macht wenig Freude, wenn draußen «Krieg den Palästen» gerufen wird.
#+end_quote
*** Note 35

#+begin_quote
Dabei wissen wir schon lange, dass weder IQ-Tests noch Schulnoten den Karriereerfolg einer Person zuverlässig voraussagen. Es gibt andere Faktoren, die eine Rolle spielen. Können Maschinen auch die replizieren? Schließlich finden sich darunter genau die Dinge, mit denen sich Maschinen so schwertun:* emotionale Intelligenz, die Fähigkeit, Beziehungen aufzubauen, andere zu verstehen, die Dynamik einer Begegnung richtig einzuschätzen und zu nutzen; das Vermögen, aus anderen das Beste herauszuholen und zu begreifen, was in einer Gruppe vor sich geht – all das also, was wir gern etwas herablassend unter «Soft Skills» zusammenfassen*.

Männliche Zukunftsforscher sind schnell mit der These bei der Hand, dass das Spiel für die gesamte Menschheit gelaufen
sei, sobald Maschinen einen höheren Intelligenzquotienten erreichten. *Doch die «Wissensökonomie» basiert in Wahrheit auf
etlichen Faktoren, die Experten gern übersehen. Sie ist eben auch eine «Beziehungsökonomie» und eine «Fürsorgeökonomie»*.
Die wirtschaftliche Dynamik speist sich nicht nur aus Körperkraft oder Geistesstärke. *Qualitäten wie Fürsorglichkeit,
Vertrauensbildung, Verständnis und ein angemessener emotionaler Umgang mit verschiedensten Menschen und Situationen sind
Teil eines jeden Wirtschaftssystems. In fast jedem Arbeitsumfeld spielen sie eine bedeutende Rolle. Dennoch sehen wir
«Soft Skills» nicht als vollwertige Qualifikationen an. Und zwar deshalb, weil wir sie als feminin verbuchen.*
#+end_quote
*** Note 36

Drei Berecieh für den Einsatz von KI:

#+begin_quote
Hier werden meist drei Bereiche genannt, und über den ersten haben wir in Kapitel 8 gesprochen: Roboter haben Probleme
mit vielen Bewegungsabläufen, die wir Menschen vollführen, ohne nachzudenken. Das [[id:0cf14cd2-8c41-49e8-b1e6-394d41410401][Polanyi-Paradoxon]] ist auch auf dem
Arbeitsmarkt von Bedeutung. *Es ist einfacher, Garri Kasparows Form von Intelligenz zu automatisieren als die von Serena
Williams*.

*Der zweite Bereich*: Wer weiß, was technologisch in den kommenden Jahrzehnten möglich sein wird? *Aber bisher sind
Menschen den Robotern weit überlegen in Tätigkeiten, die Kreativität erfordern*. Wer Schwierigkeiten hat, seine täglichen
Arbeitsabläufe in wenigen, einfachen Sätzen zu beschreiben, wird vermutlich nicht allzu bald durch Algorithmen ersetzt.

*Drittens haben Maschinen Mühe bei allem, was emotionale Intelligenz erfordert*. Unsere menschliche Gefühlswelt eröffnet
uns Fähigkeiten, die auf dem Arbeitsmarkt ausgesprochen wichtig sind. Wer im Beruf hauptsächlich damit befasst ist,
andere zu betreuen, andere von etwas zu überzeugen oder auch nur mit anderen zu kommunizieren, darf sich einigermaßen
sicher fühlen. *Die meisten Analysen kommen zu dem Schluss, dass Maschinen bis auf Weiteres nicht als Pflegekräfte,
Erzieher, Psychiaterinnen oder Sozialarbeiter zum Einsatz kommen werden.*
#+end_quote
