:PROPERTIES:
:ID:       b139ee33-5e79-4470-899c-b0dc8da1ca2b
:END:
#+title: Discipline is Destiny
#+filetags: :philosophy:book:
#+date: 2023-03-10

[[https://www.goodreads.com/book/show/60018575-discipline-is-destiny?ref=nav_sb_ss_1_20][Discipline Is Destiny: The Power of Self-Control by Ryan Holiday | Goodreads]]

* Notes
** Note 10

#+begin_quote
Yet virtue—arete—translates to something very simple and very timeless: Excellence. Moral. Physical. Mental.
In the ancient world, virtue was comprised of four key components.

- Courage.
- Temperance.
- Justice.
- Wisdom.
#+end_quote

** Note 13                                                 :quote:

#+begin_quote
Freedom, as Eisenhower famously said, is actually only the “opportunity for self-discipline.”
#+end_quote

** Note 38

#+begin_quote
Walking. Rowing. Boxing. Wrestling. Hiking. Hunting. Horseback riding. Football. Roosevelt did it all. There was hardly a day when he was not actively exercising, playing sports, or getting out into nature. Even as president, he was active enough to put much younger people to shame. “While in the White House,” Roosevelt wrote, “I always tried to get a couple of hours’ exercise in the afternoons.”
#+end_quote

** Note 43

#+begin_quote
In some ways, the habit itself is less important than what we’re really quitting, which is dependency. What the Buddhists call tanha. The thirst. The craving. Maybe with time you can go back to recreational usage—of whatever it is—yet even to do that, you’re first going to have to quit the habituation. It’s not the sex or the likes or the drink. It’s the need. And it’s this need that is the source of suffering.
#+end_quote

** Note 51

#+begin_quote
Of course, this is less about spit and polish than it is about orderliness or kosmiotes, as the Stoics called it. Chefs speak of mise en place—prepping and organizing everything you need before setting down and getting down to work. Nothing spilling out onto anything else. Nothing random. Nothing getting in the way, nothing slowing anything or anyone down.
#+end_quote

** Note 84

#+begin_quote
The most surefire way to make yourself more fragile, to cut your career short, is to be undisciplined about rest and recovery, to push yourself too hard, too fast, to overtrain and to pursue the false economy of overwork. *Manage the load*.
#+end_quote

** Note 87

#+begin_quote
You want to think clearly tomorrow? You want to handle the small things right? You want to have the energy to hustle? Go to sleep. Not just because your health depends on it, but because it is an act of character from which all our other decisions and actions descend.
#+end_quote

** Note 92

#+begin_quote
The fact is, the body keeps score.
The decisions we make today and always are being recorded, daily, silently and not so silently, in who we are, what we look like, how we feel.
Are you making good decisions? Are you in control . . . or is your body?

This matters not just physically, but also mentally and spiritually. Temperance in the body affects the mind, and just as much, intemperance and excess physically prevent the mind from working as it should. The neuroscientist Lisa Feldman Barrett has explained it in terms of a *body budget*: *Our brain regulates our body, but if we are physically bankrupt, the brain cannot possibly do its job*.
#+end_quote

** Note 99

#+begin_quote
Discipline isn’t just endurance and strength. It’s also finding the best, most economical way of doing something. It’s the commitment to evolving and improving so that *the tasks get more efficient as you go*. *A true master isn’t just dominating their profession, they’re also doing it with ease* . . . while everyone else is still huffing and puffing.
#+end_quote

** Note 23

#+begin_quote
We’re convinced everyone cares so much about what we’re doing that we get stuck. We tell ourselves it’s self-discipline when in fact, it’s self-consciousness.
As they say, *another way to spell “perfectionism” is p-a-r-a-l-y-s-i-s*.
#+end_quote

** Note 28

#+begin_quote
The graveyard of lost potential, we might say, is filled with people who just needed to do something else first.
#+end_quote

** Note 44
About conflicts:

#+begin_quote
Remember always: As wrong as they are, as annoying as it is, *it takes two for a real conflict to happen*. As the Stoics said, when we are offended, when we fight, we are complicit. We have chosen to engage. We have traded self-control for self-indulgence. We’ve allowed our cooler head to turn hot—even though we know hot heads rarely make good decisions.
#+end_quote

** Note 51

#+begin_quote
It’s a balance. While each of us needs to cultivate the courage to speak up and speak the truth, *we also need to develop the self-discipline to know when to stay focused and when to shut up* (and how to measure what we do say with the utmost economy)
#+end_quote

** Note 52

#+begin_quote
Better to be thought foolish or simple than to make a fool of yourself—to prove that you don’t actually have anything to say. Regret what you didn’t say, not the other way around.
#+end_quote

** Note 66 - Kaizen

#+begin_quote
The Japanese word for this is *kaizen*. Continual improvement. Always finding something to work on, to make a little progress on. Never being satisfied, always looking to grow.
#+end_quote

** Note 76
We dictate our time, here on Earth:

#+begin_quote
And let’s be clear, that doesn’t just mean hurrying along. Queen Elizabeth’s mother was once rushed along at a public event by an aide who claimed they were out of time. “*Time is not my dictator*,” the Queen Mother said as she stopped and shook hands with each person who had waited to see her. “*I dictate to time*.”

While time is ultimately the dictator of our presence here on this earth, we do dictate how we spend it. As long as we are aware of it, aware of its value and the importance of managing it well. As long as we are putting it to work for us, even as it is working against us in the mortal sense.
#+end_quote

** Note 83                                                 :quote:

#+begin_quote
“There is no question that the public will ultimately understand and he will be regarded as a far-seeing man who has attempted to protect the people of the US,” he said of Carter’s energy efforts. “It took about four hundred years for the Lord Jesus Christ to have his message accepted. Up to that time he would be considered a ‘failure.’ *As long as a man is trying as hard as he can to do what he thinks to be right, he is a success, regardless of the outcome*.
#+end_quote

** Note 12                                                 :quote:

Being a boss and being a leader:

#+begin_quote
Being the “boss” is a job. Being a “leader” is something you earn. You get elevated to that plane by your self-discipline. By moments of sacrifice like this, when you take the hit or the responsibility on behalf of someone else.
#+end_quote

** Note 13

#+begin_quote
The leader shows up first and leaves last. The leader works hardest. The leader puts others before themselves. The leader takes the hit.

Everything else is just semantics and titles.
#+end_quote
