:PROPERTIES:
:ID:       72f1933d-a216-4124-a9d7-abc983592411
:END:
#+created: 20201030094028952
#+finished_month: 10
#+finished_year: 2020
#+genres: Spirituality Religion
#+goodreads: https://www.goodreads.com/de/book/show/15015.Conversations_with_God
#+lang: de
#+modified: 20210518194234123
#+revision: 0
#+filetags: :spirituality:book:
#+title: Gespräche mit Gott Band 1
#+type: text/vnd.tiddlywiki
#+date: 2020-10-01

* Notizen
  - es kommt im Leben auf Freude, Wahrheit sowie Liebe an
  - etwas ist *richtig*, wenn wir damit auch einverstanden sind (bezogen auf die Frage ob Gottes Worte richtig seien)
  - Gott hat keine Form, die als Beweis dienen könnte, dass es Ihn gibt
    - keine Form und Gestalt würden _alle_ zufriedenstellen
  - das Gebet sollte *kein Bittgesuch* sondern ein *Dankgebet* sein
    - die Bitte führt dazu, dass der Mangel in der Realität auch "erschaffen" wird
    - die Realität lässt sich durch die Gedanken beeinflussen
      - Das tiefste Geheimnis ist, dass das Leben nicht ein Entdeckungsprozess sondern ein Schöpfungsprozess ist.
      - Vollführe zuerst die Tat, die der neue Gedanke deinem Willen nach beinhalten soll. Sprich dann die Worte, die der neue Gedanke deinem Willen nach beinhalten soll. Wiederhole dies so oft wie möglich und du trainierst deinen Geist, auf eine neue Weis zu denken.
    - *Dankbarkeit* ist wie Danken in Voraus; man schafft sich eine neue Realität
    - die Welt existiert so, weil es unsere Wahl ist
    - alle menschlichen Handlungen bestehen aus 2 Emotionen
      - Angst
      - [[#Liebe][Liebe]]
        - Denn es liegt in der Natur der Menschen, das, was sie am meisten wertschätzen, erst zu lieben, dann zu zerstören und dann wieder zu lieben.
      - Verlust der Liebe erzeugt Angst
        - Es kommt zur Verteidigung gegen den Verlust
        - es beeinflusst die Art wie wir Liebe _empfangen_ aber auch _geben_
  - Göttliche Polarität
    #+begin_quote
    Am Anfang war nur das, was ist /Ist/ und nichts anderes. Doch Alles-Was-Ist konnte sich nicht selbst erkennen - weil Alles-Was-Ist alles war, was da war und /nichts/ sonst. Und daher war Alles-Was-Ist ... /nicht/. Denn in Abwesenheit von etwas anderem ist Alles-Was-Ist /nicht/.
    #+end_quote
    - Gott ist Alles-Was-Ist und Alles-Was-Nicht-Ist
    - Genau aus dem Grund wurde die Angst erschaffen, denn Liebe alleine kann nicht existieren
    - auch deswegen müsse man erst erfahren was man /nicht/ ist, damit man /ist/
  - *Die Heilige Dreifaltigkeit*
    - wissend (Gott der Vater)
      - man kann nicht erfahren, was man nicht weiß
    - erfahrend (Gott der Sohn)
      - Verkörperung des Vaters und seines Wissens
      - das ist auch Ziel und Zweck der Seele
      - jede Seele folgt ihrem Weg
        #+begin_quote
        Eure Seele (Unterbewusstsein, Es, reiner Geist, Vergangenheit usw.) ist die Gesamtsumme jedes Gefühls, das ihr jemals hattet (erschaffen habt).
        #+end_quote
        - vergleichbar mit dem [[id:4eb41e5b-7ef3-41e0-86ea-bd072eda69ac][Ich bin dann mal weg - Meine Reise auf dem Jakobsweg]]
      - man kann nicht sein, was man nicht erfahren hat
    - seiend (Gott der Heilige Geist)
      - die Entkörperung dessen, was der Sohn erfahren hat
      - dieser Zustand (des Seienden) ist nur durch die Erinnerung an das Wissende und Erfahrende möglichg
  - *3 Gesetze statt 10 Gebote*
    - 1. Gesetz: /Ihr könnt sein, tun und haben, was ihr immer euch vorstellt/ (der Gedanke ist schöpferisch)
    - 2. Gesetz: /Ihr zieht an, was ihr fürchtet./ (Furch t zieht gleichgeartete Energie an)
    - 3. Gesetz: /Liebe ist alles, was es gibt./
  - Zum Thema Tod
    - in unserer Gesellschaft darf man den Wunsch nicht äußern, dass man sterben möchte
    - mit dem Tod ist der Weg der Seele auch zu Ende
    - manchmal weigert sich der Körper und strebt sich gegen die Entscheidung der Seele
  - *Religion*
    - Ihr habt sogar Religionen erschaffen, die euch lehren, dass ihr sündig auf die Welt kommt - dass ihr von Geburt an Sünder seid -, um euch von eurer eigenen Schlechtigkeit zu überzeugen.
    - wir werden gelehrt, dass wir sündig geboren wurden, sündig sterben werden und dass das Sündigen in unserer Natur liegt
    - die natürliche Intuition wird auch abgeschafft und die Religion lehrt uns, damit aufzuhören, auf unser /Selbst/ zu hören
      - Sie werden euch vom Teufel erzählen, vom Satan, von Dämonen und bösen Geistern, von der Hölle und Verdammnis und von allen Schrecknissen und Torturen, die ihnen einfallen, um euch zur Einsicht zu veranlassen, dass das, was ihr intuitiv fühlt und wisst, falsch ist; und dass der einzige Ort, an dem ihr irgendwelchen Trost finden könnt, der /ihres/ Gedankengebäudes ist, /ihrer/ Ideen, /ihrer/ Theologie, /ihrer/ Definitionen von richtig und falsch sowie /ihrer/ Konzeption von dem, was-du-bist.
    - Zum Thema Schuldgefühle
      #+begin_quote
      Was kannst du erwarten? Euch wird von frühesten Tagen an gesagt, dass ihr schlecht seid. Ihr akzeptiert, dass ihr in Sünde geboren seid. Schuldgefühle sind eine erlernte Reaktion. Euch sind Schuldgefühle wegen begangener Taten eingeredet worden, noch bevor ihr überhaupt in der Lage wart, irgendetwas zu tun. Euch ist beigebracht worden, dass ihr euch dafür schämen sollt, nicht ganz vollkommen auf die Welt gekommen zu sein.
      #+end_quote
  - *Beziehungen*
    - es geht darum die *eigene* Vollkommenheit mit dem Anderen zu teilen
      #+begin_quote
      Der Zweck einer Beziehung ist der, dass ihr entscheidet, welchen Teil von euch selbst ihr gerne sich zeigen lassen würdet, und nicht, welchen Teil des Anderen ihr einfangen und festhalten könnt.
      #+end_quote
    - Beziehungen scheitern sehr oft, weil wir uns zu sehr auf den Anderen konzentrieren
* Quotes
** Gespräche mit Gott Band 1 - Note 1                                          :quote:
#+begin_quote
Denn es liegt in der Natur der Menschen, das, was sie am meisten wertschätzen, erst zu lieben, dann zu zerstören und dann wieder zu lieben.
#+end_quote

** Gespräche mit Gott Band 1 - Note 2                                          :quote:
#+begin_quote
[...] seid ihr unfähig, sie (die Rettung) zu akzeptieren, weil die Vorstellung von einem Gott, der nicht gefürchtet werden muss, der nicht richtet und der keinen Grund zur Bestrafung hat, ganz einfach zu großartig ist, als dass ihr sie selbst in euere grandiosesten Ideen über das, was und wer Gott ist, integrieren könntet.
#+end_quote

** Gespräche mit Gott Band 1 - Note 3                                          :quote:
#+begin_quote
Das tiefste Geheimnis ist, dass das Leben nicht ein Entdeckungsprozess sondern ein Schöpfungsprozess ist.
#+end_quote

** Gespräche mit Gott Band 1 - Note 4                                          :quote:
#+begin_quote
Am Anfang war nur das, was ist Ist und nichts anderes. Doch Alles-Was-Ist konnte sich nicht selbst erkennen - weil Alles-Was-Ist alles war, was da war und nichts sonst. Und daher war Alles-Was-Ist ... nicht. Denn in Abwesenheit von etwas anderem ist Alles-Was-Ist nicht.
#+end_quote

** Gespräche mit Gott Band 1 - Note 5                                          :quote:
#+begin_quote
Eure Aufgabe auf Erden ist es deshalb nicht zu lernen (weil ihr bereits wisst), sondern euch zu erinnern/wieder einzugliedern/zusammenfügen, wer-ihr-seid, und dies nicht nur in Bezug auf euch, sondern auch in Bezug auf alle Anderen.
#+end_quote

** Gespräche mit Gott Band 1 - Note 6                                          :quote:
#+begin_quote
Eure Seele (Unterbewusstsein, Es, reiner Geist, Vergangenheit usw.) ist die Gesamtsumme jedes Gefühls, das ihr jemals hattet (erschaffen habt).
#+end_quote

** Gespräche mit Gott Band 1 - Note 7                                          :quote:
#+begin_quote
Also willst du, dass dein Leben abhebt? Dann fang sofort an, es dir vorzustellen, wie es deinem Wunsch nach sein soll - und begib dich in diese Projektion hinein. Überprüfe jede Gedanken, jedes Wort und jede Handlung, die sich nicht im Einklang damit befinden, und entferne dich von diesen.
#+end_quote

** Gespräche mit Gott Band 1 - Note 8                                          :quote:
#+begin_quote
Ihr habt sogar Religionen erschaffen, die euch lehren, dass ihr sündig auf die Welt kommt - dass ihr von Geburt an Sünder seid -, um euch von eurer eigenen Schlechtigkeit zu überzeugen.
#+end_quote

** Gespräche mit Gott Band 1 - Note 9                                          :quote:
#+begin_quote
Was kannst du erwarten? Euch wird von frühesten Tagen an gesagt, dass ihr schlecht seid. Ihr akzeptiert, dass ihr in Sünde geboren seid. Schuldgefühle sind eine erlernte Reaktion. Euch sind Schuldgefühle wegen begangener Taten eingeredet worden, noch bevor ihr überhaupt in der Lage wart, irgendetwas zu tun. Euch ist beigebracht worden, dass ihr euch dafür schämen sollt, nicht ganz vollkommen auf die Welt gekommen zu sein.
#+end_quote

** Gespräche mit Gott Band 1 - Note 10                                         :quote:
#+begin_quote
Der Zweck einer Beziehung ist der, dass ihr entscheidet, welchen Teil von euch selbst ihr gerne sich zeigen lassen würdet, und nicht, welchen Teil des Anderen ihr einfangen und festhalten könnt.
#+end_quote

** Gespräche mit Gott Band 1 - Note 11                                         :quote:
#+begin_quote
Sie werden euch vom Teufel erzählen, vom Satan, von Dämonen und bösen Geistern, von der Hölle und Verdammnis und von allen Schrecknissen und Torturen, die ihnen einfallen, um euch zur Einsicht zu veranlassen, dass das, was ihr intuitiv fühlt und wisst, falsch ist; und dass der einzige Ort, an dem ihr irgendwelchen Trost finden könnt, der ihres Gedankengebäudes ist, ihrer Ideen, ihrer Theologie, ihrer Definitionen von richtig und falsch sowie ihrer Konzeption von dem, was-du-bist.
#+end_quote

** Gespräche mit Gott Band 1 - Note 12                                         :quote:
#+begin_quote
Vollführe zuerst die Tat, die der neue Gedanke deinem Willen nach beinhalten soll. Sprich dann die Worte, die der neue Gedanke deinem Willen nach beinhalten soll. Wiederhole dies so oft wie möglich und du trainierst deinen Geist, auf eine neue Weis zu denken.
#+end_quote
