:PROPERTIES:
:ID:       4eb41e5b-7ef3-41e0-86ea-bd072eda69ac
:END:
#+filetags: book
#+date: 2011-10-01
#+title: Ich bin dann mal weg - Meine Reise auf dem Jakobsweg

* Ich bin dann mal weg - Meine Reise auf dem Jakobsweg
:PROPERTIES:
:FINISHED: 2011-10
:END:
* Description
#+begin_quote
Es ist ein sonniger Junimorgen, als Hape Kerkeling, bekennende couch potato, endgültig seinen inneren Schweinehund besiegt und in St.-Jean-Pied-de-Port aufbricht. Sechs Wochen liegen vor ihm, allein mit sich und seinem elf Kilo schweren Rucksack: über die schneebedeckten Gipfel der Pyrenäen, durch das Baskenland, Navarra und Rioja bis nach Galicien zum Grab des heiligen Jakob, seit über tausend Jahren Ziel für Gläubige aus der ganzen Welt. Mit Charme, Witz und Blick für das Besondere erschließt Kerkeling sich die fremden Regionen, lernt er die Einheimischen ebenso wie moderne Pilger und ihre Rituale kennen. Er erlebt Einsamkeit und Stille, Erschöpfung und Zweifel, aber auch Hilfsbereitschaft, Freundschaften und Belohnungen – und eine ganz eigene Nähe zu Gott. In seinem Buch über den Wert des Wanderns zeigt der beliebte Spaßmacher, wie er auch noch ist: abenteuerlustig, weltoffen, meditativ.


(Quelle: https://www.buecher.de/shop/nordspanien/ich-bin-dann-mal-weg/kerkeling-hape/products_products/detail/prod_id/20754834/)
#+end_quote

* Quotes
** Ich bin dann mal weg - Meine Reise auf dem Jakobsweg - Note 1               :quote:done:
#+begin_quote
Gibt es Gott? Oder Jahwe, Shiva, Ganesha, Brahma, Zeus, Ram, Vishnu, Wotan, Manitu, Bud dha, Allah, Krishna, Jehowa? Da ließen sich noch viele Namen nennen...
#+end_quote

** Ich bin dann mal weg - Meine Reise auf dem Jakobsweg - Note 2               :quote:done:
#+begin_quote
Eine Freundin hat mir mal gesagt: »Du musst nicht zweifeln! Du musst dich im Leben einfach auf Gott verlassen! Irgendwie löst er alle Probleme auf seine unglaubliche Weise!«
#+end_quote

** Ich bin dann mal weg - Meine Reise auf dem Jakobsweg - Note 4               :quote:done:
#+begin_quote
Je weniger wir uns über die ständigen symbolischen Geburten in unserem Leben freuen und an ihnen hängen, desto leichter können wir vielleicht auch die symbolischen Tode akzeptieren? Ich muss mich jedenfalls mal intensiver mit meinem Schatten auseinander setzen!
#+end_quote

** Ich bin dann mal weg - Meine Reise auf dem Jakobsweg - Note 5               :quote:done:
#+begin_quote
Gott ist der Film und die Kirche ist das Kino, in dem der Film läuft. Ich hoffe, wir können uns den Film irgendwann in bester 3-D- und Stereo-Qualität unverfälscht und mal in voller Länge angucken! Und vielleicht spielen wir dann ja sogar mit!
#+end_quote

** Ich bin dann mal weg - Meine Reise auf dem Jakobsweg - Note 7               :quote:done:
#+begin_quote
Wenn ich mich nicht in Wort und Gedanken ausdrücke, beeindruckt mich auch nichts! Weder Wind noch Regen. Wenn man seinen Ausdruck im Denken und Handeln, Sprechen, Singen, Tanzen nicht gelegentlich pausieren lässt, verselbstständigt er sich und das Ergebnis ist die Erzeugung ständigen Drucks.
#+end_quote

** Ich bin dann mal weg - Meine Reise auf dem Jakobsweg - Note 8               :quote:done:
#+begin_quote
Jeder eigene Ausdruck führt zu einem Eindruck bei anderen und der erzeugt in ihnen neuen Ausdruck, der wiederum für einen selbst beeindruckend ist.
#+end_quote

** Ich bin dann mal weg - Meine Reise auf dem Jakobsweg - Note 10              :quote:done:
#+begin_quote
»Drop the thought!« Lass den Gedanken fallen! »Sobald dich etwas im Job oder sonst wo plagt, lass den Gedanken einfach fallen. Kaue nicht auf ihm herum, denn nur so erlöst du ihn!«
#+end_quote

** Ich bin dann mal weg - Meine Reise auf dem Jakobsweg - Note 11              :quote:done:
#+begin_quote
Jedes Leben könnte wie eine Art Hindernisparcours funktionieren. Der Reiter ist die Seele, das Pferd der Körper und der Parcours das Leben.
#+end_quote

** Ich bin dann mal weg - Meine Reise auf dem Jakobsweg - Note 12              :quote:done:
#+begin_quote
Jeder Mensch sucht nach Halt. Dabei liegt der einzige Halt im Loslassen.
#+end_quote

** Ich bin dann mal weg - Meine Reise auf dem Jakobsweg - Note 13              :quote:done:
#+begin_quote
Hab Vertrauen in den, der dich wirft, denn er liebt dich und wird vollkommen unerwartet auch der Fänger sein.
#+end_quote
