:PROPERTIES:
:ID:       7ebbc17a-9077-4b85-afcb-31f01678f79a
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :author '("Sir Ken Robinson")
:END:
#+title: Imagine if...
#+filetags: :society:book:
#+date: 2023-02-14

by Sir Ken Robinson

Goodreads: https://www.goodreads.com/en/book/show/58536094

* Notes
** Note 1
#+begin_quote
- Imagine if we used our incredible capacities to create a world in which every person had a deep understanding of their own unique talents.
- Imagine if we built systems that lifted us up instead of keeping us down.
- Imagine if we embraced our diversities rather than running from them.

We have come to a point in our history in which continuing to do what we have
always done is no longer an option. We must do better. It begins, as it always
does, with each of us taking a stand.
#+end_quote
** Note 2 - Creativity
Definition:

#+begin_quote
Creativity—the *ability to generate new ideas and to apply them in practice*
#+end_quote

#+begin_quote
Creativity is a process, which means it includes a relationship between two main
aspects that bounce off each other:

- *generating ideas* and
- *evaluating ideas*
#+end_quote

#+begin_quote
Creativity involves [[id:ec38eea2-ed6a-4467-9261-f1f96791beb3][originality]]
#+end_quote

#+begin_quote
Creativity involves making *judgments of value*. What is considered to be of value
depends on the nature and the purpose of the work — if something is useful,
beautiful, valid, or sustainable
#+end_quote


#+begin_quote
Creativity is call and response: *one idea can catalyze a multitude more in the
minds of other people*
#+end_quote

#+begin_quote
Creativity, like the brain or muscle, *changes with use. If we neglect our
creative capacities, they lie dormant*. If we use them properly, they grow and
develop.
#+end_quote

** Note 3
#+begin_quote
Every generation lives through its own unique set of circumstances, and in doing
so leaves indelible marks for future generations to make sense of. The *unique
set of circumstances* we find ourselves navigating are in part born from the
crosscurrents of *three global forces*:
- demography
- technology
- ideology
#+end_quote
** Note 4
Many of man-kind problems are spiritual:

#+begin_quote
Despite our unprecedented material comforts, life in the twenty-first century is
proving too much to bear for growing numbers of people. *Many of the problems we
are experiencing are spiritual. I mean that in the sense of being in good
spirits or poor spirits: of feeling purposeful and fulfilled, or nihilistic and
despairing*. While the majority of people are materially better off than ever
before, a large portion are caught in a global epidemic of depression and
anxiety.
#+end_quote
** Note 5 - Save our own existence
#+begin_quote
It is often said that we have to “save the planet.” I’m not so sure that’s
true—the planet has a long time left to run until it crashes into the Sun. What
we mean when we talk about saving the planet is that *we have to save our own
existence on it*. That much is certain. If we continue to ravage the Earth at the
current rate, we face no future as a species. Extinctions are a very real part
of nature, but *at this rate humans will join an elite and unfortunate club of
species directly responsible for their own extinction*.
#+end_quote
** Note 6 - IQ
#+begin_quote
in 1912 German psychologist William Stern proposed implementing a formal
calculation of mental age divided by chronological age multiplied by 100 to
determine a specific IQ figure.
#+end_quote

#+begin_quote
Ask most people about intelligence and the conversation usually turns to
academic ability and IQ (Intelligence Quotient). “Academic” is often used
interchangeably with “intelligent,” but while academic ability is an important
example of intelligence, it is far from being the whole of it.

*Academic work* is a mode of analysis that can be applied to anything. It refers
to *intellectual work* that is mainly theoretical or scholarly, rather than
practical or applied. Working academically generally *focuses on three areas*:
- *propositional knowledge*
  — facts about what is the case, for example, “George Washington was president of the United States of America from 1789 to 1797”;
- *critical analysis*
  — the impact of Washington’s presidency and the nature of his leadership;
- *desk studies*
  — which mainly involve reading and writing, processing and presenting facts, and critical analysis.
#+end_quote
** Note 7 - IQ and Eugenics
#+begin_quote
The concept of IQ was eventually picked up by members of the *eugenics* movement,
who used it as *grounds for their belief in selective breeding and population
control*. Their argument was that the IQ test could be used to identify people
with low intelligence and stop them from reproducing. It caught on—some states
in the USA legalized the sterilization of people deemed to have low
intelligence, and *eugenics was a key tactic of the Nazis’ Final Solution*.
#+end_quote

Some facts about eugenics:
- The eugenics movement aimed to improve the genetic quality of the human population through controlled breeding, sterilization or exclusion of certain groups from society.
- This movement was popular in the late 19th and early 20th centuries.
- Eugenics was associated with racist and xenophobic beliefs.
- The movement impacted policies related to immigration, marriage, and reproductive rights in several countries.
- The Nazi regime in World War II utilized eugenics to further their own agenda.
- Eugenics lost popularity after the end of the Nazi regime.

** Note 8 - Differences between learning, school
#+begin_quote
There are a few terms that are often confused or used
interchangeably:

- learning
- education
- training
- school

but there are important differences between them.

- *Learning* is the process of acquiring new skills and understanding.
- *Education* is an organized system of learning.
- *Training* is a type of education that is focused on learning specific skills
- A *school* is a community of learners: a group that comes together to learn with and from each other.
#+end_quote
** Note 9 - Role of School
#+begin_quote
There should be three *cultural priorities for schools*:
- to help students *understand* their *own cultures*
- to understand *other cultures*
- to promote a *sense of cultural tolerance and coexistence*.
#+end_quote
** Note 10 - Separation of areas/subjects
#+begin_quote
*The conventional curriculum is based on a collection of separate subjects*. These
are prioritized according to beliefs around the limited understanding of
intelligence we discussed in the previous chapter, as well as what is deemed to
be important later in life.

The idea of “subjects” suggests that each subject, whether mathematics, science,
art, or language, stands completely separate from all the other subjects. This
is problematic. *Mathematics, for example, is not defined only by propositional
knowledge; it is a combination of types of knowledge, including concepts,
processes, and methods as well as propositional knowledge*.

This is also true of science, art, and languages, and of all other subjects. It
is therefore much more useful to focus on the concept of disciplines rather than
subjects.
#+end_quote
** Note 11 - Traditional schooling
Traditional methods of formal education compared to an industrial factory:
- /Children/ are *manufactured* in a linear process along a conveyor belt
- /Teachers/ are like *factory workers*
- /Quality control/ checks along the way
- Process is *routine*, predefined, and regulated


Mixed groups of children learning together:

#+begin_quote
In traditional schools, children are taught in specific age groups — all of the
seven-year-olds together in one group, separate from all of the nine-year-olds.
From an administrative point of view, this makes sense. It also makes sense from
the perspective of industrial priorities.

However, when it comes to *what and how children actually learn, segregation by
age makes little sense at all*. *When children of different ages learn together,
they can be grouped by their stage of mastery rather than their chronological
age*. The younger students can benefit from the relative sophistication of the
older ones, who reinforce their own learning by helping the younger ones. In
bringing a variety of ages together, the experience, knowledge, and ability of
each is enhanced. It also provides opportunities for children to nurture each
other, developing empathy, responsibility, and patience.
#+end_quote

#+begin_quote
Despite the astronomical changes in circumstances between the Industrial
Revolution and the twenty-first century, formal systems of education by and
large remain structurally the same.

*Students and teachers spend huge amounts of their time in conditions that have
been designed for the mass production of a standardized product, the student,
that by design focuses on output and yield*.

While industrial farms prioritize quantity, size, and cost over quality, health,
and natural ecosystems, we prioritize test data, attendance, and college
admission over well-being, creativity, and learning. *While industrial farms pump
crops and livestock with vast amounts of antibiotics, we prescribe
mood-stabilizing and attention-enhancing drugs to children to compensate for the
very real levels of anxiety, stress, and disengagement they are experiencing*.
#+end_quote

#+CAPTION: Traditional schooling vs. what really matters
#+LABEL: tbl:tradschooling
| Industrial priorities | What really matters |
|-----------------------+---------------------|
| quantity              | quality             |
| size                  | health              |
| cost                  | natural ecosystems  |
| test data             | well-being          |
| attendance            | creativity          |
| college admission     | learning            |


How schedule is disrupting children's attention:

#+begin_quote
The *purpose of the schedule* is to facilitate learning. Rather than rotating
teachers and students through the day from room to room and subject to subject,
the schedule should be sensitive to the needs and requirements of each activity.

*If a business required that its entire workforce stop what it was doing every
forty minutes to move to a different room and do something else entirely, the
business would rapidly grind to a halt*.

When you think of it in those terms, it seems ridiculous that the majority of
schools put their students and teachers through this bizarre routine. Not only
is it a strange concept to expect human beings to stop what they are doing and
physically move rooms at the sound of a bell, it is also counterintuitive for
learning.
#+end_quote
** Note 12 - Playing
#+begin_quote
Play is not only a fundamental aspect of learning, but also a child’s natural
expression of it and a critical aspect of developing curiosity and imagination.
In the case of play, the *most effective action a school can take is to stand
aside and let it happen. Children do not need lessons in how to play, nor do
they need to be overly surveilled or scheduled—they simply require the space and
freedom to do what they naturally do best*.
#+end_quote
** 8 Core competencies
#+begin_quote
The concept of disciplines brings us to a better starting point when planning
the curriculum, which is to ask what students should know and be able to do as a
result of their education.

The four purposes above suggest eight core competencies that, if properly
integrated into education, will equip students who leave school to engage in the
personal, cultural, economic, and social challenges they will inevitably face in
their lives. These competencies are curiosity, creativity, criticism,
communication, collaboration, compassion, composure, and citizenship
#+end_quote
- Communication

  The ability to express thoughts and feelings clearly and
  confidently in a range of media and forms
- Criticism

  The ability to analyze information and ideas and to form reasoned
  arguments and judgments
- Collaboration

  The ability to work constructively with others

  Humans are social creatures:

  #+begin_quote
  The human adventure can only be carried forward through complex forms of
  collaboration. Without the ability to work with others we would stand no chance
  against the challenges we collectively face. Fortunately, human beings are
  social creatures: we live and learn in the company of others. This is true in
  most situations, but seldom cultivated in school environments. Too often, young
  people learn in groups but not as groups.
  #+end_quote

- Compassion

  The ability to empathize with others and to act accordingly
- Composure

  The ability to connect with the inner life of feeling and develop a
  sense of personal harmony and balance
- Citizenship

  The ability to engage constructively with society and to participate
  in the processes that sustain it

** Note 13
Again and again we don't have that much time on this planet (see [[id:834efb26-9f0d-4788-a708-20a4202c0da2][4 Thousand Weeks - Time Management for Mortals]]):

#+begin_quote
In Western cultures we avoid death. Not the act itself, but acknowledging
it, talking about it, and processing what it really means. As a result, too many
people live as though it will never happen to them or the people they love. They
endure their lives, get through each week, and wait for the weekend. As life
goes on they increasingly feel they have lost their chance to be happy and
fulfilled.
#+end_quote


** Note 14 - Separation between body and mind

#+begin_quote
*The dominant Western worldview is not based on seeing synergies and connections,
but on making distinctions and seeing differences*. This *creates sharp
distinctions between the mind and the body and between human beings and the rest
of nature*. This may be why there is such a general lack of understanding about
how the food we consume directly affects how our bodies work, and that the mass
production of the goods we demand directly affects the health of the planet.
page
#+end_quote

** Note 15
We're the problem:

#+begin_quote
The crises in the worlds of nature and human resources are connected. Jonas
Salk, the scientist who developed the Salk polio vaccine, reportedly made the
observation that *if all the insects were to disappear from the earth, within
fifty years all other forms of life would end. But if all human beings were to
disappear from the earth, within fifty years all other forms of life would
flourish.* In other words, we have now become the problem.
#+end_quote

** Note 16

#+begin_quote
As David Attenborough observed: *We have come as far as we have because we are
the cleverest creatures to have ever lived on Earth. But if we are to continue
to exist, we will require more than intelligence. We will require wisdom*.
#+end_quote

** Noten 17

#+begin_quote
So, if revolutions are not government-led initiatives, how do they begin? One
insight, attributed to *Benjamin Franklin*, is that *there are three sorts of
people in the world: those who are immovable, those who are movable, and those
who move*.
#+end_quote
