:PROPERTIES:
:ID:       170C9918-4149-4CA2-8CE2-A9BE767480D6
:END:
#+title: Jäger, Hirten, Kritiker
#+filetags: :politics:philosophy:book:
#+date: 2025-01-22

👉 [[https://www.goodreads.com/book/show/39920242-j-ger-hirten-kritiker]]

* Der erste Kontakt

Über Marx und Engels Vision des *Kommunismus*
#+begin_quote
Berühmter noch ist das Urbild, das Karl Marx und Friedrich Engels entwarfen. Besoffen von
ihren Ideen, ihrer noch jungen Freundschaft und reichlich gutem Wein definieren sie 1845
in ihrem Brüsseler Exil das erste Mal, was » *Kommunismus* sein soll: *eine Gesellschaft,
die es jedem ermögliche, heute dies, morgen jenes zu tun, morgens zu jagen, nach-mittags
zu fischen, abends Viehzucht zu treiben, nach dem Essen zu kritisieren, wie ich gerade
Lust habe, ohne je Jäger, Fischer, Hirt oder Kritiker zu werden. Die klassenlose
Gesellschaft, träumen die beiden jungen Männer, werde den totalen Menschen schaffen. Und
aus gesellschaftlicher Arbeit wird freie Tätigkeit*. (S.8)
#+end_quote

* DIE REVOLUTION
** Das Ende der Leistungsgesellschaft, wie wir sie kannten

Entwicklung zum *Prosumenten*
#+begin_quote
Was früher Ausbildungsberufe waren, erledigen in Zukunft Roboter. Und vieles, was ehedem
Fachkräfte machten, erledigen die Kunden an ihren Flachbildschirmen selbst. Die
Entwicklung zum Prosumenten, zum produzierenden Konsumenten, ist älter als die
Digitalisierung. Man erinnere sich, wie in Deutschland seit den Sechzigerjahren
Supermärkte den Einzelhandel mit Lebensmitteln ersetzten. Der Discounter war nicht nur
billiger, weil er größer war, sondern auch, weil Kunden sich nun selbst bedienten und
damit Personal eingespart wurde. Das Gleiche gilt für den Kaffee- wie den
Fahrkartenautomaten in den Achtziger- und Neunzigerjahren und für die Selbstbaukünste des
IKEA-Käufers. *Das Prinzip des arbeitenden Kunden im digitalen Zeitalter ist nichts als
die konsequente Fortführung dieser Selbstbedienung: Reisen buchen, am Flughafen
einchecken, Kleider und Bücher bestellen, Uberweisungen ausführen und so weiter*. (S.25)
#+end_quote

** Wir dekorieren auf der Titanic die Liegestühle um

Über Individualität im digitalen Zeitalter
#+begin_quote
Fine Wirtschaftsform, die man aufgrund ihrer Erfolge verständlicherweise bejaht, paart
sich mit einem Kultur- und Werteverlust, den man ebenso nachvollziehbar betrauert. *Was
soll Individualität - also wörtlich: Unteilbarkeit sein, wenn der Mensch in Millionen
Daten zerlegt und als so gewonnenes Profil eingetütet und an die Meistbietenden verkauft
wird, um ihn zu manipulieren, käufliche Dinge zu begehren?* *Spürbarer und sichtbarer noch
sind der Lärm, die Geschwindigkeit, die Dauerwerbung und der Aufmerksamkeitsraub, die in
die sozialen Räume eindringen, ins gemeinsame Essen mit Kindern am Tisch, die
Verbundenheit auflösen und Geborgenheit, Stille, Zurückgezogenheit und das Bei-sich-Sein-
zerschneiden.* (S.38)
#+end_quote

** Der Palo-Alto-Kapitalismus regiert die Welt

Über technische Abhängigkeit
#+begin_quote
Die Menschen haben verlernt Auto zu fahren, Karten zu lesen, sich alleine in der Welt
zurechtzufinden. Sie müssen sich nichts mehr merken, weil elektronische Geräte uns an
alles erinnern, und speichern immer weniger Wissen über die Welt, weil Geräte dies für uns
übernehmen. *Die meisten Menschen sind wieder zu Kleinkindern geworden, in ihrem Wissen
über die Welt, ihrer Abhängigkeit von (technischer) Fürsorge und ihrem mangelnden
Lebensmut, ohne Hilfsgerät (oder bald einem Chip im Kopf) das Haus zu verlassen.
Kommunizieren tun sie durch steinzeitliche Piktogramme, und infantil teilen sie die Welt
in Likes und Dislikes.* (S.73)
#+end_quote


* DIE UTOPIE
** Grundsätzliche These zur Arbeit
#+begin_quote
*Zu arbeiten, etwas zu gestalten, sich selbst zu verwirklichen liegt in der Natur des
Menschen. Von neun bis fünf in einem Büro zu sitzen und dafür Lohn zu bekommen nicht!*
(S.114)
#+end_quote

** Die Maschinen arbeiten – die Arbeiter singen
Über den Leistungsmythos:
- Das Konzept der Leistungsgesellschaft ist eine Fiktion, die jedoch für viele Menschen
  motivierend wirkt.
- Sie erzeugt ein gesellschaftliches Klima und eine Haltung durch ihre normative Kraft.
- Die Idee einer Meritokratie, einer Herrschaft der Verdienste, ist unrealistisch, da
  niemand alleine Urheber seiner Leistung ist.
- Es zählen auch Faktoren wie Herkunft, Beziehungen, Protektion und Glück.
- Eine echte Leistungsgesellschaft wäre nicht wünschenswert, sondern es sollte vielmehr
  ein realistisches Verständnis von Leistung und Erfolg entwickelt werden.

#+begin_quote
Dosch gerade für viele Menschen in der Bundesrepublik Deutschland ist der Leistungsmythos
fur ihr Selbstbewust lem entscheidend. *Wer als Kind eines Arbeiters, Bauern oder
Handwerkers in der zweiten Hälfte des 20. Jahrhunderts durch Fleiß, Beharrlichkeit und
Studium Ingenieur, Elektrotechiker, Kleinunternehmer, Manager oder Verbandspräsident
wurde, sieht sich selbst als lebenden Beweis fur das Funknonieren der
Leistungsgesellschaft.*

Und doch, so scheint es, war die Zeit des kollektiven Aufstiegs in der alten
Bundesrepublik eher ein Ausnahmefenster als die Regel. *Dass die Karriere nur etwas mit
innerer Einstellung und Moral zu tun haben soll, ist ein lieb gewonnenes Märchen, das dem
eige nen Werdegang besonderen Glanz gibt.* Tatsächlich aber war das kulturelle Umfeld
damals ein anderes als heute, und die Aufstiegschancen und Anreize waren besser. Und wenn
heute in Deutschland pro Jahr 400 Milliarden Euro schlichtweg vererbt werden, ist der
Begriff Leistungsgesellschaft- kaum mehr als ein Euphemismus."

Die Leistungsgesellschaft ist eine Fiktion; allerdings für jeden, den sie motiviert, eine
nützliche. Sie erzeugt ein gesellschaftliches Klima und eine Haltung und sei es auch
einzig durch die normative Kraft des Fiktiven. Man sollte die Leistungsgesellschaft
deshalb nicht völlig kleinreden. Aber über höhen sollte man sie auch nicht. Denn man
stelle sich nur einmal vor, wir unterzögen das hehre Prinzip der Leistung einem echten
Belastungstest. Wie viel Leistungsgerechtigkeit verträgt unsere Gesellschaft? Der
englische *Soziologe Michael Dunlop Young erfand 1958 augenzwinkernd die Idee einer
Meritokratie, einer Herrschaft der Verdienste*." *Jeder Mensch sollte aufgrund seiner
tatsächlichen Leistung beurteilt und entlohnt werden. Alle anderen Kriterien - Herkunft,
Beziehun-gen, Protektion und Glück gehörten eliminiert.* Natürlich ist das völlig
*unrealistisch. Was ich leiste, ist ja nicht nur eine Frage meiner Verdienste, sondern
ebenso ein Verdienst anderer.* Meiner Eltern zum Beispiel, die mir Talente vererbt ha ben
und mich durch ihre Erziehung prägten. Meiner Lehrer vielleicht noch und meines sozialen
Umfelds. Keiner ist seiner Leistung alleiniger Urheber. Aber trotzdem, noch einmal fragt,
wäre eine echte Leistungsgesellschaft wünschenswert? (S.115)
#+end_quote

** Frei leben
Über das bedingungslose *Grundeinkommen*
#+begin_quote
Wirbt man in Deutschland für das BGE, das bedingungslose Grundeinkommen, das jeder Bürger
unabhängig von seiner Bedürftigkeit erhalten soll, kommt *als Erstes reflexartig die Frage*:
*Wer soll das bezahlen?* Die Frage - so automatisiert, dass augenscheinlich keiner danach
fragt, warum man sie sogleich stellt - ist befremdlich. *Warum sollte sich das BGE nicht
finanzieren lassen? Schließlich leben wir im reichsten Deutschland, das es je gab. Und die
Produktivität steigt durch die Digitalisierung noch einmal rasant an. Computer und Roboter
kosten keine Sozialabgaben, beziehen keine Rente, kein Urlaubs- oder Müttergeld. Sie
schlafen nicht, sondern arbeiten ohne Mühen Tag und Nacht.* (S.129)
#+end_quote


Über die negative Einkommenssteuer
- Das Ulmer Transfergrenzenmodell (TGM) und das Solidarische Bürgergeld sind Varianten
  einer negativen Einkommensteuer in Deutschland.
- Die meisten Modelle setzen das Grundeinkommen auf um die 1000 Euro an, auch bei
  Hartz-IV-Empfängern eine Verschlechterung der Bezüge vor.
- Das Ziel ist ein Abbau der Bürokratie und finanziell bessere Anreize für den Erwerb von
  Einkommen.
- Die Idee der negativen Einkommenssteuer stammt aus den Vierzigerjahren und wurde von
  Milton Friedman in den Sechzigern populär gemacht.
- Das Konzept wird als abstrus betrachtet, wenn die Erwerbsarbeit in Zukunft für Millionen
  Menschen verloren gehen wird.
- Die alte Idee der negativen Einkommenssteuer enthält keine Lösung für diese neue
  Situation.

#+begin_quote
Ein ebenfalls beliebtes Konzept ist die negative Einkom-menssteuer, zu der in Deutschland
mehrere Varianten disku-nert werden, etwa das Ulmer Transfergrenzenmodell (TGM) oder das
Solidarische Bürgergeld, das der ehemalige Minister-präsident von Thüringen, Dieter
Althaus, ins Gespräch brach-te. Das Grundeinkommen soll über Einkommensteuern finan-ziert
werden, je nach Modell unter Miteinbezug von Zinsen, Mieteinnahmen und Dividenden. Die
meisten dieser Modelle setzen das Grundeinkommen so gering an wie Götz Werner, also um die
1000 Euro. Auch sie nehmen eine Verschlechte-rung der Bezüge für Hartz-IV-Empfänger in
Kauf. Dafür stel-len sie finanziell bessere Anreize etwas hinzuzuverdienen in Aussicht und
versprechen einen massiven Abbau der Büro-kratie. Demjenigen, der dem BGE grundsätzlich
kritisch gegen-übersteht, erscheint die negative Einkommensteuer als die am ehesten
annehmbare Lösung. Doch genau dieser Reiz ise il Krux. Die Idee stammt aus den
Vierzigerjahren und bune den Sechzigern in Milton Friedman ihren prominentesten Ver
treter. Angesichts von Millionen Menschen, die in Zukunft den hoch entwickelten
Industrieländern ihre Erwerbsarbeit verlieren werden, erscheint sie hingegen regelrecht
abstrus; ein Versuch, einen Häuserbrand mit der Gießkanne zu löscient Wenn immer weniger
Menschen einer Erwerbsarbeit nachge hen, werden die Erwerbstätigen mit ihrer Arbeit den
Sozial staat nicht mehr finanzieren können. Und auch der für viele BGE-Skeptiker reizvolle
Gedanke, Grundeinkommenbezie hern ohne Erwerbsarbeit bessere Anreize zu geben, sich eine
zu suchen, ist unter den Vorzeichen des digital massiv verklei nerten Arbeitsmarkts eine
abständige Vorstellung. Erst wenn man verstanden hat, dass das Zeitalter flächendeckender
Er werbsarbeit mit sehr großer Wahrscheinlichkeit zu Ende geht, versteht man die Lage. Für
diese neue Situation aber enthält die alte Idee der negativen Einkommenssteuer keine
Lösung. (S.133)
#+end_quote


Über die Finanztransaktionssteuer
- Die Finanztransaktionssteuer soll die Spekulation auf den Finanzmärkten reduzieren und
  Investitionen in die Realwirtschaft fördern.
- Der Vorteil überwiegt bei Weitem den Nachteil.
- Eine solche Steuer würde die Finanzmärkte stabiler machen und die Zockerei im
  Börsencasino verringern.
- Die einzige erhebliche Einwendung ist die Furcht, dass die Finanzspekulanten sich immer
  noch Möglichkeiten zum Umgehen der Steuer finden würden.
- Einrechnen müssten auch die mutmaßlichen Folgen für die Spekulation.
- Die Mikrosteur auf Finanztransaktionen könnte das Grundeinkommen in den reichen Ländern
  sicher finanzieren.

#+begin_quote
Die Finanztransaktionssteuer wird vor allem deshalb disku-bert, um zu verhindern, dass
Spekulationen sich mehr lohnen als Investitionen in die Realwirtschaft. Angesichts des
enor-men Volumens heutiger Finanzspekulationen eine völlig rea-listische Befürchtung.
Zudem sollte eine solche Steuer für John Maynard Keynes in den Dreißigerjahren
Finanzblasen und Börsencrashs verhindern. Kein Wunder, dass angesichts der globalen
Finanzmarktkrise die EU-Kommission die Idee einer Finanztransaktionssteuer 2011 aufgriff -
unter heftigem Wi-derstand Großbritanniens, das wie kein anderes EU-Land vom Finanzsektor
lebt. Als der Entwurf 2013 fertig war, war nur noch von elf EU-Ländern die Rede. Doch je
länger die Krise zurücklag, umso weniger wurde das Konzept weiterverfolgt. Die Lobbys der
Finanzindustrie gewannen wieder die Ober-hand und fluteten die Wirtschaftsseiten der
großen Zeitungen und Zeitschriften mit fadenscheinigen Argumenten. Was auch immer an
Einwänden über den volkswirtschaftlichen Nach-teil vorgebracht wurde, der Vorteil
überwiegt sie bei Weitem. Eine Finanztransaktionssteuer macht die Finanzmärkte stabi-ler
und verringert die Zockerei im Börsencasino, Verlierer sind nur die Extremzocker und
niemand sonst.

Der einzige Einwand von Gewicht ist nicht volkswirtscha licher Natur. Es ist die
Befurchtung, den Finanzspekulantes blieben jederzeit hinreichend Möglichkeiten, die
Steuerz gehen. Einen solchen Einwand zum Grund zu nehmen wate als wenn man auf die
Bekämpfung von Verbrechen verze te, weil sie gleichwohl ständig wieder vorkommen. Klar je
mehr Länder sich an einer Finanztransaktionssteuer beteil gen, umso besser. Zwei
Überlegungen geben hier Grund zum Optimismus. Zum einen geschieht kein gesellschaftlicher
Form schritt dadurch, dass sich achtundzwanzig Regierungschefs darauf einigen. Weder wurde
so die Sklaverei abgeschafft noch die Gleichstellung von Frauen durchgeboxt, noch wird so
eine Finanztransaktionssteuer in der EU durchgesetzt. Al-ler gesellschaftliche Fortschritt
geht von einzelnen Staaten aus, die dann einen Dominoeffekt in anderen Ländern auslösen.
Betrachtet man die Finanztransaktionssteuer in dem Licht, damit zukünftig ein
Grundeinkommen an die Bürger zu zah len, so sitzen viele vorher zerstrittene EU-Länder
plötzlich im selben Boot. Denn nun geht es nicht mehr um mehr oder we niger Rücksicht
gegenüber der Finanzindustrie - es geht um ein Riesenproblem, das sich in Frankreich,
Deutschland, Polen und Italien gleichermaßen stellt: Wie verhindere ich den
gesell-schaftlichen Abstieg der Mittelschichten, wie beuge ich hefti-gen sozialen Unruhen
vor? Im Vorzeichen solcher Bedrohun-gen dürfte schnell möglich werden, was gegenwärtig
bislang völlig utopisch erscheint. Der Motor des sozialen Fortschritts war noch nie das
bessere Argument, sondern immer waren es der Affekt und die Katastrophe. Die Pläne dafür
aber müssen jetzt geschmiedet werden und nicht im Zustand des Dramas, der Überforderung
und der Schnellschüsse. Wenn eine Mikrosteuer von 0,05 Prozent für jede Finanz-transaktion
ausreichen könnte, um ein BGE für die Schweiz zu finanzieren, so lässt sich auch
ausrechnen, welcher Prozent-satz benötigt würde, um das Gleiche für Deutschland zu tun.
Der Prozentsatz wäre sicher höher, aber gewiss immer noch so gering, dass er den meisten
Menschen kaum auffällt. Ent-sprechende realistische Modelle zu entwickeln ist nicht
Auf-gabe der Philosophen, sondern der Ökonomen. Einrechnen müssten sie dabei auch die
mutmaßlichen Folgen für die Spe-kulation. Doch selbst wenn die Mikrosteuer einen gewissen
Prozentsatz an Zockergeschäften abschafft - was für die Sta-bilität der Finanzmärkte von
größtem Wert wäre, ließe sich das Grundeinkommen in den reichen Ländern auf diese Weise
sicher finanzieren. Immerhin beträgt das Volumen des welt-weiten Derivatehandels mit 600
bis 700 Billionen US-Dollar in etwa das Zehnfache des globalen Bruttoinlandsprodukts! Am
Geld also dürfte kein BGE scheitern. Und die Mikrosteu-er auf Finanztransaktionen wäre
zumindest kurz- und mittel-fristig die beste Idee, jedenfalls solange die internationale
Fi-nanzwirtschaft noch das ist, was sie heute ist (S.135)
#+end_quote

Über Liberalismus und Sozialismus
#+begin_quote
*Für eines Liberalen ist es gerecht, wenn jeder die gleiche Chance hat, zu Wohlstand zu
gelangen, unbegrenzt nach oben. Für eines Sozialisten ist es gerecht, wenn jeder das
gleiche Stück ausm Kuchen abbekommt.* Keine dieser Vorstellungen ist, philosophisch
betrachtet, von Natur aus gerechter als die andere Kein Wunder, dass die soziale
Marktwirtschaft sich stets um einen Ausgleich beider Vorstellungen bemüht, allerdings un
ter sich wandelnden ökonomischen Bedingungen. Wenn der Wohlfahrtsstaat bedroht ist, dann
deshalb, weil sich die globale Ökonomie rasant verändert. (S.142)
#+end_quote

** Gute Ideen für den Tag
Über die Entfremdung durch Technologie
#+begin_quote
Die Aufgabe ist damit klar markiert: in einer Zeit radikaliserten Effizienzdenkens das
Andere der Effizienz wieder zuentdecken! * Denn die technische Entwicklung, so wie das
Silicon Valley sie erträumt und predigt, macht uns nicht Supermenschen, sondern zu Wesen,
die ohne Hilfsmittel nichts mehr können.* *Unser handwerkliches Können erlischt, unser
sprachlicher Ausdruck reduziert sich, unser Gedächtnis, ausgelagert in Memory-Funktionen,
lässt nach, unsere Fantasie besteht aus vorgefertigten Bildern, unsere Kreatität folgt
ausschließlich technischen Mustern, unsere Neugier weicht der Bequemlichkeit, unsere
Geduld permanenter Ungeduld; den Zustand der Nicht-Bespaßung halten wir niche mehr aus.
Wenn so der Supermensch aussicht - wer wollte dann einer sein?* (S.154)
#+end_quote

Über den Wert repetitiver Tätigkeiten
#+begin_quote
Wenn Google-Vizepräsident Sebastian Thrun sagt: *Wir Menschen sollten keine repetitiven
Dinge tun.* Dafür sind wir doch zu schade, scheint er nicht zu wissen, was ein Mensch ist.
Das menschliche Leben ist voller repetitiver Dinge, für die man sich nicht zu schade sein
sollte: Essen, Trinken, Schlafen, Sich-den-Tag-Erzählen, Sich-Umarmen, Kochen,
Miteinander-ins-Bett-Gehen. *Zu einem erfüllten Leben gehören für die meisten Menschen ein
Maß an Gleichförmigkeit und lieb gewordene Rituale.* *Das Besondere daran ist: Nicht jede
dieser Tätigkeiten hat ein äußeres Ziel.* Man braucht es nicht tun, um zu überleben, und
man verdient damit auch kein Geld. Karten oder Fußball zu spielen, seinen Garten zu
verschönern, sein Aquarium zu pilegen, einen Hund zu halten oder sich gemeinsam zu
betrin-ken ist weder überlebensförderlich, noch macht es im finanziellen Sinne reich (von
Berufszockern, Hundezüchtern usw. einmal abgesehen). All das gilt in der Gesellschaft auch
nicht als Leistung; im Gegensatz zu Tätigkeiten wie ein Versicherungsimperium aufzubauen
oder gefährliche Pflanzenschutzmittel in alle Welt zu verkaufen.

*Wertvoll wird eine Tätigkeit für Menschen nicht zwangsläufig dadurch, dass sie einem
gesellschaftlich als wichtig erachteten Ziel dient. Vieles hat seinen Zweck schlichtweg in
sich selbst: Ich tue etwas, weil ich es gerne tue.* Eine solche Zweckmäßigkeit ohne Zweck
erachtete Immanuel Kant schon vor mehr als zweihundert Jahren als das Wesen der Kunst.
Nichts anderes meinte Oscar Wilde, als er den Menschen der Zukunft als Künstler beschrieb
(S.157)
#+end_quote

Kritik am *Konzept des Übermenschen*
#+begin_quote
Wer den Menschen überwinden und einen Supermenschen hervorbringen will, dem fehlt es an
Menschenliebe oder an sittlicher Reife -oder an beidem. Eigentlich gehört er auf die
Couch. Doch wer soll ihm sagen, dass er einer Therapie bedarf, wenn man mit diesem Denken
und Streben so formidabel Geld verdienen kann? So lässt man dem Mythos freien Lauf, die
Geschichte der Menschheit sei bereits evolutionär vorgezeichnet. Und am Ende steht das
*Technozän* mit seiner Verschmelzung von Mensch und Maschine, oder aber, im un günstigeren
Fall, die Diktatur der autonom gewordenen Maschinen. Nicht anders hatten schon die
Christen im Mittelalter ein Tausendjahriges Reich Gottes auf Erden vorausgesagt und die
Nationalsozialisten die Vorsehung bemüht, die ihusen gleichsam naturgesetzlich ein solches
bescheren sollte. *Aber man darf sich beruhigen: Einen wirklich perfekten Supermeschen hat
das Silicon Valley zu keinem Zeitpunkt im Auge. Nur unperfekte Menschen garantieren, dass
sie sich auch Zukunft von jeder Kaufempfehlung anreizen, von jeder Manipulation verführen
lassen. Ein perfekter Mensch, Herr seiner Antriebe und Durchschauer seiner Umwelt, ist des
Valleys Tod...* (S.162)
#+end_quote


Über Zeit und Geld
- Der Leitspruch "Zeit ist Geld" wird kaum hinterfragt, obwohl er irrig ist.
- Geld kann die menschliche Lebenszeit nicht verlängern.
- Zeit und Geld haben äußerst verschiedene Eigenschaften: Geld kann geteilt werden, Zeit
  nicht.
- Eine Zeitsparkasse gibt es nur in Michael Endes Momo.
- Verhaltensweisen wie Fast Food, Speed Dating, Power Napping oder Multitasking sparen uns
  keine Zeit, sondern nur andere Art der Verwendung derselben Lebenszeit.
- "Immer mehr ist oft immer weniger".

#+begin_quote
Dabei wird kaum hinterfragt, dass der Leitspruch Zeit ist Geld ziemlich irrig ist. Mit
Geld lässt sich die menschliche Lebenszeit oft nicht verlängern. Auch so haben Zeit und
Geld äußerst verschiedene Eigenschaften. Geld hal-Lert sich, wenn man es teilt - Zeit
nicht! Sie wird nicht schnel-ler weniger als sonst auch. Im Zweifelsfall bleibt sie uns
als erfüllte Zeit in Erinnerung, jedenfalls eher als jene Zeit, die wir damit verbracht
haben, unsere Schritte und Treppenstu-fen zu zählen. Am wichtigsten aber ist: Geld kann
man spa-ren, Zeit nicht. Eine Zeitsparkasse gibt es nur in Michael Endes Momo. Doch weder
Fast Food, Speed Dating, Power schaft Napping oder Multitasking sparen uns Zeit. Sie sind
nur an-adere Verhaltensweisen in derselben Lebenszeit. Und immer mehr ist oft immer
weniger. (S.165)
#+end_quote


Über Bildung in der digitalen Gesellschaft
- Es geht nicht nur um digitales Know-how: Es geht um die Persönlichkeitsbildung und die
  Fähigkeit, ein erfülltes Leben zu leben.
- Die Ziele von Bildung sollten nicht allein am Arbeitsmarkt ausgerichtet sein, sondern
  auch an der Förderung von Traditionen, Händen und Werten.
- Es braucht Menschen, die sich für andere Menschen einsetzen, sich kümmern und
  alternative Gesellschaftsmodelle entwickeln.
- Eine Gesellschaft, die nur auf Erfolg im digitalen Umfeld abzielt, ist weder möglich
  noch wunschenswert.
- Die Bildung soll nicht dazu dienen, die höchstmöglichen Unternehmergewinne zu erzielen,
  sondern Menschen heranzuziehen, die ihre Werte und Hände bewahren.

#+begin_quote
Deutschland muss mehr für die Bildung tun! Doch was ist damit gemeint? Vereinfacht gesagt,
treffen hier zwei Posi tionen aufermander, die gegensätzlicher nicht sein können. Für
viele Wirtschaftsvertreter und manche universitären Bildungs-experten ist die Sache ganz
einfach: Eine digitale Gesellschaft braucht mehr digitales Know-how. Je mehr digitale
Technik im Unterricht eingesetzt wird und je stärker die MINT-Fa-cher gefördert werden,
umso besser werden Kinder auf den zukünftigen Arbeitsmarkt vorbereitet. Nicht zu vergessen
sei auch das frühzeitige Antrainieren von Unternehmergeist. Je mehr Kinder später ein
Start-up gründen, umso besser ist es um eine Schule bestellt. Für viele klingt das
plausibel. Zumindest auf den ersten Blick. Doch wer sich mit dem Thema länger beschäftigt,
dem fillt auf, wie voraussetzungsreich ein solches Bildungsziel ist. Es unterstellt
erstens, dass es die Aufgabe unseres Bildungs-systems ist, dem Arbeitsmarkt passgenau die
entsprechenden Arbeitskräfte bereitzustellen. Und es nimmt zweitens an, dass die
Arbeitsmärkte der Zukunft so aussehen wie jetzt, zusatz-lich mit einer weit höheren
Nachfrage nach Informatikern und Entrepreneuren. Größere gesellschaftliche Umbrüche durch
die digitale Revolution kommen in diesem Modell nicht vor. Und Bildung ist vor allem
eines - Ausbildung! Die zweite Position formuliert ein anderes Bildungsziel: Bildung
bedeutet, so viele junge Menschen wie möglich dazu zu befähigen, ein erfulltes Leben zu
leben. Der gegenwär ge und tungsgesellschaft ist for sie nicht der höchste Maßstab, weiß
schon, ob die Prognosen zutreffen, dass wir in zehn Jah ren viel mehr Informatiker
brauchen? Möglicherweise beng tigen wir vor allem -Empathie-Berufe, wie das Millennium
Projekt vermutet. In solcher Lage Bildung an kurzfristigen Spekulationen über den
Arbeitsmarkt auszurichten ist falu lässig und gefährlich, Das hochste Bildungsziel kann
auch nicht darin bestehen, möglichst viele Kinder dazu zu bringen, hohe unternehmeri sche
Gewinne erzielen zu wollen. Unsere Gesellschaft funk tioniert offensichtlich nur, wenn die
eiskalten Kosten-Nur zen-Maximierer ihres finanziellen Vorteils in der Minderheit sind.
Wer würde unter solchen Voraussetzungen noch Kinder garnerin oder Altenpfleger? Alle
Bildungsziele, die den Ar beitsmarkt über die Persönlichkeitsbildung stellen, sind kurz
sichtig. Es braucht nicht nur Menschen, die in der digitalen Okonomie erfolgreich sind. Es
braucht auch solche, die unse re Werte und unsere Handwerkskunst bewahren, sich für an
dere Menschen einsetzen. Traditionen pflegen, sich kümmern und über alternative
Gesellschaftsmodelle nachdenken. Eine Welt allem aus Geeks, Finanzspekulanten, You Tube
Stars und Influencern ist weder möglich noch wunschenswert. Und es muss kein Nachteil
sein, wenn morgen noch jemand Koch. Okobauer, Sozialarbeiter, Tischler oder klassischer
Musiker werden will. (S.167)
#+end_quote

** Betreutes Leben?
Kritik an der Effizienzoptimierung
- Viele visionäre Ideen aus Silicon Valley sind bei näherer Hinsicht keine.
- Manche entwickeln Technologie ohne Menschenkenntnis und Beachtung von gesellschaftlichen
  Bedürfnissen.
- Effizienz sollte nicht als höchster Maßstab angesehen werden, da sie den Tod bedeuten
  würde (den Zustand, in dem sich nichts mehr verändern lässt).
- Das Leben ist wider-ständig, unberechenbar und unausgegoren, was es lebenswert und
  aufregend macht.

#+begin_quote
Viele visionäre Ideen, die aus dem Silicon Valley kommen, sind bei näherer Hinsicht keine.
Nicht wenigen mangelt es an Menschenkenntnis. Und ersonnen wird, was die Technologie
hergibt, und nicht, was viele Menschen oder die Gesellschaft dringend brauchen. Vieles,
was sich technisch perfektionie-ren lässt, muss und sollte, wie gesagt, gar nicht
perfektioniert werden jedenfalls nicht, ohne damit Folgen zu produzieren, die niemand im
Sinn hat und keiner tragen will. Man stelle sich des Ernstes halber einmal eine
Gesellschaft vor, in der alles effizient und perfekt optimiert ist was kommt eigent-lich
dann? Nichts kann mehr verändert oder variiert werden, ohne die Dinge weniger effizient zu
machen. Und was bedeu-tet es eigentlich, Effizienz als höchsten Maßstab anzulegen Der
effizienteste Zustand des Menschen, die perfekteste Lo sung aller Lebensprobleme ist der
Tod: der Zustand, in dem man sich nicht mehr bewegen muss, keine Energie mehr verbraucht,
sich nicht mehr anstrengen muss und von allen Wirrnissen und Unbilden des Lebens befreit
ist. Eine bessere Lösung als den Tod gibt es nicht, er ist der smarteste Zustand des
Menschen. Das Leben aber ist nicht smart. Es ist wider-ständig, unberechenbar,
unausgegoren und uneindeutig-und gerade das macht es lebenswert und aufregend! (S.182)
#+end_quote


Über Freiheit und Verantwortung
- Philosophen der Aufklärung wie Kant, Schiller und Herder argumentierten gegen ein Leben
  ohne Erleben von Außergewöhnlichem.
- Sie strebten nach einer Gesellschaft, in der sich Menschen im Fortschritt ihrer Kultur
  tätig am Leben abarbeiten und reifen.
- Freiheit bedeutet Verantwortung gegenüber sich selbst und anderen übernehmen, nicht
  betreuen lassen werden.
- Technischer Fortschritt muss Verantwortung nicht verringern, sondern erhöhen.

#+begin_quote
Ein betreutes Leben jedenfallh, in dem einem alles abgenommen wird, das Praktische ebenso
wie das Erleben von Außergewöhnlichem, ist kein Mensch heitsfortschritt. Statt mit
Supermenschen hätten wir es mit Menschen zu tun, die sich nie allzu weit über das
Kindheits stadium hinaus entwickeln, weil sie es nicht müssen.

Große Philosophen der Aufklärung wie Kant, Schiller und Herder haben dagegen argumentiert,
sich ins Paradies der Unmündigkeit zu träumen. Eine Gesellschaft der Lustbe friedigung und
Leidvermeidung erschien ihnen nicht erstre benswert. Freiheit ihr großer Wert besteht
nicht in einer Abkürzung zum Glück. Nicht das Paradies mit einem unmün digen Menschen war
ihr Ziel, sondern ein Mensch, der sich im Fortschritt seiner Kultur tätig am Leben
abarbeitet und da bei reift. Frei zu sein bedeutet, Verantwortung gegenüber sich selbst
und anderen zu übernehmen, nicht, sich betreuen zu las sen. Wo der technische Fortschritt
dazu führt, dass wir immer weniger Verantwortung für uns übernehmen müssen, widergricht et
der Grundvorstellung unserer Gesellschaft, auf der unsere Verfassung beruht: dem mündigen
Bürger! (S.186)
#+end_quote


** Geschichten statt Pläne
Über den "Solutionismus"
#+begin_quote
Im Jahr 2013 übertrug der weißrussische Journalist Evgeny Morozov den Begriff
>>Solutionismus aus der Architekturthe-orie auf zahlreiche Ideen, Zukunftsentwürfe und
Geschäfts-modelle des Silicon Valley. Auch hier sieht er einen kurzsichti-gen Willen zu
vervollkommnen am Werk, der sich einmal böse rächen wird. Denn dieser Wille interessiert
sich nur beiläufig für die Handlungen, die verbessert werden sollen. (S.201)
#+end_quote

Über soziale Normen und Transparenz
- Kein System sozialer Normen kann perfekte Verhaltenstransparenz ohne sich zu Tode erenn.
- Eine Gesellschaft, die jede Verhaltensabweichung aufdeckt, würde die Geltung ihrer
  Normen ruinieren.
- Normen haben zwangsläufig etwas Starres, Unverbindliches, Fixiertes und stets auch etwas
  Überforderndes.
- Grauzonen sind notwendig für Sozialleben und Moral; Regelverstöße gehören zum
  menschlichen Leben dazu.
- Der Begriff "Regelverstoß" ist hochgradig kulturell bedingt.
- Wenn alle gegen die Norm verstoßen, wird der Normverstoß belangloser.
- Je mehr wir über die Verstöße der anderen wissen, umso gerechtfertigter erscheint unser
  eigenes Fehlverhalten.

#+begin_quote
Kein System sozialer Normen könnte einer perfekten Verhaltenstransparenz ausgesetzt
werden, ohne sich zu Tode zu eren, schreibt der Soziologe Heinrich Popitz. Eine
Gesellschaft, die jede Verhaltensabweichung aufdeckte, würde gesch die Geltung ihrer
Normen ruinieren. Denn wenn es öffentlich wird, würden die Menschen dadurch nicht
anständiger. Vielmehr würden alle Normen wahrscheinlich über kar oder lang ihre Geltung
verlieren, da man sie ja ohnehin thundertprozentig einhalten kann.

Normen haben zwangsläufig etwas Starres, Unverbindliches, Fixiertes, etwas Stures und
damit stets auch etwas Überforderndes, Illusionäres, Sozialverhalten und Moral aber leben
von Grauzonen, von Verhalten, das man nicht so genao kennt. Es lässt sich nicht normieren
wie die Größe von Nigeln oder Schrauben. Wo wirkliche Menschen leben, ge-hört der
Regelverstoß zum Sozialleben dazu. Schon was über haupt ein Regelverstoß ist, ist
hochgradig kulturell bedingt. Wer in Beirut über eine rote Ampel geht, wird von der
Polizei dafür nicht belangt. In Bayreuth dagegen ist das Risiko höher. Der Grund dafür ist
klar. Würde sich die Polizei in Beirut sum Verstöße bei Fußgängern kümmern, käme sie zu
nichts anderem mehr. Auch Normen unterliegen dem Prinzip der shifting baselines. Wenn alle
gegen die Norm verstoßen, wird der Normverstoß belangloser, als wenn alle sich daran
hal-ten. Denn je mehr wir über die Verstöße der anderen wissen, umso gerechtfertigter
erscheint uns unser eigenes Fehlverhal ten. Wenn es offentlich wäre, wie viel andere bes
ihrer Steuererklärung tricksen, führte dies gewiss nicht zu einer besseren Steuermoral.
Gemäß unserer Vergleichslogik wäre es wohl ther der Anfang einer mutmaßlichen
Abwärtsspirale. (S.205)
#+end_quote


Über den Konsumenten-Zuschauer-Bürger
- Der Konsumenten-Zuschauer-Bürger wird seine demokratische Macht an die großen
  Digitalkonzerne abtreten?
- Robert Reich: Verbraucher und Anleger bekommen immer mehr Macht, Arbeitnehmer und Bürger
  dagegen immer weniger
- Ist dieser Prozess alternativlos?

#+begin_quote
Wird der >>Konsumenten-Zuschauer-Bürger, wie Richard Sennett ihn nennt, seine
demokratische Macht an die großen Digitalkonzerne abtreten und sich seine Freiheit für
Annehmlichkeiten abkaufen lassen? Und stimmt es, was der ehemalige US-amerikanische
Arbeitsminister und Politik-Professor Robert Reich sagt, dass wir als Verbraucher und
Anleger immer mehr Macht bekommen, als Arbeitneh mer und Bürger dagegen immer weniger? Ist
dieser Prozess alternativlos? Oder lässt sich das ändern? (S.212)
#+end_quote


Über den Wandel des politischen Denkens
- Die Bindung an den Staat und die Parteien ist in den letzten Jahrzehnten abgenommen.
- Viele Menschen übertragen ihre Konditionierung als Konsumenten auf den Staat.
- Sie fragen nach direkten Vorteilen und Lösungen für Probleme, wie z.B.
  Flüchtlingsproblem oder Umweltproblem.
- Wer von der Politik nur Lebenskomfort und Lösungen erwartet, hat sich vom politischen
  Denken entfernt.
- Sozialtechnische Lösungen können sich hier durchsetzen.
- Die Vision einer "Smart City" basiert auf der Überwachung mit Sensoren und Kameras.
- Die Technologie kann alle Daten in einer Cloud verfügbar machen und die Menschen in
  permanente Interaktion mit ihr bringen.

#+begin_quote
In den letzten Jahrzehnten ist die Bindung an den Staat, ins-besondere an die Parteien,
die die staatsbürgerliche Willensbil-dung mit verantworten sollen, stets geringer
geworden. Start-dessen übertragen viele Menschen die gleiche Haltung, die sie als
Konsumenten haben, an den Staat. Sie fragen: »Was bringt mir das?<< Oder: »Welchen Vorteil
habe ich davon?<< Und was die großen Fragen der Zeit anbelangt, so erwarten sie, ganz im
Geiste der Technik, Lösungen. So soll der Staat das Flücht-lingsproblem lösen. Am besten
dadurch, dass man, ganz ma-thematisch, eine Zahl als Obergrenze definiert. Und dann ist
das Problem weg. Das Gleiche gilt für das Umweltproblem oder das Gerechtigkeitsproblem.

Wer von der Politik in erster Linie Lebenskomfort und Lö-sungen für Probleme erwartet, der
hat sich aus dem politi-schen Denken weitgehend verabschiedet. Und genau hier liegt die
Einflugschneise für sozialtechnische Lösungen. Zu verhin-dern, dass Menschen kriminell
werden, ist ein schwieriger und langwieriger Prozess. Eine Stadt mit Sensoren und Kameras
vollständig zu überwachen, einfach und smart. Schon aus die-sem Grund sind »Smart
Citys<<<< eine von vielen geteilte Vision. Die Sensortechnik kann alle erfassten Daten
einer städtischen Umgebung in einer Cloud verfügbar machen. Die Menschen, die in der Stadt
leben, und die Technologie, die sie umgibt, tre-ten so in permanente Interaktion. Je nach
Perspektive werden die Dinge um uns herum menschlich, oder aber die Men-schen erscheinen
als Teil der technischen Infrastruktur. (S.213)
#+end_quote

