:PROPERTIES:
:ID:       ec38eea2-ed6a-4467-9261-f1f96791beb3
:END:
#+author: [[Adam Grant]]
#+authors: [[Adam Grant]]
#+created: 20190418210643099
#+date: 2018-09-01
#+creator: boru
#+finished_month: 09
#+finished_year: 2018
#+goodreads: https://www.goodreads.com/book/show/25614523-originals?ac=1&from_search=true&qid=8yCe96FHrQ&rank=3
#+isbn: 9780147524416
#+item_type: Ebook
#+modified: 20210608081751690
#+modifier: boru
#+publication_title: What Every Body Is Saying: An Ex-FBI Agent's Guide to Speed-reading People
#+publication_type: book
#+revision: 0
#+slider: hide
#+status: todo
#+filetags: book
#+title: Originals
#+tmap.id: 4ca1f6f1-5f98-4c84-9288-3c797d67c70d
#+type: text/vnd.tiddlywiki

#+begin_quote
In Originals the author addresses the challenge of improving the world from the perspective of becoming original: choosing to champion novel ideas and values that go against the grain, battle conformity, and buck outdated traditions. How can we originate new ideas, policies, and practices without risking it all? Using surprising studies and stories spanning business, politics, sports, and entertainment, Grant explores how to recognize a good idea, speak up without getting silenced, build a coalition of allies, choose the right time to act, and manage fear and doubt; how parents and teachers can nurture originality in children; and how leaders can build cultures that welcome dissent. Learn from an entrepreneur who pitches his start-ups by highlighting the reasons not to invest, a woman at Apple who challenged Steve Jobs from three levels below, an analyst who overturned the rule of secrecy at the CIA, a billionaire financial wizard who fires employees for failing to criticize him, and a TV executive who didn't even work in comedy but saved Seinfeld from the cutting-room floor. The payoff is a set of groundbreaking insights about rejecting conformity and improving the status quo.

(Source: [[https://www.goodreads.com/book/show/25614523-originals]])

#+end_quote
* Quotes
** Originals - Note 1                                                          :quote:done:
I learned that great creators don’t necessarily have the deepest expertise but rather seek out the broadest perspectives.

** Originals - Note 2                                                          :quote:done:
#+begin_quote
success is not usually attained by being ahead of everyone else but by waiting patiently for the right time to act.
#+end_quote

** Originals - Note 4                                                          :quote:done:
#+begin_quote
Originality is taking the road less traveled, championing a set of novel ideas that go against the grain but ultimately make things better.
#+end_quote

** Originals - Note 5                                                          :quote:done:
#+begin_quote
Originality itself starts with creativity: generating a concept that is both novel and useful.
#+end_quote

** Originals - Note 6                                                          :quote:done:
#+begin_quote
“People who suffer the most from a given state of affairs are paradoxically the least likely to question, challenge, reject, or change it.”
#+end_quote

** Originals - Note 7                                                          :quote:done:
#+begin_quote
To explain this peculiar phenomenon, Jost’s team developed a theory of system justification.7 Its core idea is that people are motivated to rationalize the status quo as legitimate—even if it goes directly against their interests.
#+end_quote

** Originals - Note 8                                                          :quote:done:
#+begin_quote
Justifying the default system serves a soothing function. It’s an emotional painkiller: If the world is supposed to be this way, we don’t need to be dissatisfied with it.
#+end_quote

** Originals - Note 9                                                          :quote:done:
#+begin_quote
The hallmark of originality is rejecting the default and exploring whether a better option exists.
#+end_quote

** Originals - Note 10                                                         :quote:done:
#+begin_quote
Déjà vu occurs when we encounter something new, but it feels as if we’ve seen it before. Vuja de is the reverse—we face something familiar, but we see it with a fresh perspective that enables us to gain new insights into old problems.
#+end_quote

** Originals - Note 11                                                         :quote:done:
#+begin_quote
When we become curious about the dissatisfying defaults in our world, we begin to recognize that most of them have social origins: Rules and systems were created by people. And that awareness gives us the courage to contemplate how we can change them.
#+end_quote

** Originals - Note 12                                                         :quote:done:
#+begin_quote
They focus their energy on consuming existing scientific knowledge, not producing new insights. They conform to the codified rules of established games, rather than inventing their own rules or their own games. All along the way, they strive to earn the approval of their parents and the admiration of their teachers.
#+end_quote

** Originals - Note 13                                                         :quote:done:
#+begin_quote
Teachers tend to discriminate against highly creative students, labeling them as troublemakers. In response, many children quickly learn to get with the program, keeping their original ideas to themselves. In the language of author William Deresiewicz, they become the world’s most excellent sheep.
#+end_quote

** Originals - Note 15                                                         :quote:done:
#+begin_quote
The drive to succeed and the accompanying fear of failure have held back some of the greatest creators and change agents in history. Concerned with maintaining stability and attaining conventional achievements, they have been reluctant to pursue originality. Instead of charging full steam ahead with assurance, they have been coaxed, convinced, or coerced to take a stand. While they may seem to have possessed the qualities of natural leaders, they were figuratively—and sometimes literally—lifted up by followers and peers.
#+end_quote

** Originals - Note 16                                                         :quote:done:
#+begin_quote
If a handful of people hadn’t been cajoled into taking original action, America might not exist, the civil rights movement could still be a dream, the Sistine Chapel might be bare, we might still believe the sun revolves around the earth, and the personal computer might never have been popularized.
#+end_quote

** Originals - Note 17                                                         :quote:done:
#+begin_quote
The word entrepreneur, as it was coined by economist Richard Cantillon, literally means “bearer of risk.”
#+end_quote

** Originals - Note 19                                                         :quote:done:
#+begin_quote
I want to debunk the myth that originality requires extreme risk taking and persuade you that originals are actually far more ordinary than we realize. In every domain, from business and politics to science and art, the people who move the world forward with original ideas are rarely paragons of conviction and commitment. As they question traditions and challenge the status quo, they may appear bold and self-assured on the surface. But when you peel back the layers, the truth is that they, too, grapple with fear, ambivalence, and self-doubt.
#+end_quote

** Originals - Note 20                                                         :quote:done:
#+begin_quote
After inventing the original Apple I computer, Steve Wozniak started the company with Steve Jobs in 1976 but continued working full time in his engineering job at Hewlett-Packard until 1977.
#+end_quote

** Originals - Note 21                                                         :quote:done:
#+begin_quote
And although Google founders Larry Page and Sergey Brin figured out how to dramatically improve internet searches in 1996, they didn’t go on leave from their graduate studies at Stanford until 1998. “We almost didn’t start Google,” Page says, because we “were too worried about dropping out of our Ph.D. program.”29 In 1997, concerned that their fledgling search engine was distracting them from their research, they tried to sell Google for less than $2 million in cash and stock. Luckily for them, the potential buyer rejected the offer.
#+end_quote

** Originals - Note 22                                                         :quote:done:
#+begin_quote
Soon thereafter he wrote “We Will Rock You.”31 Grammy winner John Legend released his first album in 2000 but kept working as a management consultant until 2002, preparing PowerPoint presentations by day while performing at night.
#+end_quote

** Originals - Note 23                                                         :quote:done:
#+begin_quote
In the stock market, if you’re going to make a risky investment, you protect yourself by playing it safe in other investments.
#+end_quote

** Originals - Note 25                                                         :quote:done:
#+begin_quote
As Polaroid founder Edwin Land remarked, “No person could possibly be original in one area unless he were possessed of the emotional and social stability that comes from fixed attitudes in all areas other than the one in which he is being original.”
#+end_quote

** Originals - Note 26                                                         :quote:done:
#+begin_quote
Having a sense of security in one realm gives us the freedom to be original in another.
#+end_quote

** Originals - Note 27                                                         :quote:done:
#+begin_quote
Across all three studies, the people who become successful entrepreneurs were more likely to have teenage histories of defying their parents, staying out past their curfews, skipping school, shoplifting, gambling, drinking alcohol, and smoking marijuana. They were not, however, more likely to engage in hazardous activities like driving drunk, buying illegal drugs, or stealing valuables. And that was true regardless of their parents’ socioeconomic status or family income.
#+end_quote

** Originals - Note 28                                                         :quote:done:
#+begin_quote
We see the same pattern in politics: When hundreds of historians, psychologists, and political scientists evaluated America’s presidents, they determined that the least effective leaders were those who followed the will of the people and the precedents set by their predecessors.49 The greatest presidents were those who challenged the status quo and brought about sweeping changes that improved the lot of the country. But these behaviors were completely unrelated to whether they cared deeply about public approval and social harmony.
#+end_quote

** Originals - Note 29                                                         :quote:done:
#+begin_quote
They know in their hearts that failing would yield less regret than failing to try.
#+end_quote

** Originals - Note 30                                                         :quote:done:
#+begin_quote
“Creativity is allowing yourself to make mistakes. Art is knowing which ones to keep.”1 Scott Adams
#+end_quote

** Originals - Note 31                                                         :quote:done:
#+begin_quote
in reality, the biggest barrier to originality is not idea generation—it’s idea selection.
#+end_quote

** Originals - Note 32                                                         :quote:done:
#+begin_quote
If originals aren’t reliable judges of the quality of their ideas, how do they maximize their odds of creating a masterpiece? They come up with a large number of ideas.
#+end_quote

** Originals - Note 33                                                         :quote:done:
#+begin_quote
Across fields, Simonton reports that the most prolific people not only have the highest originality; they also generate their most original output during the periods in which they produce the largest volume.
#+end_quote

** Originals - Note 34                                                         :quote:done:
#+begin_quote
It’s widely assumed that there’s a tradeoff between quantity and quality—if you want to do better work, you have to do less of it—but this turns out to be false. In fact, when it comes to idea generation, quantity is the most predictable path to quality. “Original thinkers,” Stanford professor Robert Sutton notes, “will come up with many ideas that are strange mutations, dead ends, and utter failures. The cost is worthwhile because they also generate a larger pool of ideas—especially novel ideas.”
#+end_quote

** Originals - Note 35                                                         :quote:done:
#+begin_quote
Many people fail to achieve originality because they generate a few ideas and then obsess about refining them to perfection.
#+end_quote

** Originals - Note 36                                                         :quote:done:
#+begin_quote
“Once you start getting desperate, you start thinking outside the box,”
#+end_quote

** Originals - Note 37                                                         :quote:done:
#+begin_quote
The best way to get better at judging our ideas is to gather feedback.
#+end_quote

** Originals - Note 38                                                         :quote:done:
#+begin_quote
Conviction in our ideas is dangerous not only because it leaves us vulnerable to false positives, but also because it stops us from generating the requisite variety to reach our creative potential.
#+end_quote

** Originals - Note 39                                                         :quote:done:
#+begin_quote
In the face of uncertainty, our first instinct is often to reject novelty, looking for reasons why unfamiliar concepts might fail.
#+end_quote

** Originals - Note 40                                                         :quote:done:
#+begin_quote
To protect themselves against the risks of a bad bet, they compare the new notion on the table to templates of ideas that have succeeded in the past.
#+end_quote

** Originals - Note 41                                                         :quote:done:
#+begin_quote
Instead of attempting to assess our own originality or seeking feedback from managers, we ought to turn more often to our colleagues. They lack the risk-aversion of managers and test audiences; they’re open to seeing the potential in unusual possibilities, which guards against false negatives. At the same time, they have no particular investment in our ideas, which gives them enough distance to offer an honest appraisal and protects against false positives.
#+end_quote

** Originals - Note 42                                                         :quote:done:
#+begin_quote
All it took was having them spend their initial six minutes a little differently: instead of adopting a managerial mindset for evaluating ideas, they got into a creative mindset by generating ideas themselves. Just spending six minutes developing original ideas made them more open to novelty, improving their ability to see the potential in something unusual.
#+end_quote

** Originals - Note 43                                                         :quote:done:
#+begin_quote
Once you take on a managerial role, it’s hard to avoid letting an evaluative mindset creep in to cause false negatives.
#+end_quote

** Originals - Note 44                                                         :quote:done:
#+begin_quote
If we want to increase our odds of betting on the best original ideas, we have to generate our own ideas immediately before we screen others’ suggestions.
#+end_quote

** Originals - Note 45                                                         :quote:done:
#+begin_quote
“If you’re gonna make connections which are innovative,” Steve Jobs said back in 1982, “you have to not have the same bag of experience as everyone else does.”
#+end_quote

** Originals - Note 46                                                         :quote:done:
#+begin_quote
It is when people have moderate expertise in a particular domain that they’re the most open to radically creative ideas.
#+end_quote

** Originals - Note 47                                                         :quote:done:
#+begin_quote
People who started businesses and contributed to patent applications were more likely than their peers to have leisure time hobbies that involved drawing, painting, architecture, sculpture, and literature.
#+end_quote

** Originals - Note 48                                                         :quote:done:
#+begin_quote
People who are open to new ways of looking at science and business also tend to be fascinated by the expression of ideas and emotions through images, sounds, and words.
#+end_quote

** Originals - Note 49                                                         :quote:done:
#+begin_quote
Just as scientists, entrepreneurs, and inventors often discover novel ideas through broadening their knowledge to include the arts, we can likewise gain breadth by widening our cultural repertoires. Research on highly creative adults shows that they tended to move to new cities much more frequently than their peers in childhood, which gave them exposure to different cultures and values, and encouraged flexibility and adaptability.
#+end_quote

** Originals - Note 50                                                         :quote:done:
#+begin_quote
To accurately predict the success of a novel idea, it’s best to be a creator in the domain you’re judging.
#+end_quote

** Originals - Note 51                                                         :quote:done:
#+begin_quote
New research led by Erik Dane shows us why: our intuitions are only accurate in domains where we have a lot of experience.
#+end_quote

** Originals - Note 52                                                         :quote:done:
#+begin_quote
“But products don’t create value. Customers do.”
#+end_quote

** Originals - Note 53                                                         :quote:done:
#+begin_quote
In a rapidly changing world, the lessons of experience can easily point us in the wrong direction.
#+end_quote

** Originals - Note 54                                                         :quote:done:
#+begin_quote
As Daniel Kahneman explains in Thinking, Fast and Slow, intuition operates rapidly, based on hot emotions, whereas reason is a slower, cooler process.
#+end_quote

** Originals - Note 55                                                         :quote:done:
#+begin_quote
When assessing the prospects of a novel idea, it’s all too easy to be seduced by the enthusiasm of the people behind it. In the words of Google executives Eric Schmidt and Jonathan Rosenberg, “Passionate people don’t wear their passion on their sleeves; they have it in their hearts.”
#+end_quote

** Originals - Note 56                                                         :quote:done:
#+begin_quote
You can love an idea and be determined to succeed, but still communicate it in a reserved manner.
#+end_quote

** Originals - Note 57                                                         :quote:done:
#+begin_quote
If we want to improve our idea selection skills, we shouldn’t look at whether people have been successful. We need to track how they’ve been successful.
#+end_quote

** Originals - Note 58                                                         :quote:done:
#+begin_quote
Bill Sahlman adds: “It’s never the idea; it’s always the execution.”
#+end_quote

** Originals - Note 59                                                         :quote:done:
#+begin_quote
Historically, the doors to many creative careers were closed to women.21 Those who managed to get their feet in the door were often full-time caregivers for children. As a result, men simply produced more output than women, giving them a higher chance of originality. With greater equality of opportunity today, these gender differences in creative output ought to disappear, and may even reverse. Berg finds that on average, women make better creative forecasts than men: They’re more open to novel ideas, which leaves them less prone to false negatives.
#+end_quote

** Originals - Note 60                                                         :quote:done:
#+begin_quote
openness, the tendency to seek out novelty and variety in intellectual, aesthetic, and emotional pursuits.
#+end_quote

** Originals - Note 61                                                         :quote:done:
#+begin_quote
Around the world, from the U.S. to Japan and Brazil to Norway, the most open-minded people experience aesthetic chills—shivers and goose bumps—when appreciating art or hearing beautiful music.
#+end_quote

** Originals - Note 62                                                         :quote:done:
#+begin_quote
Studies show that people become more creative when reminded of time they spent living in a foreign culture, and bilinguals tend to be more creative than people who speak only a single language.
#+end_quote

** Originals - Note 63                                                         :quote:done:
#+begin_quote
Less than a decade later, Carmen Medina played an indispensable role in creating a platform called Intellipedia, an internal Wikipedia for intelligence agencies to access one another’s knowledge.4 It was so radically at odds with CIA norms that, in the words of one observer, “it was like being asked to promote vegetarianism in Texas.”
#+end_quote

** Originals - Note 64                                                         :quote:done:
#+begin_quote
Power involves exercising control or authority over others; status is being respected and admired.
#+end_quote

** Originals - Note 66                                                         :quote:done:
#+begin_quote
“The way to come to power is not always to merely challenge the Establishment, but first make a place in it and then challenge and double-cross the Establishment.”
#+end_quote

** Originals - Note 67                                                         :quote:done:
#+begin_quote
Most of us assume that to be persuasive, we ought to emphasize our strengths and minimize our weaknesses. That kind of powerful communication makes sense if the audience is supportive. But when you’re pitching a novel idea or speaking up with a suggestion for change, your audience is likely to be skeptical.
#+end_quote

** Originals - Note 68                                                         :quote:done:
#+begin_quote
Investors are looking to poke holes in your arguments; managers are hunting for reasons why your suggestion won’t work. Under those circumstances, for at least four reasons, it’s actually more effective to adopt Griscom’s form of powerless communication by accentuating the flaws in your idea.12
#+end_quote

** Originals - Note 69                                                         :quote:done:
#+begin_quote
The first advantage is that leading with weaknesses disarms the audience.
#+end_quote

** Originals - Note 70                                                         :quote:done:
#+begin_quote
“Unbridled optimism comes across as salesmanship; it seems dishonest somehow, and as a consequence it’s met with skepticism.
#+end_quote

** Originals - Note 71                                                         :quote:done:
#+begin_quote
This is the second benefit of leading with the limitations of an idea: it makes you look smart.
#+end_quote

** Originals - Note 72                                                         :quote:done:
#+begin_quote
The third advantage of being up front about the downsides of your ideas is that it makes you more trustworthy.
#+end_quote

** Originals - Note 73                                                         :quote:done:
#+begin_quote
By telling them what’s wrong with the business model, I’m doing some of the work for them. It established trust,” Griscom explains. And speaking frankly about the weaknesses of the business in turn made him more credible when he talked about the strengths.
#+end_quote

** Originals - Note 74                                                         :quote:done:
#+begin_quote
We’re happier after we list three good things than twelve. Why would this be?
#+end_quote

** Originals - Note 75                                                         :quote:done:
#+begin_quote
By acknowledging its most serious problems, he made it harder for investors to generate their own ideas about what was wrong with the company.
#+end_quote

** Originals - Note 76                                                         :quote:done:
#+begin_quote
Newton’s third law can be true in human dynamics as well: every action has an equal and opposite reaction.”
#+end_quote

** Originals - Note 77                                                         :quote:done:
#+begin_quote
This explains why we often undercommunicate our ideas. They’re already so familiar to us that we underestimate how much exposure an audience needs to comprehend and buy into them.
#+end_quote

** Originals - Note 78                                                         :quote:done:
#+begin_quote
the mere exposure effect: the more often we encounter something, the more we like it.
#+end_quote

** Originals - Note 79                                                         :quote:done:
#+begin_quote
The mere exposure effect has been replicated many times—the more familiar a face, letter, number, sound, flavor, brand, or Chinese character becomes, the more we like it.23
#+end_quote

** Originals - Note 80                                                         :quote:done:
#+begin_quote
One explanation for this effect is that exposure increases the ease of processing. An unfamiliar idea requires more effort to understand. The more we see, hear, and touch it, the more comfortable we become with it, and the less threatening it is.
#+end_quote

** Originals - Note 81                                                         :quote:done:
#+begin_quote
Overall, the evidence suggests that liking continues to increase as people are exposed to an idea between ten and twenty times, with additional exposure still useful for more complex ideas. Interestingly, exposures are more effective when they’re short and mixed in with other ideas, to help maintain the audience’s curiosity.
#+end_quote

** Originals - Note 82                                                         :quote:done:
#+begin_quote
It’s also best to introduce a delay between the presentation of the idea and the evaluation of it, which provides time for it to sink in. If you’re making a suggestion to a boss, you might start with a 30-second elevator pitch during a conversation on Tuesday, revisit it briefly the following Monday, and then ask for feedback at the end of the week.
#+end_quote

** Originals - Note 83                                                         :quote:done:
#+begin_quote
Whether you’re unhappy with your job, your marriage, or your government, decades of research show that you have a choice between exit, voice, persistence, and neglect.27 Exit means removing yourself from the situation altogether: quitting a miserable job, ending an abusive marriage, or leaving an oppressive country. Voice involves actively trying to improve the situation: approaching your boss with ideas for enriching your job, encouraging your spouse to seek counseling, or becoming a political activist to elect a less corrupt government. Persistence is gritting your teeth and bearing it: working hard even though your job is stifling, sticking by your spouse, or supporting your government even though you disagree with it. Neglect entails staying in the current situation but reducing your effort: doing just enough at work not to get fired, choosing new hobbies that keep you away from your spouse, or refusing to vote.
#+end_quote

** Originals - Note 84                                                         :quote:done:
#+begin_quote
At work, our sense of commitment and control depends more on our direct boss than on anyone else.
#+end_quote

** Originals - Note 85                                                         :quote:done:
#+begin_quote
As a Google employee put it, disagreeable managers may have a bad user interface but a great operating system.
#+end_quote

** Originals - Note 86                                                         :quote:done:
#+begin_quote
Disagreeable managers are more inclined to challenge us, improving our ability to speak up effectively.
#+end_quote

** Originals - Note 87                                                         :quote:done:
#+begin_quote
“Middle-status conservatism reflects the anxiety experienced by one who aspires to a social station but fears disenfranchisement.”
#+end_quote

** Originals - Note 88                                                         :quote:done:
#+begin_quote
Middle-status conformity leads us to choose the safety of the tried-and-true over the danger of the original.
#+end_quote

** Originals - Note 90                                                         :quote:done:
#+begin_quote
To change the situation, exit and voice are the only viable alternatives.
#+end_quote

** Originals - Note 91                                                         :quote:done:
#+begin_quote
And in the long run, research shows that the mistakes we regret are not errors of commission, but errors of omission.53 If we could do things over, most of us would censor ourselves less and express our ideas more.
#+end_quote

** Originals - Note 92                                                         :quote:done:
#+begin_quote
“Never put off till tomorrow what you can do the day after tomorrow.”1 Mark Twain
#+end_quote

** Originals - Note 93                                                         :quote:done:
#+begin_quote
Parents and teachers are constantly imploring children to begin their assignments earlier instead of waiting until the last minute. In the self-help world, an entire cottage industry of resources is devoted to fighting procrastination.
#+end_quote

** Originals - Note 94                                                         :quote:done:
#+begin_quote
But surprisingly, as I’ve studied originals, I’ve learned that the advantages of acting quickly and being first are often outweighed by the disadvantages. It’s true that the early bird gets the worm, but we can’t forget that the early worm gets caught.
#+end_quote

** Originals - Note 95                                                         :quote:done:
#+begin_quote
When you procrastinate, you’re intentionally delaying work that needs to be done. You might be thinking about the task, but you postpone making real progress on it or finishing it to do something less productive. Shin proposed that when you put off a task, you buy yourself time to engage in divergent thinking rather than foreclosing on one particular idea. As a result, you consider a wider range of original concepts and ultimately choose a more novel direction. I challenged her to test it.
#+end_quote

** Originals - Note 96                                                         :quote:done:
#+begin_quote
Delaying progress enabled them to spend more time considering different ways to accomplish it, rather than “seizing and freezing” on one particular strategy.
#+end_quote

** Originals - Note 97                                                         :quote:done:
#+begin_quote
Procrastination may be the enemy of productivity, but it can be a resource for creativity. Long before the modern obsession with efficiency precipitated by the Industrial Revolution and the Protestant work ethic, civilizations recognized the benefits of procrastination. In ancient Egypt, there were two different verbs for procrastination: one denoted laziness; the other meant waiting for the right time.
#+end_quote

** Originals - Note 98                                                         :quote:done:
#+begin_quote
originality could not be rushed.
#+end_quote

** Originals - Note 99                                                         :quote:done:
#+begin_quote
He noted that people of “genius sometimes accomplish most when they work the least, for they are thinking out inventions and forming in their minds the perfect idea.”
#+end_quote

** Originals - Note 100                                                        :quote:done:
#+begin_quote
“Often when I am procrastinating, I really have something on the back burner and I need the time to work it through.”
#+end_quote

** Originals - Note 101                                                        :quote:done:
#+begin_quote
Zeigarnik effect.11 In 1927, Russian psychologist Bluma Zeigarnik demonstrated that people have a better memory for incomplete than complete tasks. Once a task is finished, we stop thinking about it. But when it is interrupted and left undone, it stays active in our minds.
#+end_quote

** Originals - Note 102                                                        :quote:done:
#+begin_quote
Half a century after King delivered his momentous speech, four words are etched into the stone tablets of our collective memory: “I have a dream.” It remains one of the most recognizable phrases in the history of human rhetoric, as it painted a vivid portrait of a better future. But I was stunned to find that the “dream” idea was not written into the speech at all. It didn’t appear in the draft by Jones, nor did King include it in his script.
#+end_quote

** Originals - Note 103                                                        :quote:done:
#+begin_quote
After being involved in starting over one hundred companies, Idealab founder Bill Gross ran an analysis to figure out what drove success versus failure. The most important factor was not the uniqueness of the idea, the capabilities and execution of the team, the quality of the business model, or the availability of funding. “The number one thing was timing,” Gross reveals.19 “Timing accounted for forty-two percent of the difference between success and failure.”
#+end_quote

** Originals - Note 104                                                        :quote:done:
#+begin_quote
Being original doesn’t require being first. It just means being different and better.
#+end_quote

** Originals - Note 105                                                        :quote:done:
#+begin_quote
“Wouldn’t you rather be second or third and see how the guy in first did, and then … improve it?” Malcolm Gladwell asked in an interview.25 “When ideas get really complicated, and when the world gets complicated, it’s foolish to think the person who’s first can work it all out,” Gladwell remarked. “Most good things, it takes a long time to figure them out.”
#+end_quote

** Originals - Note 106                                                        :quote:done:
#+begin_quote
As physicist Max Planck once observed, “A new scientific truth does not triumph by convincing its opponents and making them see the light, but rather because its opponents eventually die.”
#+end_quote

** Originals - Note 107                                                        :quote:done:
#+begin_quote
The time at which we reach our heights of originality, and how long they last, depends on our styles of thinking. When Galenson studied creators, he discovered two radically different styles of innovation: conceptual and experimental. Conceptual innovators formulate a big idea and set out to execute it. Experimental innovators solve problems through trial and error, learning and evolving as they go along.
#+end_quote

** Originals - Note 108                                                        :quote:done:
#+begin_quote
According to Galenson, conceptual innovators are sprinters, and experimental innovators are marathoners.
#+end_quote

** Originals - Note 110                                                        :quote:done:
#+begin_quote
Conceptual innovators tend to generate original ideas early but risk copying themselves. The experimental approach takes longer, but proves more renewable: instead of reproducing our past ideas, experiments enable us to continue discovering new ones.
#+end_quote

** Originals - Note 111                                                        :quote:done:
#+begin_quote
If you’re feeling pressured to start working on a creative task when you’re wide awake, it might be worth delaying it until you’re a little sleepier.
#+end_quote

** Originals - Note 112                                                        :quote:done:
#+begin_quote
The originals who start a movement will often be its most radical members, whose ideas and ideals will prove too hot for those who follow their lead.
#+end_quote

** Originals - Note 113                                                        :quote:done:
#+begin_quote
We assume that common goals bind groups together, but the reality is that they often drive groups apart. According to Dartmouth psychologist Judith White, a lens for understanding these fractures is the concept of horizontal hostility.4 Even though they share a fundamental objective, radical groups often disparage more mainstream groups as impostors and sellouts.
#+end_quote

** Originals - Note 115                                                        :quote:done:
#+begin_quote
The more strongly you identify with an extreme group, the harder you seek to differentiate yourself from more moderate groups that threaten your values.
#+end_quote

** Originals - Note 116                                                        :quote:done:
#+begin_quote
In seeking alliances with groups that share our values, we overlook the importance of sharing our strategic tactics.7
#+end_quote

** Originals - Note 117                                                        :quote:done:
#+begin_quote
They found that shared tactics were an important predictor of alliances. Even if they care about different causes, groups find affinity when they use the same methods of engagement.
#+end_quote

** Originals - Note 118                                                        :quote:done:
#+begin_quote
challenging the status quo: overcoming the skepticism of potential key stakeholders.
#+end_quote

** Originals - Note 119                                                        :quote:done:
#+begin_quote
Shifting the focus from why to how can help people become less radical.
#+end_quote

** Originals - Note 120                                                        :quote:done:
#+begin_quote
foot-in-the-door technique, where you lead with a small request to secure an initial commitment before revealing the larger one.
#+end_quote

** Originals - Note 121                                                        :quote:done:
#+begin_quote
“Keep your friends close, but your enemies closer.”
#+end_quote

** Originals - Note 122                                                        :quote:done:
#+begin_quote
Negative relationships are unpleasant, but they’re predictable: if a colleague consistently undermines you, you can keep your distance and expect the worst. But when you’re dealing with an ambivalent relationship, you’re constantly on guard,
#+end_quote

** Originals - Note 123                                                        :quote:done:
#+begin_quote
Our instinct is to sever our bad relationships and salvage the ambivalent ones. But the evidence suggests we ought to do the opposite: cut our frenemies and attempt to convert our enemies.
#+end_quote

** Originals - Note 124                                                        :quote:done:
#+begin_quote
According to Berg, the starting point in generating ideas is like the first brushstroke that a painter lays down on a canvas: it shapes the path for the rest of the painting, constraining what we imagine.
#+end_quote

** Originals - Note 125                                                        :quote:done:
#+begin_quote
To come up with something original, we need to begin from a more unfamiliar place.
#+end_quote

** Originals - Note 126                                                        :quote:done:
#+begin_quote
The most promising ideas begin from novelty and then add familiarity,
#+end_quote

** Originals - Note 127                                                        :quote:done:
#+begin_quote
we need to think differently about values. Instead of assuming that others share our principles, or trying to convince them to adopt ours, we ought to present our values as a means of pursuing theirs. It’s hard to change other people’s ideals. It’s much easier to link our agendas to familiar values that people already hold.
#+end_quote

** Originals - Note 128                                                        :quote:done:
#+begin_quote
For movement leaders to “succeed in organizing potential recruits, they must strike the appropriate balance between resonating with the existing cultural repertoire and challenging the status quo.”
#+end_quote

** Originals - Note 129                                                        :quote:done:
#+begin_quote
Years ago, when studying the conflict between Israel and Palestine, Harvard psychologist Herbert Kelman observed that conflicts between two groups are often caused and intensified by conflicts within the groups.
#+end_quote

** Originals - Note 130                                                        :quote:done:
#+begin_quote
When their methods are pretty much the same, groups simply have less to learn and gain from one another; their efforts are more likely to be redundant.
#+end_quote

** Originals - Note 131                                                        :quote:done:
#+begin_quote
Progress always involves risk.
#+end_quote

** Originals - Note 132                                                        :quote:done:
#+begin_quote
Across twenty-four different studies of more than eight thousand people, laterborns were 1.48 times more likely to participate in sports with high injury rates, such as football, rugby, boxing, ice hockey, gymnastics, scuba diving, downhill skiing and ski jumping, bobsledding, and auto racing. Firstborns preferred safer sports: baseball, golf, tennis, track, cycling, and crew.
#+end_quote

** Originals - Note 133                                                        :quote:done:
#+begin_quote
According to eminent Stanford professor James March, when many of us make decisions, we follow a logic of consequence: Which course of action will produce the best result? If you’re like Robinson, and you consistently challenge the status quo, you operate differently, using instead a logic of appropriateness: What does a person like me do in a situation like this?
#+end_quote

** Originals - Note 134                                                        :quote:done:
#+begin_quote
Rather than looking outward in an attempt to predict the outcome, you turn inward to your identity.14 You base the decision on who you are—or who you want to be.
#+end_quote

** Originals - Note 135                                                        :quote:done:
#+begin_quote
For years, experts have touted the advantages of being firstborn.15 The eldest child in the family is typically set up for success, benefiting from the undivided attention, time, and energy of fawning parents. Evidence shows that firstborns are more likely to win the Nobel Prize in science, become U.S. congressmen, and win local and national elections in the Netherlands. It also appears that they’re most likely to rise to the top of corporations: one analysis of more than 1,500 CEOs revealed that 43 percent were firstborn.
#+end_quote

** Originals - Note 136                                                        :quote:done:
#+begin_quote
although firstborns tend to be more dominant, conscientious, and ambitious, laterborns are more open to taking risks and embracing original ideas. Firstborns tend to defend the status quo; laterborns are inclined to challenge it.
#+end_quote

** Originals - Note 137                                                        :quote:done:
#+begin_quote
This concept has its roots in the work of the physician and psychotherapist Alfred Adler, who came to believe that Sigmund Freud’s emphasis on parenting failed to account for the critical influence of siblings on personality development. Adler argued that because firstborn children start life as only children, they initially identify with their parents. When a younger sibling arrives, firstborns risk being “dethroned” and often respond by emulating their parents: they enforce rules and assert their authority over the younger sibling, which sets the stage for the younger child to rebel.
#+end_quote

** Originals - Note 138                                                        :quote:done:
#+begin_quote
As hard as they may try to be consistent, parents treat children differently based on birth order, which wedges their personalities even further apart.
#+end_quote

** Originals - Note 139                                                        :quote:done:
#+begin_quote
Psychologist Robert Zajonc observed that firstborns grow up in a world of adults, while the more older siblings you have, the more time you spend learning from other children.
#+end_quote

** Originals - Note 140                                                        :quote:done:
#+begin_quote
When older siblings serve as surrogate parents and role models, you don’t face as many rules or punishments, and you enjoy the security of their protection. You also end up taking risks earlier: instead of emulating the measured, carefully considered choices of adults, you follow the lead of other children.
#+end_quote

** Originals - Note 141                                                        :quote:done:
#+begin_quote
Years ago, researchers found that from ages two to ten, children are urged by their parents to change their behavior once every six to nine minutes.
#+end_quote

** Originals - Note 142                                                        :quote:done:
#+begin_quote
This rational approach to discipline also characterizes the parents of teenagers who don’t engage in criminal deviance and originals who challenge the orthodoxies of their professions. In one study, parents of ordinary children had an average of six rules, like specific schedules for homework and bedtime. Parents of highly creative children had an average of less than one rule and tended to “place emphasis on moral values, rather than on specific rules,” psychologist Teresa Amabile reports.
#+end_quote

** Originals - Note 143                                                        :quote:done:
#+begin_quote
When mothers enforce many rules but offer a clear rationale for why they’re important, teenagers are substantially less likely to break them, because they internalize them.
#+end_quote

** Originals - Note 144                                                        :quote:done:
#+begin_quote
Reasoning does create a paradox: it leads both to more rule following and more rebelliousness. By explaining moral principles, parents encourage their children to comply voluntarily with rules that align with important values and to question rules that don’t.
#+end_quote

** Originals - Note 146                                                        :quote:done:
#+begin_quote
the rescuers’ parents encouraged their children to consider the impact of their actions on others.
#+end_quote

** Originals - Note 147                                                        :quote:done:
#+begin_quote
The dual moral emotions of empathy and guilt activate the desire to right wrongs of the past and behave better in the future.
#+end_quote

** Originals - Note 148                                                        :quote:done:
#+begin_quote
When our character is praised, we internalize it as part of our identities. Instead of seeing ourselves as engaging in isolated moral acts, we start to develop a more unified self-concept as a moral person.
#+end_quote

** Originals - Note 149                                                        :quote:done:
#+begin_quote
In an ingenious series of experiments led by psychologist Christopher Bryan, children between ages three and six were 22 percent to 29 percent more likely to clean up blocks, toys, and crayons when they were asked to be helpers instead of to help. Even though their character was far from gelled, they wanted to earn the identity.
#+end_quote

** Originals - Note 150                                                        :quote:done:
#+begin_quote
When you’re urged not to cheat, you can do it and still see an ethical person in the mirror. But when you’re told not to be a cheater, the act casts a shadow; immorality is tied to your identity, making the behavior much less attractive. Cheating is an isolated action that gets evaluated with the logic of consequence: Can I get away with it? Being a cheater evokes a sense of self, triggering the logic of appropriateness: What kind of person am I, and who do I want to be?
#+end_quote

** Originals - Note 151                                                        :quote:done:
#+begin_quote
“Don’t Be a Drunk Driver.”
#+end_quote

** Originals - Note 152                                                        :quote:done:
#+begin_quote
When we shift our emphasis from behavior to character, people evaluate choices differently. Instead of asking whether this behavior will achieve the results they want, they take action because it is the right thing to do.
#+end_quote

** Originals - Note 153                                                        :quote:done:
#+begin_quote
“It’s like saving somebody who is drowning. You don’t ask them what God they pray to. You just go and save them.”
#+end_quote

** Originals - Note 154                                                        :quote:done:
#+begin_quote
Role models have a foundational impact on how children grow up to express their originality.
#+end_quote

** Originals - Note 155                                                        :quote:done:
#+begin_quote
Children’s books reflected the values popular at the time, but also helped to nurture those values: When stories emphasized original achievement, patent rates typically soared twenty to forty years later.
#+end_quote

** Originals - Note 156                                                        :quote:done:
#+begin_quote
When children identify strongly enough with heroes who exemplify originality, it might even change the way that niche picking unfolds. Among siblings, laterborns often become original after their siblings fill conventional niches. But wherever we fall in the birth order, when we have compelling role models for originality, they expand our awareness of niches that we had never considered. Instead of causing us to rebel because traditional avenues are closed, the protagonists in our favorite stories may inspire originality by opening our minds to unconventional paths.
#+end_quote

** Originals - Note 157                                                        :quote:done:
#+begin_quote
Groupthink is the enemy of originality; people feel pressured to conform to the dominant, default views instead of championing diversity of thought.
#+end_quote

** Originals - Note 158                                                        :quote:done:
#+begin_quote
Across industries, there were three dominant templates: professional, star, and commitment. The professional blueprint emphasized hiring candidates with specific skills: Founders looked for engineers who could code in JavaScript or C++, or scientists who had deep knowledge about synthesizing proteins. In the star blueprint, the focus shifted from current skills to future potential, placing a premium on choosing or poaching the brightest hires. The individuals in question might have less current expertise in a particular area, but they had the raw brainpower to acquire it. Founders with a commitment blueprint went about hiring differently. Skills and potential were fine, but cultural fit was a must. The top priority was to employ people who matched the company’s values and norms. The commitment blueprint involved a unique approach to motivation, too. Whereas founders with professional and star blueprints gave employees autonomy and challenging tasks, those with commitment blueprints worked to build strong emotional bonds among employees and to the organization. They often used words like family and love to describe the companionship in the organization, and employees tended to be intensely passionate about the mission.
#+end_quote

** Originals - Note 159                                                        :quote:done:
#+begin_quote
Skills and stars are fleeting; commitment lasts.
#+end_quote

** Originals - Note 160                                                        :quote:done:
#+begin_quote
But in volatile settings like the computer, aerospace, and airline industries, the benefits of strong cultures disappear. Once a market becomes dynamic, big companies with strong cultures are too insular: They have a harder time recognizing the need for change, and they’re more likely to resist the insights of those who think differently. As a result, they don’t learn and adapt, and don’t have better or more reliable financial results than their competitors.
#+end_quote

** Originals - Note 161                                                        :quote:done:
#+begin_quote
In a study by strategy researchers Michael McDonald and James Westphal, the worse companies performed, the more CEOs sought advice from friends and colleagues who shared their perspectives.
#+end_quote

** Originals - Note 162                                                        :quote:done:
#+begin_quote
Dissenting opinions are useful even when they’re wrong.
#+end_quote

** Originals - Note 163                                                        :quote:done:
#+begin_quote
In the investment world, you can only make money if you think different from everyone else. Bridgewater has prevented groupthink by inviting dissenting opinions from every employee in the company.
#+end_quote

** Originals - Note 164                                                        :quote:done:
#+begin_quote
As Jack Handey advised in one of his “Deep Thoughts” on Saturday Night Live, before you criticize people, you should walk a mile in their shoes.15 That way, when you criticize them, you’re a mile away and you have their shoes.
#+end_quote

** Originals - Note 165                                                        :quote:done:
#+begin_quote
“Don’t let ‘loyalty’ stand in the way of truth and openness,”
#+end_quote

** Originals - Note 166                                                        :quote:done:
#+begin_quote
“No one has the right to hold a critical opinion without speaking up about it.”
#+end_quote

** Originals - Note 167                                                        :quote:done:
#+begin_quote
This is what separates Bridgewater’s strong culture from a cult: The commitment is to promoting dissent. In hiring, instead of using similarity to gauge cultural fit, Bridgewater assesses cultural contribution.
#+end_quote

** Originals - Note 168                                                        :quote:done:
#+begin_quote
devil’s advocate. Half a millennium later, this is effectively what most leaders do to foster dissent: bring in someone to oppose the majority.
#+end_quote

** Originals - Note 169                                                        :quote:done:
#+begin_quote
Confirmation bias: When you have a preference, you seek out information supporting it, while overlooking information that challenges it.
#+end_quote

** Originals - Note 170                                                        :quote:done:
#+begin_quote
The secret to success is sincerity, the old saying goes: Once you can fake that, you’ve got it made. In fact, it’s not easy to fake sincerity.
#+end_quote

** Originals - Note 171                                                        :quote:done:
#+begin_quote
“The greatest tragedy of mankind,” Dalio says, “comes from the inability of people to have thoughtful disagreement to find out what’s true.”
#+end_quote

** Originals - Note 172                                                        :quote:done:
#+begin_quote
If you’re always expected to have an answer ready, you’ll arrive at meetings with your diagnosis complete, missing out on the chance to learn from a broad range of perspectives.
#+end_quote

** Originals - Note 173                                                        :quote:done:
#+begin_quote
“Argue like you’re right and listen like you’re wrong.”
#+end_quote

** Originals - Note 174                                                        :quote:done:
#+begin_quote
In most organizations, the socialization period is passive: We’re busy learning the ropes and familiarizing ourselves with the culture. By the time we’re up to speed, we’re already swamped with work and beginning to see the world in the company way. The early period is the perfect time for employees to pay attention to opportunities to improve the culture.
#+end_quote

** Originals - Note 175                                                        :quote:done:
#+begin_quote
“You gain believability by other believable people saying you’re believable.”
#+end_quote

** Originals - Note 176                                                        :quote:done:
#+begin_quote
“Shapers” are independent thinkers: curious, non-conforming, and rebellious. They practice brutal, nonhierarchical honesty. And they act in the face of risk, because their fear of not succeeding exceeds their fear of failing.
#+end_quote

** Originals - Note 177                                                        :quote:done:
#+begin_quote
“I learned that courage was not the absence of fear, but the triumph over it…. The brave man is not he who does not feel afraid, but he who conquers that fear.”1 Nelson Mandela
#+end_quote

** Originals - Note 178                                                        :quote:done:
#+begin_quote
His sports scientist coined a term for it, “anticipatory thermogenesis,” and it appears to be the fruit of decades of Pavlovian conditioning: When it’s time to plunge into frosty waters, his body automatically prepares. Pugh calls it the art of self-heating. But unlike many world-class athletes, he does not consider it his mission simply to be the best in the world or to prove what’s possible. He is an ocean advocate, an environmentalist who swims to raise awareness about climate change.
#+end_quote

** Originals - Note 179                                                        :quote:done:
#+begin_quote
Those who aced the emotion regulation test spoke up more often with ideas and suggestions to challenge the status quo—and their managers rated them as more effective in doing so. They marshaled the courage to rock the boat and mastered the techniques for keeping it steady.
#+end_quote

** Originals - Note 180                                                        :quote:done:
#+begin_quote
“Defensive pessimism is a strategy used in specific situations to manage anxiety, fear, and worry,” Norem explains. When self-doubts creep in, defensive pessimists don’t allow themselves to be crippled by fear. They deliberately imagine a disaster scenario to intensify their anxiety and convert it into motivation.
#+end_quote

** Originals - Note 181                                                        :quote:done:
#+begin_quote
If we want to understand how to manage fear, we don’t have to threaten people’s lives; we need only threaten to put them on stage.
#+end_quote

** Originals - Note 182                                                        :quote:done:
#+begin_quote
To overcome fear, why does getting excited work better than trying to calm yourself down? Fear is an intense emotion: You can feel your heart pumping and your blood coursing. In that state, trying to relax is like slamming on the brakes when a car is going 80 miles per hour. The vehicle still has momentum. Rather than trying to suppress a strong emotion, it’s easier to convert it into a different emotion—one that’s equally intense, but propels us to step on the gas.
#+end_quote

** Originals - Note 183                                                        :quote:done:
#+begin_quote
The tour guide, Srdja Popovic, had trained them all. Popovic was one of the masterminds behind Otpor!, the grassroots youth nonviolence movement that overthrew Milosevic. A decade earlier, he had suffered through ethnic cleansing and martial law, and gaped in horror as his mother’s building was bombed. He was arrested, jailed, and beaten; his life flashed before his eyes when an officer of the law jammed a pistol into his mouth.
#+end_quote

** Originals - Note 184                                                        :quote:done:
#+begin_quote
After working with friends to lead the movement that toppled Milosevic and brought democracy to Serbia, Popovic dedicated his life to preparing activists to lead nonviolent revolutions. In 2010, the fifteen foreigners he trained a year earlier used his methods to overthrow the Egyptian dictator.
#+end_quote

** Originals - Note 185                                                        :quote:done:
#+begin_quote
But just because it’s your idea doesn’t mean you’re the best person to activate the go system. In a series of experiments, Dave Hofmann and I found that the most inspiring way to convey a vision is to outsource it to the people who are actually affected by it.
#+end_quote

** Originals - Note 186                                                        :quote:done:
#+begin_quote
I found that people are inspired to achieve the highest performance when leaders describe a vision and then invite a customer to bring it to life with a personal story.
#+end_quote

** Originals - Note 187                                                        :quote:done:
#+begin_quote
“Bringing the customer into the room connected them to the mission, and reached their hearts and minds,” Silverman says. “It helped employees see what a difference we could make in the world.”
#+end_quote

** Originals - Note 188                                                        :quote:done:
#+begin_quote
So, instead of appointing a leader to activate the go system, Popovic outsourced inspiration to a symbol: a black clenched fist. The effort began in the fall of 1998, when Popovic and his friends were college students. They spray painted three hundred clenched fists around the town square and plastered stickers of the image throughout buildings in Belgrade. Without that fist, he says, the revolution would never have happened.
#+end_quote

** Originals - Note 189                                                        :quote:done:
#+begin_quote
In the words of Margaret Mead, “Never doubt that a small group of thoughtful citizens can change the world; indeed, it’s the only thing that ever has.”
#+end_quote

** Originals - Note 190                                                        :quote:done:
#+begin_quote
When Popovic trained the Egyptian activists, he shared a story from 1983 of how Chilean miners had mounted a protest against the country’s dictator, Pinochet. Instead of taking the risk of going on strike, they issued a nationwide call for citizens to demonstrate their resistance by turning their lights on and off. People weren’t afraid to do that, and soon they saw that their neighbors weren’t, either. The miners also invited people to start driving slowly. Taxi drivers slowed down; so did bus drivers. Soon, pedestrians were walking in slow motion down the streets and driving their cars and trucks at a glacial pace.
#+end_quote

** Originals - Note 192                                                        :quote:done:
#+begin_quote
In his workshops, Popovic trains revolutionaries to use humor as a weapon against fear. Not long after he spent some time with the Egyptian activists, an image began to spread around Egypt—a parody of a Microsoft Windows program installation:
#+end_quote

** Originals - Note 193                                                        :quote:done:
#+begin_quote
Research demonstrates that when we’re angry at others, we aim for retaliation or revenge. But when we’re angry for others, we seek out justice and a better system. We don’t just want to punish; we want to help.
#+end_quote

** Originals - Note 196                                                        :quote:done:
#+begin_quote
Make your ideas more familiar. Repeat yourself—it makes people more comfortable with an unconventional idea.
#+end_quote

** Originals - Note 197                                                        :quote:done:
#+begin_quote
If your idea is extreme, couch it in a more conventional goal. That way, instead of changing people’s minds, you can appeal to values or beliefs that they already hold.
#+end_quote

** Originals - Note 199                                                        :quote:done:
#+begin_quote
Shift from exit interviews to entry interviews. Instead of waiting to ask for ideas until employees are on their way out the door, start seeking their insights when they first arrive. By sitting down with new hires during onboarding, you can help them feel valued and gather novel suggestions along the way. Ask what brought them in the door and what would keep them at the firm, and challenge them to think like culture detectives.
#+end_quote
