:PROPERTIES:
:ID:       31953769-76a0-4099-8a75-c85b7569b668
:END:
#+title: Range
#+filetags: book
#+date: 2020-12-01

* Range
:PROPERTIES:
:FINISHED: 2020-12
:END:
* Description
** Why we need more Rogers by Bill Gates
** Further reading:
*** InnoCentive
#+begin_quote
*InnoCentive is the global pioneer in crowdsourced innovation. We help innovative organizations solve their important technology, science, business, A/I and data challenges by connecting them with a global network of expert problem solvers.
#+end_quote
** Interesting people
*** Arturo Casadevall
* Quotes
** Range - Note 1                                                              :quote:done:
#+begin_quote
"There are so many layers of thinking", he said. "We humans sort of suck at all of them individually, but we have some kind of very approximate idea about each of them and can combine them and be somewhat adaptive. That seems to be what the trick is."
#+end_quote

** Range - Note 2                                                              :quote:done:
#+begin_quote
That is, the more contexts in which something is learned, the more the learner creates abstract models, and the less they rely on any particular example. Learners become better at applying their knowledge to a situation they've never seen before, which is the essence of creativity.
#+end_quote

** Range - Note 3                                                              :quote:done:
#+begin_quote
Ibarra concluded that we maximize match quality throughout life by sampling activities, social groups, contexts, jobs, careers, and then reflecting and adjusting our personal narratives. And repeat.
#+end_quote

** Range - Note 4                                                              :quote:done:
#+begin_quote
We discover the possibilities by doing, by trying new activities, building new networks, finding new role models. We learn who we are in practice, not in theory.
#+end_quote

** Range - Note 5                                                              :quote:done:
#+begin_quote
[...] we need both focused frogs and visionary birds. "Birds fly high in the air and survey broad vistas of mathematics out to the far horizon" [...] They delight in concepts that unify our thinking and bring together diverse problems from different parts of the landscape. Frogs live in the mud below and see only the flowers that grow nearby. They delight in the details of particular objects, and they solve problems one at a time." (Freeman Dyson)
#+end_quote

** Range - Note 6                                                              :quote:done:
#+begin_quote
Facing uncertain environments and wicked problems, breadth of experience is invaluable. Facing kind problems, narrow specialization can be remarkably efficient. The problem is what we often expect the hyperspecialist, because of their expertise in a narrow area, to magically be able to extend their skill to wicked problems. The results can be disastrous.
#+end_quote

** Range - Note 7                                                              :quote:done:
#+begin_quote
In God we trust, all others bring data (NASA)
#+end_quote

** Range - Note 8                                                              :quote:done:
#+begin_quote
So ever since I was a postdoc, I would go into a different subject every 5 years or so... I don't want to carry on studying the same thing from cradle to grave. Sometimes I joke that I am not interested in doing re-search, only search.
#+end_quote

** Range - Note 9                                                              :quote:done:
#+begin_quote
You have people walking around with all the knowledge of humanity on their phone, but they have no idea how to integrate it. We don't train people in thinking or reasoning.
#+end_quote

** Range - Note 10                                                             :quote:done:
#+begin_quote
"When you push the boundaries, a lot of it is just probing. It has to be inefficient," Casadevall told me. "What's gone totally is that time to talk and synthetize. People grab lunch and bring it into their offices. They feel lunch is inefficient, but often that's the best time to bounce ideas and make connections."
#+end_quote
