:PROPERTIES:
:ID:       719c0dec-bba6-4cac-b4c5-9b63601ed1cc
:END:
#+title: Reich werden und bleiben: Ihr Wegweiser zur finanziellen Freiheit
#+filetags: :finance:book:
#+date: 2016-03-01

* Reich werden und bleiben: Ihr Wegweiser zur finanziellen Freiheit
  :PROPERTIES:
  :FINISHED: 2016-03
  :END:
** Description
#+begin_quote
Investoren und Unternehmer, Millionäre und Milliardäre haben dieses Buch gelesen und bestätigen: Hier wird ein erprobter Weg gezeigt, wie Sie reich werden – und auch dauerhaft - bleiben! Es ist das erste Buch, das die aktuellen Ergebnisse der Reichtumsforschung aus Deutschland und Amerika einem breiteren Publikum präsentiert. Rainer Zitelmann zeigt außerdem, welche Anlegerfallen und Berater Sie meiden müssen, wie Risiken begrenzt werden können und wie sich Geld durch kluge Investitionen vermehren lässt, um Ihre finanzielle Freiheit nicht nur zu erreichen, sondern auch zu sichern. (Quelle: https://www.goodreads.com/book/show/25782016-reich-werden-und-bleiben)
#+end_quote
* Quotes
** Reich werden und bleiben: Ihr Wegweiser zur finanziellen Freiheit - Note 3  :quote:done:
#+begin_quote
Ungesundes Verhalten ist insgesamt teurer als gesundes.«
#+end_quote

** Reich werden und bleiben: Ihr Wegweiser zur finanziellen Freiheit - Note 5  :quote:done:
#+begin_quote
Entscheidend ist in der Tat nicht, wie viel Geld Sie zu einem bestimmten Zeitpunkt haben, sondern wie Sie damit umgehen.
#+end_quote

** Reich werden und bleiben: Ihr Wegweiser zur finanziellen Freiheit - Note 6  :quote:done:
#+begin_quote
sie verband mit Reichtum nicht den Erwerb teurer Konsumgüter, sondern die finanzielle Unabhängigkeit.
#+end_quote

** Reich werden und bleiben: Ihr Wegweiser zur finanziellen Freiheit - Note 7  :quote:done:
#+begin_quote
Das durchschnittliche Jahreseinkommen eines Bundesbürgers betrug 2014 brutto 41.000 Euro. Das entspricht nach Steuern und Sozialabgaben einem Nettoeinkommen von 24.000 Euro im Jahr bzw. 2000 Euro im Monat.
#+end_quote

** Reich werden und bleiben: Ihr Wegweiser zur finanziellen Freiheit - Note 8  :quote:done:
#+begin_quote
Das heißt, man muss schon 800.000 Euro »auf der hohen Kante« haben, um wenigstens so davon leben zu können wie der Durchschnittsbürger – vorausgesetzt, man tastet das Vermögen nicht an.
#+end_quote

** Reich werden und bleiben: Ihr Wegweiser zur finanziellen Freiheit - Note 9  :quote:done:
#+begin_quote
Millionaires next Door: Das sind Personen mit einem Nettovermögen zwischen 1 und 5 Millionen Dollar. Davon gibt es weltweit 12,4 Millionen. •Mid-Tier Millionaires: Personen mit einem Nettovermögen zwischen 5 und 30 Millionen Dollar. Davon gibt es weltweit 1,2 Millionen. •Ultra-HNWIs (Ultra-High-Net-Worth-Individuals): Personen mit einem Nettovermögen, das größer als 30 Millionen Dollar ist. Davon gibt es weltweit 128.000.31
#+end_quote

** Reich werden und bleiben: Ihr Wegweiser zur finanziellen Freiheit - Note 10 :quote:done:
#+begin_quote
Um Karriere als Angestellter zu machen, muss man also in höherem Maße als der Durchschnitt anpassungsfähig und sozial verträglich sein, während für Unternehmer die Konfliktfähigkeit die wichtigere Eigenschaft
#+end_quote

** Reich werden und bleiben: Ihr Wegweiser zur finanziellen Freiheit - Note 11 :quote:done:
#+begin_quote
Hohe Werte für Fleiß, Gewissenhaftigkeit, Extraversion und Offenheit gegenüber Neuem deuteten auf eine unternehmerische Persönlichkeit hin, während hohe Werte für Verträglichkeit und psychische Labilität Persönlichkeitsmerkmale sind, die dem Unternehmertum entgegenstehen.
#+end_quote

** Reich werden und bleiben: Ihr Wegweiser zur finanziellen Freiheit - Note 12 :quote:done:
#+begin_quote
Die Industrie- und Handelskammern haben im Rahmen ihrer Gründerberatungen statistische Erhebungen darüber angestellt, was die hauptsächlichen Defizite der Existenzgründer waren.75 54 Prozent der Existenzgründer hatten kaufmännische Defizite, 52 Prozent hatten sich zu wenige Gedanken über die Alleinstellungsmerkmale ihrer Geschäftsidee gemacht. 45 Prozent verfügten nur über unklare Vorstellungen ihrer Kundenzielgruppe. 44 Prozent schätzten die Startinvestitionen zu niedrig ein, und 42 Prozent hatten die Finanzierung generell nicht gründlich durchdacht. Mehr als jeder Dritte war nicht einmal in der Lage, seine Produktidee klar zu beschreiben.
#+end_quote

** Reich werden und bleiben: Ihr Wegweiser zur finanziellen Freiheit - Note 13 :quote:done:
#+begin_quote
»Es ist die Qualität der Idee, die den Ausschlag gibt«, betont Faltin immer wieder.77 Bedingung für den Erfolg als Existenzgründer sei, dass man das Vorhaben so lange durchdenke, bis man auf eine bessere, möglichst sogar sehr viel bessere Lösung stoße als diejenigen, die am Markt bereits vorhanden seien.78
#+end_quote

** Reich werden und bleiben: Ihr Wegweiser zur finanziellen Freiheit - Note 14 :quote:done:
#+begin_quote
Er muss sich einen Vorsprung vor Imitatoren sichern.
#+end_quote

** Reich werden und bleiben: Ihr Wegweiser zur finanziellen Freiheit - Note 15 :quote:done:
#+begin_quote
Das Marketing muss integraler Bestandteil des Designs sein.
#+end_quote

** Reich werden und bleiben: Ihr Wegweiser zur finanziellen Freiheit - Note 16 :quote:done:
#+begin_quote
Lernen Sie von den Erfahrungen der vielen Selbstständigen, die gescheitert sind.
#+end_quote

** Reich werden und bleiben: Ihr Wegweiser zur finanziellen Freiheit - Note 17 :quote:done:
#+begin_quote
Sie werden in keinem Lebensbereich Erfolg haben und haben nur eine geringe Chance, reich zu werden, wenn Sie nicht lernen, zu verkaufen. Weil diese Fähigkeit wichtiger ist als alle anderen, widme ich ihr ein eigenes Kapitel.
#+end_quote

** Reich werden und bleiben: Ihr Wegweiser zur finanziellen Freiheit - Note 18 :quote:done:
#+begin_quote
»Obwohl wir gelernt haben, dass Talent sich durchsetzt, ist es in Wahrheit die Sichtbarkeit, die letztlich siegt. Talent und Fähigkeit sind wichtig, aber nur Sichtbarkeit kann den Unterschied erklären zwischen einer Person, die gefragt ist und gut verdient, und einer anderen ebenso qualifizierten Person, die gerade mal so über die Runden kommt.«
#+end_quote

** Reich werden und bleiben: Ihr Wegweiser zur finanziellen Freiheit - Note 19 :quote:done:
#+begin_quote
Die Forscher fanden heraus, dass Sparsamkeit und nicht etwa ein hoher Verdienst der entscheidende Grund für den Reichtum der meisten Millionäre ist. Sie bildeten zwei Gruppen unter den sehr gut verdienenden Menschen, die aber ein völlig entgegengesetztes Konsumverhalten haben: die PAW (Prodigious Accumulator of Wealth) sowie die UAW (Under Accumulator of Wealth).
#+end_quote

** Reich werden und bleiben: Ihr Wegweiser zur finanziellen Freiheit - Note 20 :quote:done:
#+begin_quote
Als Faustformel, die zeigt, welcher Gruppe man angehört, nennt Stanley: 10 Prozent des Lebensalters x dem Jahreseinkommen = das erwartete Nettovermögen. Eine Person, die 58 Jahre alt ist und 100.000 Euro im Jahr verdient, sollte demnach über ein Nettovermögen von 580.000 Euro verfügen.117
#+end_quote

** Reich werden und bleiben: Ihr Wegweiser zur finanziellen Freiheit - Note 21 :quote:done:
#+begin_quote
Ich möchte ein wichtiges Ergebnis schon hier vorwegnehmen: Gründen Sie Ihr Sparprogramm vor allem auf zwei Säulen, auf Immobilien und auf Aktien. Der »Nachteil« von Immobilien, dass man sie nicht so rasch verkaufen kann wie z. B. Aktien, wird für Sie zum Vorteil, weil er Ihnen hilft, diszipliniert Vermögen aufzubauen. Und der »Nachteil« von Aktien, dass diese nämlich – oft erheblichen – Wertschwankungen unterliegen, muss Sie bei einem langfristig angelegten Plan zum Vermögensaufbau nicht stören.
#+end_quote

** Reich werden und bleiben: Ihr Wegweiser zur finanziellen Freiheit - Note 22 :quote:done:
#+begin_quote
Mein zweiter Ratschlag, um Ihre Sparquote zu erhöhen: Verwenden Sie 50 Prozent von jeder Erhöhung Ihres Einkommens oder – falls Sie selbstständig sind – von Ihrem Gewinn für langfristige Anlagen.
#+end_quote

** Reich werden und bleiben: Ihr Wegweiser zur finanziellen Freiheit - Note 23 :quote:done:
#+begin_quote
Heute bieten manche Banken und Vermögensverwalter auch Honorarberatung an, bei der die Berater nicht von der Vereinnahmung der Provisionen leben. Für den Kunden ist das sehr viel transparenter. Die Interessenkonflikte, die bei einer provisionsbasierten Beratung entstehen, werden weitgehend vermieden. Doch die Honorarberatung wird bislang nur von wenigen Kunden in Anspruch genommen. Und auch wenn hier die Gefahr der Interessenkollisionen geringer ist, so ist damit natürlich noch nicht gewährleistet, dass der Berater tatsächlich einen Mehrwert für den Kunden bringt.
#+end_quote

** Reich werden und bleiben: Ihr Wegweiser zur finanziellen Freiheit - Note 24 :quote:done:
#+begin_quote
Deshalb mögen Banken Immobilien nur, um dem Kunden eine Finanzierung zu verkaufen. Ansonsten handelt es sich aus ihrer Sicht um »totes Kapital«, das viel zu langfristig gebunden ist und daher – aus Sicht der Bank – leider nur der Ertragsgenerierung für den Kunden dient, für die viel wichtigere Ertragsgenerierung der Bank jedoch wertlos ist.
#+end_quote

** Reich werden und bleiben: Ihr Wegweiser zur finanziellen Freiheit - Note 26 :quote:done:
#+begin_quote
Die langfristigen Konsequenzen von Kosten werden von Anlegern fast immer unterschätzt. Ich möchte Ihnen dies an einem Beispiel demonstrieren: Nehmen wir an, Sie haben 100.000 Euro und legen diese in einem aktiv gemanagten Fonds an oder vertrauen diese einem Vermögensverwalter an. Die laufenden Kosten summieren sich auf 2 Prozent im Jahr, was durchaus konservativ gerechnet ist.
#+end_quote

** Reich werden und bleiben: Ihr Wegweiser zur finanziellen Freiheit - Note 28 :quote:done:
#+begin_quote
fondsgebundene Lebensversicherungen sind nicht sinnvoll,
#+end_quote

** Reich werden und bleiben: Ihr Wegweiser zur finanziellen Freiheit - Note 29 :quote:done:
#+begin_quote
vielleicht noch ergänzt durch eine Absicherung in Edelmetallen.
#+end_quote

** Reich werden und bleiben: Ihr Wegweiser zur finanziellen Freiheit - Note 30 :quote:done:
#+begin_quote
Legen Sie nicht alle Eier in einen Korb! Diversifizieren Sie, das vermindert Ihr Risiko! 2.Eine Anlage ist umso weniger riskant, je geringer deren Wertschwankung (= Volatilität) ist.
#+end_quote

** Reich werden und bleiben: Ihr Wegweiser zur finanziellen Freiheit - Note 31 :quote:done:
#+begin_quote
Diversifikation ist also stets ein Eingeständnis von Unsicherheit und Unwissenheit: Weil wir nicht wissen, wie sich die Zukunft entwickelt, streuen wir unser Geld lieber über unterschiedliche Anlagen, um damit das Risiko zu mindern, dass wir auf das falsche Pferd setzen.
#+end_quote

** Reich werden und bleiben: Ihr Wegweiser zur finanziellen Freiheit - Note 32 :quote:done:
#+begin_quote
Wenn ich »nicht alle Eier in einen Korb« lege, kann ich es vermeiden, die allerschlechtesten Investitionen zu tätigen, aber gleichzeitig begebe ich mich auch der Chance, die besten Investitionen zu machen.
#+end_quote

** Reich werden und bleiben: Ihr Wegweiser zur finanziellen Freiheit - Note 33 :quote:done:
#+begin_quote
»Diversifikation ist eine Vorsichtsmaßnahme gegen Ignoranz. Sie ist nicht nötig für die, die wissen, was sie tun«, hat Warren Buffett immer wieder gesagt.147
#+end_quote

** Reich werden und bleiben: Ihr Wegweiser zur finanziellen Freiheit - Note 34 :quote:done:
#+begin_quote
Wenn ich es mir nicht zutraue, beispielsweise die besten Aktien oder Immobilien selbst herauszusuchen, dann investiere ich in einen möglichst breit diversifizierten Aktien- oder Immobilienfonds.
#+end_quote

** Reich werden und bleiben: Ihr Wegweiser zur finanziellen Freiheit - Note 35 :quote:done:
#+begin_quote
Nach der Portfoliotheorie, wie sie von Harry Markowitz und seinem Schüler William Sharpe formuliert wurde, wird Risiko als Volatilität definiert, also als das Ausmaß der Ertragsschwankungen um einen Durchschnittswert. Je stärker die Preise einer Anlage schwanken bzw., mathematisch ausgedrückt, je höher die Standardabweichung ist, desto größer auch das Risiko.
#+end_quote

** Reich werden und bleiben: Ihr Wegweiser zur finanziellen Freiheit - Note 36 :quote:done:
#+begin_quote
Ein Beispiel: Sie halten Immobilien für »sicher«, weil sie deren Wertschwankungen nicht täglich in der Tageszeitung nachlesen können. Wer ein Einfamilienhaus vor zehn Jahren gekauft hat, weiß nicht, wie viel es heute wert ist. Keine Zeitung berichtet darüber. Er könnte es erst erfahren, wenn er versucht, es zu verkaufen. Zwischen dem Zeitpunkt des Kaufes und des Verkaufes kann er sich der Illusion hingeben, der Wert seines Hauses sei gestiegen, auch wenn dieser in Wahrheit gefallen ist.
#+end_quote

** Reich werden und bleiben: Ihr Wegweiser zur finanziellen Freiheit - Note 37 :quote:done:
#+begin_quote
Er demonstriert den Trugschluss, dass Risiko sich durch die Volatilität messen lasse, am folgenden Beispiel: Angenommen, eine Aktie steigt in einem Monat um 10 Prozent, im nächsten Monat um 5 Prozent und im darauffolgenden Monat um 15 Prozent. Ein Investment in diese Aktie wäre auf Basis der Standardabweichung der monatlichen Erträge als riskanter einzustufen als eine Aktie, die in jedem Monat kontinuierlich um 15 Prozent fällt. Während der Besitzer der vermeintlich »riskanten« Aktie jedoch 32,8 Prozent verdient, verliert der Anleger der zweiten Aktie im gleichen Zeitraum 38,6 Prozent. Der Autor fügt ironisch hinzu: Der zweite Anleger, der also erheblich verliert, »kann sich jedoch damit trösten, dass dieser Verlust ›risikolos‹ zustande kam, denn die Standardabweichung ist in seinem Fall null«.
#+end_quote

** Reich werden und bleiben: Ihr Wegweiser zur finanziellen Freiheit - Note 38 :quote:done:
#+begin_quote
Die scheinbar wissenschaftlichen Diagramme, die Anlegern in einer Privatbank im Beratungsgespräch mit wichtiger Miene offeriert werden, beruhen größtenteils darauf, Risiko mit Volatilität gleichzusetzen.
#+end_quote

** Reich werden und bleiben: Ihr Wegweiser zur finanziellen Freiheit - Note 39 :quote:done:
#+begin_quote
Und sie beruhen pauschal auf der Annahme, dass eine möglichst hohe Diversifikation der Königsweg sei, wobei dies in Wahrheit nur die zweitbeste Lösung ist, die sich allerdings manchmal zwingend aus der Einsicht ergibt, dass man nicht fähig ist, besser als der Markt zu sein.
#+end_quote

** Reich werden und bleiben: Ihr Wegweiser zur finanziellen Freiheit - Note 41 :quote:done:
#+begin_quote
Was lehrt die Geschichte vom Auf und Ab des Aktienmarktes und den Zu- und Abflüssen in Aktienfonds? Die meisten Anleger folgen Modetrends.
#+end_quote

** Reich werden und bleiben: Ihr Wegweiser zur finanziellen Freiheit - Note 43 :quote:done:
#+begin_quote
Die meisten Anleger beurteilen die Chancen einer Anlage danach, wie sie sich in den vergangenen Monaten und Jahren entwickelt hat. Konnte man mit einer Anlage gewinnen, dann gewinnen sie Vertrauen. Zunächst zögern viele Anleger noch. Doch dann lesen sie fast jeden Tag in der Zeitung, wie toll die Gewinne sind, die man – beispielsweise – mit Aktien machen kann.
#+end_quote

** Reich werden und bleiben: Ihr Wegweiser zur finanziellen Freiheit - Note 44 :quote:done:
#+begin_quote
Wir suchen nach kurzfristiger Belohnung, und die erhalten wir, wenn die Aktie steigt. Und wir vermeiden Schmerz, der entsteht, wenn die Aktie fällt. Das ist der Grund, warum die meisten Anleger nicht in der Lage sind, gegen den Strom zu schwimmen, sondern pro-zyklisch investieren. Und genau deshalb verdienen so wenige Anleger Geld mit Aktien.
#+end_quote

** Reich werden und bleiben: Ihr Wegweiser zur finanziellen Freiheit - Note 45 :quote:done:
#+begin_quote
»Historisch betrachtet, werden Aktien mit schöner Regelmäßigkeit entweder als Investitionsform angenommen oder zum Glücksspiel abgewertet – und dies stets genau zum falschen Zeitpunkt. Aktien werden voraussichtlich immer dann als kluge und vernünftige Anlage angesehen, wenn sie es gerade nicht sind«, so schreibt Peter Lynch, einer der erfolgreichsten Aktienfondsmanager des 20. Jahrhunderts (Fidelity Magellan Fund).
#+end_quote

** Reich werden und bleiben: Ihr Wegweiser zur finanziellen Freiheit - Note 46 :quote:done:
#+begin_quote
Wer also Aktien nur deshalb kauft, weil sie in den vergangenen Jahren gestiegen sind, geht ein hohes Risiko ein.
#+end_quote

** Reich werden und bleiben: Ihr Wegweiser zur finanziellen Freiheit - Note 47 :quote:done:
#+begin_quote
Alan Greenspan senkte nicht nur die Zinsen, sondern die Politiker erleichterten die Bedingungen für bonitätsschwache Kreditnehmer, Immobiliendarlehen zu nehmen.
#+end_quote

** Reich werden und bleiben: Ihr Wegweiser zur finanziellen Freiheit - Note 48 :quote:done:
#+begin_quote
Wieder zeigte sich die Gefahr der »Rückspiegel-Investments«. Die sogenannten Subprime-Darlehen, die an bonitätsschwache Darlehensnehmer ausgegeben worden waren, wurden als CDOs (collateralized debt obligations) verbrieft und sodann an Investoren – z. B. an deutsche Landesbanken – weiterverkauft.
#+end_quote

** Reich werden und bleiben: Ihr Wegweiser zur finanziellen Freiheit - Note 49 :quote:done:
#+begin_quote
Gewinner sind dagegen antizyklisch orientierte
#+end_quote

** Reich werden und bleiben: Ihr Wegweiser zur finanziellen Freiheit - Note 50 :quote:done:
#+begin_quote
Die Entscheider dort sind keine Unternehmer, deren oberstes Bestreben es ist, das Richtige zu tun. Es sind Angestellte, deren oberste Maxime meistens lautet, nicht das Falsche zu tun. Nicht der Erfolg, sondern die Vermeidung von Misserfolg ist ihre erste Handlungsmaxime. Der amerikanische Psychologe John William Atkinson unterscheidet zwischen Erfolgssuchern und Misserfolgsmeidern. Viele institutionelle Investoren sind der zweiten Gruppe zuzuordnen, denn für sie geht es vor allem darum, Misserfolge zu vermeiden.
#+end_quote
