:PROPERTIES:
:ID:       ecd1437b-c604-4ba4-bc15-180bf71786a0
:END:
#+title: Rich Dad Poor Dad - Was die Reichen ihren Kindern über Geld beibringen
#+filetags: book
#+date: 2016-09-01

* Rich Dad Poor Dad - Was die Reichen ihren Kindern über Geld beibringen
  :PROPERTIES:
  :FINISHED: 2016-09
  :END:
** Description
#+begin_quote
Warum bleiben die Reichen reich und die Armen arm? Weil die Reichen ihren Kindern beibringen, wie sie mit Geld umgehen müssen, und die anderen nicht! Die meisten Angestellten verbringen im Laufe ihrer Ausbildung lieber Jahr um Jahr in Schule und Universität, wo sie nichts über Geld lernen, statt selbst erfolgreich zu werden.
Robert T. Kiyosaki hatte in seiner Jugend einen »Rich Dad« und einen »Poor Dad«. Nachdem er die Ratschläge des Ersteren beherzigt hatte, konnte er sich mit 47 Jahren zur Ruhe setzen. Er hatte gelernt, Geld für sich arbeiten zu lassen, statt andersherum. In Rich Dad Poor Dad teilt er sein Wissen und zeigt, wie jeder erfolgreich sein kann.

(Quelle)
#+end_quote
* Quotes
** Rich Dad Poor Dad - Note 1                                                  :quote:done:
#+begin_quote
Es ist ein Unterschied, ob man arm ist oder pleite. Pleite ist man vorübergehend, arm bleibt man bis in alle Ewigkeit.
#+end_quote

** Rich Dad Poor Dad - Note 2                                                  :quote:done:
#+begin_quote
»Wenn du die Lektionen des Lebens lernst, wird es dir gutgehen. Wenn nicht, wird dich das Leben einfach immer weiter herumschubsen. Die Menschen reagieren unterschiedlich darauf. Manche lassen es zu, dass sie das Leben herumschubst, andere ärgern sich und wehren sich dagegen. Aber sie richten ihre Wut gegen ihren Chef, ihre Arbeit, ihren Mann oder die Frau. Sie wissen nicht, dass es das Leben ist, das sie so herumschubst.«
#+end_quote

** Rich Dad Poor Dad - Note 3                                                  :quote:done:
#+begin_quote
»Die Armen und der Mittelstand arbeiten für Geld. Die Reichen lassen das Geld für sich arbeiten.«
#+end_quote

** Rich Dad Poor Dad - Note 4                                                  :quote:done:
#+begin_quote
»Darüber brauchst du dir auch jetzt noch keine Gedanken zu machen. Begreife nur, dass es die Angst ist, die die meisten Menschen an einer Arbeitsstelle hält. Die Angst, ihre Rechnungen nicht zahlen zu können, die Angst, entlassen zu werden, die Angst, nicht genügend Geld zu haben, die Angst, noch einmal von vorne anfangen zu müssen. Das ist der Preis dafür, dass man studiert hat, um einen Beruf oder ein Handwerk zu lernen und dann für Geld zu arbeiten. Die meisten Menschen werden Sklaven des Geldes … und dann ärgern sie sich über ihren Chef.«
#+end_quote

** Rich Dad Poor Dad - Note 5                                                  :quote:done:
#+begin_quote
»Gut«, sagte mein reicher Vater sanft. »Die meisten Menschen haben einen Preis. Und sie haben diesen Preis infolge der menschlichen Emotionen, genannt Angst und Gier. Zunächst motiviert uns die Angst, kein Geld zu haben, dass wir fleißig arbeiten und sobald wir unser Gehalt bekommen, veranlassen uns Begierden und Wünsche, an all die wunderbaren Dinge zu denken, die man mit Geld kaufen kann. Und schon ist das Muster in uns verankert.«
#+end_quote

** Rich Dad Poor Dad - Note 6                                                  :quote:done:
#+begin_quote
Vergesst das nie, weil euch die beiden Gefühle Angst und Verlangen in die größte Falle eures Lebens locken können, wenn ihr euch nicht bewusst macht, dass sie euer Denken beherrschen. Euer Leben in Angst zu verbringen und niemals eure Träume zu erforschen, ist grausam. Viel für Geld zu arbeiten und zu glauben, dass Geld euch Sachen kaufen wird, die euch glücklich machen, ist ebenfalls schrecklich. Mitten in der Nacht mit klopfendem Herzen wegen unbezahlter Rechnungen aufzuwachen, ist eine fürchterliche Art zu leben. Ein Leben, das von der Höhe
#+end_quote

** Rich Dad Poor Dad - Note 7                                                  :quote:done:
#+begin_quote
Bauen Sie ein Haus am Stadtrand, brauchen Sie nur eine fünfzehn Zentimeter dicke Betonplatte zu gießen. Die meisten Menschen versuchen in ihrem Drang reich zu werden, das Empire State Building auf einer fünfzehn Zentimeter dicken Bodenplatte zu errichten.
#+end_quote

** Rich Dad Poor Dad - Note 8                                                  :quote:done:
#+begin_quote
»Reiche Menschen erwerben Vermögenswerte. Die Armen und die Angehörigen der Mittelschicht schaffen Verbindlichkeiten an, aber sie denken, dass es sich um Vermögenswerte handelt.«
#+end_quote

** Rich Dad Poor Dad - Note 9                                                  :quote:done:
#+begin_quote
Ein Vermögenswert ist etwas, das Geld in meine Tasche bringt, eine Verbindlichkeit ist etwas, das mir Geld aus der Tasche zieht. Das ist eigentlich alles, was man wissen muss. Wenn Sie reich werden wollen, kaufen Sie einfach Ihr Leben lang Vermögenswerte. Wenn sie arm sein oder der Mittelschicht angehören wollen, dann kaufen Sie Ihr Leben lang Verbindlichkeiten.
#+end_quote

** Rich Dad Poor Dad - Note 10                                                 :quote:done:
#+begin_quote
Ein Mensch kann gut ausgebildet, beruflich erfolgreich und dennoch finanziell ungebildet sein. Solche Menschen arbeiten oft mehr, als sie müssen, weil sie gelernt haben, wie man schwer arbeitet, aber nicht, wie sie ihr Geld für sich arbeiten lassen können.
#+end_quote

** Rich Dad Poor Dad - Note 11                                                 :quote:done:
#+begin_quote
Als ich ein Kind war, erzählte mein Vater uns oft, dass die Japaner drei Mächte kennen: Die Macht des Schwertes, die des Juwels und die des Spiegels.
#+end_quote

** Rich Dad Poor Dad - Note 12                                                 :quote:done:
#+begin_quote
Ein Mensch kann sehr gebildet sein, beruflich höchst erfolgreich, und trotzdem ein Analphabet in Bezug auf Finanzen.
#+end_quote

** Rich Dad Poor Dad - Note 13                                                 :quote:done:
#+begin_quote
Viele finanzielle Probleme ergeben sich, weil man mit dem Strom schwimmt und versucht, mit dem Lebensstil anderer mitzuhalten. Gelegentlich sollten wir alle in den Spiegel schauen und mehr unserer inneren Weisheit als unseren Ängsten vertrauen.
#+end_quote

** Rich Dad Poor Dad - Note 14                                                 :quote:done:
#+begin_quote
Reichtum ist die Fähigkeit eines Menschen, eine gewisse Anzahl von Tagen überleben zu können. Oder: Wenn ich heute aufhöre zu arbeiten, wie lange könnte ich dann überleben?
#+end_quote

** Rich Dad Poor Dad - Note 15                                                 :quote:done:
#+begin_quote
»Kümmere dich um deine Geschäfte.« Finanzielle Schwierigkeiten sind oft das direkte Ergebnis der Tatsache, dass Menschen ihr ganzes Leben lang für jemand anderen arbeiten. Viele werden am Ende ihres Arbeitslebens mit leeren Händen dastehen.
#+end_quote

** Rich Dad Poor Dad - Note 16                                                 :quote:done:
#+begin_quote
Der Fehler dabei ist, dass zu viele Menschen vergessen, sich um ihre eigenen Geschäfte zu kümmern. Sie verbringen ihr ganzes Leben damit, sich um die Geschäfte anderer zu kümmern und machen diese Menschen reich.
#+end_quote

** Rich Dad Poor Dad - Note 17                                                 :quote:done:
#+begin_quote
So haben sich viele Menschen in große finanzielle Schwierigkeiten gebracht, als sie kein Einkommen mehr hatten. Um Bares aufzutreiben, verkauften sie ihre Vermögenswerte. Erstens konnten sie diese Gegenstände nur für einen Bruchteil des Wertes verkaufen, mit dem sie in ihrer persönlichen Bilanz eingetragen waren. Und zweitens: Wenn sie einen Gewinn aus dem Verkauf der Vermögenswerte erzielten, mussten sie diesen versteuern. Wieder nimmt der Staat seinen Anteil vom Gewinn und schmälert so die zur Tilgung der Schulden verfügbare Summe. Deshalb sage ich, dass
#+end_quote

** Rich Dad Poor Dad - Note 18                                                 :quote:done:
#+begin_quote
Job ist ein Akronym für »Just Over Broke«, »kurz vor der Pleite«.
#+end_quote

** Rich Dad Poor Dad - Note 19                                                 :quote:done:
#+begin_quote
Ich rate ihnen, ein ganzes Jahr zu investieren, um das Verkaufen zu lernen. Auch wenn sie erst einmal nichts verdienen, wird sich ihre Kommunikationsfähigkeit verbessern, und das ist unbezahlbar.
#+end_quote

** Rich Dad Poor Dad - Note 20                                                 :quote:done:
#+begin_quote
Niederlagen inspirieren Gewinner – und vernichten Verlierer.
#+end_quote

** Rich Dad Poor Dad - Note 21                                                 :quote:done:
#+begin_quote
Wenn sie nicht mit der Arbeit oder den Kindern beschäftigt sind, sehen sie oft fern, gehen zum Angeln, zum Golfen oder Einkaufen. Und doch, tief im Innern wissen sie, dass sie dabei sind, sich vor etwas Wichtigem zu drücken. Dies ist die am weitesten verbreitete Art der Faulheit: Faulheit, indem man sich ständig beschäftigt.
#+end_quote

** Rich Dad Poor Dad - Note 22                                                 :quote:done:
#+begin_quote
Mein reicher Vater verlangte stattdessen, dass sich seine Kinder fragten: »Wie kann ich mir das leisten?« Seiner Meinung nach blockieren die Worte »Das kann ich mir nicht leisten« den Verstand. Man braucht nicht mehr zu denken. »Wie kann ich mir das leisten?« wirkt dagegen anregend, zwingt einen zum Nachdenken und dazu, nach Lösungen zu suchen.
#+end_quote

** Rich Dad Poor Dad - Note 23                                                 :quote:done:
#+begin_quote
Wie kann man also Faulheit besiegen? Die Antwort ist – wie bereits gesagt – mit ein wenig Gier. Es gibt bei uns eine Radiosendung »What‘s in it for me?« (»Was bringt mir das?«). Eine Person muss sich hinsetzen und sich fragen: »Was bringt es mir, wenn ich gesund bin, sexy und gut aussehe?« oder »Wie würde mein Leben aussehen, wenn ich nie wieder arbeiten müsste?« oder »Was würde ich tun, wenn ich so viel Geld hätte, wie ich brauche?« Ohne ein bisschen Gier, ohne den Wunsch nach etwas Besserem, gibt es keinen Fortschritt. Unsere Welt entwickelt sich weiter, weil wir uns alle ein besseres Leben wünschen. Auf der Suche nach etwas Besserem machen wir neue Erfindungen. Wir gehen zur Schule und lernen fleißig, weil wir es besser haben wollen. Wann immer Sie sich also dabei ertappen, dass Sie sich vor einer Sache drücken, die Sie eigentlich tun sollten, müssen Sie sich nur fragen: »Was bringt mir das?« Seien Sie ein wenig gierig. Gier ist das beste Mittel gegen die Faulheit.
#+end_quote

** Rich Dad Poor Dad - Note 24                                                 :quote:done:
#+begin_quote
»Tu, was du in deinem Herzen für richtig hältst – Kritik erntest du sowieso. Du bist verdammt, wenn du es tust und verdammt, wenn du es lässt.«
#+end_quote

** Rich Dad Poor Dad - Note 25                                                 :quote:done:
#+begin_quote
Lebens« ausfindig machen und Millionen von Dollars verdienen möchten, müssen wir unser finanzielles Genie erwecken. Ich glaube, dass in jedem Menschen ein finanzielles Genie steckt. Das Problem ist, dass es schläft und darauf wartet, von uns geweckt zu werden. Es schläft, weil unsere Kultur uns den Glaubenssatz vermittelt hat, dass die Liebe zum Geld die Wurzel allen Übels ist.
#+end_quote

** Rich Dad Poor Dad - Note 26                                                 :quote:done:
#+begin_quote
»Du wirst, was du lernst«.
#+end_quote

** Rich Dad Poor Dad - Note 27                                                 :quote:done:
#+begin_quote
Die Welt schubst einen Menschen nicht deshalb herum, weil die anderen Tyrannen sind, sondern weil es dem Einzelnen an innerer Kontrolle und Disziplin mangelt. Menschen, denen diese innere Stärke fehlt, werden häufig Opfer derjenigen, die Selbstdisziplin haben.
#+end_quote

** Rich Dad Poor Dad - Note 29                                                 :quote:done:
#+begin_quote
Wenn Sie knapp bei Kasse sind, halten Sie dem wachsenden Druck stand und lassen Sie Ihre Ersparnisse oder Investitionen unangetastet. Nutzen Sie den zunehmenden Druck als Inspiration für ihr finanzielles Genie, damit es neue Möglichkeiten findet, Geld zu verdienen und zahlen Sie dann Ihre Rechnungen.
#+end_quote
