:PROPERTIES:
:ID:       64176c05-e20d-42b1-8e78-64599f5dbb3f
:END:
#+title: Slow Family
#+filetags: :parenting:book:
#+date: 2020-11-01

* Slow Family (Book)
:PROPERTIES:
:FINISHED: 2020-11
:END:

- 7 Zutaten für eine glückliche Familie
  - Liebe
  - Natur
  - Achtsamkeit
  - Menschen
    - der [[id:6e77b22e-eee8-44fc-9d8c-7e70a165b09d][Mere-Exposure Effect]] ist auch bei Menschen zu beobachten
  - Resourcen
  - Wissen
  - Zauber
- Auch die Umgebung der Familie ist wichtig
  - /Slow Village/ als Pendant zu dem Dorf in [[id:67080028-4f04-4174-a2ae-60022d293cc3][Artgerecht]]
* Quotes
** Note 1                                                                      :quote:
#+begin_quote
Nicola: "Jedes Mal wenn ich ein Kinderbuch aufschlage, könnte ich platzen:
Lauter glückliche Kühe auf grünen Wiesen mit pickenden Hühnern und
Bullerbü-Kindern, die Eieer aus hübschen Nestern einsammeln. Wo bitte gibt es
das noch? Die meisten Kinder werden niemals etwas anderes essen als Eier von
zerrupften, gedopten, verhaltensgestörten armen Gefangegen mit verstümmelten
Flügeln und Schnäbeln, die zu Tausenden dich gedrängt auf Gitterböden gehalten
werden.
#+end_quote
** Note 2                                                                      :quote:
#+begin_quote
Lies man das Feuilleton der FAZ oder SZ dann unterhalten Mütter in der
Attachment-Parenting-Szene sich in erster Linie über Kinderkacke; die ewig
gestrigen Zuhause-Gebliebenen verbringen Tage damit, sich online um perfekt
gebundene Tragetücher und korrekte Stillzeiten zu prügeln.
#+end_quote
