:PROPERTIES:
:ID:       f052f625-35e3-44ea-b605-39a370a11731
:END:
#+title: So viel Freude, so viel Wut
#+filetags: book
#+date: 2022-02-01

* So viel Freude, so viel Wut
:PROPERTIES:
:FINISHED: 2022-02
:END:
* Description
- über [[id:4789eb41-9d72-4fb0-bd5b-80c87cb2918c][Gefühlsstarke Kinder]]
- über [[id:2114312c-7018-4a34-8936-7808173598d1][Bedürfnisse nach Marshall Rosenberg]]
  - in Bezug auf [[id:4789eb41-9d72-4fb0-bd5b-80c87cb2918c][Gefühlsstarke Kinder]] kann es nicht Aufgabe der Eltern sein, den "inneren" Konflikt zu lösen
    - Nähebedürfnis vs Freiheitsdrang
    - Sehnsucht nach Struktur vs. Rebellion
  - Eltern können aus den Impulsen Kraftstoff "tanken", der die Kinder in der Entwicklung weiterwachsen lässt
- Kapitel 2
  - über das unterschiedliche [[#JeromeKagan%2FTemperament][Temperament]] von Babys
  - das weinende Baby
    - Weinen als Stressabbau
      - all die Eindrücke des Tages verarbeiten
      - sich selbst [[id:cbfafa4f-4893-431a-bb11-7379e443fc29][regulieren]]
      - all die Versuche das Baby zu beruhigen führen zu noch mehr Reizen
        - führt zu Überforderung (Analogie mit den roten Flitzern auf der Strasse)
      - die wirkungsvollste Strategie: In den Armen der Eltern sich ausweinen dürfen und Liebe/Zuneigung empfangen
        - Job der Eltern ist es nicht, mit dem Weinen aufzuhören sondern für das Kind da zu sein
  - [[id:4789eb41-9d72-4fb0-bd5b-80c87cb2918c][Gefühlsstarke Kinder]] verfügen über eine innere Resilienz
    - sie zerbrechen nicht an sub-optimierten [[id:2114312c-7018-4a34-8936-7808173598d1][Bedürfnissen]]
      - auch wenn sie nicht von Anfang an gesehen werden
      - es ist nie zu spät für die Bindung / auf das Bedürfnis einzugehen
- [[#Elterntypen][Was sind die Aufgaben der Eltern]] ?
  - jede Unsicherheit bei den Eltern wird von den Kindern wahrgenommen
    - Eltern sind keine *Leitwölfe* mehr sondern "Hüttenhünde"
    - natürliche Autorität ist gefragt
      - geht ein bisschen in die Richtung [[#Gleichw%C3%BCrdige%20Familie][Gleichwürdige Familie]]
      - Kinder sollen angstfrei zu den Eltern aufschauen und Entscheidungen respektieren (natürlich Autorität)
- Umgang mit Emotionen
  - Eltern bringen den Kindern nicht bei, ihre Gefühle zu benennen
  - im Alarmzustand ziehen sich im Inneren des Ohrs die Muskeln zusammen, so dass das Kind menschliche Stimmen nicht menr hören kann
    - dafür aber "tiefe" Stimmen
  - hinter den allermeisten Gefühlsausbrüchen gefühlsstarker Kinder steckt stress
    - Ziel ist es, den Stress für die Selbstregulation zu reduzieren
  - wenn das Kind nicht zuhört, können folgende [[#Strategien%20bei%20Stressbew%C3%A4ltigung][Strategien]] angewandt werden, damit die Botschaft das Kind auch erreicht
- Was angeblich "altersgerecht" sein soll
  - Durchschlafen ist aus evolutionärer Sicht im späten Kleinkindalter dran
  - durchschnittliches Alter zum Abstillen weltweit - 2 Jahre
  - in vielen Kulturen ist es undenkbar, dass ein Kind die Nacht ohne seine Eltern verbringt
    - Es gibt nicht den Menschenschlaf. Das Konzept, 8 Stunden durchzuschlafen und den Rest des Tages zu arbeiten, ist weder natürlich noch normal. Diese Klare Trennung zwischen Tag und Nacht ist etwas, was wir uns ausgedachr haben,weil es gut in unsere Industriegesellschaft passt.
  - *Aufgeweckt werden* und gut *gut schlafen* sind Konstrukte. Kulturübergreifende Beobachtungen zeigen: In westlichen Kulturen ist die Idee vom *Durchschlafen* weiter verbreitet als in allen anderen. Hier wird auch das Wecken durch das Kind am dramatischsten empfunden. In anderen Kulturen ist das schon deshalb nicht so schlimm, weil man Schlaf ja jederzeit nachholen kann.

* Quotes
** So viel Freude, so viel Wut - Note 1                                        :quote:done:
#+begin_quote
Gefühlsstarke Kinder sind das Salz in der Suppe menschlichen Daseins.
#+end_quote
** So viel Freude, so viel Wut - Note 2                                        :quote:done:
#+begin_quote
Nicht dieses Kind hat uns enttäuscht, sondern unsere Erwartungen.
#+end_quote
** So viel Freude, so viel Wut - Note 3                                        :quote:done:
#+begin_quote
Vor der Veränderung steht das Verständnis.
#+end_quote
** So viel Freude, so viel Wut - Note 4                                        :quote:done:
#+begin_quote
[...] deswegen ist es wichtig für die Eltern: Was andere Menschen über uns und unser Kind denken, sagt viel über sie aus, und nichts über uns.
#+end_quote
** So viel Freude, so viel Wut - Note 5                                        :quote:done:
#+begin_quote
Einem Kind zu spiegeln, dass sein Verhalten nicht altersgerecht sein, wird seinen inneren Konflikt noch mehr verschärfen.
#+end_quote
