:PROPERTIES:
:ID:       31f900f1-2cd3-4a0f-ae64-59a53328928c
:END:
#+title: Start with Why - How Great Leaders Inspire Everyone To Take Action
#+filetags: :book:
#+date: 2017-03-01

* Start with Why - How Great Leaders Inspire Everyone To Take Action
  :PROPERTIES:
  :FINISHED: 2017-03
  :END:
** Description
<<<
Why are some people and organizations more innovative, more influential, and more profitable than others? Why do some command greater loyalty from customers and employees alike? Even among the successful, why are so few able to repeat their success over and over?

People like Martin Luther King Jr., Steve Jobs, and the Wright Brothers might have little in common, but they all started with why. It was their natural ability to start with why that enabled them to inspire those around them and to achieve remarkable things.

In studying the leaders who've had the greatest influence in the world, Simon Sinek discovered that they all think, act, and communicate in the exact same way—and it's the complete opposite of what everyone else does. Sinek calls this powerful idea The Golden Circle, and it provides a framework upon which organizations can be built, movements can be lead, and people can be inspired. And it all starts with WHY.

Any organization can explain what it does; some can explain how they do it; but very few can clearly articulate why. WHY is not money or profit—those are always results. WHY does your organization exist? WHY does it do the things it does? WHY do customers really buy from one company or another? WHY are people loyal to some leaders, but not others?

Starting with WHY works in big business and small business, in the nonprofit world and in politics. Those who start with WHY never manipulate, they inspire. And the people who follow them don't do so because they have to; they follow because they want to.

Drawing on a wide range of real-life stories, Sinek weaves together a clear vision of what it truly takes to lead and inspire. This book is for anyone who wants to inspire others or who wants to find someone to inspire them.

(Source: https://www.goodreads.com/book/show/7108725-start-with-why)
<<<
* Quotes
** Start with Why - Note 1                                                     :quote:done:
#+begin_quote
This is important because our behavior is affected by our assumptions or our perceived truths. We make decisions based on what we think we know.
#+end_quote

** Start with Why - Note 2                                                     :quote:done:
#+begin_quote
More data, however, doesn’t always help, especially if a flawed assumption set the whole process in motion in the first place. There are other factors that must be considered, factors that exist outside of our rational, analytical, information-hungry brains.
#+end_quote

** Start with Why - Note 3                                                     :quote:done:
#+begin_quote
But if you ask most businesses why their customers are their customers, most will tell you it’s because of superior quality, features, price or service. In other words, most companies have no clue why their customers are their customers.
#+end_quote

** Start with Why - Note 4                                                     :quote:done:
#+begin_quote
When fear is employed, facts are incidental. Deeply seated in our biological drive to survive, that emotion cannot be quickly wiped away with facts and figures. This is how terrorism works. It’s not the statistical probability that one could get hurt by a terrorist, but it’s the fear that it might happen that cripples a population.
#+end_quote

** Start with Why - Note 5                                                     :quote:done:
#+begin_quote
Just as manipulations can drive a sale but not create loyalty, so too can they help a candidate get elected, but they don’t create a foundation for leadership.
#+end_quote

** Start with Why - Note 6                                                     :quote:done:
#+begin_quote
Addicted to the short-term results, business today has largely become a series of quick fixes added on one after another after another. The short-term tactics have become so sophisticated that an entire economy has developed to service the manipulations, equipped with statistics and quasi-science.
#+end_quote

** Start with Why - Note 7                                                     :quote:done:
#+begin_quote
The concept of The Golden Circle was inspired by the golden ratio—a simple mathematical relationship that has fascinated mathematicians, biologists, architects, artists, musicians and naturists since the beginning of history.
#+end_quote

** Start with Why - Note 8                                                     :quote:done:
#+begin_quote
We say WHAT we do, we sometimes say HOW we do it, but we rarely say WHY we do WHAT we do.
#+end_quote

** Start with Why - Note 9                                                     :quote:done:
#+begin_quote
It’s worth repeating: people don’t buy WHAT you do, they buy WHY you do it.
#+end_quote

** Start with Why - Note 10                                                    :quote:done:
#+begin_quote
Loyalists for each brand will point to various features and benefits that matter to them (or don’t matter to them) in an attempt to convince the other that they are right. And that’s one of the primary reasons why so many companies feel the need to differentiate in the first place—based on the flawed assumption that only one group can be right. But what if both parties were right? What if an Apple was right for some people and a PC was right for others? It’s not a debate about better or worse anymore, it’s a discussion about different needs.
#+end_quote

** Start with Why - Note 11                                                    :quote:done:
#+begin_quote
Our need to belong is not rational, but it is a constant that exists across all people in all cultures. It is a feeling we get when those around us share our values and beliefs. When we feel like we belong we feel connected and we feel safe. As humans we crave the feeling and we seek it out.
#+end_quote

** Start with Why - Note 12                                                    :quote:done:
#+begin_quote
Dell selling mp3 players just doesn’t feel right because Dell defines itself as a computer company, so the only things that belong are computers. Apple defines itself as a company on a mission and so anything they do that fits that definition feels like it belongs.
#+end_quote

** Start with Why - Note 13                                                    :quote:done:
#+begin_quote
We have trouble, for example, explaining why we married the person we married. We struggle to put into words the real reasons why we love them, so we talk around it or rationalize it. “She’s funny, she’s smart,” we start. But there are lots of funny and smart people in the world, but we don’t love them and we don’t want to marry them. There is obviously more to falling in love than just personality and competence.
#+end_quote

** Start with Why - Note 14                                                    :quote:done:
#+begin_quote
Henry Ford summed it up best. “If I had asked people what they wanted,” he said, “they would have said a faster horse.”
#+end_quote

** Start with Why - Note 15                                                    :quote:done:
#+begin_quote
If we were all rational, there would be no small businesses, there would be no exploration, there would be very little innovation and there would be no great leaders to inspire all those things. It is the undying belief in something bigger and better that drives that kind of behavior.
#+end_quote

** Start with Why - Note 16                                                    :quote:done:
#+begin_quote
Herb Kelleher famously said, “You don’t hire for skills, you hire for attitude. You can always teach skills.”
#+end_quote

** Start with Why - Note 17                                                    :quote:done:
#+begin_quote
Great companies don’t hire skilled people and motivate them, they hire already motivated people and inspire them.
#+end_quote

** Start with Why - Note 18                                                    :quote:done:
#+begin_quote
The feeling of trust is lodged squarely in the same place as the WHY—the limbic brain—and it’s often powerful enough to trump empirical research, or at least seed doubt. This is the reason why so many manipulations are effective; we believe that, for better or worse, others know more than we do.
#+end_quote

** Start with Why - Note 19                                                    :quote:done:
#+begin_quote
Our population is broken into five segments that fall across a bell curve: innovators, early adoptors, early majority, late majority and laggards.
#+end_quote

** Start with Why - Note 20                                                    :quote:done:
#+begin_quote
Each of us assigns different values to different things and our behaviors follow accordingly. This is one of the major reasons why it is nearly impossible to “convince” someone of the value of your products or ideas based on rational arguments and tangible benefits.
#+end_quote

** Start with Why - Note 21                                                    :quote:done:
#+begin_quote
Energy motivates but charisma inspires. Energy is easy to see, easy to measure and easy to copy. Charisma is hard to define, near impossible to measure and too elusive to copy.
#+end_quote

** Start with Why - Note 22                                                    :quote:done:
#+begin_quote
We don’t want to come to work to build a wall, we want to come to work to build a cathedral.
#+end_quote

** Start with Why - Note 23                                                    :quote:done:
#+begin_quote
Don’t forget that a WHY is just a belief, HOWs are the actions we take to realize that belief and WHATs are the results of those actions.
#+end_quote

** Start with Why - Note 24                                                    :quote:done:
#+begin_quote
But Ron Bruder is no one-hit wonder. He has been able to repeat his success and change the course of multiple industries, multiple times.
#+end_quote

** Start with Why - Note 25                                                    :quote:done:
#+begin_quote
As a company grows, the CEO’s job is to personify the WHY. To ooze of it. To talk about it. To preach it. To be a symbol of what the company believes. They are the intention and WHAT the company says and does is their voice. Like Martin Luther King and his social movement, the leader’s job is no longer to close all the deals; it is to inspire.
#+end_quote

** Start with Why - Note 26                                                    :quote:done:
#+begin_quote
The reason so many small businesses fail, however, is because passion alone can’t cut it. For passion to survive, it needs structure.
#+end_quote

** Start with Why - Note 27                                                    :quote:done:
#+begin_quote
What Ben teaches us is special. When you compete against everyone else, no one wants to help you. But when you compete against yourself, everyone wants to help you.
#+end_quote

** Start with Why - Note 28                                                    :quote:done:
#+begin_quote
What if the next time when someone asks, “Who’s your competition?” we replied, “No idea.” What if the next time someone pushes, “Well, what makes you better than your competition?” we replied, “We’re not better than them in all cases.” And what if the next time someone asks, “Well why should I do business with you then?” we answer with confidence, “Because the work we’re doing now is better than the work we were doing six months ago. And the work we’ll be doing six months from now will be better than the work we’re doing today. Because we wake up every day with a sense of WHY we come to work. We come to work to inspire people to do the things that inspire them. Are we better than our competition? If you believe what we believe and you believe that the things we do can help you, then we’re better. If you don’t believe what we believe and you don’t believe the things we can do will help you, then we’re not better. Our goal is to find customers who believe what we believe and work together so that we can all succeed. We’re looking for people to stand shoulder-to-shoulder with us in pursuit of the same goal. We’re not interested in sitting across a table from each other in pursuit of a sweeter deal. And here are the things we’re doing to advance our cause …” And then the details of HOW and WHAT you do follow. But this time, it started with WHY.
#+end_quote
