:PROPERTIES:
:ID:       f822574d-bf98-42ec-a482-e23deddd83e0
:END:
#+title: Steve Jobs: Die autorisierte Biografie des Apple-Gründers
#+filetags: book
#+date: 2018-07-01

* Steve Jobs: Die autorisierte Biografie des Apple-Gründers
:PROPERTIES:
:FINISHED: 2018-07
:END:
** Description
#+begin_quote
Macintosh, iMac, iPod, iTunes, iPhone, iPad – Steve Jobs hat der digitalen Welt mit der Kultmarke Apple Ästhetik und Aura gegeben. Wo Bill Gates für solide Alltagsarbeit steht, war der Mann aus San Francisco die Stilikone des IT-Zeitalters, ein begnadeter Vordenker, der kompromisslos seiner Idee folgte. Genial und selbstbewusst hat er trotz ökonomischer und persönlicher Krisen den Apfel mit Biss (Bite) zum Synonym für Innovation und Vision gemacht.

Doch wer war dieser Meister der Inszenierung, was trieb ihn an? Walter Isaacson gewann das Vertrauen des Apple-Chefs und konnte als erster Biograf während der langjährigen Recherchen auf seine uneingeschränkte Unterstützung ebenso bauen wie auf die seiner Familie, seiner Weggefährten und auch der Kontrahenten. Entstanden ist d a s Buch über Steve Jobs und sein Unternehmen – nicht nur für Apple-Fans.

(Quelle: https://www.randomhouse.de/Taschenbuch/Steve-Jobs/Walter-Isaacson/btb-Taschenbuch/e414947.rhd)
#+end_quote
* Quotes
** Steve Jobs: Die autorisierte Biografie des Apple-Gründers : 843-46          :quote:done:
#+begin_quote
Vegetariertum und Zen-Buddhismus, Meditation und Spiritualität, LSD und Rockmusik – Jobs vereinte auf seine Weise die vielfachen Impulse der nach Erleuchtung suchenden Campus-Subkultur jener Zeit. Auch wenn er auf dem Reed College kaum Gelegenheit dazu hatte, unterschwellig waren da immer noch seine elektronischen Ambitionen, die er eines Tages erstaunlich gut mit den übrigen Komponenten verbinden würde.
#+end_quote

** Steve Jobs: Die autorisierte Biografie des Apple-Gründers : 2273 - 76       :quote:done:
#+begin_quote
»Steve hat ein Reality Distortion Field.« Als Hertzfeld nachfragte, was er damit meine, führte Tribble aus: »In seiner Gegenwart wird die Wirklichkeit formbar. Er kann jeden von praktisch allem überzeugen. Wenn er nicht da ist, lässt der Effekt nach, aber realistische Zeitpläne haben kaum eine Chance dagegen.«
#+end_quote

** Steve Jobs: Die autorisierte Biografie des Apple-Gründers : 2292 - 93       :quote:done:
#+begin_quote
»Er kann sich tatsächlich selbst belügen«, erklärte Bill Atkinson, »und dadurch auch andere Leute in seine Sichtweise hineinziehen, gerade weil er selbst völlig davon überzeugt ist und sie verinnerlicht hat.«
#+end_quote

** Steve Jobs: Die autorisierte Biografie des Apple-Gründers : 2301 - 02       :quote:done:
#+begin_quote
Wir schafften das Unmögliche, weil wir gar nicht realisierten, dass es unmöglich war.
#+end_quote

** Steve Jobs: Die autorisierte Biografie des Apple-Gründers : 3015 - 18       :quote:done:
#+begin_quote
Zu diesem Zeitpunkt war Microsoft aber schon auf dem Sprung, vom Geschäftspartner Apples zum Konkurrenten zu werden. Die Firma produzierte zwar weiterhin Anwendungsprogramme für Apple wie Microsoft Word, einen immer größeren Teil ihrer Umsätze erzielte Microsoft jedoch mit dem Betriebssystem, das sie für den Personal Computer von IBM entwickelt hatte.
#+end_quote

** Steve Jobs: Die autorisierte Biografie des Apple-Gründers : 3633 - 36       :quote:done:
#+begin_quote
Deshalb überlegte er gemeinsam mit Hertzfeld, wie er es anstellen könnte, sich davon zu befreien. »Ich hab’s!«, verkündete er Hertzfeld eines Tages. »Mir ist eine perfekte Methode eingefallen, wie ich kündigen und das Reality Distortion Field außer Kraft setzen kann. Ich gehe einfach in Steves Büro, lasse die Hosen runter und pinkle auf seinen Schreibtisch. Was kann er da noch sagen? Das funktioniert garantiert.
#+end_quote

** Steve Jobs: Die autorisierte Biografie des Apple-Gründers : 5766 - 66       :quote:done:
#+begin_quote
Glauben Sie wirklich, dass Steve Jobs etwas in der Hand hat?«, fragte Gates Amelio. »Ich kenne seine Technologie, das ist nichts anderes als aufgewärmtes UNIX, und ihr werdet es nie schaffen, das auf euren Rechnern laufen zu lassen.
#+end_quote

** Steve Jobs: Die autorisierte Biografie des Apple-Gründers : 6958 - 61       :quote:done:
#+begin_quote
Er fuhr seinen Mercedes immer noch ohne Nummernschild und er parkte immer noch auf dem Behindertenparkplatz direkt neben dem Haupteingang und blockierte dabei manchmal sogar zwei Parkbuchten. Das Ganze wurde zum Running Gag. Die Mitarbeiter bastelten Schilder mit der Aufschrift »Park Different«, und schließlich überpinselte jemand sogar das Behindertensymbol mit einem Mercedes-Stern
#+end_quote

** Steve Jobs: Die autorisierte Biografie des Apple-Gründers : 8938 - 40       :quote:done:
#+begin_quote
Nun lief damals bei Apple noch ein zweites Projekt: eine geheime Studie über die Machbarkeit eines Tablet-Computers. Im Jahr 2005 überschnitten sich dann beide Projekte und die Ideen für das Tablet-Gerät flossen in die Entwicklung des iPhone ein. Mit anderen Worten: Streng genommen ist das iPad älter als das iPhone und half bei dessen Geburt mit.
#+end_quote

** Steve Jobs: Die autorisierte Biografie des Apple-Gründers : 10742 - 44      :quote:done:
#+begin_quote
Wenn man seinen Kindern ein iPad kauft, ist das keine Starthilfe hin zu der Einsicht, dass die Welt für einen da ist, um auseinandergenommen und wieder zusammengebaut zu werden. Man vermittelt seinem Nachwuchs vielmehr, dass selbst so etwas wie ein Batteriewechsel eine Sache ist, die man Fachleuten überlassen sollte
#+end_quote
