:PROPERTIES:
:ID:       e57b5ee1-a165-4363-926e-4f138d8cda06
:END:
#+title: Stoppt die Welt, ich will aussteigen! Kuriose Abenteuer einer Weltreise
#+filetags: book
#+date: 2017-03-01

* Stoppt die Welt, ich will aussteigen! Kuriose Abenteuer einer Weltreise
:PROPERTIES:
:FINISHED: 2017-03
:END:
** Description
#+begin_quote
Wie fühlt es sich an, loszulassen und das Leben zu Leben, das man leben möchte? Martin Krengel nutzt seine Weltreise, um mit anderen Lebensstilen und Arbeitsformen zu experimentieren. Er betreibt Anti-Zeitmanagement auf Fiji, macht eine Digital-Detox-Diät auf Tahiti und zieht als digitaler Nomade durch Südamerika.
Krengels spitzfindiger und facettenreicher Bericht zeigt: Reisen bewegt. Beine UND Kopf.

(Source: https://www.martinkrengel.com/reisen/)
#+end_quote
* Quotes
** Stoppt die Welt, ich will aussteigen! - Note 1                              :quote:done:
#+begin_quote
Es geht mir nicht so sehr um die Weltreise an sich. Vielmehr um den Luxus, morgens aufzustehen und nicht zu wissen, ob ich nach Norden, Süden, Osten, Westen, nach oben oder unten weiterziehe oder ob ich die Augen zumache und einfach liegen bleibe. Einfach mal so den Tag verdösen. Nichts tun.
#+end_quote

** Stoppt die Welt, ich will aussteigen! - Note 2                              :quote:done:
#+begin_quote
Mein Ziel: kein Ziel.
#+end_quote

** Stoppt die Welt, ich will aussteigen! - Note 3                              :quote:done:
#+begin_quote
Ich beschließe ein Experiment: Ich starte ohne Masterplan. Ohne Ziel. Nur mit einer groben Richtung: Um die Welt reisen, so viel Spaß wie möglich haben, nur das machen, worauf ich wirklich Lust habe. Das Leben maximal genießen und keine fixen Ziele haben. Einfach ich sein. Und schauen was dabei passiert.
#+end_quote

** Stoppt die Welt, ich will aussteigen! - Note 4                              :quote:done:
#+begin_quote
Wie wir auf Sicherheit getrimmten Menschenaffen halt so ticken. Unser Hirn liebt’s GROB: Gewohnheit, Regeln, Ordnung, Berechenbarkeit. -
#+end_quote

** Stoppt die Welt, ich will aussteigen! - Note 5                              :quote:done:
#+begin_quote
Nicht der Weg ist das wichtigste Ziel einer Reise, sondern der Start! Sonst gibt es keine Reise, kein Abenteuer, keine Veränderung.
#+end_quote

** Stoppt die Welt, ich will aussteigen! - Note 6                              :quote:done:
#+begin_quote
Zwei jüngere, gut Yakmilch-genährte Mönche checken Facebook auf ihrem Handy: Was sie bloß posten? Vielleicht: „Heute beim Singen eingeschlafen.“ (0 Likes) „Krasse Gebetssession!“ (3 Likes) „Der Typ vor mir hat heute schon wieder einen fahren lassen.“ (8 Likes + 1 böser Kommentar – vom Typen davor).
#+end_quote

** Stoppt die Welt, ich will aussteigen! - Note 7                              :quote:done:
#+begin_quote
„What I wish I knew with 20“, das ich jedem empfehle, der mit 30 noch zögert, ob er sich selbstständig machen soll.
#+end_quote

** Stoppt die Welt, ich will aussteigen! - Note 8                              :quote:done:
#+begin_quote
Die gute Nachricht: Es steht ein Ofen in der Jurte. Die schlechte: Der brennt nur drei Stunden. Um drei Uhr nachts ist es empfindlich kalt. Der Horror: Jetzt „raus müssen“ – der Donnerbalken mit Loch im Boden steht 30 Meter entfernt. – Das Glück: Die Hirtin heizt in der Nacht nach.
#+end_quote

** Stoppt die Welt, ich will aussteigen! - Note 9                              :quote:done:
#+begin_quote
Als wir zum achten Mal bei Full Speed (wie schnell genau, kann ich nicht sagen – der Tacho ist kaputt), aufsetzen, geht unser Fahrgeräusch in ein lautes Poltern über. Tsönnar bremst. Steigt aus. Sagt unbetroffen: „Oh-oh“. Fünf Minuten später ist der neue Reifen montiert – bis auf die vierte Schraube, die er nicht mehr findet. Egal, weiter!
#+end_quote

** Stoppt die Welt, ich will aussteigen! - Note 10                             :quote:done:
#+begin_quote
Das Klammern ans traute Heim ist der Lust auf Abenteuer gewichen. Es ist bemerkenswert, wie schnell schwermütige Gedanken verfliegen, wenn du jeden Tag etwas erlebst.
#+end_quote

** Stoppt die Welt, ich will aussteigen! - Note 11                             :quote:done:
#+begin_quote
Die acht Tage verdeutlichten, dass es nichts bringt, mich über eine verpasste Chance oder über eine Schwierigkeit zu ärgern. Ganz im Gegenteil, oft entwickelt sich etwas Ungewolltes zu etwas Gutem.
#+end_quote

** Stoppt die Welt, ich will aussteigen! - Note 12                             :quote:done:
#+begin_quote
Gescheiterte Dialoge vor Ort Martin: „Where do you live?“ Mongole: „Toyota.“ Martin: „Where are you from?“ Mongole: „Horse.“ Martin: „Where are we going?“ Fahrer: „Yes!“
#+end_quote

** Stoppt die Welt, ich will aussteigen! - Note 13                             :quote:done:
#+begin_quote
Woran du merkst, dass du Mongole geworden bist: Du weißt nicht mehr, wie Bäume aussehen (es gibt hier keine). Du fährst so oft es geht neben der Straße. Du kannst einen Reifen in 5 Minuten wechseln. Du erachtest minus 5 Grad als warm und zeigst dein Dekolleté. Eine Hauptspeise für 3 Euro findest du teuer. Du machst als Museumswärter um 15 Uhr Feierabend, obwohl das Museum offiziell bis 18 Uhr geöffnet hat. Du installierst statt des Rückspiegels einen DVD-Monitor (in der Steppe fährt eh niemand hinter dir). Du magst aus Prinzip keine Chinesen. Du magst aus Prinzip keine Russen. Du findest feste Wände als Behausung merkwürdig. Du verehrst dein Pferd wie Deutsche ihr Auto.
#+end_quote

** Stoppt die Welt, ich will aussteigen! - Note 14                             :quote:done:
#+begin_quote
Das ist nur schwer mit den westlichen Knigge-Vorstellungen vereinbar. Und davon gibt es einige, sehr gewöhnungsbedürftige Verhaltensweisen, die gehörig an Herz, Nieren und Galle gehen: das laute Hochziehen der Nase, das Spucken, das Schnäuzen ohne Taschentuch auf den Fußboden, gut hörbare Rülpsgeräusche auf der Straße, lautes Schmatzen beim Essen. China ist nicht ohne!
#+end_quote

** Stoppt die Welt, ich will aussteigen! - Note 15                             :quote:done:
#+begin_quote
… und die Enttäuschung: Der Coffeeshop ist so liebevoll eingerichtet wie das Berliner Einwohnermeldeamt.
#+end_quote

** Stoppt die Welt, ich will aussteigen! - Note 16                             :quote:done:
#+begin_quote
Woran man erkennt, dass man zu lange in China ist: Du gehst in den Zoo und denkst: „So leckere Tiere hier!“ Du hast vergessen, wie es sich anfühlt, irgendwo alleine zu sein. Du bittest westliche Touristen um ein gemeinsames Foto. Du bist Nichtraucher geworden, weil dir der Smog der Stadt ausreicht. Du gehst zu IKEA, um in Ruhe auszuschlafen. Du verwendest Omas alte Stricknadeln zum Essen. Du bekommst ohne 6 Liter Grüntee am Tag Entzugserscheinungen. Du gibst jemandem deine Visitenkarte, bevor du nach seinem Namen fragst. Du kaufst Reis in 10-Kilo-Säcken. Du kannst treffsicher in 10 Meter Entfernung eine Kerze ausspucken. Du gehst nur noch mit Regenschirm in die Sonne. Du trittst in keine Gebäude mit der Hausnummer 4. Du verstehst all diese Andeutungen.
#+end_quote

** Stoppt die Welt, ich will aussteigen! - Note 17                             :quote:done:
#+begin_quote
Dass der König direkt auf die Brüste von Lady Gaga starrt, wäre ein Bild für die Götter (aber der Buddhismus hat zum Glück keine, die das ahnden könnten).
#+end_quote

** Stoppt die Welt, ich will aussteigen! - Note 18                             :quote:done:
#+begin_quote
Als passendes Gimmick fürs Hippie- und „Hängengebliebenen“-Klientel fungiert ein Party-Bus, der täglich in die Berge fährt – zum Kiffen.
#+end_quote

** Stoppt die Welt, ich will aussteigen! - Note 19                             :quote:done:
#+begin_quote
Und doch beschleicht mich gerade ein unbehagliches, fast unheimliches Gefühl beim Betrachten dieser Erste-Welt-Landschaft, in der man sein ganzes Leben vor sich hin dümpeln kann, ohne je kritische Fragen zu stellen.
#+end_quote

** Stoppt die Welt, ich will aussteigen! - Note 20                             :quote:done:
#+begin_quote
„Ja, ja“, sagt er, „nach ca. 3 Monaten Reise überkommen dich Zweifel und Heimweh – du wirst reisemüde.“
#+end_quote

** Stoppt die Welt, ich will aussteigen! - Note 21                             :quote:done:
#+begin_quote
Reisen ist ein klein wenig wie Glücksrad. Manchmal kann ein winziges Erlebnis deinen Reiseverlauf vollkommen verändern!
#+end_quote

** Stoppt die Welt, ich will aussteigen! - Note 22                             :quote:done:
#+begin_quote
Doch in Summe fand ich Australien kulturell so spannend wie das Steuergesetz von Sachsen-Anhalt.
#+end_quote

** Stoppt die Welt, ich will aussteigen! - Note 23                             :quote:done:
#+begin_quote
Statt mich noch dranzunehmen, machen sie lieber über eine Stunde vorzeitig Feierabend. Unglaublich! Die Menschen hier sind arm, wollen aber auch nicht auf Krampf Geld verdienen. Das nenne ich mal E3: Eine entspannte Einstellung.
#+end_quote

** Stoppt die Welt, ich will aussteigen! - Note 24                             :quote:done:
#+begin_quote
Um den Sorgen-Cocktail im Kopf etwas klarer zu mixen, finde ich Eckhart Tolles’ Frage: „Hast du jetzt ein Problem?“ enorm hilfreich. Natürlich ist die Antwort darauf meistens: „Nein.“ Meditationsübungen machen mir bewusst, dass ich ständig plane, argumentiere, und mir um Dinge Sorgen mache, die überhaupt noch nicht geschehen sind.
#+end_quote

** Stoppt die Welt, ich will aussteigen! - Note 25                             :quote:done:
#+begin_quote
Mir wurde klar, dass ich mit jeder Minute, die ich versuche, eine bessere Option zu finden, die Qualität des Hier und Jetzt mindere.
#+end_quote

** Stoppt die Welt, ich will aussteigen! - Note 26                             :quote:done:
#+begin_quote
Mir wird klar, dass es wahrscheinlich mehr bringt, eine Woche am Strand zu liegen und über den nächsten großen Schritt nachzudenken, der die 10-fache Wirkung in meinem Leben bzw. Geschäft hat, als mich von den vielen kleinen Sachen ablenken zu lassen, die sonst tagtäglich so um einen herumwirbeln.
#+end_quote

** Stoppt die Welt, ich will aussteigen! - Note 27                             :quote:done:
#+begin_quote
Darm mit Charme? Apropos Tauchlehrer. Apropos Klo. Es scheint zwei Reisegesetze zu geben: 1. Gesetz: Immer wenn du musst, ist keine Toilette in der Nähe. 2. Gesetz: Je dringender, desto weiter ist die Toilette entfernt. Oder mathematisch ausgedrückt:
#+end_quote

** Stoppt die Welt, ich will aussteigen! - Note 28                             :quote:done:
#+begin_quote
Lediglich vier „Gs“ werden exerziert: Es wird geplaudert, geschlafen, gegessen und manchmal wohl auch gepoppt.
#+end_quote

** Stoppt die Welt, ich will aussteigen! - Note 29                             :quote:done:
#+begin_quote
Peter öffnet mir die Augen, was das Leben mit einer Yacht anbelangt. Er verrät mir, dass viele all ihr Geld in ein Boot gesteckt haben und kein richtiges Zuhause mehr haben. So ein Kutter will getankt, repariert, gestrichen werden. Hinzu kommen Liegegebühren an den Häfen. Wer dazu lange auf hoher See verbringt, kann nur schwer Geld hinzuverdienen. Mit dem Ideal-Aussteiger-Bild von der Luxusyacht und zwei Model-Miezen drauf hat das Leben, das Peter beschreibt, nichts zu tun.
#+end_quote

** Stoppt die Welt, ich will aussteigen! - Note 30                             :quote:done:
#+begin_quote
Dann ist da noch die Sache mit den Fakaleitis: Bereits bei meiner Ankunft auf Vava‘u servierte mir im Hafenblick-Café ein Mann mit Kleid, Zöpfen und Brüsten mein Frühstück. Stell dir vor, du lebst in Tonga, einer sehr traditionellen Gesellschaft. Du bekommst einen Sohn. Wunderbar! Du bekommst einen zweiten. Gut. Das dritte Kind ist: wieder ein Sohn. Verdammt! Jemand muss aber die Wäsche waschen! Ene, mene, muh und raus bist: DU! Zack, werden dem Buben Mädchensachen angezogen, und er wird als Frau sozialisiert. Mama mia!
#+end_quote

** Stoppt die Welt, ich will aussteigen! - Note 31                             :quote:done:
#+begin_quote
Manchmal wissen wir gar nicht, was wir erwarten. Wir erwarten einfach, dass es perfekt ist. Immerhin leben wir in einer Welt der unbegrenzten Möglichkeiten! Ich nehme meine Ruhelos-Symptome mal genauer unter die Lupe: leichte, unerklärbare Unzufriedenheit, Rastlosigkeit, Gedankenknäuel im Kopf, Angst vor Langeweile und stelle medizinisch einwandfrei fest: Ich habe „Zuvielitis“!
#+end_quote

** Stoppt die Welt, ich will aussteigen! - Note 32                             :quote:done:
#+begin_quote
Nicht nur Berlin bietet viel Auswahl, das Internet erschwert die Wahl zusätzlich und zeigt uns Millionen Möglichkeiten. Es gibt Tausende Produkte, Webseiten, Jobmöglichkeiten und Wege unseren Tag zu verbringen. Das ist eine Unmenge an Möglichkeiten, eine Multi-Optionalisierung des Lebens, die zur Überfrachtung der Sinne führt. Wir haben zu viele Informationen, Angebote, Wahlmöglichkeiten.
#+end_quote

** Stoppt die Welt, ich will aussteigen! - Note 33                             :quote:done:
#+begin_quote
Mein Kopf plant, kalkuliert, wägt ab. Wo soll ich als nächstes hin? Es ist paradox: Ich bin vollkommen flexibel und dennoch gelähmt. Es gibt einfach noch zu viele Länder, Städte, Abenteuer. Das überwältigt mich wie die fiese große Welle beim Surfen heute morgen.
#+end_quote

** Stoppt die Welt, ich will aussteigen! - Note 34                             :quote:done:
#+begin_quote
Ohne Ziele bist du offen für Neues, für Menschen, Experimente. Ohne Takt, Routine, Pläne kannst du dich öffnen, ändern, in unerwartete Richtungen weiterentwickeln.
#+end_quote

** Stoppt die Welt, ich will aussteigen! - Note 35                             :quote:done:
#+begin_quote
Ich will meinen Fokus nicht aufs Sehen, sondern aufs Sein richten. Tolle Erlebnisse sind mir wichtiger als möglichst viele Sehenswürdigkeiten abzuhecheln.
#+end_quote

** Stoppt die Welt, ich will aussteigen! - Note 36                             :quote:done:
#+begin_quote
Diese Gedanken und Abwägungen sind an sich berechtigt und müssen irgendwann mal zu Entscheidungen führen. Aber nicht der Inhalt der Gedanken ist das Problem, sondern die Art des Denkens: Mein Gehirn führt ein Eigenleben.
#+end_quote

** Stoppt die Welt, ich will aussteigen! - Note 37                             :quote:done:
#+begin_quote
Du kannst vor der Kälte, dem Lärm, vor deinem Boss, Nachbarn oder gar vor Verwandten weglaufen. Aber nicht vor dir selbst. Auf einer Reise nimmst du alles mit: deine Persönlichkeit, deine Stärken, Schwächen, Wünsche, Ängste, antrainierte Verhaltensmuster. Eigentlich ist das genau das Schöne am Allein-Reisen, dass die eigenen Ecken und Kanten viel bewusster werden.
#+end_quote

** Stoppt die Welt, ich will aussteigen! - Note 38                             :quote:done:
#+begin_quote
Man glaubt es kaum: Tahiti gehört zu Frankreich und damit zur EU! Es gibt zwar eine eigene Währung, aber faktisch bin ich zuhause in Europa.
#+end_quote

** Stoppt die Welt, ich will aussteigen! - Note 39                             :quote:done:
#+begin_quote
Die ruhigen Offline-Tage helfen. Ich liege auf meinem Sonnensteg am Wasser, lese, denke, höre Musik, meditiere und mache ganz viel: nix. So komme ich richtig zur Ruhe und in die Tiefenentspannung. Ganz für mich allein.
#+end_quote

** Stoppt die Welt, ich will aussteigen! - Note 40                             :quote:done:
#+begin_quote
Ich kombiniere alle Fakten und Eindrücke, die ich bisher auf der Insel sammeln konnte: seltsame Erdhäuser; ausgehöhlte Lavatunnel; ein totes, halb verwestes Pferd auf dem Wanderweg; die größte Satellitenschüssel, die ich je gesehen habe; die mysteriöse Kokosnuss-Zeichnung. Das alles kann nur eins bedeuten: Elvis hält sich auf dieser Insel versteckt!
#+end_quote

** Stoppt die Welt, ich will aussteigen! - Note 41                             :quote:done:
#+begin_quote
Inzwischen glaube ich, diese überspäten Zeiten sind von der Drogen- und Energydrink-Industrie herbeigeführt. Und die Clubbesitzer werden entführt, geknebelt und verscharrt, wenn sie vor Mitternacht öffnen. Passenderweise fragt der Argentinier, der mich hierher geschleppt hat: „SPEED?“ Und ich denke, oho, jetzt wirft der ’ne Pille. Denkste, „Speed“ heißt hier der lokale Energy-Drink. Heute Abend sind hier alle auf SPEED.
#+end_quote

** Stoppt die Welt, ich will aussteigen! - Note 42                             :quote:done:
#+begin_quote
Nach einigen nostalgischen Sackgassen des Festhaltens und Hinterhertrauerns ist mir klar geworden: Von einigen Menschen müssen wir uns trennen, um uns weiterentwickeln zu können. Wir würden sonst nie andere Dinge tun als soziale Netzwerke zu pflegen.
#+end_quote

** Stoppt die Welt, ich will aussteigen! - Note 43                             :quote:done:
#+begin_quote
Dennoch reklamiert der Fahrer in nur kontextuell verständlichem „Portuhhh-gäsch“, dieses Ziel würde 5 Euro mehr kosten. Nö, oder?
#+end_quote

** Stoppt die Welt, ich will aussteigen! - Note 44                             :quote:done:
#+begin_quote
Ich versuche den Tanz zu zweit. Nein, ich versuche es nicht, ich habe keine Wahl: Ich werde versucht! Doch meine Hüften sind beweglich wie deutscher Panzerstahl im Vergleich zu den gelenklosen Brasilianerinnen. Strategischer Rückzug auf die Empore! Hier kann ich die aufgeheizte Stimmung aus sicherer Entfernung genießen.
#+end_quote

** Stoppt die Welt, ich will aussteigen! - Note 45                             :quote:done:
#+begin_quote
Ich bin nun schon die vierte Woche in Cartagena. Da ist mir passiert, was vielen Reisenden irgendwo passiert. Schlüssel und Schloss haben sich gefunden. Es hat *Klick!* gemacht. Es ist meine „Soul-City“ geworden.
#+end_quote

** Stoppt die Welt, ich will aussteigen! - Note 46                             :quote:done:
#+begin_quote
Schöne Bildungsreise! Ich finde, die Zeit ist reif für mutigere Deals: „Beim Kauf von drei Brüsten erhalten Sie eine halbe Arschbacke gratis.“ „Ab 20 Liter Fettabsaugen gibt’s ein Nutella-Jumboglas dazu.“ „30-Tage-Geld-zurück-Garantie, falls Ihre neue Nase zu sehr an Mike Krüger erinnert.“
#+end_quote

** Stoppt die Welt, ich will aussteigen! - Note 47                             :quote:done:
#+begin_quote
Plane pro Woche nur ein Highlight für deine Reise ein. Der Rest füllt sich von allein. Diese tolle Faustregel half mir enorm bei der Planung meiner Reise!
#+end_quote

** Stoppt die Welt, ich will aussteigen! - Note 48                             :quote:done:
#+begin_quote
Passend zu meiner Diskussion mit meiner Freundin spreche ich mit meinem Kumpel Patrick am Telefon über das ewige Gefühl, irgendetwas zu verpassen. Und darüber, dass viele Leute von Ort zu Ort rennen, blind Fotos schießen und sofort weiter zur nächsten Sehenswürdigkeit hecheln. Sie sehen viel, doch verstehen nichts. Und wenn sie damit fertig sind, sind sie durch.
#+end_quote

** Stoppt die Welt, ich will aussteigen! - Note 49                             :quote:done:
#+begin_quote
Die erste dieser Lebensweisheiten geht tatsächlich auf den amerikanischen Ingenieur Edward A. Murphy zurück, der bei einem Test für die US Air Force beobachtete: „Wenn es mehrere Möglichkeiten gibt, eine Aufgabe zu erledigen, und eine davon in einer Katastrophe endet, wird es jemand genauso machen.“ Dieses „Gesetz“ wurde später in einer Pressekonferenz zitiert und erlangte so weltweit Berühmtheit.
#+end_quote

** Stoppt die Welt, ich will aussteigen! - Note 50                             :quote:done:
#+begin_quote
Am Ende hätte ich mir von dem Geld, das ich ausgegeben habe, auch einen gut ausgestatteten Kleinwagen leisten können. Doch wenn ich mir anschaue, was ich stattdessen erlebt, gesehen, gestaunt, geflucht, verwunden, geschmeckt, gehofft, gebangt, gewonnen, abgeworfen, gelernt, erfahren, gelacht, versucht, gemeistert, bestiegen, entdeckt, gefeiert, gefunden, begriffen, empfunden, überwunden habe, fahre ich lieber bis zu meinem Lebensende Fahrrad!
#+end_quote
