:PROPERTIES:
:ID:       2b147d1b-e3c4-4498-8925-f8f4be301d0b
:END:
#+title: The Oxygen Advantage
#+filetags: :book:
#+date: 2022-05-01

* The Oxygen Advantage
:PROPERTIES:
:FINISHED: 2022-05
:END:
* Description
- Overbreathing
  - [[#The%20Oxygen%20Advantage%20-%20Note%203][The Oxygen Advantage - Note 3]]
  - [[#The%20Oxygen%20Advantage%20-%20Note%2010][The Oxygen Advantage - Note 10]]
  - [[#The%20Oxygen%20Advantage%20-%20Note%2013][The Oxygen Advantage - Note 13]]
  - [[#The%20Oxygen%20Advantage%20-%20Note%2017][The Oxygen Advantage - Note 17]]
- Effects of CO2
  - [[#The%20Oxygen%20Advantage%20-%20Note%202][The Oxygen Advantage - Note 2]]
- Oxygen Saturation ([[#SpO2][SpO2]])
- [[#V%CC%87O2%20Max][V̇O2 Max]]
- [[#BOLT][BOLT]]
- [[#Mouth%20Breathing%20vs%20Nasal%20Breathing][Mouth Breathing vs Nasal Breathing]]
- Videos
  - [[https://www.youtube.com/watch?v=0gtlAAQzENw&ab_channel=OxygenAdvantage][How to breathe during physical exercise]]
    - [[id:1e8e0c61-97ae-4d59-9c14-76ab08b49d8f][The Bohr Effect]]
* Quotes
** The Oxygen Advantage - Note 1                                               :quote:done:
We also recognize the importance of breathing good-quality air, but what about the quantity? How much air should we breathe for optimum health? Wouldn'tit be fair to surmise that air, even more important than food or water for human survival, must also meet basic requirements?

** The Oxygen Advantage - Note 2                                               :quote:done:
#+begin_quote
Carbon Dioxide is the doorway that lets oxygen reach our muscles. If the door is only partially open, only some of the oxygen at our disposal passes through, and we find ourselves gasping during exercise, often with our limbs cramping. If, on the other hand, the door is wide open, oxygen flows through the doorway and we can sustain physical activity longer and at a higher intensity. But to understand how our breathing works we must dig a bit deeper into the crucial role carbon dioxide plays in making it as efficient as possible
#+end_quote

** The Oxygen Advantage - Note 3                                               :quote:done:
#+begin_quote
Just as we have an optimal quantity of water and food to consume each day, we also have an optimal quantity of air to breathe. And just as eating too much can be damaging to our health, so can overbreathing
#+end_quote

** The Oxygen Advantage - Note 4                                               :quote:done:
#+begin_quote
At high altitude the air is thin, which results in reduced atmospheric pressure of oxygen.The body adapts to this environment by increasing the number of red blood cells. Think of red blood cells as your very own Popeye's spinach, only they come from your body instead of out of a can. Upping the presence of red blood cells translates into improved oxygen delivery to the muscles, a reduction of lactic acid buildup, and stronger overall performance, including longer endurance and a lower risk of inflammation and injury. But of course the catch is that high-altitude training is not available to most of us-which brings me to the goal of this.
#+end_quote

** The Oxygen Advantage - Note 7                                               :quote:done:
#+begin_quote
The rate and volume of breathing is determined by receptors in the brain that work in a way similar to a thermostat regulating the heating system in a home. However,instead of monitoring fluctuations in temperature,these receptors monitor the concentration of carbon dioxide and oxygen in your blood, along with the acidity or pH level. When levels of carbon dioxide increase above a certain amount, these sensitive receptors stimulate breathing in order to get rid of the excess gas. In other words, the primary stimulus to breathe is to eliminate excess carbon dioxide from the body
#+end_quote

** The Oxygen Advantage - Note 9                                               :quote:done:
#+begin_quote
Carbon Dioxide is an end product of the natural process of breaking down the fats and carbohydrates we eat. C02 is returned from the tissues and cells to the lungs via blood vessels, and any excess is exhaled. Crucially, however, part of your body's quotient of Carbon Dioxide is retained when you exhale. Correct breathing both relies on and results in the right amount of carbon dioxide being retained in your lungs.Understanding this is just as important for serious athletes as it is for anyone interested in basic fitness or in weight management.
#+end_quote


** The Oxygen Advantage - Note 10                                              :quote:done:
#+begin_quote
Breathing too much for short periods of time is not a significant problem, as no permanent change in the body occurs. However,when we breathe too much over an extended period of days to weeks, a biochemical change takes place inside us that results in an increased sensitivity or lower tolerance to carbon dioxide
#+end_quote

** The Oxygen Advantage - Note 12                                              :quote:done:
#+begin_quote
The crucial point to remember is that hemoglobin releases oxygen when in the presence of Carbon Dioxide. When we overbreathe, too much carbon dioxide is washed from the lungs, blood,tissues,and cells. This condition is called hypocapnia, causing the hemoglobin to hold on to oxygen resulting in reduced oxygen release and therefore reduced oxygen delivery to tissues and organs.
#+end_quote


** The Oxygen Advantage - Note 13                                              :quote:done:
#+begin_quote
It's important to bear in mind at this point that the purpose of breathing is to get rid of the excess carbon dioxide, and not to get rid of as much as possible. Overbreathing for a period of days and weeks,however,removes more carbon dioxide than is necessary, increasing the sensitivity of the brain's receptors
#+end_quote

** The Oxygen Advantage - Note 14                                              :quote:done:
#+begin_quote
When breathing receptors are less sensitive to carbon dioxide levels, you will experience a reduction in breathlessness as your body is able to work harder with far less effort; breathing will be lighter during both rest and physical exercise.
#+end_quote

** The Oxygen Advantage - Note 17                                              :quote:done:
#+begin_quote
Dr. Price's discovery illustrates the link between modern diet and chronic hyperventilation. Processed foods are mucus and acid forming. Throughout evolution, our diet consisted of 95 percent alkaline-forming and 5 percent acid- forming foods. Nowadays the reverse is true: Our diet is 95 percent acid-and 5 percent alkaline-forming foods. Acid-forming foods- such as processed products, dairy, meat, bread, sugar, coffee, and tea-stimulate breathing. A natural response to experiencing a greater demand to breathe is to open the mouth to take in more air. Over time, the brain adjusts to this larger intake of air,and overbreathing becomes a habit.
#+end_quote

** The Oxygen Advantage - Note 22                                              :quote:done:
#+begin_quote
The production of nitric oxide in the nasal sinuses can be increased by simply humming. In an article published in the American Journal of Respiratory and Critical Care Medicine, Doctors Weitzberg and Lundberg described how humming increased nitric oxide up to fifteenfold in comparison with quiet exhalation. They concluded that humming causes a dramatic increase in sinus ventilation and nasal nitric oxide release link zu nose songs.
#+end_quote

** The Oxygen Advantage - Note 23                                              :quote:done:
#+begin_quote
Well-known qigong and tai chi Master Chris Pei explains how breathing is at the very core of the Chinese concept of chi (qi):“Generally speaking,there are three levels of breathing. The first one is to breathe softly, so that a person standing next to you does not hear you breathing. The second level is to breathe softly so that you do not hear yourself breathing.And the third level is to breathe softly so that you do not feel yourself breathing.
#+end_quote

** The Oxygen Advantage - Note 24                                              :quote:done:
#+begin_quote
Train Your Body to Do More with Less To reap the most benefit from your physical training,you need to train your body to do more with less. To do this,you will need to reduce your air intake. Incorporating this concept into your training will result in improved breathing economy and an increase in your athletic performance, along with reduced breathlessness and lactic acid during competition
#+end_quote

** The Oxygen Advantage - Note 25                                              :quote:done:
#+begin_quote
It takes time for the body to warm up, but when it does, your body is able to function more effectively during exercise.When your body is warmed up prior to exercise, the following benefits can be maximized: ·The production of more carbon dioxide-improving the release of oxygen from the blood to tissues and organs-increasing VO2 max, improving endurance, and reducing the risk of injury The opening of blood vessels and airways-allowing for better blood flow and easy breathing.
#+end_quote

** The Oxygen Advantage - Note 26                                              :quote:done:
#+begin_quote
Creating an air shortage by holding the breath during your warm-up is vitally important to cause an accumulation of carbon dioxide in the blood before physical exercise commences.
#+end_quote

** The Oxygen Advantage - Note 27                                              :quote:done:
#+begin_quote
Maximal oxygen uptake, or V02 max, refers to the maximum capacity of an individual's body to transport and utilize oxygen during 1 minute of exhaustive exercise. The V refers to volume, the 02 to oxygen, and max to the maximum capacity of your body. Your V02 max is measured by the amount of oxygen that is used during 1 minute of exercise per kilogram of body weight. V02 max is a factor that can determine an athlete's capacity to sustain physical exercise, and is considered to be the best indicator of cardiorespiratory endurance and aerobic fitness. In sports that require exceptional endurance, such as cycling, rowing, swimming, and running,world-class athletes typically have a high VO2 max. The goal of most endurance programs is to increase an individual's V02 max, and this can be achieved by improving the oxygen-carrying capacity of the blood.
#+end_quote

** The Oxygen Advantage - Note 28                                              :quote:done:
#+begin_quote
The spleen is an organ that acts as a blood bank; when the body signals an increased demand for oxygen, the spleen releases stores of red blood cells. It therefore plays a very important role in regulating blood hematocrit (the percentage of red blood cells in the blood), as well as hemoglobin concentration.
#+end_quote

** The Oxygen Advantage - Note 29                                              :quote:done:
#+begin_quote
Higher levels of carbon dioxide in the blood can produce an even greater contraction of the spleen, resulting in an increase in the release of red blood cells and therefore the oxygenation of the blood. Increased CO2 in the blood also causes a rightward shift of the oxyhemoglobin dissociation curve. As described by the Bohr Effect, an increase in carbon dioxide decreases blood pH and causes oxygen to be offloaded from hemoglobin to the tissues, further reducing blood oxygen saturation.
#+end_quote

** The Oxygen Advantage - Note 30                                              :quote:done:
#+begin_quote
In a similar way that breath holding delays the onset of fatigue during sports, countless studies have shown that taking the alkaline agent bicarbonate of soda reduces acidity in the blood to improve endurance.Who would have thought that a cooking ingredient found in almost every kitchen cupboard in the Western world could also improve sports performance? Not only that, but it is a very helpful tool to reduce your breathing volume and increase your BOLT score.
#+end_quote

** The Oxygen Advantage - Note 31                                              :quote:done:
#+begin_quote
Over the years many studies have demonstrated the benefits of bicarbonate of soda as a method to help improve sports performance. During high-intensity training, the availability of oxygen for working muscles decreases,which causes an accumulation of acid, leading to muscle fatigue. By ingesting bicarbonate of soda, you can help to maintain normal blood pH by decreasing lactic acid buildup during anaerobic exercise. This alkaline soda neutralizes the acid that accumulates during high-intensity training, resulting in greater endurance and power output.
#+end_quote

** The Oxygen Advantage - Note 32                                              :quote:done:
#+begin_quote
Normal oxygen saturation at sea level varies between 95 and 99 percent. To receive any benefit from hypoxic (reduced oxygen) training, oxygen saturation levels must drop below 94 percent (and ideally to below 90 percent). The effect of this method depends on two factors:oxygen saturation during training, and the length of the exposure to reduced oxygen. zk hyposia.
#+end_quote

** The Oxygen Advantage - Note 33                                              :quote:done:
#+begin_quote
The primary Oxygen Advantage exercise Nick used was a daily 30-minute routine combining the following: 1. Breathe Light to Breathe Right for 15 minutes. 2. Simulate High-Altitude Training while walking with breath holds of 60 to 80 paces. 3. Rest for 3 to 4 minutes. 4. Do 1 set of Advanced Simulation of High-Altitude Training to reduce arterial blood oxygen saturation to around 81 to 84 percent.
#+end_quote

** The Oxygen Advantage - Note 34                                              :quote:done:
#+begin_quote
Nowadays, as we spend more time communicating via social media, playing computer games, and surfing the Internet,our powers of concentration are diminishing. According to international motivational guru Kevin Kelly,we are now living in an attention- deficit society. The dial has moved from conversation to presentation and from dialogue to monologue. We no longer give each other our undivided attention, and neither do we take the time to observe our own breathing or allow our minds to still.
#+end_quote

** The Oxygen Advantage - Note 35                                              :quote:done:
#+begin_quote
Distracting thoughts, however, will be habitually negative and irrational, often so automatic that the individual is unaware of them. This type of thinking creates tension, draining you of energy and distracting your game. As the Irish writer Oscar Wilde once said, “Thinking is the most unhealthy thing in the world, and people die of it just as they die of any other disease.” Thinking is a habit. We have been taught how to think by the influences of society, education, and our friends and family. From a young age we are conditioned to believe that thinking is a good thing-how many times have you been told to "think about it" or “think it over"? Developing the mind into a sharp analytical tool is obviously very useful for achieving in the world of academics and other livelihoods, and while it is important that we learn how to think, it is equally important that we learn how to stop thinking.
#+end_quote

** The Oxygen Advantage - Note 36                                              :quote:done:
#+begin_quote
Do not be disheartened-this bombardment of thoughts has built up through years of conditioning and will take time to strip away. Layer upon layer of thoughts have been added by every influence in your life: education, religion, society, relationships, and work. The mind has simply developed a bad habit; it knows how to think but is unable to stop thinking.
#+end_quote

** The Oxygen Advantage - Note 37                                              :quote:done:
#+begin_quote
We are conditioned to believe that in order to be productive and successful we must be constantly doing something. This belief, which forms the basis of modern society, is quite insane. We are not human doings; we are human beings. During my workshops, students are often astonished to hear that if l were given the choice between my degree-which I worked so hard for-and learning to reduce my thought activity, I would choose the latter without hesitation.
#+end_quote

** The Oxygen Advantage - Note 38                                              :quote:done:
#+begin_quote
We can live without food for weeks,without water for days, but without air for just a few minutes. In terms of importance for survival, breathing is at the top of the list, followed by water, with food in last place.Health professionals, athletes, and nonathletes alike pay far more attention to their food than thei breathing, but what happens if we switch this focus around? Improve your BOLT score by 10 seconds and you will find your appetite changing. Improve your BOLT score to 40 seconds and your life will change.
#+end_quote

** The Oxygen Advantage - Note 39                                              :quote:done:
#+begin_quote
Conversely, an individual who chronically overbreathes will expel too much carbon dioxide, increasing blood pH to alkaline levels above 7.45. One hypothesis for the relationship between overbreathing and weight gain is that the body craves processed and acid-forming foods in an effort to normalize blood pH. Correct breathing volume and a good diet work together to keep blood pH at a healthy balance.
#+end_quote
