:PROPERTIES:
:ID:       25164e94-c574-43f2-9a89-461f27827df2
:END:
#+title: The 4Hour Work Week
#+filetags: :productivity:book:
#+date: 2018-07-01

* The 4Hour Work Week
:PROPERTIES:
:FINISHED: 2018-07
:END:
** Description
#+begin_quote
What do you do? Tim Ferriss has trouble answering the question. Depending on when you ask this controversial Princeton University guest lecturer, he might answer: "I race motorcycles in Europe." "I ski in the Andes." "I scuba dive in Panama." "I dance tango in Buenos Aires." He has spent more than five years learning the secrets of the New Rich, a fast-growing subculture who has abandoned the "deferred-life plan" and instead mastered the new currencies-time and mobility-to create luxury lifestyles in the here and now. Whether you are an overworked employee or an entrepreneur trapped in your own business, this book is the compass for a new and revolutionary world.

(Source: https://www.goodreads.com/book/show/368593.The_4_Hour_Workweek)
#+end_quote
* Quotes
** The 4Hour Work Week - Note 1                                                :quote:done:
#+begin_quote
Whenever you find yourself on the side of the majority, it is time to pause and reflect. —MARK TWAIN
#+end_quote

** The 4Hour Work Week - Note 2                                                :quote:done:
#+begin_quote
People don’t want to be millionaires—they want to experience what they believe only millions can buy.
#+end_quote

** The 4Hour Work Week - Note 3                                                :quote:done:
#+begin_quote
D: To retire early or young. NR: To distribute recovery periods and adventures (mini-retirements) throughout life on a regular basis and recognize that inactivity is not the goal. Doing that which excites you is.
#+end_quote

** The 4Hour Work Week - Note 4                                                :quote:done:
#+begin_quote
Being financially rich and having the ability to live like a millionaire are fundamentally two very different things.
#+end_quote

** The 4Hour Work Week - Note 5                                                :quote:done:
#+begin_quote
I can’t give you a surefire formula for success, but I can give you a formula for failure: try to please everybody all the time. —HERBERT BAYARD SWOPE,
#+end_quote

** The 4Hour Work Week - Note 6                                                :quote:done:
#+begin_quote
Doing less meaningless work, so that you can focus on things of greater personal importance, is NOT laziness.
#+end_quote

** The 4Hour Work Week - Note 7                                                :quote:done:
#+begin_quote
This is hard for most to accept, because our culture tends to reward personal sacrifice instead of personal productivity.
#+end_quote

** The 4Hour Work Week - Note 8                                                :quote:done:
#+begin_quote
6. Emphasize Strengths, Don’t Fix Weaknesses.
#+end_quote

** The 4Hour Work Week - Note 9                                                :quote:done:
#+begin_quote
Busy yourself with the routine of the money wheel, pretend it’s the fix-all, and you artfully create a constant distraction that prevents you from seeing just how pointless it is. Deep down, you know it’s all an illusion, but with everyone participating in the same game of make-believe, it’s easy to forget.
#+end_quote

** The 4Hour Work Week - Note 10                                               :quote:done:
#+begin_quote
Action may not always bring happiness, but there is no happiness without action.
#+end_quote

** The 4Hour Work Week - Note 11                                               :quote:done:
#+begin_quote
FEAR COMES IN many forms, and we usually don’t call it by its four-letter name. Fear itself is quite fear-inducing. Most intelligent people in the world dress it up as something else: optimistic denial.
#+end_quote

** The 4Hour Work Week - Note 12                                               :quote:done:
#+begin_quote
What we fear doing most is usually what we most need to do.
#+end_quote

** The 4Hour Work Week - Note 13                                               :quote:done:
#+begin_quote
The reasonable man adapts himself to the world; the unreasonable one persists in trying to adapt the world to himself. Therefore all progress depends on the unreasonable man. —GEORGE BERNARD SHAW, Maxims for Revolutionists
#+end_quote

** The 4Hour Work Week - Note 14                                               :quote:done:
#+begin_quote
The opposite of love is indifference, and the opposite of happiness is—here’s the clincher—boredom.
#+end_quote

** The 4Hour Work Week - Note 15                                               :quote:done:
#+begin_quote
Samuel Beckett, a personal hero of mine: ‘Ever tried. Ever failed. No matter. Try again. Fail again. Fail better.’
#+end_quote

** The 4Hour Work Week - Note 16                                               :quote:done:
#+begin_quote
The best first step, the one I recommend, is finding someone who’s done it and ask for advice on how to do the same. It’s not hard.
#+end_quote

** The 4Hour Work Week - Note 17                                               :quote:done:
#+begin_quote
Learn to Eye Gaze
#+end_quote

** The 4Hour Work Week - Note 18                                               :quote:done:
#+begin_quote
Perfection is not when there is no more to add, but no more to take away. —ANTOINE DE SAINT-EXUPÉRY,
#+end_quote

** The 4Hour Work Week - Note 19                                               :quote:done:
#+begin_quote
EFFECTIVENESS IS DOING the things that get you closer to your goals. Efficiency is performing a given task (whether important or not) in the most economical manner possible.
#+end_quote

** The 4Hour Work Week - Note 20                                               :quote:done:
#+begin_quote
Being busy is a form of laziness—lazy thinking and indiscriminate action.
#+end_quote

** The 4Hour Work Week - Note 21                                               :quote:done:
#+begin_quote
lack of time is actually lack of priorities.
#+end_quote

** The 4Hour Work Week - Note 22                                               :quote:done:
#+begin_quote
Since we have 8 hours to fill, we fill 8 hours. If we had 15, we would fill 15. If we have an emergency and need to suddenly leave work in 2 hours but have pending deadlines, we miraculously complete those assignments in 2 hours.
#+end_quote

** The 4Hour Work Week - Note 23                                               :quote:done:
#+begin_quote
Parkinson’s Law dictates that a task will swell in (perceived) importance and complexity in relation to the time allotted for its completion. It is the magic of the imminent deadline.
#+end_quote

** The 4Hour Work Week - Note 24                                               :quote:done:
#+begin_quote
Use Parkinson’s Law to accomplish more in less time. Shorten schedules and deadlines to necessitate focused action instead of deliberation and procrastination.
#+end_quote

** The 4Hour Work Week - Note 26                                               :quote:done:
#+begin_quote
What information consumes is rather obvious: it consumes the attention of its recipients. Hence, a wealth of information creates a poverty of attention and a need to allocate that attention efficiently among the overabundance of information sources that might consume it. —HERBERT
#+end_quote

** The 4Hour Work Week - Note 27                                               :quote:done:
#+begin_quote
Practice the art of nonfinishing.
#+end_quote

** The 4Hour Work Week - Note 29                                               :quote:done:
#+begin_quote
Meetings are an addictive, highly self-indulgent activity that corporations and other organizations habitually engage in only because they cannot actually masturbate. —DAVE BARRY,
#+end_quote

** The 4Hour Work Week - Note 31                                               :quote:done:
#+begin_quote
there is a difference between being perceived as an expert and being one.
#+end_quote

** The 4Hour Work Week - Note 33                                               :quote:done:
#+begin_quote
Google Adwords Keyword Tool (http://adwords.google.com/select/KeywordToolExternal) Enter the potential search terms to find search volume and alternative terms with more search traffic. Click on the “Approx Avg Search Volume” column to sort results from most to least searched.
#+end_quote

** The 4Hour Work Week - Note 34                                               :quote:done:
#+begin_quote
I used 99Designs to get an excellent logo for www.litliberation.org in 24 hours for less than $150. I submitted the concept, more than 50 designers worldwide uploaded their best attempts, which I could browse, and I chose the best after suggesting a few improvements. From Crowdspring’s site: “Name your price, name your deadline, see entries within hours and be done in just days. The average project gets a whopping 68 entries. 25 entries or your money back.”
#+end_quote

** The 4Hour Work Week - Note 35                                               :quote:done:
#+begin_quote
Fortunately, a few simple steps can dramatically upgrade your budding Fortune 500 image and take your muse from coffee shop to boardroom in 45 minutes or less.
#+end_quote

** The 4Hour Work Week - Note 37                                               :quote:done:
#+begin_quote
By working faithfully eight hours a day, you may eventually get to be a boss and work twelve hours a day. —ROBERT FROST,
#+end_quote

** The 4Hour Work Week - Note 38                                               :quote:done:
#+begin_quote
In Japan, a three-piece zombie who joins the 9–5 grind each morning is called a sarari-man—salaryman—and, in the last few years, a new verb has emerged: datsu-sara suru, to escape (datsu) the salaryman (sara) lifestyle. It’s your turn to learn the datsu-sara dance.
#+end_quote

** The 4Hour Work Week - Note 39                                               :quote:done:
#+begin_quote
TO CREATE THE proper leverage to be unshackled, we’ll do two things: demonstrate the business benefit of remote working and make it too expensive or excruciating to refuse a request for it.
#+end_quote

** The 4Hour Work Week - Note 40                                               :quote:done:
#+begin_quote
Sherwood wants the company to invest as much as possible in him so that the loss is greater if he quits.
#+end_quote

** The 4Hour Work Week - Note 41                                               :quote:done:
#+begin_quote
Third, Sherwood creates a bullet-point list of how much more he achieved outside the office with explanations. He realizes that he needs to present remote working as a good business decision and not a personal perk.
#+end_quote

** The 4Hour Work Week - Note 42                                               :quote:done:
#+begin_quote
Sherwood didn’t expect to get two days per week approved. He asked for two so that, in the case his boss refused, he could ask for just one as a fallback position (bracketing).
#+end_quote

** The 4Hour Work Week - Note 43                                               :quote:done:
#+begin_quote
Sherwood: What’s your main concern?64 Bill: It seems like you’re on your way out. I mean, are you going to quit on us? Second, what if everyone wants to do the same?
#+end_quote

** The 4Hour Work Week - Note 44                                               :quote:done:
#+begin_quote
He realizes that, just as you want to negotiate ad pricing close to deadlines, getting what you want often depends more on when you ask for it than how you ask for it.
#+end_quote

** The 4Hour Work Week - Note 45                                               :quote:done:
#+begin_quote
Recently, I was asked if I was going to fire an employee who made a mistake that cost the company $600,000. No, I replied, I just spent $600,000 training him. —THOMAS J. WATSON,
#+end_quote

** The 4Hour Work Week - Note 46                                               :quote:done:
#+begin_quote
Would you like me to give you a formula for success? It’s quite simple, really. Double your rate of failure. —THOMAS J. WATSON,
#+end_quote

** The 4Hour Work Week - Note 47                                               :quote:done:
#+begin_quote
There are two types of mistakes: mistakes of ambition and mistakes of sloth.
#+end_quote

** The 4Hour Work Week - Note 48                                               :quote:done:
#+begin_quote
I-Resign (www.i-resign.com)
#+end_quote

** The 4Hour Work Week - Note 49                                               :quote:done:
#+begin_quote
There is more to life than increasing its speed. —MOHANDAS GANDHI
#+end_quote

** The 4Hour Work Week - Note 50                                               :quote:done:
#+begin_quote
The mini-retirement is defined as recurring—it is a lifestyle.
#+end_quote
