:PROPERTIES:
:ID:       2965cd54-8ffb-48a1-9b88-07ca58f97469
:END:
#+title: The Wim Hof Method
#+created: 20201229214719757
#+finished_month: 12
#+finished_year: 2020
#+genres: Health
#+goodreads: https://www.goodreads.com/book/show/50403522-the-wim-hof-method
#+filetags: book
#+date: 2020-12-01

* Description
- breathing
  - through breathe exercises you can control the ratio of [[#Carbon%20Dioxide][CO2]] and oxygen in your blood
  - breathing reflex is correlated to the amount of CO2 in your blood
    - while exhaling more C02 breathe retention time increases
  - causes *ph* level to increase because CO2 is an *acid* and once exhaled, it brings body to a temporary *alkaline* level
- books
  - [[https://www.lovelybooks.de/autor/Wilfried-Ehrmann/Handbuch-der-Atem-Therapie-917154250-w/][Das Handbuch der Atem-Therapie]]
* Quotes
** The Wim Hof Method - Note 1                                                 :quote:done:
#+begin_quote
A cold shower a day keeps the doctor away.
#+end_quote
** The Wim Hof Method - Note 2                                                 :quote:done:
#+begin_quote
So I asked myself: What did you do on Mount Everest? What did you do in the icy
waters beyond the Polar Circle? What did you do always in the cold? You trusted
yourself. You believed in your heart that you could do it, and with that state
of mind, you went into those challenges with confidence and succeeded. Why
shouldn't I be able to do that today?
#+end_quote
** The Wim Hof Method - Note 3                                                 :quote:done:
#+begin_quote
Cold is merciless, but it is absolutely righteous.
#+end_quote
** The Wim Hof Method - Note 4                                                 :quote:done:
#+begin_quote
People come to me with questions like, "Should I breathe through the nose?" or
"The [[id:44c42914-2c5e-42b8-b1ae-de8beceed00c][Diaphragm]] this or that", and I just say, "Yeah, breathe, motherfuckers!
Don't think, just do it! Get into the depth of your own lungs!"
#+end_quote
** The Wim Hof Method - Note 5                                                 :quote:done:
#+begin_quote
Yoga means connection; it comes from the verb /yug/, and /yug/ is "to connect". This
is what the author of [[id:ed77eeaa-5166-498d-969c-f97301f244c8][The Yoga Sutras of Patanjali]] write 16 hundred years ago
or so, more or less. It still holds. "Yoga is silencing the modifications of the
mind, then the seer dwells in his own nature".
#+end_quote
** The Wim Hof Method - Note 6                                                 :quote:done:
#+begin_quote
People get hung up on getting the breathing right. They think it is too simple
to work. They ask me, "How do you do it, Wim? Is it with the nose, or the mouth?
Do i fill the belly, the [[id:44c42914-2c5e-42b8-b1ae-de8beceed00c][Diaphragm]]? Or do you have to close one nostril and then
the other? Do I fill the lungs all the way, or not too much, or ... " And I say:
"It doesn't matter what kind of hole you use here, just get it in".
#+end_quote
