Content-Type: text/enriched
Text-Width: 80

<x-color><param>#5B6268</param>:PROPERTIES:</x-color>
<x-color><param>#83898d</param>:ID:</x-color>       <x-color><param>#83898d</param>05a8e9a4-872a-45af-a7eb-52827db9a360</x-color>

<x-color><param>#5B6268</param>:END:</x-color>

#+title: <bold><x-color><param>#c678dd</param>The Lonely Century

</x-color></bold>#+date: <x-color><param>#c678dd</param>2023-01-05

</x-color><x-color><param>#83898d</param>#+filetags: :society:book:</x-color>


<x-color><param>#51afef</param>https://www.goodreads.com/book/show/50695158-the-lonely-century</x-color>


* Own summary

Do you feel invisible when you're in the city and everybody just walks by without any eye contact, completely ignoring your existence? Are you already suffering from Zoom fatigue and sick of meeting your colleagues in a virtual environment? Or maybe you're lucky enough and do have an office but everybody headphones while moving from A to B, signaling (fake) busyness and some sort of "I don't want to talk to you now. So please respect my right to isolate myself from the rest of the world."


If you already have these symptoms, it's tempting to think it's only related to one life area (e.g. job, friends). But no, it's more than that: Do you feel disconnected from your relatives and friends despite all the modern and endless communication options? Did you also notice how public space (parks, playgrounds, cafes, libraries) seems to change in the favour of malls, housing complexes, co-working spaces, industry areas? In the worst-case scenario you have completely lost trust in politics, faith in humanity and feel how society has become "exclusive".


If you've answered most of these questions with YES, most likely you feel alone. But you're not the only one - at least in this aspect you're _<underline>not</underline>_ alone. In her book "<x-color><param>#51afef</param>[[https://www.goodreads.com/book/show/50695158-the-lonely-century][The lonely century]]</x-color>" Noreena Hertz systematically analyzes why people all over the world suffer from loneliness and how tech and politics play a vital role in amplifying feelings of frustration, misbeliefs, rage, angst, anger among people. And while COVID-19 has brought the biggest "social distancing" experiment ever, the foundations of today's loneliness at a society level have been layed long before the pandemic. Although some of the reading is quite depressing (especially the chapter about robots, automatization and how more and more people will lose their jobs), this books serves as a reminder and manual of ideas meant to restore human connnections where "social" media and neoliberal policies have been pulling us apart. So, put your smartphone down, start being aware of your surroundings, reconnect with nature, talk to people around you, engage in communities, support local stores, take initiatives, do not isolate yourself.


BTW: You can measure your subjective feeling of loneliness using the "<x-color><param>#51afef</param>[[https://psytests.org/ipl/uclaen.html][UCLA Loneliness scale]]</x-color>".


* Notes in Romanian

<x-color><param>#282c34</param>*</x-color>* Definiția singurătății


<x-color><param>#5B6268</param>#+begin_quote

</x-color><italic>Diferența esențială dintre definiția dată de mine singurita (cea la care mă voi reporta de-a lungul acestei cărți) şi cea clasică este că eu văd *</italic><bold><italic>singurătatea ca pe ceva mai mult decât lipsa iubirii, companiei sau intimității</italic></bold><italic>*. Şi reprezintă mai mult decât sentimentul de a fi ignorat, nevăzut şi nesusținut de cei cu care interacționăm zi de zi: partenerul, familia, prietenii şi vecinii noştri. Definiția mea se referă şi la *</italic><bold><italic>lipsa susţinerii din partea celorlalţi cetăţeni</italic></bold><italic>*, din partea propriului angajator, a comunităţii şi a statului. Și aici mă refer nu doar la sentimentul că nu suntem legați de cei cu care ar trebui să fim apropiați, ci şi la senzația ca suntem rupți de noi înşine. Nu e vorba doar de lipsa susținerii în context social şi familial, ci şi despre *</italic><bold><italic>sentimentul de excludere politică şi economică</italic></bold><italic>*.


Eu definesc singurătatea ca fiind atât o *</italic><bold><italic>stare internă, cât şi una existențială-personală, socială, economică și politică.</italic></bold><italic>*


Astfel, definiția mea se apropie mai mult de cea propusă de gânditori precum Karl Marx, Émile Durkheim, Carl Jung şi Hannah Arendt, precum şi de scriitori ca Isaac Asimov, Aldous Huxley, George Eliot şi, mai recent, creatorul serialului Black Mirror, Charlie Brooker."


Influențate de globalizare, urbanizare, de disparități economice şi asimetrii politice, de schimbări demografice, de mobilitatea tot mai a populaţiei, de intruziunea tehnologiei, austeritate, iar acum şi de pandemia de COVID-19, cred că formele de azi ale singurătății transcend nevoia noastră de conectare fizică cu cei din jur, nevoia de a iubi și a fi iubiți, precum și singurătatea resimțită atunci când ne considerăm lipsiți de prieteni.
</italic>#+end_quote


<x-color><param>#282c34</param>*</x-color>* Capitalismul neoliberal


<x-color><param>#5B6268</param>#+begin_quote

</x-color><italic>*</italic><bold><italic>Fundamentul ideologic</italic></bold><italic>* al crizei singurătății din secolul XXI *</italic><bold><italic>precedă tehnologia digitală, ultimul val de urbanizare, schimbările radicale survenite la locul de muncă, criza financiară din 2008, precum şi pandemia de COVID-19</italic></bold><italic>*.


Totul a început de fapt prin anii '80, atunci când capitalismul a luat o formă destul de aspră: *</italic><bold><italic>neoliberalismul, o ideologie care pune accentul îndeosebi pe libertate-alegere,,liberă", piețe,libere", „eliberarea" de influența guvernelor sau a sindicatelor</italic></bold><italic>*. Această ideologie propovăduia o formă idealizată de independență, guvern minimal şi competiție acerbă, care punea interesul de sine mai pre sus de comunitate şi de binele colectiv. Promovat initial de Margaret Thatcher şi Ronald Reagan, şi mai târziu adoptat de politicienii care au urmat cea de-a treia cale", precum Tony Brair, Bill Clinton şi Gerhard Schröder, acest curent politic a dominat practicile economice şi guvernamentale din ultimele două decenii.


Această ideologie a jucat un rol fundamental în criza actuală a singurătății pentru că, în primul rând, a dus la o creştere semnificativă a decalajului în ceea ce priveşte veniturile şi averile locuitorilor din numeroase țări ale lumii. În Statele Unite, în 1989, directorii executivi ai companiilor câştigau în medie de 58 de ori mai mult decât salariul unui muncitor obişnuit; în 2018 însă, aceştia câştigau de 278 de ori mai mult." În Marea Britanie, ponderea veniturilor celor mai bogati 1% s-a triplat în ultimii patruzeci de ani, cei mai înstăriți 10% deţinând acum de cinci ori mai multă avere decât cei mai săraci 50%.


[...]


În al treilea rând, capitalismul neoliberal ne-a redefinit profund nu doar relațiile economice, dar şi relațiile cu ceilalți. Această ideologie nu a fost niciodată doar o politică economică, după cum mărturisea Margaret Thatcher în 1981, când a declarat publicației Sunday Times că: *</italic><bold><italic>„Economia este doar metoda. Însă scopul este acela de a schimba felul nostru de a fi."</italic></bold><italic>* Şi, din multe puncte de vedere, neoliberalismul a reuşit să-şi atingă ținta. Pu nând mai ales accentul pe calități precum competitivitatea acerbă şi urmărirea propriului interes, indiferent de consecințe, *</italic><bold><italic>neoliberalismul a schimbat fundamental relațiile dintre oameni şi obligațiile pe care le simteam unii faţă de ceilalți.</italic></bold><italic>*
</italic>#+end_quote


<x-color><param>#282c34</param>*</x-color>* Afecțiunea psihologică


<x-color><param>#5B6268</param>#+begin_quote

</x-color><italic>Cu adevărat uimitor e că singurătatea ca afecțiune psihologică a început să fie studiată amănunţit în domeniul psihiatriei abia în ultimii aproximativ zece ani. Fără a fi considerată o afecțiune psihică de sine stătătoare, se acceptă faptul că se află în strânsă legătură cu o serie întreagă de afecțiuni psihice, inclusiv cu anxietatea şi depresia. Relaţia este reciprocă. Un studiu din 2012 asu- pra a 7.000 de adulți din Marea Britanie a demonstrat că cei ce suferă de depresie sunt de zece ori mai predispuşi la singurătate decât cei ce nu suferă de această afecțiune." În acelaşi timp, un studiu adesea citat din Statele Unite, pe parcursul căruia partici panții au fost analizați timp de cinci ani, ne arată că cei ce au de- clarat inițial că se simteau singuri au fost şi cei ce aveau să sufere mai degrabă de depresie cinci ani mai târziu, spre deosebire de cei ce nu raportaseră astfel de sentimente."
</italic>#+end_quote


<x-color><param>#282c34</param>*</x-color>* Despre populiști


<x-color><param>#5B6268</param>#+begin_quote

</x-color><italic>Prin *</italic><bold><italic>populisti</italic></bold><italic>* vreau să spun politicieni care *</italic><bold><italic>instigă poporul</italic></bold><italic>*", pe care pretind nu doar că îl reprezintă, ci şi că ar fi singurii capabili de-a o face, *</italic><bold><italic>împotriva unei ,,elite" economice</italic></bold><italic>*, politice sau culturale, de regulă demonizate; o „elitä" care include de obicei instituțiile cheie care mențin funcțională o societate onestă şi tolerantă, cum ar fi parlamentul, justiția sau presa liberă. În cazul populiştilor de dreapta în special, retorica acestora pune *</italic><bold><italic>mai ales accent pe diferentele culturale şi pe importanța identității naționale, ei spunând adesea că țara se află sub ameninţarea unei invazii" din partea imigranților sau a celor de etnii sau religii diferite</italic></bold><italic>*. Această atitudine reprezintă o amenințare gravă pentru o societate solidară, în care există respect pentru instituțiile şi legile care ne unesc, precum şi un pericol la adresa toleranței, înţelegerii şi dreptății. *</italic><bold><italic>Aceşti politicieni încearcă mai degrabă să scindeze societatea, nu să o unească, fiind dispuşi să amplifice tensiunile rasiale, religioase şi etnice, dacă ele le servesc scopurile</italic></bold><italic>*. Oamenii singuri, neîncrezători şi anxioşi, disperați să fie acceptați, dar deseori văzând în jur numai şerpi", sunt tinta ideală- dar şi cea mai vulnerabilă.
</italic>#+end_quote


<x-color><param>#282c34</param>*</x-color>* <x-color><param>green</param><x-color><param>green</param>TODO</x-color></x-color> Book recommendation


Hannah Arendt (sisteme totalitare?)


<x-color><param>#282c34</param>*</x-color>* Orașul solitar


<x-color><param>#5B6268</param>#+begin_quote

</x-color><italic>Copleșiți de agitația și de zgomotul oraşului, precum şi de constanta prezenţă a stimulilor vizuali, avem tendinţa, şi asta chiar înainte de pande mie, să ne distanțăm social-nu neapărat fizic, cât psihologic, mergând pe străzi cu căştile în urechi, cu ochelari de soare sau adânciți cu totul în lumea izolantă a telefonului mobil." Mulțumită celor de la Apple, Google, Facebook sau Samsung, n-a fost niciodată mai uşor să te rupi pur și simplu de oamenii şi de locu rile din jur şi să te retragi în lumea digitală, complet antisocială. Desigur, paradoxal e că, pe măsură ce ne îndepărtăm de mulțimea de oameni din lumea reală, ne afundăm în lumea virtuală care ne arată viața altora prin pozele de pe Instagram sau postările lor de pe Twitter.
</italic>#+end_quote


<x-color><param>#282c34</param>*</x-color>* Epoca fără contact


<x-color><param>#5B6268</param>#+begin_quote

</x-color><italic>Instituționalizarea unei vieți fără contact mă îngrijorează cu adevărat. Nu ne vom simți oare inevitabil mai *</italic><bold><italic>singuri odată ce factorul uman este eliminat treptat din tranzacțiile noastre zilnice</italic></bold><italic>*? Dacă viaţa noastră agitată de la oraş nu mai este întreruptă de cele câteva vorbe cu casierița de la casa de marcat sau de glumele cu barmanul, dacă nu mai vedem fața prietenoasă a celui care ne face un sendviş sau zâmbetul încurajator al instructorului de yoga atunci când reuşim să stăm pentru prima dată în mâini, dacă pierdem *</italic><bold><italic>beneficiile tuturor acelor microinteracțiuni</italic></bold><italic>* care ne fac să ne simtim mult mai legați unii de alții, nu este oare inevitabil ca izolarea şi separarea să se adâncească?
</italic>#+end_quote


<x-color><param>#282c34</param>*</x-color>* Ecranul nostru, sinele nostru


<x-color><param>#5B6268</param>#+begin_quote

</x-color><italic>„*Rețelele sociale marchează o nouă eră prin intensitatea, densitatea şi omniprezența mecanismelor de comparație socială, mai ales printre cei mai tineri dintre noi*, care sunt «aproape întot- deauna on-line>> într-un moment din viață în care propria iden titate, voce şi discernământ nu sunt în întregime conturate", scrie Shoshana Zuboff, profesor la Universitatea Harvard. *</italic><bold><italic>„Tsunamiul psihologic al comparațiilor sociale declanşate de rețelele sociale este fără precedent"</italic></bold><italic>*</italic><bold><italic>, continuă aceasta. *<bold>Problema o reprezintă necesitatea constantă de a ne vinde - şi teama că nimeni nu va fi interesat să cumpere</bold></italic></bold><bold><italic>*.
</italic>#+end_quote


<x-color><param>#282c34</param>*</x-color>* Economist singurătății

<x-color><param>#282c34</param>**</x-color>* Efervescență colectivă


<x-color><param>#5B6268</param>#+begin_quote

</x-color><italic>Într-o lume în care comunitatea pare tot mai greu de regăsit şi în care dorința de apartenenţă încă nu a dispărut, companiile au început să umple aceste goluri. Economia singurătății a început să înflorească - şi nu doar în forma sa tehnologică -, *</italic><bold><italic>antreprenorii găsind moduri tot mai inovatoare de a satisface nevoia neobosită</italic></bold><italic>* a oamenilor de ceea ce sociologul Émile Durkheim a numit,,efervescență colectivă" - *</italic><bold><italic>euforia pe care o simțim atunci când facem lucruri împreună cu alții</italic></bold><italic>*.
</italic>#+end_quote


<x-color><param>#282c34</param>**</x-color>* The Great Good Place


<x-color><param>#5B6268</param>#+begin_quote

</x-color><italic>Unele *</italic><bold><italic>afaceri locale</italic></bold><italic>* au devenit ceea ce sociologul Ray Oldenburg a numit în cartea sa *</italic><bold><italic>The Great Good Place</italic></bold><italic>*, din 1989. *</italic><bold><italic>un al treilea loc</italic></bold><italic>*": *</italic><bold><italic>nici acasă, nici la serviciu, ci un spațiu de întâlnire animat de conversații, unde se adună clienții obişnuiţi, iar oameni din diferite clase sociale şi economice interacționează, leagă prietenii sau fac schimb de idei şi opinii</italic></bold><italic>*. Locurile acestea, scrie Oldenburg, sunt cele în care „cu toţii ne simțim confortabil şi ca acasă". Ele joacă un rol fundamental în menţinerea coeziunii sociale, fiind locuri în care putem exersa democraţia şi spiritul comunitar în forma lor cea mai incluzivă-ele sunt locuri în care, la fel ca într-un club de lectură, oamenii contribuie cu păreri şi experienţe de viață complet diferite, ce trebuie reconciliate, înțelese şi discutate pentru ca intreaga comunitate să prospere. Și, tocmai pentru că spațiul este important pentru toată lumea. oamenii sunt gata să facă acest efort. Toți participanții au interesul ca acel spațiu să existe, pentru că nu sunt doar in trecere, şi sunt astfel deschişi să comunice, să asculte şi să se gândească în ansamblu, şi nu doar la perspectiva lor singulară.
</italic>#+end_quote


<x-color><param>#282c34</param>**</x-color>* Activitățile într-o comunitate


<x-color><param>#5B6268</param>#+begin_quote

</x-color><italic>Am ajuns astfel, se pare, la *</italic><bold><italic>paradoxul central al celor mai multe spații comune de muncă şi de locuire: ele vor să vă vândă beneficiile locuirii sau muncii alături de alții, însă fără implicațiile sociale şi munca asiduă presupuse de o comunitate</italic></bold><italic>*. Ca şi în cazul prieteniilor reale, consolidarea unei comunități implică anumite neajunsuri.


Gândiți-vă, de exemplu, la comunitățile de care vă simțiți legați cu adevărat. Și în acestea există situații în care trebuie să faceți *</italic><bold><italic>anumite eforturi, nu doar primiți, ci şi dați ceva</italic></bold><italic>*, în schimb.
</italic>#+end_quote


<x-color><param>#282c34</param>*</x-color>* Restabilirea legăturii capitalismului


<x-color><param>#5B6268</param>#+begin_quote

</x-color><italic>Trebuie să acceptăm mai întâi că actuala criză a singurătății nu a apărut pur şi simplu de nicăieri, ci a fost considerabil adâncită de un anumit proiect politic - *</italic><bold><italic>capitalismul neoliberal</italic></bold><italic>*. O *</italic><bold><italic>formă narcisistă şi egoistă de capitalism, care a normalizat indiferenţa şi a făcut o virtute din interesul de sine, iar din grijă și compasiune, trăsături mai puțin importante în societate</italic></bold><italic>*. O formă de capitalism de genul *</italic><bold><italic>Pune te singur pe picioare"</italic></bold><italic>* şi *</italic><bold><italic>„Trage cât mai tare"</italic></bold><italic>*, care a negat rolul vital jucat atât de serviciile publice, cât şi de comunităţile locale în evoluția indivizilor, perpetuând în schimb ideea că doar noi suntem responsabili de destinul nostru. Nu e ca şi cum oamenii nu s-ar mai fi simțit până acum singuri, dar, prin această redefinire a relațiilor ca tranzacții, prin transformarea cetățenilor în simpli consumatori şi prin favorizarea unor şi mai profunde diviziuni în ceea ce priveşte veniturile şi averea, cei patruzeci de ani de neoliberalism, în cel mai bun caz, n-au făcut decât să reducă importanţa unor valori precum solidaritatea, comunitatea, apropierea şi bunătatea.
</italic>#+end_quote


<x-color><param>#282c34</param>*</x-color>* Deutschland spricht

<x-color><param>#5B6268</param>#+begin_quote

</x-color><italic>"Deutschland spricht" vermittelt Menschen, die politisch völlig gegensätzlich denken, in kontroverse Vieraugengespräche. Seit 2017 haben sich bereits mehr 90.000 Menschen für das Gesprächsformat angemeldet.
</italic>#+end_quote


<x-color><param>#51afef</param>-</x-color> 2023-01-18 ◦ <x-color><param>#51afef</param>[[https://www.zeit.de/serie/deutschland-spricht][ZEIT ONLINE | Deutschland spricht]]</x-color>

<x-color><param>#282c34</param>*</x-color>* Umuganda


<x-color><param>#5B6268</param>#+begin_quote

</x-color><italic>Umuganda înseamnă a se strânge laolaltă pentru [...] şi poate îmbrăca diferite forme: unele grupuri dedică trei ore de muncă în serviciul comunității pentru a construi şcoli, de exemplu, iar mulțumită acestor eforturi s-au construit mai mult de 3.000 de clase de când Umuganda a fost oficial reinstaurată de către guvern în 1998, ca parte a procesului de redresare care a urmat devastatorului genocid din 1994." Printre alte activități Umuganda se numără grădinăritul, îngrijirea gardurilor vii şi a straturilor de flori de pe domeniul public, strângerea gunoaielor şi asfaltarea gropilor de pe drumuri. Şi, cu siguranță, aceste trei ore de muncă voluntară au un impact economic semnificativ, valoarea acesteia fiind estimată la 60 de milioane de dolari începând cu anul 2007.58 *</italic><bold><italic>Aceste activităţi au însă şi rolul esențial de a aduce laolaltă comunitatea</italic></bold><italic>*:,,Cei mai mulți oameni sunt încântați, pentru că este singura zi în care îşi pot vedea vecinii", ne spune Faustin Zihiga, care lucrează la o bancă în Kigali."
</italic>#+end_quote

</bold>