:PROPERTIES:
:ID:       f79b86f3-4fb0-4368-b80b-d72fcb562beb
:END:
#+title: The Scientific American Day in the Life of Your Brain
#+filetags: book
#+date: 2018-11-01

* The Scientific American Day in the Life of Your Brain
  :PROPERTIES:
  :FINISHED: 2018-11
  :END:
** Description
#+begin_quote
Have you ever wondered what's happening in your brain as you go through a typical day and night? This fascinating book presents an hour-by-hour round-the-clock journal of your brain's activities. Drawing on the treasure trove of information from Scientific American and Scientific American Mind magazines as well as original material written specifically for this book, Judith Horstman weaves together a compelling description of your brain at work and at play. The Scientific American Day in the Life of Your Brain reveals what's going on in there while you sleep and dream, how your brain makes memories and forms addictions and why we sometimes make bad decisions. The book also offers intriguing information about your emotional brain, and what's happening when you're feeling love, lust, fear and anxiety–and how sex, drugs and rock and roll tickle the same spots.

Based on the latest scientific information, the book explores your brain's remarkable ability to change, how your brain can make new neurons even into old age and why multitasking may be bad for you.

Your brain is uniquely yours - but research is showing many of its day-to-day cycles are universal. This book gives you a look inside your brain and some insights into why you may feel and act as you do.

The Scientific American Day in the Life of Your Brain is written in the entertaining, informative and easy-to-understand style that fans of Scientific American and Scientific American Mind magazine have come to expect.

(Source: https://www.goodreads.com/book/show/6698008-the-scientific-american-day-in-the-life-of-your-brain)
#+end_quote
* Quotes
** The Scientific American Day in the Life of Your Brain - Note 1              :quote:done:
#+begin_quote
You used to have even more cells and connections. By the time you were born, you lost half the neurons you had as a fetus. In your teens, you lose even more as your brain streamlines itself for optimal function.
#+end_quote

** The Scientific American Day in the Life of Your Brain - Note 2              :quote:done:
#+begin_quote
The more you repeat something—an action or a thought—the more brain space is dedicated to it.
#+end_quote

** The Scientific American Day in the Life of Your Brain - Note 3              :quote:done:
#+begin_quote
The primitive brain—the brain stem or hindbrain—that sits at the top of the spine is the oldest part of your brain. It takes care of basic business such as breathing, heartbeat, digestion, reflexive actions, sleeping, and arousal. It includes the spinal cord, which sends messages from the brain to the rest of the body, and the cerebellum, which coordinates balance and rote motions, like riding a bike or catching a ball.
#+end_quote

** The Scientific American Day in the Life of Your Brain - Note 5              :quote:done:
#+begin_quote
In an oft-cited overgeneralization, the right hemisphere is associated with creativity and the left hemisphere with logic.
#+end_quote

** The Scientific American Day in the Life of Your Brain - Note 6              :quote:done:
#+begin_quote
The amygdala handles survival needs and emotions such as fear and anger. It’s responsible for the fight-or-flight reaction.
#+end_quote

** The Scientific American Day in the Life of Your Brain - Note 7              :quote:done:
#+begin_quote
The actual crown is the nickel-thin layer of the cerebral cortex (or neocortex) that covers the cerebrum. This is the most recently evolved part of the brain—the part, some say, that makes us human. It controls thoughts, reasoning, language, planning, and imagination.
#+end_quote

** The Scientific American Day in the Life of Your Brain - Note 8              :quote:done:
#+begin_quote
The cerebrum has four major sections or lobes. Research has found that the frontal lobes take care of speech, movement commands, and reasoning. The occipital lobes in the back take care of vision, while the temporal lobes (above your ears) are responsible for hearing and for understanding speech and appreciating music. The parietal lobes run across the top and sides of the brain and are the primary sensory areas, receiving information about taste, temperature, touch, and movement. They are also involved in reading and math.
#+end_quote

** The Scientific American Day in the Life of Your Brain - Note 9              :quote:done:
#+begin_quote
Glutamate is a major excitatory neurotransmitter, dispersed widely throughout the brain. It’s involved in learning and memory.
#+end_quote

** The Scientific American Day in the Life of Your Brain - Note 10             :quote:done:
#+begin_quote
Endorphins act as hormones and neurotransmitters: they reduce pain sensations and increase pleasure. The name, by the way, is a combination of end(ogenous) (m)orphine.
#+end_quote

** The Scientific American Day in the Life of Your Brain - Note 11             :quote:done:
#+begin_quote
Epinephrine, also called adrenaline, keeps you alert and your blood pressure balanced, and it jumps in when you need energy. It’s produced and released by the adrenal glands in times of stress. Too much can increase anxiety or tension. Norepinephrine (noradrenaline) is a precursor and has similar actions.
#+end_quote

** The Scientific American Day in the Life of Your Brain - Note 12             :quote:done:
#+begin_quote
Dopamine is vital for voluntary movement, attentiveness, motivation, and pleasure. It’s a key player in addiction.
#+end_quote

** The Scientific American Day in the Life of Your Brain - Note 13             :quote:done:
#+begin_quote
Serotonin helps regulate body temperature, memory, emotion, sleep, appetite, and mood. Many antidepressants work by regulating serotonin. • Oxytocin is both a hormone and a neurotransmitter. It’s responsible for labor, breast milk, mother love, and romantic love and trust.
#+end_quote

** The Scientific American Day in the Life of Your Brain - Note 14             :quote:done:
#+begin_quote
Just about everything you do is run by the clock—your own inner biological pacemaker known as the circadian clock, from the Latin circa (“about”) and diem (“a day”). This timekeeper is hardwired into many cells throughout your body and runs on a twenty-four- to twenty-five-hour cycle that follows the turning of the globe.
#+end_quote

** The Scientific American Day in the Life of Your Brain - Note 15             :quote:done:
#+begin_quote
Called the suprachiasmatic nucleus (SCN), this tiny but mighty clock paces all sorts of daily physiological fluctuations and cycles, including body temperature, blood pressure, heart rate, hormone levels, and sleep-waking times. It tells your brain’s pineal gland when to release melatonin to promote sleep and when to shut it off to help you awaken.
#+end_quote

** The Scientific American Day in the Life of Your Brain - Note 16             :quote:done:
#+begin_quote
Scientists have found that active clock genes are not just in the SCN, but are scattered throughout the body, so that some organs and tissues may be running on different schedules, with their mini-clocks responding to other external clues such as exercise, stress, and temperature changes. Some of these clocks are accurate but inflexible, and others are less reliable but under your conscious control. They rule all of your functions and actions, and maybe even your life span, by determining the number of times your cells can divide.
#+end_quote

** The Scientific American Day in the Life of Your Brain - Note 17             :quote:done:
#+begin_quote
A sentry system in your basic brain is set to arouse you when it detects change, such as that annoying alarm clock. Called the reticular activating system (RAS), it’s a part of your brain left over from the prehistoric era when you had to be able to detect danger immediately and wake abruptly.
#+end_quote

** The Scientific American Day in the Life of Your Brain - Note 18             :quote:done:
#+begin_quote
The RAS acts as a gatekeeper for incoming stimulation and sensations, perking up when it detects something new and helping your brain wake up and stay alert and awake all day long.
#+end_quote

** The Scientific American Day in the Life of Your Brain - Note 19             :quote:done:
#+begin_quote
Like a net, the fibers of the RAS “catch” signals from the sensory systems about what’s happening in the body or its local environment.
#+end_quote

** The Scientific American Day in the Life of Your Brain - Note 20             :quote:done:
#+begin_quote
The SCN toggles a biological switch setting off a process that tells the pineal gland to shut off the flow of melatonin, start the waking process, and keep you awake all day.
#+end_quote

** The Scientific American Day in the Life of Your Brain - Note 21             :quote:done:
#+begin_quote
Other neurotransmitters jump in, including serotonin (necessary for mood regulation and involuntary movement) and dopamine (needed for voluntary movement and attentiveness). A hefty shot of cortisol jump-starts everything. Your body temperature, blood pressure, and respiration begin to rise. And these arousal systems don’t stop after they wake you. An active RAS is vital for ongoing awareness. In fact, if your brain’s RAS stops firing signals, you may fall asleep again, and damage to your RAS can cause coma. Many general anesthetics and some tranquilizers work on this part of your brain. The SCN will also stay active most of the day, helping you stay awake until evening when the process reverses, and the rising levels of sleep-promoting chemicals such as melatonin and adenosine make you sleepy all over again.
#+end_quote

** The Scientific American Day in the Life of Your Brain - Note 23             :quote:done:
#+begin_quote
And no wonder. While human sense of smell is relatively weak compared to that of other mammals, we nevertheless have 347 different types of sensory neurons in the olfactory layer for smell inside the nose.
#+end_quote

** The Scientific American Day in the Life of Your Brain - Note 24             :quote:done:
#+begin_quote
Passive touch is vital as well, and therapeutic massage is part of regular health care in many cultures. Many researchers agree that early skin-to-skin contact affects later intelligence, as well as social and emotional growth. In the laboratory, young rats separated from their mother immediately secrete less growth hormone. Human babies left untouched for too long, as many children have been in orphanages, don’t develop normally in many ways. Studies show, for example, that children who spent the first two years of their lives in an orphanage may later produce much lower levels of oxytocin, the hormone of bonding, love, and trust.
#+end_quote

** The Scientific American Day in the Life of Your Brain - Note 25             :quote:done:
#+begin_quote
By 6:00 A.M., your brain has your mind up and about—more or less. But “who” is waking up? And what is “consciousness”? Waking up often feels as if we’ve been away and the mind is returning to the body. If so, where was it?
#+end_quote

** The Scientific American Day in the Life of Your Brain - Note 26             :quote:done:
#+begin_quote
consciousness, scientists say consciousness is actually many states or levels along a continuum.
#+end_quote

** The Scientific American Day in the Life of Your Brain - Note 27             :quote:done:
#+begin_quote
When you awaken, the prefrontal cortex goes to work as soon as you start thinking about what you will do today. It’s the foundation of the thinking brain, making conscious plans, solving problems, and processing thoughts. It cooperates with the orbitofrontal cortex, which is occupied with goals as well as with the consequences of your actions. Some researchers say this is the seat of morals, ethics, and—possibly-conscience.
#+end_quote

** The Scientific American Day in the Life of Your Brain - Note 29             :quote:done:
#+begin_quote
Its main job is to recognize input from your environment that is considered terrifying or could be physically damaging and signal you to fight or flee. Some researchers believe that the amygdala also takes part in non-fear-related emotions, such as curiosity and the will to action.
#+end_quote

** The Scientific American Day in the Life of Your Brain - Note 30             :quote:done:
#+begin_quote
There’s no consensus about how consciousness works. Some researchers believe it’s a collective effort among many neurons, but they don’t quite understand how clusters of neurons from the various regions of the brain get together and collaborate to form consciousness. Others say that specific conscious perceptions correspond to specific groups of neurons or parts of the brain, or that consciousness is a process rather than a place in the brain.
#+end_quote

** The Scientific American Day in the Life of Your Brain - Note 32             :quote:done:
#+begin_quote
Studies are showing that the amount of white matter correlates directly with IQ: the more white matter, the higher the IQ. New studies also show that the extent of white matter varies in people who have different mental experiences: children who have been severely neglected have up to 17 percent less myelin in the corpus callosum, the connector between the brain’s two hemispheres.
#+end_quote

** The Scientific American Day in the Life of Your Brain - Note 33             :quote:done:
#+begin_quote
As the morning’s array of sensory impressions flows into the thalamus, the brain’s major sensory reception and sorting area, the trigger-happy amygdala is poised to react. At a perceived threat, such as a nasty quip in the kitchen, it can flip the switch that prompts the hypothalamus to set off a neurochemical chain reaction. It recruits stress chemicals such as cortisol and noradrenalin from the adrenal gland to put your body on high alert and increase stress, frustration, and, yes, anger.
#+end_quote

** The Scientific American Day in the Life of Your Brain - Note 34             :quote:done:
#+begin_quote
Serotonin is made from the amino acid tryptophan, which can be obtained only through what we eat. So when we haven’t eaten for awhile, as in the early morning, our serotonin levels go down and our tendency toward irritation can go up.
#+end_quote

** The Scientific American Day in the Life of Your Brain - Note 35             :quote:done:
#+begin_quote
Since serotonin depends on tryptophan, it’s made up from what you eat. Among the best sources are foods rich in protein and hot chocolate, oats, bananas, milk, yogurt, and eggs. Hmm. Sounds like breakfast to us.
#+end_quote

** The Scientific American Day in the Life of Your Brain - Note 37             :quote:done:
#+begin_quote
Researchers postulate that we create mental maps of our environments. They’ve discovered cells in the hippocampus that fire when we are in specific locations (they are called place cells) and that these help us organize our experiences and the places where they happened on “cognitive maps.”
#+end_quote

** The Scientific American Day in the Life of Your Brain - Note 38             :quote:done:
#+begin_quote
Finding your way to a new place by estimating distances and orientation is referred to as dead reckoning, and men do better at it than women. Women, on the other brain, may do better at navigating by remembering landmarks and reading directions.
#+end_quote

** The Scientific American Day in the Life of Your Brain - Note 40             :quote:done:
#+begin_quote
To simplify all of this, when you’re in a new place and feel as if you’ve been down this road (or in this place) before, it may be the place cells at that new location are similar to those from a place or time in the past.
#+end_quote

** The Scientific American Day in the Life of Your Brain - Note 41             :quote:done:
#+begin_quote
feature-based attention—essentially the tuning of your visual processing system to specific colors, shapes, or motions as a way of formulating an awareness of a scene—in other words, picking up on patterns.
#+end_quote

** The Scientific American Day in the Life of Your Brain - Note 42             :quote:done:
#+begin_quote
It showed that while you are consciously tuning for a particular shape or color—say, your lost keys—in one part of your visual field, you may be subconsciously alerting the entire visual system to that pattern for a more efficient search.
#+end_quote

** The Scientific American Day in the Life of Your Brain - Note 43             :quote:done:
#+begin_quote
They say there is a specific ID center for faces in a visual processing center of the brain called the fusiform face area (FFA): a pea-sized region located in the fusiform gyrus, a spindle-shaped area where the temporal lobes meet the occipital lobe.
#+end_quote

** The Scientific American Day in the Life of Your Brain - Note 44             :quote:done:
#+begin_quote
The name for this is prosopagnosia, or face blindness.
#+end_quote

** The Scientific American Day in the Life of Your Brain - Note 45             :quote:done:
#+begin_quote
One reason is that females may have an advantage when it comes to episodic memory, a type of long-term memory based on personal experiences. Previous studies have also shown that women have a better memory for verbal information, which they may use to dissect a person’s underlying motives or intentions—a skill that seems to elude many men.
#+end_quote

** The Scientific American Day in the Life of Your Brain - Note 46             :quote:done:
#+begin_quote
The findings support a model proposed by Burke and her colleagues, which predicts that when we do not often use a word, the connections among all its various representations in the brain become weak.
#+end_quote

** The Scientific American Day in the Life of Your Brain - Note 47             :quote:done:
#+begin_quote
Not only is it inefficient. Its stress can hurt your hippocampus (the place where memories are formed) and your prefrontal cortex (where executive decisions are made). That damage can make it difficult to learn new facts and skills, and it can even provoke an attack of pseudo attention deficit disorder (ADD), in which we constantly seek new information but have difficulties in concentrating on its content—no news to most of us who multitask madly with e-mail, phone, and text messaging.
#+end_quote

** The Scientific American Day in the Life of Your Brain - Note 49             :quote:done:
#+begin_quote
“It is how people respond to stress that determines whether they will profit from misfortune or be miserable,”
#+end_quote

** The Scientific American Day in the Life of Your Brain - Note 50             :quote:done:
#+begin_quote
A clutch of studies shows that people faced with many choices lose focus and later find it hard to make subsequent choices, even if they’ve been participating in something seemingly fun, like choosing gifts for a wedding registry. One study looked at several situations involving about four hundred people and choice making. In some cases, they were asked to choose; in another case, they simply had to contemplate the options. University of Minnesota psychologist Kathleen Vohs and colleagues found that those who had been busy making choices performed worse on math tests afterward, compared to those who looked at options without making a choice. Making decisions seemed to deplete mental energy, said Vohs.
#+end_quote

** The Scientific American Day in the Life of Your Brain - Note 51             :quote:done:
#+begin_quote
Food is a basic survival need, but overeating isn’t. It’s an addiction and very like drug addiction, which may explain why so many of us have such trouble with weight.
#+end_quote

** The Scientific American Day in the Life of Your Brain - Note 52             :quote:done:
#+begin_quote
(Orgasm has actually been described as the biggest legal high you can experience without a prescription. See “10:00 P.M.”)
#+end_quote

** The Scientific American Day in the Life of Your Brain - Note 53             :quote:done:
#+begin_quote
The pain message gets sent to the brain via specialized neurons called nociceptors, which sit outside the central nervous system. Their job is to detect potentially harmful happenings to your body, such as extremes of temperature, unusual pressure, or chemicals released in response to an injury or inflammation.
#+end_quote

** The Scientific American Day in the Life of Your Brain - Note 54             :quote:done:
#+begin_quote
it can make structural changes in your nerve cells that make them supersensitive, or cause them to fire off pain signals when nothing is happening, or change the pain transmission pathways in your central nervous system.
#+end_quote

** The Scientific American Day in the Life of Your Brain - Note 55             :quote:done:
#+begin_quote
The shortened days of winter bring on the SAD-ness (seasonal affective disorder) in some of us around this time of evening. SAD, which affects many people in northern climes where light levels are lower in the winter, is connected with an increase in melatonin, a decrease in serotonin, and a mix-up in the SCN, our internal body clock.
#+end_quote

** The Scientific American Day in the Life of Your Brain - Note 56             :quote:done:
#+begin_quote
Brain scans prove that music is irresistible, and possibly addictive. When scientists scanned brains that were moved to emotion by music, they found that music activated some of the same reward systems as food, sex, and addictive drugs.
#+end_quote

** The Scientific American Day in the Life of Your Brain - Note 57             :quote:done:
#+begin_quote
Creativity isn’t only, or even, about intelligence. Experts say it’s based more on the ability to think outside usual rules and guidelines, called divergent thinking. That ability seems to reside more in the right hemisphere of the brain, which tends to be more intuitive, abstract, and imaginative. The left hemisphere is more detail oriented, analytical, logical, and verbal, called convergent thinking.
#+end_quote

** The Scientific American Day in the Life of Your Brain - Note 58             :quote:done:
#+begin_quote
The danger data race from the thalamus (the brain’s receiver of information from the senses), to the amygdala through the cortex (the seat of reasoning that analyzes data) and/or the hippocampus (the memory input center that compares the new information to past experiences), while your hypothalamus tells the adrenal and pituitary to pour cortisol and other stress hormones into the mix.
#+end_quote

** The Scientific American Day in the Life of Your Brain - Note 60             :quote:done:
#+begin_quote
Researchers say that it takes a stew of ingredients to make a violent criminal. Violent behavior is the result of a complex combination of biology and environment, including gender, genetics, brain anatomy, biochemistry, and a traumatic childhood. Testosterone is involved (see “The Testosterone Connection” on the following page). In general, men are more primed for aggression than women and commit most violent crimes. But it takes more than gender to make a person violent, and it’s related more to poor impulse control than pure evil.
#+end_quote

** The Scientific American Day in the Life of Your Brain - Note 62             :quote:done:
#+begin_quote
Viagra—also known as sildenafil—works
#+end_quote
