:PROPERTIES:
:ID:       082aa166-9e25-4a6d-8b4c-e9c347753ede
:END:
#+title: Trotzdem Ja zum Leben sagen
#+filetags: book
#+date: 2023-03-20

Von Viktor E. Frankl:

- [[https://www.goodreads.com/book/show/41432931][... trotzdem Ja zum Leben sagen: Ein Psychologe erlebt das Konzentrationslager]]
  - English: [[https://www.goodreads.com/book/show/4069.Man_s_Search_for_Meaning][Man's Search for Meaning]]

* Weitere Bücher
- The Will to Meaning

  In diesem Buch erklärt Frankl seine Theorie der [[id:716d71ac-2ef8-4bd2-9343-14250eaea268][Logotherapie]] und wie sie dazu
  beitragen kann, dass Menschen ihre Lebenskrise bewältigen und ein erfülltes
  Leben führen können.

- Man's Search for Ultimate Meaning

  Dieses Buch vertieft die Themen von "Man's Search for Meaning" und "The Will
  to Meaning" und geht tiefer auf die Suche nach dem ultimativen Sinn des Lebens
  ein.

- Logotherapy and Existential Analysis

  In diesem Buch wird die Praxis der Logotherapie und Existenzanalyse
  detailliert beschrieben und es werden verschiedene Techniken und Methoden zur
  Suche nach Sinn und Bedeutung im Leben vorgestellt.

- The Unheard Cry for Meaning

  In diesem Buch geht Frankl auf die spirituelle Dimension der Suche nach Sinn
  und Bedeutung ein und wie sie dazu beitragen kann, dass Menschen ein erfülltes
  Leben führen können.

* Interviews
- "[[https://youtu.be/tULbW1kLDPk][Dr. Viktor E. Frankl im Gespräch mit Johannes Kunz]]"
* Notes
** P73
#+begin_quote
Ist es wirklich so, daß der Mensch nichts weiter sei als ein Produkt vielfacher
Bestimmtheiten und Bedingtheiten, seien sie nun biologisch gemeint oder
psychologisch oder soziologisch? Ist der Mensch also wirklich nicht mehr als das
zufällige Resultat seiner leiblichen Konstitution, seiner charakterologischen
Disposition und seiner gesellschaftlichen Situation? *Und, im besonderen: zeigt
sich an den seelischen Reaktionen des Menschen auf die besondere, sozial
bedingte Umwelt des Lagerlebens tatsächlich, daß er den Einflüssen dieser
Daseinsform, denen er gezwungenermaßen unterstellt ist, sich gar nicht entziehen
kann*? Daß er diesen Einflüssen unterliegen muß? Daß er »unter dem Zwang der
Verhält- nisse«, der dort im Lager herrschenden Lebensverhältnisse, »nicht
anders kann«?
#+end_quote

** P47
#+begin_quote
Ich erfasse jetzt den Sinn des Letzten und Äußersten, was menschliches Dichten
und Denken und - Glauben auszusagen hat: die Erlösung durch die Liebe und in der
Liebe! *Ich erfasse, daß der Mensch, wenn ihm nichts mehr bleibt auf dieser Welt,
selig werden kann - und sei es auch nur für Augenblicke, im Innersten hingegeben
an das Bild des geliebten Menschen*.
#+end_quote

** P74
#+begin_quote
Dostojewski hat einmal gesagt: *Ich fürchte nur eines: meiner Qual nicht würdig zu sein.*
#+end_quote
** P74
#+begin_quote
Erlebnis der Schönheit, im Erleben von Kunst oder Natur, sich zu erfüllen;
sondern auch noch das Leben behält seinen Sinn, das - wie etwa im
Konzentrationslager - kaum eine Chance mehr bietet, schöpferisch oder erlebend
Werte zu verwirklichen, vielmehr nur noch *eine letzte Möglichkeit zuläßt, das
Leben sinnvoll zu gestalten, nämlich eben in der Weise, in der sich der Mensch
zu dieser äußerlich erzwungenen Einschränkung seines Daseins einstellt*. Das
schöpferische wie das genießende Leben sind ihm längst verschlossen. Aber nicht
nur schöpferisches und genießendes Leben hat einen Sinn, sondern: *wenn Leben
überhaupt einen Sinn hat, dann muß auch Leiden einen Sinn haben*. Gehört doch das
Leiden zum Leben irgendwie dazu - genau so wie das Schicksal und das Sterben.
*Not und Tod machen das menschliche Dasein erst zu einem Ganzen*.
#+end_quote

** P77
#+begin_quote
Wenn vorhin davon die Rede war, daß der letzte Grund für die Deformierung der
inneren Lebenswirklichkeit des Menschen im Konzentrationslager nicht in den
aufgezählten psycho-physischen Ursachen liegt, sondern daß ihr letztlich eine
freie Entscheidung zugrunde liegt, so soll dies im folgenden näher erläutert
werden. *Die psychologische Beobachtung an den Lagerhäftlingen hat vor allem
ergeben, daß nur derjenige in seiner Charakterentwicklung den Einflüssen der
Lagerwelt verfällt, der sich zuvor geistig und menschlich eben fallen gelassen
hat*; fallen ließ sich aber nur derjenige, der keinen inneren Halt mehr besaß!
Worin hätte nun solch ein innerer Halt bestehen sollen und können? Dies ist
jetzt unsere Frage.
#+end_quote

** P79
#+begin_quote
Die totale Entwertung der Realität, wie sie der provisorischen Existenzweise des
Lagerhäftlings entspricht, verführt einen vollends dazu, sich gehen zu lassen,
sich fallen zu lassen da ja ohnedies >>alles zwecklos<< sei. Solche Menschen
vergessen, daß *oft gerade eine außergewöhnlich schwierige äußere Situation dem
Menschen Gelegenheit gibt, innerlich über sich selbst hinauszuwachsen*. Statt
gerade *die äußeren Schwierigkeiten des Lagerlebens zu einer inneren
Bewährungsprobe zu gestalten*, nehmen sie das gegenwärtige Dasein nicht ernst,
sie entwerten es zu etwas Uneigentlichem, vor dem man sich am besten
verschließt, indem man sich nur mehr mit dem vergangenen Leben abgibt.
#+end_quote

** P83

#+begin_quote
Wir müssen lernen und die verzweifelnden Menschen lehren, daß es eigentlich nie
und *nimmer darauf ankommt, was wir vom Leben noch zu erwarten haben, vielmehr
lediglich darauf: was das Leben von uns erwartet!*
#+end_quote

#+begin_quote
Wir sagten vorhin, jeder Versuch, die Menschen im Konzentrationslager
innerlich wieder aufzurichten, setze voraus, daß es uns gelingt, sie auf ein
Ziel in der Zukunft hin auszurichten. Die Devise nun, unter der alle
psychotherapeutischen oder psychohygienischen Bemühungen den Häftlingen
gegenüber stehen mußten, ist vielleicht am treffendsten ausgedrückt in den
Worten von Nietzsche: >> *Wer ein Warum zu leben hat, erträgt fast jedes Wie*. «

Man mußte also den Lagerinsassen, sofern sich hier und da einmal die Gelegenheit
hierzu bot, das Warum« ihres Lebens, ihr Lebensziel, bewußt machen, um so zu
erreichen, daß sie auch dem furchtbaren des gegenwärtigen Daseins, den Schrecken
des Lagerlebens, innerlich gewachsen waren und standhalten konnten. Umgekehrt:
*wehe dem, der kein Lebensziel mehr vor sich sah, der keinen Lebensinhalt mehr
hatte, in seinem Leben keinen Zweck erblickte, dem der Sinn seines Daseins
entschwand und damit jedweder Sinn eines Durchhaltens*. Solche Leute, die auf
diese Weise völlig haltlos geworden waren, ließen sich alsbald fallen. Die
typische Redewendung, mit der sie allen aufmunternden Argumenten
entgegentraten und jeglichen Zuspruch ablehnten, lautete dann immer: »Ich hab ja
vom Leben nichts mehr zu erwarten.<< Was soll man demgegenüber nun erwidern?
#+end_quote

** P94

#+begin_quote
So tritt man in die Natur hinaus und in die Freiheit. >>In die Freiheit«, sagt
man sich vor und wiederholt man in Gedanken immer wieder; aber man kann es
einfach nicht fassen. *Das Wort Freiheit war in den jahrelangen Sehnsuchtsträu-
men schon zu sehr abgegriffen und der Begriff zu sehr verblaßt; mit der
Wirklichkeit konfrontiert, zerfließt er*. Die Wirklichkeit dringt noch nicht
recht ins Bewußtsein ein: man kann es eben einfach noch nicht fassen.
#+end_quote

#+begin_quote
Da kommt man zu einer Wiese. Da sieht man blühende Blumen auf ihr. Man nimmt
dies alles zur Kenntnis, aber - nicht zum Gefühl«. Der erste kleine Funke von
Freude sprüht auf, sobald man einen Hahn bemerkt, der prächtige vielfarbige
Schwanzfedern hat. Aber es bleibt bei einem Freudefunken, und noch hat man nicht
teil an der Welt. Dann setzt man sich unter einen Kastanienbaum, auf eine kleine
Bank; weiß Gott, welchen Ausdruck da das Gesicht annimmt -, jedenfalls: noch
macht die Welt keinen Eindruck.
#+end_quote

Nach der Befreiung:

#+begin_quote
Abends, wenn die Kameraden in ihrer alten Erdhütte wieder zusammenströmen,
kommt einer zum andern und fragt ihn heimlich: »*Du, sag einmal, hast du dich
heute gefreut?<< Und einer sagt dem andern und fühlt sich noch beschämt, weil er
noch nicht weiß, daß es jedem so ergangen »Offen gesagt: nein!«... Man hat es
buchstäblich verlernt, sich zu freuen, und man wird es erst wieder lernen
müssen*.
#+end_quote

** P97
#+begin_quote
Für solche primitiven Menschen hat sich eigentlich nichts als das Vorzeichen der
alten Kategorie geändert, es ist aus einem negativen ein positives geworden: aus
den Objekten von Macht, Gewalt, Willkür und Unrecht sind die entsprechenden
Subjekte geworden; aber sie haften eben noch an dem, was sie erlebt haben.

Dies äußert sich oft in belanglos erscheinenden Kleinigkeiten. Wir gehen z.B.
querfeldein, ein Kamerad und ich, dem Lager zu, aus dem wir vor kurzem befreit
wurden; da steht plötzlich vor uns ein Feld mit junger Saat. Unwillkürlich
weiche ich aus. Er aber packt mich beim Arm und schiebt mich mit sich
mittendurch. Ich stammle etwas davon, daß man doch die junge Saat nicht
niedertreten soll. Da wird er böse: in seinen Augen zuckt ein zorniger Blick
auf, während er mich anschreit: >>Was du nicht sagst! Und uns hat man zu wenig
genommen? Mir hat man Frau und Kind vergast - abgesehen von allem andern und du
willst mir verbieten, daß ich ein paar Haferhalme zusammentrete...«

Nur langsam kann man diese Menschen zurückfinden lassen zu der sonst doch so
*trivialen Wahrheit, daß niemand das Recht hat, Unrecht zu tun, auch der nicht,
der Unrecht erlitten hat*. Und doch müssen wir daran arbeiten, diese Menschen zu
dieser Wahrheit zurückfinden zu lassen
#+end_quote
