:PROPERTIES:
:ID:       acff7704-6f4f-4d58-b8b9-dfa06e0e7d33
:END:
#+title: Way of the Peaceful Warrior
#+filetags: book
#+date: 2018-07-01

* Way of the Peaceful Warrior
  :PROPERTIES:
  :FINISHED: 2018-07
  :END:
** Description

* Quotes
** Way of the Peaceful Warrior - Note 1                                        :quote:done:
#+begin_quote
Life is not a private affair. A story and its lessons are only made useful if shared.
#+end_quote

** Way of the Peaceful Warrior - Note 2                                        :quote:done:
#+begin_quote
You hold many facts and opinions, yet know little of yourself. Before you can learn, you’ll have to first empty your tank.”
#+end_quote

** Way of the Peaceful Warrior - Note 3                                        :quote:done:
#+begin_quote
“You understand many things but have realized practically nothing.”
#+end_quote

** Way of the Peaceful Warrior - Note 4                                        :quote:done:
#+begin_quote
“Understanding is the one-dimensional comprehension of the intellect. It leads to knowledge. Realization is three-dimensional — a simultaneous comprehension of head, heart, and instinct. It comes only from direct experience.”
#+end_quote

** Way of the Peaceful Warrior - Note 5                                        :quote:done:
#+begin_quote
No amount of knowledge will nourish or sustain your spirit; it can never bring you ultimate happiness or peace. Life requires more than knowledge; it requires intense feeling and constant energy. Life demands right action if knowledge is to come alive.”
#+end_quote

** Way of the Peaceful Warrior - Note 6                                        :quote:done:
#+begin_quote
“It is better for you to take responsibility for your life as it is, instead of blaming others, or circumstances, for your predicament. As your eyes open, you’ll see that your state of health, happiness, and every circumstance of your life has been, in large part, arranged by you — consciously or unconsciously.”
#+end_quote

** Way of the Peaceful Warrior - Note 7                                        :quote:done:
#+begin_quote
“‘Only the supremely wise and the ignorant do not alter.’”
#+end_quote

** Way of the Peaceful Warrior - Note 8                                        :quote:done:
#+begin_quote
Everyone everywhere lived a confused, bitter search. Reality never matched their dreams; happiness was just around the corner — a corner they never turned.
#+end_quote

** Way of the Peaceful Warrior - Note 9                                        :quote:done:
#+begin_quote
“If you don’t get what you want, you suffer; if you get what you don’t want, you suffer; even when you get exactly what you want, you still suffer because you can’t hold on to it forever.
#+end_quote

** Way of the Peaceful Warrior - Note 10                                       :quote:done:
#+begin_quote
Just so, stressful thoughts reflect a conflict with reality. Stress happens when the mind resists what is.”
#+end_quote

** Way of the Peaceful Warrior - Note 11                                       :quote:done:
#+begin_quote
Finally, I realized the process of real meditation — to expand awareness, to direct attention, to ultimately surrender to the light of consciousness.
#+end_quote

** Way of the Peaceful Warrior - Note 12                                       :quote:done:
#+begin_quote
“Meditation consists of two simultaneous processes: One is insight — paying attention to what is arising. The other is surrender — letting go of attachment to arising thoughts. This is how you cut free of the mind.”
#+end_quote

** Way of the Peaceful Warrior - Note 13                                       :quote:done:
#+begin_quote
“Fear and sorrow inhibit action; anger generates it. When you learn to make proper use of your anger, you can change fear and sorrow to anger, then turn anger to action. That’s the body’s secret of internal alchemy.”
#+end_quote

** Way of the Peaceful Warrior - Note 14                                       :quote:done:
#+begin_quote
“To rid yourself of old patterns, focus all your energy not on struggling with the old, but on building the new.” (also see Atomic Habits)
#+end_quote

** Way of the Peaceful Warrior - Note 15                                       :quote:done:
#+begin_quote
“Emotions are natural, like passing weather. Sometimes it’s fear, sometimes sorrow or anger. Emotions are not the problem. The key is to transform the energy of emotion into constructive action.”
#+end_quote

** Way of the Peaceful Warrior - Note 16                                       :quote:done:
#+begin_quote
“One of the Japanese Olympic gymnasts once told me that it’s not your bad habits that count, but your good ones.” “That means your good habits must become so strong that they dissolve those which are not useful.”
#+end_quote

** Way of the Peaceful Warrior - Note 17                                       :quote:done:
#+begin_quote
“The pleasure from eating, Dan, is more than the taste of the food and the feeling of a full belly. Learn to enjoy the entire process — the hunger beforehand, the careful preparation, setting an attractive table, chewing, breathing, smelling, tasting, swallowing, and the feeling of lightness and energy after the meal.
#+end_quote

** Way of the Peaceful Warrior - Note 18                                       :quote:done:
#+begin_quote
“Proper posture is a way of blending with gravity, Dan. Proper attitude is a way of blending with life.”
#+end_quote

** Way of the Peaceful Warrior - Note 19                                       :quote:done:
#+begin_quote
“Don’t get distracted by your experiences. Experiences come and go; if you want experiences, go to the movies; it’s easier than all these yogas — and you get popcorn. Meditate all day, if you like; hear sounds and see lights, or see sounds and hear lights. But don’t get seduced by experience. Let it all go!”
#+end_quote

** Way of the Peaceful Warrior - Note 20                                       :quote:done:
#+begin_quote
“It’s better to make a mistake with the full force of your being than to timidly avoid mistakes with a trembling spirit. Responsibility means recognizing both pleasure and price, action and consequence, then making a choice.”
#+end_quote

** Way of the Peaceful Warrior - Note 21                                       :quote:done:
#+begin_quote
“There are no ordinary moments!”
#+end_quote

** Way of the Peaceful Warrior - Note 22                                       :quote:done:
#+begin_quote
I saw that I had never learned how to enjoy life, only how to achieve. All my life I had been busy seeking happiness, not finding it.
#+end_quote

** Way of the Peaceful Warrior - Note 23                                       :quote:done:
#+begin_quote
The birth of the mind is the death of the senses
#+end_quote

** Way of the Peaceful Warrior - Note 24                                       :quote:done:
#+begin_quote
You’ve become bored with things because they only exist as names to you. The dry concepts of the mind obscure your direct perception.”
#+end_quote

** Way of the Peaceful Warrior - Note 25                                       :quote:done:
#+begin_quote
Refine your senses a little more each day; stretch them, as you would in the gym. Finally, your awareness will pierce deeply into your body and into the world. Then you’ll think less and feel more. That way you’ll enjoy even the simplest things in life — no longer addicted to achievement or expensive entertainments.
#+end_quote

** Way of the Peaceful Warrior - Note 26                                       :quote:done:
#+begin_quote
“You are rich if you have enough money to satisfy all your desires. So there are two ways to be rich: You earn, inherit, borrow, beg, or steal enough money to meet all your desires; or, you cultivate a simple lifestyle of few desires; that way you always have enough money.
#+end_quote

** Way of the Peaceful Warrior - Note 27                                       :quote:done:
#+begin_quote
The secret of happiness, you see, is not found in seeking more, but in developing the capacity to enjoy less.”
#+end_quote

** Way of the Peaceful Warrior - Note 28                                       :quote:done:
#+begin_quote
“It doesn’t matter what you do, only how well you do it.
#+end_quote

** Way of the Peaceful Warrior - Note 29                                       :quote:done:
#+begin_quote
For every strength there is a weakness — and for every weakness, a strength.
#+end_quote

** Way of the Peaceful Warrior - Note 30                                       :quote:done:
#+begin_quote
“Better to live until you die,”
#+end_quote

** Way of the Peaceful Warrior - Note 31                                       :quote:done:
#+begin_quote
“So remember, Dan, embody what you teach, and teach only what you have embodied.”
#+end_quote

** Way of the Peaceful Warrior - Note 32                                       :quote:done:
#+begin_quote
“Enlightenment is not an attainment, Dan; it is a Realization. And when you wake up, everything changes and nothing changes. If a blind man realizes that he can see, has the world changed?”
#+end_quote

** Way of the Peaceful Warrior - Note 33                                       :quote:done:
#+begin_quote
There is no need to search; achievement leads to nowhere. It makes no difference at all, so just be happy now!
#+end_quote

** Way of the Peaceful Warrior - Note 34                                       :quote:done:
#+begin_quote
Open your eyes and see that you are far more than you imagine. You are the world, you are the universe; you are yourself and everyone else, too!
#+end_quote
