:PROPERTIES:
:ID:       10db442f-bb4a-4811-bf58-a1f0d7af0eb6
:END:
#+title: What Every Body Is Saying
#+filetags: book
#+date: 2017-10-01

* What Every Body Is Saying
:PROPERTIES:
:FINISHED: 2017-10
:END:
** Description
#+begin_quote
Read this book and send your nonverbal intelligence soaring. Joe Navarro, a former FBI counterintelligence officer and a recognized expert on nonverbal behavior, explains how to "speed-read" people: decode sentiments and behaviors, avoid hidden pitfalls, and look for deceptive behaviors. You'll also learn how your body language can influence what your boss, family, friends, and strangers think of you. You will discover:


The ancient survival instincts that drive body language
Why the face is the least likely place to gauge a person's true feelings
What thumbs, feet, and eyelids reveal about moods and motives
The most powerful behaviors that reveal our confidence and true sentiments
Simple nonverbals that instantly establish trust
Simple nonverbals that instantly communicate authority
Filled with examples from Navarro's professional experience, this definitive book offers a powerful new way to navigate your world.

(Source: https://www.goodreads.com/book/show/1173576.What_Every_Body_is_Saying)
#+end_quote
* Quotes
** What Every Body Is Saying - Note 1                                          :quote:done:
#+begin_quote
Nonverbal behaviors comprise approximately 60 to 65 percent of all interpersonal communication and, during lovemaking, can constitute 100 percent of communication between partners (Burgoon, 1994, 229–285).
#+end_quote

** What Every Body Is Saying - Note 2                                          :quote:done:
#+begin_quote
lip compression,
#+end_quote

** What Every Body Is Saying - Note 3                                          :quote:done:
#+begin_quote
“the best predictor of future behavior is past behavior.”
#+end_quote

** What Every Body Is Saying - Note 4                                          :quote:done:
#+begin_quote
Pacifying is not unique to our species. For example, cats and dogs lick themselves and each other to pacify.
#+end_quote

** What Every Body Is Saying - Note 5                                          :quote:done:
#+begin_quote
You now are in possession of information that is unknown to most people. You are aware that we have a very robust survival mechanism (freeze, flight, or fight) and possess a pacifying system to deal with stress. We are fortunate to have these mechanisms, not only for our own survival and success, but also to use in assessing the sentiments and thoughts of others.
#+end_quote

** What Every Body Is Saying - Note 6                                          :quote:done:
#+begin_quote
(in an L formation with one foot toward you and one away from you), you can be assured he wants to take leave or wishes he were somewhere else. This type of foot behavior is another example of an intention cue (Givens, 2005, 60–61). The person’s torso may remain facing you out of social diligence, but the feet may more honestly reflect the limbic brain’s need or desire to escape (see figure 18).
#+end_quote

** What Every Body Is Saying - Note 7                                          :quote:done:
#+begin_quote
Take note if a person who is sitting down places both hands on his knees in a knee clasp (see figure 19). This is a very clear sign that in his mind, he is ready to conclude the meeting and take leave. Usually
#+end_quote

** What Every Body Is Saying - Note 8                                          :quote:done:
#+begin_quote
Gravity-Defying Behaviors of the Feet
#+end_quote

** What Every Body Is Saying - Note 9                                          :quote:done:
#+begin_quote
starter’s position
#+end_quote

** What Every Body Is Saying - Note 10                                         :quote:done:
#+begin_quote
movement. It could mean the individual intends to engage you further, is really interested, or wants to leave. As
#+end_quote

** What Every Body Is Saying - Note 11                                         :quote:done:
#+begin_quote
The most unmistakable and easily spotted foot and leg behaviors are territorial displays.
#+end_quote

** What Every Body Is Saying - Note 12                                         :quote:done:
#+begin_quote
Hall found that the more advantaged we are socioeconomically or hierarchically, the more territory we demand. He also found that people who tend to take up more space (territory) through their daily activities also tend to be more self-assured, more confident, and of course more likely to be of higher status.
#+end_quote

** What Every Body Is Saying - Note 13                                         :quote:done:
#+begin_quote
Bodytalk: The Meaning of Human Gestures, by Desmond Morris, and Gestures: The Do’s and Taboos of Body Language Around the World, by Roger E. Axtell. These
#+end_quote

** What Every Body Is Saying - Note 14                                         :quote:done:
#+begin_quote
Steepling
#+end_quote

** What Every Body Is Saying - Note 15                                         :quote:done:
#+begin_quote
person can go from steepling (high confidence) to fingers interlaced (low confidence) and back to steepling (high confidence)—reflecting the ebb and flow of assurance and doubt.
#+end_quote

** What Every Body Is Saying - Note 16                                         :quote:done:
#+begin_quote
Apparently the marketing team at this company also recognizes that thumbs up is a high-confidence or high-status display.
#+end_quote

** What Every Body Is Saying - Note 18                                         :quote:done:
#+begin_quote
Feelings of low confidence can be evidenced when a person (usually a male) puts his thumbs in his pocket and lets the fingers hang out on the side (see figure 54).
#+end_quote

** What Every Body Is Saying - Note 19                                         :quote:done:
#+begin_quote
A person who is in doubt (a lesser degree of lowered confidence) or under low stress will only slightly rub the palms of his hands together (see figure 57).
#+end_quote

** What Every Body Is Saying - Note 20                                         :quote:done:
#+begin_quote
microgesture is a very brief nonverbal behavior that occurs when a person is attempting to suppress a normal response to a negative stimulus (Ekman, 2003, 15).
#+end_quote

** What Every Body Is Saying - Note 21                                         :quote:done:
#+begin_quote
Paul Ekman describes his research using high-speed cameras to reveal microgestures that subconsciously communicate an individual’s disfavor or true emotions (Ekman, 1991, 129–131).
#+end_quote

** What Every Body Is Saying - Note 22                                         :quote:done:
#+begin_quote
66 A delay in opening of the eyelids upon hearing information or a lengthy closure is indicative of negative emotions or displeasure.
#+end_quote

** What Every Body Is Saying - Note 23                                         :quote:done:
#+begin_quote
Nasal Wing Dilation (Nose Flare)
#+end_quote

** What Every Body Is Saying - Note 24                                         :quote:done:
#+begin_quote
If one leans forward, the other follows, the phenomenon known as isopraxism.
#+end_quote

** What Every Body Is Saying - Note 25                                         :quote:done:
#+begin_quote
Territorial Displays and Deception
#+end_quote
