:properties:
:id:       cbf3b1dd-96f8-4f72-9daf-883029156227
:end:
#+title: When The Body Says No
#+filetags: :health:psychology:book:
#+date: 2024-06-03

👉 https://www.goodreads.com/book/show/450534.When_the_Body_Says_No

* Chapters
** 1 The Bermuda Triangle
** 3 Stress and emotional competence
*** Note

#+begin_quote
When people describe themselves as being stressed, they usually mean the nervous
agitation they experience under excessive demands-most com- monly in the areas
of work, family, relationships, finances or health. But sensations of nervous
tension do not define stress-nor, strictly speaking, are they always perceived
when people are stressed. Stress, as we will define it, is not a matter of
subjective feeling. It is a measurable set of objective physiological events in
the body, involving the brain, the hormonal appa- ratus, the immune system and
many other organs. Both animals and peo- ple can experience stress with no
awareness of its presence.
#+end_quote

*** Definition of stress

#+begin_quote
What, then, is stress? Selye-who coined the word in its presen usage and who
described with mock pride how der stress, le stress and l stress entered the
German, French and Italian languages respectively- conceived of stress as a
biological process, a wide-ranging set of event in the body, irrespective of
cause or of subjective awareness. Stress con- sists of the internal
alterations-visible or not that occur when the organism perceives a threat to
its existence or well-being. While nerwartension may be a component of stress,
one can be stressed without feel- ing tension. On the other hand, it is possible
to feel tension without activating the physiological mechanisms of stress.
#+end_quote

#+begin_quote
In searching for a word to capture the meaning of the physical changes he
observed in his experiments, Selye "stumbled upon the term stress, which had
long been used in common English, and particularly in engineering, to denote the
effects of a force acting against a resistance." He gives the example of changes
induced in a stretched rubber band or in a steel spring under pressure. These
changes may be noted with the naked eye or may be evident only on microscopic
examination.
#+end_quote

#+begin_quote
Selye's analogies illustrate an important point: excessive stress occurs when
the demands made on an organism exceed that organism's rea- sonable capacities
to fulfill them. The rubber band snaps, the spring becomes deformed. The stress
response can be set off by physical dam- age, either by infection or injury. It
can also be triggered by emotional trauma or just by the threat of such trauma,
even if purely imaginary. Physiological stress responses can be evoked when the
threat is outside conscious awareness or even when the individual may believe
himself to be stressed in a "good" way.
#+end_quote

** 4 Buried Alive
** 5 Never good enough
