
* Zusammenfassung
** Trump und Project 2025
- Donald Trump und Super Tuesday
  - Trump liegt laut Prognosen in mindestens 13 der 15 Bundesstaaten vorn.
  - Seine Konkurrentin Nikki Haley gewann nur in einem Staat, was als Symbolerfolg gilt.
  - Trump wird voraussichtlich der republikanische Kandidat sein.
    
- Trump und der Supreme Court
  - Der Supreme Court of the United States hat einen Rechtsstreit zugunsten Trumps entschieden.
  - Ein Ausschluss von den Wahlzetteln nur durch die einzelnen Bundesstaaten ist nicht zulässig, nur der Kongress kann dies tun.
  - Trump hat durch diese Entscheidung Rückenwind bekommen.

- Wahlchancen im November
  - Trump hat gute Chancen im November bei den Präsidentschaftswahlen gegen Joe Biden zu gewinnen.
  - Die Swing States könnten für Trump entscheiden sein, da Biden in mehreren Bereich Probleme hat:
    + Ist zu alt und erscheint vielen nicht „links“ genug.
    + Bidens Kurs im Gazakrieg kostet ihn Zustimmung.
    + Möglicherweise geht damit ein Wähler*innenrückgang bei den Demokraten einher.

- Kritik und Herausforderungen an Trumps Präsidentschaft
  - Er hat den Iran Nuklear Deal gekündigt und mit NATO-Austritt gedroht.
  - Seine Amtszeit war im Inneren von Populismus und menschenrechtlich bedenklichen Taten geprägt (z.B. Muslim Ban).

- Projekt 2025
  - Benannt als Planung für eine mögliche zweite Trump-Präsidentschaft.
  - Der Plan sieht vor, die liberale repräsentative US-amerikanische Demokratie umzubauen.
  - Ähnlichkeiten mit Viktor Orbáns autoritärem System in Ungarn werden gezogen.
  - 50 konservative Organisationen planen unter Führung der Heritage Foundation für eine innenpolitische Revolution.
  - Ziel ist es, besser vorbereitet zu sein als bei der ersten Präsidentschaft.

- Mandate for Leadership (Playbook für Projekt 2025)
  - Ein 900 Seiten starkes Drehbuch beschreibt detailliert die Pläne für die mögliche Präsidentschaft.
  - Rückkehr zum Isolationismus und Ende der Beteiligung an internationalen Organisationen wie WHO, Weltbank und IWF.
  - Leugnung des Klimawandels, Ende des "Kriegs gegen fossile Brennstoffe".
  - Hat auch die NATO im Visier und zielt auf Umbau der US-Bundesbehörden.
  - Eliminierung oder Schrumpfung von Behörden und Organisationen wie FBI und Department of Homeland Security.
  - Neue Beamte sollen eingestellt werden, die auf Linie mit Trumps Politik sind (unitary executive theory).
  - Politik ist Personal: Planung für Ersatz von bis zu 50.000 Beamten.

- Finanzielle Probleme von Trump
  - Er steht vor einer Vielzahl von Verfahren und finanziellen Forderungen, die seine politische Karriere beeinflussen könnten.
  - Mögliche Auswirkungen auf seinen Ruf als wohlhabender Geschäftsmann sind nicht genau zu prognostizieren.

- Vorbereitung auf mögliche Trump-Präsidentschaft
    - Es gibt Bedenken, ob Europa und insbesondere Deutschland auf Trumps mögliche Wiederwahl vorbereitet sind.
    - Ein Europa-Plan für den Fall einer zweiten Trump-Präsidentschaft wird als notwendig erachtet.
    - Politische Abstimmungen, wie das Weimarer Dreieck, könnten für die europäische Zusammenarbeit an Bedeutung gewinnen.

  Dies sind die Hauptpunkte, die im Podcast zur Lage der Nation bezüglich Donald Trump und dem Projekt 2025 erörtert wurden.
** Steuergerechtigkeit und Reformvorschläge laut Christoph Trautvetter
- Verständnis von gerechtem Steuersystem
  - Gerechtigkeitslücken im derzeitigen Steuersystem sollen erstmal geschlossen werden.
  - Im Durchschnitt geben Durchschnittsverdiener die Hälfte ihres Verdiensts an Sozialabgaben.
  - Superreiche und große Konzerne zahlen teilweise deutlich weniger.
    
- Prinzip der Leistungsfähigkeit
  - Das Grundgesetz fordert eine Besteuerung nach Leistungsfähigkeit.
  - Eine progressive Einkommenssteuer wird unterminiert durch Ausnahmen und Schlupflöcher.
  - Das System war früher gerechter: Milliardäre zahlten 60%, heute nur rund 25%.
    
- Wichtige Baustellen im Steuersystem
  - Unternehmenssteuern und Erbschaftssteuern müssen näher betrachtet werden, da hier große Ungleichheiten bestehen.
  - Erbschaftssteuer wird weit unter dem gesetzlichen Satz bei großen Vermögen entrichtet.
  - Steuerverwaltung, Verbrauchssteuern und Umgang mit Umweltthemen benötigen ebenfalls Reformen.
    
- Reformvorschläge für das Steuersystem
  - Es gibt radikale Reformvorschläge, aber Trautvetter empfiehlt kleine Schritte statt großer Sprünge.
  - Sieben kleine Nachbesserungen führen seiner Ansicht nach zu größerer Akzeptanz.
    
- Priorisierung von Reformen
  - Erbschaftssteuer steht als Nächstes auf dem Plan, aufgrund ihrer Dringlichkeit und möglichen verfassungsrechtlichen Bedenken.
  - Vermögenssteuer und Besteuerung großer Konzerne, insbesondere digitaler, wären ebenfalls wichtig, aber finden politischen Widerstand.
  - Gibt bereits positive Bewegung im internationalen Kontext für fairere Besteuerung großer Konzerne.
    
- Effekte von Reformanstrengungen im politischen Prozess
  - Es geht bei Reformen nicht um die Durchschnittsbürger, sondern um die Besteuerung extrem reicher Individuen und Konzerne.
  - Gesellschaftliche Mehrheit für Reformen zu finden, ist trotzdem herausfordernd.
  - Es sollte eine demokratische Debatte über Steuergerechtigkeit geführt werden.

- Fortschritte der Ampel-Koalition
  - Technische Verbesserungen im Steuersystem sind teilweise gelungen, allerdings ohne große Änderung der Gerechtigkeit.
  - Geldwäschebekämpfung und Finanzkriminalität sind aktuelle Fortschrittsfelder.
  - Ein Immobilienregister als "Geniestreich" ermöglicht mehr Transparenz.

* Podcast
 Ulf Buermeyer
Herzlich willkommen zur Lage der Nation, Ausgabe Nummer 372 vom 6. März 2024. Und an den Mikrofonen hier im Berliner Lagestudio begrüßen euch, wie schon einmal im Dezember des vergangenen Jahres, Ulf Buermeyer und:

 Jana Münkel
Und zum zweiten Mal Jana Münkel. Ich freue mich sehr, wieder dabei sein zu dürfen und spring heute sehr gerne mit Ulf ins Pad.

 Ulf Buermeyer
Ja, sehr schön. Ich bin Jurist aus Berlin und freue mich sehr, Jana wieder bei uns begrüßen zu dürfen. Zu unserem ersten Thema. In den Vereinigten Staaten war am Dienstag, dem 5. März, der sogenannte Super Tuesday. Jana, was hat es denn damit auf sich?

 Jana Münkel
Genau, da wurde in 15 Bundesstaaten abgestimmt, unter anderem in Kalifornien, Texas, Colorado, Maine, North Carolina. Und das ist eben so ein Superwahltag. Der ist immer dienstags und gilt als wesentlicher Meilenstein im Wahljahr auf dem Weg hin zur Entscheidung, wer wird Präsidentschaftskandidat der Parteien?

 Ulf Buermeyer
Es ist ja so eine Besonderheit des amerikanischen Wahlsystems, dass für die Präsidentschaftswahl eben so Vorwahlen stattfinden. Das heißt, die Parteien wählen die Kandidierenden zwar auf Versammlungen, aber die Delegierten für diese Versammlungen wiederum, die werden nicht einfach irgendwie von der Partei bestimmt, sondern eben im Zuge von Vorwahlen, den sogenannten Primarys. Genau, und Jana hat es gesagt, der Superwahltag ist ein, gilt als Meilenstein, einfach weil da relativ viele Delegierte für diese Nominierungsveranstaltungen gewählt werden. Ja, die Wahllokale haben in der deutschen Nacht zu Mittwoch geschlossen. Was sind denn so die ersten Ergebnisse?

 Jana Münkel
Also Trump liegt laut Prognosen in mindestens 13 der 15 Bundesstaaten vorn. Da muss ich vielleicht dazu sagen, das ist jetzt der 6. März, Stand 10:30. Also wenn ihr das hört, wird es die anderen Ergebnisse auch noch geben. Aber das war erwartet worden, dass Trump da sehr klare Siege einfährt. Seine Konkurrentin Nikki Haley, die hat nur in einem Bundesstaat bis jetzt gewonnen. Das gilt so ein bisschen als Symbolerfolg. Also sie hat da nochmal Hallo gesagt, aber es wird jetzt nicht erwartet, dass das noch mal was ändert daran, dass Trump das Rennen macht bei den Republikanern.

 Ulf Buermeyer
Ja, sieht gut aus für Donald Trump. Er wird wohl der republikanische Kandidat sein. Für Joe Biden gilt auf demokratischer Seite dasselbe. Ihm ist die Kandidatur kaum noch zu nehmen. Und Donald Trump hat ja in dieser Woche auch vom Supreme Court Rückenwind bekommen, also vom Obersten Gerichtshof der Vereinigten Staaten. Dort hing nämlich ein Rechtsstreit. Und zwar hatte der Supreme Court des Bundesstaats Colorado Donald Trump von den Wahlzetteln für die Vorwahl gestrichen, mit der Begründung, er habe an einer Verschwörung mitgewirkt, insbesondere nämlich an dem Sturm auf das Kapitol am 6. Januar 2021. Diese Sichtweise des Supreme Courts von Colorado hat der Scotus, der Supreme Court of the United States, nun zurückgewiesen.

 Jana Münkel
Genau, und zwar einstimmig. Das ist wichtig, noch dazu zu sagen. Der hat halt gesagt, der Scotus hat gesagt, so eine Entscheidung steht nur dem Kongress zu. Also die einzelnen Bundesstaaten können nicht sagen, so, wir streichen jetzt einfach mal einen Kandidaten vom Zettel. Und in der Begründung war auch enthalten, dass so eine Entscheidung, läge sie denn bei den Bundesstaaten, einfach zu einer Verwirrung führen kann, also zu einem Chaos. Und das deswegen eben diese Entscheidung, ich wiederhole es noch mal, nur dem Kongress zustehe. Das heißt, Trump kann antreten und er hat total Rückenwind. Er hat total gute Karten, Ulf.

 Ulf Buermeyer
Ja, und zwar auch in der nationalen Wahl. Nicht nur, dass er die Nominierung einsammelt, sondern dass er eben auch im November bei der eigentlichen Präsidentschaftswahl den Sieg über Joe Biden davonträgt. Wir haben es gesagt, die Nominierung als Kandidat der Republikaner hat er schon fast im Sack. Aber auch bei den Wahlen im November sieht es relativ gut aus. Die werden letztlich in den sogenannten Swing States entschieden. Es läuft ja bei den Präsidentschaftswahlen in den Vereinigten Staaten in fast allen Staaten so, wer die Mehrheit der Stimmen in diesem Bundesstaat erringt, der bekommt alle Wahlmänner- und Wahlfrauenstimmen dieses Staates. Die meisten Staaten sind politisch ganz klar einzuordnen. Die sind also entweder demokratisch oder republikanisch. Da ist ziemlich klar, wer diesen Staat gewinnt, wer diese Electors dann letzten Endes nach Washington schicken darf. Aber es gibt eben so ein paar Staaten, etwa sechs an der Zahl, wo die Wahl nicht klar ist. Tja, und da muss man sagen, sieht es momentan für Donald Trump ziemlich gut aus.

 Jana Münkel
Und das wirft natürlich die Frage auf, warum sieht es denn auf der anderen Seite so schlecht aus für Biden, wenn der, wir haben es gesagt, ja eigentlich auch schon fast steht als Präsidentschaftskandidat der Demokraten und Biden hat verschiedene Probleme. Wir haben jetzt erst mal drei identifiziert. Erstes Problem, er ist zu alt. Er hat immer wieder Auftritte, auf denen er schleppend redet, bei denen er sich nicht an Dinge erinnern kann, auch nicht an die Namen von verschiedenen Staats- und Regierungschefs zum Beispiel. Und selbst im eigenen Lager ist die Auffassung verbreitet, dass er möglicherweise einfach nicht mehr fähig ist, Präsident zu sein. Es gibt eine neue Umfrage, unter anderem von der New York Times. Da sagen 61 % der Wähler:innen die Joe Biden 2020 unterstützt haben, 81 ist zu alt, um an effective President zu sein, also um ein wirkmächtiger Präsident sein zu können.

 Ulf Buermeyer
Wie gesagt, das wirkt, dieses Problem wirkt nicht nur auf die Wechselwählerinnen und Wechselwähler, sondern das wirkt sogar auf die eigenen Leute, die also politisch inhaltlich mit Joe Biden ziemlich auf einer Linie liegen. Das ist also ein gravierendes Problem, an dem man natürlich auch nichts ändern kann. Sein Lebensalter ist eben sein Lebensalter. Zweites Problem von Joe Biden, wieso er momentan so schlecht dasteht. Seine Bilanz erscheint vielen quasi nicht in Anführungsstrichen links genug. 2020 und bei den letzten Präsidentschaftswahlen hat er noch sehr davon profitiert, dass ihn die relativ linken, relativ progressiven Fans von Bernie Sanders letztlich doch unterstützt haben. Und er hat auch versucht zu liefern, quasi aus dieser Perspektive. Also er hat die Staatsausgaben relativ massiv erhöht, zum Beispiel mit dem sogenannten Inflation reduction act. Das ist also ein großes Subventionsprogramm für alle möglichen Bereiche der amerikanischen Wirtschaft. Das wirkt auch sehr deutlich, muss man sagen. Die Arbeitslosenzahlen in USA sind niedrig, die Wirtschaft wächst und so, also das hat auch positive Auswirkungen. Aber vor allem hat das natürlich die Menschen, die jetzt eben grundsätzlich mal für einen starken Staat einstehen, der viel Geld ausgibt, auch erfreut. Aber ich glaube, man muss deutlich sagen, trotz dieser positiven Zahlen sind die sozialen Probleme der USA einfach nicht gelöst. Nicht zuletzt auch, weil konservative Demokraten vieles ausgebremst haben. Besonders zu nennen ist da der Senator Joe Manchin aus West Virginia, einem sehr konservativen Bundesstaat. Und der gilt eben als Kohlelobbyist, wird unterstützt von der fossilen Industrie. In seinem Bundesstaat gibt es eben auch viele Kohleminen und der hat viele insbesondere Klimaschutzprogramme von Joe Biden ausgebremst. Ja, und das war's noch lange nicht. Vielleicht das größte Problem von Joe Biden:

 Jana Münkel
Das ist Bidens Kurs im Gazakrieg. Das kostet den viel Zustimmung und Sympathien und er versucht es da so ein bisschen allen recht zu machen. Also er versucht auf der einen Seite Israel zu unterstützen und das auch immer wieder deutlich zu machen, aber zugleich versucht er immer wieder auch zur Mäßigung in Gaza aufzurufen. Und dieser Schlingerkurs, der überzeugt viele aber trotzdem nicht. Also auf der einen Seite gibt es die jüdischen Wähler:innen, die sagen das ist uns nicht solidarisch genug mit Israel. Und es gibt aber dann auf der anderen Seite muslimische Wähler:innen und auch viele sehr linke Menschen, die eigentlich Biden unterstützen würden, die sagen, da ist nicht genug Solidarität aus unserer Sicht mit Gaza. Und da gibt es dann in dem Zusammenhang einfach ganz viel Kritik am sogenannten Genozid. So wird es dann eben in diesen Kreisen genannt in Gaza. Also seit Wochen wird Joe Biden auf Veranstaltungen mit Rufen wie "Genozidjoe" und "Waffenstillstand jetzt" empfangen. Das heißt, da hat er auch nicht so einen leichten Stand.

 Ulf Buermeyer
Das ist einfach eine extrem schwierige Position, weil natürlich auch jüdische Menschen in den Vereinigten Staaten ein ganz wichtiges Wählerpotenzial für die Demokraten sind. Das heißt also, es ist einfach im Grunde eine Situation, er ist so zwischen zwischen Baum und Borke oder in Amerika sagt between a rock and a hard place. Es ist einfach ganz schwer, da irgendwie Punkte zu machen. Einen finde ich sehr eindrucksvolles Beispiel gibt es da aus den letzten Tagen von den demokratischen Vorwahlen in Michigan.

 Jana Münkel
Da gibt es nämlich einen sehr großen Anteil arabischstämmiger Amerikaner:innen. Dienstag vergangener Woche, du hast es gesagt, Ulf, waren da die Vorwahlen und da gab es richtig so was wie eine uncommitted Kampagne. Also ist es so, dass auf den Wahlzetteln für den Präsidentschaftskandidat, der da in den Vorwahlen gewählt werden soll, es auch einen Platz gibt für "ich weiß nicht" oder "ich bin da unentschlossen", also ein Kreuzchen für uncommitted gesetzt werden kann. Und Biden hat in Michigan zwar mit 81 % gewonnen, aber diese uncommitted Kampagne, die hat auch total gezogen. 13 % haben eben uncommitted angekreuzt, also unentschlossen. Das sind über 100.000 demokratische Wähler:innen, die dann gesagt haben, nein, ich find nicht, dass ich Biden unterstützen kann, beziehungsweise ich bin da unentschlossen und das ist schon ein großes Potenzial. Und jetzt auch vom Super Tuesday hört man, dass das doch eine ganz große Rolle auch gespielt hat.

 Ulf Buermeyer
Also ich finde die Zahlen schon krass, ne? Biden hat keinen ernstzunehmenden Gegenkandidaten und bekommt trotzdem nur 81 %. Ja, nur 4/5. Einer von fünf Menschen, die bei den Demokraten registriert sind, hat entweder irgendwen anderes gewählt oder eben 13 % dieses uncommitted. Also das zeigt schon dieses große Grummeln so an der demokratischen Basis. Und wir haben drei Probleme aufgezählt. Aber das Zentrale scheint wohl zu sein tatsächlich, sein Schlingerkurs in Sachen Gaza. Ja, und die Folge im Wahlsystem ist dann, dass die von Biden Enttäuschten natürlich noch lange nicht Trump wählen. Die sind ja im Zweifel eher linker, eher progressiver als der Kurs von Joe Biden. Aber die Sorge ist nun, dass viele von ihnen einfach nicht zur Wahl gehen könnten. Das ist dieses, was man in der Politikwissenschaft so schön asymmetrische Demobilisierung nennt. Das heißt also, Menschen werden demobilisiert nur auf einer Seite des politischen Spektrums. Die Trumpwähler:innen sind in der Tendenz ziemlich radikalisiert. Die gehen mit großer Wahrscheinlichkeit auch hin, damit ihr großer Held Donald Trump, wieder Präsident wird. Und auf demokratischer Seite ist diese Begeisterung einfach überhaupt nicht da. Und das alleine könnte schon reichen, damit Donald Trump diese berühmten Swing States, diese sechs, sieben entscheidenden Bundesstaaten gewinnt.

 Jana Münkel
Also eigentlich so eine Einschläferungstaktik, oder?

 Ulf Buermeyer
Ja genau, man kann das so als kalte Füße Taktik oder eingeschlafene Füße Taktik. Es geht so ein bisschen darum, die nicht so ganz begeisterten Demokraten einfach zu Hause zu lassen. Damit hat Donald Trump zum Beispiel auch nach einigen Analysen jedenfalls die Präsidentschaftswahl 2016 gewonnen, insbesondere mit Kampagnen, die Menschen mit Migrationshintergrund davon abgehalten haben sollen, so targeted ads auf Facebook, für Hillary Clinton zu stimmen. Er hat also die Clintonwähler:innen, die potenziell nicht gerade zu Trumpwählern gemacht, aber er hat es halt geschafft, dass sie auch nicht Hillary gewählt haben und das kann dann eben in Swing States schon reichen. Tja, was bedeutet denn das jetzt?

 Jana Münkel
Ja, wenn wir nach vorne gucken, müssen wir, finde ich, trotzdem noch mal nach hinten gucken und noch mal kurz Bilanz ziehen. Was war denn an Trumps Präsidentschaft Nummer eins eigentlich so ein Riesenproblem? Also das klingt jetzt wie so eine naive, wie so ein naiver Claim, aber ich glaube, wir müssen es noch mal aufzählen: er hat den Iran Nuklear Deal gekündigt, er hat mit Austritt aus der NATO gedroht und es gab noch ein paar andere Punkte, die wir da noch nennen sollten.

 Ulf Buermeyer
Es war ziemlich gruselig. Es gab auch innenpolitisch natürlich Rabatz und Populismus an allen Ecken. Es gab den berühmten Muslim Ban. Falls man sich noch erinnert. Also Menschen aus muslimischen Staaten oder aus bestimmten Staaten durften einfach pauschal nicht mehr einreisen in die USA, selbst wenn sie eigentlich ein dauerhaftes Visum hatten, eine Niederlassungserlaubnis, was weiß ich. Das war alles völlig egal mit einem Mal. Das musste dann von Gerichten mühsam wieder zusammengestrichen werden, dieses Programm. Außerdem hat er natürlich konsequent vier Jahre lang Politik gemacht gegen Menschen aus Mittel- und Südamerika, die in die USA immigrieren könnten, da gab es schreckliche Bilder von Kindern in Käfigen und so. Also das war schon, das war schon aus einer menschenrechtlichen Perspektive, waren das vier ganz, ganz dunkle Jahre, aber auch aus der Perspektive der internationalen Politik. So, das war Trump eins. Und jetzt ist die Frage was wird bei Trump 2.0 passieren? Ich glaube, da muss man sagen, er hat sein Potenzial, sein destruktives, rassistisches Potenzial 2017 bis 21 noch bei weitem nicht ausgeschöpft.

 Jana Münkel
Genau die Wahl, die kam ja auch für ihn, so wird es zumindest analysiert, total überraschend. Also er war nicht so gut vorbereitet, wie er hätte sein können. Und da gibt es in den Analysen einen Begriff, der immer wieder mir über den Weg läuft. Das sind die Adults in the Room, also die Erwachsenen im Raum, die das Schlimmste verhindert haben sollen. Und das sieht auch Jana Puglierin vom Thinktank European Council on Foreign Relations so. Im Deutschlandfunk Kultur hat sie das so erklärt:

 Jana Puglierin
Damals gab es die sogenannten Erwachsenen im Raum. Die wurden in der Analyse und in der Presse mal so genannt. Das waren etablierte Republikaner, die noch nicht so sehr von dem eigentlichen Kurs der Republikaner abgewichen sind. Und wo man gedacht hat, na ja, wenn diese Erwachsenen im Raum sind, dann können die Trump einhegen. Und natürlich hatte man Checks and Balances in den USA. Man hatte die Bürokratie, man hatte die Justiz und die Demokratie hat ja auch gehalten in den USA, sie war resilient.

 Ulf Buermeyer
Und da ist eben die große Sorge, dass wird nicht noch mal passieren. Die Resilienz der US Demokratie dürfte beim nächsten Mal ziemlich auf die Probe gestellt werden, denn die Republikaner und das Team Trump sind diesmal vorbereitet, wie selten eine Regierung vorbereitet war.

 Jana Münkel
Und das ist ganz konkret so, dass die nicht nur eine neue Politik planen. Ich meine, das ist ja was relativ Normales. Wenn ein Lager, ein anderes Lager an die Macht kommt, dann ist es logisch, dass jemand sagt, ich habe hier andere Visionen, Das wäre ja noch was Demokratisches, eine neue Mehrheit, neue Inhalte sozusagen. Aber Trump plant was ganz anderes. Er plant mit den Republikanern wirklich einen kompletten Umbau der amerikanischen Demokratie. Und das muss man wirklich so sagen. Constanze Stelzenmüller ist die Direktorin des Center on the United States and Europe und ist Transatlantikexpertin. Und sie sagt, die MAGAner, also die Make America great again Leute, die wollen die liberal repräsentative amerikanische Verfassungsordnung komplett umbauen. Und zwar so ein bisschen nach dem Vorbild von Viktor Orbáns Ungarn.

 Ulf Buermeyer
Ja, also der Kerngedanke ist, dass die heutige, auch nicht perfekte, aber doch grundsätzlich demokratische Ordnung in den Vereinigten Staaten umgebaut werden soll zu so einer illiberalen Demokratie. Wo es also schon noch Wahlen gibt, aber deren Ergebnis im Grunde von vornherein feststeht und wo es in Wirklichkeit keinen politischen Pluralismus mehr gibt. Also wo es eine Einheit von Kirche und Staat gibt, wo es einen weißen Ethnonationalismus gibt, der alle anderen Ethnien möglichst weit von der Macht fernhält. Und dementsprechend skeptisch blickt auch Jana Puglierin vom European Council on Foreign Relations, auf das Programm der Konservativen.

 Jana Puglierin
Was das Trumplager vorhat, ist eben eine innenpolitische Revolution, ein Umbau der Demokratie, die ihm ungeahnte neue Macht gibt und ihn eben, er ist dann nicht mehr eingehegt, sondern empowered, das zu tun, was er will.

 Jana Münkel
Und das, was Jana Puglierin da als innenpolitische Revolution bezeichnet, das hat auch einen Namen. Die Planung für so eine mögliche zweite Präsidentschaft nennt sich Project 2025. Könnt ihr auch gern mal reinklicken. Es gibt da eine große Website www.project2025.org. Da haben sich 50 konservative Organisationen zusammengeschlossen unter der Führung der sogenannten Heritage Foundation. Das ist eine nationalistisch konservative Denkfabrik, so das Flaggschiff des Lagers Make America Great Again. Und das Ziel ist, wir haben es eigentlich schon gesagt, diesmal sind wir mehr vorbereitet als bei der ersten Präsidentschaft.

 Ulf Buermeyer
Was das genau bedeutet, kann man nachlesen im sogenannten Mandate for Leadership. Das ist ein knapp 900 Seiten starkes Playbook, also ein detailliertes Drehbuch für die kommende Trumppräsidentschaft. So hoffen sie jedenfalls. Dazu muss man sagen, so ein Mandate for Leadership ist an sich gar nicht unbedingt etwas Neues. Das bringt die Heritage Foundation seit den Achtzigern raus. Das Besondere an diesem Playbook sind die Inhalte. Und da wollen wir jetzt mal so ein paar Stichworte aufzählen. Zum Beispiel fordert das Playbook eine Rückkehr zum Isolationismus. Die Vereinigten Staaten sollen aus der Weltgesundheitsorganisation, der Weltbank und dem Internationalen Währungsfonds austreten. Das wäre also schon eine echte Schockwelle durch die internationale Ordnung, so wie sie seit dem Zweiten Weltkrieg mit den Vereinten Nationen und ihren Unterorganisationen aufgebaut worden ist.

 Jana Münkel
Ja, und dann ein anderes wichtiges Thema: Thema Klimawandel. Wenn es da nach den MAGAnern geht, gibt es den sozusagen nicht. Beziehungsweise die USA sehen sich da nicht in der Verpflichtung, da irgendwas gegen zu tun. Also es ist im Playbook die Rede vom Ende des Kriegs gegen fossile Brennstoffe. Sagt glaube ich einiges.

 Ulf Buermeyer
Und auch die NATO ist aus Sicht der MAGAner eigentlich Geschichte. Wobei man dazu sagen muss, austreten müssen die USA gar nicht offiziell. Wenn Donald Trump einfach beschließt, den Artikel fünf, also diese gegenseitige Beistandspflicht nicht wirklich ernst zu nehmen, nicht wirklich umzusetzen, dann ist es eigentlich aus mit der NATO. Das hatten wir ja schon in der Lage ein paar mal, weil die anderen NATO Staaten alleine so eine glaubwürdige Abschreckung einfach nicht leisten können. Aber ich denke, neben diesen außenpolitischen Schockwellen ist der wichtigste Punkt eigentlich, das haben wir eben anfangs schon angedeutet, was die MAGA Leute, was Project 2025 im innenpolitischen Raum vorhaben, das muss man so deutlich sagen. Es ist geplant zum einen der Abbau, zum anderen die totale Gleichschaltung der US Bundesbehörden.

 Jana Münkel
Und ich finde, da lohnt sich auch wirklich mal zu schauen, was sagen denn da die, die diesen Umbau dann planen? Russ Vought, der ist Vorsitzender des konservativen Centre for Renewing America, und der hat gesagt, der erste Tag des Präsidenten wird eine Abrissbirne für den Verwaltungsstaat sein.

 Ulf Buermeyer
Das muss man erst mal sacken lassen. Verwaltungsstaat, der sogenannte administrative State, das ist aus Sicht von konservativen und radikalliberalen Amerikaner:innen quasi das Böse an sich. Bundesbehörden, die gelten quasi als des Teufels. Sie sind als solche zu bekämpfen. Davon sollte es so wenig wie möglich geben für bestimmte Leute. Die dahinterstehende Vorstellung ist, der Staat lässt die Leute am allerbesten in Ruhe. Und der Staat ist eigentlich, sollte idealerweise nur für zwei Sachen zuständig sein: für die Währung, selbst da sagen manche lieber Krypto und vielleicht noch für äußere Sicherheit, also für's Militär. Ansonsten sollte der Staat die Menschen im Wesentlichen in Ruhe lassen, also eine ultraliberale Position. Und das führt dazu, dass nach dem Programm, das da auf dem Tisch liegt, zentrale Behörden des Bundes abgeschafft, völlig abgeschafft werden sollen.

 Jana Münkel
Also zum Beispiel, ich nenne mal ein paar, FBI, Homeland Security, Bildungsministerium, Handelsministerium inklusive Datenschutzbehörde der USA und andere sollen nicht abgeschafft werden, aber viel kleiner werden. Also so einem totalen Schrumpfungsprogramm unterliegen. Das Justizministerium zum Beispiel.

 Ulf Buermeyer
Das ist ja in den USA zugleich die oberste Anklagebehörde und der sogenannte Attorney General. Das soll alles abgewickelt werden oder ganz massiv eingedampft werden. Damit sollen dann entsprechend die Möglichkeiten dieser Behörden begrenzt werden. Aus Sicht dieser Menschen, die das fordern, quasi in das Leben der Menschen reinzuregieren. Und vielleicht noch dramatischer für so rechtsstaatliche Grundprinzipien wie Rule of Law ist der Gedanke, dass die Behörden, die es dann immer noch weiter geben soll, dass die eben auf Linie gebracht werden sollen, dass die gleichgeschaltet werden sollen mit dem Weißen Haus. Da gab es nämlich bisher aus der Sicht Trumps jedenfalls ein Problem. Nicht alle Beamten, das sind ja Zehntausende in den US Behörden waren MAGA Extremisten.

 Jana Münkel
Und es gibt eben zehntausende Beamte in den Behörden des Bundes. Also wir haben es schon genannt, vom FBI bis zum National Park Service. Und da ist es wichtig zu sagen, dass amerikanische Beamte eben nicht auf den Präsidenten vereidigt werden, sondern auf die Verfassung und die Verfassung schreibt fest, der Kongress kontrolliert die Regierung und schreibt den Bundesbehörden vor, wie sie zu agieren haben.

 Ulf Buermeyer
Genau und die Idee dahinter ist, der Kongress erlässt eben die Gesetze und die Beamten halten sich zuallererst mal an die Gesetze. Ja, der Präsident ist der Chef der Exekutive. Aber er kann die Exekutive eben nur im Rahmen der Gesetze tatsächlich steuern. Das ist die bisherige, seit Jahrhunderten etablierte Verfassungsordnung in den Vereinigten Staaten, und das heißt auf Englisch so schön rule of law. Das heißt also, es bedeutet, das Parlament macht die Gesetze und die Exekutive führt sie aus. Der Präsident ist zwar der Chef dieser Exekutive, aber er kann eben nicht regieren, wie er will, sondern nur im Rahmen der vom Kongress bestimmten Gesetze. Und diese Regeln, die könnten eben Beamte davon abhalten, 100 % auf Trumpkurs zu segeln, insbesondere wenn Donald Trump das geltende Recht brechen will. Und das würde auf der anderen Seite natürlich diese konservative Revolution potenziell bremsen. Im Prinzip so ein bisschen so, wie das diese Adults in the Room, die Erwachsenen im Raum ab 2017 gemacht haben. Und daher will das Projekt 2025 jetzt dafür sorgen, dass alle führenden Beamten auf Trumpkurs segeln und im Zweifel nicht mehr zählt, was im Gesetz steht, sondern was Donald Trump sagt. Und das ist jetzt nicht nur unsere Idee. Das sagen die Menschen, die das für richtig halten auch selber so.

 Jana Münkel
Genau, es gibt einen Direktor dieses Projekt 2025, der heißt Paul Dans, der ist eben der Direktor des Presidential Transition Projects und der sagt Project 2025 ist systematically preparing to march into office and bring a new army. Aligned, trained and essentially weaponized conservatives ready to do battle against the deep state.

 Ulf Buermeyer
Also auf Deutsch. Projekt 2025 ist dabei, ganz systematisch einen Sturm in die Büros des Bundes vorzubereiten. Und sie wollen mit sich bringen, eine Armee von auf Linie gebrachten, trainierten und im Grunde zu einer Waffe umfunktionierten Konservativen, die bereit sind, gegen den sogenannten Deep State zu kämpfen, also gegen das, was Konservative für die böse Verwaltung in Washington halten, für den Deep State, also wahrscheinlich müsste man sagen die Verwaltung, die sich selbstständig gemacht hat und von niemandem mehr richtig kontrolliert wird. Das ist die Idee.

 Jana Münkel
Oder die eben aus Sicht Trumps blockiert und wie so eine Bedrohung gesehen wird. Und ich finde, das muss man noch mal sacken lassen. Da ist einfach so eine Kriegsrhetorik dabei. Das ist jetzt so in dem, wie wir es übersetzt haben und wie man es vielleicht erst mal versteht, auch wirklich eine Kriegsrhetorik, die erst mal diese verbale Aufrüstung nutzt. Aber wenn man an den 6. Januar denkt, da waren halt auch wirklich Waffen im Spiel und da wird es mir schon ein bisschen anders.

 Ulf Buermeyer
Beim Sturm auf's Kapitol. Ja, genau. Das ist tatsächlich gruselig und ich meine, das muss man sich überlegen. Was bedeutet das in der Praxis? Die Grundidee dahinter ist, Politik ist Personal. Also es geht um diese Army, diese Armee, die da gerade aufgebaut werden soll. Dazu muss man fairerweise sagen, also es ist ganz normal, dass bei dem Wechsel einer sogenannten Administration, also bei einem neuen Präsidenten von einer anderen Partei, auch die Beamten im öffentlichen Dienst ausgetauscht werden, aber normalerweise eben nicht alle. Normalerweise tauscht man da so circa 4000 politische Beamte an der Spitze aus, aber hier ist der Plan, bis zu 50.000 Beamte zu ersetzen. Und das bedeutet einfach schlicht und ergreifend, die werden gefeuert. Da werden 50.000 Leute rausgeschmissen und 50.000 radikale Republikaner 150 prozentig auf Trump eingeschworene Leute werden an deren Stelle gesetzt und da ist dann mit Rule of Law nicht mehr viel los. Da wird dann nicht mehr das Gesetz gelesen, sondern da wird einfach nur jeden Morgen schön auf Twitter geguckt, was Donald Trump für richtig hält. Und das muss man sich mal überlegen. Das ist, das ist tatsächlich aus der Perspektive der Gewaltenteilung eine echte Katastrophe. Das ist wirklich ein Umbau einer Verfassungsordnung, was sie da vorhaben.

 Jana Münkel
Ich fand auch einen Ausdruck von Constanze Stelzenmüller, der Transatlantikexpertin, ganz passend. Die schreibt in dem Zusammenhang von willfährigen Loyalisten, die da bereitstehen, die total überzeugt sind, die trainiert sind. Wir haben es gehört, das wird mit Workshops gemacht, das wird mit Onlineangeboten gemacht, die eben bereitstehen, um da wirklich sofort einzumarschieren.

 Ulf Buermeyer
Ja, Trumps Leute unterfüttern dieses totale Durchregieren aus dem Weißen Haus auch noch durch eine neue, quasi juristische Doktrin mit der sogenannten unitary executive theory. Das bedeutet auf Deutsch, bisher war eben allgemeine Meinung, dass Behörden die Kompetenz und auch die Pflicht haben, das Recht anzuwenden. Rule of law. Das heißt, der Präsident konnte auch nicht direkt durchregieren durch Einzelanweisung. Er konnte also jetzt in einer Behörde nicht einfach sagen, hier, ihr macht das jetzt so und so. Wenn der Präsident der Meinung war, dass eine Behörde irgendwas falsch macht, dann konnte er im Prinzip nur den Chef austauschen. Dann musste der neue Chef aber auch vom Kongress bestätigt werden und so, da gab es also immer noch sogenannte Checks and Balances, also quasi Kontrolle der Macht. Nach dieser neuen Theorie, dieser unitary executive theory hätte der Präsident nahezu uneingeschränkte Macht über die ganze Regierung. Er könnte überall hineinregieren, durchregieren. Das Weiße Haus könnte dann im Alleingang handeln und diese ganzen früher an das Gesetz gebundenen Beamten, die wären im Grunde alle nur noch Marionetten in einem großen Spiel von Donald Trump. Tja, und ihr habt es gehört dieses Playbook ist eben wegen der guten Chancen von Donald Trump kein bloßer Fiebertraum von radikalen Rechten in den Vereinigten Staaten, sondern es ist ein ganz realistisches Szenario. Wir müssen uns alle darauf einstellen, dass es genau so kommen könnte. Denn das wird geplant, das wird vorbereitet, das ist aufgeschrieben. Da stehen die auch zu, da haben die auch überhaupt keine Scham oder so. Große Frage, lässt sich das jetzt überhaupt noch irgendwie verhindern und wenn ja, wie?

 Jana Münkel
Ich wiege hier gerade so ein bisschen den Kopf, also die Hoffnung, dass Trump vom Wahlzettel gestrichen wird, die hat sich ja zumindest schon mal nicht erfüllt. Das war ja auch nicht als wahrscheinlich angesehen worden. Also es war ja eben, haben wir ja zu Beginn schon gesagt, die Frage, ob er zum Beispiel in Colorado vom Wahlzettel gestrichen wird und das dann auch vom Supreme Court auf Bundesebene bestätigt wird, war nicht der Fall. Also die Hoffnung hat sich nicht erfüllt. Jetzt ist es aber trotzdem so, um ein bisschen Optimistisches zu nennen, also du merkst schon Ulf, das fällt mir ein bisschen schwer, aber es ist ja schon so, dass amerikanische Wahlkämpfe in der Vergangenheit auch immer mal eine unerwartete Dynamik doch noch bekommen haben. Also ich erinnere da an den Sieg von Barack Obama, den lange viele nicht für möglich gehalten haben, wo dann doch sich noch mal was gedreht hat. Who knows? Vielleicht passiert noch was, was wir jetzt gar nicht auf dem Schirm haben. Und Trump wird doch nicht Präsident.

 Ulf Buermeyer
Tja, also man möchte sich so ein bisschen an diese Hoffnung klammern, aber mir scheint doch, dass die jetzt auch nur so ganz beschränkt realistisch ist, wenn ich ganz ehrlich bin. Ein Fünkchen Hoffnung ergibt sich vielleicht noch aus den möglichen finanziellen Problemen von Donald Trump. Er hat ja eine ganze Reihe von Verfahren am Hacken. Das hatten wir in der Lage auch schon, also allein vier Strafverfahren mit über 90 einzelnen Anklagepunkten. Aber dann gibt es auch noch Zivilverfahren, wo also Leute von ihm Schadenersatz fordern, Geldstrafen und Entschädigungszahlungen, die Gerichte gegen ihn schon verhängt haben, belaufen sich inzwischen auf über eine halbe Milliarde Dollar. Muss man sich mal überlegen. 537,3 Millionen Dollar genau genommen, sind bislang schon gegen ihn tituliert. Da kann man sich schon fragen, wie er das Geld eigentlich auftreiben will. Also er sonnt sich ja immer in diesem Bild, er sei ein sehr reicher Mann. Ganz genau weiß das niemand. Aber wenn ihr euch erinnert, er hat sich auch immer konsequent geweigert, seine Steuererklärung offenzulegen, seine Steuerbescheide. Insofern vielleicht ist er auch eigentlich gar nicht so wahnsinnig reich. Das werden wir jetzt mal sehen. Jedenfalls muss er bis zum 25. März diese 537,x Millionen Dollar aufbringen oder dafür jedenfalls eine Sicherheit hinterlegen, sonst könnte der Bundesstaat New York gegen ihn pfänden. Was bedeutet denn das jetzt letzten Endes?

 Jana Münkel
Na ja, das ist auch nicht ganz in letzter Konsequenz klar. Aber der CNN Autor Stephen Collinson zum Beispiel, der hat das analysiert und der meinte, ja, das wäre dann einfach eine persönliche Belastung für Trump. Und wenn sich herausstellt, dass der Expräsident weniger wohlhabend ist, als er behauptet, dann könnte das schon auch diesen Mythos dieses Reichenmoguls gefährden, auf dem er dann schon auch komplett eigentlich seine politische Marke aufbaut. Also so ein bisschen dieses Selbstverständnis Trumps könnte angekratzt werden, obwohl ich da danebenlegen würde, er hat mit so vielen Anklagen zu kämpfen und das schadet seinem Image, so wie wir es sehen, sehr, sehr, sehr wenig. Das heißt auch da so ein Kopfwiegen.

 Ulf Buermeyer
Ja, es gelingt ihm einfach bisher, die ganzen Angriffe von ganz unterschiedlichen Behörden und Privatleuten immer als politisch motiviert zu diskreditieren. Also normalerweise würde man ja sagen, wenn jemand vier Strafverfahren über 90 Anklagepunkte am Hacken hat, ist er politisch tot. In Deutschland geht das ja schon, wenn nur bei einem Politiker durchsucht wird, war es das ja schon, je nach Vorwurf so ein bisschen. Also da sind wir in Deutschland eigentlich noch deutlich sensibler. In den Vereinigten Staaten hingegen schafft er es, diese Verfahren von unabhängigen Justizbehörden komplett zu diskreditieren als Attacken vom Deep State, da haben wir ihn wieder, oder eben als Attacken von irgendwelchen radikalen Demokraten. Oder er sagt dann auch gerne mal von Kommunisten und deswegen sind diese Verfahren für ihn bislang jedenfalls nicht schädlich. Man könnte sogar sagen, dass sie seine Basis vielleicht sogar noch eher radikalisieren, um sich so wagenburgartig um ihren großen Helden zu scharen. Ich glaube deswegen auch, wir müssen uns einfach mit diesem Szenario anfreunden, dass er die Wahlen gewinnt im November. Klar, der Wahlkampf, der eigentliche Wahlkampf steht uns noch bevor. Da kann eine Menge passieren. Jana, du hast es, glaube ich, völlig zu Recht gesagt. Aber wir müssen uns darauf vorbereiten. Und die Frage ist, sind wir es? Ist Deutschland, ist Europa, ist die NATO überhaupt auf eine neue Trump Präsidentschaft vorbereitet?

 Jana Münkel
Es gibt nicht so wenige Experten, die sagen Europa ist überhaupt nicht gut vorbereitet. Und dann kommt noch dazu, dass einige auch in der deutschen Politik nicht wahrhaben wollen, dass das, was wir da gerade verhandelt haben, ein realistisches Szenario ist. Das heißt, aus meiner Sicht ist es schon dringend notwendig, dass Europa ein Fahrplan entwirft und sich auch abstimmt für den Fall, dass Trump Präsident wird. Also zum Beispiel wird da ja immer mal das Weimarer Dreieck genannt, also dieses Dreieck aus Frankreich, Polen, Deutschland in der politischen Zusammenarbeit, was wiederbelebt werden sollte und was aber viel ernster genommen werden sollte. Und in dem Zusammenhang ist ja auch ein Hoffnungsschimmer, sage ich mal, dass es in Polen eine neue Regierung gibt, die da auch mitziehen würde. Jetzt ist aber das Weimarer Dreieck, weil Deutschland und Frankreich da drin hängen, vielleicht doch nicht ganz so stark, wie es sein könnte.

 Ulf Buermeyer
Ja, das muss man sehen. Also Olaf Scholz und Emmanuel Macron scheinen ja jedenfalls mal dieses bilaterale Verhältnis, die bilaterale Zusammenarbeit total zu vergeigen. Sie sind eigentlich die Führungskräfte in der Europäischen Union, aber sie reden momentan einfach eher übereinander als miteinander. Die Bodentruppenäußerung von Macron und die mega aggressive Reaktion von Scholz darauf war ja letzte Woche schon ausführlich Thema. Also das klingt jetzt erst mal nicht nach einem guten Klima zwischen Berlin und Paris und das klingt für mich deswegen auch nicht so, als wenn das Weimarer Dreieck jetzt so unmittelbar arbeitsfähig wäre. Aber auf der anderen Seite, ich denke, auch Donald Tusk ist ein ganz engagierter Europäer. Möglicherweise gelingt es ihm ja, Macron und Scholz einfach mal an einen Tisch zu holen und zu sagen, so Jungs, die Zeiten sind schwer und die Zeiten sind hart. Wenn Donald Trump kommt, brauchen wir einen Plan. Das wäre so meine große Hoffnung, dass Donald Tusk, klar, der hat innenpolitisch auch gerade echt ne Menge Baustellen. Aber dass der sich jetzt hinstellen könnte hoffentlich und sagt Jungs, jetzt hört mal auf hier mit euren Sandkastenspielen, wir brauchen jetzt einfach Leadership.

 Jana Münkel
Wir kommen zu unserem nächsten Thema. Und zwar geht es um eine Aufnahme, die seit Freitag im Netz kursiert. Die Chefredakteurin des russischen Propagandamediums Russia Today, die hat ja am Freitag einen 38 minütigen Audiomitschnitt veröffentlicht und seitdem steht in Deutschland die innenpolitische Diskussion Kopf, aber auch die außenpolitische, würde ich sagen. Nach russischen Angaben geht es um eine Telefonkonferenz vom 19. Februar, und darin sind Gespräche zu hören von ranghohen Offizieren der Luftwaffe. Unter anderem ist der Chef der Luftwaffe da zugeschaltet, Inspektor Ingo Gerhartz.

 Ulf Buermeyer
Ja, In diesem Gespräch geht es inhaltlich unter anderem um die Frage, ob Taurus Marschflugkörper technisch/theoretisch in der Lage wären, die von Russland gebaute Brücke zwischen Russland und der russisch besetzten ukrainischen Halbinsel Krim zu zerstören. Außerdem auch um die Frage, ob die Ukraine den Einsatz von Taurus und damit den Beschuss zum Beispiel dieser Kertsch Brücke ohne Beteiligung von Soldatinnen und Soldaten der Bundeswehr bewerkstelligen könnte. Und ich glaube, das letzte ist inhaltlich vielleicht der spannendste Punkt an diesem abgehörten Gespräch.

 Jana Münkel
Weil dieses Gespräch, das eben eigentlich geheim bleiben sollte, zumindest natürlich nicht irgendwie für alle zugänglich online landen sollte, nahelegt, dass es schon auch ohne Soldaten ginge, also ohne deutsche Soldaten, das muss ich noch spezifizieren, ginge, die Taurus Marschflugkörper in der Ukraine einzusetzen, weil nämlich, und das ist in dem Gespräch auch Thema, Briten vor Ort sind. Da sagt einer so, ich paraphrasiere jetzt, na ja, die sind ja vor Ort, die könnten das ja dann vielleicht wuppen und die könnten vielleicht den Taurus programmieren. So wird es wörtlich nicht gesagt, aber so wird es interpretiert.

 Ulf Buermeyer
Außerdem gibt es noch einen zweiten Punkt, und der ist innenpolitisch vielleicht noch dramatischer. Offenbar sind ja britische Soldaten, die längst in der Ukraine im Einsatz sind, auch aus russischer Sicht gar kein Problem, oder jedenfalls haben sie bislang nicht zu irgendwelchen russischen Gegenschlägen Anlass gegeben. Warum sollen dann eigentlich deutsche Soldaten in der Ukraine plötzlich eine rote Linie darstellen? Und genau das, deutsche Soldaten in der Ukraine sollte ja aus der Perspektive des Bundeskanzlers das zentrale Argument sein, warum Taurus nicht geliefert werden kann, weil angeblich diese Taurussysteme nur von Deutschen in der Ukraine programmiert werden können.

 Jana Münkel
Und das ist eben auch der Grund, warum Olaf Scholz, der Bundeskanzler, jetzt ziemlich unter Druck steht, weil er eben seine Absage begründet hat mit, wir brauchen deutsche Soldaten auf ukrainischem Boden für die Taurus Marschflugkörper. Und das geht nicht aus seiner Sicht. Und das wirkt eben jetzt auch nach der Veröffentlichung dieses Gesprächs immer unplausibler. Deswegen muss er sich da ziemlich viele Fragen gefallen lassen.

 Ulf Buermeyer
Das sind quasi die Inhalte dieses Gesprächs. Aber es stellt sich natürlich auch die Frage, wie konnte das denn überhaupt passieren? Wie kann es denn sein, dass eine russische Journalistin einen 38 minütigen Mitschnitt hat eines hochgeheimen Gesprächs zwischen Führungskräften der deutschen Streitkräfte. Die Tageszeitung Rheinpfalz aus Koblenz formuliert, der deutsche Sicherheitsapparat habe offenbar mehr offene Türen als ein Adventskalender am Heiligabend. Kann man das wirklich so sagen oder ist das ein bisschen überspitzt?

 Jana Münkel
Also ist es so, gucken wir uns erst mal die technischen Fakten an, dass das Gespräch über die Plattform Webex gelaufen ist. Das ist eine Online Kommunikationsplattform, also so was wie Zoom oder Teams oder so, und da haben dann im Anschluss verschiedene Theorien eine Rolle gespielt und kursiert. Also so die Frage, ob die Plattform, ob Webex eben nicht sicher genug ist für die Inhalte, die da besprochen wurden. Inzwischen ist aber klar, die Plattform an sich war nicht das Problem.

 Ulf Buermeyer
Nein, sondern diese Plattform war aus dem Ausland offenbar nicht erreichbar. Denn einer der Offiziere, die an dem Gespräch beteiligt waren, wollte sich von Singapur aus einwählen. Das hat dann nicht funktioniert. Und dann hat er einen zentralen Fehler gemacht. Dann hat er eben sich nicht über den Webbrowser bei Webex eingewählt, über den Laptop, sondern per ganz normaler Handyverbindung. Und diese ganz normale Handyverbindung, diese Telefonleitung, konnten die Russen offenbar abhören.

 Jana Münkel
Ja, und ich fand's witzig, Ulf, wir haben im Vorhinein schon mal kurz drüber gesprochen und schon gesagt, na ja, das ist halt sicherheitstechnisch natürlich ein Supergau und du hast dann aber so ein bisschen lapidar abgewunken, meintest ja, dich hat einfach diese Abhöraktion überhaupt gar nicht überrascht.

 Ulf Buermeyer
Nee, muss ich ganz ehrlich sagen. Denn, dass normale Handys und Telefone abgehört werden können, das ist seit vielen, vielen Jahren klar. Wir erinnern uns vor einigen Jahren gab es sogar mal einen Abhörskandal, wo die Vereinigten Staaten von ihrer Botschaft in Berlin aus, die ja direkt neben dem Brandenburger Tor liegt, offenbar ständig Telefongespräche im Berliner Regierungsviertel mitgeschnitten haben. Also die USA machen das weltweit, ständig und überall. Aber Russland kann das eben auch. Telefongespräche mitschneiden. Das ist inzwischen, muss man sagen, das kleine Einmaleins der so genannten Signal Intelligence, also der IT Aufklärung. Und zugleich muss man sagen, kann Russland natürlich noch viel mehr. Also es wäre grundsätzlich auch gar nicht unvorstellbar gewesen, dass Russland tatsächlich zum Beispiel einen der beteiligten Laptops der Offiziere mit einem Virus infiziert hätte. Das machen die Russen auch dauernd. Dazu gibt es gerade eine großartige Dokumentation in der ARD unter dem Titel Putins Bären steht die in der ARD Mediathek, haben wir für euch in den Shownotes verlinkt und das Ganze, dieses Hacking und das ist eben Teil der sogenannten hybriden Kriegsführung. Also Krieg wird heute im 21. Jahrhundert nicht nur mit Panzern, Granaten und Maschinengewehren geführt, sondern auch mit Computern, mit Hackern. Also das Reinhacken in IT Systeme ist inzwischen ein ganz normales Mittel der Kriegsführung und insofern muss ich immer so ein bisschen schmunzeln, wenn der Bundeskanzler sagt, Deutschland darf nicht in einen Krieg mit Russland hineingezogen werden. Russland führt seit Jahren einen ziemlich aggressiven IT Krieg gegen Deutschland. Russische Hacker haben sich in den Bundestag gehackt und dabei mindestens 16 Gigabyte Daten ausgefiltert. Das waren auch gegen Ende der Merkelzeit. Also ganz ehrlich, wir sind längst in einem hybriden Konflikt. Nur bislang wird eben nicht konventionell geschossen. Ich glaube, das ist die Lage und insofern ist der Bundeskanzler da einfach nicht ganz auf der Höhe der Zeit, wenn er sagt, Deutschland darf nicht in einen Krieg reingezogen werden. Wie gesagt, aus meiner Sicht ist dieser Krieg jedenfalls in der IT Welt, leider längst traurige Realität.

 Jana Münkel
Jetzt müssen wir aber noch mal für den konkreten Fall, glaube ich, festhalten, wir haben ja festgestellt, das war jetzt nicht die Sicherheitsplattform oder die IT Plattform, die da das Problem war, sondern in dem konkreten Fall einfach, dass sich jemand per Telefonleitung eingewählt hat. Das heißt, in dem Fall wär's dann eher so ein individueller Fehler, individuelles IT Versagen, wenn man so will. Also so nach dem Motto, die Person hinter dem Laptop ist das Problem.

 Ulf Buermeyer
Ja, wie so häufig, wenn irgendwas mit der IT schiefgeht, sitzt das Problem vor dem Gerät und so auch hier würde ich denken, eigentlich fehlt es hier vor allem an der IT Kompetenz oder auch an der Schulung der beteiligten Offiziere. Natürlich dürfen geheime Infos nicht am Telefon besprochen werden und Telefon ist natürlich auch ein Call über Webex, wenn einer in einer Runde per Telefon sich in diese Runde einwählt. Also das ist eigentlich ziemlich banal. Man würde eigentlich erwarten, dass das Teil der IT Sensibilisierung ist in der Bundeswehr. Ob es da an der Schulung gefehlt hat, ob da individuelles Versagen im Einzelfall vorliegt, ist jetzt schwer zu sagen. Aber auf jeden Fall muss man sagen da muss nachgesteuert werden. Denn, ich denke, dieser Fehler wäre ja sehr leicht zu vermeiden gewesen.

 Jana Münkel
Stichwort andere Plattformen, die sicher sind. Signal zum Beispiel nutzt du ja auch viel, Ulf, ich auch.

 Ulf Buermeyer
Benutzen wir ständig. Bei der Lage nutzen wir, auch bei der Gesellschaft für Freiheitsrechte. Signal ist halt die Messenger App, die zurzeit so als der Goldstandard in Sachen IT Sicherheit gilt. Und zwar einfach deswegen, weil der Quelltext Open Source ist. Das heißt also da gibt es einfach sehr viele Nerds, sich diesen Quelltext anschauen und etwaige Fehler, so kann man jedenfalls hoffen, gefunden hätten. Auch das hilft natürlich nicht hundertprozentig. Wenn ein Handy gehackt ist, mit einem Trojaner zum Beispiel, Stichwort Bundestrojaner, Staatstrojaner, dann ist natürlich auch Signal nicht mehr sicher, aber ansonsten eben schon. Und insofern wundert man sich so ein bisschen, wieso nicht in der Bundeswehr schlicht und ergreifend gesagt wird, greift zum Handy, telefoniert über Signal, dann ist das Problem gelöst. Dann muss man sich auch nicht mehr mit dieser blöden Plattform Webex auseinandersetzen. Und zur Not, wenn man denn der Signalfirma nicht trauen will oder dieser Organisation die Signal veröffentlicht, dann kann man sich notfalls als Bundeswehr auch den Quelltext runterladen und quasi eine eigene Bundeswehr Signal App kompilieren. Das dauert also für einen halbwegs fähigen ITler keinen Tag, das System aufzubauen. Also wundert man sich so ein bisschen, wieso das passieren konnte.

 Jana Münkel
Schauen wir noch mal kurz auf die Reaktionen, die das ausgelöst hat. Politisch, Bundesverteidigungsminister Boris Pistorius spricht von einem Informationskrieg. Den Punkt hatten wir ja gerade schon, Ulf. Die Union, die fordert eine baldige Sondersitzung. Es gibt auch Stimmen, die einen Untersuchungsausschuss wollen. Es ist jetzt erst mal so, dass es am Montag weitergeht. Die Vorsitzende des Verteidigungsausschusses, Marie-Agnes Strack-Zimmermann von der FDP, die plant eine Ausschusssitzung kommenden Montag. Da soll auch Bundesverteidigungsminister Boris Pistorius von der SPD dann zugegen sein. Und die beteiligten Offiziere sollen auch befragt werden.

 Ulf Buermeyer
Tja, wie ist das jetzt alles zu bewerten? Ich finde, natürlich ist das super peinlich, dass eine russische Journalistin mit engsten Kontakten zum Kreml 38 Minuten geheime Bundeswehrberatung ins Netz stellen kann. Auf der anderen Seite, finde ich, ist es aber auch nicht überraschend. Wie gesagt, es ist nicht der ganz große Hack, sondern es handelt sich um einen Fall von menschlichem Versagen. Menschen machen Fehler, machen wir alle. Machen wir auch. In fast jeder Lage müssen wir irgendwelche Fehler korrigieren. Also das ist zutiefst menschlich. Sicherheitshalber sollte aber natürlich das Ministerium die Regeln überprüfen, schauen, ob man nicht so was wie einen sicheren Bundeswehrmessenger verwenden könnte statt einer so etwas anstrengender Webplattform. Und natürlich müssen Offiziere, mindestens Generäle besser ausgebildet werden, damit solche Fehler möglichst nicht passieren.

 Jana Münkel
Jetzt hat Boris Pistorius auch angekündigt, dass er da erst mal keine personellen Konsequenzen daraus ziehen möchte, weil es eben auch aus seiner Sicht ein individueller Fehler war, der verzeihlich ist. Finde ich jetzt auch erst mal in Anbetracht dieses Informationskrieges, dieses Stichwortes, das da sicherlich auch von Putin Kalkül dahinter steht, zumindest verständlich.

 Ulf Buermeyer
Ja, finde ich auch so, also ich denke, da sollte man irgendwo mal die Kirche im Dorf lassen, denn die Aufregung spielt nur Putin in die Karten. Da hat Boris Pistorius völlig zu Recht darauf hingewiesen, wenn man jetzt irgendeinen der besten Generäle feuern würde, weil er eben in einem Einzelfall versagt hat, was die IT Sicherheit angeht, dann würde man letztlich nur Putin einen Gefallen tun. Das wäre also genau die falsche Reaktion. Aber klar, der Fall macht schon deutlich, dass die Bundeswehr Stand heute doch nicht so ganz auf der Höhe der Zeit ist. Das gilt für konventionelle Waffen. Wir haben einfach nicht genügend Panzergranaten und was man so alles braucht. Aber es geht eben auch für die IT Kompetenz. Und wenn wir jetzt mal so ein bisschen rein rauszoomen aus dem Einzelfall, Jana, was denkst du, wie schwer beschädigt ist denn durch diesen ganzen Zirkus rund um den Abhörskandal und aber auch die Tauruslieferung oder -nichtlieferung, wie schwer beschädigt ist der Bundeskanzler?

 Jana Münkel
Also ich habe den Eindruck, dass das natürlich jetzt laut diskutiert wird, das aber unterm Strich jetzt nicht so viel übrig bleibt, was die Abhörgeschichte angeht. Also klar befeuert das jetzt noch mal diese Diskussion, sagt Scholz oder argumentiert er in der Öffentlichkeit mit validen Argumenten, warum er keine Taurus liefern will? Da finde ich, muss er vielleicht tatsächlich noch mal nachsteuern. Aber das ist ja auch eine Diskussion, die jetzt nicht erst seit gestern läuft. Die wird dadurch halt, finde ich, noch mal intensiver geführt und lässt sich jetzt nicht mehr so leicht verstecken. Aber ich würde nicht sagen, dass ihm das jetzt nachhaltig schadet. Außer, dass halt das Image des zögernden Kanzlers noch mal mehr befeuert wird. Wie siehst du das?

 Ulf Buermeyer
Ja, also ich finde, man muss schon sagen, es wird halt immer deutlicher, dass Olaf Scholz nicht die Wahrheit sagt im Bereich Tauruslieferung. Seine Argumente werden serienweise als nicht tragfähig entlarvt und das finde ich schon peinlich, dass er der deutschen Öffentlichkeit hier einfach nicht die Wahrheit sagt. Aus meiner Sicht illustriert das mal wieder, dass der Bundeskanzler eigentlich eine ganz andere Agenda hat bei den Waffenlieferungen. Meine persönliche These kann ich nicht beweisen, finde ich aber immer plausibler, wenn ich darauf schaue, ist einfach, der Bundeskanzler will den Konflikt in einem Schwebezustand halten. Natürlich soll Russland nicht gewinnen. Natürlich soll die Ukraine den Krieg nicht verlieren. Aber, und das ist das eigentliche Problem, die Ukraine soll auch nicht gewinnen. Und das finde ich das eigentliche Problem, dass dieses ständige Verzögern bei den Waffenlieferungen mit Argumenten, die sich ständig als letztlich unwahr herausstellen, dass das aus meiner Sicht nur noch den Schluss zulässt, dass es einfach darum geht, den Krieg am Köcheln zu halten. Das mag ja sogar quasi legitime Gründe dafür geben. Also vermutlich ist es so, dass Scholz einfach denkt, den Interessen Deutschlands ist am besten gedient, wenn Russland sich dort verkämpft, wenn es da einen Stellungskrieg gibt und keine Seite gewinnt. Möglicherweise trifft es zu, ja, dieses Reasoning, aber dann sollte er das den Deutschen auch ehrlich sagen. Dann muss er den Deutschen ehrlich sagen, wir wollen nicht, dass Russland dort den Krieg verliert, weil wir nicht wissen, inwieweit das Russland destabilisiert. Also man könnte sich ja zum Beispiel vorstellen, wenn Russland verliert. Das hat Professor Behrends in der letzten Lage auch gesagt, was bedeutet das für Putins innenpolitische Situation? Gibt es da einen Putsch in Moskau? Wer hat dann den Knopf auf den russischen Atomwaffen? Das ist ja eine, wie soll ich sagen, eine legitime Sicherheitsüberlegung. Nur dann muss man es den Menschen in Deutschland ehrlich sagen. Aber wahrscheinlich wäre das wiederum auch schwer kommunizierbar, weil es natürlich letzten Endes mit ukrainischen Leben spielt. Vermutlich ist das eben etwas, was man dann doch wiederum nicht so offen sagen kann. Insofern ja, ist der Bundeskanzler insofern jedenfalls beschädigt aus meiner Sicht, als er einfach als jemand dasteht, der nicht mit offenen Karten spielt.

 Jana Münkel
Und ich glaub, was auch noch ein wichtiger Aspekt ist, ist so dieser außenpolitische. Also es war in diesem Mitschnitt ja auch davon die Rede, wir haben es gesagt, dass ja die Briten dann den Taurus da schon irgendwie wuppen könnten. Und diese militärischen Details, die waren jetzt nicht komplett versteckt vorher. Also dass da britische Soldaten offenbar auf ukrainischem Boden agieren, das wird aber offenbar in Großbritannien als schwerer Vertrauensbruch bewertet, dass das jetzt da noch mal an die Öffentlichkeit gekommen ist. Also Exverteidigungsminister Ben Wallace, der hat gesagt, der NATO Partner Deutschland sei weder sicher noch zuverlässig, da russische Geheimdienste die Deutschen offenbar in großem Stil belauschten. Also auch da noch mal die Frage, wie steht Scholz außenpolitisch da und als was für ein Partner wird er angesehen?

 Ulf Buermeyer
Tja, ich würde sagen, er steht mit heruntergelassenen Hosen da. Wobei das, wenn man ehrlich ist, dann auch nicht mehr ganz dem Stand der Debatte entspricht. Ich bin jetzt nicht sicher, wann Ben Wallace das gesagt hat, vermutlich bevor deutlich wurde, dass es eben jetzt kein Hack war im deutschen Webex Server. Also ich habe das nicht noch mal recherchiert, aber meine Vermutung wäre, dass er das heute vielleicht nicht mehr in dieser Schärfe formulieren würde. Denn wie gesagt, Telefongespräche abzuhören, das ist jetzt No Rocket Science. Das machen die Briten auch. Und ich bin absolut sicher, dass auch die Russen wiederum in Großbritannien serienweise Telefongespräche mitschneiden. Also da würde ich mich an Ben Wallace' Stelle nicht so weit aus dem Fenster hängen. Aber wie gesagt, Deutschland sieht da einfach nicht gut aus, weil es in diesem Fall jetzt eben Deutschland getroffen hat. Und eins ist klar, diese Geschichte, insbesondere mit den neuen Infos zur Programmierung des Taurus, die dürfte auf jeden Fall dafür sorgen, dass die Diskussion um die Lieferung weiterläuft.

 Jana Münkel
Heute, Mittwoch früh, ist was Neues rausgekommen, und zwar das neue Jahrbuch Steuergerechtigkeit. Die Autor:innen, die haben die steuerpolitischen Versprechen zur Bundestagswahl analysiert, der verschiedenen Parteien und dann auch mit dem Koalitionsvertrag abgeglichen und ziehen jetzt eine Halbzeitbilanz der Ampel, was das Thema Steuern und Steuergerechtigkeit angeht. Und das Ganze kommt vom Netzwerk Steuergerechtigkeit, Ulf.

 Ulf Buermeyer
Ja das Netzwerk Steuergerechtigkeit ist eine unabhängige NGO. Sie tritt ein für ein gerechteres Steuersystem in Deutschland. Und sie wird getragen vor allem von Akteuren aus Gewerkschaften, Kirchen, anderen Nichtregierungsorganisationen, aber auch eine Reihe von Einzelpersonen aus Verwaltung und Wissenschaft. Und alle die vereint die Bemühung um das, was sie ein gerechteres Steuersystem nennen. Aber Gerechtigkeit ist natürlich immer auch was sehr Subjektives. Und wir wollen uns heute Morgen mal genauer anschauen, was heißt denn Gerechtigkeit beim Thema Steuern?

 Jana Münkel
Und dafür haben wir uns Christoph Trautvetter eingeladen. Er ist der Koordinator des Netzwerks Steuergerechtigkeit und er betreut zusätzlich dort die Themenbereiche Unternehmenssteuern, Schattenfinanzen und internationale Steuergerechtigkeit. Und wir freuen uns sehr, ihn im Interview zu haben. Herzlich willkommen in der Lage der Nation, Herr Trautvetter.

 Christoph Trautvetter
Hallo, ich freue mich, hier zu sein.

 Ulf Buermeyer
Ja, Herr Trautvetter, was verstehen Sie denn unter einem gerechten Steuersystem? Was ist Gerechtigkeit bei Steuern?

 Christoph Trautvetter
Also, das ist, wie Sie schon richtig sagten, erst mal eine subjektive Frage. Ich habe also auch da meine persönliche Meinung. Aber in unserem Jahrbuch gucken wir vor allen Dingen erst mal auf das gesamte Steuersystem. Und wir sehen Gerechtigkeitslücken, wo glaube ich aus meiner Sicht fast alle zustimmen würden, dass das noch nicht gerecht ist. Und wir sagen erstmal zumindestens diese Gerechtigkeitslücken schließen und dann gucken, wie es weitergehen kann. Ich fasse es mal ganz grob zusammen. Die meisten Menschen, die Durchschnittsverdienerfamilie in Deutschland gibt ungefähr die Hälfte von dem, was sie verdient, an Sozialabgaben und Steuern in die Gemeinschaftskasse. Ähnlich sieht es beim sogenannten Reichensteuersatz aus. Der liegt mit Soli bei ungefähr 47 %. Also das ist das, was wir im Prinzip auch von den, von den Reichen, von den stärksten Schultern im Prinzip als Beitrag erwarten. Aber einige superreiche Milliardäre, die zahlen deutlich weniger, auch die großen Konzerne, die profitabelsten Konzerne zahlen deutlich weniger. Ein Milliardär, den wir uns angeguckt haben zahlt 25 %, ein Immobilienmilliardär sogar nur 17 %. Und die großen Digitalkonzerne aus den USA und aus dem Ausland, die zahlen auf ihre in Deutschland erwirtschafteten Gewinne nur 3 %, sind also weit, weit weg von dem, was wir eigentlich von ihnen erwarten, von dem, was der durchschnittliche Unternehmer zahlt, von dem, was die Durchschnittsverdienerfamilie zur Gemeinschaftskasse gibt. Und das ist erst mal, glaube ich, ganz allgemein ungerecht. Weit entfernt von dem, worauf wir uns eigentlich gesellschaftlich bisher schon geeinigt haben. Und deswegen kann man, glaube ich, erst mal die persönlichen Meinungen zur Gerechtigkeit sogar noch zurückstellen und erst mal sagen, wir sollten zumindest das, worauf wir uns schon geeinigt haben, erst mal umsetzen.

 Ulf Buermeyer
Also Sie würden davon ausgehen, dass es so eine Art gesellschaftlichen Konsens gibt, dass zumindest mal alle gleich belastet werden sollten. Oder gibt es sogar nach Ihren Vorstellungen so was wie Einigkeit darüber, dass stärkere Schultern auch tatsächlich stärker belastet werden können?

 Christoph Trautvetter
Also das steht ja auch in unserem Grundgesetz. Im Prinzip also das Leistungsfähigkeitsprinzip bei der Besteuerung, das gilt in Deutschland, dass eben starke Schultern mehr tragen sollen als schwache. Und wir haben eine progressive Einkommenssteuer, also einen steigenden Steuersatz mit steigendem Einkommen, der in der Theorie auch so funktioniert, dass Menschen mit höheren Einkommen eben höhere Steuersätze und höhere Anteile von ihrem Einkommen auch zur Gemeinschaftskasse beitragen. Aber von dieser eigentlich progressiven Einkommenssteuer gibt es eben große Ausnahmen, die in den letzten Jahrzehnten eingeführt worden. Also das sah vor 30 Jahren noch ganz anders aus. Da haben die Milliardäre, die wir uns angeguckt haben, noch 60 % Steuern gezahlt. Sie haben es aber geschafft, in den letzten 30 Jahren ihren Steuersatz auf 25 % zu senken und eben damit weit von dem, worauf wir uns eigentlich gemeinschaftlich, glaube ich, nach wie vor verständigt haben und dem, was auch in unserem Grundgesetz steht, dass starke Schultern mehr tragen sollen als schwache.

 Jana Münkel
Jetzt haben Sie, Herr Trautvetter, so ein paar Baustellen schon genannt. Also ich habe mir da die Digitalunternehmen gemerkt und die Milliardäre, die eben unverhältnismäßig wenig zahlen aus Ihrer Sicht. Was sind denn noch wichtige Baustellen, wenn Sie das Steuersystem anschauen? Also wo muss da auch noch aus Ihrer Sicht rumgewerkelt werden?

 Christoph Trautvetter
Also die Dinge hängen ja eng zusammen. Die Milliardäre sind oft auch Eigentümer von großen Konzernen. Die zahlen also die Unternehmenssteuer auf die Unternehmensgewinne und dann meistens auch nichts mehr obendrauf. Dann kommt als nächstes noch dazu, dass sehr viele von den großen Vermögen mittlerweile in der zweiten, dritten, vierten, fünften oder sechsten Generation in der Familie bleiben und eben von Generation auf Generation übertragen werden. Und da gibt es in Deutschland eigentlich eine Erbschaftssteuer von bis zu 50 %. Auch da gilt, wer besonders große Vermögen erbt, zahlt besonders wenig. Wir haben uns jetzt aus der aktuellen Steuerstatistik von 2022 Zahlen angeschaut, da haben 24 Menschen zusammen 6 Milliarden Euro geschenkt bekommen und haben darauf insgesamt nur 4 % Steuern gezahlt. Also im Prinzip eine Steuerermäßigung, ein Steuererlass von 1,43 Milliarden Euro im Vergleich zu dem, was sie eigentlich hätten zahlen müssen, bekommen. Also das ist die nächste große Baustelle, die immer noch dazugehört. Und es gibt darüber hinaus noch eine ganze Reihe von Baustellen in der Steuerverwaltung, die nicht konsequent genug dafür sorgt, dass alle auch gleich besteuert werden, dass Steuerhinterziehung konsequent verfolgt wird. Wir verfolgen in Deutschland Schwarzfahrer zehnmal so hart wie Steuerhinterzieher. Das kann man so ganz grob sagen. Wir haben auch bei der Verbrauchssteuer große Ungerechtigkeiten oder Probleme aus gesundheitlicher und umweltökologischer Sicht. Privatjets und Superjachten kommen teilweise am Emissionshandel, auch an der Kerosinsteuer, vorbei und an der CO2 Abgabe, die der normale Mensch auf sein Auto zahlt. Oder die Luftverkehrssteuer, die der normale Mensch für seinen Flug bezahlt. Zucker, Gummibärchen, Fleisch aus Massentierhaltung ist steuerlich begünstigt mit dem ermäßigten Steuersatz. Sojamilch und Fleischersatz, der ökologisch sinnvoll ist, sind es nicht. Also es gibt neben den großen Vermögen, neben den Erbschaften und den sehr hohen Einkommen noch eine ganze Reihe von Baustellen. Die haben wir zusammengefasst und systematisch einmal im Überblick aufbereitet in sieben Reformvorschlägen, die zusammen dafür sorgen würden, dass es ein gerechteres und ökologisches Steuersystem am Ende auch geben könnte.

 Ulf Buermeyer
Ja, genau das wäre nämlich jetzt unsere nächste Frage gewesen. Sie haben ja eine Vielzahl von Problemen aus Ihrer Perspektive ausgemacht im geltenden Steuerrecht. Wie könnte denn eine Reform des Steuersystems in Deutschland konkret aussehen, wenn es so viele Baustellen gibt? Da muss man ja auch irgendwie priorisieren. Was wären denn aus Ihrer Sicht die ersten konkrete Schritte hin zu einem gerechteren und vielleicht auch zugleich ökologischeren Steuersystem?

 Christoph Trautvetter
Es gibt ja schon eine ganze Reihe von Reformvorschlägen, und es gibt auch einige sehr radikale Vorschläge, die zum Beispiel sagen, wir könnten das über die Sozialabgaben lösen und da irgendwie dafür sorgen, dass 100 Milliarden Euro mehr rumkommen. Wir könnten über eine hohe Vermögenssteuer 100 Milliarden Euro mehr einnehmen. Wir könnten über eine Finanztransaktionssteuer, komplett neue Steuer, 50 Milliarden einnehmen. Also, es gibt eine ganze Reihe von Vorschlägen. Wir sagen aber, eigentlich ist das Steuersystem so, wie es ist, sehr, sehr tief in der Gesellschaft verankert und bewegt sich nur in Millimeterschritten im Prinzip vorwärts. Und anstatt einer großen Reform plädieren wir für sieben kleine Nachbesserungen an verschiedenen Stellschrauben. Auch mit dem Grund, dass im Prinzip große radikale Steuerreformen auch zu großen Anpassungsreaktionen führen. Deswegen sagen wir, lieber kleine Schritte an verschiedenen Stellschrauben, dann wird es auch nicht zu großen Verzerrungen kommen. Und wir kommen am Ende eben auch zum gleichen Resultat von 75 Milliarden Euro. Und wenn wir jetzt priorisieren müssten oder wenn ich jetzt priorisieren soll, dann würde ich sagen, als nächstes steht auf jeden Fall die Erbschaftssteuer auf dem Plan. Das Bundesverfassungsgericht will sich in den nächsten Monaten noch mal damit befassen und hat auch in der Vergangenheit schon gesagt, dass der Zustand, den wir jetzt haben, verfassungswidrig ist. Also das ist die allerwichtigste und dringendste Baustelle. Bis wir eine Vermögenssteuer bekommen, wird es wahrscheinlich noch eine Weile dauern. Da ist der politische Widerstand sehr groß. Aber wir sehen gerade, dass der französische und der brasilianische Finanzminister das für diesen Sommer noch mal auf die Agenda gesetzt haben und dass es vielleicht international da erste Bewegungen gibt. Ich denke, als nächste Priorität kommt dann in meiner Liste tatsächlich die Frage der großen Konzerne, die viel, viel zu mächtig geworden sind, wo wir internationale oder auch nationale Lösungen brauchen, um dafür zu sorgen, dass die großen Digitalkonzerne hier in Deutschland mehr Steuern zahlen. Da sind sich eigentlich alle Menschen und auch alle Parteien einig, dass das so nicht weitergehen kann. Da sind wir aber immer noch weit davon entfernt. Also das wäre dann aus meiner Sicht noch der nächste Schritt und alles andere kann man dann Schritt für Schritt gucken. Also, ich glaube tatsächlich, die Mehrwertsteuerreform wäre nötig. Die fordert der Bundesrechnungshof aktuell mal wieder. Die fordert er aber auch schon seit zehn, 20 Jahren. Also da gibt es Reformbedarf. Der ist aber sehr, sehr träge. Also wie gesagt, an vielen Ecken und Enden Reformbedarf. Aber zunächst erst mal Erbschaftssteuer, dann die großen Vermögen und großen Konzerne, vielleicht auch mit dem internationalen Schwung, der da gerade herrscht und dann gucken, was man sonst alles noch im Steuersystem verbessern kann.

 Jana Münkel
Ich finde es spannend, weil sie vorher von so kleinen Projekten gesprochen haben. Das, was Sie jetzt gerade geschildert haben, klingt für mich jetzt gar nicht so klein, aber eben doch nach einem Fokus auf sehr verschiedene Baustellen. Ist da nicht die Gefahr, dass dann der Fokus auf ein wichtiges Projekt so ein bisschen verloren geht? Wenn Sie sagen, Sie wollen, das, das, das, das, also viele in Anführungszeichen kleine Baustellen, ist da dann nicht die Gefahr, dass da der Blick auf ein großes, wichtiges Reformprojekt vielleicht verstellt wird?

 Christoph Trautvetter
Also das müssen Sie vielleicht auch noch mal die Politiker fragen, und das würde ich persönlich auch Ihnen überlassen. Also das soll die Politik entscheiden. Wir liefern nur die Informationen und die Fakten zu und machen Vorschläge. Wie das dann in den in den Wahlprogrammen für die nächste Bundestagswahl oder eben in der politischen Diskussion sich wiederfindet, da gibt es andere, die dafür zuständig sind. Also das würde ich jetzt gar nicht als unsere Zuständigkeit sehen. Aber ich gebe Ihnen an zwei Stellen auf jeden Fall Recht. Das Reformpaket und auch jede einzelne dieser Reform, von der Vermögenssteuer über eine Übergewinnsteuer von großen Konzernen, das klingt tatsächlich wie ein großes Projekt, wie eine radikale Änderung schon allein für sich genommen und im Gesamtpaket von sieben Vorschlägen dann wie eine sehr, sehr große Aufgabe. Aber wenn man sich im Vergleich dazu mal die Herausforderungen anschaut, die vor uns liegen und auch einfach mal zurückblickt auf die letzten zwei Jahre Bundesregierung, wo sich gar nichts bewegt hat, die letzten 20 Jahre im Prinzip, wo sich das Steuersystem kaum mehr geändert hat, dann ist tatsächlich einfach der Reformbedarf so groß, die Herausforderungen sind so groß, dass im globalen Maßstab alle diese Reformen zusammengenommen überhaupt nicht radikal sind und eigentlich nur für eine Wiederherstellung eines Gleichgewichts sorgen. Also sie sorgen noch nicht dafür, dass die riesigen Vermögen, die sich in den letzten Jahren aufgebaut haben, irgendwie kleiner werden oder abgetragen werden, sondern diese Reformen sorgen insgesamt nur dafür, dass sie langsamer wachsen und sind deswegen alles andere als radikal. Und wir brauchen einfach in der Gesellschaft die Erkenntnis, dass dieses Update im Steuersystem ganz dringend wichtig ist.

 Ulf Buermeyer
Aber mich würde da doch noch mal so ein bisschen die Perspektive der praktischen Politik interessieren. Sie sagen, Sie liefern die Fakten zu, aber die Fakten alleine reichen ja nicht. Sie haben es eben schon angedeutet. Große Vermögen wachsen immer weiter. Und die großen Vermögen haben natürlich auch in der Ampel mit der FDP eine Partei, die sich als ihre Fürsprecherin sieht. Bleiben wir doch vielleicht mal bei der Reform der Erbschaftsteuer. Selbst Menschen, die selber gar nicht wahnsinnig reich sind, sehen ja eine Reform der Erbschaftssteuer in der Tendenz kritisch. Woher soll denn dann gesellschaftlich diese breite Bewegung kommen, um eine Reform der Erbschaftssteuer durchzusetzen, die tatsächlich die großen Vermögen nicht so wie heute weiter privilegiert, sodass sie teilweise nur ein paar Prozent an Erbschaftssteuer zahlen. Wie sehen Sie da konkret die politische Vision, dass da eine gesellschaftliche Mehrheit entstehen könnte?

 Christoph Trautvetter
Also ich muss Sie da, glaube ich, leider noch mal enttäuschen. Diese Frage kann ich erst mal nur mit Fakten beantworten. Also wenn man sich die Vorschläge noch mal anguckt, dann geht es bei den Ausnahmen von der Erbschaftssteuer, über die wir reden, ungefähr um 300 Menschen jedes Jahr, die davon profitieren, also wirklich um einen ganz, ganz, ganz kleinen Teil der Bevölkerung. Der allergrößte Teil, 70 % der Menschen, die erben gar nichts nennenswertes und sind überhaupt nicht betroffen. Und selbst die anderen 30 %, die zahlen im Prinzip jetzt schon die Erbschaftssteuer oder werden ausgenommen. Es geht tatsächlich nur um 300 Menschen, also null Komma irgendwas Prozent der Bevölkerung, die von so einer Reform überhaupt betroffen wären. Das gleiche ist bei der Vermögenssteuer auf Milliardenvermögen, über die wir sprechen. Da geht es um 200 Vermögen und nicht um das Haus vom Arzt. Und bei den Übergewinnen geht es um 200 große Konzerne. Also es sind tatsächlich sehr, sehr wenige riesengroße Vermögen, riesengroße Konzerne und Erbschaften betroffen. Und trotzdem ist die politische Herausforderung, die Mehrheit der Bevölkerung erst mal darüber zu informieren und davon zu überzeugen, dass es im Sinne der demokratischen Mehrheit wäre, eben da für eine gerechte Besteuerung zu sorgen. Die ist riesig. Ich finde das aus meiner Perspektive einfach nur faszinierend, wie das passieren kann, dass also eine Demokratie, die eigentlich eine Mehrheitsentscheidung beinhaltet, es nicht schafft, die 2 Millionen Unternehmer, die 45 %, 48 % Steuern zahlen, zu mobilisieren, dafür zu sorgen, dass die 200 Großkonzerne das auch tun. Und eine Politik, die es nicht schafft, die vielen Durchschnittsverdiener und die Normalverdiener, die eben die Hälfte von ihrem Einkommen abgeben müssen, da zu mobilisieren, zu sagen, dass die Milliardäre, die 200 Milliardenvermögen, das Gleiche tun. Das ist für mich tatsächlich auch genauso ein Rätsel wie für Sie. Und ich kann nur antworten, mehr als dran glauben, dass die Demokratie in irgendeiner Form funktioniert, dass wir eine demokratische Debatte über diese Probleme hinbekommen, wenn die Leute sehen, wie ungerecht es ist. Mehr Antworten kann ich da leider auch nicht liefern. Und diese demokratische Debatte, die müssen unsere gewählten Politiker oder die Parteien irgendwie organisieren.

 Jana Münkel
Jetzt haben wir über vieles gesprochen, was nicht so gut läuft und was sich aus Ihrer Sicht ändern sollte. Jetzt haben Sie aber im Jahrbuch Steuergerechtigkeit auch ein paar Sachen angesprochen, die die Ampel aus Ihrer Sicht nicht so verkehrt macht. Was läuft denn aus Ihrer Sicht eigentlich schon ganz gut beim Thema Steuergerechtigkeit?

 Christoph Trautvetter
Da kann ich Ihnen zwei Antworten geben. Einmal aus Sicht des Koalitionsvertrags, also aus dem Minimalkompromiss. Muss man ja so sagen. Also, die Koalitionäre sind mit ganz, ganz unterschiedlichen Positionen aus ihren Wahlprogrammen in den Koalitionsvertrag, in die Koalitionsverhandlungen gestartet. Und da ist ein Nichtangriffspakt im Prinzip herausgekommen, wo weder große Steuererhöhungen noch große Steuersenkungen drinne stehen und vor allen Dingen technische Verbesserungen aufgelistet sind. Von diesen technischen Verbesserungen im Koalitionsvertrag ist zur Halbzeit ungefähr die Hälfte abgearbeitet, also die Homeoffice Pauschale wurde angepasst, die Rentenbesteuerung wurde reformiert, die globale Mindeststeuer umgesetzt, CO2 Preise, Luftverkehrssteuer, LKW Maut. Also es sind eine ganze Reihe an Dingen passiert, die im Koalitionsvertrag drinstehen, die aber aus Gerechtigkeitssicht keine, keine Änderung bringen. Die spannendsten Fortschritte gab es aus unserer Sicht im Bereich der Geldwäschebekämpfung und im Bereich der Bekämpfung von Finanzkriminalität. Da gibt es aktuell einen sehr, sehr umfassenden Gesetzesentwurf, der im Bundestag liegt, das Finanzkriminalitätsbekämpfungsgesetz. Und da wird jetzt aktiv gerade darum gestritten, ob die Koalition sich irgendwie einigen kann, tatsächlich verdächtige Vermögen, anonyme Briefkästen noch in dieser Regierungszeit effektiv zu bekämpfen. Also das ist gerade ganz aktuell noch spannend. Das wäre ein tatsächlich großer Wurf. Den hat der Finanzminister Lindner auch angekündigt. Also dass wir da Reformen erwarten können, die endlich auch dafür sorgen, dass die großen Fische, die großen Finanzkriminellen, gefangen werden. Das ist aus meiner Sicht die größte und spannendste Reform. Und auf diesem Weg gegen die anonymen Briefkästen, da gab es eine aus meiner Sicht spektakuläre Reform, ich würde es einen Geniestreich nennen. Das ist also im Rahmen der Diskussion um die russischen Sanktionen im letzten Jahr gelungen. Nachdem wir 20 Jahre im Prinzip darum gerungen haben, gibt es jetzt seit Juli 2023 ein zentrales Immobilienregister, also einen Ort, wo die Information über alle Immobilieneigentümer Deutschlands gesammelt ist und wo jetzt 100 Menschen daran arbeiten, diese Information über die Immobilieneigentümer mit dem Transparenzregister zu verknüpfen und die Daten aufzuräumen und die Polizei und die Behörden im Prinzip in die Lage zu versetzen, zu wissen, wem die Immobilien in Deutschland gehören. Das ist, wie gesagt, ein Riesenfortschritt. Da bleiben noch ganz viele Lücken im Transparenzregister übrig. Große Fragezeichen. Und die sollen hoffentlich, wenn sich der Bundestag da jetzt darauf einigt und die Koalition sich darauf einigt, dann von professionellen Ermittlern geschlossen werden, die anonyme Vermögensstrukturen aufdecken und abstellen.

 Ulf Buermeyer
Ja, da sind wir mal gespannt, ob das tatsächlich so durch den Bundestag und durch den Bundesrat gehen wird. Aber für heute erst einmal ganz herzlichen Dank an Christoph Trautvetter vom Netzwerk Steuergerechtigkeit.

 Christoph Trautvetter
Ich bedanke mich.

 Jana Münkel
Und wir kommen vom Thema Steuergerechtigkeit zu einem ganz anderen Thema, aber auch ein innenpolitisches. Vielleicht ist das der Link, der ganz gut passt. Es geht ums Thema Clan-Kriminalität und ich habe da jetzt eine Pause vor dem Wort gemacht, weil ich dieses Wort Clan-Kriminalität in Anführungszeichen setzen möchte, weil das wird jetzt unser Thema. Ist dieses Wort, ist dieser Begriff ein angemessener, um ein Phänomen kriminologischer Art zu beschreiben? Es gab Ende Februar in Deutschland, Spanien und Polen Razzien wegen des Verdachts auf Veruntreuung und Geldwäsche. Und Niedersachsens Innenministerin Daniela Behrens, die hat diese Polizeiaktion als Ermittlungserfolg gegen die, und da ist er wieder der Begriff, Clan-Kkriminalität bezeichnet. In der Mitteilung hat sie erklärt:

 Ulf Buermeyer
"Diese hochkriminellen Gruppierungen zeichnen sich durch eine enorme Kreativität und Anpassungsfähigkeit an sich ändernde Rahmenbedingungen aus."

 Jana Münkel
Dabei stellt neue Forschung eigentlich komplett in Frage, ob dieser Begriff der Clan-Kriminalität überhaupt geeignet ist, um eine bestimmte Form von Kriminalität trennscharf beschreiben zu können.

 Ulf Buermeyer
Ja, es fehle an einer wissenschaftlichen Grundlage des Begriffs, ist das Fazit eines neuen wissenschaftlichen Sammelbandes, entstanden im Rahmen des Verbundprojekts Kriminalität großfamiliär begründeter Strukturen, kurz KONTEST, gefördert vom Bundesministerium für Bildung und Forschung. Aber ungeachtet dieser wissenschaftlichen Fragezeichen hat der Begriff ja gerade politisch einige Konjunktur. Und nun stellt sich raus, dass der Begriff möglicherweise völlig ungeeignet ist. Wir wollten das genauer wissen.

 Jana Münkel
Genau. Und dazu fragen wir eine Kriminologin, die sich seit vielen Jahren mit diesem Begriff befasst und zur sogenannten Clan-Kriminalität forscht. Ich sag Herzlich Willkommen in der Lage der Nation Laila Abdul-Rahman von der Universität in Frankfurt am Main.

 Laila Abdul-Rahman
Ja, Guten Tag. Hallo.

 Ulf Buermeyer
Ja. Laila Abdul-Rahman forscht an der Goethe-Universität Frankfurt am Main mit dem Schwerpunkt Polizeiforschung. Am Lehrstuhl von Professor Dr. Tobias Singelnstein, der ja auch schon öfter in der Lage der Nation zu Gast war. Sie ist Mitautorin des Buchs "Generalverdacht, wie mit dem Mythos Clan-Kriminalität Politik gemacht wird", das im vergangenen Oktober erschienen ist. Und sie wollte diesen Begriff erst mal auf eine wissenschaftliche Grundlage stellen. Und sie war dann überrascht, wie dünn genau diese wissenschaftliche Grundlage war. Frau Abdul-Rahman, wir müssen erst mal kurz auf diesen Begriff selbst schauen. Was soll denn der Begriff in Anführungsstrichen Clan-Kriminalität überhaupt genau beschreiben?

 Laila Abdul-Rahman
Also der Begriff Clan-Kriminalität, der ist sehr, sehr weit definiert. Letztendlich fällt darunter wirklich jegliches delinquente Verhalten von Personen, die eben von der Polizei als sogenannte Clanangehörige definiert werden. Das heißt, anders als es, glaube ich, in der öffentlichen Wahrnehmung sehr häufig wahrgenommen wird, fällt darunter nicht nur schwere organisierte Kriminalität, sondern eben auch ein ganz großer Teil an Allgemeinkriminalität. Das heißt alle möglichen Formen auch leichter Straftaten und sogar auch Ordnungswidrigkeiten, also selbst Verkehrsverstöße, Falschparken, ja alles im ordnungswidrigen Bereich werden eben polizeilich registriert, wenn sie sogenannten Clanangehörigen zugeordnet werden.

 Ulf Buermeyer
Das heißt also, es geht letztlich gar nicht um die Art von Kriminalität, sondern Kriminalität fällt in diesen Topf Clan-Kriminalität allein deswegen, weil bestimmte Menschen sich strafbar oder auch nur ordnungswidrig verhalten?

 Laila Abdul-Rahman
Genau. Und das ist letztlich auch die zentrale Kritik an dem Begriff. Es ist letztendlich personenbezogen und am Ende wird letztendlich Kriminalität auch kollektiviert und sozusagen ganzen Familien zugeschrieben. Und das ist natürlich dann erst mal fraglich und begründungsbedürftig, weil wir dann natürlich auch ein großes Diskriminierungspotential haben. Also es werden auch nur ganz bestimmte Familien und Menschen mit bestimmten Herkünften hier noch mal gesondert registriert. In der Definition selbst wird jetzt keine bestimmte Herkunft mehr adressiert, aber in den polizeilichen Lagebildern steht wortwörtlich drin, dass der polizeiliche Fokus eben nur auf bestimmten Familien liegt, nämlich arabischstämmigen, türkischstämmigen oder auch kurdischstämmigen Familien, die eben insbesondere damals nach dem Libanonkrieg nach Deutschland gekommen sind.

 Jana Münkel
Sie haben jetzt diese Lagebilder schon angesprochen. Die Polizei arbeitet ja damit um, korrigieren Sie mich, wenn ich das falsch erkläre, aber um sozusagen so ein Verdachtsmoment oder einen Fokus ihrer Arbeit festzulegen. Das heißt, wenn in diesen Lagebildern das Wort Clan-Kriminalität vorkommt, ist dann auch der Fokus auf bestimmte Familien mit bestimmten Namen gerichtet, richtig?

 Laila Abdul-Rahman
Ja, das ist korrekt. Es ist von Bundesland zu Bundesland so ein bisschen unterschiedlich. Aber beispielsweise in Nordrhein-Westfalen wird es tatsächlich so gehandhabt, dass Listen mit bestimmten Nachnamen existieren, die dann eben diese Clanzugehörigkeit definieren. In Berlin wird es ein bisschen anders gemacht mit sogenannten ermittlungsstützenden Hinweisen, wo dann die Polizei im Einzelfall prüft, um was für Familienangehörige es sich eben handelt. Aber am Ende des Tages ist die Bezugsgröße immer die Abstammung. Und das ist natürlich die Kritik auch daran, dass wir hier eigentlich, wenn wir es genauer betrachten, eine institutionalisierte Form einer rassistischen Ungleichbehandlung haben und es doch sehr erklärungsbedürftig ist, warum über bestimmte Bevölkerungsgruppen eigene polizeiliche Statistiken geführt werden. Vor allen Dingen, wenn wir uns auch bewusst machen, dass wir zum Beispiel in der Diskussion um Racial Profiling, ja, da wird ja immer wieder gefordert, wir bräuchten eine bessere statistische Erfassung, wer eigentlich von polizeilichen Kontrollen erfasst wird. Und da wird aber immer wieder auch angeführt, dass wir in Deutschland aufgrund unserer Geschichte, aufgrund unserer Historie eigentlich keine intensivierte polizeiliche Erfassung haben wollen. Also da wird dann eben gesagt, wir können die Herkunft, die Ethnie nicht erfassen, wir sollten das nicht tun. Aber hier in diesem Fall, im Fall der Clan-Kriminalität, wird das eigentlich schon die ganze Zeit gemacht.

 Ulf Buermeyer
Aber um vielleicht die Bedeutung dieses, dieses problematischen Begriffs besser einschätzen zu können, was sagen denn da eigentlich die Zahlen? Also welche Bedeutung nimmt denn diese Zuschreibung von sogenannter Clan-Kriminalität in der polizeilichen Beschreibung von Kriminalität eigentlich ein?

 Laila Abdul-Rahman
Ja, also die Bedeutung des Phänomens muss man natürlich einerseits wieder einordnen. Es ist eben, ich würde sagen, zum Teil eine überschätzte Bedrohungslage, weil wir ja auch diese Ordnungswidrigkeiten und kleineren Delikte mit drin haben. Aber selbst wenn wir jetzt alles zusammennehmen, zum Beispiel waren im Jahr 2022 in der Berliner Polizeilichen Kriminalstatistik 872 Straftaten sogenannten Clanangehörigen zugeordnet. Und das klingt vielleicht erst mal viel, aber wenn wir das dann in einem Gesamtverhältnis sehen, sind es eigentlich nur 0,2 % der Gesamtkriminalität in Berlin. Und das ist in anderen Bundesländern ähnlich. Außerdem auch sind das Hellfelddaten. Das bedeutet, wir wissen auch gar nicht, ob jetzt diese Fälle am Ende tatsächlich zu einer Verurteilung geführt haben oder vielleicht auch zu einem Freispruch, zu einer Einstellung, aber auch so insgesamt jetzt vielleicht nicht der große Teil, den man vermuten könnte. Außerdem, wenn man es noch mal ins Verhältnis zur organisierten Kriminalität setzen möchte, dann machen nur insgesamt 7 % aller Ermittlungsverfahren wegen organisierter Kriminalität sind eben Verfahren wegen Clan-Kriminalität. Also auch hier ist es auch nicht der größte Teil, also bei weitem nicht, sondern auch nur ein geringer Teil an organisierter Kriminalität in Deutschland tatsächlich Clan-Kriminalität.

 Jana Münkel
Wenn Sie jetzt sagen, dieser Begriff Clan-Kriminalität ist nicht passend und nicht trennscharf, gibt es einen Begriff, der aus Ihrer Sicht besser passen würde?

 Laila Abdul-Rahman
Also ich würde sagen, dass es letztlich nicht nur um den Begriff geht, sondern wir müssen uns eben fragen, was wird hier eigentlich erfasst mit diesem Begriff? Und müssen wir nicht auch was an der polizeilichen Praxis ändern? Und grundsätzlich glaube ich, dass es ja schon Konzepte gibt, die beispielsweise auf die organisierte Kriminalität angewendet werden können, wenn in diesem Bereich auch Familiennetzwerke eine Rolle spielen, dann ist es der Polizei natürlich unbenommen, diese auch aufzuklären. Aber in den ganzen anderen Bereichen sehe ich eigentlich keine Notwendigkeit, hier eigene Statistiken zu führen. Und das zweite wäre eben auch, es sind so Begriffe in der Diskussion wie familienbasierte Kriminalität usw. Wenn es darum aber geht, warum das dann aber nur für Menschen mit einer bestimmten Herkunftsgeschichte gelten soll? Weil, wie ich anfangs schon gesagt habe, in den Lagebildern steht ausdrücklich drin, es geht nur um diese arabischstämmigen oder auch kurdischstämmigen Familien. Und wenn sich eben eine deutsche oder deutsch gelesene Familie in der gleichen Art und Weise verhalten würde, dann wäre sie auch nicht in dieser Statistik drin. Und dementsprechend würde ich dafür plädieren, wenn wir von familienbasierter Kriminalität sprechen, dann muss das aber auch für alle Menschen in einer gleichen Weise gelten und kann dann eben nicht nur in der Praxis am Ende doch wieder für nur bestimmte Gruppen gelten.

 Ulf Buermeyer
Also wenn man das jetzt mal zuspitzt, gibt es dann überhaupt das Bedürfnis nach einem Nachfolgebegriff, der dann hoffentlich nicht diskriminierend, nicht rassistisch wäre? Oder reicht nicht eigentlich der Begriff der organisierten Kriminalität, weil der ja jedenfalls im Ansatz ethnisch neutral ist?

 Laila Abdul-Rahman
Also ich persönlich würde das so sehen. Es gibt natürlich viele, gerade aus der polizeilichen Praxis, die das anders sehen, aber aus meiner Sicht wäre das wahrscheinlich das, wo man dann wieder hin müsste, dass man wirklich einmal grundsätzlich hinterfragt, ja, was wir hier eigentlich tun wollen. Und auch wenn es dann darum geht, wie wir eigentlich auf diese Formen der Kriminalität reagieren und dann ist es glaube ich, eher angezeigt, da wirklich zu differenzieren und gerade auch schwere von leichter Kriminalität zu unterscheiden, um da überhaupt auch, ja sage ich mal, evidenzbasiert voranzukommen.

 Ulf Buermeyer
Vielleicht dann eine Nachfrage dazu, wenn sie sagen, Praktiker:innen aus der Polizei sehen da ein Bedürfnis, was soll denn dann noch beschrieben werden? Also was bleibt denn quasi, was unter dem Begriff der OK, der organisierten Kriminalität nicht zu beschreiben ist?

 Laila Abdul-Rahman
Ja, das ist natürlich eine Frage, die man wahrscheinlich eher an die an die Polizei richten muss. Wir sehen eben das an diesen großen Einsätzen, diesen großen Razzien, die da zum Teil gemacht werden, das sind ja zum Teil auch sogenannte Verbundseinsätze. Das heißt, die Polizei ist da eigentlich gar nicht federführend, sondern ist in Amtshilfefunktion, zum Beispiel für die Ordnungsämter. Dann werden dann in großem Maße Gewerbekontrollen durchgeführt, zum Beispiel von Cafes, Bäckereien, Shisha Bars sind da sehr stark im Fokus. Und da geht es eigentlich gar nicht um erst mal vordergründig um eine strafprozessuale Maßnahme, sondern über diese Verbundseinsätze sollen eigentlich Erkenntnisse generiert werden über organisierte Kriminalitätsstrukturen. Aber auch da ist so ein bisschen fraglich, wie effektiv und effizient die Maßnahmen eigentlich sind, weil wir eben aus Berichten wissen, es wird überwiegend dann doch zum Beispiel unversteuerte Shisha Tabak gefunden. Und auch eine Analyse des LKA Berlins hat ergeben, dass es zum Teil eher Zufallsfunde sind, die dann noch über organisierte Strukturen gefunden werden. Und ich glaube, es ist natürlich ein hilfreiches Mittel, wenn ich, sage ich mal, sehr breit kontrollieren kann in bestimmten Bereichen und erhoffe mir dann Erkenntnisse über bestimmte Netzwerke. Aber diese wahnsinnig große Streubreite, die ist eben sehr problematisch, weil hier wirklich eine ganze Reihe an Personen und da dann eben auch nicht nur Familienangehörige, sondern auch Menschen, die eben in diesem bestimmten Vierteln leben, die dort ihr Gewerbe betreiben, die werden eben kriminalisiert. Und daher rührt ja auch der Widerstand. Also die Kritik kam jetzt auch gar nicht vorrangig aus der Wissenschaft, sondern man muss das ganz klar sagen, die Kritik kommt von den Betroffenen selbst oder von Menschen, die beispielsweise in Neukölln leben oder auch in Nordrhein-Westfalen in den einschlägigen Städten leben, die sich hier eben tagtäglich schon fast von solchen Einsätzen eben kriminalisiert sehen und da ja auch ihrem Alltagsgeschäft sozusagen nicht mehr nachgehen können.

 Jana Münkel
Frau Abdul-Rahman, Sie haben in Ihrer Forschung auch Anhaltspunkte dafür gefunden, dass eben nicht nur Beschwerden von den Menschen, die dort leben, selber kommen, sondern dass die Verwendung des Begriffs der Clan-Kriminalität auch Folgen haben kann für die Präventionsarbeit, wenn es um Kriminalität geht. Welche denn?

 Laila Abdul-Rahman
Ja, also im Zusammenhang mit Clan-Kriminalität wird ja immer wieder die sogenannte Zero Tolerance Strategie diskutiert oder auch dass eben sehr, sehr hart vorgegangen wird, dass quasi keinerlei Toleranz mehr gegenüber diesen Familien herrschen soll. Und das ist natürlich ein großes Problem, wenn man eigentlich Präventionsarbeit machen will, die dann wiederum auf Vertrauen und Vertrauensaufbau beruhen muss. Und da gibt es eben auch Forschung zu, die mit Menschen aus der sozialen Arbeit gesprochen haben, die eben sagen, diese Diskriminierung, diese Stigmatisierung, die führt eben immer mehr dazu, dass Vertrauen verloren geht und man dadurch eigentlich auch keine soziale Arbeit mehr machen muss. Also ein Beispiel, wenn solche Familien, die ja selbst auch auf eine jahrzehntelange Entrechtungsgeschichte zurückblicken, na also, hier waren sie sehr lange von gesellschaftlicher Teilhabe ausgeschlossen, weil es sogenannte Kettenduldungen gab, die Zugang zum Arbeitsmarkt verweigerten usw. Und wenn, dann vor diesem Hintergrund auch Politiker fordern beispielsweise, dass Familien die Kinder weggenommen werden. Das sind ja immer so die Schlagzeilen, dass aus diesen Familien quasi die Kinder rausgeholt werden müssen, damit sie nicht auch kriminell werden usw., dann ist eben eigentlich gar keine vertrauensvolle Sozialarbeit mehr möglich, sowohl für die Familien als auch für die Jugendlichen, die sich dann eben auch das als Jugendliche, als Clanjugendliche Clankinder stigmatisiert werden. Wir haben da Berichte über Kinder, die schon in der Grundschule so bezeichnet werden und das produziert natürlich Ausschlüsse, gesellschaftliche Ausschlüsse und Diskriminierungen sozusagen am laufenden Band. Und dann wird es auch immer schwieriger, tatsächlich Personen zu erreichen, die möglicherweise wirklich Unterstützung brauchen und die vielleicht auch ein Risiko haben, sonst eben nicht mehr an der Gesellschaft teilhaben zu können.

 Ulf Buermeyer
Ja, ganz herzlichen Dank. Laila Abdul-Rahman. Sie sagt im Interview mit der Lage der Nation, der Begriff der Clan-Kriminalität ist wissenschaftlich unscharf, er ist eigentlich überflüssig, und er behindert die Integration und die Prävention von Kriminalität. Ganz herzlichen Dank für Ihre Zeit und für dieses Interview.

 Laila Abdul-Rahman
Ja, vielen Dank für das Gespräch.

 Jana Münkel
Wir springen geografisch jetzt in den Südosten von Thüringen, und zwar in den Saale-Orla-Kreis. Da spielt unser nächstes Thema oder zumindest der Aufhänger für unser nächstes Thema. Der Saale-Orla-Kreis war in den letzten Tagen ziemlich groß in den Medien, weil Asylsuchende dort verpflichtet werden, gemeinnützige Arbeit zu verrichten. Also da geht es zum Beispiel um so was wie Laubhaken rund um ihre Unterkunft.

 Ulf Buermeyer
Und sie sollen dafür 0,80 € pro Stunde bekommen. Es ist also nur ein Bruchteil dessen, was man sonst als Mindestlohn verdient in Deutschland. Wer sich weigert, diese Arbeiten zu verrichten, dem sollen die Sozialleistungen gekürzt werden. Zunächst einmal muss man sehen, juristisch ist das im Prinzip gestattet. Rechtsgrundlage ist schon seit den 90er Jahren, seit 1993 Paragraph fünf des Asylbewerberleistungsgesetz, der da sagt:

 Jana Münkel
"Im Übrigen sollen so weit wie möglich Arbeitsgelegenheiten bei staatlichen, bei kommunalen und bei gemeinnützigen Trägern zur Verfügung gestellt werden, wenn das Arbeitsergebnis der Allgemeinheit dient."

 Ulf Buermeyer
Juristisch also ist das durchaus machbar, wenngleich die Rechtsgrundlage dafür natürlich aus ganz anderen Zeiten stammt, nämlich als wir in Deutschland eine relativ hohe Arbeitslosigkeit hatten. Ganz anders als heute, wo ja Arbeitskräftemangel herrscht. Ja, aber grundsätzlich ja, kann man natürlich sagen, klingt das erst mal sinnvoll. Warum sollen Geflüchtete sich nicht nützlich machen?

 Jana Münkel
Und der CDU Landrat im Saale-Orla-Kreis der heißt Christian Herrgott, der argumentiert im Deutschlandfunk auch so ähnlich.

 Christian Herrgott
Wir möchten diejenigen, die zu uns kommen und die ja mindestens in den ersten drei Monaten nicht arbeiten dürfen nach den Gesetzlichkeit sofort abholen und auch in eine Tagesstruktur und eine sinnvolle Tätigkeit bringen und danach die Möglichkeiten schaffen, dass sie auch zügig, wenn es rechtlich möglich ist, in den ersten Arbeitsmarkt integriert werden. Denn jeder, der nicht von Sozialleistungen leben muss sondern sein Leben selbst bestimmen kann, ist für uns und aus unserer Sicht ein großer Vorteil.

 Jana Münkel
Also ich bringe es noch mal auf den Punkt. Er sagt, es ist besser, wenn jemand nicht rumsitzt und ein bisschen Arbeit macht, egal welcher Art diese Arbeit auch ist. Und aus seiner Sicht dient das wirklich der Integration in den Arbeitsmarkt. Jetzt finde ich, kann man aber oder muss man trotzdem fragen, dient diese gemeinnützige Arbeit wirklich der Integration in den Arbeitsmarkt?

 Ulf Buermeyer
Ja, ich bin da auch so ein bisschen skeptisch, denn das ist ja eben gerade kein Arbeitsmarkt im engeren Sinne, sondern das ist eben dann, keine Ahnung, der Betreiber des Asylbewerberheims, bei dem man da arbeitet. Und man verdient natürlich auch bestenfalls ein Taschengeld. Wenn man drei Stunden arbeitet, hat man 2,40 € in der Tasche. Das reicht kaum für ein Eis. Also das ist sehr die Frage, inwieweit das tatsächlich zu mehr Autonomie führt. Es spart jedenfalls auch keine Leistung, wenn man natürlich, wenn man so extrem wenig den Menschen bezahlt, dann auch nicht weniger an Sozialleistungen zahlen kann. Und ich weiß auch nicht, ob es dem Spracherwerb so dient, wenn man dann eben in der Unterkunft und eben ohne deutschsprachige Kollegen arbeitet oder Kolleginnen. Also ich glaube, das mit der Integration, das ist ehrlich gesagt, sagen wir mal vorsichtig, eine Hoffnung. Aber ob die sich so erfüllen wird? Ich finde aber noch viel spannender die Frage, warum muss man denn die Menschen überhaupt zwangsweise zur Arbeit bringen, wenn man sie doch auf der anderen Seite nicht arbeiten lässt?

 Jana Münkel
Genau das ist nämlich das, wie ich finde, Absurde. In den ersten Jahren haben Geflüchtete oft ja ein de facto Arbeitsverbot. Also wir haben gerade schon gehört, Christian Herrgott hat das auch gesagt. In den ersten drei Monaten sind sie vollständig ausgeschlossen vom Arbeitsmarkt. Und selbst danach brauchen sie eine Genehmigung vom Amt, die oft einfach nicht so leicht zu kriegen ist. Das dauert oft ewig, die kommt teilweise auch gar nicht. Und wenn Ämter überlastet sind, muss man es sozusagen gar nicht probieren. Du hast da ein paar Beispiele auf Lager, oder?

 Ulf Buermeyer
Ja, das war vor einiger Zeit mal ausführlich, ich glaube in der Süddeutschen Zeitung Thema. Die haben sich mal die katastrophale Situation der Stuttgarter Ausländerbehörde angeschaut. Da müssen irgendwie bundesweit Menschen eine Erlaubnis beantragen, wenn sie arbeiten wollen. Und sie müssen sogar eine Erlaubnis beantragen, wenn sie einfach nur eine Arbeit über ein paar Monate hinaus fortsetzen wollen. Und das führt dazu, dass teilweise Menschen, die längst zum Beispiel als Krankenschwester arbeiten, ihre Arbeit aufgeben müssen, obwohl, wie man weiß, in einigen Kliniken Arbeitskräftemangel herrscht. Einfach deswegen, weil sie keinen Termin in der Ausländerbehörde bekommen. Und in Berlin ist natürlich die Behörde auch im Zweifel überlastet. Also, ich finde das so problematisch, wenn man immer so tut, Menschen wollten nicht arbeiten. In der Praxis ist es einfach so, dass wir den Menschen reichlich Steine in den Weg legen. Es stimmt einfach nicht zu sagen, die wollen alle nicht, sondern die allermeisten Geflüchteten, bis sie anerkannt sind mal irgendwann, dürfen schlicht und ergreifend nicht arbeiten.

 Jana Münkel
Und ich finde, da kommt ja noch ein Aspekt dazu, wenn man sagt, ja, wir müssen jetzt Geflüchtete zu gemeinnütziger Arbeit verpflichten, das sendet ja auch so ein Signal, das eigentlich befeuert, dass Menschen, die hierherkommen, eigentlich nur rumsitzen oder rumliegen wollen und dass man diesen Schritt gehen muss, sagen muss, wir verpflichten euch jetzt zur Arbeit. Also da gab es auf Instagram eine Äußerung von Orkan Özdemir von der SPD, Der ist Mitglied des Berliner Abgeordnetenhauses.

 Ulf Buermeyer
Und der schrieb: "bevor man sie zwingt, für 0,80 € gemeinnützige Arbeit zu leisten, sollte man Geflüchteten erlauben zu arbeiten. Es ist absurd. Geflüchtete haben in den ersten Jahren selten eine Arbeitserlaubnis. Und dann wird suggeriert, sie würden nicht arbeiten wollen, sie seien faul, man müsste sie zwingen. Geflüchtete wollen arbeiten, Geflüchtete wollen sich ein selbstbestimmtes Leben aufbauen. Was für eine absurde und ekelhafte Diskussion. Dieser Ekeldiskurs wird nur von dieser quasi Sklaverei überboten. Das sind meine zwei Cent zur Sache."

 Jana Münkel
Klare Worte. Ich habe noch eine andere Aussage gefunden von der Thüringer Integrationsbeauftragten. Die heißt Mirjam Kruppa und die hat ihre Ablehnung dieses Vorschlags so begründet.

 Mirjam Kruppa
Es ist wirklich so, dass es eine gewisse populistische Wirkung hat zu sagen, die Menschen wollen nicht arbeiten, die sitzen rum und tun nichts. Und das halte ich für wirklich gefährlich, dass man ständig suggeriert, hier sind Menschen, die nicht wollen. Und das stimmt nicht. Man findet in den Gemeinschaftsunterkünften, in den Erstaufnahme viele Freiwillige, die das tun, auch für so wenig Geld.

 Jana Münkel
Das heißt, es funktioniert ja schon. Also wenn man ganz konkret auf Thüringen guckt, gibt es ganz viele Menschen, die wollen auch diese Freiwilligenarbeit verrichten. Das bedeutet, dieser Zwang dahinter ist eigentlich auch auf dieser Ebene gar nicht nötig.

 Ulf Buermeyer
Stellt sich natürlich die Frage, was würde besser funktionieren? Im Grunde ist es schon angeklungen in allen Statements, die wir jetzt hatten, wie wär's denn, wenn wir die Menschen einfach mal arbeiten lassen auf dem ganz normalen Arbeitsmarkt, wo es ja genügend Bedarf gibt anstatt mit der Peitsche zu drohen? Im Ansatz hat auch das Bundeskabinett das Problem erkannt. Es hat im November nämlich schon beschlossen, Arbeitsverbote lockern zu wollen. Unter anderem ist der Plan, dass Ausländerbehörden die Zustimmung zur Beschäftigung künftig im Regelfall erteilen sollen, auch bei geduldeten Ausländern. Bisher ist dies wohl nur eine Kannregelung, die im Ermessen der Behörde liegt. Das aber würde jedenfalls nach dem, was wir so in den letzten Monaten in verschiedenen Hintergrundgesprächen eben mit Menschen gehört haben, die zum Beispiel selber versuchen, Geflüchtete einzustellen oder die die als Anwältin vertreten. Das würde an dem eigentlichen Problem nicht so wahnsinnig viel ändern.

 Jana Münkel
Weil selbst wenn es eine Regelung gibt, dass alle eine Genehmigung bekommen, müssen sie sich diese Genehmigung ja trotzdem vom Amt holen. Das heißt, die Bürokratie oder dieser bürokratische Schritt, der ist ja immer noch da. Und diese bürokratische Hürde, wenn man jetzt wirklich was ändern wollte, dann braucht es halt mehr.

 Ulf Buermeyer
Dann würde man konsequenterweise sagen müssen, jeder darf arbeiten, meinetwegen nach den ersten drei Monaten, wo man sagt, wir machen jetzt hier erst mal so eine Art Onboarding in Deutschland, aber und dann muss man halt den Arbeitsvertrag bei der Behörde melden und wenn die ein Problem damit hat, dann kann sie sich ja immer noch beim Arbeitgeber melden. Man würde also quasi Regel und Ausnahme verkehren. Heute muss jeder sich erst mal bei der Behörde melden, muss bitten, arbeiten zu dürfen, dann erst kann er anfangen zu arbeiten. In Zukunft würde man anfangen zu arbeiten. Man meldet seinen Arbeitsvertrag bei der Behörde und wenn die dann ein Problem damit hat, dann grätscht sie halt rein. Diese Umkehrung des Regel-Ausnahme-Verhältnisses, die würde ohne Ende Arbeitszeit bei den Behörden sparen. Das würde den Arbeitsmarkt entlasten, weil halt ganz viele Unternehmen mit einem Mal wieder Arbeitskräfte finden würden. Und es bringt halt echte Jobs. Nicht 0,80 € Jobs, sondern richtige Jobs bei richtigen Unternehmen, würde wirklich was für die Wirtschaft tun und es würde die Integration fördern.

 Jana Münkel
Und ich finde, selbst wenn man nicht sofort diesen, ich würde ihn schon als radikalen Schritt bezeichnen, dass man sagt, man macht da jegliche Bürokratie weg, könnte man ja auch Strukturen schaffen, die eben diesen Schritt in den ersten Arbeitsmarkt erleichtern. Man könnte ja auch Programme auflegen, dass man Praktika total fördert oder dass man es wirklich schafft, dass Menschen eben aus ihrer Unterkunft schnell rauskommen, um wirklich auch überhaupt zu sehen, was gibt es denn für Möglichkeiten? Also das muss ja gar nicht unbedingt aus meiner Sicht sofort dieses jegliche Bürokratie muss weg sein. Aber einfach diesen Willen zu zeigen, dass man wirklich auch die Menschen integrieren will und das nicht mit so Alibilösungen wie diesen 0,80 € Jobs zu machen, da wäre schon mal viel geholfen aus meiner Sicht.

 Ulf Buermeyer
Ja, also im Hintergrund hören wir so aus der Ampelkoalition, dass tatsächlich in der grünen Fraktion es große Sympathien dafür gibt. Die SPD Fraktion ist gespalten. Ich hatte da auch schon im letzten Jahr Hintergrundgespräche mit einzelnen Abgeordneten, die total dafür sind, diese Bürokratie abzubauen und zu sagen, Arbeitsverhältnisse müssen nicht vorher genehmigt, sondern nur hinterher gemeldet werden. Ist aber in der Fraktion jedenfalls noch nicht Mehrheitslinie, wie man hört. Kanzleramt und FDP gelten bislang als skeptisch, aber das ist halt hinter den Kulissen ein ganz großes Thema. Und ich glaube, es verdient ein Thema zu werden, über das Deutschland breiter diskutiert. Ich denke, SPD und FDP oder die SPD-Spitze und FDP sollten da ihren Widerstand aufgeben. Denn das scheint mir eine der ganz zentralen Hürden zu sein, dieses Klischee vom faulen Ausländer, der nur die Sozialkassen belastet. Das begegnet uns auch in der Lage ständig. Das ist zwar ein falsches Klischee, aber es ist natürlich schon insofern was dran, als wir momentan viele Menschen nicht arbeiten lassen. Das muss man einfach sehen. Die Menschen sind nicht faul, aber wir zwingen sie zur Passivität. Und das ist halt einfach absurd. Wir können nicht auf der einen Seite sagen, hallo, wir wollen Sozialleistungen sparen, wir wollen keine Migration in die Sozialsysteme und dann auf der anderen Seite sagen, du darfst aber auch nicht arbeiten, das passt nicht zusammen. Insofern wünsche ich mir da eine breite Diskussion und hoffe, die Ampel rauft sich zusammen und dreht hier an der richtigen Schraube.

 Jana Münkel
Zum guten Schluss noch eine gute Nachricht aus Frankreich. Da ist eine historische Entscheidung gefallen. Frankreich ist nämlich weltweit das allererste Land, das das Abtreibungsrecht in die Verfassung eingeschrieben hat. Im historischen Schloss von Versailles hat der Kongress aus Nationalversammlung und Senat abgestimmt. Und das klang dann so:

 Yaël Braun-Pivet
Pour l‘adoption: 780. Contre: 72.

 Ulf Buermeyer
Ja, das war die Stimme der Präsidentin der Nationalversammlung Yaël Braun-Pivet. Die verliest das Abstimmungsergebnis. 780 Abgeordnete der Nationalversammlung und des Senats haben in Versailles im Schloss dafür gestimmt, das Abtreibungsrecht in die französische Verfassung aufzunehmen. Nur 72 waren dagegen. Also eine 3/5 Mehrheit war hier nötig in einer gemeinsamen Sitzung der beiden Kammern des französischen Parlaments. Und diese 3/5 Mehrheit ist locker erreicht worden. Und das gilt als historische Entscheidung auch deswegen, weil eben auch viele konservative Menschen sich für diesen Vorstoß erwärmen konnten. Jana, wie kam es denn dazu, dass es gerade jetzt zu einer solchen historischen Entscheidung kommen konnte?

 Jana Münkel
Ja, das war tatsächlich die Überlegung, dass jetzt die Zeiten so sind, dass es einen Konsens gibt, dass es wichtig ist, wirklich abzusichern, dass Frauen auch in Zukunft, wenn sich möglicherweise politische Mehrheiten ändern, weiter abtreiben dürfen. Also das ist tatsächlich vor dem Hintergrund des verschärften Abtreibungsrechts in den USA passiert. Im Sommer 2022 hat der Supreme Court ja das sogenannte Roe versus Wade gekippt, also damit das bundesweite Recht auf Schwangerschaftsabbrüche. Das war in Frankreich groß diskutiert worden. Das war dann auch ein bisschen die Initialzündung, um zu sagen, wir wollen das sicherer machen. Aber es gibt natürlich auch andere Beispiele. Polen hat das Abtreibungsrecht extrem verschärft. Da gibt es Frauen, die in andere Länder reisen, um abtreiben zu können. Das heißt, die Idee dahinter,  die Zeiten in Frankreich sind gerade so, dass es ein Konsens gibt, dass wir das absichern müssen. Und deswegen tun wir es.

 Ulf Buermeyer
Ja, in Polen gibt es ja sogar immer wieder Nachrichten, dass Frauen zu Tode kommen, weil ihnen Ärztinnen und Ärzte eine lebensrettende Abtreibung verweigern. Also wenn es Komplikationen gibt bei der Schwangerschaft. Das hat also wirklich dramatische Konsequenzen, dieses extrem drakonische polnische Recht. Wobei da natürlich die Hoffnung besteht, dass das unter der neuen Mehrheit im Sejm jetzt auch wieder reformiert werden wird. Aber diese Entscheidung aus Frankreich bedeutet einfach, keine Regierung in Frankreich kann Abtreibung einfach wieder so verbieten. Wobei man sagen muss, es gibt da ja noch so ein paar Nuancen. Es steht ja jetzt nicht einfach nur in der Verfassung, jede Frau hat immer das Recht, eine Abtreibung vornehmen zu lassen. Es ist ja so ein bisschen anders geregelt.

 Jana Münkel
Ja, genau das finde ich ganz spannend die Nuance. In der Verfassung steht strenggenommen nicht das Recht auf Abtreibung, sondern nur die Freiheit, eine solche vorzunehmen. Also da steht dann ganz konkret "la liberté garantie à la femme d’avoir recours à une IVG". Also eine "interruption volontaire de grossesse", also eine freiwillige, ein freiwilligen Abbruch der Schwangerschaft. Aber Ulf, du bist jetzt hier der Jurist. Was macht das für einen Unterschied? Also nicht das Recht auf Abtreibung, sondern die Freiheit zur Abtreibung.

 Ulf Buermeyer
Ja, das ist, das ist ganz interessant. Also die Norm in der Verfassung, der Artikel 34, der da geändert wurde, regelt eigentlich vor allem die Spielräume des Gesetzgebers. Das heißt also, es ist jetzt geregelt worden, dass der Gesetzgeber die Details bestimmen kann, der liberté garantie aller femme usw., also quasi der garantierten Freiheit. Der Gesetzgeber kann die Umstände regeln, unter denen diese garantierte Freiheit wahrgenommen werden kann. Das war quasi so eine Art politischer Kompromiss. Man hat nicht einfach nur ein Abtreibungsrecht reingeschrieben, sondern man hat reingeschrieben ein Recht des Gesetzgebers, etwas zu regeln. Aber implizit und in dieser Norm enthalten ist eben auch diese liberté garantie. Und das heißt also, es gibt eben schon eine Garantie des Abtreibungsrecht, wenn auch gleichsam ein bisschen verklausuliert versteckt fast schon, in einer Regelung der Kompetenzen des französischen Gesetzgebers.

 Jana Münkel
Und warum hat man das dann so kryptisch versteckt und verklausuliert?

 Ulf Buermeyer
Das hat vor allem technische Gründe. Also die Grundrechte in der französischen Verfassung sind vor allem garantiert durch Verweis zum einen auf die Erklärung der Bürger- und Menschenrechte von 1789, also ein Text aus der Französischen Revolution und zum zweiten durch einen Verweis auf die Verfassung der Vierten Republik von 1946. Und weil eben die Grundrechte so durch Verweisung geregelt sind, ist es ein bisschen schwierig. Man kann jetzt ja nicht mehr die Erklärung von 1789 ändern. Man kann auch die Verfassung von 1946 nicht mehr ändern. Und deswegen, wenn man weitere Grundrechte garantieren will, dann steht man in Frankreich immer so ein bisschen vor dem Problem, wie man das rechtstechnisch eigentlich abbildet im Verfassungstext. Und in diesem Fall hat sich jetzt eben eine breite, vor allem überparteiliche Mehrheit darauf geeinigt, regeln wir doch einfach, was der Gesetzgeber so kann zum Thema Abtreibung und versteckt gleichsam oder eingebaut in dieser Regelung der Gesetzgebungskompetenzen steht dann eben die liberté garantie, die garantierte Freiheit der Frauen in Frankreich.

 Jana Münkel
Dann kommen wir mal zurück aus dem deep dive ins französische Recht oder aus dem französischen Recht. Es gab ja ganz viele Reaktionen auch darauf. Der Eiffelturm hat total geglitzert, während diese Abstimmung stattgefunden hat. Außerdem wurden da ja so Botschaften drauf projiziert. #moncorpsmonchoix. Also mein Körper, meine Wahl zum Beispiel. Es gab total den Jubel in Frankreich, aber auch im Schloss Versailles. Also muss ich sagen, als ich diese Bilder angeschaut habe, habe ich auch gedacht, nice, da ist wirklich eine Erfolgsnachricht passiert und da hat wirklich jemand, also Frankreich hat es geschafft, die Verfassung krisenfester zu machen, wenn man so will.

 Ulf Buermeyer
Ja, so jedenfalls hat die französische Gesellschaft, muss man ja sagen, von der Linken bis zur Rechten parteiübergreifend mit einer breiten Koalition geschafft, bestimmte Rechte, in diesem Fall eben ein ganz zentrales Recht für Frauen, in der Verfassung zu verankern. Und ich glaube, da spüren einfach viele, dass das ein großer Erfolg ist, denn auch Frankreich ist ja gespalten politisch, ähnlich wie Deutschland. Die Rechtsextremisten in Frankreich haben sogar schon deutlich höhere Stimmenanteile, sind schon viel mehr noch verwurzelt im französischen politischen System. Und da gilt es einfach als großer Erfolg, dass man noch mal gleichsam parteiübergreifend die Kraft gefunden hat, eine solche grundsätzliche Regelung zu treffen. Und rechtlich ist Frankreich da einfach eine ganze Ecke weiter als Deutschland, muss man sich überlegen. In Deutschland gibt es eben keine explizit verfassungsrechtliche Garantie, Schwangerschaftsabbrüche vornehmen zu lassen, sondern es gibt quasi die Grundrechtsabwägung zwischen den Rechten des werdenden Lebens auf der einen Seite und dem Selbstbestimmungsrecht der Frau auf der anderen Seite. Und das Bundesverfassungsgericht hat ja in den 90er Jahren sogar gesagt, dass eine Abtreibung nie rechtmäßig sein darf. Sie darf nur straffrei bleiben. Also der Gesetzgeber ist verpflichtet, sie als rechtswidrig zu betrachten. Er darf sie nur straffrei stellen. Und das ist die Regelung, die wir heute haben in Deutschland die sogenannte Fristenlösung mit Beratungspflicht.

 Jana Münkel
Genau. Also das muss man, finde ich noch mal betonen. Der Schwangerschaftsabbruch ist in Deutschland gemäß Paragraf 218 Strafgesetzbuch grundsätzlich für alle Beteiligten strafbar. Und du hast es genannt, Ulf, es gibt eine Straffreiheit, wenn sich die Schwangere ergebnisoffen in so einer staatlich anerkannten Beratungsstelle beraten lässt. Aber es ist eine Straftat, abzutreiben in Deutschland nach wie vor.

 Ulf Buermeyer
Ja, es sei denn, man hält eben diese Spielregeln ein. Dann ist es keine Straftat. Das ist so ein bisschen so diese rechtliche Grauzone, die der Gesetzgeber da geschaffen hat. Aber nachdem ihn das Bundesverfassungsgericht dazu verpflichtet hatte, rechtswidrig, aber straffrei, weil nicht tatbestandsmäßig, also allen Strafrechtsdogmatiker:innen, rollen sich da immer gleich die Fußnägel hoch, weil das sonst an keiner Stelle so funktioniert im deutschen Strafrecht. Aber gut, das war offensichtlich der Kompromiss, den die Richterinnen und Richter in Karlsruhe da gefunden haben. Aber wie gesagt, der überzeugt natürlich heute viele nicht mehr, insbesondere für die Rechtswidrigkeit. Nämlich dazu, dass es zum Beispiel immer wieder Probleme gibt bei der Kostenübernahme durch Krankenkassen und so. Immerhin hat die Bundesregierung ja eine Kommission eingesetzt, die zurzeit Alternativen zur geltenden Rechtslage prüfen soll, insbesondere nämlich, ob Abtreibungen möglicherweise auch außerhalb des Strafrechts geregelt werden können. Im April sollen erste Ergebnisse vorliegen. Ich sage mal, wir bleiben dran. Wir sind gespannt, ob diese Kommission da neue Regelung vorschlagen wird.

 Jana Münkel
Dann war's das für heute. Schön, dass ihr dabei wart mit der Lage der Nation Nummer 372.

 Ulf Buermeyer
Die politische Lage in Deutschland und der Welt ist damit abschließend und umfassend erörtert, wie ihr das von uns gewohnt seid. Wir hoffen, diese Folge hat euch gefallen. Wir hoffen, ihr hattet insbesondere viel Freude an unserer Moderatorin Jana Münkel, die heute zum zweiten Mal dabei war. Wir wünschen einen schönen Rest der Woche. Ein schönes Wochenende. Bleibt uns gewogen. Bis ganz bald und tschüss!
