#+title: Beruhigendes Corona-Update, Scholz` Deutschland-Pakt, Wirtschaftskrise in Deutschland (Jens Suedekum, Ökonom), Freie WLANs vor dem Aus

👉 https://plus.lagedernation.org/2023/09/07/ldn347-beruhigendes-corona-update-schroeders-deutschland-pakt-wirtschaftskrise-in-deutschland-jens-suedekum-oekonom-freie-wlans-vor-dem-aus/

 Philip
Herzlich willkommen zur Lage der Nation, Ausgabe Nummer 347 vom 7. September 2023. Mein Name ist Philip Banse.

 Ulf
Und ich bin Ulf Buermeyer. Herzlich willkommen auch von mir. Der Philip ist Journalist, ich bin Jurist aus Berlin und wir haben für euch wieder ein volles Pad vorbereitet mit diesen Themen.

 Philip
Wir kümmern uns um das drohende Ende der freien WLANs in Deutschland.

 Ulf
Wir schauen uns an, wie es um die Lage der Wirtschaft in Deutschland bestellt ist.

 Philip
Und wir interviewen einen der Spitzenökonomen in Deutschland zur Frage, wie wir den Karren aus dem Dreck ziehen und ob er überhaupt so tief im Dreck steckt, wie viele behaupten.

 Ulf
Anfangen wollen wir heute aber mit einer guten Nachricht und die kommt fast überraschenderweise zum Thema Corona.

 Philip
Ja, so ändern sich die Zeiten. Gute Nachrichten machen wir eh viel zu wenig. Und dann auch noch zu Corona. Also worum geht's? Aus dem Umkreis, privat, aber auch aus vielen Bekanntschaftskreisen und so, da ist zu hören viele Leute sind mal wieder krank, liegen flach, haben Corona.

 Ulf
Die haben Corona. Es kursiert momentan auch, jedenfalls hier bei uns in Berlin, eine andere, ziemlich fiese Atemwegsgeschichte. Manche Leute haben überhaupt gar keine Stimme mehr. Das soll aber irgendwie kein Corona sein. Jedenfalls sind die Corona Tests negativ. Andererseits sind die auch ziemlich unzuverlässig. Man weiß es nicht, aber einige Leute haben eben doch Corona. Und eins ist natürlich auch sicher Philip, der Herbst steht vor der Tür.

 Philip
Der Herbst steht vor der Tür. Und angesichts auch dieser ja wirklich spürbaren Corona Fälle, die ja da sind, habe ich mich immer gefragt: Sag mal, was ist denn damit jetzt eigentlich Phase? Also ist das jetzt eine neue Welle? Was sind wir denn eigentlich gerade für eine Variante? Müssen wir uns da jetzt Sorgen machen? Und da kam es irgendwie ganz treffend, dass der Science Media Center eine Pressekonferenz gemacht hat. Science Media Center, weiß gar nicht, was für ein Form ist, Verein oder GmbH? Jedenfalls eine Organisation, die auch gar nicht immer genannt werden will, aber die sich zur Aufgabe gemacht hat, zu wichtigen Themen Wissenschaftler, Wissenschafterinnen zusammen zu holen und zu interviewen und deren Informationen zusammenzufassen, um sie eben für die Medien wissenschaftlich fundiert aufzubereiten. Und die haben jetzt tatsächlich eine PK gemacht, eine Pressekonferenz, ein Hearing oder eine Zoom-Konferenz zum Thema: Wo stehen wir mit Corona?

 Ulf
Tja, und da gab es ganz spannende Ergebnisse und die wollen wir mal für euch zusammenfassen, denn das muss ich euch sagen, da kommen jetzt auch immer mehr Fragen, so auch auf sozialen Medien. Was ist denn jetzt zum Thema Corona? Also Ergebnis: Das Virus ist natürlich weiter da, das war nicht anders zu erwarten. Das geht natürlich nie wieder weg und es mutiert auch weiterhin. Das heißt es entwickeln sich immer neue Virusvarianten und es macht weiterhin Leute krank und es kann auch tatsächlich noch gefährlich werden. Aber vor allem für bestimmte Gruppen.

 Philip
Ältere Menschen, Menschen mit einem geschwächten oder auch künstlich unterdrückten Immunsystem. Beispielsweise Leute, die was weiß ich für eine Transplantation Medikamente nehmen müssen, damit dieses neue Organ nicht abgestoßen wird und das Immunsystem runtergenommen wird. Solche Leute sind durch dieses Virus, aber natürlich auch durch viele andere Viren immer noch bedroht. Aber dieses Virus ist längst nicht mehr so gefährlich wie noch vor ein paar Jahren.

 Ulf
Ja, also auf den Intensivstation gibt es schon noch einzelne Fälle von Menschen, die dort eben liegen mit einer Corona Infektion, aber in aller Regel nicht mehr wegen einer Corona Infektion. Und vor allem wichtige Erkenntnisse: Es droht also keine neue Pandemie, die dann tatsächlich zu drastischen Maßnahmen zwingen würde, wie 2020/21. Der wichtigste Grund, warum Corona weitgehend seinen Schrecken verloren hat: Es gibt kaum noch Menschen, die, wie man so schön sagt, naiv sind, deren Immunsystem das Coronavirus noch nicht kennt.

 Philip
Das heißt also, das Immunsystem fast aller Menschen in Deutschland hat schon mal Kontakt mit dem Virus gehabt, sei es durch eine direkte Infektion oder eben über einen Impfstoff, weil einfach so gut wie alle irgendwie mal infiziert waren, ob sie es nun gemerkt haben oder nicht. Und last but not least: Viele sind einfach geimpft und gepustet, sagt Professor Leif Erik Sander, Infektiologe an der Charite in Berlin.

 Leif Erik Sander
Wir haben jetzt im Grunde schon Impfstoffe, die die allermeisten von uns eben schon sehr, sehr gut schützen. Wir haben quasi eine sehr starke Immunität aufgebaut und deswegen ist auch die Fallsterblichkeit, also die Gefährlichkeit dieses Virus, für jeden Einzelnen deutlich reduziert worden im Vergleich zu der Zeit, bevor wir geimpft waren. Insofern es geht jetzt um Optimierung. Es geht um optimalen Schutz gerade von Risikogruppen. Und noch eine weitere Senkung. Denn natürlich jeder Todesfall, jede schwere Erkrankung ist eine zu viel. Und wenn man mit einer relativ einfachen Intervention einer Impfung das senken kann, glaube ich, sollte man das machen. Bei uns auf der Intensivstation sind es sporadische Fälle von Patienten, die noch mal so schwer erkranken, häufig Patienten mit Immunschwäche. Von daher haben die Impfungen schon sehr guten, auch breiten Schutz geliefert.

 Ulf
Professor Dr. Sandra Ciezek, vielen noch sicher bekannt vom Corona Podcast von NDR Info. Sie ist Direktorin des Instituts für Medizinische Virologie am Universitätsklinikum in Frankfurt am Main, sagte mit Blick auf den Herbst:

 Sandra Ciezek
Ach, ich glaube, das wird so ähnlich wie letztes Jahr und es ist einfach ein Nervfaktor für alle. Wenn die Erkältungssaison kommt, wenn die Infektionen ansteigen. Ich gehe davon aus, dass sehr viele von uns noch einmal in der kommenden Saison eine Corona Infektion durchmachen werden. Und es ist ja schon so, dass die meisten dann doch eine Woche zu Hause sind und ausfallen, weil sie krank sind, weil sie einfach wirklich Fieber haben, weil sie Husten haben und Schnupfen haben. Aber ich sehe, solange Omikron zirkuliert, keine Gefahr, dass sich die Situation groß verändert oder dass es auch noch mal nötig wird, dass zum Beispiel der Staat irgendwelche Maßnahmen verhängt. Das sehe ich im Moment überhaupt nicht.

 Philip
Sie sieht auch keine wirklich gefährlichen Varianten am Horizont. Aktuell ist es Omikron und ein paar Mutationen davon, aber andere gefährliche, wirkliche gefährliche Varianten sehen sie nicht am Horizont. Und da ist natürlich die Frage: Ist Corona jetzt also nur noch wirklich eine nervige Erkrankung, so wie Husten oder Schnupfen? Daran machten eine Fußnote schon erwähnt alleine Leif Erik Sander von der Charite und Stefan Kluge. Der ist Direktor der Klinik für Intensivmedizin am Uniklinikum in Hamburg Eppendorf. Beide sagen im Prinzip: Ja, so ist es. Es droht auf keinen Fall eine neue Pandemie. Aber es gibt generelle strukturelle Probleme im deutschen Gesundheitswesen, die durch diese Viren jetzt noch mal deutlich drastischer werden könnten. Vor allem der Personalmangel bei der Pflege.

 Stefan Kluge
Ich glaube, wir können davon ausgehen, dass irgendwann im Herbst, Winter vermehrt Atemwegsinfektionen zirkulieren, die auch zu einer Belastung des Gesundheitswesens führen. Ich glaube nicht, dass die so hoch werden wird, auch nur annähernd so hoch wie in den wirklichen Pandemiejahren. Aber der Mitarbeitermangel, der Fachkräftemangel, der wird uns natürlich weiterhin zu schaffen machen. Das ist unser größtes Problem in den Krankenhäusern. Und der wird natürlich durch Infektionswellen noch mal verschlechtert. Insofern ist das so meine große Sorge, die ich habe vor dem Herbst, dem Winter.

 Leif Erik Sander
Diesen Herbst und Winter, sehe ich ungefähr so wie den letzten, und es kann auch wieder zu Belastungen führen. Das kann aber dazu führen, dass Leute in die Rettungsstellen gehen und stundenlang warten müssen und nicht behandelt werden können und vielleicht in weit entfernte Krankenhäuser verlegt werden müssen, weil nichts frei ist, was eine Kombination aus vielen Infektionen und Personalmangel ist.

 Ulf
Das war also erst Professor Kluge und dann zum Schluss Professor Sander. Ja, Philip, was sollten wir denn jetzt machen in diesem Herbst? Von staatlicher Seite, glaube ich, ist nicht mehr so wahnsinnig viel an Schutzmaßnahmen zu erwarten.

 Philip
Und auch nicht notwendig.

 Ulf
Und auch vielleicht nicht notwendig. Ob es klug wäre, weiß ich nicht. Aber jedenfalls wird es, wird es nicht kommen. Da muss man sich, glaube ich, keine Illusionen machen. Aber wir können natürlich privat eine ganze Menge tun. Zentral weiterhin: Masken.

 Philip
Genau das haben wir auch gesagt. Es wird keine staatlich verordnete Massenflucht oder so was geben. Aber natürlich, Maske hilft immer, schadet eigentlich nie. Na klar. Wer den ganzen Tag acht Stunden mit Maske rumrennen muss, ist das noch mal was anderes. Aber im öffentlichen Nahverkehr oder auf Konzerten oder wie auch immer öffentliche Veranstaltungen Maske aufzusetzen, das ist sicherlich mindestens für den Selbstschutz gut und sicherlich auch für die anderen.

 Ulf
Und zwar nicht nur wegen Corona, sondern das schützt ja auch vor allen möglichen anderen Infektionskrankheiten, also insbesondere wenn was wichtiges ansteht. Eine Reise zum Beispiel, eine Hochzeit irgendwie. So was ist es auf jeden Fall eine gute Idee, eine Woche in Menschenansammlungen sich selber zu schützen. Wäre natürlich toll, wenn alle Menschen eine Maske trügen, vor allem in öffentlichen Verkehrsmitteln. Denn wir wissen ja, am aller effektivsten schützen die Masken nicht beim Einatmen, sondern beim Ausatmen. Aber du hast es gesagt, Philip, Von der Pflicht sind wir meilenweit entfernt. Leider Gottes fehlt es da in Deutschland an dieser nötigen Solidarität. Das ist ja zum Beispiel im asiatischen Raum häufig anders. Da gehört zum guten Ton, eine Maske zu tragen in der Ubahn. Das ist bei uns leider nicht so, im Gegenteil hat sich ja hier die Maske so aus meiner Sicht bedauerlicherweise so raus entwickelt zu einem Symbol der persönlichen Freiheitsentfaltung oder die Maskenfreiheit. Schade, aber so ist es eben bei uns. Wie gesagt, jeder einzelne von uns kann sich schützen und schützt damit eben und das ist das Schöne, zugleich auch seine Mitmenschen.

 Philip
Ja, dann natürlich das wirklich wichtige Element: die Impfung. Die Impfung ist wichtig, bleibt wichtig. Das Robert Koch Institut RKI schreibt dazu: Gesunden Personen ab 18 Jahre, auch Schwangeren wird eine Grundimmunisierung plus eine Auffrischung empfohlen, um eine Basis Immunität aufzubauen. Wichtig für diese Basisimmunität schreibt des RKI ist, dass das Immunsystem drei mal Kontakt hatte mit Bestandteilen des Erregers und mit dem Erreger selbst, also Bestandteilen des Erregers durch die Impfung und den Erreger selbst durch eine Infektion. Mindestens zwei dieser Kontakte sollen durch die Impfung erfolgen.

 Ulf
Was heißt das jetzt praktisch und konkret? Ihr könnt euch alle fragen: Hatte ich mindestens zwei Impfungen und hatte ich schon mal Corona oder eine dritte Impfung? Ansonsten sollte man sich schon deswegen dringend gegen Corona impfen lassen und zwar auch wenn man nicht zu einer Risikogruppe gehört, einfach um diese sogenannte Basisimmunität aufzubauen. Denn was wir oben gesagt haben, nämlich dass Corona nicht mehr so gefährlich ist, das gilt natürlich nur für Menschen, deren Immunsystem nicht naiv ist, wenn ihr durch großes Glück zum Beispiel bislang überhaupt kein Corona hattet und bislang auch impfskeptisch wart, dann ist es spätestens jetzt ein guter Moment, um sich diese Basisimmunität aufzubauen. Und was gilt denn jetzt für alle, die Immunsystem schon mindestens drei mal Kontakt zu Corona hatte?

 Philip
Was ja die große große Mehrheit in Deutschland ist. Die sollte zumindest den Booster erwägen, sagt Leif Erik Sander von der Charite.

 Leif Erik Sander
Wir haben früher gesagt, jeder braucht drei Impfungen. Jetzt ist es aber so, dass sie kaum noch einen Menschen finden, der keinen Kontakt hatte mit dem Virus, also keine Infektionshistorie hat. Und von daher geht man davon aus, dass auch eine einmalige Impfung ausreichen kann, um den Impfschutz zu komplettieren, insbesondere wenn Infektionen vorliegen. Und man kann dafür auch die jetzt neuen angepassten Impfstoffe verwenden, weil nur noch Omikron zirkuliert.

 Ulf
Ja, empfohlen ist diese Impfung auf jeden Fall von Seiten des Robert Koch Instituts für Risikogruppen und ab 60 Jahren. Man sollte das nicht machen, wenn man gerade eine Infektion hatte. Aber ansonsten ist so eine Impfung auf jeden Fall eine gute Idee. Also Philip und ich werden uns auch auf jeden Fall impfen lassen. Ganz praktisch dabei: Man kann sich wohl in diesem Winter erstmals gegen Corona und Grippe kombiniert impfen lassen.

 Philip
Das haben die auch bei der Pressekonferenz gesagt. Es gibt eine eine Kombiimpfung, dass man das in einem Abwasch quasi erledigen kann. Und deswegen habe ich jetzt noch ein bisschen gewartet und jetzt nicht gleich diese Woche los gestopft. Es wird einen angepassten Impfstoff an die aktuelle Corona Variante geben. Der Impfstoff der Firma Biontech soll von der Woche vom 18. September an erstmals in Praxen zu bekommen sein. Dabei handelt es sich eben um ein angepasstes Präparat für die Omikron Sublinie XBB 1.5 und der soll dann noch mal ein bisschen besser schützen vor den jetzt kursierenden Varianten als die bisher schon auf dem Markt befindlichen Impfstoffe. Ich glaube, auch mit den bisherigen Impfstoffen macht man jetzt nichts falsch.

 Ulf
Also ist natürlich auf jeden Fall besser, als sich gar nicht impfen zu lassen. Andererseits gibt es dann halt auch wieder den Tipp: Na ja, die drei Monate nach der Impfung hat man den besten Impfschutz. Deswegen ist natürlich schon eine gute Idee, sich vielleicht sagen wir mal so relativ knapp vor der harten Infektionszeit impfen zu lassen. September ist vielleicht ein Tick zu früh, also insofern macht es vielleicht auch Sinn, auf den Oktober zu warten. Aber das muss jeder für sich selber entscheiden. Auf jeden Fall ist es eine gute Idee, sich so eine Impfung abzuholen. Philip, für den angepassten Impfstoff von Moderna gibt es so noch keine Zulassung.

 Philip
Ja, da schreibt die dpa wenn die vorliege, dann werde sie im Rahmen der Regelversorgung auch angeboten und dann auch von den Krankenkassen bezahlt, wenn Ärzte ihn aufgrund einer Empfehlung der Ständigen Impfkommission verordnen und Ärztinnen natürlich auch. Es gibt auch gegen SV, eine andere Viruserkrankung, die gerade rumgeht, sehr gute Impfstoffe haben sie auch noch mal empfohlen. Kann man sich auch gegen impfen lassen, ganz interessant. Ich habe noch mal geguckt ja, wie würde man das denn jetzt machen? Und ob da mal bei Doktolib einfach mal gegeben Impfung Corona. Und da haben sie mich gefragt: Ja, welchen Impfstoff hättest du denn gerne? Diese Angepasste jetzt an XBB 1.5, der war noch nicht zur Auswahl, aber habe jetzt mal den den den neuesten, den spezifischen genommen, den es da gerade gab und vielen jede Menge niedergelassene Ärzte und Ärztinnen raus, wo ich mir Freitag also ich habe Dienstag mal geguckt, am Freitag den Termin gekriegt und auch Impfzentren gab es.

 Ulf
Ah, immer noch!

 Philip
Wieder auch? Wieder noch? Keine Ahnung. Jedenfalls konnte ich mir auch in Impfzentren einen Termin buchen. Wie gesagt, ich warte jetzt noch bis der angepasste Impfstoff da ist, aber dann werd ich das sicherlich machen.

 Ulf
Zu unserem nächsten Thema: wir schauen in den Deutschen Bundestag. Dort laufen nämlich in dieser Woche die Haushaltsberatungen. Das heißt, der Bundestag debattiert den Haushaltsentwurf von Bundesfinanzminister Christian Lindner und am Mittwoch dieser Woche stand der Etat des Kanzleramts auf der Agenda. Und das ist ja der traditionelle Anlass für die sogenannte Generaldebatte. Philip, was hat es damit auf sich?

 Philip
Na ja, also dieser Haushaltsentwurf ist ja ein Gesetzesentwurf, der wird dann halt ins Parlament eingebracht, und dann wird halt über die allermeisten Etats da ausführlich diskutiert, wer da wie viel Geld bekommt. Und wenn der Etat des Kanzleramts da am Mittwoch traditionell auf der Tagesordnung steht, na dann darf zuerst der Oppositionsführer reden, also der Vorsitzende der größten Oppositionsfraktion und halt traditionell einfach mit der Regierung abrechnen. Da geht es ja nicht nur um den konkreten Euroetat, was die jetzt für ihre Empfänger ausgeben dürfen, sondern einfach um die generelle Politik der Regierung.

 Ulf
Und Oppositionsführer Friedrich Merz nutzte seine Rede für eine Generalabrechnung mit der Bundesregierung. Der Vorsitzende der CDU und zugleich Vorsitzender der Unionsfraktion von CDU und CSU, sparte in seiner Rede nicht mit deutlichen Worten.

 Friedrich Merz
Unser Land erstickt in Bürokratie. Wir würden sofort alle Gesetze stoppen. (Gelächter im Plenum) Wir würden sofort alle Gesetze stoppen, die diesen wahnsinnigen Bürokratieaufwand immer noch weiter erhöhen. Dazu zählen eben das angekündigte Kindergrundsicherungsgesetz, das wir bis heute nicht haben. Und das Gebäudeenergiegesetz. Wir würden es nicht machen.

 Philip
Ja, das Gelächter, das kommt natürlich daher, weil diese von Merz kritisierte Bürokratie nicht zuletzt in den 16 Jahren Merkelregierung entstanden ist, also unter der Führung von CDU und CSU auch gewuchert ist. Aber gut, die Kritik ist berechtigt und angekommen.

 Ulf
Tja, und danach war dann der Bundeskanzler an der Reihe und Olaf Scholz zeichnete in seiner auch relativ kämpferischen Rede doch ein erstaunlich klares und zugleich kritisches oder auch vielleicht in Teilen selbstkritisches Bild der Lage der Bundesrepublik.

 Olaf Scholz
Zu viel ist in den vergangenen Jahren auf die lange Bank geschoben worden. Wer heute mit der Bahn oder mit dem Auto von Hamburg nach München fährt, der erlebt bei jeder weichen Störung, unter jeder Brücken Baustelle, wie sehr unsere Infrastruktur auf Verschleiß gefahren wurde. Statt in die Zukunft zu investieren, haben wir über die PKW Maut diskutiert und die jahrelange Vernachlässigung unserer Bundeswehr bis zur Zeitenwende ist hier schon so oft debattiert worden, dass ich darüber nicht mehr als das zu Anfang sagen muss.

 Philip
Also Infrastruktur ist auf Verschleiß gefahren, die Bundeswehr kaputtgespart, Bürokratie eine Plage für Bürger und Unternehmen Bürgerinnen. Der Stand der Digitalisierung eines Landes wie Deutschland nicht würdig. Das waren so die Töne des Bundeskanzlers. Ja, und er benennt eben tatsächlich auch durchaus zutreffend eine Reihe von Problemen, die wir oft schon auch in der Lage besprochen haben. Also Fachkräftemangel ist natürlich eine Sache. Dann auch der zu langsame Ausbau der erneuerbaren Energien.

 Olaf Scholz
Der Bund, die Länder, Städte und Gemeinden, Unternehmen und Behörden, Verbände und Gewerkschaften. Nur gemeinsam werden wir den Mehltau aus Bürokratismus, Risikoscheu und Verzagtheit abschütteln, der sich über Jahre, Jahrzehnte hinweg über unser Land gelegt hat. Dieser Mehltau lähmt unsere Wirtschaft, und er sorgt für Frust bei den Leuten im Land, die einfach wollen, dass Deutschland ordentlich funktioniert, dass die Bahn pünktlich fährt, dass unsere Infrastruktur analog und digital zu den Besten in Europa zählt, dass einem die Ämter unter die Arme greifen und keine Schwierigkeiten machen. Das erwarten die Bürgerinnen und Bürger nach Jahren des Stillstands.

 Philip
Ja, das sind dann schon deutliche Worte.

 Ulf
Und vor allem kommt da schon ein Ton, der im Grunde den weiteren Verlauf von Olaf Scholz Rede vorzeichnet. Nur gemeinsam geht es voran, macht der Bundeskanzler deutlich. Und sein Kassensturz gipfelte dann in einem Stoßseufzer, dass es so nicht weitergehen könne. Deswegen hat Olaf Scholz ein Angebot.

 Olaf Scholz
In meiner Verantwortung als Bundeskanzler möchte ich Ihnen daher heute ein Angebot machen. Mein Vorschlag richtet sich an die 16 Regierungschefinnen und Regierungschefs der Länder, an die Landräte und Landräte, an die Bürgermeisterinnen und Bürgermeister überall in unserer Republik. Und mein Vorschlag richtet sich ausdrücklich auch an Sie, verehrter Herr Merz als Vorsitzender der größten Oppositionspartei, die im Bundesrat, in den Ländern und Kommunen Verantwortung trägt. Wir brauchen eine nationale Kraftanstrengung. Lassen Sie uns unsere Kräfte bündeln. (Applaus) Beweisen wir den Bürgerinnen und Bürgern, wozu unser Land, unser Föderalismus und unsere Demokratie imstande sind. Viele im Lande warten geradezu sehnsüchtig nach einem solchen Schulterschluss. Und ich möchte Ihnen deshalb einen Pakt vorschlagen, sagen wir einen Deutschland-Pakt. Ein Deutschland-Pakt, der unser Land schneller, moderner und sicherer macht. Tempo statt Stillstand. Handeln statt Aussitzen. Kooperation statt Streiterei.

 Ulf
Olaf Scholz will also einen Deutschland-Pakt. Und Philip, du hast den Eindruck, er sollte eigentlich lieber frei reden?

 Philip
Ja, er hat am Anfang auf Friedrich Merz reagiert, der vor ihm gesprochen hat. Und da merkte man, da gibt es Anliegen, da formuliert er frei, da sitzt das, da verhaspelt er sich nicht so, und irgendwann muss er dann wieder zu seiner Rede übergehen und dann wird es halt doch ein bisschen vorgelesen. Ich würde ihm empfehlen Reden Sie öfter mal frei. Das ist einfach überzeugender. Und das ist das letztlich, was er erreichen muss. Er muss überzeugen, er muss mitnehmen, man muss ihm das irgendwie abnehmen. Und das fällt schwerer, wenn er es abliest.

 Ulf
Den Eindruck kann man haben, aber man muss ja nicht zu seiner Ehrenrettung dazu sagen. Er hatte in der vergangenen Woche einen Sportunfall, er ist beim Joggen gestürzt. Deswegen trägt er zurzeit eine Augenklappe. Sieht so ein bisschen aus wie ein Pirat.

 Philip
Der erste Bundeskanzler der Piraten.

 Ulf
Haben die Piraten auch gleich getwittert, unser erster Bundeskanzler. Na gut, also vielleicht liegt das auch daran, vielleicht fällt es ihm einfach gerade schwer abzulesen von seinem Zettel. Wer weiß es? Aber jedenfalls machte Olaf Scholz dann auch eine ganze Reihe von Vorschlägen, welche Elemente denn in einem solchen Deutschland-Pakt enthalten sein sollten.

 Olaf Scholz
Der Deutschland-Pakt setzt dort an, wo die Bürgerinnen und Bürger Fortschritte am dringendsten erwarten bei der Energieversorgung, die sauber, sicher und bezahlbar sein muss, beim Bau neuer Wohnungen und Häuser, bei der Modernisierung und Digitalisierung unserer Infrastruktur, bei der Wettbewerbsfähigkeit unserer Unternehmen, bei einer schnellen, leistungsfähigen und digitalen Verwaltung.

 Philip
Ja, also insgesamt, sagt er, müsste man mehr Tempo machen. Mehr Deutschland Tempo. Es müsste schneller gehen, sagt der Kanzler.

 Olaf Scholz
Das heißt natürlich auch, dass wir die Planungsprozesse überall digitalisieren. Schluss jetzt mit Zwei Meter Aktenordnern.

 Philip
Das habe ich aufgenommen. Da dachte ich Junge, Junge, Junge, der, der, der legt aber hier gut vor. Also schnell, schnell nimmt er schon beim Wort. War natürlich auch zweifacher Geschwindigkeit. Ich hatte das so oft, ich merke das gar nicht mehr. Die original Geschwindigkeit von Olaf Scholz, das Deutschland Tempo. Das klingt natürlich anders.

 Olaf Scholz
Schneller heißt natürlich auch, dass wir die Planungsprozesse überall digitalisieren. Schluss mit 2 Meter Aktenordnern für den Bau eines Solardachs oder eine Mobilfunkantenne. Schneller heißt, dass Gutachten und Umweltdaten, die schon oft da sind, nicht noch mal vorgelegt werden. Schneller heißt das wir EU-Regeln zum Naturschutzrecht eins zu eins umsetzen, damit das auch überall gleich funktioniert. Schneller heißt, dass alle 16 Länder bis Ende des Jahres Bauanträge auch digital annehmen. Schneller heißt, dass nicht noch weitere Gutachter und Sachverständige für Genehmigungen gebraucht werden, wenn ein Handwerksmeister bestimmte und Gebäude und Gebäudeteile plant. Schneller heißt, das Ordnungsrecht so zu ändern, dass überall im Land neue Geothermie-Anlagen entstehen können. Schneller heißt, dass wir eine Anlaufstelle schaffen für Schwertansporte auf Autobahnen, damit die Rotorblätter für Windräder und vieles andere besser transportiert werden kann. Schneller heißt auf manche Genehmigungspflicht einfach mal zu verzichten, damit Glasfaserleitungen zu den Nutzern kommen. Alles das heißt schneller. Und darum geht es. Wir müssen das Bürokratiedickicht lichten.

 Philip
Ja, was war das jetzt für eine Rede? Also ich finde ja erst mal erfrischend, dass er die Wirklichkeit relativ konkret und zutreffend beschreibt. Ich finde, dass es erst mal schon ein Fortschritt.

 Ulf
Ja, das finde ich auch. Das ist ein ganz erfrischender Fortschritt gegenüber zum Beispiel seinen Kommunikationen zum Thema CO2 Einsparung, Klimaschutzziele, wo er sich letztlich an Wolkenkuckucksheim festhält. Hier wird Klartext geredet, hier wird Tacheles geredet, hier benennt er sehr genau und auch vor allem sehr konkret. Jetzt, im letzten Ton gehört manchmal sogar ein bisschen detailverliebt die Probleme. Und das lässt mich doch hoffen, dass er da jetzt ernsthaft mal ran will nach zwei Jahren.

 Philip
Ja, weil das ist die Messlatte. An diesen Problemen wird er gemessen werden, weil er hat sie genannt, er hat sie anerkannt und an denen wird er gemessen werden. Es ist aber auch klar geworden, spätestens jetzt, und das merkt man in dieser Rede: Er weiß, die Ampel allein kann das nicht schaffen. Er will also ein Bündnis schmieden. Auch das ist richtig. Ich glaube, es sollte so eine Rede sein wie diese Zeitenwenderede so von der, von der, von der von der Bedeutung. So ein Ruc. So, ich trete jetzt dahin und rede mal Tacheles. Was bei der Zeitenwende der Fall war, war, dass er gesagt hat 100 Milliarden €, zwei Prozent für die Bundeswehr vom Bruttoinlandsprodukt. So was gab es hier nicht. Es gab keine neuen Vorschläge, keine neuen Investitionen, kein neues Gesetz, kein neues Geld. Es waren alles bekannte Probleme, bekannte Maßnahmen. Es war schlicht der Versuch, Schwung in bestehende Gespräche, in bestehende Vorhaben zu bringen.

 Ulf
Ja, es ist natürlich auch ein ganz kleines bisschen schon auch eine Verantwortungsverschiebung auf die Union. Denn es ist ja ein offenes Geheimnis, dass auch die Ampel sich bei weitem nicht immer einig ist bei ganz vielen dieser Projekte. Aber auf jeden Fall finde ich es gut, dass er versucht hat, hier mal einen Vorschlag zu machen, wenn auch nicht inhaltlich, dann doch jedenfalls zum Verfahren. Denn Olaf Scholz weiß ja ganz genau: er ist zwar Kanzler einer Ampelkoalition. Die haben auch eine Mehrheit im Bundestag. Aber damit es wirklich vorangeht mit diesen vielen Projekten, braucht er die Union. Von Windkraft bis Wachstumschancengesetz. Ohne die Länder und damit ohne die Union geht nichts. Denn die Union, die Länder können im Bundesrat praktisch alle wesentlichen Gesetze blockieren, sobald es irgendwie ums Geld geht. Und wo geht es nicht ums Geld? Kann ohne den Bundesrat praktisch nichts Gesetz werden. Wir wollen das jetzt nicht im Detail aufdröseln, aber die Bottom Line ist: Er braucht den Bundesrat praktisch immer. Und die spannende Frage ist natürlich, wie sich jetzt die Union dazu strategisch, politisch positioniert.

 Philip
Also Merz hat ja vor ihm geredet. Dann kam der Vorschlag, da konnte er jetzt also unmittelbar im Bundestag nicht darauf reagieren. Er wirkte so ein bisschen vielleicht überrascht. Keine Ahnung.

 Ulf
War so der Eindruck, der der Korrespondent von Frank Capellan im Deutschlandfunk gestern zitiert, der meinte, er hätte sich jetzt also Merz hätte erst mal mit Dobrindt die Köpfe zusammengesteckt und heiß diskutiert, was man damit jetzt machen soll. Aber das ist natürlich keine offizielle Verlautbarung, das war so der Eindruck von Frank Capellan.

 Philip
Also ich glaube nicht, dass Sie es vorher wussten, dass dieses Angebot kommt. Und die Frage ist natürlich: Wie reagieren Sie drauf, wo sieht die Union, wo sieht Merz die größeren Chancen, wenn sie die Ampel vor die Wand fahren lassen? Wir machen hier Obstruktion und blockieren. Und seht mal zu, wie ihr den Karren aus dem Dreck kriegt? Oder rechnen Sie für sich aus, dass es für Sie politisch günstiger ist, wenn Sie Verantwortung übernehmen, konstruktiv mitgestalten? Ich würde sagen, da ist die Meinungsbildung nicht abgeschlossen.

 Ulf
Das kann man so sagen. Es ist, glaube ich, auch nicht so hoch gegriffen oder nicht so weit spekuliert. Wenn man davon ausgeht, dass vor den Landtagswahlen in Hessen und Bayern so eine Einheitsfront sicherlich nicht zustande kommen wird. Bis dahin wird erst mal Wahlkampf gemacht. Aber die Frage ist, was passiert denn dann? Denn klar ist eins: Fundamentalopposition wäre rein rechtlich problemlos möglich. Die sehr weitreichenden Mitwirkungsrechte des Bundesrats auf Bundesebene machen das möglich. Ohne die Union kann die Ampel fast nichts beschließen. Aber, und das ist irgendwie ein bisschen der Plottwist an der Stelle: Merz und seine Leute von der Union wissen natürlich auch das gilt genauso andersherum.

 Philip
Richtig. Selbst wenn Sie, also die Union, die nächste Bundestagswahl gewinnen sollten, wären auch sie für wirklich tiefgreifende Reformen auf die SPD und die Grünen angewiesen. Ohne die würde auch die Union nichts durchbekommen. Und wer jetzt blockiert, wird potenziell selber in zwei, drei Jahren ausgebremst.

 Ulf
Genau. Und dann könnte es doch einen nicht unerheblichen Anreiz geben, im Grunde für alle, die politisch Verantwortung tragen, mit Ausnahme der Obstruktionsleute von der AfD, sich doch vielleicht lieber jetzt gleich zu einigen, denn dadurch schlägt man zwei Fliegen mit einer Klappe. Man schafft quasi jetzt tatsächliche Fortschritte. Das macht die Menschen in Deutschland grundsätzlich zufriedener mit der Politik und man hat dann zugleich auch die Chance, dass man, wenn man die Wahl gewonnen haben sollte, 2025 selber besser gestalten kann. Der Witz allerdings an Olaf Scholz Vorschlag ist natürlich, dass der in gewisser Hinsicht auch nur die Realität mal offenlegt.

 Philip
Ja, ich habe mich auch gefragt, als er das so vorgeschlagen hat, dann was ist das Besondere daran, was er da erzählt? Denn es gibt ja längst de facto diese Mitregierung der Union, bei allen wesentlichen Gesetzen, das haben wir gesagt im Bundesrat, ohne die geht im Bundesrat nichts. Deswegen gibt es heute schon de facto so ein Bündnis, so ein Deutschland Pakt, weil die sich in wesentlichen Fragen bei tiefgreifenden Reformen immer mit der Union einigen müssen.

 Ulf
Das würde ich im Detail anders sehen. Ich würde sagen, es gibt diese De facto Mitregierung ja, aber es gibt die eben nicht als Teil eines Deutschland-Pakts. Und es gibt die eben bislang nicht offen und ausgesprochen, sondern es gibt die de facto hinter den Kulissen. Nur findet diese de facto Mitregierung eben oft erst im sogenannten Vermittlungsausschuss statt. Das ist ja quasi das Gremium, das eingeschaltet wird, wenn sich, wenn ein Gesetz des Bundestags, das im Bundesrat zustimmungspflichtig ist, eben nicht durchkommt, dann gibt es da diesen Vermittlungsausschuss, ich sage jetzt mal dieses Hinterzimmergremium unter Ausschluss der Öffentlichkeit, wo dann irgendwie versucht wird, ein Ergebnis zu finden. Und das ist ja häufig für die Demokratie nicht so wahnsinnig hilfreich.

 Philip
Das ist maximal spät im Verfahren da hast du schon irre viel Zeit investiert in irgendwelche Lösungen, die dann alle am Ende irgendwie noch mal über den Haufen geworfen werden können. Dass ist maximal spät abends in aller Regel, das ist maximal intransparent, weil das alles hinter verschlossenen Türen verhandelt wird. Das führt in aller Regel zu Minimalkompromissen, die dann irgendwie das Land leicht ein bisschen in Trippelschritten voranbringen. Aber große Sprünge erreichst du da in aller Regel nicht. Siehe Bürgergeldreform haben wir auch lange drüber geschrieben, geredet, hatte der Bundestag beschlossen. Bundesrat erhebt Einspruch und am Ende wird das Ding zusammengeschrumpft auf fast nichts.

 Ulf
Das hatte natürlich schon ein paar Änderungen, aber die spannendste Änderung ist wirklich der neue Name und ganz viele Entlastungen, die da geplant waren, sogar letzten Endes mit Zustimmung der FDP, mit den Stimmen der FDP sind dann an der Union gescheitert im Bundesrat. Das heißt also diese Mitregierung de facto der Opposition auf Bundesebene findet bislang in einer Weise statt, die sowohl inhaltlich als auch vom demokratischen Prozess her maximal unerfreulich ist. Philip, und wenn man das aus dieser Perspektive einmal betrachtet, dann hat der Vorschlag von Scholz schon gewissen Charme.

 Philip
Ja, wir können in seinen Kopf nicht reingucken. Aber wenn wir das mal wohlwollend interpretieren, was er da vorgeschlagen hat, so unkonkret das war, aber eben ein Pakt, dann könnte man annehmen, dass er ohnehin unvermeidliche Diskussionen und Abstimmungen mit der Union quasi aus dem Hinterzimmer vom Ende des Prozesses hervorziehen will und ganz an den Anfang stellen will mit mehr Transparenz, mehr Diskurs. Am Anfang versuchen wir, eine Einigung zu finden. Das ist dann zwar natürlich mühsamer, erst mal, aber wenn das klappt, könnte das auch zu mehr Tempo führen, weil man einfach hintenraus viel schneller ist und man weiß, das kommt in der Regel dann auch so, und man muss nicht erst noch durch den Vermittlungsausschuss. Aber ob dabei wirklich größere Ergebnisse rauskommen, das ist die Frage.

 Ulf
Ich meine, das ist eben das ganz große Problem dieser starken Mitwirkungsrechte des Bundesrats, dass es zu einer De facto Super Koalition führt, zu einer ganz großen Koalition von Grünen bis hin zur CSU. Das muss man sich mal überlegen. Alle diese Parteien Grüne, FDP, SPD, CDU und CSU, alle diese Parteien müssen sich einig werden. Und wenn man sich überlegt, dass die natürlich völlig unterschiedliche Konzepte haben, ist das einfach extrem problematisch. Der Vorteil könnte allerdings sein, dass man dann nicht mehr diese quälende ich sag jetzt mal etwas überspitzt Zoffphase in der Ampel hat, wo sich FDP und Grüne verhaken. Dann hat man einen Kompromiss gefunden und dann kommt noch mal die Union. Das heißt, man hat wenigstens nicht zwei Zoffphasen, sondern man hat hoffentlich nur noch eine.

 Philip
Na ja, aber dann muss erstmal die Ampel eine Meinung bilden, bevor du mit der Union redest. Der Zoff, der wird da glaube ich nicht nicht nicht weggehen. Die Alternative, würde ich sagen, wäre daher eigentlich eine bessere Idee gewesen, nämlich dass Scholz quasi einen Pakt zur Reform des Föderalismus vorgeschlagen hätte. Aber dass natürlich dann noch mal eine ganz andere Baustelle.

 Ulf
Das ist eine andere Baustelle. Aber das ist tatsächlich so die zentrale Erkenntnis, die wir gewonnen haben in den letzten 18 Monaten, als wir für unser Buch recherchiert und geschrieben haben, dass der Föderalismus in Deutschland in seiner gegenwärtigen Gestalt, insbesondere mit den Rechten des Bundesrats, einfach an allen Ecken und Enden bremst und Dinge ausbremst und verhindert. Und ich glaube, ein gutes Stück des Mehltau ist im Grunde Fallout des Bundesrats. Deswegen: Zusammen mit der Union ließe sich natürlich der Bundesrat auf ein gesundes Maß zurechtstutzen. Und vielleicht hätte Olaf Scholz statt dieses sogenannten Deutschland-Pakts oder jedenfalls begleitend dazu mal zu einem Gipfel nach Meseberg laden sollen, ins Gästehaus der Bundesregierung mit der Union und Linkspartei, aber ohne Presse und ohne Handys. Und ohne Twittern. Und dann in Ruhe besprechen, wie man eine eine kleine, aber wichtige Föderalismusreform hinbekommt, die dann tatsächlich der Mehrheit im Bundestag deutlich mehr Spielräume einräumt. Das wäre das wäre aus meiner Sicht die grundsätzliche Lösung des Problems gewesen. Aber Philip, du hast es eben gerade schon angedeutet Föderalismus hin oder her. Eine Voraussetzung für einen solchen Deutschland-Pakt, wie ihn Olaf Scholz jetzt offensichtlich will, nämlich im Wesentlichen Absprachen mit der Union, ist doch klar, Du hast es eben schon angedeutet eine geschlossene Ampel.

 Philip
Ja, ich glaube, da kommst du nicht vorbei, weil auch so ein Pakt Führung braucht. Der muss in eine Richtung wandern und die muss die Ampel vorgeben, die muss er vorgeben. Und das sieht halt momentan nicht danach aus. Davon sind sie einfach sehr weit entfernt. Und das hat man in dieser Debatte um den Haushalt auch so deutlich gesehen wie eigentlich selten zuvor. Da stellt der Finanzminister einer gemeinsamen Regierungskoalition sein Haushaltsgesetz vor und erzählt, wofür über viel Geld ausgeben will und wo er kein Geld oder weniger Geld ausgeben will. Und es klatscht wirklich die Minderheit der Regierungsabgeordneten.

 Ulf
Natürlich sind SPD und Grüne mit diesem Haushalt kreuzunglücklich.

 Philip
Und das war, das war selten so zu sehen. Oft gibt es zumindest ein Pseudo-Applaus. Ja, ja, hier applaudieren wir und dann im Haushaltsausschuss haken wir das alles um. Aber da haben einfach ganz viele nicht applaudiert. Die haben einfach ihre Hände nicht bewegt. Nur die FDP und vielleicht noch ein, zwei andere haben mal geklatscht. Hat man selten gesehen. Das heißt ohne Zug und Schluss in der Ampel kriegst du diesen Deutschland packt nicht aufs Gleis.

 Ulf
Tja, und Scholz wirkt einfach nicht ganz so stark, wie man sich das wünschen würde, dass er tatsächlich die Leute mitreißt. Bislang wirkt er für mich also zumindest als jemand, der quasi den Ernst der Stunde erkannt hat. Ich glaube, er weiß schon: so geht es nicht weiter. Weder mit dem Zoff innerhalb der Ampel, noch mit der der CDU/CSU, die natürlich sich momentan in so einer Oppositionshaltung verhakt, hat insofern hat er da glaube ich, schon die richtige Idee. Aber mir wirkt er auch einfach noch nicht so führungsstark Also ich habe bislang nicht den Eindruck, dass er die Union wirklich mitgerissen hat. Aber wie gesagt, ich hoffe einfach mal, dass das eine Menge zu tun hat mit den Wahlkämpfen in Bayern und Hessen. Noch vier Wochen, dann sind die Landtagswahlen rum. Möglicherweise gelingt es Scholz ja dann, sich mal mit Merz unter vier Augen zu treffen.

 Philip
Aber dann kommen ja im nächsten Jahr schon die nächsten drei Landtagswahlen.

 Ulf
Aber das ist eben das große Problem mit diesen ständigen Wahlkämpfen, diesen ständigen Landtagswahlen. Aber es gibt dann doch zumindest bis zum Jahresende mal so ein Zeitfenster, das er vielleicht nutzen könnte. Ich denke, die diese Rede von Scholz war so ein erster wichtiger Schritt. Dem müssen jetzt aber weitere folgen, insbesondere klare, innerhalb der Ampel abgestimmte Vorschläge, die man dann mit der Union überhaupt diskutieren kann.

 Philip
Denn eins ist klar, und das hat ja Scholz auch unterstrichen und das sieht ja auch Merz, das wissen eigentlich alle. Die Probleme hier im Land sind doch erheblich. Viele davon hat Scholz aufgezählt. Ein ganz zentraler Punkt, über den momentan alle reden, ist die Situation der deutschen Wirtschaft.

 Ulf
Da hat das hatten wir ja auch schon im Habeck Interview angesprochen und hat der Spiegel in dieser Woche eine dicke Titelgeschichte gemacht. So nach dem Motto: Die deutsche Wirtschaft steht am Abgrund. Das Interessante an der aktuellen Situation ist ja, dass sich über diese Krisensymptome eigentlich alle relativ einig sind. Auch Olaf Scholz hat da einen überraschend klaren Blick auf die Lage. Allein welche Diagnose ergibt sich aus diesen Symptomen? Da gehen die Analysen doch dann sehr auseinander, und zwar teilweise auch entlang durchaus überraschender Linien, also insbesondere nicht unbedingt parteipolitischer Linien, auch nicht wirtschaftsnah oder weniger wirtschaftsnah. Und das Problem ist: Wenn die Diagnose nicht klar ist, ist natürlich auch die Therapie umstritten. Aber fangen wir doch mal an, Philip um sich diesem Thema Wirtschaftskrise Ja,  Nein, Vielleicht zu nähern, fangen wir noch mal an mit dem Krisensymptome.

 Philip
Die Krisensymptome. Die deutlichsten lassen sich in ein paar Zahlen festhalten. Jetzt haben führende deutsche Wirtschaftsforschungsinstitute Zahlen veröffentlicht und sie warnen vor einer Rezession, in die Deutschland rein steuern könnte. Da wäre zum einen das ifo Institut, das rechnet für 2023, also für das laufende Jahr mit einem Minus von 0,4 % des Wirtschaftswachstums. Fürs nächste Jahr prognostizieren sie nur noch 1,4 % Wachstum und Ifo.

 Ulf
Immerhin wieder Wachstum.

 Philip
Aber abgesenkt die Prognose und der Konjunkturchef des ifo Instituts, Timo Wollmershäuser, der sagte: Die Abkühlung setzt sich fort. In nahezu allen Branchen steht die Tendenz auf Flaute. Anders als bisher erwartet dürfte die Erholung in der zweiten Jahreshälfte ausbleiben. Daher die Rezession.

 Ulf
Tja, das RWI Leibniz Institut für Wirtschaftsforschung rechnet ebenfalls für 2023 mit einem negativen Wachstum, also mit einer Schrumpfung der deutschen Konjunktur der deutschen Wirtschaft um 0,6 %. Und 2024 hatten sie bislang mit 2 % Wirtschaftswachstum gerechnet. Jetzt haben sie korrigiert auf nur noch 1,1 %, also minimal Wachstum unterhalb der Inflationsrate. Also real bleibt da auch nicht viel über. Und ähnliche Töne kommen vom Kieler Institut für Weltwirtschaft. Die Prognose für '23 wurde von -0,3 auf sogar -null 0,5 % im Vorjahresvergleich gesenkt. Und man kann jetzt nicht sagen und wenn es eine weltweite Situation wäre, aber so ist es ja nicht. Das Wachstum in Deutschland ist eben auch noch signifikant niedriger als in den anderen europäischen Ländern. Insofern kann man schon sagen, die Summe strich darunter, die Zukunftsprognosen sind düster.

 Philip
Vor allen Dingen haben sich wenige Länder so schlecht von Corona erholt wie Deutschland. Der Spiegel hat auch noch mal ein paar Zahlen, also ein paar, wie sagt man s, Symptome aufgelistet: Absatz deutscher Autobauer. Die deutschen Autohersteller produzieren 2022 fast 40 % weniger Fahrzeuge als vor zehn Jahren, dann minus 50 % ausländische Direktinvestitionen in 2022 im Vergleich zu 2021. Auch wenn jetzt natürlich wieder Chiphersteller hier investieren, würde die Regierung anmerken. Aber in der Vergangenheit ist das doch extrem zurückgegangen. Das Geld, was ausländische Firmen und Konzerne hier in Deutschland investieren. Industrieproduktion ist im Juni '23 im Vergleich zum Juni 2019, also zu vor vier Jahren um -7 Prozent zurückgegangen. Also das sind alles Zahlen, die doch darauf hindeuten, dass es substanzielle wirtschaftliche Probleme gibt, natürlich auch getrieben von der schwächelnden Bauwirtschaft.

 Ulf
Ja, das ist vielleicht so der Wirtschaftsbereich, wo die Krise am deutlichsten zu erkennen ist bisher. Die Bauwirtschaft leidet enorm unter den hohen Zinsen, denn es ist völlig klar: Wann muss man sich als Privatperson Geld leihen? Na klar, wenn man ein Haus bauen will oder kaufen will. Das ist so der Moment, wo die meisten Menschen sich Geld leihen von der Bank und ob man da 1 % Zins zahlt wie noch vor zwei Jahren oder ob man da 4,5 % zahlt wie jetzt zu Spitzenzeiten, das macht einen gigantischen Unterschied.

 Philip
Auch für große Konzerne wie Vonovia und so, die ja bis zum Jahresende alles eingestellt haben. Für die sind die Zinsen auch ein Problem.

 Ulf
Und deswegen wirkt sich dieses extrem hohe Zinsniveau trotz der sagen wir mal doch sehr speziellen Gründe für die Inflation einfach sehr schlecht aus, sehr negativ aus auf die Bauwirtschaft. 27 % Einbruch im Vergleich zum Vorjahr nicht irgendwie ein, zwei 3 Prozent - 27! Also das ist schon richtig hart.

 Philip
Baugenehmigungen in dem Fall.

 Ulf
Aber die Baugenehmigungen sind ja die Bauten von morgen. Und das Ampel Ziel von jährlich 400.000 neuen Wohnungen um die gigantische Wohnungsnot insbesondere in deutschen Städten zu beheben, ist natürlich so überhaupt nicht zu schaffen. Und sogar das gewerkschaftsnahe Institut für Makroökonomie und Konjunkturforschung, kurz IMK, rechnet damit, dass 2024 nur rund 177.000 neue Wohnungen fertiggestellt werden. Das sei ein historischer Tiefststand, vergleichbar mit dem Jahr 2009.

 Philip
Ja, der Frankfurter Wirtschaftshistoriker Werner Plumpe, kommt das aus dem Spiegel, das Zitat? Ich glaube schon. Der sagt: Zur Mischung aus Bräsigkeit und Überheblichkeit, die die letzten Merkel Jahre prägte, kommt nun eine Selbstblockade, aus der sich manche Politiker in Wunschdenken flüchteten. Damit kommen wir zu den Ursachen. Also das sind die Symptome, durch was sind denn diese Symptome hervorgerufen?

 Ulf
Da gibt es natürlich eine bunte Mischung von Faktoren, die alle einen gewissen Einfluss haben. Also natürlich gewisse Nachwehen von Corona wird man immer noch feststellen.

 Philip
Lieferketten und solche Sachen.

 Ulf
Das alles hat sich jetzt weitgehend wieder normalisiert, aber eben noch nicht so vollständig. Dann natürlich die russische Invasion in der Ukraine und die in der Folge gestiegenen Energiepreise. Das ist natürlich der zentrale Faktor, der jetzt kurz bis mittelfristig die deutsche Wirtschaft belastet. Niemand weiß, wie lange der Konflikt noch dauert, was da noch genau passiert. Auf jeden Fall ist klar: Die billige, wenn auch natürlich extrem klimaschädliche Energie, nämlich Gas, ist erst mal weggefallen. Dementsprechend sind die Energiepreise gestiegen und das hat unmittelbar eine enorme Inflation ausgelöst.

 Philip
Richtig, RWE, Leibniz Institut Wirtschaftsforschung spricht von beträchtlichen Abwärtsrisiken für die Weltwirtschaft. Das geht also vor allem von China aus, weil dort die Konjunktur auch abflaut. Gleichzeitig bauen die Chinesen immer mehr selbst, was sie vorher in Deutschland einkaufen mussten. Und beides, also Abflauen der Konjunktur in China, wo die Chinesen selber weniger kaufen. Und sie stellen auch gleichzeitig mehr her, was früher aus Deutschland kam, das führt eben dazu, dass die Nachfrage aus China in Deutschland nachlässt. Und das ist für eine Exportnation wie Deutschland, die extrem davon lebt, allen möglichen Krempel in die Welt zu verkaufen, natürlich ein Problem.

 Ulf
Und dazu kommen natürlich die hausgemachten Probleme, die oben auch schon in den Tönen von Olaf Scholz angeklungen sind. Daher hier nur ein paar Stichworte: überbordende Bürokratie, mangelnde Digitalisierung, zu wenig Fachkräfte, alternde Gesellschaft, marode Infrastruktur, Brücken und Bahn und zu schlechte Schulen und ein unterfinanzierten Bildungssystem. Für treue Hörerinnen und Hörer der Lage alles keine Neuigkeiten. So, und diese ganzen Probleme, die werden jetzt insbesondere von Seiten der deutschen Wirtschaft sehr gerne, allerdings auf die Bundesregierung projiziert. Und es wird sehr gerne der Vorwurf erhoben, die wirtschaftlichen Rahmenbedingungen, die die Politik setzt, seien einfach zu schlecht.

 Philip
Ja, und Marcel Fratzscher, Chef vom Deutschen Institut für Wirtschaftsforschung. Der schreibt auch im Tagesspiegel so sinngemäß: Ja, das ist schon alles richtig in Deutschland, da gibt es viele Probleme. Du hast es gesagt von Digitalisierung bis Fachkräfte über alternde Gesellschaft. Er sagt aber, die größere Verantwortung für den Verlust der Wettbewerbsfähigkeit und die drohende Deindustrialisierung liegt jedoch bei den Unternehmen. Die hätten in den letzten 10 bis 15 Jahren einfach richtig Kasse gemacht, seien dabei aber Risiken eingegangen. Große Risiken, die jetzt geplatzt sind, die Wetten, und dafür solle der Staat einstehen.

 Ulf
Das finde ich einen total spannenden Ansatz ehrlich gesagt. Das ist ja so ein ganz klassischer Vorwurf. Die Gewinne werden privatisiert, direkt eingestrichen. Die Risiken werden dann aber gerne wieder auf die Allgemeinheit abgewälzt. Und diese, sagen wir mal generelle These, dass das so eine eine Herangehensweise in der Wirtschaft sei. Diese generelle These, die projiziert Marcel Fratzscher in seinem Beitrag im Tagesspiegel jetzt auf drei Wetten, die, so sein Vorwurf oder seine Analyse nicht aufgegangen seien.

 Philip
Richtig! Das ist zum einen, dass die Industrie die klimatechnische und digitale Transformation verpennt hat, weil sie einfach angenommen oder gewettet haben, dass diese Transformation noch ein paar Jahre warten kann. Oder auch Jahrzehnte. So nach dem Motto:: Jaja, machen wir dann und so kommt beizeiten.

 Ulf
Wenn ich in Rente bin.

 Philip
Müssen wir uns jetzt nicht drum kümmern. Erste Wette definitiv in die Hose gegangen.

 Ulf
Konkretes Beispiel einmal für die erste Wette, dass die deutsche Automobilindustrie so lange die Wende weg vom Verbrenner hin zur Emobilität verpennt hat, dass sie im Grunde erst jetzt seit vielleicht ein, zwei Jahren engagiert anfangen, eAutos auszurollen. Mit der Folge, dass in China inzwischen deutsche Autos zu Zehntausenden auf irgendwelchen Höfen stehen und nicht mehr zu verkaufen sind und stattdessen aber chinesische Autounternehmen ziemlich coole Modelle entwickelt haben, die jetzt den europäischen Markt überfluten. Das muss man einfach sehen, dass das das ist jetzt nicht nur ein abstrakter Vorwurf, Transformation verpennt. Das hat ganz konkrete Folgen. Dass die deutsche Automobilindustrie so dasteht, wie sie dasteht, liegt an diesem Fehler.

 Philip
Zweite Wette, die sie verloren haben, ist die Wette auf billiges Gas aus Russland und immer laufenden umsatzträchtigen Absatz in China. Also diese Abhängigkeit von zwei schwierig regierten Ländern, Russland und China und diese Abhängigkeit speziell vom Gas, argumentiert Fratzscher, die sei nicht vom Staat getrieben worden, sondern von den Unternehmen. Die großen Chemieunternehmen, Gasversorger auch Kommunen hätten dafür lobbyiert. Für so Pipelines wie Nordstream zwei hätten die vorangetrieben, um sich einfach mit billigem Gas mit billiger Energie versorgen zu können. Diese Wette ist mit dem Krieg in der Ukraine auch geplatzt. Und die dritte Abhängigkeit und die dritte Wette, die sie gemacht haben, die kaputt gegangen ist: Sie haben sich auf zu wenige, zu fragile Lieferketten konzentriert und haben verpasst, sich zu diversifizieren.

 Ulf
Das ist eben das ist eben das Risiko, das sie dadurch eingegangen sind, dass sie jeweils den absolut billigsten Markt gewählt haben, als Hersteller von Vorprodukten und eben nicht zwei oder drei Märkte, auch wenn einer der anderen Märkte zwei, drei, 5 % teurer gewesen wäre. Und dann hat man natürlich das, was man so schön ein Klumpenrisiko nennt. Dann brechen mit einem Mal alle möglichen Vorprodukte weg und zwar alle, weil man eben keine mehreren Zulieferer unternehmen. Das ist ein Problem. Und Marcel Fratzscher bringt das auf ein, wie ich finde, schon relativ knackiges Fazit.

 Philip
Er schreibt: Ein Teil der Unternehmen erwartet ein Teil der Unternehmen, dass der Staat sie gegen Risiken absichert, existierende Strukturen zementiert und sie notfalls durch Subventionen stützt. Diese Vollkaskomentalität ist heute die größte Gefahr für die Zukunftsfähigkeit Deutschlands.

 Ulf
Zitatende. Harte Worte. Klar, Marcel Fratzscher hat jetzt sicherlich nicht völlig aus dem Blick verloren, dass auch politische Rahmenbedingungen besser sein könnten. Aber er sieht die Verantwortung eben doch vor allem in Deutschlands Vorstandsetagen. Generell sehr entspannt mit Blick auf die Wirtschaftssituation zeigt sich kein linker Nein, sondern der Bundesbankchef Joachim Nagel im Interview mit dem Handelsblatt.

 Philip
Der lehnt sich relativ relaxt und sagt: Deutschland ist nicht der kranke Mann Europas. Da spielt er so ein bisschen an auf die Berichterstattung des britischen Economist aus den letzten Wochen, die ein ähnliches Bild skizziert haben, wie wir das oben getan haben.

 Ulf
Ein süßes Titelbild übrigens fand ich ganz süß.

 Philip
Mit dem grünen Männchen.

 Ulf
So ein Ampelmännchen am Tropf. Das fand ich schon sehr süß.

 Philip
Also Bundesbankchef Nagel. Deutschland ist nicht der kranke Mann Europas. Ich halte das für eine Fehldiagnose, die bei vielen allzu leicht verfängt. Das Land hat immer wieder seine Anpassungsfähigkeit bewiesen. Wer hätte vor einem Jahr gedacht, dass wir mit der Gasversorgung so gut durch den Winter kommen? Wir erwarten, dass sich das Bild im kommenden Jahr wieder aufhellt. Insbesondere bei Beschäftigung und Schuldentragfähigkeit stehe Deutschland besser da als andere Länder.

 Ulf
Was meint er mit dem letzten Punkt? Wir haben in Deutschland nahezu Vollbeschäftigung, also eine sehr niedrige Arbeitslosigkeit. Und die Menschen, die offiziell arbeitslos gemeldet sind, sind eben in der in der Realität häufig einfach gar nicht arbeitsfähig. Das heißt, wir haben tatsächlich nahezu Vollbeschäftigung. Und was meint er mit Schuldentragfähigkeit? Die Schuldenquote ist in Deutschland extrem niedrig aufgrund der sehr harten Haushaltsdisziplin, insbesondere in den späten GroKo Jahren. Das heißt also, Deutschland ist eben nicht völlig überschuldet und die Bonität von Deutschland als Schuldner steht überhaupt nicht in Frage.

 Philip
Also soweit zu den Symptomen und der Diagnose. Allein wie Deutschland da rauskommen will, ist bisher nicht ganz klar.

 Ulf
Ich meine, dass natürlich die die Konjunktur schwächelt, ist ja alles unbestritten.

 Philip
Und dass es auch viele Probleme gibt es auch unbestritten. Das haben wir oben bei Olaf Scholz gehört. Aber die Frage ist: Welche Strategie verfolgen Sie? Ok, Pakt, maybe. Aber das, was sie dann letztlich aufs Parkett bringen, ist eben widersprüchlich. Also einerseits gibt es den Fachkräftemangel, andererseits beschließt die Regierung aber, jetzt die Vorgängerregierung, eine Rente mit 63, also dass die Leute bei voller Rente einfach früher in Rente gehen können, sprich nicht mehr arbeiten können, sprich den Fachkräftemangel verschärfen. Dann gibt es einerseits die Klimaziele, okay, andererseits subventioniert der deutsche Staat aber weiterhin jedes Jahr klimaschädliche Aktivitäten mit 70 Milliarden €.

 Ulf
Vor allem Auto fahren.

 Philip
Vor allen Dingen Auto fahren und solche Sachen. Und die beste Passage aus dem Spiegel-Titel schreibt dazu:

 Ulf
In den Sozialkassen wird das Geld knapp. Die Regierung zementiert das Rentenniveau. Zu viele Ältere verlassen den Arbeitsmarkt, die Ampel verteidigt den abschlagsfreien Vorruhestand. Viele Frauen sitzen in der Teilzeitfalle. Die Regierung weitet die Minijobs aus. Deutschland plant die größte Transformation der Industriegeschichte. Lindner und Scholz halten es für das Wichtigste, keine neuen Schulden zu machen. Tja, was ist denn jetzt wirklich dran an der Krisenstimmung? Und wenn ja, was sollte die Ampel tun? Um die deutsche Wirtschaft wieder in Schwung zu bringen. Und um das zu klären, haben wir uns mit Professor Dr. Jens Südekum verabredet.

 Philip
Er ist Professor für International Economics, also Internationale Ökonomie, Internationale Wirtschaft an der Heinrich Heine Universität in Düsseldorf. Ganz herzlich willkommen in der Lage der Nation.

 Jens Südekum
Hallo, ich grüße Sie!

 Ulf
Herr Professor Südekum, die wirtschaftlichen Parameter in Deutschland sind ja zurzeit relativ widersprüchlich. Auf der einen Seite haben wir ein Wirtschaftswachstum nahe Null. China kauft weniger bei uns ein, die Exportnation sieht sich bedroht. Und vor allem in der deutschen Presse gibt es überall Wirtschaftskrisenerzählung. Aber das ist ja nur die eine Seite.

 Philip
Die andere ist: Es gibt kaum Arbeitslosigkeit. Die Autokonzerne, auch die Autokonzerne fahren Milliardengewinne ein. Viele andere Firmen auch. Was ist denn nun dran? Steckt die deutsche Wirtschaft in der Krise oder nicht?

 Jens Südekum
Ja, es ist eine sehr unübersichtliche Situation, das stimmt. Und wenn wir eine Krise haben, dann ist die komplett anders als die letzte große Krise, die Deutschland hatte. Also so in den frühen 2000 Jahren, wo dann Kanzler Schröder mit der Agenda 2010 um die Ecke kam. Das war ja so eine Krise, wie man sich vorstellt. Massenarbeitslosigkeit, der Staat hoch verschuldet. Und dann kam ja die Reform. Und jetzt haben wir zumindest auf dem Arbeitsmarkt ja die komplett gegensätzliche Situation, also der Fachkräftemangel. Ich glaube jetzt die aktuellen Zahlen, die momentan herumgeistern, also dass der Internationale Währungsfonds eine Prognose rausgegeben hat, Wirtschaftswachstum für 2023 bei minus 0,5 % und damit so ziemlich auf dem letzten Platz in Europa. Das ist natürlich ein Warnzeichen, aber dafür gibt es natürlich auch plausible Erklärungen, warum wir schlechter dastehen als Spanien zum Beispiel. Das hat zum einen natürlich ganz stark damit zu tun, dass wir einfach viel stärker von russischer Energie abhängig waren als andere Länder. Und da ist ja die wirkliche Krise, da ist ja etwas Neues wirklich passiert. Und das Zweite ist: Wir sind stärker als andere von China abhängig, sowohl von chinesischen Importen und Vorprodukten, aber vor allem auch vom chinesischen Absatzmarkt. Die deutschen Autokonzerne, die drei großen, machen 40 % ihres Umsatzes in China. Und wenn die chinesische Wirtschaft hustet, sage ich mal, dann kriegen alle irgendwie einen Schnupfen. Aber Deutschland kriegt dann eben Grippe. So kann man vielleicht sagen, weil wir viel stärker davon abhängig sind. Das sind, würde ich jetzt mal sagen, kurzfristig die Erklärungen, warum die Wirtschaftsprognose, der Ausblick beim Wachstum so schwach ausschaut. Aber über all dem liegen natürlich strukturelle Probleme, die jetzt aber nicht ganz neu sind und die eher längerfristiger Natur sind. Also insbesondere der Fachkräftemangel. Das ist ja ein Spiegelbild der deutschen Demografie, also der Alterung der Gesellschaft, der auch noch schlimmer werden wird in den kommenden Jahren, der aber nicht neu ist. Das wusste man vor zehn Jahren auch schon, dass das so kommen wird. Und dann die Bürokratie, über die jetzt alle reden. Und jetzt gerade bei den Krisenerzählungen, die jetzt überall in der Presse stehen, da wird ja jetzt quasi gesagt: Ja, die Bürokratie ist schuld. Aber die Bürokratie hat sich jetzt in den letzten zehn Jahren auch nicht groß verändert. Sie ist jetzt an einigen Stellen vielleicht sogar besser geworden, weniger schlimm geworden. Und deswegen glaube ich, das ist gerade der Grat, auf dem wir da wandern, dass wir eigentlich viel stärker mit strukturellen Problemen zu tun haben, nicht mit unmittelbaren, akuten Krisen. Deswegen brauchen wir auch kein Konjunkturprogramm. Aber wir werden eben zusätzlich belastet, einfach durch diese eintrübenden Faktoren auf die Konjunktur, die eben stark von außen kommen. Stichwort China, Stichwort Energieabhängigkeit von Russland und Energiepreise.

 Philip
Ja, also in ähnlicher Weise, wenn ich das richtig verstehe, hat eine ähnliche Erzählung oder ähnlichen Blick auf die Lage Ihr Kollege David Kohl, der Chefvolkswirt bei der Privatbank Julius Bär, der sagt im Kern: Also Krise gibt es eigentlich nicht so richtig, sondern es gibt eigentlich eher strukturelle Probleme, aber vor allem bei den Unternehmen. Im Deutschlandfunk sagte er.

 David Kohl
Es sind Probleme im Unternehmensbereich und nach unserer Einschätzung hauptsächlich Probleme, nicht weil man ineffizient oder weil man zu hohe Kostenbelastung über den Arbeitsmarkt hat oder bei den Energiepreisen, sondern weil man eben zu langsam ist, um sich an die neuen Herausforderungen anzupassen. Und da könnte man natürlich von der Politik mehr tun.

 Philip
Und da ist jetzt natürlich die riesen Diskussion: Soll es jetzt Subventionen geben für die Industrie? Oder muss man einfach sagen: Na, ihr seid so langsam beim Wandel, das müsst ihr jetzt einfach mal hinkriegen? Die hohen Energiepreise sind die hohen Energiepreise, der Arbeitskräftemarkt ist der Arbeitskräftemarkt. Ihr müsst euch dran anpassen. Wo stehen Sie?

 Jens Südekum
Also jetzt eine pauschale Schelte, dass alle deutschen Unternehmen zu langsam und zu unflexibel sind. Das würde ich jetzt so nicht unterschreiben. Natürlich gibt es einzelne Bereiche, wo man da sicherlich so argumentieren kann. Also man kann sich ja schon fragen, warum hat die Automobilindustrie die Trends, die momentan so durchschlagen, warum hat sie die nicht schon viel früher erkannt? Also warum hat sie in den Jahren, wo es ihr super ging, wo sie super Exportgeschäfte insbesondere gemacht hat, warum hat sie da nicht schon verstanden, dass dieses Geschäftsmodell mit Verbrennern ans Ende kommt irgendwann des Lebenszyklus? Und darüber nachgedacht, was kommt danach? Warum muss erst Tesla kommen, um quasi klar zu machen, wohin die Reise geht mit der Elektromobilität? Das sind aber so ein bisschen die Probleme in der Vergangenheit. Ich glaube, mittlerweile haben das die deutschen Autokonzerne auch verstanden und sind jetzt eben auch wirklich dabei, sich rapide zu wandeln und hoffentlich toi toi toi, auch wirklich wieder nach vorne zu kommen in ihrem Geschäftsfeld. In anderen Bereichen, also bei mangelndem Wandel würde ich sagen vor allem kleine und mittelständische Unternehmen tun viel zu wenig im Bereich Digitalisierung. Da hat der Kollege recht. Da gibt es auch handfeste Daten dazu, dass der deutsche Kapitalstock insgesamt überaltert ist, also weniger modern, weniger zeitgemäß als in anderen Ländern. Und dass insbesondere hat das damit zu tun, dass einfach digitale Technologien in der Breite bei weitem noch nicht so stark eingesetzt sind und Unternehmen eben auch ihre Daten, die im Produktionsprozess anfallen, nicht effektiv nutzen. Insofern ist das schon so gesehen ein Problem, wo die Unternehmen erst mal ihre Hausaufgaben machen müssen. Bei den Energiepreisen, das ist jetzt so noch mal ein etwas spezieller Bereich. Also dafür konnte ja nun die deutsche Industrie so nichts. Also durch jetzt einfach die Krisenfolgen, die ja vor allem und hauptsächlich durch den Kriegsausbruch eben angefallen sind. Und die Konstellationen haben sich dadurch natürlich extrem verschlechtert. Also gerade jetzt, um eine Zahl zu nennen, nehmen wir mal den Strompreis. Vor der Krise hat die mittelständische Industrie ungefähr 0,18 € für eine Kilowattstunde Strom bezahlt. Inklusive aller Steuern und Umlagen. Und dann ist das im Jahr 2022 durch die Decke geschossen auf 0,53 €. Und das ist natürlich etwas. Da stehen erstmal die Räder still und viele Geschäftsmodelle haben sich einfach nicht mehr gerechnet.

 Philip
Also nur zur Unterbrechung: der Spiegel schreibt von 0,26 € Industriestrompreis im zweiten Halbjahr '22.

 Jens Südekum
0,26 € haben wir jetzt aktuell. Also die 0,53, die ich gerade besprochen habe. Das war sozusagen zum Hochpunkt der Krise im Jahr 2022.

 Philip
Aber der Strompreis ist wieder gesunken.

 Jens Südekum
Er ist wieder gesunken. Aber 26, das ist noch nicht bei 18, aber wir haben jetzt eben für die energieintensive Industrie schon eine spezielle Lage, weil die sehen, okay, wir sind noch nicht ganz wieder auf dem Niveau von vor der Krise. Zugleich sehen Sie aber andere Standorte, andere Länder haben erstens günstigere Energiepreise sowieso schon immer gehabt, jetzt insbesondere etwa die USA, die ja jetzt vom Krieg Russland Ukraine nicht so stark betroffen waren und die aber zudem neben den günstigeren Energiepreisen jetzt auch noch eine dezidierte industriepolitische Strategie auf den Tisch gelegt haben und eben im großen Stil noch zusätzliche Subventionen anbieten. Das heißt also jetzt bestimmte Branchen in der Industrie, gerade in energieintensiven Zukunftsbranchen wie Wasserstoff oder Batteriezellenfertigung. Da hat der Standort Deutschland gerade eben wirklich ein handfestes Problem, weil eben andere Länder günstigere Energiepreise, günstige Standortbedingungen plus zusätzliche Subventionen anbieten. Und das würde ich sagen, ist eine ganz aktuelle Entwicklung. Darauf müssen wir auch eine Antwort finden. Und da kommen eben diese Subventionen, Stichwort der Industriestrompreis, der kommt da eben ins Spiel.

 Ulf
Die Ampel hat sich ja nun zähneknirschend sage ich mal auf ein so genanntes Wachstumschancengesetz geeinigt, insbesondere auf Betreiben der Freien Demokraten. Ob das tatsächlich kommt, ist unklar. Liegt jetzt erst mal im Bundestag. Auch im Bundesrat deutet sich schon eine ziemlich harte Oppositionsfront an. Aber nehmen wir doch mal die Pläne, die zurzeit aus dem Hause von Christian Lindner auf dem Tisch liegen. Das ist ja ein ganzes Maßnahmenbündel mit ganz vielen einzelnen Ideen, wie Unternehmen entlastet werden sollen. Welche Maßnahmen aus diesem Plan von Christian Lindner erscheinen Ihnen denn sinnvoll oder welche zum Beispiel sind vielleicht auch weniger sinnvoll und verbrennen nur Steuergelder?

 Jens Südekum
Ja, dieses Wachstumschancengesetz ist ein Sammelsurium von an die 50 Einzelmaßnahmen. Davon sind einige wirklich finde ich sehr sehr gut.

 Philip
Welche?

 Jens Südekum
Die sogenannte Investitionsprämie finde ich sehr gut. Also Unternehmen, die Investitionen im Bereich Energieeffizienz machen, bekommen bis zu 15 % der Investitionssumme als Steuergutschrift praktisch erstattet vom Staat. Das heißt, das ist eine effektive Entlastung. Es ist wie eine Steuersenkung, kann man sagen, aber eben nicht mit der Gießkanne Steuersenkung für alle, sondern eine Steuersenkung ausschließlich für Unternehmen, die eben auch wirklich investieren. Und das finde ich sehr gut, weil diese Problematik mit dem überalterten Kapitalstock und der mangelnden Modernität der deutschen Wirtschaft die kann man ja nur durch private Investitionen irgendwie heilen. Und deswegen braucht man eben Programme, die wirklich Investitionen anreizen. Und da würde ich sagen, ist das Programm gut.

 Philip
Okay, was noch?

 Jens Südekum
Steuerliche Forschungs- und Entwicklungsförderung finde ich sehr gut. Also so etwas wie bei Biontech oder große Zukunftsprojekte forschen daran, dass die steuerlich gefördert wird. Das ist sozusagen mein zweiter Liebling. Und dann geht es aber schon los. Dann haben wir so viele Maßnahmen, die irgendwie ähnlich sind, aber die ich nicht für so besonders zielgenau halte. Also zum Beispiel das Thema Verlustrücktrag, also dass Unternehmen, die jetzt in den Krisenjahren Verluste gehabt haben, dass sie die jetzt verrechnen dürfen mit Gewinnen, die sie jetzt momentan machen oder die sie in der Zukunft machen können, das ist okay. Das ist auch eine steuerliche Entlastung, aber die ist eben nicht maßgeschneidert auf Investitionen, die kriegt jeder Mittelständler, jedes Unternehmen, ganz egal ob er nun investiert oder nicht. Und das finde ich wenig zielgenau. Und in dieselbe Richtung gehen ein paar andere Maßnahmen. Die sind dann sehr komplex und technisch. Thesaurierungsbegünstigung ist eine dieser 50 Maßnahmen. Das ist eben das Problem. Das ist schon alles okay. Aber das hat eben nicht wie die Investitionsprämie diese ganz starke Fokussierung: Es gibt Entlastung, aber nur dann, wenn auch tatsächlich investiert wird.

 Philip
Diese Maßnahmen, die Sie jetzt geschildert haben und dieses Gesetz, wenn es denn so kommt, das ist ja alles noch ein bisschen mit einem Fragezeichen versehen, hat Ulf gesagt. Da sagen ja viele Ja, das geht schon in die richtige Richtung. Könnte noch zielgenauer sein. Aber interessant ist ja auch, dass die finanziert werden sollen in erster Linie dadurch, dass an anderer Stelle Investitionen gestrichen werden und gekürzt werden. Und da gibt es die Kritik, dass viele sagen: Na ja, solche Investitionen von Staatsgeld möchte ich mal sagen, die haben ja einen Hebel. Das heißt, für einen staatlich investierten Euro werden mehr als einer, 2, 3, 4 in Euro angereizt durch private Investitionen. Und nun ist es so: Wenn wir, so die Idee, wenn man das sagen Kritiker, wenn dieses Gesetz jetzt finanziert wird, indem quasi Investitionen staatlicherseits gekürzt werden, dann könnte sich quasi das Gesetz selber konterkarieren. Ja, wir schieben vielleicht die Wirtschaft ein bisschen an, so das denn klappt. Aber weil wir da staatliche Investitionen streichen und somit dann auch dieser Hebel von mehr privaten Investitionen wegfällt, konterkariert sich das Ganze und das wird ein Nullsummenspiel. Das treibt die Wirtschaft ein bisschen an, aber weil das Ganze mit weniger Investitionen bezahlt wird, kommt dann doch alles am Ende bei Null raus. Wie sehen Sie das?

 Jens Südekum
Das ist schon richtig. Das Wachstumschancengesetz ist aus meiner Sicht sowieso erst mal von vornherein zu klein vom Volumen. Es hat ja ungefähr so einen Rahmen von 7 Milliarden diese Entlastungen. Ich glaube, wir hätten das Vierfache bis fünffache gebraucht.

 Philip
Oder Herr Lindner würde sagen, in den nächsten Jahren sollen es ja über 20 Milliarden werden. Soll er sich auf 30 Milliarden...

 Jens Südekum
Jetzt gehts es erstmal um die Haushaltsauswirkungen die berechnet sind für ein Jahr und da kommt man ja laut den Berechnungen auf diese 7 Milliarden und das halte ich für zu wenig. Es gibt so Berechnungen, wie viel zusätzliche Investitionen bräuchten wir denn in der Privatwirtschaft bis 2030, um realistischerweise die Transformation, die Klimaziele zu erreichen und die Modernisierung des Kapitalstocks zu erreichen? Und da sind wir bei viel, viel größeren Summen. Deswegen ist die erste Geschichte: Das Volumen ist aus meiner Sicht zu klein. Und dann kommt das, was Sie gerade gesagt haben. Dann ist es so gesehen noch gegenfinanziert durch andere Steuererhöhungen, zum Beispiel Mehrwertsteuer, Gas kommt zurück und ein paar andere Sachen und Kürzungen an anderer Stelle. Und dadurch ist der gesamtwirtschaftliche Effekt tatsächlich ein Stück weit wieder konterkariert. Also aus meiner Sicht hätte man es anders machen sollen von vornherein größer anlegen sollen und finanzieren sollen aus dem Wirtschaftstabilisierungsfonds. Da liegen ja 150 Milliarden ungenutzte Kreditermächtigungen, die aus dem sogenannten Doppelwumms Programm kamen, das letztes Jahr aufgelegt wurde, um einfach die Energiekrise zu bekämpfen. Da ist noch sehr viel Geld über, weil die Energiepreise eben schon wieder stark gefallen sind. Und ich glaube, dieses Geld wäre gut angelegt, wenn man es jetzt eben nutzt für mittelfristige Investitionen, um eben die strukturellen Probleme, über die wir gesprochen haben, in den Griff zu kriegen. Also endlich eine echte Investitions Agenda zu machen, die auch nicht nur so ein bisschen in die richtige Richtung geht, sondern die wirklich auch mal ein richtiges Wort ist, wo richtig auch Geld auf den Tisch gelegt wird, so wie es andere Länder, etwa die USA ja auch machen. Das wäre aus meiner Sicht der richtige Weg gewesen.

 Ulf
Sie haben das Stichwort USA schon angesprochen. Die USA wählen ja unter Joe Biden mit dem sogenannten Inflation Reduction Act einen völlig anderen Weg. Sie haben die Unternehmenssteuern sogar ein bisschen erhöht. Sie zahlen aber riesige Subventionen, und zwar kreditfinanziert, sofern Unternehmen in Zukunftstechnologien investieren, insbesondere zum Klimaschutz. Das ist also ganz klassisches Schuldenmachen in der Krise. Deficit spending und die Daten jedenfalls scheinen Joe Biden recht zu geben. Jedenfalls wächst das Bruttoinlandsprodukt in den Vereinigten Staaten weitaus schneller als in Deutschland. Das heißt, wir sehen da sogar schon einen ersten Konjunktureffekt. Wäre das aus einer ökonomischen Perspektive auch für Deutschland der klügere Weg?

 Jens Südekum
Ich glaube, wir können sehr viel von Bidenomics, wie es gerade praktiziert wird, lernen. Ich glaube, Deutschland sollte tatsächlich stärker in diese Richtung gehen. Teilweise ist es passiert. Diese Investitionsprämie im Wachstumschancengesetz, die hat durchaus Ähnlichkeiten mit den Taxcredits vom Inflation Reduction Act. Die funktionieren durchaus ähnlich. Insofern das ist schon mal gut. Dann ist aber natürlich das Volumen. Also in den USA reden wir jetzt eben nach aktuellen Projektionen über ein Programm mit einer Größenordnung von 1,2 Billionen $, insbesondere Ansiedlungsanreize für neue grüne Technologien. Und das Wachstumschancengesetz geht so ein bisschen in die ähnliche Richtung. Aber wir kontern dann eben mit einem Programm von 7 Milliarden. Also Wir versuchen sozusagen mit der Wasserpistole gegen Godzilla anzutreten. Und das verstehe ich wirklich nicht. Also wir sind in einer kritischen Phase. Es werden jetzt in vielen dieser Zukunftsfelder jetzt auch die Felder verteilt. Wer wird dort die neue Technologie beherrschen? Wer wird sozusagen der Weltmarktführer werden? Und in vielen dieser Technologien war eigentlich Deutschland in einer guten Position. Aber meine Befürchtung ist ist, dass wir da diese Position verlieren und viele dieser Geschäftsmodelle auch durch diese Subventionen am Ende in die USA abwandern. Und ich glaube nicht, dass das eine gute Entwicklung ist.

 Philip
Ich habe noch eine Nachfrage zu diesen Subventionen. Also wir haben uns jetzt sie haben die positiven Seiten in den USA beschrieben. Kritiker hierzulande sagen Ja. Na ja, wenn wir jetzt an der falschen Stelle diese Unternehmen, diese alten Unternehmen subventionieren, dann verhindern wir, dass die sich wandeln. Dann nehmen wir den Druck runter, dass die sich einfach an diese neuen Bedingungen anpassen. Industrie, Strompreis, sie sind dafür. Kritiker sagen, Wenn wir diesen Strompreis künstlich senken, dann verhindern wir, dass der Druck auf diese Unternehmen so groß ist, Energie zu sparen und sich an eine neue, klimaneutrale Wirtschaft anzupassen. Wo Sie sagen, sind Subventionen sinnvoll, wenn das Ziel denn ist Wandel der Industrie hin zu einer klimaneutralen Wirtschaft, wo müsste das gezielt eingesetzt werden? Was wären die Kriterien?

 Jens Südekum
Ich glaube, viele der Kritikpunkte, die geäußert werden, sind oftmals Missverständnisse. Wenn man so ein bisschen hört Aha, Subventionen. Und dann ist so ein Reflex, da sollen quasi alte Strukturen konserviert werden. So ein bisschen, wie es vielleicht mal früher im Ruhrgebiet mit Kohle und Stahl mal war und man gesagt hat: Wir geben euch Geld, damit ihr hier weiter noch Kohle abbaut, obwohl jeder wusste, dass das nicht mehr wettbewerbsfähig ist. Aber die Subventionen, über die wir jetzt reden, die sind ja gerade dazu da, Transformation zu unterstützen. Also einen kompletten Wandel, ein kompletten Wandel des Geschäftsmodells. Also zum Beispiel weg von konventioneller Stahlproduktion, hin zu grüner Stahlproduktion oder in der Kunststoff- und Plastikbranche, weg von fossilen Brennstoffen und eine Elektrifizierung hin zu Strom basierten Verfahren. Das heißt, da bleibt kein Stein auf dem anderen. Das ist ein kompletter Wandel der Produktionsprozesse und der Geschäftsmodelle. Und der wird sowieso stattfinden. Also das wird sowieso passieren. Die Frage ist also quasi: Wird es hier passieren? Und die Subventionen, um die es jetzt hier geht, die versuchen eben bloß zu beeinflussen, dass diese Investitionen, dass diese Transformation, die aus meiner Sicht wie gesagt, ohnehin kommen wird, dass die auch hier am Standort passiert. Und deswegen ist dieser Industriestrompreis so wichtig. Wenn wir jetzt eben sagen, wir bieten der energieintensiven Industrie sichere Konditionen für die nächsten 5 bis 10 Jahre, also fünf oder sechs Cent. Diese Planungssicherheit, die beeinflusst dann Investitionsrechnungen. In dem Moment, wenn der Strompreis sicher ist, können Unternehmen auch sagen: Gut, dann mache ich das jetzt. Dann elektrifiziere ich meinen Produktionsprozess, und zwar hier in Deutschland. Wenn Unsicherheit besteht, wenn es die Subventionen nicht gibt in Deutschland, dann werden die Unternehmen wahrscheinlich trotzdem diese Investitionen machen, aber eben anderswo. Und das können wir aus meiner Sicht nicht wollen. Deswegen sind diese Subventionen wichtig. Aber noch mal: Die Subventionen, über die wir reden, sind nicht strukturkonservativ, sondern sie sind geradezu transformationsbeschleunigend, nur eben in dem Sinne, dass es hier passiert und nicht irgendwo anders auf der Welt.

 Ulf
Ja, ich hätte noch eine Frage zu den 150 Milliarden, die Sie eben schon angesprochen haben, die es ja bereits gibt an Kreditermächtigungen, die also die Ampelkoalition relativ einfach ausgeben könnte, tatsächlich für ein Konjunkturprogramm, vielleicht sogar für einen über einige Jahre gestrecktes Konjunkturprogramm. Was wären denn aus Ihrer Sicht die besten Hebel? 150 Milliarden sind immer noch weit entfernt von den Summen, die Joe Biden ins Spiel gebracht hat. Aber immerhin was ganz anderes als 7 Milliarden. Wo würden Sie denn ansetzen, um dieses Geld möglichst konjunkturwirksam und im Interesse einer Beschleunigung des Umbaus der deutschen Industrie einzusetzen?

 Jens Südekum
Also erst mal möchte ich sagen, der Begriff Konjunkturprogramm, den finde ich da nicht passend. Unter Konjunkturprogramm stelle ich mir vor, wir machen jetzt einen großen Stimulus für den privaten Konsum. Wir senken die Mehrwertsteuer. Oder wir machen eine Abwrackprämie für Autos und wollen den privaten Konsum anschieben. Darum geht es nicht, der private Konsum ist nicht unser Problem. Der wird sich, glaube ich, in diesem und im kommenden Jahr sowieso wieder relativ gut entwickeln, weil jetzt auch die Löhne allmählich angezogen haben. Das, worum es geht, ist wirklich die Investition, also ein anderes Nachfrage Aggregat. Die Investitionen, da ist unser Problem. Und deswegen würde ich sagen, sollten wir diese 150 Milliarden, die eben "übrig" sind im Wirtschaftstabilisierungsfonds, nutzen, eben für erstens den Industriestrompreis, zweitens für das Wachstumschancengesetz, und zwar für die guten Elemente aus den Wachstumschancengesetz, also insbesondere die Investitionsprämien und die steuerliche Forschungs- und Entwicklungsarbeit. Die würde ich nehmen und um den Faktor 4 bis 5 vergrößern. Und dann, wenn noch was über ist, würde ich sagen, sollten wir noch mal richtig in Bildung investieren, weil das ist langfristig sowieso das wichtigste Thema, gerade für Deutschland. Dann werden diese 150 Milliarden aus meiner Sicht insgesamt ganz gut angelegt.

 Philip
Ich habe noch eine letzte Frage, wie es immer so ist in so einem Gespräch. Ihr Kollege, Herr Schularik, neuer Chef des Kieler Instituts für Weltwirtschaft, hat im Spiegel sinngemäß gesagt: Die Deutschen haben Schiss. Dieser ganze Wandel, der geht nicht so schnell, der geht nicht so nachhaltig, weil die Deutschen Angst haben vor dem Wandel, weil sie nur darauf gucken, was sie verlieren und nicht darauf gucken, was sie gewinnen. Und ihnen erzählt auch keiner, was sie gewinnen. Wie wichtig halten Sie diese Mentalitätsfrage?

 Jens Südekum
Also das ist mir ein bisschen zu pauschal. Also das mag sicherlich für viele zutreffen.

 Philip
Ich hab das paraphrasiert, ja nicht gesagt haben Schiss, aber wir haben so was Angsthasen, Kultur.

 Jens Südekum
Ich habe es auch gelesen. Also erstmal spricht Herr Schularik davon, mit diesen Subventionen wolle man alte Strukturen konservieren. Aber ich habe ja nun gerade erklärt, dass es darum gerade nicht geht. Dann ist es natürlich dieser Heulgesang über die Bürokratie, der da zu lesen ist. Und dem stimme ich ja zu. Also mich nerven diese überbürokratischen Prozesse auch, uns alle nerven die! Und natürlich müssen wir das machen. Aber dass jetzt niemand darüber redet und dass niemand hören will, das ist ja nun nachweislich nicht so, wir reden ja kaum noch über was anderes. Und auch die Bundesregierung hat sich ja dieses Thema Entbürokratisierung sehr stark auf die Fahnen geschrieben, gerade auch die FDP. Und das finde ich auch richtig. Und es geht ja jetzt auch nicht darum, einfach mehr Geld auf dieselben Prozesse zu kippen und zu hoffen, dass dann was Gutes bei rauskommt. Wir brauchen beides, wir brauchen mehr Geld, also meinetwegen 150 Milliarden aus dem Wirtschaftstabilisierungsfonds und müssen gleichzeitig viel schneller und schlanker in der Bürokratie werden. In allen Bereichen. Genehmigungsverfahren bei der Fachkräfteeinwanderung ganz wichtig und in vielen anderen Bereichen. Aber jetzt eben zu sagen, die Deutschen wollen das alles nicht hören und sind ein bisschen bräsig und wollen am liebsten so weitermachen mit ihrer überbordenden Bürokratie. Ich glaube, das trifft die Realität auch jetzt nicht mehr.

 Ulf
Na ja, ich glaube, ich glaube, da haben wir jetzt die Aussagen von Herrn Schularik so ein bisschen verkürzt. Denn es geht ja nicht nur um die Bürokratie. Es geht ja zum Beispiel auch darum, sich in seinem Privatleben so ein bisschen umzustellen. Denken wir an den mitunter fanatisch anmutenden Widerstand gegen das Gebäudeenergiegesetz. Also ich glaube, er hatte schon auch so eine gewisse Veränderungsresistenz der Menschen überhaupt im Blick. Oder die Frage: Ersetze ich jetzt meinen lieb gewonnenen Diesel gegen ein eAuto? Da gibt es natürlich auch noch teilweise praktische Probleme, je nachdem was man für ein Fahrprofil hat. Aber für die allermeisten Menschen wäre eMobilität eine echte Option. Trotzdem wissen wir alle, wie viel Zurückhaltung es da noch gibt. Ich glaube, da wollte ich jedenfalls auch drauf hinweisen. Und was halten Sie denn von dieser Diagnose?

 Jens Südekum
Ja, wenn man es so auffasst, dann stimme ich ihm schon wieder eher zu. Also es mag im politischen Raum so ein bisschen das Bedürfnis geben für so eine Erzählung: Ach, diese Transformation, das passiert einfach so und ihr müsst eigentlich gar nichts machen und ihr habt auch keine Einbußen. Für euch ändert sich eigentlich nichts. Das organisieren wir alles in der Politik. Das wird so nicht funktionieren. Da muss man schon ehrlich sein, dass diese Transformation natürlich alle irgendwo betreffen wird. Und es geht aus meiner Sicht jetzt eben darum, nicht nur negativ, sondern auch positiv betreffen kann. Weil wenn jetzt dieses industriepolitische Projekt, von dem ich gerade sprach, wenn das so ausgeht, also wenn jetzt gerade die neuen Geschäftsmodelle wirklich auch weiterhin ihren Standort in Deutschland haben, dann wäre das ja etwas, was mit diesem Wirtschaftsmodell, mit diesen Branchen auch richtig Geld verdient werden kann, auch gerade durch Export in andere Länder. Und so eine Geschichte, die wird mir auch noch zu wenig erzählt, dass man sagt, wir müssen diese Transformation machen. Aber nicht nur, um irgendwie die Klimaziele zu erreichen, auf die wir uns mal verpflichtet haben, sondern vor allem auch, damit wir an der Spitze bleiben bei der industriellen Wertschöpfung. Wenn wir das nicht machen, dann ist nichts mit grünem Wirtschaftswachstum. Also wenn wir einfach bräsig sozusagen so weitermachen mit dem alten Stiefel, dann wird Deutschland wirklich auf den absteigenden Ast gehen, weil diese Geschäftsmodelle werden dann einfach anderswo kommen und Deutschland wird keine Rolle mehr spielen. Ich glaube, diese Geschichte müsste man noch mal anders erzählen, dass es hier wirklich gerade bei diesen Transformationsfragen nicht um softe grüne Themen und Klimaziele geht, sondern auch ganz knallhart, ob der Wirtschaftsstandort Deutschland so erfolgreich bleiben wird, wie er mal war.

 Ulf
Ganz herzlichen Dank, dass wir im Gespräch mit der Lage der Nation Professor Dr. Jens Südekum, Professor for International Economics an der Heinrich Heine Uni in Düsseldorf. Ganz herzlichen Dank, Professor Südekum.

 Jens Südekum
Vielen, vielen Dank.

 Philip
Ja, soweit Jens Südekum. Also, wir haben ja so ein bisschen jetzt wie sagt man nicht zum guten Brauch gemacht. Aber ich fand es ganz interessant, sich nach solchen Interviews noch mal zurückzulehnen und zu sagen: Was haben wir denn jetzt gelernt? Was haben wir denn so mitgenommen? Also feststeht: Der Bundeskanzler analysiert viele Probleme zutreffend, finden wir gut. Realitätscheck Positiv ist immer eine gute Basis, um richtige Maßnahmen zu machen.

 Ulf
Tja, doch, es gibt eine riesige Leerstelle in seinem Angebot an die Union für einen Deutschland Pakt. Ja, Bürokratieabbau ist wichtig. Ja, Digitalisierung ist ein zentraler Faktor. Aber, ihr habt es eben gehört, Professor Südekum fordert und da steht er mehr oder weniger stellvertretend für seine Disziplin, massive und vor allem zielgerichtete Investitionen in die Transformation der deutschen Wirtschaft. So nach dem Beispiel des Inflation Reduction Acts von Joe Biden. Phillip, und dazu enthielt die Rede des Kanzlers kein Wort.

 Philip
Ich habe sie extra noch mal vollständig angehört, um zu horchen. Okay. Anerkennung der Realität. Problembeschreibung Gut, aber ich habe es oben gesagt. Letztlich kam da wenig Neues. 150 Milliarden an Kreditermächtigung stehen der Bundesregierung zur Verfügung. Die sind genehmigt, um Industrie und Verbraucher vor zu hohen Energiepreisen zu schützen. Ebenso sinnvoll lassen sie sich für Modernisierungsoffensiven einsetzen. Das stünde zur Verfügung. Dazu gab's aber nichts. Außerdem stehen 70 Milliarden klimaschädliche Subventionen in den Büchern. Haben wir oben auch schon gesagt. Die könnten zumindest schrittweise abgebaut werden. Man kann das ja nicht immer alles sofort streichen, aber zumindest müsste mal rangegangen werden, um sie schrittweise abzubauen, sodass der Anreiz einfach da ist, um CO2 zu vermeiden und dass der Staat das nicht noch stützt. Also quasi nicht subventionieren, dass die Leute CO2 rein pusten, sondern im Gegenteil das Geld einsparen und wirklich zielgerichtet investieren. Das hat ja Südekum auch gesagt: Zielgerichtet, nicht einfach mit der Gießkanne, sondern zielgerichtet dort investieren, wo es dem Klimaschutz und auch der zukünftigen Wettbewerbsfähigkeit der Industrie nutzt.

 Ulf
Das fand ich ehrlich gesagt so fast den spannendsten Punkt. Das ist jetzt für Lage-Hörerinnen und Hörer auch keine Neuigkeit. Wir haben das schon immer mal wieder gesagt, aber jetzt schon lange nicht mehr. Und ich fand es toll, dass jetzt aus seinem Munde noch mal zu hören. Es geht eben ja nicht nur um CO2 Einsparung bei dieser ganzen Transformation der Wirtschaft. Es geht ja auch darum, zukunftsfähige Branchen aufzubauen. Es geht ja auch darum, einfach neue Wirtschaftszweige zu erschließen, wenn eben wenn es eben keine Verbrenner mehr geben wird in ein paar Jahren, dann muss ja irgendwas anderes in der deutschen Wirtschaft passieren, damit die Leute weiter Arbeit haben und weiterhin Mehrwert erwirtschaftet wird. Und da würde ich schon sagen, da weist Scholz Plan Stand heute eine große Leerstelle auf. Ja, Olaf Scholz weiß natürlich, dass die FDP und auch die Union jedenfalls im Grundsatz überhaupt keine Lust haben, Geld auszugeben. Die FDP ist da dogmatisch, Aber auch die Union hat sich viele, viele Jahre an die sogenannte schwarze Null geklammert, steht wie ein Mann hinter der Schuldenbremse. Aber man muss auf der anderen Seite sehen: Aus einer ökonomischen Perspektive bleibt jeder Pakt Stückwerk, wo zwar irgendwie keine Ahnung Bürokratie abgebaut wird und paar Glasfaserleitungen gezogen werden, aber es ist an staatlichen Investitionshilfen an einem staatlichen Konjunkturprogramm fehlt, so bleibt jeder Pakt irgendwie Stückwerk. Und ich persönlich finde, dass ist natürlich konfliktträchtig. Aber Scholz ist mir persönlich hier an der Stelle zu mutlos. Er antizipiert im Grunde den Widerspruch von Union und FDP und kämpft gar nicht erst.

 Philip
Ja, und er müsste, weißt du, um so einen Pakt loszutreten, um so eine Dynamik zu entfalten, müsstest du vorangehen, so wie er das bei der Zeitenwende gemacht hat. Da hat er gesagt: Wir als Ampel investieren 100 Milliarden in die Bundeswehr. Ja, da war die Union da mit dabei. Du musst ja vorgehen. Du kannst ja nicht sagen Hey, komm, lass uns alle mal sehen. Du bist an der Regierung, du bist gewählt, du machst den Haushalt, du stellst Programme auf, du setzt Prioritäten. Du sagst Schattenhaushalt Ja. Nein. Wie hoch? Also, es ist jetzt ja nicht so, dass er völlig machtlos wäre. Und er müsste diese Macht nutzen, um Akzente zu setzen. Prioritäten setzen. Der muss ja nicht in jedem Bereich auf einmal eine Bombe zünden. Das reicht, wenn er in zwei, mit der Zeit, wenn er hat das bei der Bundeswehr getan und es war ein neuer weiter. Wenn der das in einem Bereich macht, in der Bildung, bei der Transformation einmal so eine Bombe zündet, wo er vorangeht, dann würde ich denken, kann so ein Paket auch in Bewegung kommen, so glaube ich, ist das eine Totgeburt.

 Ulf
Wir kommen zu unseren Hausmitteilungen, die haben wir jetzt hier mal so in die Mitte der Sendung verschoben, Aber wir wollen sie auch nicht ausfallen lassen, denn so ein ganz bisschen ist ja doch immer zu sagen, was so hinter den Kulissen passiert. Diese Woche zum Beispiel hatten wir großen Spaß bei unserem Lagefeuer.

 Philip
Mein Sohn hat mich auch immer gefragt: Und dann habt ihr dann Feuer gemacht?

 Ulf
Nein.

 Philip
Und das heißt warum dann Lagefeuer?

 Ulf
Na ist halt gemütlich. Die Idee war halt, wir setzen uns mal mit unseren Freundinnen und Freunden, die uns mit einem Plusabo unterstützen, in den Kreis ums Feuer und schnacken mal so ein bisschen. Und das haben wir halt in virtueller Weise gemacht diese Woche. Und ich muss ganz ehrlich sagen, mir hat das großen Spaß gemacht. Ein paar hundert Leute waren dabei.

 Philip
War cool. Und wenn wir noch mal Danke sagen können so für den Support, weil das ja auch enorm wichtig ist, haben wir ja auch schon x mal erzählt. Und wenn ihr die Lage gut findet und wenn ihr die Lage unterstützen wollt, dann könnte natürlich einerseits ein Plusabo klicken unter plus.LagederNation.org. Wir sind natürlich sehr danbar. Aber ihr könnt auch einfach die frohe Kunde verbreiten. Ihr könnt einfach Freunden, Familienmitgliedern erzählen, dass es die Lage gibt und dass man da sich ein bisschen informieren kann.

 Ulf
Kolleginnen und Kollegen.

 Philip
Kolleginnen und Kollegen, über die politischen Ereignisse hierzulande und in der Welt.

 Ulf
Und zwar insbesondere vielleicht, wenn ihr so das Gefühl habt, da könnte jemand so ein bisschen in Gefahr sein, abzurutschen. Da könnte jemand ein bisschen viel Telegramm lesen und ein bisschen viel irgendwelche wilden Verschwörungs Blogs lesen. Ich glaube, gerade diese Menschen könnten besonders profitieren, wenn sie gelegentlich mal bei uns an reinhören.

 Philip
Unser abschließendes Thema heute ist ein Thema, was ihr vielleicht in eurem Alltag oft zu spüren bekommt und von dem ihr eigentlich in der letzten Zeit glaube ich, mehr profitiert habt. Also da geht es um WLANs, also Funknetze, mit denen man ins Internet kommt. Die sind ja relativ häufig anzutreffen mittlerweile ja. Man muss sich immer noch manchmal so ein bisschen anmelden hier klick darauf und akzeptiere so, aber im Prinzip sind das freie WLANs in vielen Bereichen Hotels, Kaffees, Ferienwohnungen, Gaststätten, wo man sich einfach einklinken kann, auch in Supermärkten, wo man schnell mal zack drin ist und.

 Ulf
Bei Aldi, bei Rewe oder so.

 Philip
Unterschiedlicher Qualität. Aber man kommt halt rein und das ist im Ausland ist das schon seit vielen, vielen Jahren so, in Deutschland hingegen ist das eine relativ neue Entwicklung.

 Ulf
Ja, das ist total krass aufgefallen. Ich habe ja 2013/14 mal ein Jahr in USA studiert. Na, da kamst du an jeder Ecke in alle möglichen WLANs. In Deutschland gab's das damals im Prinzip noch nicht, denn in Deutschland war es extrem riskant, öffentliche WLANs anzubieten, einfach weil die Anbieter:innen solcher WLANs früher ein ganz erhebliches rechtliches Risiko eingegangen sind.

 Philip
Früher war es nämlich so, dass Menschen und Firmen, die ein freies WLAN betreiben und eben auch anbieten, immer damit rechnen mussten, dass sie teure Abmahnungen kassieren und bekommen.

 Ulf
Genau dann, wenn man so ein WLAN betreibt, dann betreibt man ja einen Internetzugang und da ist es nicht völlig auszuschließen, nicht so wahnsinnig wahrscheinlich, aber eben auch nicht auszuschließen, dass Menschen aus diesem WLAN heraus zum Beispiel Musikdateien oder Filme im Internet tauschen.

 Philip
Urheberrechtlich geschützt.

 Ulf
Und da gibt es natürlich so Kanzleien, die haben sich darauf spezialisiert, das Internet zu durchforsten nach den IP Adressen von Menschen, die eben so was tauschen. Und da gab es dann häufig Abmahnungen. Und diese Abmahnungen richten sich halt immer an die Person oder die Firma, die das Netz betreibt, weil das die Firma oder Person ist, die beim Provider, bei der bei dem Internetzugangsanbieter quasi eingetragen ist. Und das konnte richtig teuer werden. Da musste dann die Eisdiele mit einmal vierstellige Summen bezahlen an irgend so eine fiese Abmahnerkanzlei und deswegen traut...

 Philip
...weil Irgendeiner der Gäste irgendwas angeblich Illegales über dieses WLAN geladen oder angeboten hatte.

 Ulf
Angeblich. Und schon musste die Eisdiele Capri da ein paar 1.000 € raushauen. An so eine, an so eine Abmahnungskanzlei. Und angesichts dieses Haftungsrisiko traute sich kaum jemand ein solches WLAN anzubieten. Und diese sogenannte Störerhaftung wurde nun aber vor ein paar Jahren abgeschafft mit einem Gesetz von 2017 und es war eine relativ schwere Geburt. Ich selber muss gestehen, das war eines der ersten netzpolitischen Themen, wo ich mich sehr engagiert habe. Ich habe da sogar mal einen Gesetzentwurf geschrieben, 2012, glaube ich. Es war so eine extrem schwere Geburt. Aber wie gesagt, letztlich 2017 konnte sich die GroKo darauf einigen, dass sie die Störerhaftung abschaffen wollte. Und dazu hat sie in Paragraph acht des Telemediengesetz einen Satz eingefügt, der klarstellte, dass Betreibende von WLANs eben nicht haften müssen, wenn ihr Netz missbraucht wird.

 Philip
Also unter Paragraf acht Absatz eins Satz zwei des Telemediengesetz, heißt es dort seitdem...können Sie insbesondere nicht wegen einer rechtswidrigen Handlung eines Nutzers auf Schadenersatz oder Beseitigung oder Unterlassung einer Rechtsverletzung in Anspruch genommen werden. Also können nicht in Anspruch genommen werden wegen einer rechtswidrigen Handlung eines Nutzers oder einer Nutzerin. Dasselbe gilt hinsichtlich aller Kosten für die Geltendmachung und Durchsetzung dieser Ansprüche. Also sie konnten also nicht in Anspruch genommen werden und mussten auch nicht zahlen, seitdem dieser Satz im Gesetz steht.

 Ulf
So sieht es aus seit 2017. Nach einem langen Kampf, der fast zehn Jahre gedauert hat, ist die Störerhaftung in Deutschland für WLANs endlich abgeschafft. Und ich würde sagen, das war ein toller Fortschritt und insbesondere ohne wirkliche Probleme. Also die Urheberrechtsindustrie hat natürlich eine Riesenwelle gemacht, deswegen hat das auch so lange gedauert. Aber jedenfalls mir persönlich ist von einer Insolvenz von Sony Music oder Universal Pictures bislang nichts zu Ohren gekommen.

 Philip
Jetzt muss man natürlich auch diese Firmen nicht erst in die Insolvenz treiben, damit sie den Schaden haben. Aber mir ist das jetzt auch nicht bekannt geworden, dass es da irgendwie massive Probleme gegeben hätte, weil Eisdielen und Cafes und Restaurants und Tankstellen jetzt einfach WLANs anbieten, in die man einfach reinkommt.

 Ulf
Ehrlich gesagt war das von vornherein eine Scheindebatte, denn ich meine, wer stellt sich denn zum Dateien tauschen an die Tanke? Absurde Idee, aber gut. Und dieser gesellschaftliche Fortschritt, jetzt die News, dieser gesellschaftliche Fortschritt, dass wir seit ein paar Jahren freie WLANs haben können dank dieser Haftungsfreistellung, das könnte bald wieder vorbei sein.

 Philip
Ja, es droht nämlich eine ärgerliche Rolle rückwärts. Und verantwortlich dafür wäre Deutschlands Minister für Verkehr und digitale Infrastruktur Volker Wissing von der FDP. Und der Hintergrund dieser Geschichte ist der sogenannte Digital Services Act der Europäischen Union. Das ist also bekannt als DSA. Das ist eine Verordnung der EU. Und eine Verordnung gilt im Prinzip immer unmittelbar. Die muss also nicht erst noch kompliziert und langwierig in irgendwelche nationalen Gesetze umgegossen und eingebettet werden, wie das bei Richtlinien der Fall ist. Wenn die EU eine Verordnung beschließt, dann gilt die in jedem Staat der EU, so auch beim Digital Services Act. Und trotzdem gibt es in diesem Fall, obwohl der DSA eine Verordnung ist, einen Gesetzentwurf, der den die DSA in Deutschland umsetzen soll. Warum?

 Ulf
Tja, ganz einfach weil es zwar einen Anwendungsvorrang gibt für europäisches Recht, das heißt also quasi das europäische Recht geht vor. Aber nur weil der europäische Gesetzgeber ein bestimmtes Gesetz erlässt, treten eben nicht deutsche Gesetze außer Kraft. Und das würde zu der sehr unschönen Situation führen, dass im Deutschen Gesetzbuch noch was steht, zum Beispiel das Telemediengesetz, das aber in weiten Teilen nicht angewendet werden darf, weil der DSA eben vorgeht.

 Philip
Und das hätte dann das wäre dann so der blöde Effekt. Du willst mal nachgucken, was gilt denn so in Deutschland? Dann blättert so im Gesetz und liest Aha, das und das gilt. Wenn du dann aber nicht weiß, dass es dazu eine europäische Verordnung gibt, denkst du, das gilt? Dabei steht das zwar im Gesetz, gilt aber nicht mehr, weil es eben diese Verordnung gibt, die irgendwas anderes sagt. Und dann macht es total schwer bis unmöglich, halbwegs einen Überblick darüber zu bekommen, welche Regeln denn jetzt gelten.

 Ulf
Ganz genau. Und deswegen ist eben parallel zur Einführung des DSA ein deutsches Gesetz geplant, das sogenannte Digitale Dienste Gesetz. Und das muss man sich also so ein bisschen vorstellen wie so einen legislativen Hausputz. Eigentlich eine sehr gute Idee aus dem Hause von Volker Wissing, dass man also quasi das deutsche Recht einfach aufhebt und aus dem Gesetzbuch streicht, das sowieso vom DSA überlagert wird. Und das wesentliche Gesetz, das überlagert wird vom vom DSA, ist eben das sogenannte Telemediengesetz. Und in diesem Telemediengesetz wiederum steht diese Haftungsfreistellung für WLANs. Und deswegen wäre es natürlich wichtig, dass die aus dem außer Kraft tretenden TMG auch wieder übernommen wird ins Digitale Dienste Gesetz.

 Philip
Aber da gibt es ein Problem, denn es gibt da eine Lücke, die dazu führen könnte, dass öffentliche WLANs in Deutschland wieder abgeschaltet werden. Dass es in Deutschland heute keine Störerhaftung für WLANs gibt, das verdanken wir wie gesagt, diesen Satz, den wir oben vorgelesen haben, den die GroKo 2017 ins Telemediengesetz aufgenommen hat, haben wir oben vorgelesen. Das Telemediengesetz aber wird, nun ja, komplett aufgehoben, weil eben von der Verordnung aus der EU überlagert.

 Ulf
So, und die Teile, die wenigen Teile des Telemediengesetz, die nicht im DSA stehen, die kommen nun in das Digitale Dienste Gesetz. Problem: Alle Teile? Nein, eine kleine Klausel hat das Ministerium von Volker Wissing bei seiner Umsetzung ins Digitale Dienste Gesetz vergessen, nämlich ausgerechnet die Klausel, die die Störerhaftung abgeschafft hat. Und wenn das so Gesetz wird, dann müssen WLAN Betreiber:innen eben doch wieder mit Abmahnungen rechnen und viele freie WLANs würden ziemlich sicher wieder abgeschafft.

 Philip
Also wenn das so kommt und um das noch mal klar zu machen, dann gibt es die Verordnung, den DSA, der regelt ganz viel, was bisher das Telemediengesetz geregelt hat. Was nicht im DSA steht, ist diese Abschaffung der Störerhaftung. Die steht nur im Telemediengesetz. Damit die weiter gilt, muss sie aus dem Telemediengesetz raus in ein neues Gesetz reingeschrieben werden. Dieses Digitale Dienste Gesetz. Das ist zum Teil auch passiert, aber eben ohne diesen Satz, der dafür sorgt, dass Leute, die ein öffentliches WLAN anbieten, nicht dafür haften.

 Ulf
Ganz genau. Also die Menschen im Ministerium haben ganz offensichtlich sich angeschaut okay, hier ist das alte Telemediengesetz. Ganz vieles davon steht jetzt schon im DSA, kann einfach weg. Ein paar Sachen stehen nicht im DSA, das haben sie quasi per Copy and Paste in diesen Entwurf für das Digitale Dienste Gesetz geschrieben. Aber diesen einen Satz, der die Störerhaftung abschafft, den haben Sie dabei vergessen.

 Philip
So, und wenn, das ist jetzt ein Gesetzentwurf. Wenn das Ding Gesetz wird, dann werden sehr wahrscheinlich viele Betreiber freier WLANs Betreiberin das Ding einfach abschalten, weil sie Schiss haben, berechtigt Schiss haben vor teuren, nervigen Abmahnungen. Und deswegen ist der Verbraucherzentrale Bundesverband also der größte Verband für Verbraucherinteressen, Verbraucherinneninteressen in Deutschland auch auf der Palme, denn die sind da letztlich drauf gestoßen.

 Ulf
Sie haben das auch schon ausgegraben. Und die schreiben in Ihrer Stellungnahme zu dem Referentenentwurf des Digitale Dienste Gesetzes: Obschon in der Gesetzesbegründung des Gesetzentwurfs die Gründe für die seinerzeitige Änderung des Telemediengesetz genannt wurden, nämlich die Angst vor Abmahnungen, fehlt im Referentenentwurf in Paragraf sieben die entscheidende Passage, die diese Angst ausgeräumt hat bzw ausräumen kann. Deswegen fordert der vzbv:

 Philip
Der Gesetzgeber muss sicherstellen, dass keine erneute Abmahnwelle für Anbieter von öffentlichen WLANs droht und Paragraf acht Absatz eins Satz zwei Telemediengesetz ebenfalls ins DDG, also Digitale Dienste Gesetz übernommen wird. Ja, es ist interessant, dass die in dem Gesetzentwurf selber schon sagen: Hier gab ein Problem haben wir abgeschafft, aber das, was das bewirkt hat, haben sie dann einfach nicht übernommen.

 Ulf
Also das kann halt einfach ein Fehler sein. Also dass das in der Gesetzesbegründung sogar ausdrücklich steht, könnte darauf hindeuten, dass es ein Fehler ist. Es könnte natürlich auch einfach eine Nebelkerze sein, dass man halt einfach sagt, er wird. Man tut so, als wenn man das Problem gesehen hat.

 Philip
Und dann jeder, der die Begründung liest, ist ja alles ok.

 Ulf
Und in Wirklichkeit haben sie es gerade nicht im Griff. Ist so ein bisschen unklar, was das Verkehrsministerium da bewogen hat.

 Philip
Deswegen haben wir noch mal nachgefragt beim Bundesministerium für Verkehr und Digitales, was es denn damit auf sich habe, da das ein Versehen war. Ob das Absicht war? Und die Antwort ist jetzt hier quasi während der Sendung eingetrudelt. Und da heißt es: Lieber Herr Banse, danke für Ihre Anfrage. Als Sprecher vom Ministerium kann ich hier mitteilen: Das Ministerium überarbeitet derzeit den Referentenentwurf des Digitale Dienstes Gesetzes im Lichte der Stellungnahme der Länder und Verbände. Dabei wird auch geprüft, ob die Regelung des Paragraf acht Absatz eins Satz zwei TMG wieder aufgenommen werden soll. Jetzt kommt's. Ziel ist es, an der bestehenden Rechtslage für WLAN Anbieter nichts zu ändern. So.

 Ulf
Das klingt ja jetzt erst mal gut. Das klingt ja erst mal so, als solle die Störerhaftung nicht wieder eingeführt werden. Ich muss ganz ehrlich sagen, ich werde so ein bisschen stutzig bei der Formulierung. Man prüft, ob man diesen Satz, diesen bisherigen WLAN Schutzsatz wieder aufnehmen soll. Das könnte nämlich so ein bisschen so klingen wie: Der ist ja vielleicht gar nicht erforderlich, weil das ja schon im DSA steht. Und so.

 Philip
Nach einem Versehen klingt es nicht.

 Ulf
Nee, nach einem Versehen klingt es überhaupt nicht. Und ich mache mir einfach die ganz große Sorge, dass man sagt, man will an der Rechtslage nichts ändern. Man lässt diesen Satz am Ende trotzdem weg. Dann ist nämlich genau das Problem. Dann kann man sagen Ja, wir wollten ja nichts ändern, man hat aber dann was geändert und dann liegt das Problem wieder bei den Gerichten. Und die haben sich leider Gottes immer extrem WLAN feindlich gezeigt in den letzten Jahren. Da sind ja wie man, wie man sich vielleicht dunkel erinnert, auch irgendwelche 80-jährigen Omas wegen angeblichem Filesharing verurteilt worden. Also da muss ich sagen, da traue ich so ganz insbesondere der Rechtsprechung in Deutschland nicht über den Weg. Da kommen dann immer irgendwelche tränenschwangeren Stellungnahmen der Urheberindustrie und dann knickt der kleine Amtsrichter ein.

 Philip
Also der Satz muss wieder rein.

 Ulf
Der Satz muss wieder rein, ohne Punkt und Komma, sondern so, wie er bisher auch schon im Telemediengesetz steht. Einfach nur zu sagen wird schon gut gehen und wir wollten nichts ändern, das reicht aus meiner Sicht auf keinen Fall aus.

 Philip
Damit ist die Lage diese Woche ausführlich und abschließend erörtert, wie ihr das gewohnt seid. Wir sagen Vielen Dank fürs Zuhören. Gibt uns ein paar Sternchen bei iTunes.

 Ulf
Genau. Und wir hoffen vor allem ihr hatte viel Spaß an dieser Sendung. Empfehlt uns weiter. Das hilft uns auch sehr gefunden zu werden dieser Welt, wo es doch immer mehr viele, viele bunte Podcasts gibt. Und vor allem: Habt ein schönes Wochenende.

 Philip
Und dann hören wir uns nächste Woche wieder. Bis dann. Tschüss!
