:PROPERTIES:
:ID:       413f29b9-9539-438c-9044-7146c778bca5
:END:
#+title: Bias

* TODO Confirmation bias
* Binary bias
From [[id:ce02c8f6-cdf1-4aeb-aa63-2d03142ff979][Think again]]

#+begin_quote
Psychologists have a name for this: binary bias. It's a basic human tendency to seek clarity and closure by simplifying a complex continuum into two categories. To paraphrase the humorist Robert Benchley, there are two kinds of people: those who divide the world into two kinds of people, and those who don't.

An antidote to this proclivity is complexifying: showcasing the range of perspectives on a given topic. We might believe we're making progress by discussing hot-button issues as two sides of a coin, but people are actually more inclined to think again if we present these topics through the many lenses of a prism. To borrow a phrase from Walt Whitman, it takes a multitude of views to help people realize that they too contain multitudes.
#+end_quote

* TODO Hindsight bias
- in retrospect, earlier events always seem more predictable than they really were at the time
* TODO Attribution bias
