:PROPERTIES:
:ID:       93e27662-0a7b-47fc-b6bb-e1fc17a8f7e5
:END:
#+created: 20201202205918657
#+lang: de
#+modified: 20210518184429828
#+origin: [[<<. bibliography "Gespräche mit Gott Band 2">>]]
#+revision: 0
#+tags: 
#+title: Die Gesellschaft heute
#+type: text/vnd.tiddlywiki

Ein Zitat aus dem Buch , das den Zustand unserer heutigen Gesellschaft ziemlich genau auf den Punkt bringt (das Buch wurde 1997 veröffentlicht)

#+begin_quote
Tatsache ist, dass ihr euch kaum weiterentwickelt habt. Ihr agiert immer noch aus einer primitiven Mentalität des "jeder für sich selbst" heraus. Ihr plündert die Erde aus, beraubt sie ihrer Ressourcen, beutet ihre Lebewesen aus, entzieht systematisch jenen Personen die Bürgerrechte, die euch dabei nicht zustimmen, und bezeichnet sie als /Radikale/.

Ihr tut das alles um eurer eigenen selbstsüchtigen Zwecke willen, weil ihr einen Lebensstill entwickelt habt, den ihr auf andere Weise nicht aufrechterhalten könnt. Ihr müsst jedes Jahr Millionen Hektar an Baumbeständen fällen, sonst könnt ihr eure Sonntagszeitung nicht bekommen. Ihr müsst die euren Planeten schützende Ozonschicht immer weiter zerstören, sonst könnt ihr euren Haarspray nicht bekommen. Ihr müsst die Flüsse und Bäche irreparabel verschmutzen und verseuchen, sonst können euch eure Industrien nicht mit immer noch mehr und noch Größerem und Besserem beliefern. Und ihr müsst die Geringsten unter euch ausbeuten - die Unterprivilegiertesten, die am wenigsten Ausgebildeten, die am wenigsten Bewussten -, sonst könnt ihr nicht an der Spitze der menschlichen Leiter eines unerhörten (und unnötigen) Luxus leben. Und schließlich müsst ihr leugnen, dass ihr das alles tut, sonst könnt ihr nicht mit euch selber leben.

Euer Herz rät euch nicht, "einfach zu leben, damit andere einfach leben können". Diese Aufkleber-Weisheit ist zu simpel für euch. Sie ist zu viel verlangt, fordert zuviel von euch. Schließlich habt ihr so hart für das, was ihr habt, gearbeitet! Davon gebt ihr nichts auf! Und wenn der Rest der Menschheit - von den Kindern eurer eigenen Kinder ganz zu schweigen - dafür leiden muss, ist das eben ihr Pech, richtig? Ihr habt getan, was /ihr/ tun musstet, um zu überleben, um es "zu schaffen" - sie können dasselbe tun! Schließlich ist es nun mal so, oder etwa nicht: Ein jeder für sich!

#+end_quote
