#+created: 20191209101153541
#+modified: 20210518202803541
#+origin: https://wiki.python.org/moin/GlobalInterpreterLock
#+revision: 0
#+tags: Python Definition
#+title: GIL
#+tmap.id: 10397919-7d35-4846-b8c2-3163362aec5e
#+type: text/vnd.tiddlywiki

- Global Interpreter Lock :: In CPython, the global interpreter lock, or GIL, is a mutex that protects access to Python objects, preventing multiple threads from executing Python bytecodes at once. This lock is necessary mainly because CPython's memory management is not thread-safe. (However, since the GIL exists, other features have grown to depend on the guarantees that it enforces.)
  The GIL is controversial because it prevents multithreaded CPython programs from taking full advantage of multiprocessor systems in certain situations. Note that potentially blocking or long-running operations, such as I/O, image processing, and [[#NumPy][NumPy]] number crunching, happen outside the GIL. Therefore it is only in multithreaded programs that spend a lot of time inside the GIL, interpreting CPython bytecode, that the GIL becomes a bottleneck.
