:PROPERTIES:
:ID:       a6bda56f-bc32-4d68-8112-f0bb8b248fa1
:END:
#+created: 20201110082543573
#+modified: 20220328190433613
#+origin: [[<<. bibliography "Dein kompetentes Kind">>]] [[<<. bibliography "Die kompetente Familie">>]] [[<<. bibliography "So viel Freude, so viel Wut" >>]]
#+revision: 0
#+tags: Definition
#+title: Gleichwürdige Familie
#+tmap.id: 71f315f2-d9cd-46aa-a0d4-2b1147791a05
#+type: text/vnd.tiddlywiki

* Definition
- /gleichwürdig/ heisst, dass die Rollen in einer Beziehung (Eltern - Eltern,
  Eltern - Kind) immer wieder aufs Neue beschrieben werden (unabhängig von der
  Rollenverteilung)
  - und nicht wie in Südeuropa:
- beide Elternteile sind gleichermaßen /entscheidungskompetent/
- in der Famile haben alle das gleich Recht and /Würde/
  - aber nicht das gleiche Entscheidungsrecht
- Entscheidungen werden gemeinsam getroffen oder von der Person, die kompetent
  ist
- im Gegensatz zur /demokratischen/ Familie werden Entscheidungen auch dann
  akzeptiert, wenn nicht beide Elternteile damit einverstanden sind
- ein /demokratisches/ Modell sollte es trotzdem *nicht* sein
  - Beschlüsse werden gemeinschaftlich diskutiert oder in Übereinstimmung
    gefasst
  - dennoch sollten Konflikte auch wirklich ausgetragen werden und sich nicht in
    Analysen und Unterlagen vertiefen, "statt mit der Fernbedienung zu werfen"
    ([[#Guido%20Schmidt][Mehr Synthese, weniger Analyse]])
- Eltern betrachten die Lebensäußerungen, Ansichten, Bedürfnisse und Wünsche des
  Kindes mit derselben Priorität wie ihrer eigenen
- Kinder müssen (und wollen!) sich an Eltern orientieren
  - Kinder sollen angstfrei zu den Eltern aufschauen und /Entscheidungen/
    respektieren
* Zitate
** Note 1
#+begin_quote
Demokratische Spielregeln können die Wertegrundlage der Familie sinnvoll
ergänzen, doch reichen sie allein nicht aus. Mit Begriffen wie Mitbestimmung,
Stimmrecht und ähnlichem lassen sich vielleicht organisatorische Dinge regeln
wie beispielsweise die Frage, wo der nächste Urlaub verbracht werden soll. Der
Prozess des Zusammenspiels, der dafür verantwortlich ist, ob die einzelnen
Familienmitglieder sich wohlfühlen, wird davon nicht berührt.

Entscheidend für die gesunde Entwicklung von Kindern und Eltern ist die Qualität
des Zusammenspiels in der Familie, also das, was wir gemeinhin als «Ton»,
«Stimmung» und <<Atmosphäre>> bezeichnen. Die griechischen Philosophen nannten es
*Ethos*. Ich werde später auf diesen zentralen Begriff zurückkommen und will mich
an dieser Stelle mit der Bemerkung begnügen, dass die Verantwortung für die
Qualität des Prozesses in den Händen der Erwachsenen liegt. Sie kann weder
delegiert noch geteilt werden.
#+end_quote
** Note 2
#+begin_quote
Für die Qualität des Zusammenspiels tragen die Kinder jedoch keine
Verantwortung. *In Familien, in denen die Kinder «bestimmen», weil die Eltern
aus unterschiedlichen Gründen nicht in der Lage sind, ihrer Verantwortung
gerecht zu werden, hat dies stets negative Folgen*. Man kann Kindern bestimmte
Aufgaben und Verantwortungsbereiche zuweisen, *die Verantwortung für das
Wohlergehen der Familie tragen jedoch allein die Eltern*. Natürlich ist nichts
dagegen einzuwenden, die Kinder in demokratischem Geist an
Entscheidungsprozessen zu beteiligen, doch sollte es sich in erster Linie um das
Erlernen de- mokratischer Spielregeln handeln. Ansonsten ist den Kindern am
besten damit gedient, wenn die Erwachsenen ihre Wünche und Bedürfnisse ernst
nehmen. Zwischen der Durchsetung unseres Rechts und der Befriedigung unserer
Bedürfmisse herrscht eben ein himmelweiter Unterschied
#+end_quote
** Note 3
#+begin_quote
Was ist mit *Gleichwürdigkeit* eigentlich gemeint? Wahrend *Gleichheit eine
statische, messbare Größe* ist, impliziert *gleiche Würde einen dynamischen
Prozess*, eine veränderliche Kategorie, um die man sich in jeder Beziehung stets
aufs Neue bemühen muss.

*Gleichwürdigkeit* unterscheidet sich von Gleichheit darin, dass sie *keiner
bestimmten Rollenverteilung* bedarf. Selbst wenn die Frau am Samstagnachmittag in
der Küche steht, während der Mann sich ein Fußballspiel im Fernsehen ansicht
oder umgekehrt, sagt dies nichts darüber aus, wie es um die Gleichwürdigkeit
zwischen ihnen bestellt ist. Ungleichheit spielt für die Gleichwürdigkeit nur
dann eine Rolle, wenn sie aufgezwungen ist, und Gleichheit kommt nur dann ins
Spiel, wenn jemand, der neue Aufgaben und Verantwortungsbereiche übernimmt, auch
menschlich davon profitiert. Wenn sich Väter beispielsweise mehr mit ihren
Kindern beschäftigen, kann das für Mütter natürlich eine Erleichte rung sein;
der Partnerschaft der Erwachsenen kommt dies jedoch nur zugute, wenn der Vater
durch die Beschäftigung mit den Kindern seine zwischenmenschlichen Qualitäten
ausbaut und vertieft.
#+end_quote
** Note 4
#+begin_quote
 Das Problem besteht jedoch darin, dass *den Kindern somit die Verantwortung für
die persönlichen Grenzen und das Wohlbefinden der Erwachsenen aufgebürdet wird*.
Damit ist jedes *Kind überfordert*. Kinder entwickeln in der Folge oft
hyperaktive oder chaotische Züge, und am Ende wird das Leben der Familie von den
unmittelbaren Wünschen und Bedürfnissen der Kinder geprägt. Nicht weil sie
machthungrig wären oder aus dachalb weil die Bedürfnisse und Grenzen der Erwachsenen
nicht mehr erkennbar sind.
#+end_quote
