:PROPERTIES:
:ID:       b2831721-165d-4943-a41a-da770d96be41
:END:
#+title: Golang
* Resources
** Articles
- 2022-08-29 ◦ [[https://appliedgo.com/blog/go-as-a-glue-language][How to use Go as a glue language]]
  #+begin_quote
  Happiness comes from within: _self-conained binaries_

  Go is _verb-oriented_. Put a pot on the stove. Boil water. Pour the water over some tea leaves. Wait. Drink. This is the way humans think. When planning a task, you think about the necessary actions before you think about the array of objects needed for executing these actions.


  Go's “*do something*” approach gets your *stuff done.*


  The =net/http= package allows building a basic *HTTP server* with a *few lines of code*.

  Go has quite a unique approach of *abstracting away data sources and sinks as uniform data streams*. An =io.Reader= stream, for example, can represent input from a file, a network connection, an in-memory buffer, or even a simple string. Unit-test your code with a byte buffer, then use it in production with real files.
  #+end_quote

- 2022-08-17 ◦ [[https://www.reddit.com/r/golang/comments/wlw5bj/preferred_resource_for_advanced_go/][Preferred resource for 'advanced' Go? : golang]]
  - Some good recommendation for advanced Go learning resources
- 2022-08-16 ◦ [[https://betterprogramming.pub/service-discovery-with-go-17b44011bcb2][Service Discovery with Go and mDNS]]
*** Botnets
- 2022-08-22 ◦ [[https://github.com/ThrillQuks/Pitraix][GitHub - ThrillQuks/Pitraix: Modern Self-Modifying Cross-Platform Peer-to-Peer Botnet over TOR]]
*** Design Patterns
- 2022-09-05 ◦ [[https://dev.to/mauriciolinhares/gof-design-patterns-that-still-make-sense-in-go-27k5][GoF Design patterns that still make sense in Go]]
*** Microservices
- 2022-08-25 ◦ [[https://github.com/zeromicro/go-zero][go-zero]]

  A cloud-native Go [[id:adce7f16-ab79-4935-b73e-71f3740a071f][Microservices]] framework with cli tool for productivity.
*** AWS
- 2022-09-06 ◦ [[https://www.go-on-aws.com/][GO ON AWS :: Learn to code go on AWS]]
  - Using Golang for writing [[id:61b1e794-8d3a-45f1-b414-612b6ad4dad4][CDK]] stacks for [[id:be5bebfe-5df9-4db2-af87-7e80e11723c7][AWS]]
