#+created: 20220711125007656
#+modified: 20220711125459540
#+origin: [[<<. bibliography "The Oxygen Advantage" >> ]]
#+revision: 0
#+tags: 
#+title: Mouth Breathing vs Nasal Breathing
#+type: text/vnd.tiddlywiki

- *Mouth Breathing*
  - Mouth-breathing children are at greater risk of developing forward head posture,and reduced respiratory strength.
  - Breathing through the mouth contributes to general dehydration (mouth breathing during sleep results in waking up with a dry mouth).
  - A dry mouth also increases acidification of the mouth and results in more dental cavities and gum disease. ** Mouth breathing causes bad breath due to altered bacterial flora.
  - Breathing through the mouth has been proven to significantly increase the number of occurrences of snoring and obstructive sleep apnea.
- *Nasal Breathing*
  - Nose breathing imposes approximately 50 percent more resistance to the airstream in normal individuals than does mouth breathing, resulting in 10 to 20 percent more oxygen uptake.
  - Nasal breathing warms and humidifies incoming air
  - Nasal breathing removes a significant amount of germs and bacteria from the air you breathe in.
  - Nasal breathing during physical exercise allows for a work intensity great enough to produce an aerobic training effect as based on heart rate and percentage of [[#V%CC%87O2%20Max][V̇O2 Max]]
  - the nose is a reservoir for [[#Nitric%20oxide][nitric oxide]], an essential gas for the maintenance of good health.
