:PROPERTIES:
:ID:       794fe4d2-6c9b-4f95-9d27-9aba13a3c0b2
:END:
#+created: 20200908112114494
#+modified: 20210518184432912
#+revision: 0
#+title: Serverless
#+tmap.id: 68bcde7b-0863-4c96-bb99-8e212a09618f
#+type: text/vnd.tiddlywiki

* Articles
- 2023-05-15 ◦ [[https://dev.to/aws-builders/serverless-a-ctos-perspective-3hpc][Serverless, a CTO’s Perspective - DEV Community]]
  #+begin_quote
  As many others have stated, it's *not the absence of servers* that makes it
  serverless, it's the *place in your problem-solving and deployment* that makes it
  so.
  #+end_quote

  #+begin_quote
  So why would a CTO choose serverless from a people perspective? For me it's
  simple. With serverless I *spend less time running infrastructure and more time
  building application*
  #+end_quote

  #+begin_quote
  I tend to book *serverless components in two categories*. I have the *bedrock
  components* that I know I won't need to outgrow such as [[id:45a2f0a9-f32d-4592-afac-fd9500b06f3a][SQS]], DyanmoDB and
  EventBridge. And then I have *the components that get me going the quickest and
  will last a long time but might be replaced*. Step Functions and [[id:871392b8-355f-486b-badd-2a2458363ade][Lambda]]s fall
  into the this category. I've not reached a scale that requires this in a few
  places but the upgrade path is easy enough. I lean into Fargate on ECS which
  gives me plenty of horizontal scale to deal with load that might be more
  consistent.
  #+end_quote

- 2023-05-11 ◦ [[https://www.primevideotech.com/video-streaming/scaling-up-the-prime-video-audio-video-monitoring-service-and-reducing-costs-by-90][Scaling up the Prime Video audio/video monitoring service and reducing costs by 90% - Prime Video Tech]]
- 2023-03-16 ◦ [[https://serverlessland.com/][Serverless Land]]
  #+begin_quote
  This site brings together the latest information, blogs, videos, code, and
  learning resources for AWS Serverless. Learn to use and build apps that scale
  automatically on low-cost, fully-managed serverless architecture.
  #+end_quote
- 2022-11-09 ◦ [[https://news.ycombinator.com/item?id=33520733][Ask HN: Skeptical about my company going “full serverless”. What am I missing? | Hacker News]] ([[id:91f33643-b126-4383-9ffb-af8c379a28d9][HackerNews]])
  - great comments where Serverless is good at (and where not)
  - some interesting comments why GCP *should* be better than *AWS* (with regards to serverless)
- 2022-10-04 ◦ [[https://www.thisdot.co/blog/build-your-backend-with-netlify-functions-in-20-minutes][Build your Backend with Netlify Functions in 20 Minutes]]j
* Resources
- 2023-08-03 ◦ [[https://serverless.tf/][Doing serverless with Terraform]] ([[id:06676c92-78a2-4d38-966e-058acdf5cdfd][Terraform]])
