#+created: 20210622081606663
#+modified: 20210826085840399
#+origin: [[<<. bibliography "The Clean Architecture">>]]
#+revision: 0
#+tags: Definition
#+title: Software System
#+type: text/vnd.tiddlywiki

- Every software system provides two different values to the stakeholders:
  - behavior
  - structure
- Software developers are responsible for ensuring that both those values remain high.
- Unfortunately, they often focus on one to the exclusion of the other. Even more unfortunately, they often focus on the lesser of the two values, leaving the software system eventually valueless.
- What programmers are
  - Programmers are hired to make machines behave in a way that makes or saves money for the stakeholders. We do this by helping the stakeholders develop a functional specification, or requirements document. Then we write the code that causes the stakeholder's machines to satisfy those requirements
- must be developed by an organization with many teams
  - they have many concerns that require a [[#Software%20Architecture][Software Architecture]] that facilitates independent actions by those teams
    - this is done by seggregating the system into well-isolated, independently developable components
  - this way you can continue to add new [[#Software System/Use Cases][use cases]] w/o interfering with old ones ([[id:91ad1a5b-7a03-42e3-83b2-468e5d0eedd7][Open-Close Principle]])
