:PROPERTIES:
:ID:       9a7b9ce3-a734-4242-9b67-57c1925bc1f2
:END:
#+title: Vocea Natiei

* #185
În episodul 185 din podcastul Vocea Nației:
- „Acest medicament a fost prescris numai pentru dumneavoastră. Nu trebuie să-l dați altor persoane. Le poate face rău, chiar dacă au aceleași semne de boală ca dumneavoastră”. Ignorăm acest mesaj din prospectele medicamentelor, la fel cum ignorăm faptul că sfaturile despre cum să fim fericiți, cum să fim mai bine, nu pot să fie aceleași pentru toată lumea.
- Fericirea e un proces de producție cu intrări și cu ieșiri, ca într-o fabrică în care intră materie primă și iese un produs finit. Intrările fericirii sunt toți stimulii care se întrec să ne capteze atenția. Stimulii sunt apoi transformați în fericire prin atenția pe care le-o acordăm.
- A fost odată un om de afaceri care vizita o plajă într-un mic sat brazilian. În timp ce stătea întins la soare, vede un pescar vâslind spre mal într-o barcă mică, în care avea doar vreo câțiva pești. Afaceristul, uimit, întreabă: „Cât timp îți ia să prinzi atâta pește?”. „Oh, puțin”, îi răspunde pescarul. „Atunci de ce nu stai mai mult pe mare, ca să prinzi mai mulți?”

Cărți menționate:
- Rețeta fericirii – Paul Dolan
* #182
Cărți menționate:
- Burnout. Cum să spargi cercul vicios al stresului – Emily și Amelia Nagoski
- Mother of Invention – Katrin Marçal
* #180
Cărți menționate:
- Cine i-a gătit cina lui Adam Smith – Katrine Marçal
- Work won’t love you back – Sarah Jaffe
- Doughnut Economics – Kate Rawort
* #169
https://soundcloud.com/stareanatiei/podcast-vn-vocea-natiei-169

Discuții pe larg despre cărțile menționate aici, găsești în episoadele de mai jos:
- Vocea Nației #148
  – Spune-mi cine ești ca să-ți spun cum poți fi dezinformat – bit.ly/3Hq8PPT
- Vocea Nației #138
  – Drumul spre nelibertate – bit.ly/3VODdI4
- Vocea Nației #141
  – STOP PUTIN! Dictatorii se opresc doar atunci când sunt opriți – bit.ly/3Yd2NrP
- Vocea Nației #136
  – Amurgul democrației – bit.ly/3W2mHEN
- Vocea Nației #131
  – Întotdeauna alegerea îți aparține – bit.ly/3iM3IiN
- Vocea Nației #137
  – Secolul singurătății – bit.ly/3hfQ72U
- Vocea Nației #161
  – Cetățenesc, deci exist – bit.ly/3W4h5t5
- Vocea Nației #144
  – Regăsirea sensului – bit.ly/3UNJNgS
- Vocea Nației #145
  – De ce ne dezbină politica? – bit.ly/3UMKQxm
- Vocea Nației #156
  – Ce ne datorăm unii altora – bit.ly/3iHQB22
- Vocea Nației #166
  – Imaginație, educație, nație – bit.ly/3PjvL5C
- Vocea Nației #139
  – Gogoașa creșterii economice – bit.ly/3HqGXLQ
- Vocea Nației #133
  – Cum schimbăm capitalismul? – bit.ly/3W18nvA
- Vocea Nației #153
  – De unde vin de fapt banii și de ce nu îi avem? – bit.ly/3hbF8rp
- Vocea Nației #158
  – Cum a stricat PIB-ul viața pe Pământ – bit.ly/3HqBiW0
- Vocea Nației #164
  – Munca nu-ți va împărtăși dragostea – bit.ly/3YdrxR2
- Vocea Nației #146
  – Ai 4.000 de săptămâni. Ce faci cu ele? – bit.ly/3hjWOkn
- Vocea Nației #149
  – Rețeta fericirii – bit.ly/3Br7wfP
- Vocea Nației #159
  – Prețul rețelelor sociale – bit.ly/3FHZBgK
- Vocea Nației #160
  – Tu ce ești? Cimpanzeu sau albină? bit.ly/3Hucb4u

* #158                                                                          :book:
- Creșterea economică, o amăgire. Bogăția, sărăcia și bunăstarea națiunilor - David Pilling (book)
- https://happyplanetindex.org/
* #151                                                                          :book:
- https://www.goodreads.com/author/show/321601.Johann_Hari
- [ ] Ian Varoufakis
* #150                                                                          :book:
- [[id:9a5fc738-0ba0-42ce-8271-99eccc5c2abb][How to be good they can't ignore you]]
* #148                                                                          :book:
- Tim Harford în cartea [[https://www.goodreads.com/book/show/54564213-how-to-make-the-world-add-up][How To Make The World Add Up]]
* #136                                                                          :book:
- Amurgul Democrației. Seducătoarea atracție a autoritarismului” - Anne Applebaum”
- Economie utilă pentru vremuri dificile” - Abhijit Banerjee
* #134                                                                          :book:
- „The Entrepreneurial State”, scrisă tot de economista Mariana Mazzucato
  - există și un TED talk
* #131                                                                          :book:
 „Alegerea. Acceptă cu bucurie posibilul” scrisă de Edith Eva Eger
