:PROPERTIES:
:ID:       ed186da4-7847-4851-8705-54d4a24606d4
:END:
#+title: Regăsirea sensului
#+filetags: :todo:book:

* Introducere
** Ideologiile Râului

In esență, Ideologiile Răului împărtăşesc patru credințe principale:

• Lumea aşa cum o ştim este distrusă şi de nesalvat.
• Există un moment în viitorul apropiat în care totul se va schimba.
• De cealaltă parte a acestui punct de inflexiune, toți cei pe care îi apreciem vor fi salvati/mântuiţi.
• Aşa că hai să ajungem acolo cât mai repede posibil, fără să ne batem capul prea mult cu lumea pe care o lăsăm in urmă.

** Despre călătoria către Marte

Marte nu e locul din care provenim. Este foarte departe şi extrem de ostil vieții omeneşti. Rezolvarea acestor două probleme - distanţa şi supraviețuirea - reprezintă un efort monumental. De ce, dacă tot am putea dispune de expertiza tehnică, capitalul şi hotărârea de a realiza această reuşită istorică, nu am aloca aceleași resurse pentru a repara locul în care deja trăim? Locul din care provenim, de fapt?

** Fericirea universală

În nenumărate studii, moderații religioşi şi umaniştii seculari din toată lumea împărtăşesc o dorință de stabilitate și prosperitate. Majoritatea oamenilor, din toate culturile, vor doar să trăiască în pace şi să-şi vadă copiii având o şansă la o viaţă mai bună. Această dorință ne uneşte. Atei, musulmani, creştini, confucianişti, budiști, evrei, hinduşi şi hipsteri - toți îşi doresc doar să moară în somn, fericiți și înconjurați de nepoți. Așa a fost dintotdeauna

* Partea 1
** Centrul nu poate rezista
*** Mai multe sinucideri

Organizația Mondială a Sănătății raportează că astăzi mult mai mulți oameni se sinucid decât mor din cauza tuturor războaielor şi dezastrelor naturale la un loc. Gândiți-vă la toate uraganele, inundațiile şi incendiile şi la toate războaiele civile, terorismul şi conflictele militare care ne inundă fluxurile de știri. Puse laolaltă ele nu egalează numărul celor care aleg să părăsească această lume pentru că nu o mai pot îndura

** Încetați sa mai înțelegeți
*** Definiție escaton

escaton

Substantiv: evenimentul final în planul divin; sfârşitul lumii

escatotezie

Substantiv: un sentiment al unui eveniment uriaş în viitorul apropiat care ne aşteaptă: sfârşitul unei acţiuni, un reper în timp după care nimic nu va mai fi la fel.

*** Definiție apocalipsă, armaghedon și rău

Mai întâi, Apocalipsa. În greaca veche, apocalypsis înseam- nă,,dezvelirea sau dezvăluirea". Pe măsură ce experimentăm şi colapsul Autorității Benigne şi al Autorității Divine şi punem în discuție atât dictatele religiei tradiționale, cât şi pe cele ale liberalismului modern, ne sunt dezvăluite tot felul de adevă- ruri ascunse. Nu toate sunt liniştitoare, dar sunt necesare dacă sperăm să dezvoltăm o capacitate avizată de a actiona

Apoi Armaghedon. Este o contragere a evreiescului Har Meggido şi se referă la muntele de lângă oraşul israelian Haifa. Acolo credincioşii aşteaptă confruntarea finală între Bine şi Rău. Odată începută această bătălie suntem pe drumul către ultimele zile ale Judecăţii. Nu mai există întoarcere pentru vii sau morţi.

Şi, în cele din urmă, Răul. În versiunea sa cu literă mică, înseamnă fericire intensă sau împlinire. În versiunea cu majus- culă, răul este o poveste despre un cataclism iminent pentru cei mulţi şi de mântuire fericită a câtorva. Deşi a început ca o credinţă religioasă despre Sfârşitul Timpului, de atunci forma ei a suferit nenumărate mutaţii, atât sacre, cât şi seculare

*** Reflexul Semmelweiss

în care reflexul Semmelweiss-ideea că, de obicei şi adeseori în mod violent, respingem dovezi sau cunoştinţe noi doar pentru că ele funcționează într-o manieră contrară credințelor noastre preexistente - a devenit un reper pe lista prejudecăţilor cognitive obişnuite

*** Despre vacile sacre
**** Capitalismul de piață liberă și democrația

Capitalismul de piață liberă şi democrația reprezentativă merg mână în mână și oferă meca- nismul suprem pentru a ridica omenirea la niveluri tot mai înalte de prosperitate. Eforturile de a redistribui bogăția, a limita competiţia şi a restrânge opoziția publică variază de la contraproductive la catastrofice.

Colapsul Uniunii Sovietice şi ridicarea standardelor de viață în toată lumea au oferit o justificare puternică pentru această paradigmă. Piețele funcționează. Comunismul, nu. Democrația funcționează. Dictaturile, nu. Pentru o scurtă perioadă, între căderea Zidului Berlinului în 1991 şi căderea Turnurilor Gemene în 2001, acest model a părut necontestat şi ascendent.

Însă neoliberalismul a rămas rapid în pană de explicații pentru tot ce se întâmpla. Când a doua Administrație Bush şi-a imaginat Orientul Mijlociu eliberându-se de jugul tiraniei şi îmbrăţişând democrația, situația a ricoşat îngrozitor. Eşecul schimbării de regim după Primăvara Arabă în Siria, în Irak şi în Libia a destabilizat şi mai mult regiunea şi a creat condițiile care au determinat apariția ISIS.

** Noi suntem lumea
*** Mereu în stare de alertă

Dat fiind că ultimii ani par să însumeze decenii de soci schimbări destabilizatoare, este corect să spunem că amiga lele noastre - sistemele noastre de detectare a pericolului- fost în stare de alertă maximă. Fie că a fost vorba de remit surprinzătoare ale alegerilor electorale, de dezastre nature sau de pandemii globale, ceea ce se întâmpla in alte ţări, in a state, ba chiar la doi paşi de noi a fost ceea ce a contat cu ade- vărat. Impulsul nostru de a fi la curent cu orice ştire, cu ori noutate şi cu orice „părere expertă” a crescut vertiginos.

Pe vremuri am fi ascultat tobele din junglă şi bârfele din sat sau am fi urmărit semnalele cu fum. Acum asta s-a metamor- fozat în postări pe Facebook și pe Instagram, stat cu orele pe YouTube şi pe grupuri de WhatsApp. Suntem cu toţii dispen să înțelegem ce ar putea să ne salveze sau să ne omoare

*** Filantrocapitalism
** Proiectand Sens 3.0
*** Filantrocapitalismul

Pentru că statul sovietic la a cărui destramare a contribuir Elçin nu este singura centralizare verticală de care ar trebui să finem cont. Ironic, capitalismul şi-a creat propria mutatie. Suntem în epoca filantrocapitalismului unde Bill Gates, Eric Schmidt, Mark Zuckerberg, Jeff Bezos și alții, după ce şi-au zdrobit fără milă competitorii și au exploatat paradisuri fiscale off-shore, îşi redirecționează acum averile istorice către rezol- varea multora dintre problemele la a căror creare au contribuit (şi, ca să fim corecți, a câtorva la care nu au contribuit

*** Funcțiile credinței

Există o mulțime de modalități de a cartografia funcțiile credinței, dar Laboratorul de Design Sacru de la Şcoala de Divinitate Harvard le-a redus la trei elemente centrale: Dincolo, Devenire şi Apartenenţă. Trei nutrienți esențiali, vitali pentru înflorirea umanității. Sau altfel spus, inspirație, vindecare şi conectare. Grecii antici le numeau pe cele trei ecstasis, catharsis şi communitas. Deşi pot purta nume diferite, rolul lor în susţinerea înfloririi umanității este esențial. Ele sunt modul în care ne trezim, creştem şi ne prezentăm. Iar şi iar, atât timp cât este nevoie.

*** Candidatul ideal pt Sens 3.0

Să recapitulăm: Un candidat ideal pentru Sens 3.0 va trebui să îndeplinească funcțiile prosociale ale Credinței tradiționale 1.0-Inspirație, Vindecare și Conectare. Și, pentru a avea o şansă să ajute lumea, trebuie să îndeplinească promisiunea inclusivă a Modernismului 2.0 şi să fie din Surse Deschise, Scalabil şi Antifragil

*** Cele Mari Cinci pt a crea sensul

Respirația - Noi suntem puternic codați să ne asigurăm că rezerva noastră de oxigen rămâne constantă, aşadar modula- rea respirației este una dintre modalitățile cele mai de succes pentru a schimba stările fizice şi psihologice.

Întruparea - Regulatorii centrali ai sistemului nostru ner- vos parasimpatic şi simpatic joacă un rol uriaș în sănătatea, bunăstarea şi reziliența noastră la stres. Ei sunt metronomul fiziologiei noastre care stabileşte ritmul experiențelor trăite.

Sexualitatea - Dacă nu procream, murim. Prin urmare, există tone de motoare neurochimice integrate în sistemele noastre pentru a se asigura că o facem. Intelegerea lor permite o reorientare puternică către această activitate centrală dătă- toare de viaţă.

Substanțe - Oamenii, și majoritatea celorlalte animale, caută în mod obişnuit să-şi schimbe starea ca parte a procesu- lui lor de învățare, creştere şi însănătoşire. Ron Siegel de la UCLA a ajuns chiar să numească căutarea intenționată a into- xicării a patra forță -o dorință de a te simți diferit, o schim- bare rapidă de stare" care este la fel de mult o parte a condiţiei umane ca sexul, foamea şi setea"

Muzica - De la anticele incantații lângă foc, la catedrale, la sclavi în lanţuri şi până la concerte, muzica ne-a însoţit în călă- toria civilizației umane. Ea nu doar ,,calmează bestia sălbati- că"; ea ne formează psihologia, simțul conectivității și capacitatea de a fi uimiţi

*** Personalități extatice

Vezi imaginea cu tabelul (p. 135)

*** Personalități extatice (2)

Aşadar, în timp ce citești aceste descrieri, notează-ți care dintre ele ţi s-a părut că se potriveşte cel mai bine cu viața ta:: Vezi cum au ajutat și ți-au afectat negativ propriile încercări de a experimenta Ecstasisul (experiență de extaz şi uimire Catharsisul (vindecare profundă și integrare) şi Communitas (conectare profundă cu alții).

Noi nu ne putem lăsa distrași de senzații, aşa cum ar pute un Hedonist. Şi nici nu putem strâmba din nas la abordări car nu se potrivesc identității noastre idealizate, aşa cum ar putea un Purist. Și nu putem ignora soluții noi care ar putea aduce un beneficiu puternic, aşa cum ar putea un Conformist.

În timp ce ele au toate unghiuri moarte, fiecare dintre aces te orientări are o valoare centrală pe care ceilalţi ar face bi!! să o încorporeze. Hedonistul caută să scoată tot ce e mai b din viaţă şi să urmeze cea mai amplă gamă de experiențe po bile. Puristul valorizează sanctitatea minţii şi corpul Conformistul valorizează sfatul expert şi dovezile.

* Partea 2: Cartea de bucate a alchemistului
** Respirație
*** Oxid de azot

Acele vibrații conştiente" mai fac ceva. Eliberează un neurotransmiţător puternic care diminuează stresul, determi- nă o schimbare a stărilor fiziologice şi facilitează accesul la conştiinţa de transă. Oamenii de ştiinţă de la Institutul Karolinska din Suedia au descoperit că respirația nazală are ca rezultat o mai bună oxigenare cu 15-30% decât respirația pe gură. Şi dacă produci vibrații în cavitatea nazală în timp ce o faci, aşa cum fac cântăreții la didgeridu, ea creşte nivelul de oxid de azot de până la 15 ori.

Oxidul de azot este o moleculă puternică care trece peste bariera hemato-encefalică şi ne duce de la stări vigilente şi stresante, la stări mai calme, mai inventive. Potrivit lui Herbert Benson de la Harvard,,,studiile moleculare au arătat că răs- punsul calmant eliberează mici <«<pufuri» de oxid de azot, care a fost legat de producția unor astfel de neurotransmiţători ca endorfinele şi dopamina". Benson a descoperit că tranziția de la conştiinţa obişnuită la stări de vârf este declanşată de un flux de oxid de azot prin sistemul nervos. Ea funcționează ca o moleculă de semnalizare, trimiţând informații înainte şi îna- poi între părțile creierului care în mod normal nu comunică, reducând reacţiile la stres și amplificând relaxarea profundă şi conexiunea. El numeşte oxidul de azot,,spiritul" sau catali- zatorul experienței extatice.

Impulsul de oxid de azot pe care îl creează didgeridu are şi alte beneficii generale pentru sănătate de la diminuarea dificultăților de respirație, precum astmul şi apneea din timpul somnului, la reducerea stresului. Un studiu a descoperit că ,,meditaţia pe fond de didgeridu este la fel de eficientă ca meditaţia tăcută pentru reducerea oboselii, a energiei şi excitației negative autopercepute, şi mai eficientă decât meditaţia tăcută pentru relaxare şi stres acut."

*** Apnee statică

Trageți adânc aer în piept chiar acum. Ţineţi-vă respirația cât de mult puteți. Simțiți acele prime spasme în stomac sau înghițituri în gât. Continuaţi până când trebuie să evacuați aerul. Vedeţi cât de mult a durat. Fără antrenament, cele mai multe tentative durează undeva între 30 și 90 de secunde. Acesta este cunoscut drept scorul tău de,,apnee statică" - un termen pompos pentru a-ți ține respirația. La sfârşitul acestui capitol, scorul tău ar trebui să se dubleze

*** Stiluri de respirație

Vezi tabelul

*** Zona Goldilocks

Dar cum rămâne cu dioxidul de carbon? Presupusesem întotdeauna că CO, era pur şi simplu un gaz rezidual pe care încercai să-l minimizezi astfel încât să poți face mai multe cu un plămân plin cu aer. Apoi am aflat despre cercetările fizicianului sovietic Konstantin Buteiko asupra creşterii nivelului de CO, pentru a impulsiona oxigenul dispo- nibil în sânge. Buteiko a pledat în favoarea unei „Zone Goldilocks" cu nici prea mult, nici prea puțin CO, pentru sănă- tatea şi performanța optimă. Acesta este motivul pentru care, când cineva are un atac de panică și hiperventilează, i se dă o pungå de hârtie în care să respire. Ea îi ajută să reechilibreze cantitatea de CO, din sânge și fi aduce înapoi în starea de echilibru.

*** Protoxid de azot

Protoxidul de azot este un compus organic care a fost degajat din atmosferă, sol şi oceane de milenii întregi. Este unul dintre cei mai interesanţi membri ai familiei azotului. Deşi e doar o ușoară variaţie a azotului inert care formează aproximativ 80% din aerul pe care-l respirăm, acest oxid are un efect fun- damental diferit asupra sistemului nostru nervos. Protoxidul de azot calmează nervii şi alină durerea, dar dă naştere unor experienţe mai ciudate - şi poate mai utile din punct de vedere terapeutic-decât majoritatea substanțelor de pe Lista I.*

Medicamentele, substanțele sau substanţele chimice de pe Lista I sunt definite ca medicamente fără utilizare medicală acceptată în prezent şi cu un potențial ridicat de abuz Printre acestea se numără heroina, dietilamida acidului lisergic (LSD), marijuana (canabis), 3,4-metilendioximetamfetamina (ectasy), metaqualona şi peyote

*** Monoxide de azot

Pe măsură ce urmărim ceea ce Organizația Mondială a Sănătăţii descria atât de anost drept „,,excitarea tranzientă” pe care o produce protoxidul de azot, mai trebuie făcute câteva legături. Ele ne duc înapoi pe teritoriul lui William James, la Harvard Medical School. Acolo, Herbert Benson, cu care ne-am întâlnit mai devreme, a devenit autoritatea incontesta- bilă în ceea ce priveşte răspunsul biologic al corpului la experienţa de vârf. Cercetările sale l-au condus la un studiu profund al familiei azotului și al vărului apropiat al protoxidu- lui de azot, monoxidul de azot - sau oxidul nitric. Acest neurotransmiţător elimină substanţele chimice de stres din creier și serveşte ca un vasodilatator în corp - Viagra, care impulsionează direct producția de monoxid de azot, se foloseşte tocmai de acest mic efect colateral.

Monoxidul de azot (NO), identic cu protoxidul de azot (NO), dar cu un singur atom de azot, este, potrivit cercetăto- rului său prim,,,catalizatorul experienței fizice, mentale şi chiar spirituale"

** Sacramente
*** Despre religii și cum ne raportam la ele

Wade Davis, explorator in rezidență la National Geographic,

mi-a spus că pe vremea când studia posedarea voodoo in Haiti, un houngan (preot) a extins distincţia originală a lui Quanah Parker: Când albii merg la biserică, se vorbeşte des- pre un zeu, când nativii americani intră în cort, vorbesc cu zeul, când facem ceremonia noastră voodoo, noi devenim propriii zei." Este cât se poate de la persoana întâi.

Aţi putea argumenta că, deşi toate cele trei expresii - per- soana a treia, persoana a doua şi persoana întâi - sunt parte a unei relaţii umane sănătoase cu sacrul, am ajuns la un deze- chilibru al repartizării acestora. Cele mai multe dintre riturile noastre de trecere contemporane, de la baluri de absolvire şi jurăminte în frăţii, pe partea seculară, la bar mitzvah, comu- niune şi nunţi, pe partea religioasă, sunt pantomime la persoa- na a treia, care nu mai asigură legătura cu zeii. Taine placebo în toate privințele, cu excepția numelui. Astăzi suntem mult mai implicați în discuția la persoana a treia decât în imersiu- nea la persoana întâi sau a doua. Şi suferim din cauza asta.

** Sex, partea a 2-a
*** Despre asasini

Sus, intr-o ascunzătoare din munţi, în provincia Qazvin din Iran, un războinic musulman şiit antrena luptători pentru misiuni sinucigașe. Folosea metode foarte eficiente de îndoc- trinare şi spălare pe creier pentru a crea soldaţi absolut loiali, fanatici, care puteau penetra aproape orice apărare și vizau asasinarea unor diplomați importanți. Fără să le pese de pro- pria supraviețuire, zona lor de influenţă era aproape nelimitată

- agenţi operativi se infiltraseră cu succes în centre de putere din regiune şi eliminaseră zeci de oficiali de prim rang. Și în bătălia pentru,,inimi şi minţi" ajunseseră la nivelul psihologic la care aspiră toţi teroriștii -inculcaseră o teamă iraţională în duşmanii lor.

Pe măsură ce am început această descriere, am putut vedea cum creşte tensiunea în încăpere. Aceşti douăzeci şi ceva de operatori speciali, care se întinseseră relaxați ca niște lei tineri după o vânătoare, s-au ridicat în capul oaselor, cu ochii țintă la mine. Dacă acesta era succesorul lui Bin Laden sau un nou comandant ISIS, voiau să ştie totul despre el.

Insă Hassan-i Sabbah, liderul războinic al sectei ismailite şiite Nazari despre care discutam, nu avea să se afle în bătaia puştilor prea curând, oricât de mult l-ar fi căutat. Era o fanto- mă. Un cifru. De neatins. Impenetrabil. Mai mult, era mort de vreo mie de ani.

Hassan sau Bătrânul de pe Munte, cum era cunoscut, era unul dintre primii maeştri confirmaţi istoric ai Ingineriei Hedoniste

manciurian a imortalizat ideea unui agent adormit", progra mat să asasineze, inspirat fiind de această legendă. Seria de jocuri video de supersucces Assassin's Creed îşi are originile poveştii tot acolo, in castelul Alamut - fortăreaţa din munţi a lui Hassan.

Pe scurt, există mult mai multe lucruri imaginate despre Asasini (cum au ajuns să fie numiți) decât se ştiu cu certitudi- ne. Până şi originea numelui este disputată - unii cred că a izvorât direct din Hassan", in timp ce alții insistă că este o trimitere la Hashashin-acei fumători de haşiş care au devenit soldații săi. Însă metodele sale rămân un studiu de caz fasci- nant privind puterea de a manipula trupul şi creierul pentru a controla inimi şi minți.

Candidații la Ordin erau aduşi la castel în perechi şi invitați să ia masa cu Hassan însuşi. Hassan le spunea că are puterea să-i trimită în Paradis, dar numai dacă îi jurau loialitate eternă. Ascunsă în mâncarea lor era o capsulă cu eliberare lentă care conţinea opiu şi care le inducea o picoteală visătoare. Apoi ser- vitorii ii cărau pe inițiați într-o frumoasă Grădină a Deliciilor Pământeşti, înconjurată cu ziduri şi plină de pomi fructiferi exotici precum portocalul, numit „mărul paradisului”. Băieţilor persani de la țară trebuie să li se fi părut absolut fantastic.

Apoi capsula elibera efedră (care creşte în tufişuri prolifice în tot Orientul Mijlociu şi care este ingredientul principal pen- tru amfetamine) şi haşiş, revigorându-i pe candidați și adău gând strălucire la tot ce vedeau. Priveau în jur şi, pe bună dreptate, trăgeau concluzia că ajunseseră în Paradis. Hurii frumoase, virgine divine care, în legenda musulmană, însoţeau martirii către Paradis - în realitate, curtezane aduse din cele mai bune bordeluri din Cairo - îi înconjurau pe inițiaţi, cân- tând la fluiere, dansând și dezbrăcându-se jucăuş.

În cele din urmă, după cum descrie Robert Anton Wilson, unele cădeau la picioarele candidatului şi îi sărutau gleznele; altele îi sărutau genunchii sau coapsele, una îi sugea în extaz penisul, altele îi sărutau pieptul, brațele și pântecele, câteva îi sărutau ochii, gura şi urechile. Şi cum era prins în avalanșa de iubire intensificată de haşiş, doamna care se ocupa de penisul lui sugea şi tot sugea, iar el şi-a dat drumul în gura ei la fel de

delicat şi de încet şi de fericit ca un fulg de zăpadă care cade." Cam pe atunci, un al doilea val de opiu le pătrundea în sânge. Se întorceau la somn până când erau readuși în came- rele lui Hassan. Acolo îşi reveneau in simțiri.
