#+startup: indent fold
#+title: Jerusalem - Das Kochbuch

* Salate & Vorspeisen
** Auberginendip mit Knoblauch, Zitrone & Granatapfelkernen
:PROPERTIES:
:Source:    Jerusalem - Das Kochbuch
:Portions:  4
:Category:  Vorspeise
:Meal:      Teil eines Mezze-Tellers
:END:

*** Einführung
Dieser Dip hat ein herrlich rauchiges Aroma und passt gut zu gegrilltem Fleisch oder
Fisch. Aber auch zusammen mit anderen Dips und Salaten als Auftakt für ein üppiges
levantinisches Festessen darf er nicht fehlen. Um den vollen Durchgeschmack zu erzielen,
unbedingt die Anleitung genau befolgen und die Auberginen lange genug im Ofen lassen. Und
wenn Sie daraus ein "richtiges" Baba Ghanoush machen wollen (was immer das sein mag -
siehe Seite 76), beträufeln Sie das Ganze zum Schluss noch mit etwas heller Sesampaste.

*** Zutaten
| Menge | Einheit | Zutat                              |
|-------+---------+------------------------------------|
|     4 | große   | Auberginen (etwa 1,5 kg)           |
|     2 | Stück   | Knoblauchzehen, zerdrückt          |
|     1 | Stück   | Bio-Zitrone, abgeriebene Schale    |
|     2 | EL      | Zitronensaft                       |
|     5 | EL      | Olivenöl                           |
|     2 | EL      | gehackte glatte Petersilie         |
|     2 | EL      | gehackte Minze                     |
|   0.5 | Stück   | Granatapfel (80g) ausgelöste Kerne |
|       |         | Salz und schwarzer Pfeffer         |

*** Zubereitung
1. Wenn Sie einen Gasherd benutzen, zunächst die Topfträger abnehmen und das Kochfeld mit
   Alufolie auslegen, die Topfträger wieder aufsetzen.
2. Die Auberginen auf die Kochstellen verteilen und über der offenen Flamme 15-18 Minuten
   bei mittlerer Hitze rösten, bis die Schale verbrannt und rissig und das Fruchtfleisch
   weich ist.
3. Die Auberginen dabei gelegentlich mit einer Zange wenden.
4. Wer die Auberginen im Backofen röstet, sticht sie zunächst mehrfach mit einem Messer
   einige Zentimeter tief ein.
5. Dann auf ein Backblech legen und für etwa 1 Stunde unter den heißen Backofengrill
   schieben, bis sie aufplatzen und zerfallen.
6. Die Auberginen dabei etwa alle 20 Minuten wenden.
7. Die Auberginen etwas abkühlen lassen.
8. Eine Öffnung hineinschneiden, das Fruchtfleisch herauslösen und mit den Händen in lange
   dünne Streifen zerteilen.
9. Die Schalen wegwerfen.
10. Das Fruchtfleisch mindestens 1 Stunde in einem Sieb abtropfen lassen, um ihm die
    Flüssigkeit möglichst vollständig zu entziehen.
11. Danach sollten etwa 500g Fruchtfleisch übrig sein.
12. Das Fruchtfleisch in einer mittelgroßen Schüssel mit Knoblauch, dem größten Teil der
    Zitronenschale, Zitronensaft, Olivenöl, ½ Teelöffel Salz sowie frisch gemahlenem
    Pfeffer vermengen.
13. Anschließend mindestens 1 Stunde bei Zimmertemperatur durchziehen lassen.
14. Unmittelbar vor dem Servieren den größten Teil der Kräuter untermischen und das Püree
    noch einmal abschmecken.
15. Kuppelförmig auf einer Servierplatte anrichten, zum Schluss mit der restlichen
    Zitronenschale, den Granatapfelkernen und den übrigen Kräutern bestreuen.

*** Notizen
- Für ein "richtiges" Baba Ghanoush zum Schluss mit etwas heller Sesampaste beträufeln
- Die Auberginen können entweder über offener Flamme oder im Backofen geröstet werden
- Das lange Abtropfen ist wichtig für die richtige Konsistenz
** Balilah
:PROPERTIES:
:Source:    Jerusalem - Das Kochbuch
:Portions:  4
:Category:  Streetfood
:Meal:      Imbiss, Vorspeise
:END:

*** Einführung
Am Rande des Souks in der Jerusalemer Altstadt befand sich der Stand des außerordentlich
beliebten Balilah-Verkäufers, auf dem sich Berge dampfender, frisch gekochter und
appetitlich mit Petersilie und Zitrone garnierter Kichererbsen türmten. Gekonnt füllte er
seine Ware im Nu in eine Tüte aus Zeitungspapier und reichte sie dem Kunden, dem bereits
das Wasser im Munde zusammenlief.

Balilah ist ein außerordentlich beliebter palästinensischer Imbiss aus Kichererbsen,
gewürzt mit Kreuzkümmel und Zitronensaft. Lustigerweise bekommt man im jüdisch-orthodoxen
Viertel Me'ah She'arim einen ähnlichen, ebenso beliebten und preiswerten Snack, genannt
Arbes, hier allerdings findet anstelle von Kreuzkümmel schwarzer Pfeffer Verwendung.

*** Zutaten
| Menge | Einheit | Zutat                                         |
|-------+---------+-----------------------------------------------|
|   200 | g       | getrocknete Kichererbsen                      |
|     1 | TL      | Backnatron                                    |
|    60 | g       | glatte Petersilie, gehackt                    |
|     2 | Stück   | Frühlingszwiebeln, in feine Ringe geschnitten |
|     1 | große   | Zitrone                                       |
|     3 | EL      | Olivenöl                                      |
|   2.5 | TL      | gemahlener Kreuzkümmel                        |
|       |         | Salz und frisch gemahlener schwarzer Pfeffer  |

*** Zubereitung
1. Am Vorabend die Kichererbsen in einer großen Schüssel mit der doppelten Menge Wasser
   bedecken, das Backnatron hinzufügen und die Kichererbsen über Nacht einweichen.
2. Am nächsten Tag abgießen, in einen großen Topf füllen und mit kaltem Wasser bedecken.
3. Bei starker Hitze aufkochen lassen, abschäumen und 60-90 Minuten köcheln lassen, bis
   sie sehr weich sind, sie dürfen aber nicht zerfallen.
4. Inzwischen Petersilie und Frühlingszwiebeln in eine Schüssel geben.
5. Die Zitrone mit einem kleinen scharfen Messer schälen und dabei auch die weiße Haut mit
   entfernen.
6. Das Fruchtfleisch zwischen den Trennhäuten herauslösen, grob hacken und mit dem
   ausgepressten Saft ebenfalls in die Schüssel geben.
7. Die Kichererbsen abgießen und sofort in die Schüssel füllen.
8. Olivenöl, Kreuzkümmel, ¾ Teelöffel Salz sowie 1 kräftige Prise Pfeffer hinzufügen und
   alles gut durchmischen.
9. Etwas abkühlen lassen, noch einmal abschmecken und servieren.

*** Notizen
- Serviervorschläge:
  - Warm oder mit Zimmertemperatur als kleinen Imbiss
  - Als Beilage zu gegrilltem Huhn oder Fisch
  - Als Salat mit Salatblättern, Feta und Tomatenwürfeln
- Regionale Variante: Im jüdisch-orthodoxen Viertel wird statt Kreuzkümmel schwarzer
  Pfeffer verwendet (dann "Arbes" genannt)
- Das Einweichen über Nacht mit Backnatron ist wichtig für die richtige Konsistenz
- Traditionell in Zeitungspapier serviert
** Dip aus Butternusskürbis & Tahini
:PROPERTIES:
:Source:    Jerusalem - Das Kochbuch
:Portions:  6-8
:Category:  Vorspeise
:Meal:      Snack, Vorspeise
:END:

*** Einführung
Der Dattelsirup, der diesem Gericht sein intensives Aroma verleiht, ist ein beliebtes
natürliches Süßungsmittel. Man kann ihn für Dressings verwenden, Schmorgerichte damit
aromatisieren, aber auch auf Müsli schmeckt er prima. Sie bekommen ihn in Reformhäusern
und arabischen Lebensmittelgeschäften. Ersatzweise eignet sich Goldsirup, Ahornsirup oder
Melasse.

Wer diesen fantastischen Dip einmal probiert hat, wird nicht mehr von ihm loskommen. Nicht
von ungefähr ist die Kombination aus Tahini und Kürbis in Jerusalem so populär (Gebackener
Butternusskürbis, siehe Seite 36). Servieren Sie den Dip mit Brot als Vorspeise oder auf
einem Mezze-Teller.

*** Zutaten
| Menge | Einheit | Zutat                                                                         |
|-------+---------+-------------------------------------------------------------------------------|
|     1 | Stück   | Butternusskürbis, geschält und in Stücke geschnitten (etwa 1kg Fruchtfleisch) |
|     3 | EL      | Olivenöl                                                                      |
|     1 | TL      | Zimt                                                                          |
|    70 | g       | helles Tahini (Sesampaste)                                                    |
|   120 | g       | griechischer Joghurt                                                          |
|     2 | Stück   | Knoblauchzehen, zerdrückt                                                     |
|   0.5 | TL      | helle und dunkle Sesamsamen (oder 1 TL helle Sesamsamen)                      |
|   1.5 | TL      | Dattelsirup                                                                   |
|     2 | EL      | gehacktes Koriandergrün (nach Belieben)                                       |
|       |         | Salz                                                                          |

*** Zubereitung
1. Den Backofen auf 200°C vorheizen.
2. Die Kürbisstücke in einer ofenfesten Form oder in der Fettpfanne des Backofens
   verteilen, mit dem Olivenöl beträufeln und mit Zimt und ½ Teelöffel Salz bestreuen.
3. Das Ganze gut durchmischen, mit Alufolie abdecken und den Kürbis für 70 Minuten in den
   Backofen schieben.
4. Die Stücke nach der Hälfte der Zeit wenden. Anschließend aus dem Ofen nehmen und
   abkühlen lassen.
5. Den Kürbis mit Tahini, Joghurt und Knoblauch in der Küchenmaschine grob pürieren oder
   mit der Gabel oder dem Kartoffelstampfer zerdrücken.
6. Den Dip auf einer Servierplatte anrichten und mit einem Wellenmuster verzieren.
7. Die Oberfläche mit Sesamsamen bestreuen, mit dem Sirup beträufeln und nach Belieben mit
   Koriander garnieren.

*** Notizen
- Alternative Süßungsmittel: Goldsirup, Ahornsirup oder Melasse
- Kann als Vorspeise oder auf einem Mezze-Teller serviert werden
- Passt gut zu Brot
** Na'amas Fattoush
:PROPERTIES:
:Source:    Jerusalem - Das Kochbuch
:Portions:  4
:Category:  Salat
:Meal:      Vorspeise
:END:

*** Einführung
Ob auf den Tischen der arabischen oder der jüdischen Einwohner: Frischer Salat ist einfach
ein Muss. Egal wo, egal zu welcher Tageszeit und zu welchem Gericht - immer und überall
wird man Ihnen Salat aus gehackten Tomaten, Gurken und Zwiebel servieren, angemacht mit
Olivenöl und Zitronensaft. Wenn uns Freunde aus Jerusalem in London besuchen, klagen sie
stets über die »ungesunde« Ernährung, weil es nicht zu jeder Mahlzeit einen solchen Salat
gibt.

Es existieren zahlreiche Varianten, eine der beliebtesten ist Fattoush, eine arabische
Erfindung, angereichert mit geröstetem Pitabrot. Man kann aber auch noch Paprikaschoten,
Radieschen, Kopfsalat, Chilischoten, Minze, Petersilie, Korianderblätter, Piment, Zimt und
mehr Sumach hinzufügen. Jeder Koch, jede Familie, jede Stadt hat ihre eigenen Vorlieben.
Und auch wie fein man die Zutaten schneidet, ist reine Geschmackssache. Wichtig ist nur,
dass die Tomaten von guter Qualität, frisch und möglichst sonnengereift sind.

Diese herrliche Kreation mit Buttermilchdressing stammt vermutlich von Samis Mutter.
Zumindest kann sich Sami nicht daran erinnern, den Salat in dieser Form jemals anderswo
gegessen zu haben.

*** Zutaten
| Menge | Einheit | Zutat                             |
|-------+---------+-----------------------------------|
|   200 | g       | griechischer Joghurt              |
|   200 | ml      | Vollmilch                         |
|   250 | g       | altbackenes dickes Fladenbrot     |
|   350 | g       | Tomaten                           |
|   100 | g       | Radieschen                        |
|   250 | g       | Minigurken                        |
|     2 | St      | Frühlingszwiebeln                 |
|    15 | g       | Minze                             |
|    25 | g       | glatte Petersilie                 |
|     1 | EL      | getrocknete Minze                 |
|     2 | St      | Knoblauchzehen                    |
|     3 | EL      | Zitronensaft                      |
|    60 | ml      | Olivenöl                          |
|     2 | EL      | Apfel- oder Weißweinessig         |
|   3/4 | TL      | grob gemahlener schwarzer Pfeffer |
|   1.5 | TL      | Salz                              |
|     1 | EL      | gemahlener Sumach                 |

*** Zubereitung
1. Am Vortag Joghurt und Milch sorgfältig in einer Schüssel verrühren und im Kühlschrank
   ruhen lassen, bis sich Bläschen an der Oberfläche bilden. Das Ergebnis hat die
   Konsistenz von Buttermilch, schmeckt jedoch weniger sauer als die handelsüblichen
   Produkte.
2. Das Brot in mundgerechte Stücke reißen und in eine große Schüssel füllen. Die
   Joghurt-Milch-Mischung oder die Buttermilch und die übrigen Zutaten bis auf den Sumach
   dazugeben, alles gut vermengen und den Salat 10 Minuten durchziehen lassen.
3. Den Salat auf Portionsschalen verteilen, mit Olivenöl beträufeln und großzügig mit
   Sumach bestreuen.

*** Notizen
- Verwenden Sie für diesen und ähnliche Salate nach Möglichkeit Minigurken, die inzwischen
  in fast jedem Supermarkt angeboten werden. Sie sind um Längen besser als ihre "großen
  Schwestern".
- Um die Zubereitungszeit zu verkürzen, ersetzen Sie Joghurt und Milch einfach durch
  Buttermilch - dann entfällt die Wartezeit.
** Kohlrabisalat
:PROPERTIES:
:Source:    Jerusalem - Das Kochbuch
:Portions:  4
:Category:  Salat
:Meal:      Vorspeise/Beilage
:END:

*** Einführung
Kohlrabi ist schon ein recht ungewöhnliches Gemüse - eine Art Kohl mit verdickter
Sprossachse, der wie ein blassgrüner oder violetter Apfel aussieht und dessen
Fruchtfleisch in Textur und Geschmack dem von Rettich nicht unähnlich ist. Mit seiner
runden Knolle, aus der die langen, geraden Stiele mit den Blättern sprießen, wirkt er
geradezu wie ein Alien unter den Gemüsen. Das ist vielleicht auch der Grund, weshalb man,
von Deutschland einmal abgesehen, in der westlichen Welt nicht viel mit ihm anzufangen
weiß. In Israel aber liebt man ihn, sicher auch weil er so einfach zu ziehen ist und einen
schönen frischen Geschmack hat. In Jerusalem wird er vorwiegend zu frischen, knackigen
Salaten verarbeitet, mitunter auch in Kombination mit anderem Gemüse und Obst wie Fenchel,
Rettich, Kohl oder Äpfeln. Aber auch in sahnigen Gratins oder gefüllt erfreut sich
Kohlrabi großer Beliebtheit.

*** Zutaten
| Menge | Einheit | Zutat                            |
|-------+---------+----------------------------------|
|     3 | St      | mittelgroße Kohlrabi (750g)      |
|    80 | g       | griechischer Joghurt             |
|    70 | g       | saure Sahne                      |
|    50 | g       | Sahne                            |
|     1 | St      | kleine Knoblauchzehe             |
|   1.5 | TL      | Zitronensaft                     |
|     1 | EL      | Olivenöl                         |
|     2 | EL      | frische, fein geschnittene Minze |
|     1 | TL      | getrocknete Minze                |
|    20 | g       | Brunnenkresse                    |
|  0.25 | TL      | gemahlener Sumach                |
|     - | -       | Salz und weißer Pfeffer          |

*** Zubereitung
1. Kohlrabi schälen, in 1,5 cm große Würfel schneiden und in eine große Schüssel füllen.

2. Den Joghurt in einer kleinen Schüssel mit saurer und süßer Sahne, Knoblauch,
   Zitronensaft, Olivenöl, ¼ Teelöffel Salz sowie 1 kräftigen Prise Pfeffer verrühren und
   das Dressing über die Kohlrabiwürfel gießen.

3. Die Minze und die Hälfte der Brunnenkresse hinzufügen. Den Salat vorsichtig
   durchmischen, in einer Servierschüssel anrichten und mit der restlichen Brunnenkresse
   und dem Sumach bestreuen.

*** Notizen
- Dieser einfache, frische Salat, den man vor oder nach dem Hauptgang genießen kann, ist
  im NOPI, unserem Restaurant im Londoner Westend, entstanden. Zusammen mit anderen
  Salaten oder gekochtem Gemüse wird daraus eine leichte Hauptmahlzeit.
- Verwenden Sie möglichst kleine Kohlrabi mit fester, glatter Schale.
** Rote-Bete-Püree mit Joghurt und Za'atar
:PROPERTIES:
:Source:    Jerusalem - Das Kochbuch
:Portions:  6
:Category:  Gemüse
:Meal:      Vorspeise
:END:

*** Einführung
Rote Bete zählt zu den wenigen Gemüsen, die in den Küchen fast aller Jerusalemer
Bevölkerungsgruppen stark vertreten sind. Man findet sie auf fast jedem Mezze-Teller und
sie bildet die Grundlage für Borschsch und Hamitsa, eine frische kalte Variante der
Fischsuppe. Darüber hinaus ist sie die Hauptzutat einer anderen Suppe, die aus der
jüdisch-irakischen und der jüdisch-kurdischen Küche stammt und in der die berühmten Kubbeh
(siehe Seite 162) serviert werden.

Bei den Dreharbeiten zu einer Dokumentation über die Jerusalemer Küche lernte Yotam Michal
Baranes und Yakub Barhum kennen. Sie ist Jüdin mit marokkanischen Wurzeln, er ist Moslem
und stammt aus der am Rand Jerusalems gelegenen arabischen Ortschaft Ein Raffa. In ihrem
Restaurant bieten die beiden eine einfache israelische Küche mit marokkanischen Elementen
und eine Vielzahl traditioneller palästinensischer Gerichte an. Michals »Allzweckwaffe«
ist Chrein, ein Relish aus Meerrettich und Roter Bete, das in keinem aschkenasischen
Haushalt fehlt und das sie beispielsweise für ihre Garnelen-Falafel – fein gehackte
Garnelen, mit Panko-Mehl paniert und anschließend frittiert – verwendet.

*** Zutaten
| Menge | Einheit | Zutat                         |
|-------+---------+-------------------------------|
|   900 | g       | mittelgroße Rote-Bete-Knollen |
|     2 | St      | Knoblauchzehen                |
|     1 | St      | kleine rote Chilischote       |
|   250 | g       | griechischer Joghurt          |
|   1.5 | EL      | Dattelsirup                   |
|     3 | EL      | Olivenöl                      |
|     1 | EL      | Za'atar                       |
|     - | -       | Salz                          |

*** Zum Garnieren
| Menge | Einheit | Zutat              |
|-------+---------+--------------------|
|     2 | St      | Frühlingszwiebeln  |
|    15 | g       | Haselnusskerne     |
|    60 | g       | weicher Ziegenkäse |

*** Zubereitung
1. Den Backofen auf 200°C vorheizen.

2. Die Rote-Bete-Knollen waschen, in eine ofenfeste Form legen und ohne Deckel etwa 1
   Stunde im Backofen garen, bis sich ein Messer mühelos hineinstecken lässt. Etwas
   abkühlen lassen, schälen, sechsteln und vollständig erkalten lassen.

3. Rote Bete mit Knoblauch, Chili und Joghurt in der Küchenmaschine zu einem glatten Püree
   verarbeiten und in eine große Schüssel füllen. Dattelsirup, Öl, Za'atar sowie 1
   Teelöffel Salz unterrühren und das Püree noch einmal abschmecken.

4. Das Püree in eine Servierschale füllen und mit einem Löffelrücken glatt streichen. Mit
   Frühlingszwiebeln, Haselnüssen und Käse bestreuen, mit etwas Olivenöl beträufeln und
   zimmerwarm servieren.

*** Notizen
- Sie werden staunen, wie gut die Rote Bete mit Chilischoten und Za'atar harmoniert. Kein
  Wunder, dass sich dieses Gericht bei den Gästen des Ottolenghi in London besonderer
  Beliebtheit erfreut.
- Servieren Sie das Püree als Dip oder mit Brot als Vorspeise.
- Ist es zu flüssig, dicht man es einfach mit etwas zerdrückter gekochter Kartoffel an.
- Der Dattelsirup kann durch Ahornsirup ersetzt werden.
** Rote-Bete-Salat mit Walnüssen
:PROPERTIES:
:Source:    Jerusalem - Das Kochbuch
:Portions:  4
:Category:  Salat
:Meal:      Vorspeise, Beilage
:END:

*** Einführung
Dieser köstliche Salat ist von der georgischen Küche (siehe Seite 71) inspiriert. Die Rote
Bete und der Lauch können bis zu einen Tag im Voraus gegart werden. Damit die Rote Bete
den Lauch nicht verfärbt, beides getrennt aufbewahren (es sei denn, solche ästhetischen
Überlegungen sind nebensächlich für Sie). Für den Salat eignen sich auch gelbe, weiße oder
gestreifte Bete-Knollen.

*** Zutaten
| Menge | Einheit     | Zutat                                                  |
|-------+-------------+--------------------------------------------------------|
|     4 | mittelgroße | Rote-Bete-Knollen (600g gegrates Fruchtfleisch)        |
|     4 | mittelgroße | Stangen Lauch (360g), in 10cm große Stücke geschnitten |
|    15 | g           | Koriandergrün, grob gehackt                            |
|    25 | g           | Rucola                                                 |
|    50 | g           | Granatapfelkerne (nach Belieben)                       |
|       |             | Salz                                                   |

Für das Dressing:
| Menge | Einheit | Zutat                                     |
|-------+---------+-------------------------------------------|
|   100 | g       | Walnusskerne, grob gehackt                |
|     4 | Stück   | Knoblauchzehen, fein gehackt              |
|  0.25 | TL      | Chiliflocken                              |
|    60 | ml      | Apfelessig                                |
|     1 | EL      | Tamarindenpaste, mit 1 EL Wasser verrührt |
|   0.5 | TL      | Walnussöl                                 |
|  2.25 | EL      | Erdnussöl                                 |
|     1 | TL      | Salz                                      |

*** Zubereitung
1. Den Backofen auf 220°C vorheizen.
2. Die Rote-Bete-Knollen einzeln in Alufolie verpacken und je nach Größe 60-90 Minuten im
   Backofen garen.
3. Für die Garprobe mit einem spitzen Messer in die Knollen hineinstechen. Es sollte
   mühelos eindringen.
4. Aus dem Ofen nehmen und etwas abkühlen lassen.
5. Die Knollen schälen, halbieren, die Hälften in 1cm dicke Spalten schneiden und in eine
   mittelgroße Schüssel füllen.
6. Den Lauch in einen mittelgroßen Topf mit Salzwasser geben, zum Kochen bringen und 10
   Minuten köcheln lassen.
7. Den Lauch bei geringer Hitze garen, damit er nicht zerfällt.
8. In ein Sieb abgießen, unter fließendem kaltem Wasser abschrecken, die Stücke mit einem
   sehr scharfen Sägemesser dritteln und trocken tupfen.
9. In eine Schüssel füllen und zur Seite stellen.
10. Während das Gemüse gart, die Dressingzutaten verrühren und die Sauce mindestens 10
    Minuten durchziehen lassen.
11. Dressing und Koriandergrün gleichmäßig auf die beiden Gemüse verteilen, vorsichtig
    durchmischen und noch einmal abschmecken.
12. Den größten Teil der Rote-Bete-Spalten auf einer Servierplatte anrichten, etwas Rucola
    und danach den größten Teil des Lauchs darauf verteilen.
13. Das restliche Gemüse daraufgeben, gefolgt von den übrigen Rucolablättern.
14. Den Salat nach Belieben mit Granatapfelkernen bestreuen und servieren.

*** Notizen
- Rote Bete und Lauch können bis zu einem Tag im Voraus zubereitet werden
- Getrennt aufbewahren, wenn die Rote Bete den Lauch nicht verfärben soll
- Alternative Bete-Sorten: gelbe, weiße oder gestreifte Knollen
- Granatapfelkerne sind optional
** Spinatsalat mit Datteln & Mandeln
:PROPERTIES:
:Source:    Jerusalem - Das Kochbuch
:Portions:  4
:Category:  Salat
:Meal:      Vorspeise
:END:

*** Einführung
Pitabrot schmeckt am besten frisch aus dem Ofen, deshalb ist es in Jerusalem immer rasch
ausverkauft. Altbacken eignet es sich hervorragend für Croûtons, die wir gerne über
Suppen, Salate und andere Mezze streuen. Luftdicht verschlossen halten sich die Croûtons
bis zu einer Woche. Dieser frische, pikante Salat ist eine Vorspeise, die so richtig
Appetit macht.

*** Zutaten
| Menge | Einheit | Zutat                    |
|-------+---------+--------------------------|
|     1 | EL      | Weißweinessig            |
|   1/2 | St      | mittelgroße rote Zwiebel |
|   100 | g       | Medjoul-Datteln          |
|    30 | g       | Butter                   |
|     2 | EL      | Olivenöl                 |
|     2 | St      | kleine Pitabrote         |
|    75 | g       | Mandeln                  |
|     2 | TL      | gemahlener Sumach        |
|   1/2 | TL      | Chiliflocken             |
|   150 | g       | junger Spinat            |
|     2 | EL      | Zitronensaft             |
|     - | -       | Salz                     |

*** Zubereitung
1. Essig, Zwiebel, Datteln und 1 Prise Salz in einer kleinen Schüssel mit den Händen
   vermengen. Die Mischung 20 Minuten ziehen lassen und danach in ein Sieb abgießen. Die
   Flüssigkeit wegschütten.

2. Inzwischen die Butter mit der Hälfte des Öls in einer mittelgroßen Pfanne erhitzen.
   Pitabrot und Mandeln hineingeben und unter stetigem Wenden 4-6 Minuten bei mittlerer
   Hitze rösten, bis das Brot goldbraun und knusprig ist. Die Pfanne vom Herd nehmen,
   Sumach, Chiliflocken und 1/4 Teelöffel Salz untermischen und beiseitestellen.

3. Die Spinatblätter unmittelbar vor dem Servieren in eine große Schüssel füllen, die
   Pita-Mandel-Mischung, Datteln, Zwiebel, das restliche Öl, Zitronensaft sowie 1 Prise
   Salz hinzufügen und die Zutaten durchmischen. Noch einmal abschmecken und sofort
   servieren.

*** Notizen
- Pitabrot schmeckt am besten frisch aus dem Ofen, deshalb ist es in Jerusalem immer rasch
  ausverkauft.
- Altbacken eignet es sich hervorragend für Croûtons, die für Suppen, Salate und andere
  Mezze verwendet werden können.
- Luftdicht verschlossen halten sich die Croûtons bis zu einer Woche.
** Tabbouleh
:PROPERTIES:
:Source:    Jerusalem - Das Kochbuch
:Portions:  mindestens 4
:Category:  Salat
:Meal:      Vorspeise, Beilage
:END:

*** Einführung
"Wenn du einen guten Mann finden willst, solltest du lernen, Petersilie richtig zu
hacken", tadelte Samis Mutter seine Schwester als Teenager. Tatsächlich kommt es beim
Tabbouleh ganz besonders auf die Petersilie an. Sie ist die wichtigste Zutat, und das
nicht nur in diesem Gericht, sondern überhaupt in der palästinensischen Küche. Und sie
will mit Respekt und Geschick behandelt werden.

Das Rezept stammt ursprünglich aus dem Libanon und aus Syrien. Ein gutes Tabbouleh besteht
aus viel frischer Petersilie und Minze, vorsichtig von Hand gehackt. Anschließend werden
die Kräuter kräftig gewürzt und mit Tomatenwürfeln und Bulgur gemischt. Das Verhältnis von
Petersilie und Bulgur variiert. Im Libanon verwendet man etwas weniger Bulgur, in
Palästina etwas mehr. In jedem Fall aber ist die Petersilie die Hauptzutat – Tabbouleh ist
ein Petersilien- und kein Bulgursalat.

*** Zutaten
| Menge | Einheit    | Zutat                                           |
|-------+------------+-------------------------------------------------|
|    30 | g          | feiner Bulgur                                   |
|     2 | große      | reife, aber feste Tomaten (300g)                |
|     1 | Stück      | Schalotte, fein gehackt                         |
|     3 | EL         | Zitronensaft, plus Zitronensaft zum Abschmecken |
|     4 | große Bund | glatte Petersilie (160g)                        |
|     2 | Bund       | Minze (30g)                                     |
|     2 | TL         | gemahlener Piment                               |
|     1 | TL         | Baharat-Gewürzmischung (siehe Seite 299)        |
|    80 | ml         | Olivenöl                                        |
|    70 | g          | Granatapfelkerne (nach Belieben)                |
|       |            | Salz und schwarzer Pfeffer                      |

*** Zubereitung
1. Den Bulgur in ein feines Sieb geben und unter fließendem kaltem Wasser waschen, bis das
   Wasser klar bleibt und die Stärke weitgehend abgespült ist. Den Bulgur anschließend in
   eine Schüssel füllen.
2. Die Tomaten mit einem Sägemesser zunächst in 0,5cm dicke Scheiben, dann in 0,5cm breite
   Streifen und schließlich in Würfel schneiden. Die Tomatenwürfel mit ihrem Saft, der
   Schalotte und dem Zitronensaft zu dem Bulgur geben und alles gut durchmischen.
3. Ein paar Stängel Petersilie fest zusammendrücken. Mit einem großen, sehr scharfen
   Messer den größten Teil der Stiele abschneiden und wegwerfen.
4. Die Blätter anschließend so fein wie möglich (die Stücke dürfen maximal 1mm groß sein)
   hacken und zu den übrigen Zutaten in die Schüssel geben. Auf diese Weise die gesamte
   Petersilie zerkleinern.
5. Die Minzeblätter abzupfen, zusammendrücken und ebenso fein hacken wie die Petersilie.
   Die Blätter dabei nicht zerquetschen, damit sie ihre schöne grüne Farbe behalten. Die
   gehackte Minze ebenfalls in die Schüssel geben.
6. Zum Schluss Piment, Baharat, Olivenöl und nach Belieben die Granatapfelkerne
   hinzufügen.
7. Den Salat mit Salz, Pfeffer und eventuell noch etwas Zitronensaft abschmecken und
   servieren.

*** Notizen
- Das richtige Hacken der Petersilie ist essentiell - die Stücke dürfen maximal 1mm groß
  sein
- Regional unterschiedliche Bulgur-Mengen: Im Libanon weniger, in Palästina mehr
- Petersilie ist die Hauptzutat, nicht der Bulgur
- Granatapfelkerne sind optional
- Traditionell wird Tabbouleh mit kleinen Salatblättern aufgenommen, nicht mit Löffel oder
  Gabel
- Eignet sich als Vorspeise oder als Beilage zu Fleisch- und Fischgerichten
** Würzige Kichererbsen mit buntem Salat
:PROPERTIES:
:Source:    Jerusalem - Das Kochbuch
:Portions:  4
:Category:  Gemüse
:Meal:      Hauptgericht
:END:

*** Einführung
Die Anregung zu diesem Gericht fand ich nicht eigentlich in der Jerusalemer Küche, sondern
vielmehr im Morito, einer großartigen Tapas-Bar in London. Die Speisen, die die Besitzer,
Samantha und Samuel Clark, dort anbieten, sind von der südspanischen, nordafrikanischen
und orientalischen Küche geprägt, die viele Ähnlichkeiten mit den kulinarischen
Traditionen Jerusalems aufweisen. Die Kombination aus kaltem, frischem Salat und warmen
Kichererbsen ist einfach unwiderstehlich. Dazu braucht man eigentlich nichts anderes als
warmes Pitabrot. Aber auch Hummus (siehe Seite 114) oder Frittierter Blumenkohl in
Tahini-Sauce (siehe Seite 60) passen sehr gut dazu. Den Salat kann man auch ohne die
Kichererbsen servieren (in diesem Fall den Zucker weglassen).

*** Zutaten
| Menge | Einheit | Zutat                                |
|-------+---------+--------------------------------------|
|     1 | TL      | Backnatron                           |
|   100 | g       | getrocknete Kichererbsen             |
|     2 | St      | Minigurken (280g)                    |
|     2 | St      | große Tomaten (300g)                 |
|   240 | g       | Radieschen                           |
|     1 | St      | rote Paprikaschote                   |
|     1 | St      | kleine rote Zwiebel                  |
|    20 | g       | Koriandergrün                        |
|    15 | g       | glatte Petersilie                    |
|    90 | ml      | Olivenöl                             |
|     1 | St      | Bio-Zitrone (Schale)                 |
|     2 | EL      | Zitronensaft                         |
|   1.5 | EL      | Sherryessig                          |
|     1 | St      | Knoblauchzehe                        |
|     1 | TL      | Zucker                               |
|     1 | TL      | gemahlener Kardamom                  |
|   1.5 | TL      | gemahlener Piment                    |
|     1 | TL      | gemahlener Kreuzkümmel               |
|     - | -       | griechischer Joghurt (nach Belieben) |
|     - | -       | Salz und schwarzer Pfeffer           |

*** Zubereitung
1. Eine große Schüssel mit Wasser füllen, das Backnatron hinzufügen und die Kichererbsen
   über Nacht darin einweichen. Am nächsten Tag abgießen, in einen großen Topf füllen und
   mit der doppelten Menge Wasser bedecken. Aufkochen, falls nötig abschäumen und etwa 1
   Stunde köcheln lassen, bis die Kichererbsen weich sind. Anschließend in ein Sieb
   abgießen und abtropfen lassen.

2. Gurken, Tomaten, Radieschen und Paprikaschote in 1,5 cm große Würfel schneiden. Die
   Zwiebel fein hacken und alles in einer Schüssel mit den Kräutern mischen.

3. In einem Schraubglas 75 ml Olivenöl sorgfältig mit Zitronenschale und -saft, Essig,
   Knoblauch und Zucker vermischen. Das Dressing mit Salz und Pfeffer abschmecken, über
   den Salat gießen und kurz durchmischen.

4. Kardamom, Piment, Kreuzkümmel mit ¼ Teelöffel Salz mischen und auf einen Teller
   streuen. Die Kichererbsen in der Gewürzmischung wenden, bis sie gleichmäßig damit
   überzogen sind. Das restliche Öl bei mittlerer Temperatur in einer Pfanne heiß werden
   lassen und die Kichererbsen 2-3 Minuten darin braten. Die Pfanne dabei vorsichtig
   rütteln, damit die Kichererbsen nicht anhängen und gleichmäßig gebräunt werden.

5. Den Salat auf vier Teller verteilen und die Kichererbsen in der Mitte anrichten. Nach
   Belieben mit etwas griechischem Joghurt garnieren und servieren.

*** Notizen
- Das Gericht kann auch ohne Kichererbsen serviert werden - in diesem Fall den Zucker
  weglassen
- Passt gut zu Hummus oder Frittiertem Blumenkohl in Tahini-Sauce
- Warmes Pitabrot ist die ideale Beilage
** Zucchini-Tomaten-Salat
:PROPERTIES:
:Source:    Jerusalem - Das Kochbuch
:Portions:  6
:Category:  Salat
:Meal:      Vorspeise, Beilage
:END:

*** Einführung
Dies ist die Variante eines beliebten palästinensischen Salats, Matbucha, der sich auch
als Belag für Crostini eignet. Traditionell wurde das Gemüse im Tabun gegart, einem
Tonofen, der sich in den Dörfern in der Regel außerhalb der Häuser befand. Das
Originalrezept wird mit gegrillten Tomaten und Zucchini, Knoblauch, Buttermilch und
Petersilie zubereitet. Wir haben es noch mit diesem und jenem angereichert und so ist eine
herrliche Vorspeise entstanden, zu der man am besten nur etwas knuspriges Brot reicht. Das
Gemüse kann natürlich auch auf dem Holzkohlengrill zubereitet werden.

*** Zutaten
| Menge | Einheit | Zutat                                                |
|-------+---------+------------------------------------------------------|
|     8 | Stück   | Zucchini (etwa 1kg)                                  |
|     5 | große   | sehr reife Tomaten (800g)                            |
|     3 | EL      | Olivenöl, plus Olivenöl zum Beträufeln               |
|   200 | g       | griechischer Joghurt                                 |
|     2 | Stück   | Knoblauchzehen, zerdrückt                            |
|     2 | Stück   | rote Chilischoten, von den Samen befreit und gehackt |
|     1 | Stück   | mittelgroße Bio-Zitrone, abgeriebene Schale          |
|     2 | EL      | Zitronensaft                                         |
|     1 | EL      | Dattelsirup, plus Dattelsirup zum Beträufeln         |
|   200 | g       | Walnusskerne, grob gehackt                           |
|     2 | EL      | gehackte Minze                                       |
|    20 | g       | glatte Petersilie, gehackt                           |
|       |         | Salz und schwarzer Pfeffer                           |

*** Zubereitung
1. Den Backofen auf 220°C vorheizen. Eine Grillpfanne auf den Herd stellen und bei starker
   Hitze heiß werden lassen.
2. Die Zucchini der Länge nach halbieren, die Stielansätze entfernen.
3. Die Tomaten ebenfalls halbieren. Die Schnittflächen von Tomaten und Zucchini mit
   Olivenöl bestreichen und mit Salz und Pfeffer bestreuen.
4. Die Zucchinihälften mit der Schnittfläche nach unten in die sehr heiße Pfanne legen und
   portionsweise 5 Minuten grillen, bis sie dunkle Streifen zeigen.
5. Mit den Tomaten ebenso verfahren.
6. Tomaten und Zucchini anschließend in einer ofenfesten Form verteilen und für etwa 20
   Minuten in den Backofen schieben, bis die Zucchini sehr weich sind.
7. Herausnehmen und etwas abkühlen lassen. Grob hacken, dann 15 Minuten in einem Sieb
   abtropfen lassen.
8. In einer großen Schüssel den Joghurt mit Knoblauch, Chili, Zitronenschale, Zitronensaft
   und Dattelsirup verrühren.
9. Das gehackte Gemüse, Walnusskerne, Minze sowie den größten Teil der Petersilie
   hinzufügen.
10. Alles gut durchmischen und mit ¾ Teelöffel Salz und etwas Pfeffer würzen.
11. Den Salat in einer flachen Schüssel gleichmäßig verteilen.
12. Mit der restlichen Petersilie bestreuen und mit etwas Dattelsirup und Olivenöl
    beträufeln.

*** Notizen
- Das Gemüse kann alternativ auf einem Holzkohlengrill zubereitet werden
- Traditionell wird das Gericht im Tonofen (Tabun) gegart
- Als Beilage wird knuspriges Brot empfohlen
- Eignet sich auch als Belag für Crostini
* Suppen                                                                                     :suppe:
** Auberginensuppe mit Mograbieh
:PROPERTIES:
:Source:    Jerusalem - Das Kochbuch
:Portions:  4
:Category:  Suppe
:Meal:      Vorspeise, Hauptgericht
:END:

*** Einführung
Mograbieh, gelegentlich auch Maftoul (siehe Seite 139), bekommt man in orientalischen
Lebensmittelläden oder über das Internet. Fregola, eine sardische Spezialität, findet man
in italienischen Geschäften. Was immer Sie für diese herrliche, gehaltvolle Suppe
verwenden, halten Sie sich in puncto Kochzeit genau an die Packungsanweisung, denn die
Kügelchen sollten unbedingt bissfest sein. Servieren Sie im Anschluss etwas Leichtes wie
Omelette mit Dicken Bohnen (siehe Seite 39) oder Gebratene Makrele mit
Gelbe-Bete-Orangen-Salsa (siehe Seite 222).

*** Zutaten
| Menge | Einheit | Zutat                                                                                |
|-------+---------+--------------------------------------------------------------------------------------|
|     5 | kleine  | Auberginen (etwa 1,2kg)                                                              |
|   150 | ml      | Sonnenblumenöl                                                                       |
|     1 | Stück   | Zwiebel (125g), in Scheiben geschnitten                                              |
|     1 | EL      | frisch gemahlene Kreuzkümmelsamen                                                    |
|   0.5 | TL      | Tomatenmark                                                                          |
|     2 | große   | Tomaten (350g), enthäutet und in Würfel geschnitten                                  |
|   350 | ml      | Hühner- oder Gemüsebrühe                                                             |
|     4 | Stück   | Knoblauchzehen, zerdrückt                                                            |
|   2.5 | TL      | Zucker                                                                               |
|     2 | EL      | Zitronensaft                                                                         |
|   100 | g       | Mograbieh (ersatzweise Maftoul, Fregola oder israelischer Couscous; siehe Seite 139) |
|     2 | EL      | Basilikumblätter, in Streifen geschnitten, oder 1 EL gehackter Dill (nach Belieben)  |
|       |         | Salz und schwarzer Pfeffer                                                           |

*** Zubereitung
1. Zunächst 3 Auberginen rösten wie im Rezept Auberginendip mit Knoblauch, Zitrone und
   Granatapfelkernen (siehe Seite 79) beschrieben.
2. Die restlichen Auberginen in 1,5cm große Würfel schneiden.
3. Das Sonnenblumenöl bei mittlerer bis hoher Temperatur in einem großen Topf erhitzen und
   die Auberginenwürfel 10-15 Minuten unter häufigem Rühren goldbraun frittieren.
4. Dabei falls nötig noch etwas Öl hinzufügen.
5. Die Auberginen herausnehmen, in einem Sieb abtropfen lassen und mit Salz bestreuen.
6. Zwiebel und Kreuzkümmel in den Topf geben (vorher prüfen, ob noch mindestens 1
   Esslöffel Öl im Topf ist) und 7 Minuten unter häufigem Rühren anbraten.
7. Das Tomatenmark einrühren und 1 Minute anschwitzen.
8. Tomaten, Brühe, 400ml Wasser, Knoblauch, Zucker und Zitronensaft hinzufügen, mit 1½
   Teelöffeln Salz und etwas Pfeffer würzen und das Ganze 15 Minuten köcheln lassen.
9. Inzwischen in einem kleinen Topf Wasser aufkochen, salzen und den Mograbieh nach
   Packungsanweisung bissfest garen (die Kochzeit beträgt 15-18 Minuten).
10. Anschließend unter fließendem kaltem Wasser abschrecken.
11. Das Fleisch der gerösteten Auberginen auslösen und zur Suppe geben.
12. Das Ganze mit dem Stabmixer glatt pürieren.
13. Mograbieh und frittierte Auberginenwürfel (von beidem etwas zum Garnieren aufheben)
    dazugeben und die Suppe noch einmal abschmecken.
14. Mograbieh und Auberginenwürfel darüberstreuen und nach Belieben mit Basilikum oder
    Dill garnieren.

*** Notizen
- Alternative Nudeln:
  - Maftoul
  - Fregola (sardische Spezialität)
  - Israelischer Couscous
- Die Kügelchen müssen unbedingt bissfest sein
- Serviervorschläge für den Hauptgang:
  - Omelette mit Dicken Bohnen
  - Gebratene Makrele mit Gelbe-Bete-Orangen-Salsa
- Ein Teil der Auberginen wird geröstet, der andere Teil wird frittiert
- Garnierung kann mit Basilikum oder Dill erfolgen
** Tomatensuppe
:PROPERTIES:
:Source:    Jerusalem - Das Kochbuch
:Portions:  unbekannt
:Category:  Suppen
:Meal:      Hauptgericht
:END:

*** Einführung
Mehr als diese recht überschaubare Auswahl an Zutaten benötigen Sie nicht, um eine
ausgesprochen köstliche Suppe zuzubereiten.

*** Zutaten
| Menge | Einheit | Zutat                         |
|-------+---------+-------------------------------|
|     2 | EL      | Olivenöl                      |
|     1 | große   | Zwiebel (250g), gehackt       |
|     1 | TL      | Kreuzkümmel                   |
|     2 |         | Knoblauchzehen, zerdrückt     |
|   750 | ml      | Gemüsebrühe                   |
|     4 | große   | reife Tomaten (650g), gehackt |
|     1 | Dose    | Tomatenstücke (400g)          |
|     1 | EL      | Zucker                        |
|     1 | Scheibe | Sauerteigbrot (40g)           |
|     3 | EL      | gehacktes Koriandergrün       |
|       |         | Salz und schwarzer Pfeffer    |
|       |         | Olivenöl zum Beträufeln       |

*** Zubereitung
1. Das Öl in einem mittelgroßen Topf erhitzen und die Zwiebel etwa 5 Minuten unter
   häufigem Rühren glasig anschwitzen.
2. Kreuzkümmel und Knoblauch dazugeben und 2 Minuten mitbraten.
3. Die Brühe angießen, Tomatenwürfel, Dosentomaten sowie Zucker hinzufügen und mit 1
   Teelöffel Salz sowie 1 kräftigen Prise Pfeffer würzen.
4. Die Suppe zum Köcheln bringen und 20 Minuten köcheln lassen.
5. Nach der Hälfte der Zeit das in Stücke gebrochene Brot hinzufügen.
6. Zum Schluss 2 Esslöffel Koriandergrün unterrühren.
7. Die Suppe kurz im Mixer pürieren (sie sollte noch Tomatenstücke enthalten und relativ
   dick sein). Falls nötig, mit etwas Wasser verdünnen.
8. Mit Olivenöl beträufeln und mit dem restlichen Koriandergrün bestreuen.

*** Notizen
- Der Text erwähnt zusätzliches Olivenöl zum Beträufeln am Ende
- Die Konsistenz sollte relativ dick sein und noch Tomatenstücke enthalten
- Nach Bedarf kann die Suppe mit Wasser verdünnt werden
* Hauptgerichte                                                                      :hauptgerichte:
** Auberginen mit Chermoula, Bulgur & Joghurt
:PROPERTIES:
:Source:    Jerusalem - Das Kochbuch
:Portions:  4
:Category:  Gemüse
:Meal:      Hauptgericht
:END:

*** Einführung
Früher ernährte sich vor allem die Landbevölkerung von Bulgur, während die wohlhabenderen
Städter Reis bevorzugten. Auch bei vielen Palästinensern gehörten die gedämpften,
getrockneten und zu Grieß gemahlenen Hartweizenkörner zu den Grundnahrungsmitteln. Heute
erfreut sich Bulgur in allen Schichten wachsender Beliebtheit und wird besonders gerne für
Salate und Mezze verwendet.

Chermoula ist eine nordafrikanische Würzpaste, mit der man Fisch, Fleisch und Gemüse
aromatisiert. Die mit Chermoula gewürzten Auberginen werden hier noch mit kaltem Joghurt
beträufelt. Zusammen mit dem süßlich-salzigen Bulgursalat wird daraus ein vegetarischer
Festschmaus.

*** Zutaten
| Menge | Einheit | Zutat                                         |
|-------+---------+-----------------------------------------------|
|     2 | St      | Knoblauchzehen                                |
|     2 | TL      | gemahlener Kreuzkümmel                        |
|     2 | TL      | gemahlener Koriander                          |
|     1 | TL      | Chiliflocken                                  |
|     1 | TL      | Paprikapulver edelsüß                         |
|     2 | EL      | fein gehackte Schale von eingelegten Zitronen |
|   140 | ml      | Olivenöl                                      |
|     2 | St      | mittelgroße Auberginen                        |
|    50 | g       | feiner Bulgur                                 |
|    25 | g       | Sultaninen                                    |
|    10 | g       | Koriandergrün                                 |
|    10 | g       | frische Minze                                 |
|     6 | St      | grüne Oliven                                  |
|     1 | EL      | Mandelblättchen                               |
|     2 | St      | Frühlingszwiebeln                             |
|   1.5 | EL      | Zitronensaft                                  |
|   120 | g       | griechischer Joghurt                          |
|     - | -       | Salz                                          |

*** Zubereitung
1. Den Backofen auf 200°C vorheizen.

2. Für die Chermoula in einer kleinen Schüssel Knoblauch, Kreuzkümmel, Koriander, Chili,
   Paprikapulver, die Schale der eingelegten Zitronen, zwei Drittel des Olivenöls sowie ¼
   Teelöffel Salz vermengen.

3. Die Auberginen der Länge nach halbieren und das Fruchtfleisch rautenförmig
   einschneiden. Dabei darauf achten, dass die Schale intakt bleibt. Die Hälften
   gleichmäßig mit Chermoula bestreichen, mit der Schnittfläche nach oben auf ein
   Backblech legen und 40 Minuten im Backofen garen.

4. Inzwischen den Bulgur in einer Schüssel mit 140 ml kochendem Wasser übergießen.

5. Die Sultaninen 10 Minuten in 50 ml warmem Wasser einweichen, anschließend abgießen und
   mit dem restlichen Öl zu dem Bulgur geben. Kräuter, Oliven, Mandelblättchen,
   Frühlingszwiebeln und Zitronensaft hinzufügen, mit 1 Prise Salz würzen und alles gut
   durchmischen. Den Salat danach noch einmal abschmecken.

6. Die Auberginenhälften auf vier Teller verteilen, den Bulgursalat darauf anrichten und
   mit dem Joghurt garnieren. Das gehackte Koriandergrün darüberstreuen, etwas Olivenöl
   aufträufeln und die Auberginen warm oder mit Zimmertemperatur servieren.

*** Notizen
** Butternusskürbis mit Tahini-Sauce & Za'atar
:PROPERTIES:
:Source:    Jerusalem - Das Kochbuch
:Portions:  4
:Category:  Gemüse
:Meal:      Vorspeise/Hauptgericht
:END:

*** Einführung
Ein außerordentlich vielseitiges Gericht, dabei ganz einfach zuzubereiten - und obendrein
schmeckt es vorzüglich. Es eignet sich als Vorspeise, als fleischloses Hauptgericht, aber
auch als Beilage zu einfachen Gerichten wie Lamm-Shawarma (siehe Seite 210) oder
Hähnchen-Sofrito (siehe Seite 190). Die Tahini-Sauce ist relativ dominant. Bei uns zu
Hause liebt man das, die Menge lässt sich aber nach Belieben auch reduzieren. Schmecken
Sie das Gericht zum Schluss einfach noch einmal ab und entscheiden Sie dann selbst.

*** Zutaten
| Menge | Einheit | Zutat                             |
|-------+---------+-----------------------------------|
|     1 | St      | großer Butternusskürbis (1,5kg)   |
|     2 | St      | rote Zwiebeln                     |
|    50 | ml      | Olivenöl                          |
|   3.5 | EL      | helles Tahini                     |
|   1.5 | EL      | Zitronensaft                      |
|     1 | St      | kleine Knoblauchzehe              |
|    30 | g       | Pinienkerne                       |
|     1 | EL      | Za'atar                           |
|     1 | EL      | grob gehackte glatte Petersilie   |
|     - | -       | Maldon Sea Salt oder Fleur de Sel |
|     - | -       | schwarzer Pfeffer                 |

*** Zubereitung
1. Den Backofen auf 240°C vorheizen.

2. Kürbis und Zwiebeln in einer großen Schüssel mit 3 Esslöffeln Öl, 1 Teelöffel Salz und
   etwas frisch gemahlenem Pfeffer vermischen. Alles auf einem Backblech verteilen (Kürbis
   mit der Schale nach oben) und 30-40 Minuten in den Backofen schieben, bis das Gemüse
   weich ist und etwas Farbe angenommen hat. Dabei darauf achten, dass die Zwiebeln nicht
   zu dunkel werden, denn sie sind schneller gar als der Kürbis und müssen früher aus dem
   Ofen genommen werden. Das Blech anschließend herausnehmen und das Gemüse abkühlen
   lassen.

3. Für die Sauce das Tahini in einer kleinen Schüssel kräftig mit Zitronensaft, 2
   Esslöffeln Wasser, Knoblauch und ¼ Teelöffel Salz verrühren. Die Konsistenz sollte
   flüssigem Honig gleichen. Falls nötig, noch etwas Wasser oder Tahini hinzufügen.

4. Das restliche Öl in einer kleinen Pfanne bei geringer bis mittlerer Temperatur erhitzen
   und die Pinienkerne mit ½ Teelöffel Salz 2 Minuten unter häufigem Wenden goldbraun
   rösten. Den Pfanneninhalt anschließend in eine kleine Schüssel füllen.

5. Das Gemüse auf einer großen Platte anrichten. Mit der Tahini-Sauce überziehen, die
   Pinienkerne mit dem Öl darauf verteilen und mit Za'atar und Petersilie bestreuen.

*** Notizen
- Die Tahini-Sauce ist relativ dominant, die Menge kann nach Geschmack reduziert werden.
- Die Zwiebeln müssen früher aus dem Ofen genommen werden als der Kürbis.
- Eignet sich als Vorspeise, Hauptgericht oder Beilage zu Lamm-Shawarma oder
  Hähnchen-Sofrito.
** Conchiglie mit Joghurt, Erbsen & Chili
:PROPERTIES:
:Source:    Jerusalem - Das Kochbuch
:Portions:  6
:Category:  Pasta
:Meal:      Hauptgericht
:END:

*** Einführung
Pasta mit heißer Joghurtsauce – das mag zunächst ein bisschen seltsam klingen, aber der
palästinensische Klassiker Shishbarak – eine Art Ravioli mit Fleischfüllung – wird,
ähnlich wie die türkischen und armenischen Manti, genau so serviert. Joghurt macht das
Gericht wunderbar sahnig und trotzdem leicht. Eine ausgezeichnete Alternative, wenn man
keine schwere Sauce mit Sahne essen möchte. Wir empfehlen sie wärmstens.

Chiliflocken gibt es in der Türkei und in Syrien in den unterschiedlichsten Varianten –
mal ist das Aroma eher süßlich, mal scharf oder erdig –, und wir experimentieren gerne mit
diesen unterschiedlichen Noten. Meine besonderen Favoriten sind der dunkelrote Urfa-Chili,
der ein beinahe moschusartiges Aroma hat, der fruchtige Aleppo-Chili, aber auch der
einfache Kirmizi Biber, der auch leichter zu bekommen ist. In türkischen
Lebensmittelgeschäften und im Internet werden Sie sicher fündig. Ersatzweise tun es aber
auch herkömmliche Chiliflocken und ein bisschen geräuchertes Paprikapulver.

*** Zutaten
| Menge | Einheit | Zutat                                              |
|-------+---------+----------------------------------------------------|
|   500 | g       | griechischer Joghurt                               |
|   150 | ml      | Olivenöl                                           |
|     4 | Stück   | Knoblauchzehen, zerdrückt                          |
|   500 | g       | Erbsen, blanchiert oder tiefgefroren und aufgetaut |
|   500 | g       | Conchiglie (Muschelnnudeln)                        |
|    60 | g       | Pinienkerne                                        |
|     2 | TL      | Chiliflocken (oder weniger, je nach Schärfe)       |
|    40 | g       | Basilikumblätter, in Stücke gerissen               |
|   240 | g       | Feta, in Stücke gebrochen                          |
|       |         | Salz und frisch geschroteter weißer Pfeffer        |

*** Zubereitung
1. Den Joghurt in der Küchenmaschine mit 90ml Olivenöl, dem Knoblauch und 100g Erbsen zu
   einer glatten Sauce verarbeiten und in eine große Schüssel füllen.
2. Die Nudeln in reichlich Salzwasser al dente garen.
3. Inzwischen das restliche Öl bei mittlerer Temperatur in einer kleinen Pfanne erhitzen
   und die Pinienkerne mit den Chiliflocken darin 4 Minuten rösten, bis die Pinienkerne
   goldbraun sind und das Öl eine intensive rote Farbe angenommen hat.
4. Gleichzeitig die restlichen Erbsen in etwas kochendem Wasser erhitzen und anschließend
   abgießen.
5. Die Nudeln abgießen, gut abtropfen lassen und nach und nach mit der Joghurtsauce
   vermischen (die Nudeln nicht auf einmal zum Joghurt geben, damit er nicht gerinnt).
6. Erbsen, Basilikum und Feta hinzufügen und mit 1 Teelöffel Salz und ½ Teelöffel Pfeffer
   würzen.
7. Das Ganze vorsichtig durchmischen, in Portionsschalen anrichten und die Pinienkerne mit
   dem Öl darauf verteilen.

*** Notizen
- Chilivarianten:
  - Urfa-Chili (dunkelrot, moschusartiges Aroma)
  - Aleppo-Chili (fruchtig)
  - Kirmizi Biber (leichter erhältlich)
  - Alternative: herkömmliche Chiliflocken mit geräuchertem Paprikapulver
- Die schrittweise Vermischung mit der Joghurtsauce ist wichtig, damit der Joghurt nicht
  gerinnt
- Kulturelle Verbindung: Ähnlich wie der palästinensische Shishbarak und
  türkische/armenische Manti
- Eine leichtere Alternative zu Pastagerichten mit Sahnesauce
** Frikadellen mit Zitrone und Lauch
:PROPERTIES:
:Source:    Jerusalem - Das Kochbuch
:Portions:  4
:Category:  Gemüse
:Meal:      Vorspeise
:END:

*** Einführung
Was hat ein Rezept mit Fleisch im Gemüsekapitel zu suchen? Nun, was diese Frikadellen zu
etwas Besonderem macht, ist die Tatsache, dass hier der Lauch die Hauptrolle spielt, und
dadurch werden sie besonders locker.

Das Rezept habe ich von Tamara Meitlis, einer wunderbaren Freundin und einer Expertin für
die türkisch-jüdische Küche. Es handelt sich um ein typisches Gericht der Juden von Izmir.
Wie bei den meisten türkischen Rezepten sollte man auch hier tunlichst nicht
herumexperimentieren. »Natürlich kannst du es abwandeln«, sagt Tamara mit gönnerhaftem
Lächeln, »aber nur, wenn du die Absicht hast, es zu verhunzen!« Recht hat sie!
Sephardische Rezepte, zumal aus der Türkei, wurden über Generationen perfektioniert, und
es empfiehlt sich, sie genauestens zu befolgen. Wenn man es recht bedenkt, gilt das für
die meisten Gerichte der Jerusalemer Küchen. Deshalb sollte man traditionelle Rezepte nur
abwandeln, wenn einem keine Meisterköchin dabei über die Schulter schaut.

*** Zutaten
|   Menge | Einheit | Zutat                           |
|---------+---------+---------------------------------|
|       6 | St      | große Stangen Lauch             |
|     250 | g       | Hackfleisch                     |
|      90 | g       | Semmelbrösel                    |
|       2 | St      | Eier                            |
|       2 | EL      | Sonnenblumenöl                  |
| 200-300 | ml      | Hühnerbrühe                     |
|      80 | ml      | Zitronensaft                    |
|      80 | g       | Sahnejoghurt                    |
|       1 | EL      | fein gehackte glatte Petersilie |
|       - | -       | Salz und schwarzer Pfeffer      |

*** Zubereitung
1. Den Lauch in 2 cm breite Ringe schneiden und etwa 20 Minuten dämpfen, bis er weich ist.
   Anschließend abgießen, abkühlen lassen, in ein Geschirrtuch einschlagen und die
   überschüssige Flüssigkeit herauspressen. Das Gemüse danach in der Küchenmaschine grob
   zerkleinern (es soll aber nicht breiig werden).

2. In einer großen Schüssel mit Hackfleisch, Semmelbröseln, Eiern, 1 Teelöffel Pfeffer und
   ½ Teelöffel Salz sowie 1 Teelöffel Salz vermengen. Acht etwa 7 x 2 cm große Frikadellen
   daraus formen und 30 Minuten im Kühlschrank ruhen lassen.

3. Das Öl bei mittlerer Hitze in einer großen Deckelpfanne mit schwerem Boden erhitzen.
   Die Frikadellen – falls nötig portionsweise – auf beiden Seiten goldbraun braten und
   danach aus der Pfanne nehmen.

4. Die Pfanne mit Küchenpapier ausreiben, die Frikadellen wieder hineinlegen und soviel
   Hühnerbrühe angießen, dass die Frikadellen fast bedeckt sind. Den Zitronensaft sowie ½
   Teelöffel Salz hinzufügen und aufkochen. Den Deckel auflegen und die Frikadellen 30
   Minuten bei geringer Hitze garen. Danach den Deckel abnehmen und die Flüssigkeit fast
   vollständig einkochen lassen. Die Pfanne vom Herd nehmen und zum Abkühlen
   beiseitestellen.

5. Die Frikadellen warm oder mit Zimmertemperatur mit einem Klecks Joghurt und mit
   Petersilie bestreut servieren.

*** Notizen
- Sie müssen die Frikadellen übrigens nicht unbedingt in Hühnerbrühe fertig garen. Man
  kann sie auch einfach nur entsprechend länger braten und dann heiß mit Zitronenspalten
  servieren.
- Bei türkischen Rezepten sollte man tunlichst nicht experimentieren, da sie über
  Generationen perfektioniert wurden.
- Der Lauch spielt die Hauptrolle in diesem Gericht und macht die Frikadellen besonders
  locker.
** Mejadra
:PROPERTIES:
:Source:    Jerusalem - Das Kochbuch
:Portions:  4
:Category:  Hauptgericht
:Meal:      Lunch, Dinner
:END:

*** Einführung
Dieses Gericht erfreut sich nicht nur in der gesamten arabischen Welt großer Beliebtheit,
es ist auch eines unserer Lieblingsgerichte. Das Geheimnis sind die süßlichen, etwas
öligen, knusprig frittierten Zwiebelringe. Immer wenn Samis Familie einen Tagesausflug
nach Jericho machte, nahm man für das Picknick einen großen Topf Mejadra mit. Das aß man
dann aus kleinen Schüsseln mit einem Klecks Joghurtsauce. Und zum Nachtisch gab es eine
riesige Wassermelone, die Samis Vater in einem kleinen Fluss kühlte, der in den Jordan
mündet.

Wir beide können stundenlang darüber diskutieren, was ein gutes Linsengericht ausmacht und
warum das so ist. Aber eine definitive Antwort darauf finden wir nie. Nur bei diesem
Linsenreis sind wir uns vollkommen einig. Mit Gurkenjoghurt (siehe Seite 299) oder etwas
einfachem griechischem Joghurt serviert, ist er unübertroffen. Am besten schmeckt er warm.

*** Zutaten
| Menge | Einheit     | Zutat                      |
|-------+-------------+----------------------------|
|   250 | g           | grüne oder braune Linsen   |
|     4 | mittelgroße | Zwiebeln (700g)            |
|     3 | EL          | Mehl                       |
|   250 | ml          | Sonnenblumenöl             |
|     2 | TL          | Kreuzkümmelkerne           |
|   1.5 | TL          | Koriandersamen             |
|   200 | g           | Basmatireis                |
|     2 | EL          | Olivenöl                   |
|   0.5 | TL          | gemahlene Kurkuma          |
|   1.5 | TL          | gemahlener Piment          |
|   1.5 | TL          | Zimt                       |
|     1 | TL          | Zucker                     |
|       |             | Salz und schwarzer Pfeffer |

*** Zubereitung
1. Die Linsen in einem kleinen Topf mit reichlich Wasser bedecken, aufkochen, 12-15
   Minuten bissfest garen, dann in ein Sieb abgießen.
2. Die Zwiebeln schälen und in feine Ringe schneiden.
3. Auf einer großen Platte verteilen, mit Mehl bestäuben und mit 1 Teelöffel Salz würzen.
4. Das Ganze dann mit den Händen durchmischen.
5. In einem Topf mit schwerem Boden das Sonnenblumenöl bei hoher Temperatur erhitzen.
6. Einen Zwiebelring hineinfallen lassen, um zu prüfen, ob das Öl die richtige Temperatur
   hat. Es sollte kräftig brutzeln.
7. Die Wärmezufuhr etwas verringern und die Zwiebelringe portionsweise 5-7 Minuten im
   heißen Öl frittieren, bis sie goldbraun und knusprig sind.
8. Dabei gelegentlich mit einem Schaumlöffel umrühren und die Temperatur, falls nötig,
   reduzieren, damit die Zwiebeln nicht zu dunkel werden.
9. Mit dem Schaumlöffel aus dem Topf heben, auf Küchenpapier abtropfen lassen und noch
   einmal nachsalzen.
10. Das restliche Öl aus dem Frittiertopf abgießen, den Boden mit Küchenpapier abtreiben.
11. Kreuzkümmel und Koriander hineingeben und 1-2 Minuten bei mittlerer Hitze rösten.
12. Reis, Olivenöl, die Gewürze, Zucker, ½ Teelöffel Salz und reichlich Pfeffer hinzufügen
    und das Ganze verrühren, bis die Reiskörner mit Öl überzogen sind.
13. Die gekochten Linsen dazugeben und 350ml Wasser angießen.
14. Aufkochen und zugedeckt 15 Minuten bei sehr geringer Hitze köcheln lassen.
15. Den Topf vom Herd nehmen.
16. Den Deckel abheben und den Topf sofort mit einem Geschirrtuch bedecken.
17. Den Deckel wieder auflegen und den Reis 10 Minuten ruhen lassen.
18. Die Hälfte der frittierten Zwiebeln untermischen.
19. Den Linsenreis in einer Schüssel anrichten und mit den restlichen Zwiebelringen
    bestreuen.

*** Notizen
- Serviervorschläge:
  - Mit Gurkenjoghurt
  - Mit einfachem griechischem Joghurt
- Am besten warm servieren
- Die knusprigen Zwiebelringe sind das Herzstück des Gerichts
- Traditionell ein beliebtes Picknickgericht
** Musabaha (warme Kichererbsen mit Hummus) & geröstetes Pitabrot
:PROPERTIES:
:Source:    Jerusalem - Das Kochbuch
:Portions:  4
:Category:  Hauptgericht
:Meal:      Frühstück, Brunch
:END:

*** Einführung
Traditionell isst man dieses Gericht mit eingelegtem Gemüse, frischem Rettich und
Frühlingszwiebeln oder in Spalten geschnittenen weißen Zwiebeln zum Frühstück. Es eignet
sich auch hervorragend für einen Brunch. Die knusprigen Brotstücke dienen als
Löffelersatz.

*** Zutaten
| Menge | Einheit | Zutat                      |
|-------+---------+----------------------------|
|   250 | g       | getrocknete Kichererbsen   |
|     1 | TL      | Backnatron                 |
|     1 | EL      | gemahlener Kreuzkümmel     |
|    70 | g       | helles Tahini (Sesampaste) |
|     3 | EL      | Zitronensaft               |
|     1 | Stück   | Knoblauchzehe, zerdrückt   |
|     2 | EL      | eiskaltes Wasser           |
|     4 | Stück   | kleine Pitabrote (120g)    |
|     2 | EL      | Olivenöl                   |
|     2 | EL      | gehackte glatte Petersilie |
|     1 | TL      | Paprikapulver edelsüß      |
|       |         | Salz und schwarzer Pfeffer |

Für die Tahini-Sauce:
| Menge | Einheit | Zutat                    |
|-------+---------+--------------------------|
|    75 | g       | helles Tahini            |
|     1 | EL      | Zitronensaft             |
|   0.5 | Stück   | Knoblauchzehe, zerdrückt |

Für die Zitronensauce:
| Menge | Einheit | Zutat                           |
|-------+---------+---------------------------------|
|    10 | g       | glatte Petersilie, fein gehackt |
|     1 | Stück   | grüne Chilischote, fein gehackt |
|     4 | EL      | Zitronensaft                    |
|     2 | EL      | Weißweinessig                   |
|     2 | Stück   | Knoblauchzehen, zerdrückt       |
|  0.25 | TL      | Salz                            |

*** Zubereitung
1. Die Kichererbsen wie auf Seite 114 (Grundrezept für Hummus) beschrieben einweichen und
   garen.
2. Die Kochzeit jedoch ein wenig verkürzen, damit sie noch etwas Biss behalten.
3. Die gekochten Kichererbsen abgießen und 80 ml Kochwasser auffangen.
4. Die Kichererbsen wiegen (es werden etwa 600g benötigt). 150g abnehmen und
   beiseitestellen.
5. Die restlichen 450g mit der aufgefangenen Kochflüssigkeit, dem Kreuzkümmel, ½ Teelöffel
   Salz und ¼ Teelöffel gemahlenem schwarzem Pfeffer verrühren und warm stellen.
6. Die restlichen 150g in der Küchenmaschine fein pürieren.
7. Bei laufendem Motor Tahini, Zitronensaft, Knoblauch und ½ Teelöffel Salz dazugeben.
8. Zum Schluss das Eiswasser langsam hineingießen und das Ganze etwa 3 Minuten rühren, bis
   eine glatte, cremige Paste entstanden ist.
9. Während die Kichererbsen kochen, die Saucen zubereiten.
10. Die Zutaten für die Tahini-Sauce in einer kleinen Schüssel mit 60ml Wasser und 1 Prise
    Salz verrühren.
11. Ist die Sauce zu dick (sie sollte die Konsistenz von relativ flüssigem Honig haben),
    noch etwas Wasser hinzufügen.
12. Die Zutaten für die Zitronensauce ebenfalls verrühren.
13. Die Pitabrote jeweils in zwei Hälften teilen, öffnen und 2 Minuten unter den heißen
    Backofengrill legen, bis sie goldbraun und vollkommen trocken sind.
14. Etwas abkühlen lassen und in Stücke brechen.
15. Das Hummus in vier Portionsschalen füllen und die Kichererbsen darauf verteilen.
16. Mit den Saucen überziehen, mit etwas Olivenöl beträufeln und mit Petersilie und
    Paprikapulver bestreuen.
17. Die Pitastücke rundherum verteilen und servieren.

*** Notizen
- Das Gericht eignet sich für:
  - Traditionelles Frühstück
  - Brunch
- Serviervorschläge:
  - Mit eingelegtem Gemüse
  - Mit frischem Rettich
  - Mit Frühlingszwiebeln
  - Mit weißen Zwiebelspalten
- Die Kichererbsen sollten noch Biss haben, nicht zu weich sein
- Die Tahini-Sauce sollte die Konsistenz von flüssigem Honig haben
** Offene Kibbeh
:PROPERTIES:
:Source:    Jerusalem - Das Kochbuch
:Portions:  6
:Category:  Gefülltes
:Meal:      Hauptgericht
:END:

*** Einführung
Dies ist eine sehr untypische Variante der Kibbeh (siehe Seite 159). Die wichtigsten
Zutaten – Bulgur, Hackfleisch, Gewürze und Pinienkerne – wurden hier als eine Art Kuchen
zubereitet, der zum Schluss mit der obligatorischen Tahini-Sauce begossen wird. Servieren
Sie das Gericht warm oder mit Zimmertemperatur, dazu einen pikanten, aromatischen Salat
wie Tabbouleh oder Fattoush (siehe Seite 83 und 29).

*** Zutaten
| Menge | Einheit | Zutat                              |
|-------+---------+------------------------------------|
|   125 | g       | feiner Bulgur                      |
|    90 | ml      | Olivenöl                           |
|     2 |         | Knoblauchzehen, zerdrückt          |
|     2 |         | mittelgroße Zwiebeln, fein gehackt |
|     1 |         | grüne Chilischote, fein gehackt    |
|   350 | g       | Lammhackfleisch                    |
|     1 | TL      | gemahlener Piment                  |
|     1 | TL      | Zimt                               |
|     1 | TL      | gemahlener Koriander               |
|     2 | EL      | grob gehacktes Koriandergrün       |
|    60 | g       | Pinienkerne                        |
|     3 | EL      | grob gehackte glatte Petersilie    |
|     2 | EL      | Mehl                               |
|    50 | g       | helles Tahini (Sesampaste)         |
|     2 | TL      | Zitronensaft                       |
|     1 | TL      | gemahlener Sumach                  |
|       |         | Salz und schwarzer Pfeffer         |

*** Zubereitung
1. Den Backofen auf 200°C vorheizen. Eine Springform (20 cm Durchmesser) mit Backpapier
   auslegen.
2. Den Bulgur 30 Minuten in 200 ml Wasser einweichen.
3. Inzwischen 4 Esslöffel Öl in einer großen Pfanne erhitzen. Knoblauch, Zwiebeln und
   Chili darin bei mittlerer bis starker Hitze anschwitzen, bis alles weich ist, dann aus
   der Pfanne nehmen.
4. Das Fleisch bei hoher Temperatur 5 Minuten unter stetigem Rühren in der Pfanne
   anbräunen.
5. Die Zwiebelmischung zum Fleisch geben, Gewürze, Koriandergrün, ½ Teelöffel Salz, 1
   kräftige Prise Pfeffer und den größten Teil der Pinienkerne und der Petersilie
   hinzufügen und das Ganze einige Minuten erhitzen. Vom Herd nehmen und noch einmal
   abschmecken.
6. Wenn der Bulgur das Wasser vollständig aufgesogen hat (eventuell noch verbliebene
   Flüssigkeit abgießen), Mehl, 1 Esslöffel Öl, ¼ Teelöffel Salz sowie 1 Prise Pfeffer
   hinzufügen und die Zutaten zu einem elastischen Teig verarbeiten. Ist er gut klebrig,
   noch etwas Mehl hinzufügen.
7. Den Teig gleichmäßig auf dem Boden der Form verteilen und dabei leicht andrücken.
8. Die Fleischmischung daraufgeben, glatt streichen und leicht andrücken.
9. Die Form für 20 Minuten in den Backofen schieben, bis das Fleisch gebräunt und sehr
   heiß ist.
10. Inzwischen Tahini mit Zitronensaft, 50 ml Wasser und 1 Prise Salz zu einer dicken
    Sauce verrühren.
11. Die Kibbeh aus dem Ofen nehmen, die Tahini-Sauce gleichmäßig darauf verteilen, mit den
    restlichen Pinienkernen und der Petersilie bestreuen, die Form sofort wieder in den
    Ofen schieben.
12. 10-12 Minuten weiterbacken, bis die Sauce gerade gestockt ist und etwas Farbe
    angenommen hat.
13. Aus dem Ofen nehmen und leicht abkühlen lassen. Mit Sumach bestreuen und mit Olivenöl
    beträufeln.
14. Den Rand der Springform vorsichtig abnehmen und die Kibbeh aufschneiden.

*** Notizen
- Die Kibbeh kann warm oder bei Zimmertemperatur serviert werden
- Als Beilage eignen sich Tabbouleh oder Fattoush
- Dies ist eine untypische Variante der traditionellen Kibbeh
- Der Bulgurteig sollte elastisch und leicht klebrig sein
** Shakshuka
:PROPERTIES:
:Source:    Jerusalem - Das Kochbuch
:Portions:  2-4
:Category:  Hauptgericht
:Meal:      Frühstück, Mittagessen
:END:

*** Einführung
Shakshuka kommt eigentlich aus Tunesien, erfreut sich inzwischen aber auch in Jerusalem
und ganz Israel großer Beliebtheit als herzhaftes Frühstück oder kleines Mittagessen. Eier
spielen in der tunesischen Küche eine wichtige Rolle. Diese Variante von Shakshuka
bereitet man vor allem im Sommer und Frühherbst zu. Im Winter wird das Gericht mit
Kartoffeln und im Frühjahr mit Auberginen angereicht.

Shakshuka lässt sich auf unterschiedlichste Weise abwandeln. Ich selbst habe bereits ein
oder zwei Rezepte veröffentlicht und stelle Ihnen hier schon die dritte Version dieses
beliebten Gerichts vor. Diesmal stehen Tomaten und Gewürze im Mittelpunkt. Ich möchte Sie
aber ausdrücklich ermuntern, mit anderen Zutaten Ihrer Wahl zu experimentieren und die
Schärfe Ihrem Geschmack anzupassen. Als Beilage braucht man lediglich etwas gutes
Weißbrot.

*** Zutaten
| Menge | Einheit | Zutat                                                                                                              |
|-------+---------+--------------------------------------------------------------------------------------------------------------------|
|     2 | EL      | Olivenöl                                                                                                           |
|     2 | EL      | Pilpelchuma (siehe Seite 302) oder Harissa (siehe Seite 301 oder Fertigprodukt)                                    |
|     2 | TL      | Tomatenmark                                                                                                        |
|     2 | große   | rote Paprikaschoten (200g), von Stielansatz, Samen und Scheidewänden befreit und in 0,5cm große Würfel geschnitten |
|     4 | Stück   | Knoblauchzehen, fein gehackt                                                                                       |
|     1 | TL      | gemahlener Kreuzkümmel                                                                                             |
|     5 | große   | sehr reife Tomaten (800g), gehackt, oder 2 Dosen (á 400g) Tomatenstücke                                            |
|     4 | Stück   | Eier (Gewichtsklasse M)                                                                                            |
|     4 | Stück   | Eigelb                                                                                                             |
|   120 | g       | Labneh (siehe Seite 302) oder stichfester Joghurt                                                                  |
|       |         | Salz                                                                                                               |

*** Zubereitung
1. Das Öl bei mittlerer Temperatur in einer großen Pfanne erhitzen. Pilpelchuma oder
   Harissa, Tomatenmark, Paprika, Knoblauch, Kreuzkümmel und ¾ Teelöffel Salz hineingeben,
   umrühren und das Ganze etwa 8 Minuten bei geringer Hitze anschwitzen, bis die
   Paprikawürfel weich sind.
2. Die Tomaten dazugeben und die Mischung weitere 10 Minuten köcheln lassen, bis eine
   relativ dicke Sauce entstanden ist.
3. Die Sauce abschmecken, acht kleine Vertiefungen hineindrücken.
4. Die Eier aufschlagen und vorsichtig in die Mulden gleiten lassen. Anschließend die
   Eigelbe auf die Vertiefungen verteilen.
5. Mit einer Gabel die Eiweiße leicht mit der Sauce verquirlen. Dabei darauf achten, dass
   die Eigelbe nicht auslaufen.
6. Das Gericht 8-10 Minuten köcheln lassen, bis die Eiweiße gestockt, die Eigelbe aber
   noch flüssig sind (um den Prozess zu beschleunigen, die Pfanne eventuell mit einem
   Deckel verschließen).
7. Die Pfanne anschließend vom Herd nehmen und ein paar Minuten stehen lassen.
8. Shakshuka auf Tellern anrichten und mit Labneh oder Joghurt servieren.

*** Notizen                                                   :hauptgerichte:
- Das Gericht kann je nach Saison variiert werden:
  - Winter: mit Kartoffeln
  - Frühjahr: mit Auberginen
  - Sommer und Frühherbst: klassische Version mit Tomaten
- Als Beilage wird gutes Weißbrot empfohlen
- Die Schärfe kann nach persönlichem Geschmack angepasst werden
* Beilagen                                                                                 :beilage:
** Couscous mit Tomate & Zwiebel
:PROPERTIES:
:Source:    Jerusalem - Das Kochbuch
:Portions:  4
:Category:  Hauptgericht
:Meal:      Beilage, vegetarische Mahlzeit
:END:

*** Einführung
Ein Essen, das Leib und Seele wärmt. Das Rezept basiert auf einem Gericht, das Samis
Mutter für ihren kleinen Sohn kochte (siehe Seite 8). Wichtig ist dabei – ähnlich wie beim
Tadik, einem persischen Reisgericht – die knusprige Kruste, die sich beim Kochen am
Topfboden bildet. Hier kommt es zudem auf die Qualität der Brühe an. Den Couscous serviert
man als Beilage zu Gegrilltem Fischspießen mit Hawayej und Petersilie (siehe Seite 226),
Puten-Zucchini-Burgern mit Frühlingszwiebel und Kreuzkümmel (siehe Seite 200) oder mit
einem Salat als leichte vegetarische Mahlzeit.

*** Zutaten
| Menge | Einheit     | Zutat                                             |
|-------+-------------+---------------------------------------------------|
|     3 | EL          | Olivenöl                                          |
|     1 | mittelgroße | Zwiebel (160g), fein gehackt                      |
|     1 | EL          | Tomatenmark                                       |
|   0.5 | TL          | Zucker                                            |
|     2 | sehr reife  | Tomaten (320g), in 0,5cm große Würfel geschnitten |
|   150 | g           | Couscous                                          |
|   220 | ml          | kochende Hühner- oder Gemüsebrühe                 |
|    40 | g           | Butter                                            |
|       |             | Salz und schwarzer Pfeffer                        |

*** Zubereitung
1. In einer beschichteten Pfanne (etwa 22cm Durchmesser) 2 Esslöffel Olivenöl bei
   mittlerer Hitze erhitzen und die Zwiebel 5 Minuten unter häufigem Rühren glasig
   anschwitzen.
2. Tomatenmark und Zucker einrühren und 1 Minute erhitzen.
3. Die Tomaten hinzufügen, mit ½ Teelöffel Salz sowie etwas Pfeffer würzen und die Sauce 3
   Minuten kochen lassen.
4. Inzwischen den Couscous in einer flachen Schüssel mit der kochenden Brühe übergießen.
5. Mit Frischhaltefolie abdecken und 10 Minuten quellen lassen.
6. Anschließend mit einer Gabel auflockern und mit der Tomatensauce mischen.
7. Die Pfanne mit Küchenpapier ausreiben und die Butter bei mittlerer Temperatur mit dem
   restlichen Öl erhitzen.
8. Den Couscous in die Pfanne geben und mit einem Löffelrücken gleichmäßig darin
   verteilen, dabei vorsichtig andrücken.
9. Den Deckel auflegen und den Couscous 10-12 Minuten bei sehr geringer Hitze braten, bis
   Boden und Rand leicht gebräunt und knusprig sind.
10. Gegen Ende der Garzeit mit einer Palette oder einem Messer den Couscous vorsichtig vom
    Rand der Pfanne lösen, um zu prüfen, ob er knusprig genug ist.
11. Wenn es so weit ist, einen großen Teller umgekehrt auf die Pfanne setzen und den
    Couscous daraufstürzen.
12. Warm oder mit Zimmertemperatur servieren.

*** Notizen
- Wichtige Aspekte:
  - Die knusprige Kruste am Boden ist essentiell
  - Die Qualität der Brühe ist wichtig für den Geschmack
- Serviervorschläge:
  - Als Beilage zu:
    - Gegrillten Fischspießen mit Hawayej und Petersilie
    - Puten-Zucchini-Burgern mit Frühlingszwiebel und Kreuzkümmel
  - Mit Salat als vegetarische Mahlzeit
- Kann warm oder bei Zimmertemperatur serviert werden
** Frittierter Blumenkohl in Tahini-Sauce
:PROPERTIES:
:Source:    Jerusalem - Das Kochbuch
:Portions:  6
:Category:  Gemüse
:Meal:      Vorspeise/Mezze
:END:

*** Einführung
Dieses Gericht kommt gewöhnlich zusammen mit anderen Mezze auf den Tisch, den vielen
kleinen Vorspeisen, die man teilt, bevor der Hauptgang serviert wird. Für die Menschen in
Jerusalem – Araber wie Juden – ist Essen ein Gemeinschaftserlebnis. Etikette und gute
Tischmanieren stehen dabei nicht im Vordergrund. Man darf ruhig auch einmal vom Teller der
anderen Tischgäste probieren, und die Platten werden herumgereicht, bis auch der Letzte
satt und zufrieden ist. Auch sonst geht es beim Essen recht lebhaft zu.

*** Zutaten
| Menge | Einheit | Zutat                             |
|-------+---------+-----------------------------------|
|   500 | ml      | Sonnenblumenöl                    |
|     1 | kg      | Blumenkohl                        |
|     8 | St      | Frühlingszwiebeln                 |
|   180 | g       | helles Tahini                     |
|     2 | St      | Knoblauchzehen                    |
|    15 | g       | glatte Petersilie                 |
|    15 | g       | Minze                             |
|   150 | g       | griechischer Joghurt              |
|     1 | St      | Bio-Zitrone                       |
|    60 | ml      | Zitronensaft                      |
|     1 | TL      | Granatapfelsirup                  |
|     - | -       | Maldon Sea Salt oder Fleur de Sel |
|     - | -       | schwarzer Pfeffer                 |

*** Zubereitung
1. Das Öl bei mittlerer bis starker Temperatur in einem großen Topf erhitzen. Die
   Blumenkohlröschen in kleinen Portionen mit einer Zange vorsichtig ins heiße Öl geben
   und 2-3 Minuten unter häufigem Wenden frittieren, bis sie gleichmäßig gebräunt sind.
   Mit einem Schaumlöffel herausheben, in einem Sieb abtropfen lassen und mit etwas Salz
   bestreuen. Die Frühlingszwiebeln ebenfalls portionsweise etwa 1 Minute frittieren, zum
   Blumenkohl geben und das Gemüse etwas abkühlen lassen.

2. Tahini mit Knoblauch, Kräutern, Joghurt, Zitronenschale und -saft, Granatapfelsirup
   sowie etwas Salz und Pfeffer in eine große Schüssel geben. Die Zutaten sorgfältig mit
   einem Kochlöffel verrühren und dabei etwa 180 ml Wasser hinzufügen, bis ein dickes,
   glattes Dressing entstanden ist (es sollte die Konsistenz von flüssigem Honig haben).

3. Blumenkohl und Frühlingszwiebeln dazugeben, gut durchheben und noch einmal abschmecken.

4. Das Gericht in eine Servierschüssel füllen, mit etwas Granatapfelsirup beträufeln und
   mit gehackter Minze bestreuen.

*** Notizen
- Für westliche Gaumen, die an Blumenkohl mit sahnigen Saucen und Käse oder ähnlich
  schwere Zubereitungsarten gewöhnt sind, wird diese schärfere, frischere Variante
  vielleicht zunächst einmal gewöhnungsbedürftig sein.
- Im Kühlschrank kann er einen Tag aufbewahrt werden.
- In diesem Fall rechtzeitig vor dem Servieren herausnehmen und noch einmal abschmecken.
** Gebackene Aubergine mit frittierten Zwiebeln & Zitrone
:PROPERTIES:
:Source:    Jerusalem - Das Kochbuch
:Portions:  4
:Category:  Gemüse
:Meal:      Vorspeise
:END:

*** Einführung
Eine herrlich reichhaltige Vorspeise, in der sich Schärfe, Salzigkeit und milde Süße
verbinden. Am besten serviert man sie vor einem einfachen, leichten Hauptgericht wie
unseren Puten-Zucchini-Burgern mit frischen Frühlingszwiebeln und Kreuzkümmel (siehe Seite
200). Eine gute Aubergine sollte leicht in der Hand liegen, wenig Kerne enthalten und eine
glatte, glänzende Schale aufweisen. Stellen Sie beim Braten ein Gefäß mit Wasser auf den
Boden des Ofens. So trocknet das Fruchtfleisch nicht aus.

*** Zutaten
| Menge | Einheit | Zutat                      |
|-------+---------+----------------------------|
|     2 | St      | große Auberginen           |
|   150 | ml      | Olivenöl                   |
|   550 | g       | Zwiebeln                   |
|   1.5 | TL      | grüne Chilischoten         |
|   1.5 | TL      | gemahlener Kreuzkümmel     |
|     1 | TL      | gemahlener Sumach          |
|    50 | g       | Feta                       |
|     1 | St      | mittelgroße Zitrone        |
|     1 | St      | Knoblauchzehe              |
|     - | -       | Salz und schwarzer Pfeffer |

*** Zubereitung
1. Den Backofen auf 220°C vorheizen.

2. Das Fruchtfleisch der Auberginen rautenförmig einritzen, die Schnittflächen mit 100 ml
   Olivenöl bestreichen und großzügig mit Salz und Pfeffer bestreuen. Die Auberginen mit
   der Schnittfläche nach oben auf ein Backblech legen und für etwa 45 Minuten in den Ofen
   schieben, bis sie goldbraun sind.

3. Inzwischen das restliche Öl in eine große Pfanne gießen und die Zwiebeln mit ½
   Teelöffel Salz unter häufigem Wenden 8 Minuten bei starker Hitze frittieren, bis sie
   knusprig braun sind. Die Chilischoten entkernen und in Streifen schneiden, ⅔ mit
   Kreuzkümmel und Sumach zu den Zwiebeln geben. Das Ganze weitere 2 Minuten braten, den
   Feta hinzufügen und alles 1 weitere Minute unter stetigem Rühren garen. Die Pfanne
   danach vom Herd nehmen.

4. Die Zitrone mit einem scharfen Messer schälen und dabei auch die weiße Haut entfernen.
   Das Fruchtfleisch zwischen den Trennhäuten herauslösen, grob hacken und mit dem Saft,
   der restlichen Chilischote und dem Knoblauch in eine kleine Schüssel geben.

5. Die Auberginen auf einer Servierplatte anrichten und mit der Zitronensauce überziehen.
   Die Zwiebeln noch einmal kurz erwärmen und darauf verteilen. Warm oder mit
   Zimmertemperatur servieren.

*** Notizen
- Eine gute Aubergine sollte leicht in der Hand liegen, wenig Kerne enthalten und eine
  glatte, glänzende Schale aufweisen.
- Beim Braten ein Gefäß mit Wasser auf den Boden des Ofens stellen, damit das
  Fruchtfleisch nicht austrocknet.
** Gurkenjoghurt
:PROPERTIES:
:Source:    Jerusalem - Das Kochbuch
:Portions:  8
:Category:  Beilagen
:Meal:      Beilage
:END:

*** Einführung
Diese erfrischende Mischung aus Joghurt und Salatgurke ist die ideale Ergänzung zu vielen
herzhaften Speisen. Wir lieben den Gurkenjoghurt und essen ihn zu so gut wie allem. Die
palästinensische Variante – Khyar B'laban – wird häufig zu Reisgerichten (Mejadra, siehe
Seite 120), aber auch zu Lamm und Hähnchen (Lamm-Shawarma, siehe Seite 210, und
Hähnchen-Soffritto, siehe Seite 190) serviert. Die Aschkenasim verwenden saure Sahne
anstelle von Joghurt oder machen die Gurken lediglich mit Öl, Zucker, Frühlingszwiebel,
Dill und Essig an.

*** Zutaten
| Menge | Einheit | Zutat                     |
|-------+---------+---------------------------|
|     2 |         | Minigurken (200g)         |
|   500 | g       | griechischer Joghurt      |
|     1 |         | Knoblauchzehe, zerdrückt  |
|     1 | Prise   | Cayennepfeffer            |
|     1 | EL      | getrocknete Minze         |
|     2 | EL      | frische gehackte Minze    |
|     2 | EL      | Zitronensaft              |
|     ½ | TL      | Salz                      |
|     ¼ | TL      | gemahlener weißer Pfeffer |

*** Zubereitung
1. Die Gurken schälen und in hauchdünne Scheiben schneiden.
2. Die übrigen Zutaten verrühren, die Gurke dazugeben und noch einmal abschmecken.
3. Den Gurkenjoghurt 30 Minuten im Kühlschrank durchziehen lassen und gut gekühlt
   servieren.

*** Notizen
- Serviervorschläge: zu Reisgerichten (Mejadra), Lamm-Shawarma oder Hähnchen-Soffritto
- Aschkenasische Variante: mit saurer Sahne statt Joghurt
- Alternative Zubereitung: Gurken nur mit Öl, Zucker, Frühlingszwiebel, Dill und Essig
  anmachen
- Die Gurken sollten sehr dünn geschnitten werden
- Vor dem Servieren 30 Minuten durchziehen lassen
- Gut gekühlt servieren
** Mangold mit Tahini-Joghurt-Sauce & Pinienkernen
:PROPERTIES:
:Source:    Jerusalem - Das Kochbuch
:Portions:  4
:Category:  Gemüsegericht
:Meal:      Beilage, Hauptgericht
:END:

*** Einführung
Mangold ist eines der beliebtesten Blattgemüse in Jerusalem. Er hat ein angenehm herbes
Aroma und zerfällt beim Kochen nicht so leicht. Gerne werden die Blätter gefüllt oder auch
einfach mit Kräutern und verschiedenen Gewürzen gegart. Ganz wichtig: Knoblauch! Mit einer
Tahini-Joghurt-Sauce wird aus dem Mangold eine interessante Gemüsebeilage, die den
Geschmack des Hauptgerichts nicht überdeckt. Probieren Sie ihn einmal zu Mejadra (siehe
Seite 120) oder Lamm-Shawarma (siehe Seite 210).

*** Zutaten
| Menge | Einheit | Zutat                                                     |
|-------+---------+-----------------------------------------------------------|
|   1.3 | kg      | Mangold                                                   |
|    40 | g       | Butter                                                    |
|     2 | EL      | Olivenöl, plus Olivenöl zum Beträufeln                    |
|    40 | g       | Pinienkerne                                               |
|     2 | Stück   | kleine Knoblauchzehen, in hauchdünne Scheiben geschnitten |
|    60 | ml      | trockener Weißwein                                        |
|       |         | Paprikapulver edelsüß zum Bestreuen (nach Belieben)       |
|       |         | Salz und schwarzer Pfeffer                                |

Für die Sauce:
| Menge | Einheit | Zutat                      |
|-------+---------+----------------------------|
|    50 | g       | helles Tahini (Sesampaste) |
|    50 | g       | griechischer Joghurt       |
|     2 | EL      | Zitronensaft               |
|     1 | Stück   | Knoblauchzehe, zerdrückt   |

*** Zubereitung
1. Die Saucenzutaten mit 1 Prise Salz und 2 Esslöffeln Wasser in einer mittelgroßen
   Schüssel mit einem kleinen Schneebesen zu einer glatten, halbfesten Paste aufschlagen.
2. Die Mangoldstiele mit einem scharfen Messer heraustreinen und in 2cm breite Stücke
   schneiden.
3. In einem großen Topf reichlich Wasser zum Kochen bringen, salzen und die Mangoldstiele
   2 Minuten darin garen.
4. Die Blätter hinzufügen und 1 Minute mitkochen.
5. Das Gemüse in ein Sieb abgießen, unter fließendem kaltem Wasser abschrecken und
   abtropfen lassen.
6. Die Blätter anschließend gut ausdrücken.
7. In einer großen Pfanne die Hälfte der Butter mit dem Olivenöl bei mittlerer Hitze heiß
   werden lassen und die Pinienkerne darin etwa 2 Minuten goldbraun rösten.
8. Die Pfanne dabei immer wieder rütteln.
9. Die Pinienkerne mit einem Schaumlöffel aus der Pfanne heben, den Knoblauch hineingeben
   und etwa 1 Minute goldbraun braten.
10. Den Wein angießen und auf etwa ein Drittel einkochen lassen.
11. Den Mangold und die restliche Butter dazugeben und das Gemüse 2-5 Minuten unter
    gelegentlichem Rühren erhitzen.
12. Mit ½ Teelöffel Salz und etwas Pfeffer würzen.
13. Den Mangold auf vier kleine Schüsseln verteilen, mit etwas Sauce überziehen und mit
    den Pinienkernen bestreuen.
14. Nach Belieben mit Olivenöl beträufeln und etwas Paprikapulver darüberstreuen.

*** Notizen
- Passt gut zu:
  - Mejadra
  - Lamm-Shawarma
- Die Sauce sollte eine halbfeste Konsistenz haben
- Paprikapulver zum Bestreuen ist optional
** Ruths gefüllte Paprikaschoten
:PROPERTIES:
:Source:    Jerusalem - Das Kochbuch
:Portions:  4 (reichlich)
:Category:  Gemüsegerichte
:Meal:      Hauptgericht
:END:

*** Einführung
Dieses einfache, aber ausgesprochen leckere Gericht stammt von Yotams Mutter. Dazu noch
ein Kohlrabisalat (siehe Seite 46) – und fertig ist eine herrliche Mahlzeit. Achten Sie
darauf, dass die Pfanne oder der Topf groß genug ist, um die Paprikaschoten nebeneinander
aufzunehmen. Ansonsten besser in zwei Portionen garen.

*** Zutaten
| Menge | Einheit | Zutat                                     |
|-------+---------+-------------------------------------------|
|     8 |         | mittelgroße rote Spitzpaprika             |
|     1 | große   | Tomate (170g), grob gehackt               |
|     2 |         | mittelgroße Zwiebeln (250g), grob gehackt |
|   500 | ml      | Gemüsebrühe                               |
|   140 | g       | Basmatireis                               |
|    1½ | EL      | Baharat-Gewürzmischung (siehe Seite 299)  |
|     ½ | TL      | gemahlener Kardamom                       |
|     2 | EL      | Olivenöl                                  |
|     1 | große   | Zwiebel (200g), fein gehackt              |
|   400 | g       | Lammhackfleisch                           |
|    2½ | EL      | gehackte glatte Petersilie                |
|     2 | EL      | gehackter Dill                            |
|    1¾ | EL      | getrocknete Minze                         |
|    1½ | TL      | Zucker                                    |
|       |         | Salz und schwarzer Pfeffer                |

*** Zubereitung
1. Für die Füllung den Reis in einem Topf mit leicht gesalzenem Wasser bedecken, zum
   Kochen bringen und 4 Minuten kochen lassen. In ein Sieb abgießen, unter fließendem
   kaltem Wasser abschrecken und zur Seite stellen.
2. Die Gewürze in einer Pfanne ohne Fett anrösten. Olivenöl und Zwiebel hinzufügen und die
   Zwiebel unter häufigem Rühren etwa 7 Minuten anschwitzen, bis sie weich ist.
3. Den Pfanneninhalt mit Reis, Fleisch, Kräutern, Zucker sowie 1 Teelöffel Salz in eine
   große Schüssel füllen und die Zutaten sorgfältig mit den Händen vermengen.
4. Die Paprikaschoten vom Stielansatz her mit einem kleinen Messer zu zwei Drittel
   aufschneiden, sodass eine Öffnung entsteht. Die Stielansätze stehen lassen. Die Samen
   vorsichtig entfernen und die Schoten mit der Farce (jeweils etwa 100g) füllen.
5. Tomaten- und Zwiebelwürfel in einer großen Pfanne mit fest schließendem Deckel
   verteilen. Die Paprikaschoten dicht an dicht darauflegen und so viel Brühe angießen,
   dass sie etwa 1cm hoch steht.
6. Mit ½ Teelöffel Salz und etwas Pfeffer würzen, den Deckel auflegen und das Gemüse bei
   geringster Hitze 1 Stunde garen. Dabei darauf achten, dass der Pfannenboden immer mit
   etwas Flüssigkeit bedeckt ist.
7. Die Paprikaschoten warm oder mit Zimmertemperatur servieren.

*** Notizen
- Das Rezept lässt sich auch in zwei Portionen zubereiten, wenn die Pfanne zu klein ist
- Die Baharat-Gewürzmischung findet sich im Rezept auf Seite 299
- Als Beilage wird ein Kohlrabisalat empfohlen
- Die Füllung muss gut mit den Händen vermengt werden
- Die Paprika können warm oder bei Zimmertemperatur serviert werden
- Wichtig ist, dass während des Garens immer etwas Flüssigkeit im Topf ist
** Salat von geröstetem Blumenkohl mit Haselnüssen
:PROPERTIES:
:Source:    Jerusalem - Das Kochbuch
:Portions:  2-4
:Category:  Salat
:Meal:      Hauptgericht/Beilage
:END:

*** Einführung
Roh oder nur kurz gegart, eignet sich Blumenkohl hervorragend für Salate, vor allem im
Winter, wenn das Angebot an frischem Gemüse nicht sehr groß ist. Blumenkohl nimmt Aromen
gut an und harmoniert wunderbar mit süßen wie scharfen Zutaten. Zu diesem Salat, der
vorzüglich zu Hähnchen-Soffritto (siehe Seite 190) und Gegrillten Fischspießen mit Hawayej
und Petersilie (siehe Seite 226) passt, hat mich ein Rezept der brillanten australischen
Köchin und Autorin Karen Martini inspiriert.

*** Zutaten
| Menge | Einheit | Zutat                            |
|-------+---------+----------------------------------|
|   660 | g       | Blumenkohl                       |
|     5 | EL      | Olivenöl                         |
|    30 | g       | Haselnusskerne                   |
|     1 | St      | große Stange Sellerie            |
|    10 | g       | kleine glatte Petersilienblätter |
|    50 | g       | Granatapfelkerne                 |
|   0.5 | TL      | Zimt                             |
|   0.5 | TL      | gemahlener Piment                |
|     1 | EL      | Sherryessig                      |
|   1.5 | TL      | Ahornsirup                       |
|     - | -       | Salz und schwarzer Pfeffer       |

*** Zubereitung
1. Den Backofen auf 220°C vorheizen.

2. Den Blumenkohl in einer Mischung aus 3 Esslöffeln Olivenöl, ½ Teelöffel Salz und etwas
   Pfeffer wenden. In einer ofenfesten Form verteilen und 25-35 Minuten auf der obersten
   Schiene des Backofens rösten, bis er knusprig braun ist. Anschließend in eine Schüssel
   füllen und abkühlen lassen.

3. Die Backofentemperatur auf 170°C herunterschalten. Die Haselnusskerne auf ein mit
   Backpapier ausgelegtes Blech streuen und 17 Minuten rösten.

4. Die Nusskerne etwas abkühlen lassen, grob hacken und mit den übrigen Zutaten zum
   Blumenkohl geben. Den Salat durchmischen, mit Salz und Pfeffer abschmecken und
   zimmerwarm servieren.

*** Notizen
* Gebäck & Teig
** Blätterteigkuchen mit Paprika & Spiegelei
:PROPERTIES:
:Source:    Jerusalem - Das Kochbuch
:Portions:  4
:Category:  Pikantes Gebäck
:Meal:      Vorspeise/Mezze
:END:

*** Einführung
Kaum hat man in einem arabischen Restaurant in Jerusalem Platz genommen, füllt sich der
Tisch auch schon mit unzähligen Mezze in allen Formen und Farben (wir fragen uns jedes
Mal, wie man danach noch etwas essen kann, doch kaum werden die berühmten gegrillten
Fleischspieße serviert, erübrigt sich diese Frage ...). Wunderbar saftige geröstete
Paprikaschoten gehören natürlich auch auf den Mezze-Teller.

Das Rot der Paprikaschoten und die gelben Dotter machen diesen Snack nicht nur zu einem
Gaumen-, sondern auch zu einem Augenschmaus. Der Kuchen ist einfach zuzubereiten,
wunderbar knusprig und schmeckt auch Kindern. Wenn er kalt serviert werden soll, empfiehlt
es sich, die Eier durch Feta zu ersetzen.

*** Zutaten
| Menge | Einheit | Zutat                                                                                                   |
|-------+---------+---------------------------------------------------------------------------------------------------------|
|     4 |         | mittelgroße rote Paprikaschoten, halbiert, von den Samen befreit und in 1cm breite Streifen geschnitten |
|     3 |         | kleine Zwiebeln, halbiert und in 2cm breite Spalten geschnitten                                         |
|     4 | Zweige  | Thymian, die Blätter abgezupft und gehackt                                                              |
|     1 | TL      | gemahlener Koriander                                                                                    |
|    1½ | TL      | gemahlener Kreuzkümmel                                                                                  |
|     6 | EL      | Olivenöl, plus Öl zum Beträufeln                                                                        |
|    1½ | EL      | grob gehackte glatte Petersilie                                                                         |
|    1½ | EL      | grob gehackte Korianderblätter                                                                          |
|   250 | g       | Blätterteig                                                                                             |
|    30 | g       | saure Sahne                                                                                             |
|     4 |         | Eier (oder 160g Feta, zerkrümelt), plus 1 Ei, leicht verquirlt                                          |
|       |         | Salz und grob geschroteter schwarzer Pfeffer                                                            |

*** Zubereitung
1. Den Backofen auf 210°C vorheizen.
2. In einer großen Schüssel die Paprikaschoten mit Zwiebeln, Thymianblättern, Gewürzen,
   Olivenöl und 1 kräftigen Prise Salz mischen. Auf einem Backblech verteilen und 35
   Minuten im Backofen rösten.
3. Das Gemüse dabei gelegentlich wenden. Es sollte weich werden, aber nicht bräunen.
4. Aus dem Ofen nehmen, die Hälfte der frischen Kräuter untermischen und noch einmal
   abschmecken.
5. Die Backofentemperatur auf 220°C erhöhen.
6. Den Blätterteig auf der leicht bemehlten Arbeitsfläche etwa 3mm dick ausrollen und vier
   15cm große Quadrate zurechtschneiden.
7. Mehrfach mit einer Gabel einstechen, in ausreichendem Abstand auf ein mit Backpapier
   bedecktes Blech legen und mindestens 30 Minuten im Kühlschrank ruhen lassen.
8. Den Teig oben und an den Seiten mit verquirltem Ei bepinseln und jedes Quadrat mit ½
   Esslöffel saurer Sahne bestreichen. Dabei einen 0,5cm breiten Rand frei lassen.
9. Jeweils 3 Esslöffel der Paprika-Zwiebel-Mischung gleichmäßig auf den Teigstücken
   verteilen und in die Mitte eine leichte Vertiefung für das Ei drücken.
10. Die Teigstücke 14 Minuten im Ofen backen, anschließend herausnehmen und die Eier
    vorsichtig über den Vertiefungen aufschlagen.
11. Wieder in den Ofen schieben und weitere 7 Minuten backen, bis die Eier gerade gestockt
    sind.
12. Mit grob geschrotetem Pfeffer und den restlichen Kräutern bestreuen, mit Olivenöl
    beträufeln und sofort servieren.

*** Notizen
- Für eine kalte Variante können die Eier durch 160g zerkrümelten Feta ersetzt werden
- Das Gemüse sollte weich werden, aber nicht bräunen
- Der Teig muss mindestens 30 Minuten im Kühlschrank ruhen
- Das Gericht sollte sofort serviert werden
- Das Rezept ist Teil der Mezze-Tradition Jerusalems
** Ka'ach Bilmalch
:PROPERTIES:
:Source:    Jerusalem - Das Kochbuch
:Portions:  30-40 Stück
:Category:  Pikantes Gebäck
:Meal:      Snack
:END:

*** Einführung
Diese einfachen pikanten Kekse hat eigentlich jeder Jerusalemer stets zu Hause vorrätig.
Yotams Vater hat die Angewohnheit, mitten in der Nacht in die Küche zu schleichen und sich
ein paar davon zu Gemüte zu führen – ohne dass es jemand merkt, versteht sich. Das Gebäck
ist nicht sehr gehaltvoll, deshalb passt dazu gut ein Käsedip, oder man genießt es einfach
so mit einem Glas Bier, Arak auf Eis oder einer Tasse schwarzem Kaffee. Der Dip ist
lediglich als Anregung gedacht, falls Sie die Kekse einmal als kleines Amuse-Gueule vor
einem Abendessen servieren möchten.

*** Zutaten
| Menge | Einheit | Zutat                                      |
|-------+---------+--------------------------------------------|
|   500 | g       | Mehl                                       |
|   100 | ml      | Sonnenblumenöl                             |
|   100 | g       | weiche Butter, in Würfel geschnitten       |
|     1 | TL      | Trockenhefe                                |
|     1 | TL      | Backpulver                                 |
|     1 | TL      | Zucker                                     |
|    1½ | TL      | Salz                                       |
|     ½ | TL      | gemahlener Kreuzkümmel                     |
|    1½ | EL      | Fenchelssamen, geröstet und grob zerstoßen |
|     1 |         | Ei (Gewichtsklasse M), verquirlt           |
|     1 | TL      | weiße Sesamsamen                           |
|     1 | TL      | schwarze Sesamsamen                        |

Für den Dip:
| Menge | Einheit | Zutat                      |
|-------+---------+----------------------------|
|    35 | g       | glatte Petersilie          |
|     1 |         | Knoblauchzehe, zerdrückt   |
|    25 | g       | helles Tahini (Sesampaste) |
|   125 | g       | griechischer Joghurt       |
|    25 | ml      | Zitronensaft               |
|     1 | Prise   | Salz                       |

*** Zubereitung
1. Den Backofen auf 200°C vorheizen.
2. Das Mehl in eine große Schüssel sieben und eine Mulde in die Mitte drücken.
3. Das Öl hineingießen, Butter, Hefe, Backpulver, Zucker, Salz und Gewürze dazugeben und
   die Zutaten vermengen.
4. Nach und nach etwa 100 ml Wasser unterrühren, bis der Teig glatt ist.
5. Anschließend einige Minuten durchkneten.
6. Zwei Backbleche mit Backpapier auslegen.
7. Aus dem Teig kleine Kugeln (à etwa 25 g) formen und auf der Arbeitsfläche zu etwa 1 cm
   dicken und 12-13 cm langen Streifen rollen.
8. Zu Ringen formen und im Abstand von etwa 2 cm auf die Bleche legen.
9. Mit dem verquirlten Ei bepinseln, mit Sesam bestreuen und 50 Minuten gehen lassen.
10. Die Kekse in den Backofen schieben und 22 Minuten goldbraun backen.
11. Auskühlen lassen und in einem Schraubglas oder einem luftdicht verschließbaren
    Behälter aufbewahren.

Für den Dip:
1. Sämtliche Zutaten im Mixer glatt pürieren.
2. Ist er zu dick, etwas Wasser hinzufügen.

*** Notizen
- Das Gebäck ist maximal 10 Tage haltbar
- Die Kekse können als Snack oder als Amuse-Gueule serviert werden
- Serviervorschläge: mit Käsedip, Bier, Arak auf Eis oder schwarzem Kaffee
- Der Teig muss 50 Minuten gehen
- Für den Dip kann die Konsistenz nach Belieben mit Wasser angepasst werden
** Latkes
:PROPERTIES:
:Source:    Jerusalem - Das Kochbuch
:Portions:  4
:Category:  Kartoffelgericht
:Meal:      Vorspeise, Beilage
:END:

*** Einführung
Wir möchten unserer Freundin Helen Goh danken, die diesem aschkenasischen Chanukkagericht
den letzten Schliff gegeben hat. Latkes sollte man jedoch nicht nur an Feiertagen
servieren, denn sie sind wirklich lecker und eignen sich hervorragend als Vorspeise,
passen aber auch gut zu gebratenem Rindfleisch. Oft serviert man sie auch mit süßen
Beilagen. In diesem Fall den Schnittlauch weglassen und weniger Salz verwenden. Die Latkes
warm mit Zucker bestreuen und mit saurer Sahne servieren.

*** Zutaten
| Menge | Einheit | Zutat                                                      |
|-------+---------+------------------------------------------------------------|
|   600 | g       | vorwiegend festkochende Kartoffeln, geschält und geraspelt |
|   300 | g       | Pastinaken, geschält und geraspelt                         |
|    30 | g       | Schnittlauch, in feine Röllchen geschnitten                |
|     4 | Stück   | Eiweiß                                                     |
|     2 | EL      | Maisstärke                                                 |
|    80 | g       | Butter                                                     |
|   100 | ml      | Sonnenblumenöl                                             |
|       |         | saure Sahne zum Servieren                                  |
|       |         | Salz und frisch gemahlener schwarzer Pfeffer               |

*** Zubereitung
1. Die Kartoffeln in eine große Schüssel mit kaltem Wasser geben, um die Stärke
   abzuspülen.
2. In einem Sieb abtropfen lassen, ausdrücken und auf einem sauberen Geschirrtuch
   ausbreiten.
3. Sie sollen vollständig trocken.
4. In einer großen Schüssel die Kartoffeln mit den Pastinaken, dem Schnittlauch, den
   Eiweißen, der Stärke, 1 Teelöffel Salz und reichlich Pfeffer vermengen.
5. In einer großen Pfanne die Hälfte der Butter mit der Hälfte des Öls bei mittlerer bis
   hoher Temperatur erhitzen.
6. Etwa 2 Esslöffel von der Kartoffelmischung abstechen und die Flüssigkeit zwischen den
   Handflächen herauspressen.
7. Die Masse zu etwa 1 cm dicken und 8 cm breiten Küchlein formen.
8. Die Latkes portionsweise in die Pfanne legen, mit einem Löffelrücken glatt streichen
   und auf jeder Seite 3 Minuten knusprig braun backen.
9. Aus der Pfanne nehmen, auf Küchenpapier abtropfen lassen und warm stellen, bis alle
   gebacken sind.
10. Dabei nach und nach die restliche Butter und das restliche Öl hinzufügen.
11. Die Latkes sofort servieren und die saure Sahne dazu reichen.

*** Notizen
- Variante für süße Zubereitung:
  - Schnittlauch weglassen
  - Weniger Salz verwenden
  - Warm mit Zucker bestreuen
- Ursprünglich ein Chanukkagericht
- Serviervorschläge:
  - Als Vorspeise
  - Zu gebratenem Rindfleisch
  - Mit süßen Beilagen
* Grundrezepte
** Grundrezept für Hummus
:PROPERTIES:
:Source:    Jerusalem - Das Kochbuch
:Portions:  4
:Category:  Dip
:Meal:      Vorspeise, Mezze
:END:

*** Einführung
Dieses supersämige Hummus wird mit viel Tahini zubereitet - so lieben wir es. Im
Kühlschrank ist es bis zu drei Tage haltbar. Man streicht das Püree einfach auf einen
kleinen Teller, träufelt etwas Olivenöl darüber und isst es mit einem Stück Pita oder
knusprigem Weißbrot. Das Hummus auch wesentlicher Bestandteil einer sättigenden Mahlzeit
sein kann, zeigen die beiden folgenden, in Jerusalem außerordentlich beliebten Rezepte.
Die Grundzubereitung kann nach Belieben abgewandelt werden, etwa indem man gekochte und
zerdrückte Kichererbsen untermischt, damit das Ganze mehr Biss bekommt, oder indem man das
Püree noch mit etwas Kreuzkümmel verfeinert.

*** Zutaten
| Menge | Einheit | Zutat                      |
|-------+---------+----------------------------|
|   250 | g       | Kichererbsen               |
|     1 | TL      | Backnatron                 |
|   270 | g       | helles Tahini (Sesampaste) |
|     4 | EL      | Zitronensaft               |
|     4 | Stück   | Knoblauchzehen, zerdrückt  |
|   1.5 | TL      | Salz                       |
|   100 | ml      | eiskaltes Wasser           |

*** Zubereitung
1. Am Vortag die Kichererbsen gründlich waschen, in eine große Schüssel füllen, mit der
   doppelten Menge Wasser bedecken und über Nacht einweichen.
2. Die Kichererbsen am nächsten Tag abgießen. Mit dem Backnatron in einen mittelgroßen
   Topf füllen und bei starker Hitze etwa 3 Minuten unter Rühren erhitzen.
3. 1½ Liter Wasser angießen, zum Kochen bringen und abschäumen.
4. Je nach Sorte und Alter der Kichererbsen beträgt die Kochzeit zwischen 20 und 40
   Minuten.
5. Die Kichererbsen sollten anschließend sehr weich sein und sich mühelos zwischen Daumen
   und Zeigefinger zerdrücken lassen.
6. Die Kichererbsen abgießen (das Gewicht sollte jetzt etwa 600g betragen) und in der
   Küchenmaschine pürieren.
7. Bei laufendem Motor Tahini, Zitronensaft, Knoblauch und Salz hinzufügen.
8. Zum Schluss das Eiswasser langsam dazugießen und das Ganze etwa 5 Minuten verrühren,
   bis eine glatte, cremige Paste entstanden ist.
9. In eine Schüssel füllen, mit Frischhaltefolie abdecken und mindestens 30 Minuten ruhen
   lassen.
10. Wenn es nicht sofort verbraucht wird, im Kühlschrank aufbewahren und vor dem Servieren
    rechtzeitig herausnehmen.

*** Notizen
- Haltbarkeit im
Kühlschrank: bis zu 3 Tage
- Variationen:
  - Mit gekochten und zerdrückten Kichererbsen für mehr Textur
  - Mit Kreuzkümmel verfeinert
- Serviervorschlag:
  - Auf einem Teller ausstreichen
  - Mit Olivenöl beträufeln
  - Mit Pita oder knusprigem Weißbrot servieren
** Tahini-Sauce
:PROPERTIES:
:Source:    Jerusalem - Das Kochbuch
:Portions:  350 Milliliter
:Category:  Saucen
:Meal:      Beilage
:END:

*** Einführung
Einem Außenstehenden zu vermitteln, weshalb Tahini von den Einheimischen so geschätzt
wird, ist nicht einfach. Als wir in Jerusalem einen Dokumentarfilm für die BBC drehten,
versuchten wir, James und Lauren, die beiden Teammitglieder aus England, dafür zu
begeistern. Es ist uns nicht gelungen, obwohl wir es ihnen sogar heimlich ins Essen
schmuggelten. Beide bemerkten es und meinten, es würde jedes Gericht verderben, sei es nun
ein saftiges Kebab oder ein frischer Salat. Sie konnten sich zwar damit anfreunden, dass
man Tahini unter die Auberginenpüree mischt, aber als Hauptzutat einer Sauce mochten sie
es sich nicht vorstellen. Leider war das die Zutat, die in Ost- wie in Westjerusalem, bei
Juden wie Palästinensern, in Privathäusern wie im Restaurant stets auf dem Tisch stand –
ob nun pur, verdünnt, mit oder ohne Gewürze, mit Knoblauch, Zitronensaft und Olivenöl
gemischt, mit Paprikaschoten oder Petersilie kombiniert, als Salatdressing oder Würzsauce,
ja sogar in Desserts (Tahini-Plätzchen, siehe Seite 292).

Auch bei den Gästen unserer Restaurants erfreuen sich Tahini-Saucen großer Beliebtheit.
Wir servieren sie zu geröstetem und frischem Gemüse ebenso wie zu Fisch und Fleisch.

Hauptbestandteil der Sauce ist eine Paste aus fein gemahlenen Sesamsamen, die man in
arabischen und türkischen Lebensmittelgeschäften findet (Tahin, Tahina oder Tahini). Die
verschiedenen Produkte unterscheiden sich zum Teil erheblich in Qualität, Geschmack, Farbe
und Konsistenz. Sesam aus Äthiopien gilt als der beste, auch wenn sich manche Sorten
besser für Öle und andere eher für Pasten eignen. Die Samen können geröstet werden oder
man lässt sie keimen und mahlt sie anschließend. Verarbeitet man sie mit Schale, wird die
Paste dunkler und kompakter, verwendet man sie geschält, wird die Paste heller und
leichter. Die Qualität der Paste hängt vor allem vom Sesam ab.

Die anspruchsvollen Jerusalemer können sich nur schwer darauf einigen, welches die beste
der heimischen Marken ist, die vorwiegend in Jerusalem, Nablus und Nazareth hergestellt
werden. Wir geben Produkten aus dem Libanon, aus Palästina und Israel den Vorzug vor
Erzeugnissen aus Griechenland und Zypern.

*** Zutaten
| Menge | Einheit | Zutat                                |
|-------+---------+--------------------------------------|
|   150 | g       | helles Tahini (Sesampaste)           |
|     2 | EL      | Zitronensaft                         |
|     1 |         | mittelgroße Knoblauchzehe, zerdrückt |
|     ¼ | TL      | Salz                                 |

*** Zubereitung
1. Bevor Sie mit der Zubereitung beginnen, die Sesampaste gut umrühren, weil sich das Fett
   gerne absetzt.
2. Die Paste mit 120 ml Wasser, Zitronensaft, Knoblauch und Salz in einer mittelgroßen
   Schüssel zu einer dicken Sauce verrühren, die in etwa die Konsistenz von flüssigem
   Honig haben sollte.
3. Falls nötig, noch ein paar Tropfen Wasser hinzufügen.
4. In ein Schraubglas füllen und im Kühlschrank aufbewahren.

*** Notizen
- Die Sauce ist bis zu 1 Woche im Kühlschrank haltbar
- Vor dem Gebrauch umrühren und falls nötig etwas verdünnen
- Die Qualität der Sauce hängt stark von der verwendeten Tahini-Paste ab
- Die Sauce sollte die Konsistenz von flüssigem Honig haben
- Einsetzbar zu geröstetem und frischem Gemüse, Fisch und Fleisch
- Bevorzugt werden Tahini-Produkte aus dem Libanon, Palästina und Israel
