#+TITLE: BBC Good Food Slow Cooker Rezepte
#+AUTHOR: BBC Good Food
#+DATE: 2025-05-07

* Getränke
** Slow Cooker Mulled Cider
:PROPERTIES:
:ORIGINAL: https://www.bbcgoodfood.com/recipes/slow-cooker-mulled-cider
:END:

*** Zutaten
- 1,5 Liter trockener Apfelwein
- 500ml Apfelsaft
- 75g hellbrauner weicher Zucker
- 1 Orange, in Scheiben geschnitten
- ½ Zitrone, Schale in Streifen abgeschält
- 5 Nelken
- 10 Pimentkörner
- 3 Kardamomkapseln, mit einem Nudelholz zerdrückt
- 2 Lorbeerblätter
- 2 Zimtstangen
- 100ml Calvados (Apfel- oder normaler Brandy)

*** Anweisungen zum Kochen
1. Alle Zutaten außer dem Calvados in einen Slow Cooker geben und 1 Stunde auf hoher Stufe oder bis zu 4 Stunden auf niedriger Stufe kochen lassen.
2. Kurz vor dem Servieren den Calvados unterrühren. In hitzebeständige Gläser oder Tassen füllen zum Servieren.
*** Zutaten
- 2 x 400g Dosen gehackte Tomaten
- 1 rote Zwiebel, gehackt
- 1 Karotte, gehackt
- 1 Rosmarinzweig
- 2 EL Tomatenmark
- 1 Gemüsebrühwürfel
- 2 Lorbeerblätter
- 2 EL Sahne
- Croutons zum Servieren (optional)

*** Anweisungen zum Kochen
1. Alles außer der Sahne und den Croutons in den Slow Cooker geben, zusammen mit 500ml heißem Wasser. 3 Stunden auf hoher Stufe oder 5 Stunden auf niedriger Stufe kochen lassen.
2. Den Rosmarin entfernen. Die Suppe pürieren, entweder mit einem Stabmixer, was Sie im Slow Cooker tun können, oder in einem Standmixer, bis sie glatt ist. Wenn Sie eine dünnere Suppe mögen, können Sie bis zu 250ml mehr heißes Wasser hinzufügen. *Hält sich drei Tage im Kühlschrank.* In Schüsseln füllen, etwas Sahne darüber träufeln und nach Belieben mit Croutons bestreuen.

**** Tipps
Servieren Sie die Suppe mit Croutons, die mit etwas Kreuzkümmel bestäubt sind, oder versuchen Sie, Halloumi-Croutons herzustellen, indem Sie Halloumi-Würfel in etwas Olivenöl wenden und im Ofen backen, bis sie goldbraun und knusprig sind.

Wenn Sie keinen Slow Cooker haben, kann dieses Suppenrezept leicht angepasst werden, um in einem Schnellkochtopf zu funktionieren. Fahren Sie wie oben mit Schritt 1 fort und kochen Sie 5-10 Minuten auf hoher Stufe, dann fahren Sie mit dem Rest des Rezepts fort.

** Slow Cooker Breakfast Beans
:PROPERTIES:
:ORIGINAL: https://www.bbcgoodfood.com/recipes/slow-cooker-breakfast-beans
:END:

*** Zutaten
- 1 EL Olivenöl
- 1 Zwiebel, dünn geschnitten
- 2 Knoblauchzehen, gehackt
- 1 EL Weiß- oder Rotweinessig
- 1 gehäufter EL weicher brauner Zucker
- 400g Dose Pintobohnen, abgetropft und abgespült
- 200ml Passata
- Kleines Bund Koriander, gehackt

*** Anweisungen zum Kochen
1. Den Slow Cooker bei Bedarf vorheizen. Das Öl in einer großen Bratpfanne erhitzen und die Zwiebel anbraten, bis sie beginnt, braun zu werden, dann den Knoblauch hinzufügen und 1 Minute kochen. Den Essig und den Zucker hinzufügen und 1 Minute köcheln lassen. Die Bohnen und Passata unterrühren und mit schwarzem Pfeffer würzen. Alles in den Slow Cooker geben.
2. 5 Stunden auf niedriger Stufe kochen. Wenn die Sauce ein wenig dünn erscheint, die Hitze auf hohe Stufe stellen und noch einige Minuten kochen. Den Koriander unterrühren.

* Gemüse und Beilagen                                                                      :beilage:
** Slow Cooker Aubergines
:PROPERTIES:
:ORIGINAL: https://www.bbcgoodfood.com/recipes/slow-cooker-aubergines
:END:

*** Anweisungen zum Kochen
1. Die Hälfte des Olivenöls in den Slow Cooker gießen und die Zwiebeln und den zerdrückten Knoblauch darauf legen. Die Auberginen der Länge nach in 1 cm dicke Scheiben schneiden und mit dem restlichen Olivenöl bestreichen. Sie in den Slow Cooker auf die Zwiebeln legen und die Tomaten, Fenchelscheiben und getrockneten Tomaten zwischen die Auberginen legen. Die Koriandersamen darüberstreuen und alles gut mit Salz und Pfeffer würzen.
2. 6-8 Stunden auf niedriger Stufe kochen oder bis die Auberginen weich sind. Nach dem Garen alle Zutaten für das Dressing in eine kleine Küchenmaschine geben und glatt pürieren.
3. Das gekochte Gemüse mit einem Schaumlöffel auf eine Servierplatte geben und das Kräuterdressing darüber träufeln. Mit zerbröckeltem Feta-Käse und Mandelblättchen garnieren und mit etwas knusprigem Brot dazu servieren.

** Slow Cooker Red Cabbage
:PROPERTIES:
:ORIGINAL: https://www.bbcgoodfood.com/recipes/slow-cooker-red-cabbage
:END:

*** Zutaten
- 1kg Rotkohl
- 2 weiße Zwiebeln, gehackt
- 4 Granny Smith Äpfel, geschält, entkernt und gehackt
- Abrieb von 1 Orange oder 2 Clementinen
- 2 TL gemahlenes Mischgewürz
- 100g hellbrauner weicher Zucker
- 3 EL Apfelessig
- 200ml trockener Apfelwein
- 25g Butter

*** Anweisungen zum Kochen
1. Ihren Slow Cooker auf niedrige Stufe erhitzen. Die äußeren Blätter vom Kohl abziehen und entsorgen. Den Kohl vierteln, den harten Strunk entfernen, dann in dünne Scheiben schneiden. Eine Schicht des Kohls auf den Boden Ihres Slow Cookers legen, dann mit einigen der Zwiebeln, Äpfel, Abrieb, Mischgewürz, Zucker und etwas Gewürzen bedecken. Weiterhin Schichten bilden, bis Sie diese Zutaten aufgebraucht haben. Würzen.
2. Den Essig und den Apfelwein darüber gießen und die Butter darauf verteilen. Mit einem Deckel abdecken und 4-5 Stunden kochen lassen, bis der Kohl zart ist. *Hält sich im Kühlschrank abgedeckt bis zu drei Tage oder im Gefrierschrank bis zu zwei Monate*. In einer Pfanne oder in der Mikrowelle wieder aufwärmen.

**** Tipps
Die Temperatur von Slow Cookern kann stark variieren; Sie werden Ihren Slow Cooker besser kennenlernen, je mehr Sie ihn benutzen.

Auf einer hohen Einstellung sollte der Kohl 2-3 Stunden brauchen. Kleinere Slow Cooker kochen schneller als größere.

** Simple Sweet & Sour Slow-Cooker Red Cabbage
:PROPERTIES:
:ORIGINAL: https://www.bbcgoodfood.com/recipes/simple-sweet-sour-slow-cooker-red-cabbage
:END:

*** Zutaten
- 1 Rotkohl (etwa 1kg), geviertelt und fein geschnitten
- ½ TL gemahlenes Mischgewürz
- 50g hellbrauner weicher Zucker
- 75ml Rotweinessig
- Ein großes Stück Butter

*** Anweisungen zum Kochen
1. Den Slow Cooker auf niedrige Stufe erhitzen. Den Kohl hineingeben, dann das Mischgewürz, den Zucker und etwas Salz und Pfeffer darüberstreuen. Den Essig einrühren, gut umrühren, dann die Butter darauf verteilen. Den Deckel aufsetzen und 3 Std. 30 Min. kochen lassen, bis der Kohl weich wird.
2. Den Deckel abnehmen und weitere 30 Minuten kochen lassen, bis der Kohl sehr zart und klebrig ist und die Flüssigkeit reduziert ist. Abschmecken und servieren. *Nach dem Abkühlen hält sich der Kohl bis zu drei Tage abgedeckt und gekühlt oder bis zu zwei Monate eingefroren. Im Slow Cooker oder in einer Pfanne bei mittlerer Hitze wieder erhitzen, bis er sehr heiß ist.*

** Slow Cooker Cheesy Creamed Greens
:PROPERTIES:
:ORIGINAL: https://www.bbcgoodfood.com/recipes/slow-cooker-cheesy-creamed-greens
:END:

*** Zutaten
- 50g Butter
- ½ EL Olivenöl
- 1 Zwiebel, dünn geschnitten
- 400g Schwarzkohl (Cavolo Nero)
- 3 Lauchstangen, in Scheiben geschnitten
- 100ml Brühe
- 400ml Sahne
- 1 gehäufter TL Dijon-Senf
- Großzügige Prise Muskatnuss
- 40g geriebener Parmesan oder vegetarische Alternative

*** Anweisungen zum Kochen
1. Den Slow Cooker auf niedrige Stufe erhitzen. Die Butter und das Öl in einer Bratpfanne erhitzen. Die Zwiebel hinzufügen und 5 Minuten bei niedriger Hitze anbraten, bis sie weich und durchsichtig ist. Den Schwarzkohl in die Pfanne geben und 5 Minuten anbraten oder bis er beginnt, zu welken. In den Slow Cooker geben, zusammen mit dem Lauch, der Brühe und 300ml der Sahne. Mit geschlossenem Deckel 3 Stunden kochen lassen, gelegentlich umrühren.
2. Kurz vor dem Servieren die restliche Sahne, den Senf, die Muskatnuss und den Käse sowie etwas Gewürze unterrühren. *Hält sich abgedeckt im Kühlschrank bis zu drei Tage.* Im Slow Cooker bei mittlerer Hitze 45 Minuten bis 1 Stunde aufwärmen.

** Slow-Cooked Summer Blush
:PROPERTIES:
:ORIGINAL: https://www.bbcgoodfood.com/recipes/slow-cooked-summer-blush
:END:

*** Zutaten
- 15 rote Paprika, geviertelt und entkernt
- 15 reife Pflaumentomaten, geviertelt
- 2 Knoblauchköpfe, in einzelne ungeschälte Zehen zerteilt
- 6 EL natives Olivenöl extra
- 1 EL feiner Streuzucker
- 3 EL Rotweinessig
- Eine Handvoll Thymianzweige
- 3 Handvoll Basilikumblätter, grob zerrissen

*** Anweisungen zum Kochen
1. Den Ofen auf 160°C/Umluft 140°C/Gasstufe 3 vorheizen. In einer großen, tiefen Bratform alles außer dem Basilikum vorsichtig vermischen, dann würzen.
2. Das Gemüse in den Ofen stellen und 2 Stunden ungestört rösten. Aus dem Ofen nehmen und abkühlen lassen. Wenn gewünscht, das Gemüse vor dem Servieren abtropfen lassen und den Saft separat servieren, oder einfach das Basilikum unterrühren und die Würze korrigieren.
3. Das Gemüse kann bis zu 2 Tage im Voraus geröstet werden. Abdecken und im Kühlschrank aufbewahren, aber mindestens 4 Stunden vor dem Servieren herausnehmen, damit das Gemüse bei Zimmertemperatur serviert wird.

** Slow-Cooked Tomatoes with Basil
:PROPERTIES:
:ORIGINAL: https://www.bbcgoodfood.com/recipes/slow-cooked-tomatoes-basil
:END:

*** Zutaten
- 3kg kleine Tomaten vom Strauch, halbiert
- 4 TL Kräuter der Provence
- Großes Bund Basilikum, nur die Blätter
- 500ml leichtes Olivenöl, plus extra zum Beträufeln
- 2 TL schwarze Pfefferkörner

*** Anweisungen zum Kochen
1. Den Ofen auf 140°C/Umluft 120°C/Gasstufe 1 vorheizen. Die Tomatenhälften auf 2 große Backbleche verteilen, mit der Schnittseite nach oben. Mit Salz und Pfeffer würzen, mit den Kräutern der Provence bestreuen und mit etwas Olivenöl beträufeln. Im Ofen etwa 3-4 Stunden rösten oder bis sie halbgetrocknet und intensiv rot sind. Sie sollten in der Mitte trocken sein und eine kaubare Textur haben - die beste Art zu testen ist, eine zu probieren. Für die letzte Stunde des Garens ein kleines Basilikumblatt oder ein Stück zerrissenes Basilikum auf jede Tomatenhälfte legen.
2. Das Öl und die Pfefferkörner in einem Topf erhitzen. In Gläser oder hitzebeständige Behälter füllen (wie zuvor) und mit dem Öl bedecken. Im Kühlschrank bis zu 1 Woche aufbewahren.

** Slow-Cooked Tomatoes
:PROPERTIES:
:ORIGINAL: https://www.bbcgoodfood.com/recipes/slow-cooked-tomatoes
:END:

*** Anweisungen zum Kochen
1. Kann bis zu 2 Tage im Voraus zubereitet werden. Den Ofen auf 120°C/Umluft 100°C/Gasstufe ½ vorheizen. Die Tomaten in der Breite halbieren und mit der Schnittseite nach oben in eine Bratform legen. Die Knoblauchzehen schälen und sehr dünn in Scheiben schneiden. Auf jede Tomate eine Scheibe legen, würzen und Thymian- oder Rosmarinblätter darüber streuen. Jede Tomate mit Sherryessig, dann mit Balsamico-Essig und schließlich mit Olivenöl beträufeln. 2-3 Stunden backen, bis die Tomaten weich und leicht geschrumpft sind. Herausnehmen und abkühlen lassen.

** Slow-Cooked Vine Tomatoes with Garlic
:PROPERTIES:
:ORIGINAL: https://www.bbcgoodfood.com/recipes/slow-cooked-vine-tomatoes-with-garlic
:END:

*** Zutaten
- 300g Kirschtomaten am Strauch
- 1 oder 2 kleine Knoblauchknollen, halbiert, um das Fleisch freizulegen
- 150ml Olivenöl
- Knuspriges Brot zum Servieren (optional)

*** Anweisungen zum Kochen
1. Den Ofen auf 150°C/130°C Umluft/Gasstufe 2 vorheizen. Die Tomaten und den Knoblauch in eine Auflaufform geben, die eng anliegt. Gut würzen. Das Olivenöl darüber gießen und mit Folie abdecken. 1¼ Stunden backen, dann den Knoblauch zerdrücken und in das Öl rühren. Warm mit knusprigem Brot servieren. *Hält sich in einem luftdichten Behälter im Kühlschrank bis zu zwei Wochen. Vorher abkühlen lassen.*

**** Tipps
Die Tomaten durch heiße Pasta mischen für eine schnelle Sauce oder als Pizzabelag verwenden.

* Frühstück und Grundnahrungsmittel                                                      :breakfast:
** Slow Cooker Bread
:PROPERTIES:
:ORIGINAL: https://www.bbcgoodfood.com/recipes/slow-cooker-bread
:END:

*** Zutaten
- Mehl
- Hefe
- Salz
- 350ml warmes Wasser

*** Anweisungen zum Kochen
1. Mehl, Hefe und Salz in einer großen Schüssel mischen und in der Mitte eine Mulde bilden. 350ml warmes Wasser abmessen und den größten Teil davon in die Mulde gießen. Mehl und Wasser mit den Fingern oder einem Holzlöffel zu einem leicht feuchten, weichen, gut verarbeitbaren Teig verrühren – bei Bedarf noch etwas mehr Wasser hinzufügen.
2. Den Teig auf eine leicht bemehlte Fläche geben und mindestens 10 Minuten kneten, bis er glatt und elastisch ist. Dies kann auch in einer Küchenmaschine mit einem Knethaken erledigt werden.
3. Den Teig zu einer großen, festen Kugel formen und auf ein Stück Backpapier setzen. Das Backpapier verwenden, um den Teig in den Slow Cooker zu heben, abdecken und den Slow Cooker auf hohe Stufe stellen. 2 Stunden stehen lassen.
4. Das Brot mit Hilfe des Backpapiers herausheben. Der Boden sollte knusprig und die Oberseite elastisch, nicht weich sein. (Wenn Sie ein digitales Thermometer haben, sollte die Mitte des Brotes 90°C haben.) Wenn es noch nicht fertig ist, für weitere 15 Minuten in den Slow Cooker zurückgeben und erneut testen – es kann bis zu 2 Stunden 30 Minuten dauern.
5. Das Brot bekommt im Slow Cooker keine signifikante Kruste oder goldene Farbe. Sobald es gegart ist, können Sie es abkühlen lassen oder für 5-10 Minuten bei 240°C/220°C Umluft/Gasstufe 9 in den Ofen stellen, um etwas Farbe zu bekommen.

** Slow Cooker Bio Yogurt
:PROPERTIES:
:ORIGINAL: https://www.bbcgoodfood.com/recipes/slow-cooker-bio-yogurt
:END:

*** Zutaten
- 2l Vollmilch
- 100ml lebendiger Joghurt (entweder gekauft oder aus einer vorherigen selbstgemachten Charge)

*** Anweisungen zum Kochen
1. Die Milch in den Slow Cooker geben. Abdecken und auf hoher Stufe erhitzen, bis die Temperatur der Milch 82°C erreicht, dies dauert ein paar Stunden. Den Slow Cooker ausschalten und die Temperatur für weitere 2-3 Stunden auf 43°C sinken lassen. Eine Tasse der warmen Milch nehmen und mit dem Joghurt mischen, dann die Mischung zurück in den Slow Cooker gießen und gut umrühren. Abdecken, den Slow Cooker in ein großes Handtuch wickeln und dann 9-12 Stunden ungestört stehen lassen, bis die Mischung fest geworden ist.
2. Essen Sie ihn auf Müsli oder Porridge, garniert mit frischem Obst, in Marinaden oder trinken Sie ihn in Smoothies. Wenn Sie ihn dicker haben möchten, z.B. für Dips, legen Sie ein großes Sieb mit Musselin aus und stellen Sie es über eine Schüssel, geben Sie den Joghurt hinein und lassen Sie etwas von der Molke abtropfen, bis Sie die gewünschte Konsistenz des Joghurts erreicht haben. Je länger Sie ihn stehen lassen, desto dicker wird er. Im Kühlschrank bis zu 2 Wochen aufbewahren.

** Slow Cooker Turkish Breakfast Eggs
:PROPERTIES:
:ORIGINAL: https://www.bbcgoodfood.com/recipes/slow-cooker-baked-turkish-breakfast-eggs
:END:

*** Zutaten
- 1 EL Olivenöl
- 2 Zwiebeln, fein geschnitten
- 1 rote Paprika, entkernt und fein geschnitten
- 1 kleine rote Chilischote, fein geschnitten
- 8 Kirschtomaten
- 1 Scheibe Sauerteigbrot, gewürfelt
- 4 Eier
- 2 EL Magermilch
- Ein kleines Bund Petersilie, fein gehackt
- 4 EL Naturjoghurt zum Servieren

*** Anweisungen zum Kochen
1. Das Innere eines kleinen Slow Cookers einölen und bei Bedarf vorheizen. Das restliche Öl in einer schweren Bratpfanne erhitzen. Die Zwiebeln, Paprika und Chili unterrühren. Kochen, bis sie beginnen, weich zu werden. In den Slow Cooker geben und die Kirschtomaten und das Brot hinzufügen und alles umrühren. Würzen.
2. Die Eier mit der Milch und der Petersilie verquirlen und über den Inhalt des Slow Cookers gießen, wobei darauf zu achten ist, dass alle anderen Zutaten bedeckt sind. 5-6 Stunden kochen lassen. Mit dem Joghurt servieren.

** Slow-Cooked Porridge
:PROPERTIES:
:ORIGINAL: https://www.bbcgoodfood.com/recipes/slow-cooked-porridge
:END:

*** Zutaten
- 1 Tasse Jumbo-Haferflocken
- 4 Tassen Milch (oder halb Milch, halb Wasser für eine weniger cremige Version), plus etwas mehr Milch zum Servieren
- ¼ Tasse getrocknete Früchte (optional)

**** Zum Servieren
- Ihre Lieblingsbeläge - brauner Zucker oder Honig, Bananenscheiben, geriebener Apfel, Blaubeeren, eine Prise Zimt, Naturjoghurt usw.

*** Anweisungen zum Kochen
1. Den Slow Cooker bei Bedarf vorheizen. Eine stabile Keramikschüssel finden, die in den Kocher passt. Die Haferflocken mit einer Prise Salz in die Schüssel geben, dann die Milch oder eine Mischung aus Milch und Wasser darüber gießen. Die getrockneten Früchte hinzufügen, falls verwendet. Die Schüssel in den Slow Cooker stellen, auf die niedrigste Stufe stellen und über Nacht 7-8 Stunden kochen lassen. Wenn jemand in der Nacht wach ist, den Brei kurz umrühren, um die knusprigeren Teile von den Rändern und dem Boden abzukratzen, aber keine Sorge, wenn nicht.
2. Am Morgen den Brei wirklich gut umrühren - es kann sich eine Kruste auf der Oberseite gebildet haben, aber einfach einrühren, um sie aufzubrechen. Einen Tropfen mehr Milch hinzufügen, um ihn gegebenenfalls zu lockern, dann in Schüsseln füllen und Ihre Lieblingsbeläge hinzufügen.

** Slow Cooker Spiced Apples with Barley
:PROPERTIES:
:ORIGINAL: https://www.bbcgoodfood.com/recipes/spiced-apples-barley
:END:

*** Zutaten
- ½ Tasse Gerste
- 2 Tafeläpfel
- ½ TL Zimt
- Eine Prise frische Muskatnuss
- Fein geriebene Schale einer großen Orange
- 4 EL Naturjoghurt

*** Anweisungen zum Kochen
1. Den Slow Cooker bei Bedarf vorheizen. Die Gerste und 750ml kochendes Wasser in den Slow Cooker geben. Die Äpfel schälen und entkernen, so dass in jedem ein Loch in der Größe einer Ein-Pfund-Münze entsteht. Jeden Apfel halbieren.
2. Die Äpfel mit der Hautseite nach unten auf die Gerste stellen. Zimt, Muskatnuss und Orangenschale mischen und über die Äpfel streuen.
3. 2 Stunden auf niedriger Stufe kochen. Mit Naturjoghurt servieren.

* Süße Leckereien und Desserts
** Slow Cooker Sticky Toffee Pudding
:PROPERTIES:
:ORIGINAL: https://www.bbcgoodfood.com/recipes/slow-cooker-sticky-toffee-pudding
:END:

*** Zutaten
- Datteln
- 150ml kochendes Wasser
- Butter
- Zuckerrübensirup (Treacle)
- Vanille
- Zucker
- Sahne
- Eier
- Mehl
- Natron (Bicarb)
- Salz
- Eiscreme zum Servieren

*** Anweisungen zum Kochen
1. Die Datteln in eine hitzebeständige Schüssel geben, mit 150ml kochendem Wasser übergießen und 30 Minuten einweichen lassen. Eine 1-Liter-Puddingform mit Butter einfetten und den Boden mit Backpapier auslegen.
2. Die Hälfte der Butter, die Hälfte des Zuckerrübensirups, die Vanille, 75g Zucker und die Sahne in einen Topf bei mittlerer Hitze geben. 4-5 Minuten unter Rühren kochen, bis sich der Zucker auflöst. Die Hitze erhöhen, 3 Minuten köcheln lassen und dann eine Prise Salz unterrühren. Ein Drittel der Sauce in die Form gießen.
3. Die restliche Butter, den Zuckerrübensirup, den Zucker und die Eier zusammen schlagen, dann das Mehl, das Natron, ¼ TL Salz, die Datteln und deren Einweichflüssigkeit unterheben. In die Form füllen und die Oberfläche glätten, wobei ein 1 cm großer Abstand zum Rand bleiben sollte. Mit einer doppelten Lage Backpapier und Folie abdecken, in der Mitte eine Falte machen, damit der Pudding aufgehen kann. Mit Küchengarn sichern.
4. Den Slow Cooker auf niedrige Stufe stellen. Die Form hineinstellen und kochendes Wasser einfüllen, so dass es bis zur Hälfte der Form reicht. Abdecken und 7-8 Stunden kochen. Mit einem Messer um den Rand des Puddings fahren und auf einen Teller stürzen. Die restliche Sauce wieder erhitzen und darüber gießen. Mit Eiscreme servieren.

** Slow Cooker Banana Bread
:PROPERTIES:
:ORIGINAL: https://www.bbcgoodfood.com/recipes/slow-cooker-banana-bread
:END:

*** Anweisungen zum Kochen
1. Den Boden und 5 cm der Seite Ihres Slow Cookers mit Folie auskleiden, um eine Art Kuchenform zu schaffen, dann die Folie mit Backpapier auslegen. Die Bananen in einer Schüssel zerdrücken, bis sie zerkleinert sind, dann beiseite stellen.
2. Die Butter und beide Zuckerarten zusammen schlagen, bis sie hell und cremig sind, etwa 5 Minuten. 1 Ei mit einem Löffel Mehl einschlagen, bis es vermischt ist. Wiederholen, bis alle Eier eingearbeitet sind.
3. Das restliche Mehl und Backpulver unterheben, gefolgt von der zerdrückten Banane. In den Slow Cooker geben, den Deckel aufsetzen und 4 Stunden auf hoher Stufe kochen. Den Deckel mindestens 3 Stunden 30 Minuten nicht abnehmen, dann prüfen, ob der Kuchen fertig ist. Ein in die Mitte gesteckter Spieß sollte sauber herauskommen. Wenn nicht, den Deckel wieder aufsetzen und weitere 15 Minuten kochen, dann erneut prüfen. Auf ein Brett stürzen und vor dem Servieren abkühlen lassen, mit etwas Butter oder einfach so.

** Slow Cooker Fudge
:PROPERTIES:
:ORIGINAL: https://www.bbcgoodfood.com/recipes/slow-cooker-fudge
:END:

*** Zutaten
- 375g Dose Kondensmilch
- 250g Milchschokolade, gehackt
- 250g Zartbitterschokolade, gehackt
- 100g hellbrauner weicher Zucker
- 1 TL Vanilleextrakt
- Pflanzenöl für die Form

*** Anweisungen zum Kochen
1. Den Slow Cooker auf niedrige Stufe stellen (wir haben einen 6-Liter-Cooker verwendet). Die Kondensmilch, beide Schokoladen, den Zucker, die Vanille und eine Prise Salz hineingeben. 1 Stunde kochen lassen, alle 15 Minuten mit einem Spatel gut umrühren, um zu mischen und alle Teile abzukratzen, die am Topf kleben bleiben, bis die Masse dick und glatt ist. Eine 20 cm große quadratische Form einölen, dann mit Backpapier auslegen. Die Fudge-Mischung in die Form gießen und 4 Stunden kühlen lassen.
2. Das Fudge mit einem scharfen Messer in 36 Quadrate schneiden. *Hält sich in einem luft

** Slow Cooker Clotted Cream Fudge
:PROPERTIES:
:ORIGINAL: https://www.bbcgoodfood.com/recipes/slow-cooker-clotted-cream-fudge
:END:

*** Anweisungen zum Kochen
1. Streuzucker, goldenen Sirup, Clotted Cream, Vanille und eine Prise Meersalzflocken in einen Slow Cooker geben. Rühren, bis alles gut vermischt und glatt ist. 4-5 Stunden auf hoher Stufe kochen, alle 30 Minuten umrühren, oder bis es eine goldene Karamellfarbe hat und glänzend aussieht. Wenn Ihr Slow Cooker mit abgenommenem Deckel funktioniert, unbedeckt kochen, um den Kochvorgang zu beschleunigen. Es dauert etwa 5 Stunden, wenn Sie einen Multifunktionskocher mit einem verschlossenen Deckel verwenden, den Sie immer wieder öffnen und umrühren müssen.
2. Eine 20 cm Backform einölen und mit Backpapier auslegen. Die Schüssel des Slow Cookers vorsichtig abnehmen und auf eine hitzebeständige Matte oder ein Schneidebrett stellen. Mit einem Holzlöffel oder Spatel 10-15 Minuten kräftig mischen, um das Fudge abzukühlen und große Zuckerkristalle zu zerbrechen. Das Fudge wird beim Abkühlen dicker und beginnt, matt auszusehen. In die Form geben und mit einem Spatel die Oberfläche glätten. Mit etwas mehr Salz bestreuen und kühlen, bis es fest ist, etwa 1 Stunde. In Stücke schneiden. *Hält sich fünf Tage in einem luftdichten Behälter*.

** Slow Cooker Hot Chocolate Fondant Cake
:PROPERTIES:
:ORIGINAL: https://www.bbcgoodfood.com/recipes/slow-cooker-hot-chocolate-fondant-cake
:END:

*** Zutaten
- 100g Butter, plus extra für den Slow Cooker
- 100g goldener Streuzucker
- 50g hellbrauner weicher Zucker
- 3 Eier
- 250g Selbstrührendes Mehl
- 50g Kakaopulver
- 1 TL Backpulver
- ½ TL Instant-Espressopulver
- 100g Zartbitterschokolade, gehackt (oder Zartbitterschokoladenstückchen)
- 100-150ml Milch
- Crème fraîche, geschlagene Sahne oder Vanilleeis zum Servieren

**** Für die Sauce
- 200g hellbrauner weicher Zucker
- 25g Kakaopulver
- ½ TL Instant-Espressopulver
- ½ TL Vanilleextrakt

*** Anweisungen zum Kochen
1. Den Boden und die Seiten der Schüssel eines Slow Cookers buttern. Die Butter und beide Zuckerarten in einer Küchenmaschine mit dem Schneebesen-Aufsatz oder mit einem elektrischen Schneebesen schlagen, bis sie hell und flaumig sind. Die Eier einzeln hinzufügen, dann das Mehl, Kakaopulver, Backpulver, Espresso, eine Prise Salz und die Schokolade unterheben. Gerade genug Milch hinzufügen, so dass der Teig in großen Klumpen vom Spatel fällt. In den vorbereiteten Slow Cooker geben.
2. Die Sauce-Zutaten in einer hitzebeständigen Schüssel mit 300ml kochendem Wasser mischen, dann vorsichtig über den Teig im Slow Cooker gießen. Abdecken und 5-6 Stunden auf niedriger Stufe oder 3 Stunden auf hoher Stufe kochen, bis der Kuchen beim Drücken zurückfedert und gut aufgegangen ist. Mit Crème fraîche, geschlagener Sahne oder Vanilleeis servieren.

** Slow Cooker Christmas Cake
:PROPERTIES:
:ORIGINAL: https://www.bbcgoodfood.com/recipes/slow-cooker-christmas-cake
:END:

*** Anweisungen zum Kochen
1. Eine 20 cm tiefe, runde Kuchenform buttern und mit zwei Lagen Backpapier auslegen. Den Slow Cooker 30 Minuten lang auf hoher Stufe vorheizen. In der Zwischenzeit in einer großen Schüssel die Butter, den Zucker, den goldenen Sirup und die Eier vermischen, dann die restlichen Zutaten unterheben, gefolgt von den eingeweichten getrockneten Früchten und jeglicher Flüssigkeit.
2. 9 Std. 30 Min. - 10 Std. auf niedriger Stufe kochen, bis ein in den Kuchen gesteckter Spieß sauber herauskommt. Die Temperaturen von Slow Cookern können variieren, überprüfen Sie den Kuchen daher nach 5 Stunden und achten Sie darauf, den Deckel nicht zu lange abzunehmen. Die Innentemperatur sollte etwa 92°C betragen. Vollständig in der Form abkühlen lassen. *Hält sich bis zu zwei Monate in einer verschlossenen Kuchendose*.

** Slow Cooker Rice Pudding
:PROPERTIES:
:ORIGINAL: https://www.bbcgoodfood.com/recipes/slow-cooker-rice-pudding
:END:

*** Zutaten
- 1 TL Butter
- 1l fettarme Milch
- 200g Vollkornreis
- Muskatnuss oder Zimt
- 1 EL Honig
- Eine Handvoll geröstete, gehobelte Mandeln und Obst zum Servieren

*** Anweisungen zum Kochen
1. Den Slow Cooker überall am Boden und zur Hälfte an den Seiten buttern. Die Milch zum Siedepunkt erhitzen. Den Puddingreis mit der Milch mischen und in den Slow Cooker gießen. Eine Prise Muskatnuss oder Zimt hinzufügen. 2½ Stunden auf hoher Stufe kochen und ein- oder zweimal umrühren, wenn möglich.
2. Mit Honig oder gehobelten Mandeln und Obst servieren, wenn Sie möchten.

** Slow Cooker Self Saucing Pud
:PROPERTIES:
:ORIGINAL: https://www.bbcgoodfood.com/recipes/slow-cooker-self-saucing-pud
:END:

*** Anweisungen zum Kochen
1. Den Slow Cooker 20 Minuten lang auf hoher Stufe vorheizen. Das Innere Ihres Slow Cookers vorsichtig mit Butter einreiben. Den Teig herstellen, indem Sie die geschmolzene Butter mit beiden Zuckerarten, den Eiern und der Milch vermischen, dann das Mehl, Backpulver, Ingwer und Zimt unterheben. Bei Bedarf schlagen, um alle Klumpen zu entfernen, dann in Ihren Slow Cooker gießen.
2. Für die Sauce die Speisestärke mit 1 TL Wasser mischen, dann beiseite stellen. Zucker und Ingwer mit 350 ml kochendem Wasser vermischen, bis sich der Zucker aufgelöst hat. Die Speisestärke-Paste einrühren, dann über den Teig gießen.
3. 1 Std. 30 Min. - 2 Std. 30 Min. auf hoher Stufe kochen (dies variiert je nach Ihrem Slow Cooker), bis der Teig fest geworden ist und sich fest anfühlt. Zum Servieren nach Belieben etwas Sahne darüber gießen.

* Hauptgerichte
** Slow Cooker Vegetable Lasagne
:PROPERTIES:
:ORIGINAL: https://www.bbcgoodfood.com/recipes/slow-cooker-vegetable-lasagne
:END:

*** Zutaten
- 1 EL Rapsöl
- 2 Zwiebeln, in Scheiben geschnitten
- 2 große Knoblauchzehen, gehackt
- 2 große Zucchini, gewürfelt
- 1 rote und 1 gelbe Paprika, grob geschnitten
- 400g gehackte Tomaten
- 2 EL Tomatenmark
- 2 TL Gemüsebrühe
- 15g gehacktes Basilikum
- 1 große Aubergine
- 6 Lasagneblätter
- 125g vegetarischer Büffelmozzarella
- Etwas Basilikum zum Garnieren
- Eine Handvoll Rucola zum Servieren

*** Anweisungen zum Kochen
1. 1 EL Rapsöl in einer großen Antihaftpfanne erhitzen und 2 in Scheiben geschnittene Zwiebeln und 2 gehackte große Knoblauchzehen 5 Minuten unter häufigem Rühren anbraten, bis sie weich sind.
2. 2 gewürfelte große Zucchini, 1 rote und 1 gelbe Paprika (grob geschnitten) sowie 400g gehackte Tomaten mit 2 EL Tomatenmark, 2 TL Gemüsebrühe und 15g gehacktem Basilikum dazugeben.
3. Gut umrühren, abdecken und 5 Minuten kochen. Nicht in Versuchung kommen, mehr Flüssigkeit hinzuzufügen, da aus dem Gemüse beim Kochen viel Feuchtigkeit austritt.
4. 1 große Aubergine in Scheiben schneiden. Die Hälfte der Auberginenscheiben auf den Boden des Slow Cookers legen und mit 3 Lasagneblättern bedecken.
5. Ein Drittel der Ratatouille-Mischung darauf verteilen, dann die restlichen Auberginenscheiben, weitere 3 Lasagneblätter und schließlich die restliche Ratatouille-Mischung.
6. Abdecken und auf hoher Stufe 2½ - 3 Stunden kochen lassen, bis die Nudeln und das Gemüse weich sind. Das Gerät ausschalten.
7. 125g vegetarischen Büffelmozzarella über dem Gemüse verteilen, dann abdecken und 10 Minuten ruhen lassen, damit der Käse schmelzen kann.
8. Mit zusätzlichem Basilikum bestreuen und mit einer Handvoll Rucola servieren.

** Slow Cooker Vegetable Curry
:PROPERTIES:
:ORIGINAL: https://www.bbcgoodfood.com/recipes/slow-cooker-vegetable-curry
:END:

*** Zutaten
- 400ml Dose leichte Kokosmilch
- 3 EL mildes Currypaste
- 2 TL Gemüsebrühepulver
- 1 rote Chili, entkernt und in Scheiben geschnitten
- 1 EL fein gehackter Ingwer
- 3 Knoblauchzehen, in Scheiben geschnitten
- 200g Butternusskürbis (geschältes Gewicht), in Stücke geschnitten
- 1 rote Paprika, entkernt und in Scheiben geschnitten
- 1 kleine Aubergine (etwa 250g), halbiert und in dicke Scheiben geschnitten
- 15g Koriander, gehackt
- 160g aufgetaute TK-Erbsen
- 1 Limette, Saft nach Geschmack
- Vollkorn-Fladenbrot zum Servieren

*** Anweisungen zum Kochen
1. Kokosmilch, Currypaste, Brühepulver, Chili, Ingwer, Knoblauch, Butternusskürbis, Paprika und Aubergine in den Slow Cooker geben und gut umrühren. Mit dem Deckel abdecken und über Nacht kühlen.
2. 6 Stunden auf niedriger Stufe kochen, bis das Gemüse sehr weich ist, dann den Koriander und die aufgetauten Erbsen unterrühren. Die Hitze des Currys sollte ausreichen, um sie zu erwärmen. Abschmecken und nach Belieben einen guten Spritzer Limettensaft hinzufügen. Mit einem Vollkorn-Fladenbrot servieren.

**** Tipp
Sie können den Kürbis durch Süßkartoffeln ersetzen, wenn Sie möchten – sie zählen immer noch als eine Ihrer fünf Portionen am Tag, im Gegensatz zu weißen Kartoffeln.

** Slow Cooker Ratatouille
:PROPERTIES:
:ORIGINAL: https://www.bbcgoodfood.com/recipes/slow-cooker-ratatouille
:END:

*** Zutaten
- 2 EL Olivenöl
- 1 rote Zwiebel, in Scheiben geschnitten
- 2 Knoblauchzehen
- 2 große Auberginen, in 1,5 cm große Stücke geschnitten
- 3 Zucchini, halbiert und in 2 cm große Stücke geschnitten
- 3 gemischte Paprika, in 2 cm große Stücke geschnitten
- 1 EL Tomatenmark
- 6 große reife Tomaten, grob gehackt
- Ein kleines Bund Basilikum, grob gehackt, plus ein paar zusätzliche Blätter zum Servieren
- Einige Thymianzweige
- 400g Dose Dosentomaten
- 1 EL Rotweinessig
- 1 TL brauner Zucker
- Sauerteigbrot zum Servieren (optional)

*** Anweisungen zum Kochen
1. Das Öl in einer großen Bratpfanne erhitzen und die Zwiebel 8 Minuten anbraten, bis sie durchsichtig ist. Knoblauch hinzufügen und 1 Minute anbraten. Die Hitze auf mittelhoch stellen, die Auberginen hinzufügen und 5 Minuten anbraten, bis sie golden sind. Zucchini und Paprika unterrühren und weitere 5 Minuten anbraten, bis sie etwas weich sind. Tomatenmark, frische Tomaten, Kräuter, Dosentomaten, Essig, Zucker und 1 TL Salz hinzufügen und zum Kochen bringen.
2. In den Slow Cooker geben und 5-6 Stunden auf niedriger Stufe kochen lassen, bis alles weich ist und die Sauce eingedickt ist. Würzen, etwas zusätzliches Basilikum darüber streuen und nach Belieben mit Sauerteigbrot servieren.

**** Tipp
Restliche Ratatouille wieder aufwärmen und etwas braunen Zucker und Rotweinessig hinzufügen, um einen süß-sauren Geschmack zu erhalten. Abkühlen lassen, dann grob hacken und als Relish für Sandwiches verwenden oder zu gegrilltem Fleisch oder Fisch servieren. Hält sich im Kühlschrank bis zu fünf Tage.

** Slow Cooker Vegetable Stew with Cheddar Dumplings
:PROPERTIES:
:ORIGINAL: https://www.bbcgoodfood.com/recipes/spring-veg-stew-cheddar-dumplings
:END:

*** Zutaten
- 2 EL Olivenöl
- 200g Babykarotten, gewaschen, gestutzt und halbiert, wenn sie groß sind
- 3 Lauchstangen, in dicke Scheiben geschnitten
- 3 Knoblauchzehen, zerdrückt
- 3 EL Mehl
- 400ml Gemüsebrühe
- 2 Zucchini, in große Stücke geschnitten
- 2 x 400g Dosen Butter- oder Cannellini-Bohnen, abgetropft und abgespült
- 1 Lorbeerblatt
- 4 Thymian-, Rosmarin- oder Estragonzweige
- 200ml Crème fraîche
- 1 EL körniger Senf
- 200g Dicke Bohnen oder Erbsen
- 200g Spinat
- ½ kleines Bund Petersilie, fein gehackt, plus extra zum Servieren

**** Für die Klöße
- 100g Selbstrührendes Mehl
- 50g vegetarischer Rindernierentalg oder kalte Butter, gerieben
- 100g gereifter Cheddar
- ½ kleines Bund Petersilie, fein gehackt

*** Anweisungen zum Kochen
1. Den Slow Cooker auf niedrige Stufe stellen. 1 EL Öl in einer Bratpfanne erhitzen und die Karotten 5 Minuten anbraten, bis sie gerade goldbraun sind, dann in den Slow Cooker geben.
2. Das restliche Öl in der Pfanne erhitzen und die Lauchstangen mit einer Prise Salz 5 Minuten anbraten, bis sie weich sind. Den Knoblauch hinzufügen und das Mehl unterrühren. Nach und nach die Brühe unter Rühren hinzufügen, bis sich das Mehl aufgelöst hat und keine Klumpen mehr vorhanden sind. Zum Kochen bringen, dann in den Slow Cooker geben. Die Zucchini, Bohnen und Kräuter hinzufügen und bei Bedarf mit Wasser auffüllen, um das Gemüse zu bedecken. Abdecken und 4 Stunden kochen lassen.
3. Für die Klöße das Mehl in eine Schüssel geben und den Rindernierentalg oder die Butter einrühren, bis sie gleichmäßig verteilt sind. Den Käse, die Petersilie, ½ TL schwarzen Pfeffer und eine Prise Salz hinzufügen. Mit den Händen 3-4 EL kaltes Wasser einarbeiten, um einen weichen, leicht klebrigen Teig zu erhalten (bei Bedarf etwas mehr Wasser hinzufügen). In sechs Teile teilen und zu Kugeln rollen.
4. Die Crème fraîche, den Senf, die dicken Bohnen oder Erbsen und den Spinat in den Slow Cooker geben und auf hohe Stufe stellen. Die Klöße über dem Eintopf anordnen, abdecken und weitere 1-2 Stunden kochen lassen, bis sie fest sind und sich in der Größe verdoppelt haben. Mit Petersilie bestreuen und servieren. *Hält sich bis zu drei Tage im Kühlschrank oder bis zu drei Monate im Gefrierschrank.*

**** Tipps
Achten Sie darauf, dass das Gemüse in Stücke und nicht in kleine Teile geschnitten wird, damit es nicht matschig wird.

Dieses Rezept lässt sich leicht halbieren für kleine Slow Cooker.

** Slow Cooker Chickpea Stew
:PROPERTIES:
:ORIGINAL: https://www.bbcgoodfood.com/recipes/slow-cooker-chickpea-stew
:END:

*** Zutaten
- 1 EL Pflanzen- oder Sonnenblumenöl
- 1 rote Zwiebel, in Scheiben geschnitten
- 2 Knoblauchzehen, zerdrückt oder fein gerieben
- 1 Butternusskürbis (ca. 600g), entkernt und in mundgerechte Stücke geschnitten
- ½ TL gemahlener Ingwer
- 1 TL gemahlener Kreuzkümmel
- 1 TL geräuchertes Paprikapulver
- 1 TL gemahlener Koriander
- 1 TL gemahlenes Kurkuma
- ½ TL gemahlener Zimt
- 400g Dose Kichererbsen
- 400g Dose gehackte Tomaten
- 2 EL Tomatenmark
- 500ml Gemüsebrühe
- Gekochter Couscous und eine Handvoll gehackter Koriander zum Servieren

*** Anweisungen zum Kochen
1. Das Öl in einer großen Bratpfanne oder einem Topf bei mittlerer bis niedriger Hitze erhitzen und die Zwiebel 10-12 Minuten anbraten, bis sie weich ist und beginnt, golden zu werden. Den Knoblauch unterrühren und 1 Minute kochen, dann den Kürbis hinzufügen und einige Minuten länger kochen, um ihn etwas weich werden zu lassen. Die Gewürze hineinstreuen, umrühren und 2 Minuten kochen, bis sie duften.
2. Alles aus der Pfanne in den Slow Cooker geben, zusammen mit den Kichererbsen und ihrer Flüssigkeit, den Tomaten, dem Tomatenmark und der Brühe. Gut umrühren, dann 5 Stunden auf hoher Stufe oder 7 Stunden auf niedriger Stufe kochen. Mit Couscous servieren und den Koriander darüberstreuen.

** Sweet Potato & Coconut Curry
:PROPERTIES:
:ORIGINAL: https://www.bbcgoodfood.com/recipes/sweet-potato-coconut-curry
:END:

*** Anweisungen zum Kochen
1. 1 EL Olivenöl in einer großen Antihaftpfanne erhitzen und die Zwiebel hinzufügen. 10 Minuten bei schwacher Hitze sanft anbraten, bis sie weich ist, dann den Knoblauch hinzufügen und den Ingwer direkt in die Pfanne reiben. Paprika und Cayennepfeffer unterrühren und eine weitere Minute kochen, dann in den Slow Cooker geben.
2. Die Pfanne wieder erhitzen und noch 1 EL Öl zusammen mit der Chili, der roten Paprika und dem geschredderten Kohl hinzufügen. 4-5 Minuten kochen lassen, dann in den Slow Cooker geben.
3. Das restliche Öl verwenden, um die Süßkartoffeln anzubraten. Je nach Größe Ihrer Pfanne müssen Sie dies möglicherweise in 2 oder 3 Chargen tun. Die Süßkartoffeln etwa 5 Minuten kochen oder bis sie an den Rändern etwas Farbe annehmen, dann ebenfalls in den Slow Cooker geben.
4. Die Passata und die Kokosmilch über die Süßkartoffeln gießen, umrühren, um alles zu vermischen, den Slow Cooker mit einem Deckel abdecken und 6-8 Stunden kochen lassen oder bis die Süßkartoffeln weich sind.
5. Die Erdnussbutter durch das Curry rühren, mit Salz und Pfeffer abschmecken und mit Couscous und gehacktem Koriander darüber servieren.

** Slow-Cooked Marrow with Fennel & Tomato
:PROPERTIES:
:ORIGINAL: https://www.bbcgoodfood.com/recipes/slow-cooked-marrow-fennel-tomato
:END:

*** Anweisungen zum Kochen
1. Den Kürbis halbieren, entkernen und in Stücke schneiden. Mit etwas Salz bestreuen und die Stücke 30 Minuten in einem Sieb abtropfen lassen, um überschüssiges Wasser zu entfernen.
2. Das Olivenöl in einer großen Pfanne bei mittlerer Hitze erhitzen. Rosmarin und Fenchelsamen hinzufügen und einige Minuten kochen, bis der Rosmarin brutzelt. Die rote Zwiebel, getrocknete Chili, Fenchel und eine große Prise Salz hinzufügen und 10 Minuten kochen, bis die Zwiebeln beginnen, Farbe anzunehmen und süßer zu werden.
3. Den Knoblauch hinzufügen und unter Rühren eine weitere Minute kochen. Die Hitze etwas erhöhen, den Kürbis und eine gute Prise Pfeffer hinzufügen und 10 Minuten kochen, dabei umrühren, damit nichts anbrennt.
4. Die Pfanne mit dem Weißwein ablöschen. Kochen, bis er verdunstet ist, dann die Tomaten und den Rotweinessig hinzufügen. Alles vermischen, dann die Hitze reduzieren und gelegentlich umrühren, bei niedrigster Hitze mindestens 35 Minuten kochen, bis die Tomaten konzentriert sind und der Kürbis alle Aromen in der Pfanne aufgenommen hat. Die Kapern und weißen Bohnen unterrühren, um sie zu erwärmen.
5. Das Sauerteigbrot toasten und jede Scheibe halbieren. Die Mischung auf vier Teller verteilen, dann das Brot mit dem Ziegenkäse bestreichen, mit etwas Olivenöl beträufeln, Oregano und Rosmarin darüber streuen und servieren.

** Vegan Chilli (Slow Cooker Methode)
:PROPERTIES:
:ORIGINAL: https://www.bbcgoodfood.com/recipes/vegan-chilli
:END:

*** Anweisungen zum Kochen
1. Das Öl in einer großen Bratpfanne bei mittlerer Hitze erhitzen. Die Zwiebel, Karotte und Sellerie hinzufügen. 8-10 Minuten kochen, gelegentlich umrühren, bis das Gemüse weich ist, dann den Knoblauch hineindrücken, die Süßkartoffelstücke hinzufügen und 1 Minute länger kochen. Alle getrockneten Gewürze, Oregano und Tomatenmark hinzufügen, 1 Minute kochen lassen, dann in einen Slow Cooker geben.
2. Die rote Paprika und die gehackten Tomaten hinzufügen. Alles gut umrühren und dann 5 Stunden auf niedriger Stufe kochen lassen. Die Bohnen unterrühren und weitere 30 Minuten bis 1 Stunde kochen lassen. Abschmecken und mit Limettenspalten, Guacamole, Reis und Koriander servieren.

** Slow Cooker Mac 'n' Cheese
:PROPERTIES:
:ORIGINAL: https://www.bbcgoodfood.com/recipes/slow-cooker-mac-n-cheese
:END:

*** Zutaten
- 350g Makkaroni-Nudeln
- 600ml Vollmilch
- 50g Butter, gewürfelt
- 50g Weichkäse
- 100g gereifter Cheddar, gerieben, plus extra zum Servieren
- 20g Parmesan oder vegetarische Alternative, plus extra zum Servieren

*** Anweisungen zum Kochen
1. Kochendes Wasser über die Nudeln gießen und abgießen, dann alles in einen Slow Cooker geben und gut umrühren. Würzen, abdecken und 1 Stunde auf niedriger Stufe kochen. Erneut umrühren, den Deckel wieder aufsetzen und weitere 30 Minuten kochen, bis die Nudeln gar sind und die Sauce eingedickt genug ist, um die Makkaroni zu überziehen.
2. Den Deckel für die letzten 10 Minuten abnehmen und weiter einkochen lassen, falls nötig, oder einen Schuss mehr Milch hinzufügen – dies hängt von der Größe Ihres Slow Cookers und der Marke ab. Mit extra Käse servieren.

**** Tipp
Restlichen Mac & Cheese in die Vertiefungen einer Antihaft-Muffinform füllen und dabei etwas Platz lassen. Verquirlte Eier darübergießen, würzen und mit geriebenem Käse bestreuen. Bei 200°C/180°C Umluft/Gasstufe 8 für 20 Minuten backen, bis sie aufgegangen und goldbraun sind.

** Slow Cooker Mushroom Risotto
:PROPERTIES:
:ORIGINAL: https://www.bbcgoodfood.com/recipes/slow-cooker-mushroom-risotto
:END:

*** Zutaten
- 1 Zwiebel, fein gehackt
- 1 TL Olivenöl
- 250g Kastanienpilze, in Scheiben geschnitten
- 1l Gemüsebrühe
- 50g Steinpilze
- 300g Vollkornreis
- Ein kleines Bund Petersilie, fein gehackt
- Geriebener vegetarischer Parmesan-ähnlicher Käse zum Servieren

*** Anweisungen zum Kochen
1. Den Slow Cooker bei Bedarf vorheizen. Die Zwiebel in dem Öl in einer Bratpfanne mit einem Spritzer Wasser 10 Minuten anbraten oder bis sie weich, aber nicht gefärbt ist. Die Pilzscheiben hinzufügen und umrühren, bis sie beginnen, weich zu werden und ihre Säfte freizusetzen.
2. In der Zwischenzeit die Brühe in einen Topf gießen und die Steinpilze hinzufügen, zum Kochen bringen und dann einweichen lassen. Die Zwiebeln und Pilze in den Slow Cooker geben und den Reis hinzufügen, gut unterrühren. Die Brühe und die Steinpilze darüber gießen, wobei alle Sedimente im Topf zurückbleiben sollten (oder die Mischung durch ein feines Sieb gießen).
3. 3 Stunden auf hoher Stufe kochen, nach der Hälfte der Zeit umrühren und dann die Konsistenz prüfen – der Reis sollte gar sein. Wenn er noch etwas mehr Flüssigkeit benötigt, einen Schuss Brühe unterrühren. Die Petersilie unterrühren und würzen. Mit dem Parmesan servieren.

* Suppen und Eintöpfe
** Slow Cooker Broccoli & Cheese Soup
:PROPERTIES:
:ORIGINAL: https://www.bbcgoodfood.com/recipes/slow-cooker-broccoli-cheese-soup
:END:

*** Zutaten
- 1 EL Pflanzen- oder Sonnenblumenöl
- 1 Zwiebel, gehackt
- 2 Knoblauchzehen, zerdrückt oder fein gerieben
- 250g Kartoffeln, grob gehackt
- 1 Brokkoli (ca. 325g), grob gehackt
- 750ml Hühner- oder Gemüsebrühe
- 150g gereifter Cheddar, in Würfel geschnitten
- 125ml Schlagsahne, plus extra zum Servieren
- Getoastetes oder knuspriges Brot zum Servieren

*** Anweisungen zum Kochen
1. Das Öl in einer Bratpfanne bei mittlerer bis niedriger Hitze erhitzen und die Zwiebel 10-12 Minuten anbraten, bis sie weich, aber nicht goldbraun ist. Den Knoblauch unterrühren und 1 Minute anbraten, dann die Kartoffeln unterrühren und einige Minuten kochen, um sie etwas weich werden zu lassen. In Ihren Slow Cooker geben.
2. Den Brokkoli und die Brühe in den Slow Cooker geben und gut mit Salz und frisch gemahlenem schwarzen Pfeffer würzen. 3 Stunden auf hoher Stufe oder 5 Stunden auf niedriger Stufe kochen. Der Brokkoli sollte weich sein, aber der Stiel kann noch etwas Biss haben. Den Käse hinzufügen und rühren, bis er geschmolzen ist, dann die Sahne unterrühren.
3. In einen Mixer geben und pürieren, bis die Suppe glatt ist. Mit einem Klecks Sahne, einer Prise schwarzem Pfeffer und dem Brot zum Eintunken servieren.

**** Tipp
Tauschen Sie den Cheddar gegen Blauschimmelkäse aus, wenn Sie einen kräftigeren Geschmack bevorzugen.

** Slow Cooker Spiced Parsnip Soup
:PROPERTIES:
:ORIGINAL: https://www.bbcgoodfood.com/recipes/slow-cooker-spiced-parsnip-soup
:END:

*** Zutaten
- 750g Pastinaken, geschält und gehackt
- 400g Karotten, gehackt
- 1 Zwiebel, gehackt
- 2 große Knoblauchzehen, zerdrückt oder fein gerieben
- 1-2 EL Currypulver (nach Geschmack)
- 1l Gemüsebrühe

*** Anweisungen zum Kochen
1. Die Pastinaken, Karotten, Zwiebeln, Knoblauch und das Currypulver in einen Slow Cooker geben und gut mischen, so dass das gesamte Gemüse mit dem Currypulver bedeckt ist. Die Gemüsebrühe hinzugießen, dann erneut umrühren und würzen.
2. 8 Stunden auf niedriger Stufe kochen. In einen Mixer geben und pürieren, bis die Suppe glatt ist. Wenn Sie Ihre Suppe etwas flüssiger mögen, können Sie ein paar Spritzer kochendes Wasser aus dem Wasserkocher unterrühren. Auf Schüsseln verteilen und vor dem Servieren mit gemahlenem schwarzem Pfeffer würzen. *Nach dem vollständigen Abkühlen hält sich die Suppe bis zu drei Monate lang eingefroren. Über Nacht vollständig im Kühlschrank auftauen, dann in einem Topf erhitzen, bis sie vor dem Servieren sehr heiß ist.*

** Slow Cooker Pumpkin Soup
:PROPERTIES:
:ORIGINAL: https://www.bbcgoodfood.com/recipes/slow-cooker-pumpkin-soup
:END:

*** Zutaten
- 2 EL Rapsöl
- 3 Zwiebeln (480g), gehackt
- 30g Ingwer, geschält und gehackt
- 3 große Knoblauchzehen, gehackt
- 1½-2 EL mittelscharfes Currypulver
- 1 TL gemahlener Koriander
- ½ TL zerdrückte getrocknete Chilischoten (optional)
- 1kg Kürbis oder Butternusskürbis (nur das Fruchtfleisch), in Würfel geschnitten
- 1 EL Gemüsebrühepulver (bei Bedarf vegan)
- 400g Dose Kokosmilch
- 180g getrocknete rote Linsen
- 15g Koriander, gehackt

*** Anweisungen zum Kochen
1. Das Öl in einer großen Pfanne bei mittlerer Hitze erhitzen und die Zwiebeln und den Ingwer 10 Minuten anbraten, gelegentlich umrühren, bis sie weich sind und anfangen, Farbe anzunehmen. Den Knoblauch, das Currypulver, den gemahlenen Koriander und die getrockneten Chilischoten, falls verwendet, unterrühren und 1 Minute länger kochen.
2. Die Mischung in einen großen Slow Cooker geben, zusammen mit allen übrigen Zutaten, außer dem frischen Koriander. 2 Liter Wasser hinzufügen. 8 Stunden auf hoher Stufe kochen oder über Nacht 15 Stunden auf niedriger Stufe. Gut umrühren, dann mit einem Stabmixer pürieren, bis die Suppe glatt ist. In Schüsseln füllen und zum Servieren den frischen Koriander darüberstreuen. *Nach dem vollständigen Abkühlen hält sich die Suppe in einem luftdichten Behälter 48 Stunden im Kühlschrank oder bis zu zwei Monate eingefroren. In einer Pfanne bei niedriger Hitze oder in der Mikrowelle erhitzen, bis sie sehr heiß ist.*

**** Tipp
Wenn Ihr Kürbis oder Butternusskürbis nicht ganz groß genug ist, um das erforderliche Gewicht zu erreichen, können Sie ihn mit gehackten Karotten ergänzen.

** Slow Cooker Tomato Soup
:PROPERTIES:
:ORIGINAL: https://www.bbcgoodfood.com/recipes/slow-cooker-tomato-soup
:END:

*** Zutaten
- 2 x 400g Dosen gehackte Tomaten
- 1 rote Zwiebel, gehackt
- 1 Karotte, gehackt
- 1 Rosmarinzweig
- 2 EL Tomatenmark
- 1 Gemüsebrühwürfel
- 2 Lorbeerblätter
- 2 EL
