:PROPERTIES:
:ID:       dd69d636-84e3-4239-bbcc-efa6cedafee9
:END:
#+created: 20210928173514935
#+modified: 20210928174015027
#+revision: 0
#+filetags: :Journal:
#+title: 2021-09-28
#+date: 2021-09-28
#+type: text/vnd.tiddlywiki

- [[https://www.fugue.co/blog/2015-11-11-guide-to-emacs.html][A CEO's guid to Emacs]] ([[id:f9f5fffd-d536-45c5-95ee-532d0b756766][Emacs]])
  - why one should use [[id:f9f5fffd-d536-45c5-95ee-532d0b756766][Emacs]] (from a productivity point of view)

  - also see follow-up: [[https://www.fugue.co/blog/2018-08-09-two-years-with-emacs-as-a-cto.html][2 years with Emacs as a CEO]]

    #+begin_quote
    I no longer decide what app to use for this or that thing. Instead, I just work. There is real power and efficiency to having a great tool and committing to it In the modern world of computing, this generally means using several applications, all of which have distracting user interfaces and different ways to store, sort, and search. The result is that you need to constantly switch mental contexts and remember minutiae. I hate context switching because it is an imposition put on me due to a broken interface model2 and I hate having to remember things my computer should remember for me in any rational world For those who haven't used Emacs, it's something you'll likely hate, but may love. It's sort of a Rube Goldberg machine the size of a house that, at first glance, performs all the functions of a toaster Once you grok Emacs, you realize that it's a thermonuclear toaster that can also serve as the engine for... well, just about anything you want to do with text The third reason I find Emacs more advantageous than other environments is that it's easy to take all your stuff with you Assuming that humans have now solved the problem of storage 6 for good, the issue we face over time is whether we can continue to access the information we've created. Text files are the most long-lived format for computing. You easily can open a text file from 1970 in Emacs. That's not so true for Office applications. Text files are also nice and small---radically smaller than Office application data files The best programs provide access to the computer without demanding attention

    #+end_quote

- [[https://www.reuters.com/business/finance/banks-beware-outsiders-are-cracking-code-finance-2021-09-17/][Banks beware, Amazon and Walmart are cracking the code for finance]]
- [[https://www.inputmag.com/features/rise-and-ruin-of-couchsurfing/amp][The rise and ruin of couchsurfing.com]]
