:PROPERTIES:
:ID:       26b141bb-efef-4674-afdf-58ae7aa4f898
:END:
#+created: 20210812063705404
#+modified: 20210812084201812
#+revision: 0
#+filetags: :Journal:
#+title: 2021-08-12
#+date: 2021-08-12
#+type: text/vnd.tiddlywiki

- [[https://daveasprey.com/dr-steven-gundry-803/][How to Identify Your Energy Blockers and Beat Fatigue -- Dr. Steven Gundry with Dave Asprey -- #803]]
  - with Dr. Steven Gundry

    - [[https://www.goodreads.com/en/book/show/53739867-the-energy-paradox][The Energy Paradox: What to Do When Your Get-Up-and-Go Has Got Up and Gone]]

  - talk about fatigue and low energy

    #+begin_quote
    We've produced mitochondrial gridlock which never would have occurred in our grandparents' age when everybody ate whole foods. One of the most common markers of inflammation is called C-reactive protein, and it's abbreviated CRP. I call it crap because if your CRP is elevated, quite frankly you will feel like crap. When you have leaky gut, quite frankly, you have leaky brain, and your brain becomes on high alert [[#Fruktose][Fructose]] is a very funny sugar. It's absorbed directly from our intestines, not into our blood stream, but makes a beeline directly into our liver via the portal vein. And there, it actually stops ATP production. It blunts ADP from turning into ATP.

    #+end_quote

    - that's why no fuctose before a training, because your body already has the right energy levels
    - in case of a training your blood is for your muscles, not for digestion

  - suggests [[id:4ffeeec7-52f7-454b-9785-5fc5a7683e2b][CoQ10]] has some benefits
