:PROPERTIES:
:ID:       85667022-3a65-4ebf-bb8c-03c572d7e11b
:END:
#+created: 20220428081907206
#+modified: 20220502071500135
#+revision: 0
#+filetags: :Journal:
#+title: 2022-04-28
#+date: 2022-04-28
#+type: text/vnd.tiddlywiki

- [[https://changelog.com/podcast/484][Wisdom from 50+ years in software]]
  - Interview with Brian Kerningham

  - talk about birth of [[#Unix][Unix]]

  - how [[id:cdf2a03e-f080-4e6f-8636-7c0f582d91fc][Rust]] or ([[id:b2831721-165d-4943-a41a-da770d96be41][Golang]]) might change the way how we code

  - Brian also has a new [[https://www.goodreads.com/en/book/show/53011383-unix][book]]

    #+begin_quote
    Yeah, the iPad is a nice example of that, in a way. I mean, I have an iPad; I turn it on maybe once every six months or something like that, because it's an utterly useless device, because it only lets me do what Apple thought I wanted to do. And I don't know how to make it do most of the things, because it requires funny artificial "wiggle your fingers while rubbing your elbow with something else" to make something happen, which with a command line interface - and this is the old-fogey speaking - I could type two or three characters and I'd be done. But I don't use it primarily because it's not programmable. It is a totally useless device to me And let me explain that... Because on an iOS device, let's say - and I'm not trying to say that Apple is being malicious with this activity, but the functionality of the device is definitely limiting. You can't program it in itself; you have to leave the device, enter your computer world with the command line, with the Unix underpinnings and the Linux backgrounds and the packages and this whole world of possibilities to make the other thing work.

    #+end_quote
