:PROPERTIES:
:ID:       2774f402-0c83-4e34-86d8-e187ea9c8beb
:END:
#+TITLE: 2022-11-17
#+DATE: 2022-11-17
#+FILETAGS: journal

- 2022-11-17 ◦ [[https://www.infoq.com/podcasts/managing-tech-debt/][Managing Tech Debt with Glenn Engstrand]]
  - [[https://www.youtube.com/watch?v=szPO4cE_O6U&ab_channel=InfoQ][Managing tech debt in a Microservice architecture]] (video, [[id:adce7f16-ab79-4935-b73e-71f3740a071f][Microservices]])
    - TCP
      #+begin_quote
      "Here is the stated purpose of the TCP. It is used by and for engineering to signal intent to both engineering and product, by collecting, organizing, and communicating the ever-changing requirements in the technology landscape for the purposes of architecting for longevity and adaptivity."
      #+end_quote
    - technological risk
      #+begin_quote
      "understanding of the relative risks of not following each part of the plan. This is captured as a numerical risk score. The higher the score, the greater the risk, the more important the priority. Technologies with the use status always have a score of zero. The non-zero risk score can increase for each quarter that a technology has a migrate, deprecate, or remove status. While each plan comes from the bottom up, the risk score comes from the top down. What goes into the plan comes from community participating engineers, and how that list is prioritized comes from executive engineering management."
      #+end_quote
    - metrics for technological risk
      #+begin_quote
      "These metrics are collected into what is known as a balanced scorecard, which is a strategy performance management tool that originally came from the Harvard School of Business. For that purpose, each technology from the various plans is rolled up by product. The per product risk score is the sum of the risk scores for that product. A product gets penalized by a risk score, if even a single one of its repos still is using or dependent on the deprecate, migrate, or remove technology. That risk score is counted only once, even if several repos are out of compliance. The median of these per product risk score aggregates is what gets recorded in the balanced scorecard. It makes sense to use automated static code analysis on your repositories in determining technology dependencies. You will also need good support for CI/CD, DevOps, and GitOps in order to easily and reliably calculate this metric. We also calculate the TCP risk score in a different way in order to help focus the teams for each product. In this metric, each technology from the plans is rolled up by repo. The per repo risk score is the sum of the risk scores for that repo. The aggregate risk scores for the repos for a product are summed up as the aggregate risk score for the product itself."
      #+end_quote
