:properties:
:id:       72D44577-0588-47DF-AFD2-9EA5692E5883
:end:
#+title: 2024-08-30
#+date: 2024-08-30
#+filetags: journal

* LdN 392: Spezial: Wie geht wirksame Klimapolitik? (Jens Beckert, Max-Planck-Institut für Gesellschaftsforschung) ([[https://plus.lagedernation.org/2024/08/08/spezial-wie-geht-wirksame-klimapolitik-jens-beckert-max-planck-institut-fuer-gesellschaftsforschung/][link]])
** Zusammenfassung
*** Erbschaftssteuer und soziale Ungleichheit
**** Vermögenskonzentration und soziale Mobilität
Hauptprobleme:
- Zunehmende Vermögenskonzentration
- Mangel an sozialer Mobilität
- Dynastische Vermögensweitergabe

Lösungsansätze:
- Höhere Erbschaftssteuer für sehr große Vermögen
- Investitionen in Bildung zur Förderung der Chancengleichheit
- Neugestaltung des gesellschaftlichen Narrativs

Zitate:

#+begin_quote
"Wir haben bei einem vermuteten Erbschaftsvolumen von jährlich um die 400
Milliarden € jährliche Erbschaftssteuer Einnahmen von unter 10 Milliarden €."
#+end_quote

#+begin_quote
"Dass wir Erbschaftssteuern eben nicht mehr primär sehen als Eingriff in die
Familien oder als Ausdruck von Neid oder als Behinderung von wirtschaftlichen
Aktivitäten, sondern dass wir sie sehen vor der Problematik, dass eine
Gesellschaft, die in die Vermögensperpetuierung nicht eingreift, sich immer
stärker verknöchert."
#+end_quote

**** Öffentliche Wahrnehmung und Widerstand
Hauptprobleme:
- Öffentlicher Widerstand gegen Erbschaftssteuer
- Missverstehen der tatsächlichen Betroffenheit
- Fehlende Unterstützung in der breiten Bevölkerung

Lösungsansätze:
- Bessere Kommunikation der tatsächlichen Auswirkungen
- Fokus auf lokale Initiativen und konkrete Vorteile
- Betonung der gesellschaftlichen Vorteile von Umverteilung

Zitate:
#+begin_quote
"Es ver\u00e4ndert an dem Ergebnis ganz wenig. Und es ist tats\u00e4chlich aus
der sozialwissenschaftlichen Perspektive ungeheuer schwer zu verstehen das
Ph\u00e4nomen. Weshalb also die Interessenlage, wir haben ja eine demokratische
Mehrheit von was wei\u00df ich, 98\u00a0% der W\u00e4hler, die von einem Gesetz
profitieren w\u00fcrden. Warum setzen die sich da nicht durch?"
#+end_quote

**** Gesellschaftlicher Wandel und Wertvorstellungen
Hauptprobleme:
- Verschiebung vom Staat zur Familie als Sicherheitsgarant
- Spannung zwischen Individualismus und kollektiver Verantwortung
- Mythos der Leistungsgesellschaft

Lösungsansätze:
- Neuausrichtung des Verhältnisses zwischen Individuum und Gemeinschaft
- Betonung der Interdependenz von Individuen und Gesellschaft
- Kritische Auseinandersetzung mit dem Leistungsprinzip

Zitate:

#+begin_quote
"Also dass wir in einer Gemeinschaft oder in einem sozialen Kollektiv leben, in
dem auch die Individuen, die Einzelnen ihre Leistungen nur bringen können in
einem sozialen Kontext, den sie nicht selbst erstellen und insofern immer ist,
eine Verbindung gibt zwischen dieser Gemeinschaft und den Individuen."
#+end_quote

#+begin_quote
"Ich denke, dass ein solches Bild der Verbindung von Kollektiv und Individuum
letztendlich das ist, was wir als Gesellschaftsmodell verständlich machen."
#+end_quote

**** Politische und praktische Umsetzung
Hauptprobleme:
- Mangelnde politische Priorität für Erbschaftssteuerreform
- Schwierigkeiten bei der Umsetzung von Umverteilungsmaßnahmen
- Lobbyismus und Interessenkonflikte

Lösungsansätze:
- Fokus auf konkrete, lokale Projekte (z.B. Klimaanpassung)
- Nutzung von Erbschaftssteuereinnahmen für sichtbare Verbesserungen (z.B. Bildung)
- Stärkere Einbindung der Zivilgesellschaft

Zitate:
#+begin_quote
"Mir geht es um die Frage: Wie kann man die Akzeptanz für Klimaschutz und
Klimapolitik allgemein erhöhen?"
#+end_quote

#+begin_quote
"Also mein Grundgedanke ist zunächst einmal, dass wir uns anfreunden müssen mit
der Idee, dass wir dieses Problem nicht in angemessener Weise lösen werden."
#+end_quote
*** Klimapolitik und CO2-Emissionen
Hauptprobleme:
- Schwierigkeiten bei der Umsetzung effektiver Klimaschutzmaßnahmen
- Widerstand gegen CO2-Bepreisung
- Ungleiche Verteilung der Kosten für Klimaschutzmaßnahmen

Lösungsansätze:
- Fokus auf lokale Klimaanpassungsprojekte
- Verknüpfung von Klimaschutz mit konkreten Vorteilen für die Bevölkerung
- Bessere Kommunikation der Notwendigkeit und Vorteile von Klimaschutzmaßnahmen

Zitate:
#+begin_quote
"Wir haben heute eine CO2 Bepreisung, die weltweit also überhaupt nur etwas über
20% der Emissionen umfasst. In der Europäischen Union sind es 40%, etwas über
40%."
#+end_quote

#+begin_quote
"Wenn die Ergebnisse von Klimapolitik konkret als Vorteil erfahrbar sind, dass
dann eine größere Zustimmung der Menschen erwartet werden kann als in einer
Situation, in der in einem ganz abstrakten Sinne ja zum Klimaschutz beigetragen
werden soll."
#+end_quote

**** Technologischer Wandel und Energiewende
Hauptprobleme:
- Herausforderungen bei der Umstellung auf erneuerbare Energien
- Neue Umweltprobleme durch technologischen Wandel (z.B. Lithiumproduktion)
- Unsicherheiten bezüglich zukünftiger Technologien und deren Auswirkungen

Lösungsansätze:
- Investitionen in Forschung und Entwicklung nachhaltiger Technologien
- Berücksichtigung der gesamten Lieferkette bei der Bewertung von Technologien
- Förderung von Innovationen im Bereich CO2-Entnahme aus der Atmosphäre

Zitate:
#+begin_quote
"Also nehmen Sie nochmal das Beispiel Heizungsgesetz. Ich baue eine Wärmepumpe
ein, damit reduziere ich ein wenig den CO2 Ausstoß von mir, klar, aber was trage
ich eigentlich damit zur Lösung des Gesamtproblems bei?"
#+end_quote

#+begin_quote
"Aber wie sieht das aus, wenn das Geld dafür ausgegeben wird, dass sagen wir mal
für den Hochwasserschutz etwas bei mir vor Ort getan wird und ich erleben kann,
dass beim nächsten Hochwasser tatsächlich der Ort, in dem ich lebe, besser
geschützt ist."
#+end_quote
