:PROPERTIES:
:ID:       7BAE6878-45EB-4DFE-BDE0-44E488C5F146
:END:
#+TITLE: 2025-04-09
#+DATE: 2025-04-09
#+FILETAGS: journal

- The [[https://www.thecoder.cafe/p/100-go-mistakes][story]] behing [[id:76028904-9a38-4aad-ad9c-9f4f990e92b3][100 Go Mistakes and how to avoid them]]
  #+begin_quote
  In terms of royalties, I got paid 10% on all sales. On one hand, yes, that’s not a lot.
  Yet, you really have to understand how helpful a publisher can be for a first-time
  “author” with zero experience like I was back then, for two main reasons:

  First, and we will go over the process later, but the number of reviews from different
  people is insane. If I had written the book completely on my own, I can guarantee the
  quality would have been way lower.

  Second, in terms of visibility, going with a publisher helps a lot, especially if, like me
  back then, you had around 400 followers on Twitter. Sure, content can still go viral
  without a big audience, but it’s a lot less likely.

  When I signed the contract, I also received an advance: $2,000 upfront, and $2,000 after
  delivering one-third of the book.
  #+end_quote
  #+begin_quote
  To this day, I’ve earned around $47,000 from the book (before taxes). If I consider the
  time spent, using a conservative lower bound of 2,000 hours, that comes out to about $23
  per hour.
  #+end_quote
- 2025-04-09 ◦ [[https://pagefind.app/docs/][Getting Started with Pagefind | Pagefind — Static low-bandwidth search at scale]]

